---
title: "Another Corrective to the Conventional Crisis Narrative"
date: "2011-06-03"
categories: ["Economics", "Financial Markets"]
---

I recently [reviewed](http://www.institutional-economics.com/index.php/section/reviews) the outstanding [Guaranteed to Fail](http://www.amazon.com/dp/0691150788/ref=as_li_tf_til?tag=institutional-20&camp=0&creative=0&linkCode=as1&creativeASIN=0691150788&adid=008NDJBTQ8KFYRABFBX5), perhaps the best book written about the financial crisis. In the WSJ, [James Freeman](http://online.wsj.com/article/SB10001424052702303745304576361531730887312.html) reviews [Reckless Endangerment](http://www.amazon.com/dp/0805091203/ref=as_li_tf_til?tag=institutional-20&camp=0&creative=0&linkCode=as1&creativeASIN=0805091203&adid=04AGKQ4H1E02WW5VFNQC) by Pulitzer Prize-winning journalist Gretchen Morgenson and analyst Joshua Rosner. It reinforces the argument I made in my review of Guaranteed to Fail that the conventional crisis narrative is a (largely successful) attempt on the part of officialdom to divert attention from their culpability for the crisis:

> In Ms. Morgenson and Mr. Rosner’s book, a bipartisan parade of famous Washington movers-and-shakers appear in cameos to do some disservice (now largely forgotten) to taxpayers. There is Newt Gingrich lauding Fannie Mae at a corporate event. There is Larry Summers bullying his Treasury staff to water down a report critical of Fannie. There is current World Bank President Robert Zoellick as a Fannie executive in the 1990s lobbying on Capitol Hill.
>
> Look at Rep. Barney Frank, responding in 2005 to the question of whether the government’s push to increase home-ownership rates might result in people buying more home than they could afford and putting themselves in dire straits. The authors report: “Frank brushed off the questioner. ‘We’ll deal with that problem if it happens,’ he barked.”
>
> It happened all right, and perhaps the most amazing part of this tale is that so many of those responsible for the disaster remain in power.

A catastrophic failure of democratic accountability.
