---
title: "Auctioning Permanent Migration Rights: Friedman Agreed"
date: "2011-10-27"
categories: ["Economics", "Population & Migration"]
---

My recent [proposal](http://www.cis.org.au/publications/policy-monographs/article/3503-hands-mouths-and-minds-three-perspectives-on-population-growth-and-living-standards) to auction the right to permanently migrate to Australia was not new. I was treading a path already worn by Gary Becker and Julian Simon in the US, and Mark Harrison, John Logan and Wolfgang Kasper in Australia.

My proposal provoked predictable outrage from those unwilling to think about the idea for more than five seconds. The outrage is partly due to the failure to understand that an auction scheme is designed to facilitate migration, not prevent it. Wolfgang Kasper emailed me this recollection of his experience trying to sell the idea at a conference of economists in San Francisco:

> It was a gathering of like-minded friends and some very prominent economists. We had been told that Milton and Rose \[Freidman\], who lived in their apartment nearby, would come to a morning session, when Milton (now 89) was fresh….Before long, Milton was in the midst of the debate, debunking some idea or elaborating and extending someone else’s. He was in fine form! At morning tea, we expected to say goodbye, but they said they had come for the day! “Rose and I are not a monument,” he said. “This is exciting work, it’s an elixir for Milton to mix with you people,” said Rose…
>
> At one stage of the conference, when I spoke about the idea of selecting immigrants by worldwide auction, I was attacked by R. Rubin, a former Clinton Minister of Labor. He disagreed with me violently… “You just want to sell passports!” I had of course worked on this question in a consultancy report for New Zealand and stood my ground. Our argument became, in my opinion, a distraction to the main topic of our session. Friedman intervened: “I am sure that everyone here has understood Dr. Kasper’s rationale, and I agree with him. Robert, why don’t you think it over overnight. Give me a ring in the morning if you still disagree and I’ll buy you and Wolfgang the best breakfast in town, so we can argue it out some more!” This was vintage Friedman. Alas, Rubin never came back with his counterarguments, and I never was bought breakfast by Friedman.
