---
title: "Fed Glasnost: Australia’s Media Shouldn’t Settle for Less"
date: "2011-04-21"
categories: ["Economics", "Monetary Policy"]
---

If it’s good enough for [Ben Bernanke](http://online.wsj.com/article/SB10001424052748704740204576273603698504140.html), it’s good enough for Glenn Stevens:

> Next Wednesday, Federal Reserve Chairman Ben Bernanke will do something no Fed chief has done before: Stand before a room full of journalists after officials conclude a policy meeting and answer questions about the central bank’s decisions…
>
> Fed officials have been preparing carefully, according to people familiar with the process. Mr. Bernanke spent a recent weekend watching videos of European Central Bank President Jean-Claude Trichet and Bank of England chief Mervyn King, parrying reporters’ questions at their regular press conferences.
>
> In February, on the sidelines of a meeting of financial officials in Paris, Mr. Bernanke quizzed Mr. Trichet and other European central bankers on how they manage their press conferences. He’ll do dress rehearsals, with staffers peppering him with questions, as the briefing nears.
>
> Mr. Bernanke’s staff, meanwhile, has spent weeks scripting the mechanics of how the press conference will work.
>
> He will hold his briefing in a big top-floor conference room at the Fed’s Martin building, opposite the central bank’s main cafeteria, where Mr. Bernanke can sometimes be found wandering, tray in hand, to chat with staffers…
>
> In the past month alone, 16 different Fed policy makers have given more than 40 formal addresses, in addition to television, newspaper and newswire interviews. They espouse different views, not only on when to reverse the Fed’s easy-money policies, but how.

As I noted in this [op-ed](../2009/no_time_for_a_media-shy_central_banker.qmd), post-Board meeting and post-CPI press conferences by the RBA Governor would change for the better the media dynamics around inflation and interest rates in Australia.
