---
title: "Be Careful What Jim Grant Wishes For"
date: "2011-07-19"
categories: ["Economics", "Financial Markets", "Gold"]
---

A gold standard won’t do [what Jim Grant says it will](http://uneasymoney.com/2011/07/18/gold-and-ideology/):

> Supporters of the gold standard like to point out that since creation of the Fed in 1913 the dollar has lost 95% of its value.  Well in 1913, the dollar was convertible into an ounce of gold at \$20.86 an ounce.  So while the dollar has lost 95 percent of its value, gold has appreciated even more rapidly than the dollar has depreciated.  If gold had kept its value in 1913, its value today would be somewhere between \$400 and \$500 an ounce.  Accept for argument’s sake the claim of supporters of the gold standard that the recent run up in the value of gold was caused by a loss of confidence in the dollar.  Would it not be reasonable to conclude from that assumption that if the dollar were made convertible into gold, people would then start selling off their gold, the threat of dollar depreciation having been eliminated?
>
> But wait.  If people started selling off their gold, the value of gold would decline.  If the real value of the gold fell from its current value back to its value in 1913 when the dollar was convertible into gold at \$20.86, the value of would lose two-thirds to three-quarters of its value.  We are talking about two or three hundred percent inflation.  Does that make feel more confident about the value of your savings?
