---
title: "Bernanke is Not a ‘Money Printer’"
date: "2011-03-14"
categories: ["Economics", "Financial Markets", "Monetary Policy"]
---

Frederic Mishkin is in Australia and will be presenting at the Reserve Bank on Thursday. He was interviewed by Alan Kohler for [Inside Business](http://www.abc.net.au/insidebusiness/content/2011/s3162678.htm):

> ALAN KOHLER: So therefore do you join those who call Ben Bernanke a money printer?
>
> PROFESSOR RICK MISHKIN: No, so… I don’t at all. The purpose here is not to print money and to just not worry about future inflationary consequences.
>
> There is, however, an issue that when you have a balance sheet which is this large - and particularly in long-term assets and even more so in housing assets - the Fed is now involved in the most politicised of all financial markets in the US. The Federal Reserve and also the government has been involved in very large transactions to help the economy and bail outs.
>
> The government’s not going to lose a penny on everything but one - the Fannie and Freddie, a couple \[sic\] of hundred billion dollars. So again, this is an indication of how crazy some of our policies have been.
>
> Economists didn’t get - we missed a lot of things in this crisis, we got a lot of things wrong. Much to trusting for example of the quality of prudential supervision, which by the way in your country was done much, much better than in many other places, so you know, I don’t know whether you’re just lucky or good but…
>
> ALAN KOHLER: Good!
