---
title: "Budget Needs Micro Not Macro Focus"
date: "2011-04-13"
categories: ["Economics", "Financial Markets", "Fiscal Policy"]
---

I have an op-ed in [The Australian](http://www.theaustralian.com.au/national-affairs/commentary/trimming-to-fit-budgets-reduced-revenue/story-e6frgd0x-1226038104396) arguing that federal budget debates need a stronger micro rather than macro focus:

> A good indicator of the macroeconomic importance of the budget is the reaction of financial markets on budget night. More often than not, the market reaction is minimal, highlighting the irrelevance of the change in the budget balance to economic growth and macro variables such as interest rates.
>
> The real economic significance of the budget is its microeconomic implications: how tax and expenditure policies influence incentives to work, save and invest. Tax and spending policies should be evaluated based on the incentives they create, for better or worse.

As if to prove my point, Shadow Treasurer [Joe Hockey](http://www.theaustralian.com.au/national-affairs/commentary/rapid-return-to-surplus-needed/story-e6frgd0x-1226038097530) has an op-ed on the same page arguing that the budget should be judged solely on the basis of the surplus.

The Centre for Independent Studies has also released my Policy Monograph [Why Does Government Grow?](http://cis.org.au/images/stories/policy-monographs/pm-117.pdf)

Economic Papers has published the papers from the symposium on Monetary and Fiscal Policy Interactions: How to Improve Policy Outcomes held at the 2010 Conference of Economists. My contribution can be found [here](../../files/ecpa_098.pdf).
