---
title: "Budget Office Helps Pollies, Not Punters"
date: "2011-05-20"
categories: ["Economics", "Fiscal Policy", "Politics"]
---

I have a piece at the ABC’s [Drum Unleashed](http://www.abc.net.au/unleashed/2721450.html) on the proposed federal Parliamentary Budget Office. Here’s my conclusion:

> Policy costings should be a low priority for the PBO or any other independent fiscal authority. Were we really any the wiser for the 128 policy costings released by Treasury and Finance for the 2010 federal election, the work of some 300 public servants? Hands-up if you can recall the conclusion of even one?
>
> The new federal PBO’s focus should instead be on the analysis of overall fiscal strategy and long-term fiscal sustainability. The PBO will not end partisan disputes over competing policies. But it could serve a useful purpose if it injects some realism into debates over costings. To do this, it will need the independence to scrutinise and contradict, rather than just recycle, the work of Treasury and Finance. Whether the PBO is given the necessary freedom to do so remains to be seen.
