---
title: "Chinese Perspectives on Investing in Australia"
date: "2011-06-24"
categories: ["Economics", "Foreign Investment"]
---

With Sinosteel [pulling the plug](http://www.theaustralian.com.au/business/sinosteel-move-may-sink-6bn-oakajee-port-and-rail-project/story-e6frg8zx-1226080893160) on a \$2bn iron ore mine, the Lowy Institute has come out with a timely survey of [Chinese Perspectives on Investing in Australia](http://www.lowyinstitute.org/Publication.asp?pid=1616). The Lowy analysis highlights the role of government policy in causing confusion among Chinese investors. It singles out what it calls ‘public (but undocumented) comments in 2009 by a FIRB official.’ I assume the author means [these comments](http://www.theaustralian.com.au/news/opinion/more-inscrutable-than-the-chinese/story-e6frg6zo-1225831954203), which are now on the public record following an FOI request.

The Lowy analysis is disappointing in arguing that if the FIRB did not exist, we would have to invent it. It even suggests setting up a FIRB presence in China. Given that the Treasurer has sought to regulate Australian FDI in China through some of the conditionality imposed on Chinese acquisitions in Australia, that would be perversely appropriate.  It seems that geography is no boundary to the Treasurer’s discretion. Australia’s dysfunctional regulatory regime for FDI is a problem not only for Chinese investors, but for anyone engaged in cross-border acquisitions of Australian equity capital.
