---
title: "CIS Liberty & Society Student Conference"
date: "2011-08-17"
categories: ["Classical Liberalism"]
---

CIS is seeking applications for its [Liberty & Society Student Conference](http://www.cis.org.au/student-program/liberty-and-society-student-conferences):

> Liberty and Society is a unique conference program for undergraduates, postgraduates and recent graduates over the age of 18 who live in Australia, New Zealand or the South Pacific. The goal of the Liberty and Society conferences is to create an intellectual environment where ideas and opinions about what makes a free society can be discussed, argued and learnt.
>
> Liberty and Society is for young people who may be questioning the standard answers they are getting regarding social, political and economic issues. You may not see yourself as a fitting into the ‘left’ or ‘right’ mould. This is an opportunity to consider the classical liberal perspective. Classical liberalism promotes individual freedom, private property, limited government and free trade.
>
> Students from every Australian state and New Zealand attend. Formal and informal discussions on economics, political thought, law and social policy dominated the weekend interspersed with arguments about foreign policy, education and politics. Generous scholarships allow everyone to apply.
>
> Join us for an intellectual experience that may change the way you think about the world.
