---
title: "Conservatives and Libertarians for Dumping the Gold Stock"
date: "2011-05-17"
categories: ["Commodity Prices", "Economics", "Financial Markets", "Fiscal Policy", "Gold"]
---

We have previously noted the irony of those who worry about an over-supply of fiat money taking refuge in a commodity in which governments hold stocks that dwarf annual production. We also noted that the pro-free trade social democrats at the [Petersen Institute](http://www.piie.com/publications/opeds/oped.cfm?ResearchID=1681) had suggested liquidating the US gold stock to reduce US government debt and interest payments.

Now [conservative and libertarian US think-tanks](http://www.washingtonpost.com/national/economy/us-should-sell-assets-like-gold-to-get-out-of-debt-economists-say/2011/05/12/AFIvmI4G_story.html) are saying it too. It is consistent with their long-standing support for the privatisation of government assets. Of course, it is a lazy approach to debt reduction, but a lazy debt reduction is better than none.

Dumping the gold stock without tanking the gold price is easier said than done, but the RBA was able to discretely offload 167 tonnes in 1997, yielding a handsome profit on the old Bretton Woods parity price and adding income producing assets to the RBA’s portfolio ([contrary to Paul Cleary’s FOI beat-up](../2011/the_rba_didnt_lose_5bn_on_its_1997_gold_sales.qmd)).

In Australia, sales of public trading enterprises Qantas, Telstra, CBA and the airports yielded \$61 billion during the 1990s and 2000s, making a large contribution to the reduction in net debt from \$96 billion in 1996-97 to a negative net debt position in 2005-06 before the terms of trade boom really took off. Peter Costello knew a lazy policy option when he saw one. One of the problems facing the current government is that it has to do debt reduction the hard way. And the gold stock’s long gone.

UPDATE: Portugal is under pressure to [sell its Nazi gold back to Germany](http://online.wsj.com/article/SB10001424052748703509104576326880547925262.html).
