---
title: "Cranks of the 1930s: Marion King Hubbert"
date: "2011-09-18"
categories: ["Economics", "Oil"]
---

[Daniel Yergin](http://online.wsj.com/article/SB10001424053111904060604576572552998674340.html) on Marion King Hubbert, the original peaknik:

> Marion King Hubbert was one of the most eminent—and controversial—earth scientists of his time. Born on a ranch in San Saba, Texas in 1903, he did his university education, including his Ph.D., at the University of Chicago. One of his fundamental objectives was to move geology from what he called its “natural history phase” into its “physical science phase,” firmly based in physics, chemistry and, in particular, rigorous mathematics.
>
> In the 1930s, while teaching at Columbia University, Hubbert became active in a movement called Technocracy and served as its educational director. Holding politicians and economists responsible for the debacle of the Great Depression, Technocracy promoted the idea that democracy was a sham and that scientists and engineers should take overthe reins of government and impose rationality on the economy. “I had a boxseat at the Depression,” Hubbert later said. “We had manpower and raw materials. Yet we shut the country down.”
>
> Technocracy envisioned a no-growth society and the elimination of the price system, to be replaced by the wise administration of the Technocrats. Hubbert believed that a “pecuniary” system, guided by the “hieroglyphics” of economists, was the road to ruin.
