---
title: "Data versus Anecdote on Foreign Acquisitions in Agriculture"
date: "2011-09-12"
categories: ["Economics", "Foreign Investment"]
---

The debate over foreign acquisitions of both agricultural and urban land has been driven by anecdote rather than data. Some high profile acquisitions have gained considerable media attention, but this has obscured the underlying reality that Australia’s broadacre, dairy and other farms remain overwhelmingly Australian-owned.

The Australian Bureau of Statistics (ABS) and the Rural Industries Research and Development Corporation (RIRDC) have been engaged in a data gathering exercise to measure the level of foreign ownership in Australian agriculture. As of 31 December 2010, [the ABS finds that](http://www.abs.gov.au/AUSSTATS/abs@.nsf/Latestproducts/7127.0Media%20Release1December%202010?opendocument&tabname=Summary&prodno=7127.0&issue=December%202010&num=&view=):

99% of agricultural businesses in Australia were entirely Australian owned;\
89% of agricultural land was entirely Australian owned; and\
91% of water entitlements for agricultural purposes were entirely Australian owned

This helps put the current debate in proper perspective. Foreign investment in agriculture [should be welcomed](http://www.cis.org.au/media-information/opinion-pieces/article/3190-foreign-investment-will-boost-food-security), but agriculture in Australia is likely to remain overwhelmingly Australian-owned.
