---
title: "De-Occupying Greg Mankiw"
date: "2011-11-04"
categories: ["Economics"]
---

At the beginning of my first Economics I lecture at ANU in 1986, the lecturer told us that for the next three years we would be studying neo-classical economics. He helpfully suggested if we were interested in other schools of economic thought, we might want to enrol at another university. He went on to point out the significant earnings premium that ANU economics graduates then earned in the labour market. The implication was that these two facts were not unrelated. Not that we needed to be told. This is exactly what many of us had signed-up for. The subject had a 45% failure rate.

If the idea was to indoctrinate students, it failed in my case. I don’t consider myself a neo-classical economist, more a heterodox institutionalist, although I accept many fundamental neo-classical insights. You first have to study neo-classical economics to understand what you reject and why. Too many dismiss neo-classical economics without ever having understood it other than as a caricature.

This would seem to be the case with those students who staged a walk-out from Greg Mankiw’s class at Harvard, judging by their very silly [open letter](http://hpronline.org/campus/an-open-letter-to-greg-mankiw/?mid=51). Having taught from Mankiw’s introductory and intermediate texts, I can vouch for the fact that they are very balanced in their approach, as a good textbook should be. I teach from Cowen and Tabarrok’s principles text, which is more Hayekian than neo-classical, yet still very balanced. For example, it makes a conditional case for activist fiscal policy I would reject, but it is important that students understand the thinking behind such policy.

It is far from clear what Mankiw’s critics want taught instead, but I suspect it is not economics.
