---
title: "ERA and Economic Papers"
date: "2011-03-17"
categories: ["Economics"]
---

A letter to contributors from the editor of Economics Papers, Harry Clarke, can be found below the fold.

Dear Contributor to Economic Papers,

The ARC will review the Excellence in Research for Australia rankings assigned in 2010 during an initial consultation period running to 4 April, 2011.  Economic Papers urgently needs your help on this matter by making a representation to the ARC before this deadline. \
Submissions from contributors carry specific weight beyond that of the Editor and Editorial Board.\
My request to you is to go the website [https://roci.arc.gov.au/](https://institutional-economics.com/?URL=https%3A%2F%2Froci.arc.gov.au%2F) to make an appeal for Economic Papers to (i) be given an A ranking and (ii) for the criteria that determine high rankings to be extended to include applied Australian economic research.  You need to go to this hyperlink, enter some data. You will then receive an email which tells you how to make a submission.  Entering more data and clicking on “Search Ranked Outlets” after entering “Economic Papers” as the title will get you to the point where a submission can be made by clicking on “Comment on this Outlet”.\
The two main questions you will be asked to comment on: (i) Why you are qualified to comment/ and (ii) What evidence you have to support an improved ranking?\
As background to my request Economic Papers is currently ranked a B level journal and needs to go up ranking A journal status if it is to have a secure future.  It is only journals that rank A or A\* that contribute to university rankings in Australia which drive research funding and which are hence a major driver of choice of publication.  This is a severe general problem for work in the applied social sciences in Australia since few applied journals have a ranking A or A\*.\
For economics this creates a severe bias against doing applied economic research on the Australian economy.  In my view not only should such research be given prominence but it should be given the highest prominence.  As a profession this i8s exactly the sort of work Australian economists should be doing. \
Can I remind you of some of the changers that have occurred in the operation of Economic Papers over the past two years?\
• The formation of an editorial board comprising some of the best economists in Australia both in the universities and in the public sector.\
• The use of an international publishing house (Wiley-Blackwell) and the development of a rigorous, anonymous referring process by peer review.\
• The publication of high quality applied economic research in a wide range of areas.  To name a few – Australia and the GFC,  reforming Australian excises on alcohol,  Australian climate change issues,  reform of the Australian health system, population aging economics, the Future Fund,  contingent valuation of the environment,  Australia Post and so on. I selected this list from two recent issues – the list is broader than this. \
Please reflect on what Economic Papers has delivered over the past couple of years.  I think it is now a high quality publication.  I cannot believe that research into the Murray Darling Basin water problems or problems of the GFC for Australia should be actively discouraged as research endeavours and yet this will be the effect of retaining a B ranking.  Please help.

Best wishes,

Harry
