---
title: "‘Everybody’s Money’s the Same Colour to Us’"
date: "2011-08-27"
categories: ["Economics", "Foreign Investment"]
---

[Australian farmers](http://www.theaustralian.com.au/news/nation/farmers-go-against-grain-on-land-ownership/story-e6frg6nf-1226123177343) don’t want a bar of scare-mongering by the Farmers Federation:

> farmers such as Simon Tiller have a clear message to any foreigner interested in his multi-million-dollar operation: come on down.
>
> The 29-year-old father of two would not say where the “considerable overseas interest” was coming from for his \$15.5 million wheat, barley and canola concern east of Esperance, 700km southeast of Perth, but he is adamant foreign investment is pivotal to keeping Australian agriculture strong and productive.
>
> “Can you imagine the mining industry getting off the ground without foreign investment? It’s a sophisticated global economy and we need to keep pace,” he told The Weekend Australian.
>
> While the West Australian Farmers Federation has warned about the dangers of “large-scale Chinese ownership” following moves on Australia’s sugar industry and rumours China was seeking 80,000ha of WA farmland, grain producers such as Mr Tiller around Esperance won’t have a bar of any “scaremongering”...
>
> Foreign investment was good for farmers who wanted to sell - it gave them an out - and those that didn’t as it “kept values rising”.

I make related arguments in this [op-ed](../2011/i_dont_like_it_australias_hansonite_political_class.qmd).
