---
title: "Five More Years"
date: "2011-01-17"
categories: ["Economics", "Financial Markets", "Monetary Policy"]
---

[Peter Martin](http://www.petermartin.com.au/2011/01/memo-to-swan-mckibbins-bird-in-hand.html "Peter Martin") rounds-up opinion in favour of re-appointing Warwick McKibbin to another five-year term on the Reserve Bank Board, including some supportive comment from me.

As [Chris Joye](http://christopherjoye.blogspot.com/2011/01/great-article-by-peter-martin-on-why-we.html "Chris Joye") notes, there is no reason why Ross Garnaut could not be appointed to one of the other looming vacancies on the Board, allowing both Warwick and Ross to serve concurrently. That would certainly liven-up Board meetings and move the Board closer to an MPC-style model of decision-making. The government should eventually move to separate monetary policy decision-making from the Board, as I argue in this [article](../../files/ANewErafortheRBA.pdf "article").

In the UK, the government was brave enough to appoint an American, Adam Posen, to the BoE’s MPC. The logistics of having a foreigner other than a kiwi attending monthly RBA Board meetings would be difficult, and the local media reaction would be nothing short of hysterical, but there is no reason why foreign talent should not be considered. A foreigner would actually be significantly less conflicted as a monetary policy decision-maker than many of the existing external Board members.

While my first foreign pick would be Don Brash, my guess is he would be unwilling to serve under the existing RBA governance model. All the more reason to change it.
