---
title: "How New Zealand Turned Away IKEA"
date: "2011-06-02"
categories: ["Economics", "Foreign Investment"]
---

In contrast to the Australian Treasury, the [Acting Secretary of the New Zealand Treasury](http://www.nbr.co.nz/article/treasury-drop-all-screening-foreign-investment-ck-94649) injects some sense into the debate over foreign direct investment:

> Acting Secretary to the Treasury Gabriel Makhlouf has hit out at critics of foreign investment in New Zealand, saying Treasury has consistently recommended removing all screening.
>
> The British civil servant who arrived in this country 15 months ago told the New Zealand Institute of International Affairs that lowering foreign investment would be counter-productive to growth ambitions.
>
> Small, high productivity economies relied heavily on international connections of people, capital, trade and ideas, he said.
>
> He advocated the reduction of costs and distortions associated with capital inflows, particularly tax.
>
> “If we are to continue to screen foreign investment, and Treasury has consistently recommended removing all screening, it needs to be kept to a minimum and under constant review,” he said.
>
> “Some of you might have followed the story of the big Swedish furniture outlet called IKEA, and its attempts to find a site for a store in the North Island,” Mr Makhlouf said.
>
> The company ran into so many obstacles that it eventually abandoned its plans to establish a New Zealand branch. Domestic policy settings relating to roading infrastructure, the Environment Court process and the approach of the local council managed to sink IKEA’s plans.

The UK has one of the world’s most liberal FDI regimes, so the New Zealand regime must have come as a surprise to Makhlouf.
