---
title: "How to Respond to the Terms of Trade Boom"
date: "2011-09-02"
categories: ["Economics", "Foreign Investment", "Free Trade & Protectionism", "Population & Migration"]
---

From this week’s [Ideas@theCentre](http://cis.org.au/publications/ideasthecentre/article/3459-how-to-respond-to-the-terms-of-trade-boom):

Listening to some commentators, you could be forgiven for thinking that the terms of trade boom was the worst thing that ever happened to the Australian economy.

Relative to what we pay for our imports, Australia now gets higher prices for its exports than at any time since at least 1870. This was illustrated by Reserve Bank Governor Glenn Stevens’ observation that ‘five years ago, a ship load of iron ore was worth about the same as about 2,200 flat screen television sets. Today it is worth about 22,000 flat-screen TV sets.’

This increased international purchasing power is attributable not only to rising commodity prices, but also lower prices for imports, not least manufactured goods. The flip side of Australia’s terms of trade boom is the collapse in the terms of trade for countries like Japan.

It wasn’t supposed to be this way. In the 1950s, economists Raúl Prebisch and Hans Singer argued that manufactured goods prices would enjoy a secular rise relative to commodity prices and that developing countries should engage in activist industrial policy and import substitution to avoid a declining terms of trade. The same argument has long been made in Australia, but would have had disastrous consequences if its policy prescriptions had been followed in response to previous terms of trade slumps.

Julian Simon would certainly agree with the proposition that real commodity prices should decline in secular terms, but he also noted the broader gains in real purchasing power from increased productivity and declining real prices for manufactured goods. It is fair to say that Simon would have been agnostic on any trend in their relative prices.

The terms of trade boom came about in part because it was unexpected, not least by the mining industry itself. It underinvested in the 1990s, partly because of implicit acceptance of the Prebisch-Singer hypothesis on the part of many investors. Historical experience highlights the danger of conditioning public policy on assumptions about the future direction of relative prices for traded goods.

Our best response to the terms of trade boom is to become even more open to inflows of foreign labour and capital and to reduce the government’s command over resources so that the mining industry can expand with less pressure on other sectors. While the non-mining sectors will contract relative to mining, they can still expand in absolute terms if we continue to remove government-imposed resource constraints to overall economic growth.
