---
title: "How the ACCC Doomed ASX"
date: "2011-01-27"
categories: ["Economics", "Financial Markets", "Foreign Investment"]
---

[Maurice Newman](http://www.theaustralian.com.au/news/opinion/say-yes-to-singapore-merger-or-risk-irrelevance/story-e6frg6zo-1225995058830) on a fateful decision:

> When, in 1998, the Australian Competition and Consumer Commission rejected ASX’s bid for the Sydney Futures Exchange, it consigned ASX to a non-independent future. In the seven years it took for the ACCC to finally approve the merger, most of the bigger stock exchanges in our region and some outside it had emulated Australia’s aborted lead. This robbed ASX of a significant first mover advantage, depriving it of scale and scope and an unrepeatable regional leadership position.
>
> There can be no doubt that the 2006 merger of ASX and the Sydney Futures Exchange, when it came, was a huge benefit to both markets and to Australian financial services generally, but it came too late to fully leverage this success internationally.
