---
title: "How the Financial Crisis Inquiry Commission Suppressed Dissent"
date: "2011-07-16"
categories: ["Economics", "Financial Markets"]
---

Peter Wallison [responds](http://www.aei.org/article/103867) to the Report of the Democratic Staff of the House Oversight and Government Reform Committee:

> *The report of the Democratic staff of the House Committee on Oversight and Government Reform—although it attempts to call my conduct into question as a member of the Financial Crisis Inquiry Commission—actually indicts the Commission. The facts are these. From the outset of its “investigation” the Commission’s chair, Phil Angelides, was intent on reporting that the financial crisis was caused by greed, misconduct and lack of regulation of the private sector, exculpating government housing policy from any significant responsibility. Evidence of this can be seen in the fact that in December 2009—before any investigation had been done—Angelides handed the commission members a list of hearings that the Commission would hold over the succeeding 8 months. Those hearings focused on the private sector’s role in the financial crisis, and paid scant attention to the government’s role. This was fully in accord with the interests of the House and Senate Democrats, who were intent on establishing this narrative as a basis for enacting the Dodd-Frank Act, which sought to impose substantial new regulation on the U.S. financial system.*
