---
title: "‘I Don’t Like It’: Australia’s Hansonite Political Class"
date: "2011-07-02"
categories: ["Economics", "Foreign Investment"]
---

I have an op-ed in today’s AFR arguing that Australia’s politicians are united as much by a desire to meddle as by xenophobia in their opposition to foreign investment in agricultural land. Text below the fold (may differ slightly from edited AFR text).

Alan Oxley makes related arguments in today’s [Australian](http://www.theaustralian.com.au/national-affairs/foreigners-have-always-owned-the-farm/story-fn59niix-1226085168484).

There is perhaps only one issue in federal politics that seemingly unites Labor, coalition, Green and independent MPs. Foreigners are acquiring Australian farm land. And just like Pauline Hanson, they ‘don’t like it.’

Senator Nick Xenophon introduced legislation into federal parliament last year that would lower the threshold for Foreign Investment Review Board (FIRB) scrutiny and apply a new national interest test to foreign acquisitions of agricultural land.

This goes against the trend in Australia’s regulation of foreign direct investment (FDI), which has been to raise or abolish the thresholds for scrutiny as part of the progressive liberalisation of inward FDI.

At the same time, the government has requested the Australian Bureau of Statistics (ABS) and the Rural Industries Research and Development Corporation (RIRDC) to collect data on foreign ownership of agricultural land and water resources. The data currently collected by the FIRB and ABS gives only a very limited picture of foreign ownership.

This data gathering exercise is worthwhile in so far as it will help put these acquisitions in perspective. The debate over foreign acquisitions of both agricultural and urban land is being driven by anecdote rather than data. This creates an informational vacuum in which politicians can more easily manipulate xenophobia for electoral advantage.

What unites politicians on this issue is not so much xenophobia, but their conviction they have the right to meddle in commercial transactions they don’t like.

Such meddling will certainly not do Australian farmers any favours. Restricting foreign investment in Australian agricultural land has the potential to lower land values and the equity in Australian farms.

It could be especially harmful to farmers who want to capitalise on the equity they have built in their farms and exit the industry by selling to the highest bidder. This in turn would reduce the amount of domestic capital available for re-investment in Australia.

Senator Xenophon’s proposed national interest test is more prescriptive than the existing national interest test under the Foreign Acquisitions and Takeovers Act, which is deliberately open-ended. Ironically, this would open the door to administrative and judicial review of the Treasurer’s currently unbounded discretion to reject foreign acquisitions that fall within the terms of the Act.

This may not bother Senator Xenophon, but it certainly bothers other politicians and Treasury, who want to preserve their ability to meddle without scrutiny by the courts.

Foreign acquisitions have raised concerns about food security. The best way to ensure Australia’s food security is to increase agricultural output through increased investment. Foreign capital is increasingly important in expanding agricultural output, especially as the scale and capital intensity of production increases.

The best guarantor of food security is free trade. Australia is a net exporter of food, producing more than is needed for domestic consumption.

Prices for Australian agricultural goods are set in world markets and there is little scope for domestic prices to deviate far from the world price.

As Amartya Sen has observed, no country with multi-party democracy and a free press ever experiences famine.

In the unlikely event of a serious international conflict or crisis, foreign-owned assets in Australian can be nationalised or exports of food restricted.

Foreign interest in Australian land is not limited to its agricultural, but also its mineral potential. Agriculture and mining can often co-exist. Legislation already provides for environmental impact assessments to determine and help resolve the extent of any conflict.

Where land has competing uses, the market already provides a mechanism for determining the most valuable use and allocating the land accordingly.

Australia has a robust regulatory framework around land use and business investment more generally. Politicians should put their trust in these frameworks, rather than seeking new mechanisms for political interference and meddling in commercial transactions.

The existing Foreign Acquisitions and Takeovers Act and the FIRB add very little that is useful to the regulation of foreign investment. The FIRB already relies heavily on the advice of the Australian Competition and Consumer Commission, the Tax Office and other bodies in advising the government. The government is free to ignore this advice. The FIRB is just a fig-leaf of bureaucratic respectability for political decisions to interfere in commercial transactions and deny the resident owners of Australian equity the right to realise its full value by selling to the highest bidder.

Pauline Hanson may not have known the right word for it, but she instinctively knew the political potential of xenophobia. Unfortunately, politicians across the spectrum share her basic instincts. However, the issue is not really one of xenophobia or food security. It is whether we allow commercial decisions to be overridden by politicians who, like Pauline, say: ‘I don’t like it.’
