---
title: "Is It Any Wonder Kevin Rudd Loves the G20?"
date: "2011-02-20"
categories: ["Economics", "Financial Markets"]
---

The G20, solving the world’s problems [one complicated but meaningless sentence at a time](http://online.wsj.com/article/SB10001424052748703407304576153890049850736.html?mod=WSJ_hp_LEFTWhatsNewsCollection):

> Negotiators from the world’s leading economies haggled all night over seemingly technical details regarding how to measure global economic imbalances. They eventually produced a 53-word sentence intended to appease all sides—and open to interpretation by all sides…
>
> All 20 countries must agree on any technical detail for there to be a deal. If one country walks away, no deal.
>
> The key agreement they came up with on Saturday—one sentence in the four-page “communiqué”—essentially says that exchange rates and fiscal and monetary policies will be taken into consideration when determining whether a country’s policies lead to imbalances.
>
> To draft that sentence, officials from the U.S., Canada, France, Germany, China, Russia, Indonesia, Brazil and India were just some of the members who weighed in—at times with much different views—according to several people present. The sentence had one colon, one semi-colon, three commas, and the word “and” appeared six times…
>
> “The way it’s written, the French can say it’s an indicator and the Chinese can say it’s not really,” said one G-20 official after the meetings.
