---
title: "Italian-French Food Fight: How to Regulate FDI"
date: "2011-04-21"
categories: ["Economics", "Foreign Investment"]
---

[A couple of US lawyers](http://www.ft.com/cms/s/0/5d6d2e9e-6b75-11e0-a53e-00144feab49a.html) note the global trend towards invoking bogus strategic and national interest considerations to support political intervention in cross-border acquisitions. They suggest the following principles for regulating politically-sensitive transactions:

> First, the review process should encourage investment and be tailored to apply to transactions implicating true national security interests. Screening for other reasons, such as a “national interest” standard should require an exceptionally high standard for intervention. To support this principle, reviews should be led by a responsible agency able to assign appropriate weight to the interests of open investment while also fully protecting against national security risks. The review process should be protected from political interference…
>
> Also, the review mechanism should provide as much certainty as possible to investors…
>
> Third, the government agencies conducting the review should be accountable.

Australia’s regime for regulating FDI fails on all three counts.
