---
title: "John Edwards Tipped for the RBA Board"
date: "2011-03-29"
categories: ["Economics", "Monetary Policy"]
---

John Edwards has been [tipped](http://www.businessspectator.com.au/bs.nsf/Article/Labor-to-name-RBA-board-members-report-pd20110328-FDNVM?OpenDocument&src=hp4) as an appointment to the RBA Board. John’s Lowy Institute monograph [Quiet Boom](http://www.lowyinstitute.org/Publication.asp?pid=506) gives a good insight into the thinking he would bring to monetary policy decision-making. He is critical of the conduct of monetary policy in the late 1980s and early 1990s and directly challenges former RBA Governor Ian Macfarlane’s attempts to re-write the history of this episode. I review Edwards’ and Macfarlane’s interpretations of this episode in this [essay](http://cis.org.au/publications/policy-magazine/article/1835-review-essay-quiet-boom-and-the-search-for-stability).

As I have suggested previously, if the government is not going to re-appoint McKibbin, it could at least give thought to appointing an overseas economist to the Board. Here is an [interview](http://www.guardian.co.uk/business/2011/mar/27/inflation-cuts-consumer-spending-mpc) with Adam Posen, a US economist appointed to the Bank of England’s Monetary Policy Committee. He takes his job very seriously:

> *“If I have made the wrong call, not only will I switch my vote, I would not pursue a second term. They should have somebody who gets it right and not me. I am accountable for my performance.”*

Meanwhile, Peter Diamond’s nomination to the Fed is being held up by Senate Republicans, revenge for the Democrats blocking Bush nominee Randall Kroszner. As [Hassett](http://www.aei.org/article/103378) notes:

> *This is what we have come to: In the minds of our politicians, partisan manoeuvring and score-settling far outweigh the desire to populate government with skilled individuals.*
