---
title: "Martin Armstrong is Back"
date: "2011-09-30"
categories: ["Economics", "Financial Markets", "Rule of Law"]
---

Fresh from the longest ever jailing for civil contempt in a federal white-collar case in the US, [Martin Armstrong is back](http://www.businessweek.com/news/2011-09-28/felon-forecaster-blogs-on-cycles-after-11-years-in-prison.html). You can read a much longer profile of him and others like him in [The New Yorker](http://www.newyorker.com/reporting/2009/10/12/091012fa_fact_paumgarten).

I don’t have much time for cycle theories. When I worked in financial markets I met numerous advocates for various cycle theories among fund managers. Strangely, I always wound-up being the one who paid for lunch. However, his story is an interesting one. I’m always suspicious when someone gets locked-up for an incidental crime that hadn’t taken place before the prosecutors got involved and when everyone in the case seems to have copped a plea bargain. Even if I’m completely wrong in my suspicions, there are plenty of other cases like it pointing to the decline of the rule of law in the US.
