---
title: "MNI-Deutsche Börse Economic Forecasting Competition – May Round"
date: "2011-06-09"
categories: ["Economics", "Financial Markets"]
---

I came second in the May round of the [MNI-Deutsche Börse Economic Forecasting Competition](http://marketnews.deutsche-boerse.com/press/mnl-announces-may-forecast-competition-winners), having come third in the April round:

> NEW YORK, NY, June 8, 2011 – Market News International has announced the May winners of the MNI Forecast Competition, a free online contest in predicting US economic indicators.
>
> April’s highest forecasters in descending order are:\
> •  Jos Theelen, University of Amsterdam\
> •  Dr. Stephen Kirchner, UTS Business School\
> •  Mike Moran, Dawai Capital Markets America
>
> Until June 30, contestants are competing for the title of Best Overall Forecaster and a prize of \$1,500 by forecasting ten economic data releases: Non-farm Payrolls, Retail Sales, CPI, PPI, Industrial Production, ISM Manufacturing Index, Housing Starts, Durable Goods Orders, International Trade Balance, and New Home Sales.

The competition would appear to be mine to lose. The pressure!
