---
title: "Monetising the US Gold Stock"
date: "2011-07-30"
categories: ["Economics", "Financial Markets", "Gold"]
---

Monetising the US gold stock is a [tried and true method](http://www.american.com/archive/2011/july/rebels-without-a-clue) of keeping the bond bailiffs at bay:

> *the nation owns about a quarter billion ounces of gold, valued at the quaint old figure of \$42 2/9 per ounce. This stock serves as collateral for about \$11 billion of gold certificates on the books of the Federal Reserve. The Treasury and the Fed could swap the old certificates for new ones based on a value closer to the current market price of \$1,650 per ounce. To balance its books, the Fed would credit the Treasury’s account an additional \$400 billion or so. This should be enough for even our improvident government to run for a few more months. Such an accounting transaction has the attraction of being done before in identical circumstances, as pointed out by my colleague Alex Pollock. In 1953, the Fed similarly “monetized” the gold after the Congress failed to pass an increase in the debt ceiling. This by the way, highlights the bipartisan nature of debt-ceiling dramatics. At the time, Republicans held the presidency and majorities in both chambers of the Congress.*

Plenty of irony there for gold bugs.
