---
title: "My Review of Paul Cleary’s ‘Too Much Luck’"
date: "2011-11-22"
categories: ["Commodity Prices", "Economics", "Foreign Investment", "Media"]
---

My review of Paul Cleary’s book ‘Too Much Luck’ is up at [The Conversation](http://theconversation.edu.au/has-the-mining-boom-given-us-too-much-luck-hardly-4376). The original review included a discussion of the role of the exchange rate which unfortunately hit the cutting room floor, but can be found below the fold. The review draws on a monograph by Robert Carling and I making the case against a sovereign wealth fund for Australia that will be published by CIS in the New Year.

Paul has been offered the opportunity to respond.

Correction requested by Paul Cleary: “Stephen Kirchner’s review of Paul Cleary’s book Too Much Luck said he “wants the Foreign Investment Review Board to use its powers to force foreign companies to buy local”, and that he has advocated policies, including industry intervention, which appeal to “Australia’s parochial, insular and protectionist past”. Dr Kirchner now accepts that Mr Cleary’s book advocates no such policies. His policy recommendations only involve measures to save windfall resource revenue in a sovereign wealth fund, and to tax and regulate the resources industry more effectively.”

I welcome the fact that Paul says he does not support such policies and I am sorry for the misunderstanding.

Too Much Luck is Never Enough

If Paul Cleary is to be believed (Too Much Luck: The Mining Boom and Australia’s Future, Melbourne, Black Inc, 2011), the mining boom is the worst thing that ever happened to Australia. He maintains that the mining industry is under-taxed and under-regulated and in need of ‘stronger and more effective government control’ (ix). Yet at the same, he argues that recent governments have also squandered the revenue windfall from the mining boom. These positions are difficult to reconcile. Cleary’s proposals for greater taxation and regulation of the mining sector and increased use of a sovereign wealth fund (SWF) would only enhance the capacity of governments to squander the boom.

Cleary’s book is based in part on Freedom of Information requests made to Treasury, the Reserve Bank and other agencies on some of the public policy issues raised by the mining boom. Ironically, these FOI documents are far less revealing than what Treasury and other official sources have put on the public record.  Cleary tries hard to find support for a sovereign wealth fund among the documents even though they mostly relate to experience in overseas economies that have little in common with Australia. He is forced to concede the Treasury’s ‘curious bias against sovereign wealth funds’ (71). Cleary neglects to mention comments in a speech by then Treasury Secretary Ken Henry to Australian Business Economists on 18 May 2010 arguing against a SWF. These comments are far more compelling than the Treasury working papers Cleary cites. Cleary also seeks to enlist Reserve Bank Governor Glenn Stevens to his cause, but Stevens’ comments on SWFs have been equivocal and have called for no more than the issue to be considered.  Much of Cleary’s argument is ultimately an appeal to the authority of economists, but the few reputable ones he relies on for support would also reject many of the arguments in his book.

Cleary’s support for a sovereign wealth fund reflects his view that Australia’s resources are finite and that future generations will be left worse-off because the current generation will have exhausted these resources and spent the proceeds.  The idea that resources are finite in any economically meaningful sense is fallacious because of productivity growth and long-run substitutability on both the demand and supply sides of commodity markets. The Australian economy is well diversified and not dependent on a single resource, unlike the economies of Norway or Timor-Leste that Cleary views as models for Australia. The so-called ‘resource curse’ is not a function of resources, but of weak institutional frameworks in some resource-rich developing countries. Australia, by contrast, scores very highly on comparative measures of institutional quality.

The idea that future generations need to be ‘compensated’ for resource depletion by the current generation through a SWF is absurd. Future generations will be much wealthier than the current generation due to the ongoing technical progress that drives productivity and long-run growth in real GDP per capita. This will occur regardless of the contribution of the resources sector. Proven reserves are a poor guide to future resource availability. But even based on these estimates, Australia’s resources are not in danger of being exhausted. Cleary’s case for ‘compensation’ is the equivalent of saying that people in the late 19th century should forgo current consumption and living standards for the benefit of people in the late 20th century.

Cleary’s view that resources are finite leads to the absurd suggestion that they should be left in the ground because future resource scarcity will render them more valuable later. For example, he thinks that LNG should be left in the ground ‘for another decade or two at least’ (15). He also argues Australia should not compete with other countries that are also exploiting their resources aggressively because this will lead to over-supplied markets and falling commodity prices. Australia is a price-taker in global commodity markets. It should focus its efforts on increasing real output and exports rather than a fruitless attempt at manipulating world prices through cartel-like behaviour.

It is a gross contradiction to say that resources are in danger of being exhausted and that their prices will also fall. Cleary can’t have both sides of the argument. In fact, real commodity prices almost certainly will fall in the long-run because they become less scarce over time, a stylised fact well established by economists like Julian Simon, Harold Barnett and Chandler Morse. But this is no threat to Australia’s future prosperity, because Australia will share in the process of increasing global supply through greater output and export volumes, employment and productivity growth. Cleary’s suggestion that Australia will in future become ‘like Nauru today, but on a continental scale’ is ridiculous hyperbole.

Cleary accuses the mining industry of a multitude of sins. The mining industry uses imported equipment, adding to the current account deficit. It is capital intensive and does not create jobs. He is hostile to foreign investment and foreign ownership and wants the Foreign Investment Review Board to use its powers to force foreign companies to buy local (92). Yet the policies implied by these views are at odds with his complaint that the mining industry draws resources away from other sectors of the economy. The solution to these capacity constraints is to increase Australia’s openness to foreign goods, capital and labour so that the mining industry can expand without increasing pressure on other sectors of the economy. But Cleary does not argue for a single measure that would increase the openness and flexibility of the Australian economy.

Cleary complains that the mining industry puts upward pressure on the exchange rate, but fails to mention that this has the effect of reducing the Australian dollar incomes of the mining industry. The reason the current mining boom has not triggered the boom-bust cycle that characterised the Australian economy historically is precisely because this is the first boom Australia has experienced with the benefit of a flexible exchange rate. Just as a falling exchange rate insulates the Australian economy against adverse foreign shocks, a rising exchange rate serves to moderate the macroeconomic consequences of the terms of trade boom. Exchange rate appreciation is the solution not the problem.

Instead of allowing the price signals from the exchange rate and commodity prices to guide resource allocation, Cleary wants the government to warehouse the revenue from the mining boom in foreign currency denominated assets, effectively taking a massive punt on the future direction of the exchange rate (the foreign currency assets would rise in value if the exchange rate fell). This proposal is little different from massive intervention in the foreign exchange market and would mark a return to a managed exchange rate regime. However, it would be entirely ineffective in alleviating upward pressure on the exchange rate. Average daily turnover in the Australian dollar against foreign currencies is around \$A100 billion. Any foreign currency assets held by an Australian SWF would be a drop in the ocean of this enormously deep and liquid market, which is why official intervention in foreign exchange markets is rarely effective in moving exchange rates other than in the very short-term. 

In addition to a sovereign wealth fund, Cleary would like to see a debate about the creation of a state-owned resource company. But both these proposals sit uneasily with his concern about the role of governments in squandering the mining boom. Cleary is critical of the National Broadband Network, seeing it as symptomatic of the bad public policy that results when governments are awash with revenue, yet at the same time, he is in favour of industry policy and laments the demise of government boondoggles like the Green Car Innovation Fund (29). Cleary would have Australia retreat behind a wall of strategic industry and trade policy and state-run commodity cartels.

Cleary thinks that a sovereign wealth fund can be ‘pollie proofed’ through legislative provisions. The problem with public saving through a SWF is that it is just deferred government spending. There is no reason to believe that future governments will spend the saving accumulated in a SWF any more wisely than the governments we have actually had. In reality, the proceeds of the mining boom are being saved and invested by the private sector. It is only governments that have been dissaving and spending poorly, as Cleary is the first to admit.

If Cleary doesn’t like multinationals making money off Australia’s resources, he’s not too keen on workers profiting either. For Cleary, tax cuts and welfare payments are just ‘pissed up against the wall’ (ix). Miners spend their wages on ‘grog, gambling and women’ or go into debt to buy houses, boats and four wheel drives (47).  Apparently, future generations of Australians will be more saintly and frugal and therefore more deserving of this largess.

Cleary goes so far as to suggest that the mining industry has ‘subverted a well functioning democracy’ (77) through its opposition to additional taxes. Yet no one would suggest that the trade union movement was ‘subverting democracy’ by defending its interests in the public sphere in response to the Howard government’s industrial relations reforms. Defending one’s interests in the public sphere is the very definition of democracy, not its subversion. Yet the extra taxation and regulation Cleary proposes would only increase the incentives for the mining industry to become involved in politics.

Cleary’s views on the mining boom and his public policy recommendations are confused and contradictory. Cleary’s book is an appeal to Australia’s parochial, insular and protectionist past, when mining booms really did cause boom-bust cycles because the Australian economy lacked its current openness and flexibility. We can be thankful those days are behind us, but it is mystery why a journalist of Cleary’s standing would want to turn back the clock to the failed policies of the past.
