---
title: "Not that 70s Show: Why This Boom is Different"
date: "2011-11-30"
categories: ["Commodity Prices", "Economics", "Monetary Policy"]
---

Treasury’s [David Gruen](http://www.treasury.gov.au/documents/2237/HTML/docshell.asp?URL=2237_speech.htm) highlights the role of Australia’s macroeconomic policy framework in sustaining the boom:

> The Federal Governments of the 1970s were in direct control of all arms of macroeconomic policy, including the value of the exchange rate. When commodity prices were rising strongly, generating boom conditions in parts of the economy, it proved extremely difficult for governments of either political persuasion to impose sufficient restraint on other parts to deliver an appropriate outcome for the economy overall.
>
> By contrast, the current macroeconomic framework has several elements that together represent a crucial improvement on the framework of the 1970s. These elements are: a market-determined exchange rate, a medium-term inflation target implemented by the Reserve Bank, a medium-term fiscal framework implemented by the Federal Government, and largely decentralised wage-setting arrangements.
>
> A consequence of the current framework is that when commodity prices are high, the floating exchange rate is likely to have appreciated sharply, acting as a shock absorber, and reducing the expansionary effects of the terms of trade rise on the overall economy. As a consequence, there is a smaller role for ‘activist’ macroeconomic management - simply because much of the necessary restraint is imposed by the exchange rate.
>
> The exchange rate plays its shock-absorber role primarily by imposing significant restraint on those parts of the traded sector, including parts of the manufacturing sector, which are not experiencing strongly rising prices for their output or are not directly exposed to the booming sectors of the economy…
>
> In the longer term, the increasing numbers of people in the Asian middle classes, with disposable incomes to match, will generate rising demand for a range of Australian goods and services - whether they be a range of foodstuffs, Australian tourist destinations, or educational, financial and other professional services in which Australia has a proven track record. Indeed, this process is well underway.
