---
title: "Offshore Perceptions of Australia: A Failure of Leadership"
date: "2011-03-22"
categories: ["Economics", "Financial Markets", "Foreign Investment", "Rule of Law"]
---

The [WSJ](http://online.wsj.com/article/SB10001424052748703858404576214161570884724.html?mod=asia_opinion) on the failure of the federal government and opposition to provide leadership on the SGX-ASX takeover:

> Ms. Gillard professes to understand the general principle involved, having said that “An open economy has been in Australia’s interest.” So the failure by her and Mr. Swan to more aggressively support lifting the ownership cap to open the economy further is puzzling.
>
> She may feel politically constrained as the head of a minority government beholden to a small band of Greens and independents. But that’s all the more reason to mount an aggressive persuasion campaign. Equally disappointing is the reaction—ranging from silence to outright hostility—from members of the ostensibly more free market opposition.

On this issue, the federal opposition is not even ostensibly free market.

[Jennifer Hewett](http://www.theaustralian.com.au/business/opinion/sgx-deal-needs-major-surgery-to-avoid-certain-political-death/story-e6frg9px-1226025674503) argues the government won’t risk defeat on something it doesn’t care about anyway:

> *It would be hard enough to muster political energy and risk defeat for something the government strongly supported, but Labor doesn’t really like this deal one bit. That is even though it knows blocking it on national interest grounds would be awkward for a government already regarded with suspicion by the international investment community. It’s why the Treasurer is sounding so cautious.*
