---
title: "Some Agreement and Disagreement on FDI in Australia"
date: "2011-07-07"
categories: ["Economics", "Foreign Investment"]
---

[Paul Barratt](http://www.abc.net.au/unleashed/2784876.html) agrees with me that foreign investment in Australian agricultural land does not raise questions of sovereignty or food security. However, he argues that foreign investment may give rise to other ‘national interest’ concerns. Barrett gives as an example the proposal by Chinalco to increase its stake in Rio Tinto. Yet the concerns raised by Barrett in this context were investigated and dismissed by the ACCC. Similarly, the Australian Taxation Office has a very broad mandate and strong powers to address the transfer pricing issues raised by Barrett.

The point of my [article](../2011/i_dont_like_it_australias_hansonite_political_class.qmd) in the Australian Financial Review was not to say that commercial transactions should be outside the scope of regulation. As I noted in my op-ed:

> *Australia has a robust regulatory framework around land use and business investment more generally. Politicians should put their trust in these frameworks, rather than seeking new mechanisms for political interference and meddling in commercial transactions.*

The Foreign Acquisitions and Takeovers Act (FATA) and the FIRB do not add anything useful to the regulation of business investment in Australia that is not already addressed by other agencies, upon which the FIRB relies heavily for advice. FATA and the FIRB exist only to provide a mechanism for political interference in the market ownership and control of Australian equity capital. Parliament should legislate to regulate business investment in the national interest, regardless of ownership. But this can be done effectively without the FATA or the FIRB.
