---
title: "Sovereign Wealth Funds as ‘Social Control of Public Wealth’"
date: "2011-09-07"
categories: ["Economics", "Financial Markets", "Fiscal Policy"]
---

[The Greens](http://greens.org.au/content/greens-senate-move-sovereign-wealth-fund) are big supporters of making greater use of sovereign wealth funds. This [op-ed](http://www.theage.com.au/opinion/politics/a-nest-egg-for-the-country-could-be-just-what-labor-needs-20110906-1jv1w.html) in The Age helps explain the appeal of sovereign wealth funds to the left:

> *contemporary Left thinkers have increasingly argued that the ‘‘financialisation’’ of society - the replacement of government-funded retirement with individually-funded savings invested in financial markets, the privatisation of core services, the increasing ownership of society by hedge funds and the explosive use of credit - needs some tempering through social control of public wealth.  That could come through government ownership of vehicles such as sovereign wealth funds.*

In other words, the role of SWFs is to disintermediate the private sector from saving and investment decisions. This is perfectly understandable coming from a left-wing perspective. However, it begs the question as to why so many Coalition MPs, such as Malcolm Turnbull and Josh Frydenburg, are also such enthusiastic supporters of SWFs.

The private sector already saves and invests for the future through private capital markets. It is governments that routinely squander future wealth thorough increased public spending and borrowing. Increased public saving via a SWF sounds virtuous, until you recognise that public saving is just deferred government spending. Unless you think future governments are going to make better spending decisions than the governments we have actually had, the argument for increased public saving via a SWF is decidedly weak.

In this [op-ed](http://www.theaustralian.com.au/business/opinion/the-mining-tax-debate-highlights-the-terms-of-trade-boom/story-e6frg9if-1225891819484), I argue that some of the objectives behind a sovereign wealth fund could be better achieved through binding fiscal responsibility legislation. If a politician supports a SWF, but opposes fiscal responsibility legislation, then you know they can’t be trusted with a SWF.
