---
title: "Speaking Truth to Bill Shorten"
date: "2011-02-12"
categories: ["Economics", "Financial Markets", "Foreign Investment", "Rule of Law"]
---

An investment banker speaking to Bill Shorten [gets a less than cogent response](http://www.smh.com.au/business/time-is-ripe-for-exchange-of-ownership-20110211-1aqg6.html):

> IT WAS mid January and Bill Shorten, the Assistant Treasurer, was in Hong Kong attending an Australian Chamber of Commerce function.
>
> In an address to a relaxed gathering of ‘‘Australians in finance’‘, Shorten told the audience of the importance of financial services, and if anyone had fresh ideas they should approach him in the informal setting.
>
> David Webb, a former director of the Hong Kong Stock Exchange, elected on a corporate governance ticket by institutional investors, took up the offer. A well-known activist and retired investment banker, he now devotes much of his time to dealing with corporate governance in Hong Kong.
>
> When Webb’s turn came for a chat, the Englishman told the minister that Australia should consider scrapping the Foreign Investment Review Board as it was an impediment to attracting foreign capital. Other regulators could consider contentious investments, he said.
>
> According to Webb, Shorten said the board was necessary, turning the topic to a looming decision on the takeover of the Australian Securities Exchange by its Singapore counterpart…
>
> But what Shorten said next surprised Webb.
>
> ‘‘His attitude about this was … that foreign ownership or a perceived foreign takeover would result in Australian investors being screwed. He didn’t make very cogent arguments to me.’‘
