---
title: "Steve Jobs versus Bill Gates: The Entrepreneur as Hero and Villain"
date: "2011-10-14"
categories: ["Economics"]
---

My appreciation of Steve Jobs, from this week’s [Ideas@theCentre](http://cis.org.au/publications/ideasthecentre/article/3608-ipod-ipad-iself):

The passing of Steve Jobs saw a remarkable outpouring of appreciation for the man and the company he founded, and its many innovative products. The quality and user-friendliness of the products, combined with outstanding brand management and marketing, explain Apple’s loyal, even sectarian, following.

It is unusual for an entrepreneur to be appreciated this way. The obvious comparison is with Bill Gates. Gates and the company he founded have also had a profound impact on our everyday lives. Yet if Gates were to die tomorrow, it is hard to imagine people lighting candles outside computer stores. Gates is still seen as the grasping robber-baron of computing, even though his business strategies have been no more anti-competitive than Apple’s iTunes store. Gates’ success earned him prosecution by the US Justice Department and EU competition authorities for supposedly harming consumers.

Microsoft has bestowed benefits on the world rivalling those of Apple, but to the extent that Gates earns plaudits, it is mainly for his philanthropic efforts. Gates’ philanthropy is likely motivated, at least in part, by the desire to win the respect and appreciation he never found as an entrepreneur. Gates is a member of a group of billionaires who have signed up to the notion that they must give away the majority of their wealth. In Australia, Dick Smith threatens to ‘out’ the wealthy who fail to give, treading a fine line between moral suasion and public intimidation. Yet Gates has done more for humanity as an entrepreneur than he is ever likely to achieve as a philanthropist. It is only the entrepreneurship that made the philanthropy possible.

This is something Jobs understood very well. He showed little interest in philanthropy, not because he was uncharitable but because he recognised that it was not his comparative advantage. Jobs was consequently ‘named and shamed’ by the US philanthropic sector. This did not dent his reputation, perhaps because the public also recognised they were better served by his relentless focus on Apple’s product.

Adam Smith famously observed that ‘it is not from the benevolence of the butcher, the brewer, or the baker, that we can expect our dinner, but from their regard to their own interest.’ In 1985, Jobs told *Playboy* magazine ‘we think the Mac will sell zillions, but we didn’t build the Mac for anybody else. We built it for ourselves.’ Like Gates, Jobs was a self-interested and self-serving businessman and yet we are all much richer for their efforts.
