---
title: "The Finite Resource Assumption: Tripling or Quadrupling Down with Jeremy Grantham"
date: "2011-05-06"
categories: ["Commodity Prices", "Economics", "Financial Markets"]
---

[Malcolm Turnbull](http://www.businessspectator.com.au/bs.nsf/Article/sovereign-wealth-fund-Bill-Shorten-super-superannu-pd20110506-GKRUJ?OpenDocument&src=sph) is not the only person to be led astray by the assumption that resources are finite. According to GMO’s [Jeremy Grantham](http://www.gmo.com/websitecontent/JGLetterALL_1Q11.pdf):

> *Scavenging refuse pits will no doubt be a feature of the next century if we are lucky enough to still be in one piece.*

Here is Grantham’s strategy for trading commodities:

> *Given my growing conﬁdence in the idea of resource limitation over the last four years, if commodities were to keep going up, never to fall back, and I owned none of them, then I would have to throw myself under a bus.  If prices continue to run away, then my small position will be a solace and I would then try to focus on the more reasonably priced – “left behind” – commodities.  If on the other hand, more likely, they come down a lot, perhaps a lot lot, then I will grit my teeth and triple or quadruple my stake and look to own them forever. *

Sounds like a good formula for losing ‘a lot lot’. Apparently, this is what passes for macro strategy at GMO.
