---
title: "The Real Cost of the CPRS Mk II"
date: "2011-08-01"
categories: ["Economics", "Politics"]
---

[Ricardian Ambivalence](http://ricardianambivalence.wordpress.com/2011/07/31/carbon-tax-changing-the-policy-climate/) highlights the real cost of the CPRS Mark II in the presence of political capital constraints:

> *The fact is the government can’t open a new tax battle while the carbon tax is taking all the oxygen. This is the hidden cost of the carbon tax. Not only will it do nothing to change the climate it is also crowding out a discussion of controversial but important policy debates.*

The government’s apparent determination to die in a ditch over the CPRS Mark II is puzzling from a public choice perspective. There is nothing wrong with dying in a ditch for something worthwhile, but this is not typical behavior for politicians and begs the question why they don’t do it for something more worthwhile if they really are putting principle ahead of political expediency. Implementing the entirety of the Henry review would surely come at lower political cost and could even gain bipartisan political support.

Rudd and Turnbull realised they had to form a policy cartel on the CPRS to avoid it consuming them both. Neither wanted to fight an election on the issue. It was a bipartisan political conspiracy that nearly paid-off.  A policy cartel is consistent with the median voter model. The CPRS Mk I would be operating today were it not for the coalition revolt against Turnbull’s leadership. Turnbull’s judgment that this would be electorally fatal to the Coalition was spectacularly wrong. Breaking the Rudd-Turnbull CPRS policy cartel destroyed Rudd and nearly won the Coalition the 2010 election.
