---
title: "The Long March of Fightback"
date: "2011-12-13"
categories: ["Economics", "Politics"]
---

I have an op-ed in [Online Opinion](http://www.onlineopinion.com.au/view.asp?article=13004) marking the 20th anniversary of Fightback:

> Twenty years ago this November, the Liberal-National Party coalition released Fightback, the most comprehensive and market-oriented policy platform ever taken to a federal election. Conventional wisdom holds that Fightback was a political folly that saw the opposition lose an un-losable election. Yet in the last twenty years, much of Fightback has been implemented and even enjoys bipartisan political support. Fightback was a failure only when viewed through the lens of short-term electoral politics rather than public policy.
>
> The1993 federal election is still considered Paul Keating’s greatest political triumph and John Hewson’s spectacular failure. But this is to elevate personal political fortunes above public policy outcomes. Fightback’s centerpiece, the goods and services tax, was supported by Paul Keating in 1985. It would be surprising if he now called for its repeal. Keating beat Hewson in 1993 but within seven years the GST prevailed and now serves to diminish Keating and his legacy.
>
> Even with the advantages of incumbency, the Howard government’s 1998 tax reform package was as politically risky as Fightback. It nearly cost John Howard both the 1998 and 2001 elections. Yet it made Howard’s reputation as a reformer and few would argue with the economic legacy of the tax reforms introduced in 2000. As Paul Kelly has noted, if the Labor Party had implemented the 1998 tax reform package, the ABC would have been making documentaries about it for the next 50 years.
