---
title: "The RBA Didn’t ‘Lose’ $5bn on its 1997 Gold Sales"
date: "2011-01-11"
categories: ["Economics", "Financial Markets", "Gold"]
---

[Paul Cleary](http://www.theaustralian.com.au/news/nation/reserve-banks-gold-sale-cost-us-5bn/story-e6frg6nf-1225985231872 "Paul Cleary") has not done himself any favours beating-up the product of The Australian’s latest FOI request of the Reserve Bank:

> The decision to sell 167 tonnes of the bank’s reserves has cost the nation about \$5 billion based on today’s soaring price of almost \$1400 an ounce…
>
> The RBA’s sales pushed the world gold price down to an 11-year low, returning just \$2.4bn for the gold that was sold via a single broker engaged without a tender.
>
> The same amount of gold would be worth about \$7.4bn today.

This analysis ignores two inconvenient facts. The gold was sitting on the RBA’s books at the Bretton Woods parity price, so the RBA booked a sizeable profit on the sale even at 1997 prices. The suggested \$5 billion ‘loss’ ignores the return on the income producing assets the RBA purchased with the proceeds of the sale. It is likely these assets have underperformed gold recently, but historically, the real returns to gold have been negligible compared to other assets. As one of the world’s biggest producers, Australia is naturally long gold. There is no diversification value in relocating gold from the WA goldfields into vaults under Martin Place.

The 1997 RBA gold sale should give gold bugs pause. As we have noted previously, above ground gold stocks dwarf annual production, so the gold price is best viewed as a stock rather than a flow equilibrium. There is a certain irony in people who fear an over-supply of fiat money taking refuge in an asset in which central banks hold substantial stocks that could be dumped on the market at any time. At least one US think tank has advocated selling the US gold stock of 261.5m ounces to yield a quick and dirty profit for the US Treasury. The RBA was able to offload 167 tonnes without too much difficulty.
