---
title: "Time to Dump Australia’s Anti-Dumping Laws"
date: "2011-03-02"
categories: ["Economics", "Free Trade & Protectionism"]
---

I have an op-ed in today’s [Australian](http://www.theaustralian.com.au/business/anti-dumping-rules-have-a-greater-potential-to-harm-producers-and-consumers/story-e6frg8zx-1226014363959) arguing against the campaign by the Australian Workers’ Union and the federal opposition to strengthen Australia’s anti-dumping regime:

> The AWU has dressed up its anti-dumping campaign in the language of free trade and adherence to World Trade Organisation rules. But there is nothing in the WTO rules that prohibits dumping and WTO members are not required to maintain an anti-dumping system…
>
> It is far more likely that Australian consumers and producers will end up paying more because of misplaced fears about foreign predation than due to the acquisition of international monopoly power by foreign producers. Anti-dumping measures bring about the very outcome they are designed to prevent.
>
> The Productivity Commission has recommended the introduction of a public interest test, which would improve the operation of our anti-dumping system by allowing greater consideration of the economy-wide implications of dumping.
>
> But a simpler reform that would have greater benefits for Australian consumers and the majority of producers would be for Australia to dump its anti-dumping system. This was one of the recommendations of the 1989 Garnaut Report. It shows just how little progress has been made in this area that we have still not acted on Garnaut’s recommendation two decades later.
