---
title: "Unhypothecating the Flood Levy"
date: "2011-07-08"
categories: ["Economics", "Fiscal Policy"]
---

If your first pay packet of the new financial year is a bit lighter, it is probably due to the [flood levy](http://www.ato.gov.au/individuals/content.aspx?doc=/content/00282044.htm), the first discretionary federal tax increase in over a decade. Robert Carling wrote a paper for CIS in 2007 on the [misuse of tax earmarking](http://www.cis.org.au/images/stories/policy-monographs/pm-75.pdf), of which the flood levy is a good example.

Tax increases should not come as a surprise following the unfunded fiscal stimulus of 2008-09. Announcing an unfunded fiscal stimulus is equivalent to announcing a future tax increase. It is just a matter of when the increased tax burden will have to be paid. The increase in household saving that accompanied the stimulus suggests that households understand this.

Announcing the details of the re-jigged Rudd-Turnbull CPRS at the end of the same week that many taxpayers will experience their first discretionary federal income tax increase in over a decade is a curious political choice to say the least. It can only add to the unpopularity of the new CPRS.
