---
title: "Wayne Swan at Home and Abroad"
date: "2011-04-15"
categories: ["Economics", "Free Trade & Protectionism"]
---

[Wayne Swan](http://online.wsj.com/article/SB10001424052702304741404575563850838835966.html) before the G20 summit in South Korea:

> *“As we go forward we have to ensure that we don’t see a return to protectionism in new guises,” Mr. Swan said, citing the G-20’s success in staving off protectionist measures in the past two years as one of the global gathering’s “great achievements.”*

[Wayne Swan](http://www.theaustralian.com.au/national-affairs/cabinet-split-on-free-trade-push/story-fn59niix-1226039362945) before federal cabinet:

> *Sources confirmed yesterday that Trade Minister Craig Emerson won approval for the shift with the backing of Ms Gillard, but only after her deputy, Wayne Swan, attacked the policy as lacking a political constituency. The sources said that, although the Treasurer, who has a long record of advocacy for trade liberalisation, did not attack the principles of the policy, he questioned the political wisdom of proceeding with the change at a time when the government was already fighting for reform on a range of other fronts, including the carbon tax.*
