---
title: "We’re Too Busy to be Transparent: FIRB"
date: "2011-06-09"
categories: ["Economics", "Foreign Investment", "Rule of Law"]
---

FIRB chairman [John Phillips](http://www.theaustralian.com.au/business/firb-head-questions-support-for-singapore-asx-bid/story-e6frg8zx-1226071975788) on the rejection of the SGX-ASX merger:

> *“I couldn’t understand why anyone would support it—unless they had a vested interest.”*

John ignores the possibility that some people might support the merger by taking the view that it was none of their business what ownership structure ASX management chose to pursue. Unfortunately, many in government and the media see their role as being back-seat drivers of other people’s business decisions.

John also complains about the FIRB’s time being taken up responding to FOI requests:

> Mr Phillips said the FIRB was currently subject to many Freedom of Information requests which were taking up the time of its staff.
>
> “We are getting so many requests from (journalists) and others under the FOI Act which is unfortunate in a way because it is taking up the time of people who ought to be dealing with applications,” he said.
>
> Mr Phillips said he was “not sure how much more transparency there can be”.

I can think of [one less FOI application](http://www.theaustralian.com.au/news/opinion/more-inscrutable-than-the-chinese/story-e6frg6zo-1225831954203) the FIRB would have had to deal with if they had taken the time to put their public speeches on their web site. It is the FIRB that wastes everyone else’s time by denying access to information that should be on the public record as a matter of course.
