---
title: "What’s So Special About the ASX?"
date: "2011-02-10"
categories: ["Economics", "Foreign Investment", "Rule of Law"]
---

[Deutsche Börse AG looks set to acquire the New York Stock Exchange](http://online.wsj.com/article/SB10001424052748703310104576134653031893900.html?mod=WSJ_hp_LEFTWhatsNewsCollection), while the LSE Group is also set to merge with the Toronto exchange in the latest cross-border tie-ups between securities exchanges. The local market has correctly interpreted these deals as increasing the likelihood that Australia’s Treasurer will approve the proposed merger of SGX and ASX (it has already cleared ACCC scrutiny). If an icon of US capitalism such as the NYSE can be acquired by Deutsche Börse, it becomes very difficult for Australia’s FDI protectionists to argue that the ASX should be immune from foreign acquisition. Oddly enough, opposition to the Deutsche-NYSE deal is more likely to come from European than US regulators.

We should still not underestimate the potential for the ASX-SGX deal to fall over, either because Treasurer Swan deliberately spikes the approval with so much conditionality as to make it unacceptable to the parties or because of parliamentary disallowance of the necessary regulatory changes. The deal remains a key test of Australia’s international openness, one that some combination of the federal government, the cross-benches and the opposition might still fail.
