---
title: "When the Guano Runs Out"
date: "2011-03-28"
categories: ["Economics", "Fiscal Policy"]
---

A [RBA research paper](http://www.theaustralian.com.au/business/rba-tips-120bn-flood-of-capital-as-dollar-hits-post-float-record/story-e6frg8zx-1226029063163) obtained through FOI advocates an offshore sovereign wealth fund, although the story seems to contain some editorialising by Paul Cleary, who thinks Australia is just a bigger version of Timor Leste. [Liberal MP Paul Fletcher](http://www.abc.net.au/unleashed/45646.html) seems to think Australia is just a bigger version of Naru:

> More fundamentally, natural resources are finite. When they run out, the money will stop flowing. So we should make sure we put some of the money aside – rather than spending it all now.
>
> In our own region, the micro-state of Nauru offers a sobering example of the folly of assuming that the good times will last forever. It used to have large reserves of guano, used to make fertiliser.  With only a few thousand people and a steady flow of mining royalties, it was in a fortunate position.
>
> But the money was largely frittered away. Then the guano ran out – and Nauru had little to show for decades of mining.

Resources are not finite in any economically meaningful sense. The Coalition seems to think that SWFs are a great idea once government debt is paid off (they set up the Future Fund after all). I make the case against further use of SWFs in this [op-ed](http://www.theaustralian.com.au/business/opinion/the-mining-tax-debate-highlights-the-terms-of-trade-boom/story-e6frg9if-1225891819484). Governments that are not prepared to commit to binding fiscal responsibility legislation cannot be trusted with SWFs.
