---
title: "Donald Trump has a chance to shape US monetary policy for years"
date: "2018-02-14"
categories: ["Economics", "Financial Markets", "Monetary Policy"]
---

I have an op-ed in today’s [AFR](http://www.afr.com/opinion/columnists/trump-has-a-chance-to-shape-us-monetary-policy-for-years-20180213-h0w05o) on how Obama’s neglect gives Trump the chance to own the leadership of the Federal Reserve Board. Full text below the fold (may differ slightly from published version).

Obama’s neglect of the Fed an opportunity for Trump

Incoming Chairs of the US Federal Reserve Board often find themselves stepping straight into trouble.

Alan Greenspan took up the role two months before the 1987 stock market crash.

Ben Bernanke assumed the office in February 2006 just as US house prices were peaking ahead of the financial crisis of 2008.

Jerome Powell was sworn in at the beginning of this month only to face a sharp sell-off in US equities his first day on the job. Powell will inevitably face similar challenges to his predecessors, perhaps the most important being how the Fed balances its inflation and financial stability mandates.

The change at the top of the Fed is the start of what promises to be a compete remaking of the membership of the Federal Reserve Board under President Trump.

The current President has the opportunity to appoint six of the seven Board members who determine US monetary policy, alongside five of the regional Federal Reserve Bank presidents on a rotating basis.

This opportunity arises in part because of the Obama Administration’s neglect of the governance of this important economic institution, leaving Federal Reserve Board positions vacant for extended periods.\
Board Governors notionally serve a term of 14 years, with one term beginning every two years on the first of February of even numbered years. 

In recent years, Board members have served for significantly less than their full terms, in some cases, as little as two years. This places an increased burden on the executive branch of government to ensure that the Board is fully staffed.

The Obama Administration failed to meet that burden, not because of Senate obstruction of Fed appointments, although the Senate did reject one Obama nominee in 2010, but due to the failure to even nominate candidates for the positions.

There were two vacancies on the Board when Trump assumed office, but the departure of former Chair Janet Yellen, former Vice Chair Stanley Fischer and Daniel Tarullo, together with Trump-appointed Randal Quarles’s partial term that ended on 31 January, gives Trump and the Republican-dominated US Senate enormous influence over the leadership of the Fed.

The Board vacancies change the balance of power on the Federal Open Market Committee (FOMC) that sets monetary policy. Whereas the seven Board members notionally outnumber the rotating regional Bank presidents by seven to five, the regional bank presidents have come to outnumber the Board members.

Obama’s lack of interest in the Fed perhaps reflected his view, rather indelicately expressed to the incoming Chair of his Council of Economic Advisers Christina Romer, that ‘monetary policy has shot its wad.’\
Romer disagreed and, perhaps reflecting her exchange with Obama, published an article in 2013 with David Romer titled ‘The Most Dangerous Idea in Federal Reserve History: Monetary Policy Doesn’t Matter.’

Since taking office, Trump passed on the opportunity to reappoint Yellen as Chair in favour of Jerome Powell. While there was some disappointment that Yellen was not reappointed, Powell’s appointment was otherwise widely view as a conventional one. Trump has yet to nominate a Vice Chair.

In additional to Randal Quarles, Trump has nominated Marvin Goodfriend, a noted monetarist, to fill one Board vacancy. Goodfriend is a firm believer in the efficacy of monetary policy and is committed to meeting the Fed’s inflation target.

It is ironic that while neither Ben Bernanke nor Janet Yellen were considered particularly hawkish on inflation before taking office, their focus on official interest rates as the main indicator of the stance of policy and belief in an effective trade-off between the unemployment rate and the inflation rate led them to deliver a monetary policy stance that was much tighter than they likely intended.

The Fed has systematically undershot its inflation target in recent years, calling its credibility into question. The Fed has blamed various one-off and non-monetary factors, but such a sustained undershooting can only be attributed to the conduct of monetary policy.

Janet Yellen described low inflation as a ‘mystery,’ while former Board member Daniel Tarullo, who resigned in April last year, claimed the Fed did not have a ‘theory of inflation dynamics that works.’ These were extraordinary statements coming from those charged with setting the inflation rate.

Trump should waste no time bringing the Board up to strength with appointees willing to serve a full term. A full strength Board is essential in enabling the Fed to effectively discharge its numerous statutory responsibilities, quite apart from monetary policy, as well as restoring the traditional balance of power with the regional bank presidents on the FOMC.

Trump should also ensure that future Fed appointees believe in the effectiveness of monetary policy and understand that inflation and nominal spending are the product of that policy.

Anyone who thinks differently has no business making monetary policy.

Wednesday sees the first reading on US inflation for 2018 and will be closely watched. With inflation still below target, the Fed will need to proceed cautiously in raising interest rates. Based on recent history, market fears that the Fed will overdo it are entirely justified.

Dr Stephen Kirchner is Program Director, Trade and Investment, at the United States Studies Centre, University of Sydney.
