---
title: "Making America 1930 Again"
date: "2018-03-05"
categories: ["Economics", "Free Trade & Protectionism"]
---

I have an op-ed in the [AFR](http://www.afr.com/opinion/steel-tariffs-will-undermine-american-national-security-20180302-h0ww1d) on Trump’s latest tariff measures. Full text below the fold.

Steel tariffs make America 1930 again

The Trump Administration’s decision to impose global tariffs of 25% on imported steel and 10% on aluminium will come as a disappointment to Australia and other US allies who hoped to be carved out of the measures. While there may still be scope for Australian exports to be excluded from the tariffs, Trump has told US industry executives he wants no exceptions.

The tariffs are to be imposed under Section 232 of the US Trade Expansion Act of 1962, which authorises the Secretary of Commerce to investigate whether imports are harming US national security and to propose remedies to the President.

This provision was designed to guard against a situation in which the US might become dependent on unfriendly countries for imports critical to national security. It was last used by President Reagan in 1986.

Yet in the case of steel imports, there is no such dependence. Most US steel imports come from allies such as Canada, Europe, South Korea and Australia. China and Russia have a small share of overall imports. The defence sector consumes a trivial share of US domestic steel output. The measures will harm US allies more than its strategic competitors.

A stronger although still flawed national security case can be made for aluminium, where Russia and China have a larger share of imports. The US has only one aluminium smelter that produces aerospace-grade product. \
But the aluminium tariff is much smaller than the steel tariff, so the proposed remedies are not proportional to the alleged threat. This suggests the real motivation is protectionism not national security.

As well as harming US allies, the tariffs will increase costs for the US defence sector. The measures as proposed were opposed by the Pentagon, in part because of the harm to US allies like Australia. The consumers of US steel across a wide range of industries and US exports will be hit. The tariffs will also increase the cost of President Trump’s proposed infrastructure program.

The measures are an abuse of US trade law. By all accounts, the Commerce Department’s investigation into the matter was perfunctory, with little regard for proper process. Trump has complete discretion over the form and duration of the measures.  They are so sweeping it will almost certainly be necessary to introduce exclusions in future, from which Australia may or may not benefit.

Affected countries will retaliate and the measures could be the subject of disputes before the World Trade Organisation. Whether the WTO upholds the national security justification will be a key issue.

If it does, this will set a dangerous precedent for other countries to abuse similar provisions in domestic and international trade rules. If it does not, the Administration may ignore the WTO ruling or, worse, withdraw from the WTO. The latter outcome would be the biggest blow to the rules-based international trading system since the 1930s.

The WTO dispute settlement process is already being actively undermined by the Trump Administration, which is blocking appointments to the appellate body that adjudicates trade disputes.

The tariffs follow the safeguard measures imposed earlier this year on solar panels and washing machines. The Administration is also expected to pursue major retaliatory action in response to Chinese intellectual property rights violations. These measures will almost certainly violate WTO rules. If challenged by China, the WTO could rule against the US and declare the relevant provisions of US trade law inconsistent with WTO obligations.

Collectively, these actions amount to a massive assault on free trade that will harm the US economy more than other countries. It suggests the anti-free trade forces in Trump’s Administration are in the ascendant. The adverse financial market reaction to the latest tariffs only hints at the damage that could be done to the world economy.

While some in the Administration continue to hold the door open to the US re-joining the Trans-Pacific Partnership, as the Australian government hopes, Trump’s policy actions demonstrate this is an increasingly remote prospect.

While Australia will be disappointed with the latest tariffs, it does not come to this issue with clean hands. Australia is an increasingly aggressive user of anti-dumping actions, including duties on steel imports. Ironically, Australian producers are now being hit by these duties as they need to import product to meet demand in excess of domestic production.

Changes to Australia’s anti-dumping regime under the Abbott and Turnbull governments have made it easier for local producers to abuse the anti-dumping system for protectionist purposes.\
Successive Australian governments have ignored advice going back as far as the 1989 Garnaut Report that they should abandon or curtail the use of anti-dumping measures.

Australia’s lobbying effort on US steel tariffs might have resonated more strongly in Washington if we were not also playing the protectionist game.

Dr Stephen Kirchner is Program Director, Trade and Investment, United States Studies Centre at the University of Sydney.
