---
title: "Trump pursuing the wrong strategy against China"
date: "2018-04-09"
categories: ["Free Trade & Protectionism"]
---

I have an op-ed in the [AFR](http://www.afr.com/opinion/columnists/how-trump-should-really-tackle-beijings-technology-thefts-20180408-h0yh86) arguing President Trump is pursuing the wrong trade policy strategy against China. Full text below the fold.

President Trump has proposed an additional \$US 100 billion in tariffs on Chinese imports, on top of the 25 per cent tariffs on \$US 50 billion of imports already mooted as retaliation for China’s forced technology transfers and intellectual property rights violations. The US has also initiated a WTO dispute with China over its increasingly discriminatory technology regulations.

The latest tariff measures are a response to genuine violations of international trade law by China, unlike the recent tariffs on steel and aluminium, which were based on a bad faith invocation of the national security provisions of US trade law.

However, the Administration’s proposed tariffs are the wrong remedy, inconsistent with its domestic and international legal obligations and will be ineffective in changing Chinese practices.

Instead of implementing new tariffs, the US should instead broaden its WTO dispute with China to cover the full range of intellectual property issues and discriminatory technology regulations.

Foreign firms operating in China have long complained about forced intellectual property transfer as a condition for entry into the Chinese market and as part of joint venture arrangements with Chinese firms.\
China’s new National Cybersecurity Law and the National Security Law require that information, communications and technology (ICT) products must be “secure and controllable.” This vague standard provides a legal mechanism through which China can engage in ICT protectionism and extract trade secrets and intellectual property such as source code from foreign firms.

Foreign companies operating in China are subject to multiple security reviews administered by multiple agencies, including a new cybersecurity review regime. China is imposing data localisation requirements that potentially interfere with the ability of both foreign and Chinese firms to operate global ecommerce and other platforms.

China is also erecting barriers to competition in cloud computing, with foreign cloud service providers requiring a local partner.

These measures reflect China’s desire to control the internet and ICT goods as part of its apparatus of social and political repression, as well as to foster indigenous technological innovation through state intervention and protectionism. China seeks to become a global technology leader through self-sufficiency in the production and consumption of all technology goods and services. China’s mercantilist approach to technology innovation threatens to fragment the internet and ICT product development globally.

China’s ICT protectionism violates both the WTO Agreement on Trade Related Intellectual Property Rights and China’s WTO Accession Protocol. China is vulnerable to a WTO challenge over its intellectual property rights violations. Indeed, the US has previously brought successful WTO actions against China in this area which led China to voluntarily eliminate the offending practices.

The US could initiate a broader action at the WTO in concert with other countries with good prospects for success. The US and other countries supported China’s accession to the WTO in 2001 so they could exercise this leverage over China.

By pursuing unilateral tariff measures outside the WTO, the Trump Administration transforms the US from trade victim to trade villain. China is well within its rights to challenge the US measures as a violation of US obligations and impose proportionate retaliatory measures. The WTO could rule that the relevant provisions of US trade law are inconsistent with WTO rules, authorising Chinese retaliation, a perverse outcome.

Trump has engineered a situation in which China can turn the WTO against the United States over an issue where China is ultimately at fault.

Trump’s latest tariffs are also vulnerable to domestic legal challenge. The measures fall outside his legislative authority under section 301 of the Trade Act, which authorises the US Trade Representative (USTR) to take action only in respect of foreign trade barriers that fall outside the scope of WTO rules. US law requires the USTR to invoke WTO dispute settlement procedures where applicable. Trump is abusing both domestic and international law.

Unilateral tariffs by the United States are unlikely to change Chinese policy and China’s retaliatory tariffs will compound the self-inflicted harm to the US economy.                                                                                                                                                             

The US should instead be leading concerted action through the WTO to change Chinese policy and protect the internet and global ICT standards from further fragmentation at the hands of China.

The Trans-Pacific Partnership was potentially a vehicle through which the US could have enlisted other countries to pushback against China’s ICT protectionism and state-led capitalism, but US withdrawal from the TPP means that is now a missed opportunity.

It is incumbent upon the Republican-led Congress to reign in the Trump Administration’s anti-trade policies. There is historical precedent for Congress overturning Presidential tariff measures. Congress should go further and legislate to remove some of the President’s Cold War-era discretionary powers over trade policy.

If Congress does not act to reign in the Trump Presidency over trade, the damage that will be inflicted on the US and world economy will only compound that from China’s mercantilist policies.
