---
title: "Trump Administration Divided on Trade Policy"
date: "2018-05-23"
categories: ["Free Trade & Protectionism"]
---

I have an [op-ed](http://www.afr.com/opinion/columnists/trump-is-fighting-trade-war-against-economic-fundamentals-20180522-h10efh) in the AFR noting the contradictions in US international economic policy. Full text below the fold (may differ slightly from edited AFR version).

The joint United States-China communique on trade issues released over the weekend has been flagged by US Treasury Secretary Steven Mnuchin as a ceasefire in the trade war between the two economies.

Yet the communique suggests the two countries remain far apart on key issues. The statement contained little of substance and at best serves as a placeholder for further negotiations.

Perhaps the biggest stumbling block is the US insistence on trying to negotiate specific trade outcomes rather than over the rules of trade.

Ironically, this is pushing China even further in the direction of managed trade as it attempts to satisfy US demands. Complaints about Chinese mercantilism ring hollow when the US is pursuing a mercantilist policy of its own.

Media reports note that the US Agriculture Department is looking into how to expand production of key agricultural products that China could then buy in an eerie echo of communist central planning.

The key US demand that China reduce the size of its bilateral trade surplus by increasing purchases of US goods and services is unrealistic and makes no economic sense.

The trade balance is an arbitrary construct, calculated on the basis of goods crossing lines on a map, with little regard to the location of value-added or the associated cross-border investment that balances the overall economic relationship between the two economies.

Even if China were to somehow increase its purchases of US goods and services, the increased demand for US dollars to make those purchases would tend to put upward pressure on the US dollar foreign exchange rate, making the US less competitive.

An expansionary US fiscal policy is already inducing foreign capital inflows and putting upward pressure on the US dollar exchange rate, crowding-out US net exports.

This is one reason why the US Federal Reserve has little reason to fear expansionary fiscal policy. The US dollar will do much of the work of tightening monetary conditions.

The US current account deficit is ultimately the product of its own imbalance between domestic saving and investment.

As Australia learned from policy mistakes in the 1980s and 90s, a current account deficit and corresponding capital account surplus is an indication of economic strength, not weakness.

China’s former current account surplus, which turned to a deficit in the first quarter of this year, says more about the defects of its economy than its strengths, in particular, the suppression and distortion of its domestic capital markets.

US economic and trade policy under Trump are fundamentally incoherent. By all accounts, the US negotiating team is itself divided on key issues and China is at a loss to work out what the US wants and how to satisfy US demands.

At the same time that the US is looking to strike a superficial deal on managed trade with China, time is running out to re-negotiate the North American Free Trade Agreement (NAFTA). Having already walked away from another high quality trade agreement in the Trans-Pacific Partnership, the failure of the NAFTA negotiations would be another blow to the US economy as well as to US allies.

By focusing on specific outcomes on trade, the US is losing sight of the more important rules of the game that ensure trade and cross-border investment are conducted in a fair and reciprocal manner.

Donald Trump’s offer at the instigation of the Chinese to relax restrictions on Chinese telecoms company ZTE as part of the effort to secure Chinese concessions illustrates how attempts to manage trade internationally can undermine the rule of law domestically.

The rule of law is one of the great strengths of the US economy, the foundation stone of its capital markets and itself an important export to the rest of the world that consumes US financial services.

Even if China and the US were to flesh out their weekend communique with a more specific deal on trade, it is unlikely to prove robust to the inherently dynamic nature of the world economy.

Financial markets, including exchange rates, will effectively discount the substance of any agreement and the other incoherent elements of US economic policy.

The laws of economics will continue to work, even if President Trump does not believe in them.

The US Administration will find itself fighting a losing war against economic fundamentals. It will also find very few partners willing to enter into bilateral agreements to replace the multilateral agreements it has walked away from.

Those looking for a resolution of US and Chinese trade tensions in the weekend communique are sure to be disappointed. With the Trump Administration focused on arbitrary and economically irrelevant measures of trade performance, a lasting peace in its self-imposed trade war with the rest of the world will be impossible to achieve.

Dr Stephen Kirchner is Program Director, Trade and Investment, United States Studies Centre at the University of Sydney.
