---
title: "Trump’s tariff war doesn’t play to America’s great strengths"
date: "2018-07-05"
categories: ["Foreign Investment", "Free Trade & Protectionism"]
---

I have an op-ed in today’s [AFR](http://online.isentialink.com/afr.com/2018/07/04/4568b29d-54b9-48fb-bafc-82bcffd0ec88.html) on America’s move away from its traditional open door policy towards foreign investment. Text below the fold.

Recent volatility in US stock markets has been attributed to speculation about new restrictions on foreign investment in the United States. The Trump Administration has been sending mixed signals on the issue, but is likely to move away from what is still a relatively open foreign investment policy.

The Administration has considered invoking the International Emergency Economic Powers Act to impose blanket restrictions on foreign investment in sensitive sectors of the US economy. The US Congress is also considering legislation expanding the scope and powers of the Committee for Foreign Investment in the United States (CFIUS), a review body similar to Australia’s Foreign Investment Review Board.

Both measures target China’s systematic harvesting of technology through investments in US companies in support of Beijing’s ‘Made in China 2025’ initiative. China aims to become a world leader in key technologies, including robotics and artificial intelligence, many of which have both civil and military applications.

The US correctly sees China as pursuing a mercantilist approach to economic development through state industrial policies that discriminate in favour of Chinese firms and which may harm US national security.

The US concern over China’s systematic, state-sponsored theft of foreign technology is a legitimate one, but increased restrictions on foreign investment may not be the right way to tackle the problem. There are alternative, more targeted policy instruments that can be used.

The US has an export control regime that regulates the export of sensitive technologies that is already being expanded in legislation before Congress.

The US can initiate further World Trade Organization disputes in concert with other countries to address China’s violations of the Trade-Related Investment Measures and its own WTO Accession Protocol, which prohibit requiring technology transfer as a condition for market access.

The US could also adopt targeted sanctions against Chinese companies engaged in intellectual property theft and impound Chinese imports found to have infringed intellectual property rights.

By contrast, limiting Chinese investment in the United States could backfire by encouraging China to double-down on its indigenous innovation strategy. The recent US sanctions against ZTE have already spurred China further down this path. If Chinese capital stays at home, it is more likely to finance Chinese innovation at the expense of the US and other US-allied economies.

Failing to capitalise on Chinese investment may hinder the development of domestic capabilities important to national security, particularly as China closes the technology gap with the US. To the extent that China becomes a leader in key technologies through indigenous innovation, excluding Chinese investment may further cede technological leadership.

This suggests a delicate balance between rejecting specific transactions that may pose national security risks while otherwise seeking to capitalise on the benefits of Chinese investment. A blanket ban on investments in entire sectors is unlikely to find this balance.

Ideas want to be free and new technologies will eventually diffuse across international borders. That is mostly for the better. It is unrealistic to expect that the world’s soon-to-be-largest economy will forever remain a technology laggard.

That is not to say that the US cannot maintain its technological leadership. Theft and autarky are a poor foundation on which to seek technological and economic progress. The main advantage the US has over China is not specific innovations that will be appropriated by foreigners, either legally or illegally, but the institutional framework that sustains their creation. That framework includes open capital markets, the rule of law and intellectual, political and cultural freedom.

That China relies heavily on appropriating foreign technology is itself evidence that it is struggling to compete in fostering institutions and a culture conducive to innovation and progress. The history of state-directed economic development is littered with costly failures and Made in China 2025 may well join them.

While many in the Trump Administration see China’s failure to fully play by international rules and norms as a weapon employed against the US, China’s selective adherence to these rules and norms is also a strategic weakness.

It helps explains why China has no allies apart from North Korea, a country that is more a problem to be managed than a strategic asset. The US, by contrast, enjoys a network of security and economic relationships with countries like Australia that increases its strategic weight, although this is an asset the current Administration seems determined to ignore.

China’s political and economic system is brittle and insecure. The same forces that diffuse technological innovation also promote ideas and aspirations that threaten the Chinese Communist Party’s rule.

The US should continue to play to its strengths, including open capital markets. Blanket restrictions on foreign investment may hinder the US as much as China.

Dr Stephen Kirchner is Program Director, Trade and Investment, United States Studies Centre at the University of Sydney.
