---
title: "A $42 Billion Future Tax Increase: Immiseration Not Stimulation"
date: "2009-02-04"
categories: ["Economics", "Fiscal Policy", "Monetary Policy"]
---

I have an op-ed in [The Australian](http://www.theaustralian.news.com.au/story/0,25197,25004488-7583,00.html "The Australian"), arguing that the government has just announced a \$42 billion future tax increase.  In reality, it’s worse than that because of the interest bill on the \$42 billion in unfunded spending, plus the future welfare costs associated with an increased tax burden and the government’s diversion of resources away from potentially more highly valued uses.  The package will immiserate rather than stimulate.

In the [statement](http://rba.gov.au/MediaReleases/2009/mr_09_01.html "statement") accompanying yesterday’s 100 basis point cut in the official cash rate, the Reserve Bank said that ‘the Board took into account the package of measures announced by the Government earlier today.’  If the RBA shares the Treasury’s Keynesian assumptions about the implications of the package for short-term economic growth, then it is entirely possible that yesterday’s rate cut was smaller than it might have been in the absence of the latest fiscal stimulus package.  While fiscal policy has been irrelevant to monetary policy in recent years due to a steady fiscal impulse, it is less likely the RBA will ignore the massive turnaround in the budget balance we have seen since May last year.  Those ‘free’ pink batts are likely to have come at the cost of a higher mortgage interest rate.
