---
title: "A Carling-Kirchner Ticket?"
date: "2009-07-15"
categories: ["Economics", "Fiscal Policy"]
---

Robert Carling and I have an [op-ed](http://www.theaustralian.news.com.au/story/0,25197,25783307-7583,00.html "op-ed") in today’s Australian on our proposals to reform Australia’s federal fiscal responsibility legislation.

‘[Henry Thornton](http://www.theaustralian.news.com.au/business/story/0,28124,25785512-30538,00.html "Henry Thornton")’ responds:

> Pardon my cynicism, but I see Australia as a long way from establishing another “self-binding” system, one that enforces long-term economic rationality on the government of the day.
>
> Carling and Kirchner might consider offering themselves for election at the next federal election, and see how enthusiastically this plan is embraced by the voters.

Thornton underestimates voters.  There is a reason Kevin Rudd claimed to be a fiscal and economic conservative when running for office.  The federal opposition now campaigns on debt and deficits because it thinks it will play well with voters. 

Our proposal offers a framework through which politicians could make a credible commitment to fiscal responsibility, so that voters would no longer need to rely on politicians promises in relation to fiscal policy. 

The idea of linking politicians pay to fiscal performance is also likely to be popular, not least because politicians have long argued that private sector pay should be tied to performance.  As Mark Latham demonstrated in relation to parliamentary superannuation, if a major party were to run with our proposal, it would be very hard for the other side of politics to argue against it.
