---
title: "A New Era in FDI Protectionism?"
date: "2009-04-24"
categories: ["Economics", "Foreign Investment"]
---

The conditional approval of Minmetals’ acquisition of OZ Minerals’ assets under the Foreign Acquisitions and Takeovers Act marks what may well be a new era in FDI protectionism.  Indeed, the Treasurer’s [press release](http://www.treasurer.gov.au/DisplayDocs.aspx?doc=pressreleases/2009/043.htm&pageID=003&min=wms&Year=&DocType= "press release") states explicitly that the conditions and undertakings required of Minmetals ‘are designed to protect around 2000 Australian jobs.’  Some of these conditions, such as the requirement to ‘comply with Australian industrial relations law and honour employee entitlements’ are legal obligations of any company operating in Australia, regardless of ownership, and are therefore completely redundant.  The reporting requirements imposed on the company are also already required under the Corporations Act.  This is a perfect illustration of how scrutiny of FDI under the FATA adds nothing to the regulation of business investment in Australia. The FATA’s only real purpose is to serve as a vehicle for political intervention in the market for foreign ownership and control of Australian equity capital.

In this case, political intervention has resulted in some extraordinarily prescriptive conditions in relation to both corporate governance and operational matters.  For example, Minmetals is required to: 

> 1\. continue to operate the Century, Rosebery and Golden Grove mines at current or increased production and employment levels;\
> 2. pursue the growth of the following projects:\
> 1. the Century mine in Queensland, by the continuation of exploration activities for ore and/or the conversion or later sale of the plant so that it can produce a phosphate concentrate; and\
> 2. the Rosebery mine in Tasmania, which with further exploration and development work, could continue to operate well beyond current mine life or at levels beyond current production rates; and\
> 3. reopen Avebury (nickel) in Tasmania and develop Dugald River (zinc) in Queensland;
>
> subject in each case to project feasibility and economic fundamentals permitting.

The weasel clause is, of course, ‘economic fundamentals permitting.’  Since there is no legal basis for determining ‘economic fundamentals’, these conditions are meaningless, except that the Treasurer has powers under the FATA to order divestment by foreign persons.  The conditions could conceivably be used to rationalise a future divestment order, but there is no need to demonstrate a breach of these undertakings for the Treasurer to exercise his powers under the Act.

The current government is sending increasingly strong signals to prospective foreign investors that they will have to conduct their business operations in Australia in accordance with politically-determined requirements and objectives rather than according to the rule of law.

Sadly, the government’s increasingly prescriptive regulation of FDI is no different from the [protectionist views](http://www.institutional-economics.com/index.php/section/index/peter_costello_economic_nationalist "protectionist views") of Liberal backbencher and former Treasurer, Peter Costello.  With a seemingly bipartisan consensus in favour of FDI protectionism, foreign investors could be forgiven for looking elsewhere.  Indeed, China’s National Development and Reform Commission [withheld approval](http://business.theage.com.au/business/china-puts-brakes-on-hunan-bid-20090414-a6b5.html "withheld approval") for Hunan Valin Steel’s bid for 17% of Fortescue Metals on the grounds that Canberra’s conditions were too onerous and set a bad precedent.  Australia’s regulation of FDI offends even Chinese central planners.
