---
title: "Absolute Greed"
date: "2009-10-16"
categories: ["Economics", "Financial Markets"]
---

The rhetoric of class hatred from [Prime Minister Kevin Rudd](http://www.abc.net.au/news/stories/2009/10/16/2715667.htm "Prime Minister Kevin Rudd"):

> *If you want a definition of social injustice this was it in brutal colour - millions of innocent workers losing their jobs because a few thousand financial executives around the world surrendered any pretence of social responsibility in their blind pursuit of absolute greed.*

The facts from the AEI’s [Peter Wallison](http://online.wsj.com/article/SB10001424052748704107204574475110152189446.html "Peter Wallison"):

> Mortgage brokers had to be able to sell their mortgages to someone. They could only produce what those above them in the distribution chain wanted to buy. In other words, they could only respond to demand, not create it themselves. Who wanted these dicey loans? The data shows that the principal buyers were insured banks, government sponsored enterprises (GSEs) such as Fannie Mae and Freddie Mac, and the FHA—all government agencies or private companies forced to comply with government mandates about mortgage lending. When Fannie and Freddie were finally taken over by the government in 2008, more than 10 million subprime and other weak loans were either on their books or were in mortgage-backed securities they had guaranteed. An additional 4.5 million were guaranteed by the FHA and sold through Ginnie Mae before 2008, and a further 2.5 million loans were made under the rubric of the Community Reinvestment Act (CRA), which required insured banks to provide mortgage credit to home buyers who were at or below 80% of median income. Thus, almost two-thirds of all the bad mortgages in our financial system, many of which are now defaulting at unprecedented rates, were bought by government agencies or required by government regulations.
>
> The role of the FHA is particularly difficult to fit into the narrative that the left has been selling. While it might be argued that Fannie and Freddie and insured banks were profit-seekers because they were shareholder-owned, what can explain the fact that the FHA—a government agency—was guaranteeing the same bad mortgages that the unregulated mortgage brokers were supposedly creating through predatory lending?
>
> The answer, of course, is that it was government policy for these poor quality loans to be made.
