---
title: "Akerlof and Shiller’s Economic Authoritarianism"
date: "2009-04-30"
categories: ["Economics", "Financial Markets"]
---

My review of George Akerlof and Robert Shiller’s *Animal Spirits: How Human Psychology Drives the Economy and Why It Matters for Global Capitalism* (Princeton: Princeton University Press, 2009), below the fold.

*Animal Spirits* attempts to marry behavioural economics with Keynesian macroeconomics to explain how the economy ‘really works’, while making the case for government intervention as a counterweight to the cyclical behaviour of the economy and asset prices.  ‘Animal spirits’ is borrowed from Keynes’ *General Theory* and is defined by the authors as ‘a restless and inconsistent element in the economy.  It refers to our peculiar relationship with ambiguity and uncertainty’ (p. 4).  The idea of animal spirits is by no means unique to Keynes, who was clearly influenced by the Chicago School’s Frank Knight in distinguishing between quantifiable risks and unquantifiable uncertainties and their implications for economic decision-making.

Akerlof and Shiller maintain that it is animal spirits that drive the business cycle and that mainstream economics neglects the role of psychology, informal narratives and notions of fairness in influencing economic behaviour.  Economists have long used measures of consumer and business confidence to gauge the strength of economic activity.  However, when we control for the influence of other economic variables, confidence is usually found to have little or no predictive power for economic activity.  The clear implication is that it is economic activity that drives confidence, not the other way around.  Akerlof and Shiller are well aware of these results, but argue that ‘such tests are actually of limited value’ (p. 17) because ‘there are no standard ways to quantify the psychology of people’ (p. 140).  This is true enough, but it also happens to be just a little too convenient for their argument.  Consistent with their focus on ‘stories’, Akerlof and Shiller never let the facts get in the way of a good one. 

Akerlof and Shiller claim that ‘there is an easy and simple test to prove that what we are saying is correct…we think that our description of how the economy operates fits almost any business cycle’ (p. 168-169).  In reality, this is no test at all.  A heavily stylised account that claims to fit every set of business cycle facts is too successful to be credible.  It is a theory of everything and nothing.  Austrian business cycle theorists also claim they can account for every historical business cycle, but in practice, many Austrian economists have turned their theory into little more than a fundamentalist cult. 

How are we to adjudicate between these competing accounts?  We need both theory and evidence to answer these questions, but Akerloff and Shiller have no shame in admitting they cannot support their most basic propositions.  They freely concede they cannot establish the central claim for which Shiller is most famous, noting that ‘one cannot decisively prove that the stock market has been irrational.’  Instead, they make an argument that would never be accepted coming from an undergraduate: ‘in all of this debate, no one has offered any real evidence to think that the volatility *is* rational’ (p. 132-133, emphasis in original).  In my Centre for Independent Studies Policy Monograph, *[Bubble Poppers](http://www.cis.org.au/policy_monographs/pm93.pdf "Bubble Poppers")*, I discuss this very common confusion of volatility with irrationality.  Akerlof and Shiller actually undermine the argument in Shiller’s *Irrational Exuberance*, when they note in passing that ‘there has been one way, at least in the past, in which almost everyone could become at least moderately rich…Invest it for the long term in the stock market, where the rate of return after adjustment for inflation has been 7% per year’ (p. 117).  This is not what Shiller was [telling people in 1996](http://www.econ.yale.edu/~shiller/data/peratio.html "telling people in 1996"), when he said that ‘long run investors should stay out of the market for the next decade.’

Akerlof and Shiller implicitly or explicitly reject the major post-war advances in macroeconomic thought in their attempt to rehabilitate discredited economic doctrines.  In particular, they argue that there is a long-run trade-off between inflation and unemployment that is attributable to ‘money illusion’.  They invoke the efficiency wage theory and the well-known inflexibility of nominal wages as evidence for money illusion.  Although the failure of labour markets to clear like goods markets is to some extent still an unsolved puzzle in macroeconomics, money illusion is neither necessary nor sufficient to explain it.  There are plenty of alternative explanations for the disequilibrium behaviour of labour markets that do not rely on money illusion and the existence of nominal wage rigidities is not necessarily evidence of money illusion. 

There is a very simple test for the existence of money illusion: surveys of consumers’ inflation expectations.  These surveys suggest that, on average, people have a good understanding of the inflation process.  Inflation expectations help forecast future inflation (the coefficient instability noted in a footnote by the authors is an econometric rather than a substantive issue).  The whole point of inflation targeting, which the authors believe causes unemployment (p. 114), is to anchor long-run inflation expectations so as to *minimise* the economic importance of money illusion.  In noting that anti-inflationary monetary policies are often associated with increases in unemployment, Akerlof and Shiller in no way invalidate the view that there is no long-run trade off between inflation and unemployment.  The authors even suggest that a dated penalty notice on a Boston train is evidence of money illusion (p. 41) instead of the more prosaic explanation that the law has not kept pace with inflation.  It is not surprising that the authors patronise Milton Friedman as ‘the boy who knew how to spell banana but did not know when to stop’ (p. 108). 

In discussing responses to the current crisis, Akerlof and Shiller argue that ‘macroeconomic planners…must also make a plan – we might call it a target or an intermediate target – for the amount of credit of different sorts that is to be granted.  This target should correspond to the credit that would normally be given if the economy were at full employment.  The target should not be merely a mechanical credit aggregate, but should reflect the more general condition that credit be available for those who, under normal circumstances, would be deserving of it’ (p. 89).  The idea that credit growth can be restored independently of the demand for it is bad enough, but to suggest that the authorities should also allocate the supply of credit to the ‘deserving’ is little different from Soviet-style central planning.

Akerlof and Shiller’s authoritarianism is evident in their effusive praise for systems of forced saving in Singapore and China, which they compare favourably to the (mismeasured) saving performance of the US and other Western economies.  They ludicrously suggest that Lee Kuan Yew ‘may be one of the most important economic thinkers of the twentieth century.  His high-saving economy became a model for China, which has copied Singapore’s saving achievement’ (p. 125).  Akerlof and Shiller are surely not unaware of the fact that high saving rates in both countries are a function of political and economic repression, in which the state overrides individual preferences in relation to consumption and saving, imposes capital controls, manages the exchange rate and directs investment spending.  By implication, Akerlof and Shiller support all these policies, of which high saving rates are but a by-product.  They view individuals as incapable of making appropriate choices between consumption and saving.  This reflects their view that capitalism ‘does not automatically produce what people really need; it produces what they *think* they need’ (p. 26, emphasis in original).  Left to their own devices, people will undersave, so ‘saving policy has an important role in correcting for their failures’ (p. 130).  They maintain that high saving leads to economic growth, but ignore the fact that as income rises, financial innovation and the use of debt to smooth life-time consumption also increases, at least in a free market economy. 

Akerlof and Shiller claim that their work ‘provides an answer to a conundrum: Why did most of us utterly fail to foresee the current economic crisis?’ (p. 167).  Yet this supposed ‘failure’ is entirely consistent with a rational expectations interpretation of the economy.  If events such as the global financial crisis could be forecast with any certainty, policymakers and the public would take action to avert them.  The crisis is a crisis precisely *because* it was unforeseen.  From a rational expectations perspective, these events are unforecastable almost by definition.  While financial crises are necessarily unforecastable, this is not the same as saying that mainstream economics cannot explain the latest crisis *ex post*.  The behavioral economics of Akerlof and Shiller, by contrast, suffers from an inescapable paradox that flows from their elitist and arrogant assumption that only they know the true model of the economy, while everyone else is trapped in a morass of cognitive bias and confusion.  If everyone read Akerlof and Shiller and came to understand the way the economy ‘really works’, much of their analysis would no longer apply, unless we assume that people are either incapable of learning or are willfully ignorant.

With *Animal Spirits*, Akerlof and Shiller have further demonstrated how behavioural economics has been captured by an authoritarian political agenda that is leveraging off the financial crisis to attack and undermine the basic institutions of a liberal economic order.  Behaviouralism now serves mainly as an excuse to dump all that the economics profession has learned over the last 60 years and replace it with an elitist paradigm in which only the anointed few know the true model of the economy and institute policies to give the muddled masses what they really need, as opposed to what they think they want.  Needless to say, Akerlof and Shiller conclude by stressing ‘the urgency for setting up the committees and commissions to develop the reforms in financial institutions and the regulations that are so immediately needed’ (p. 176).  Akerlof is a Nobel laureate, but as with Paul Krugman and Joe Stiglitz, *Animal Spirits* shows that a Nobel prize is no barrier to being an authoritarian economic crank.
