---
title: "All Praise Lu Kewen Thought!"
date: "2009-03-18"
categories: ["Economics", "Politics"]
---

The [over-stretched](http://www.theaustralian.news.com.au/story/0,25197,25202547-5013480,00.html "over-stretched") Department of Foreign Affairs and Trade makes the thought of the [legendary Lu Kewen](../2008/the_legendary_lu_kewen.qmd "legendary Lu Kewen") [available to the benighted masses of G20 nations](http://www.theaustralian.news.com.au/story/0,25197,25203447-601,00.html "available to the benighted masses of G20 nations"):

> KEVIN Rudd believes in spreading the good word - particularly his own good words on the evils of greedy neo-liberals - and doesn’t mind using the Department of Foreign Affairs and Trade as a worldwide publishing agent.
>
> The Prime Minister decided his 7700-word essay on the origins of the global financial crisis deserved a world audience before the G20 financial summit in London next month.
>
> The essay, which argues for more global regulation of financial markets and says capitalism is “cannibalising itself”, is being distributed around the world through Australian embassies and high commissions…
>
> Mr Rudd’s essay is now intended for world publication before the crisis meeting of the world’s top 20 economies in London on April 2.
