---
title: "Anglo-American Outperformance"
date: "2009-02-14"
categories: ["Economics", "Financial Markets"]
---

The Anglo-American economies are outperforming in the current global economic downturn, as [Chris Dillow](http://stumblingandmumbling.typepad.com/stumbling_and_mumbling/2009/02/what-anglo-saxon-instability.html "Chris Dillow") observes:

> The “Anglo Saxon” model - lightly-regulated financial markets and high debt - makes their economies unusually vulnerable to boom and bust…
>
> This has become conventional wisdom. Today’s figures, though, seem to contradict it. They show that euro zone fell 1.5% in Q4 (6% annualized!), as much as it did in the UK and more than in the US. With next week’s figures likely to show a huge fall in Japanese GDP, this means that the major “non-Anglo” economies are doing at least as bad as the US and UK.

As Chris notes, this is partly due to the exposure of the non-Anglo-American economies to highly cyclical manufacturing industries.  However, the importance of manufacturing to these economies is itself a function of the mistaken strategic industry and trade policies pursued by these countries.

The cyclical outperformance of the Anglo-American economies reflects their structural outperformance, which affords them higher trend growth rates around which their economies cycle.  Japan’s trend growth rate of around 1.5%-2% is so low that it takes only a modest downturn to throw its economy into recession, which is why Japan experiences so many of them.

Fiscal stimulus packages and other interventionist policy responses in the Anglo-American economies will undoubtedly hurt their structural performance.  However, these polices are no worse than those being pursued elsewhere, so the Anglo-American economies and asset markets still have scope to outperform in the context of the current downturn.

It should not be surprising then that those who followed the asset allocation advice of some of the leading permabears are now seeing their portfolios underperform.
