---
title: "‘Attacking Iran is a Shovel-Ready Project’"
date: "2009-02-06"
categories: ["Economics", "Fiscal Policy"]
---

[Robert Barro](http://business.theatlantic.com/2009/02/an_interview_with_robert_barro.php "Robert Barro") interviewed in *The Atlantic*.

On Obama’s fiscal stimulus bill:

> *This is probably the worst bill that has been put forward since the 1930s. I don’t know what to say. I mean it’s wasting a tremendous amount of money. It has some simplistic theory that I don’t think will work, so I don’t think the expenditure stuff is going to have the intended effect. I don’t think it will expand the economy. And the tax cutting isn’t really geared toward incentives. It’s not really geared to lowering tax rates; it’s more along the lines of throwing money at people. On both sides I think it’s garbage. So in terms of balance between the two it doesn’t really matter that much.*

On Paul Krugman:

> *He just says whatever is convenient for his political argument. He doesn’t behave like an economist.*

On war as stimulus:

> *I think the best evidence for expanding GDP comes from the temporary military spending that usually accompanies wars—wars that don’t destroy a lot of stuff, at least in the US experience. Even there I don’t think it’s one for one, so if you don’t value the war itself it’s not a good idea. You know, attacking Iran is a shovel-ready project. But I wouldn’t recommend it.*
