---
title: "Bankruptcy and the Rule of Law in the US"
date: "2009-06-01"
categories: ["Economics"]
---

[James Glassman](http://www.nytimes.com/2009/05/30/opinion/30glassman.html?_r=1&ref=opinion "James Glassman") on the decline of the rule of law in the United States:

> I head a nonprofit group that encourages developing nations to adopt policies that will lead to prosperity — starting with transparency and the rule of law — and hold up America as a model. Yet in its high-handed dealings with Chrysler and G.M., the Obama administration reminds me of an irresponsible third-world regime, skirting the law and handing economic prizes to political cronies…
>
> What lesson does federal favoritism toward Chrysler and G.M. teach other businesses that play by the rules? How will our trade negotiators keep a straight face when complaining about subsidies to Airbus or Chinese steel makers? The government should have stepped aside earlier and allowed a normal bankruptcy that would have treated the union and the debt-holders fairly.

As [P J O’Rourke](http://online.wsj.com/article/SB10001424052970203771904574173401767415892.html "P J O’Rourke") notes, bankruptcy is the norm rather than the exception for the US car industry:

> *American cars have been manufactured mostly by romantic fools. David Buick, Ransom E. Olds, Louis Chevrolet, Robert and Louis Hupp of the Hupmobile, the Dodge brothers, the Studebaker brothers, the Packard brothers, the Duesenberg brothers, Charles W. Nash, E. L. Cord, John North Willys, Preston Tucker and William H. Murphy, whose Cadillac cars were designed by the young Henry Ford, all went broke making cars. The man who founded General Motors in 1908, William Crapo (really) Durant, went broke twice. Henry Ford, of course, did not go broke, nor was he a romantic, but judging by his opinions he certainly was a fool.*
