---
title: "Big Government Will Hinder Growth"
date: "2009-05-14"
categories: ["Economics", "Fiscal Policy"]
---

I have an op-ed in today’s [Australian](http://www.theaustralian.news.com.au/story/0,25197,25475539-7583,00.html "Australian") on the ‘economic conservatives’ who have turned into the biggest spending government since Gough Whitlam:

> THE 2009 budget forecasts the biggest expansion in federal government spending since Gough Whitlam. While the budget deficit is being sold as a necessary response to the worst global economic downturn since the Depression, government spending will hinder growth long after Australia’s recession is over.
>
> The Government has made much of the reduction in revenue flowing from the global downturn and the resulting domestic recession. But this is only one side of the budget deficit equation. The unprecedented deterioration in the budget balance is also driven by the biggest increase in government spending in a generation.
>
> The federal government spending share of gross domestic product will increase by 2.6 percentage points this financial year, with a further increase of two percentage points forecast for next financial year, the biggest increases since the early 1970s. Government spending will reach 28.6per cent of GDP in 2009-10, a figure unprecedented in peacetime.
>
> It is appropriate that the Government should allow the automatic stabilisers to work in response to an economic downturn.
>
> However, the deterioration in the budget balance has been made worse by discretionary fiscal stimulus packages of doubtful effectiveness.
