---
title: "Blame it on Rio"
date: "2009-03-29"
categories: ["Economics", "Foreign Investment"]
---

[John Durie](http://www.theaustralian.news.com.au/business/story/0,28124,25252371-5013408,00.html "John Durie") sees straight through Treasurer Wayne Swan:

> FEDERAL Treasurer Wayne Swan went to extraordinary lengths not to make a ruling on Chinese investment in Australia’s resources industry by partially knocking back the OZ Minerals deal.
>
> His excuse was as lame as they get: the Chinese rescue could not include the Prominent Hill copper and gold mine because it was too close to the defence facility at Woomera in South Australia.
>
> The mine is 162km from the facility and to define it as being of strategic importance is a stretch of extraordinary proportions.
>
> If China or anyone wanted to spy on Woomera, and few would, all you would need to do would be to log on to Google Earth rather than pay more than \$4 billion to buy a gold and copper mine…
>
> For a Government that boasts about its good work in helping the country through the recession, this decision says the exact opposite…
>
> Swan’s non-decision has made an already murky part of Government even murkier.

Apparently, Chinese miners are more of a security risk than the [Russians](http://www.space.com/missionlaunches/launches/russia_spacelift.html "Russians").
