---
title: "Boondoggle Nation"
date: "2009-05-26"
categories: ["Economics", "Fiscal Policy"]
---

RBA Board member [Warwick McKibbin](http://www.theaustralian.news.com.au/story/0,25197,25538672-601,00.html "Warwick McKibbin"), on the effectiveness of activist fiscal policy:

> “Most fiscal policy doesn’t do anything except switch spending from one period to another,” the RBA director said.
>
> “When you change fiscal policy, all you do is stimulate the economy today out of future possible growth.”
>
> Stimulus spending had to be paid for either with higher future taxes or reduced opportunities for the private sector so that the public sector could be financed.
>
> “The only exceptions are infrastructure and similar spending, which raises the return to private activities,” Professor McKibbin said.
>
> “The most sustainable way of reducing a fiscal deficit is through strong productivity growth in the private sector.”
>
> He said that in mature economies, it was hard to engineer productivity growth.

Whether public infrastructure spending increases private sector productivity is a case-by-case judgement.  As the rest of the story makes clear, much of the government’s stimulus spending consists of little more than electoral boondoggles such as swimming pools and sports stands.
