---
title: "‘Bubble’ Popping at Treasury and the BoE"
date: "2009-06-17"
categories: ["Economics", "Financial Markets", "Monetary Policy"]
---

The Australian Treasury’s [David Gruen](http://www.treasury.gov.au/documents/1564/HTML/docshell.asp?URL=Sydney_Institute_Speech.htm "David Gruen") on monetary policy and asset prices:

> Some have suggested that, rather than simply being a contributing factor, expansionary US monetary policy in the early 2000s was the main cause of the crisis.
>
> Expansionary US monetary policy undoubtedly contributed to rising US asset prices, including house prices, at the time. Indeed, that is the point of the policy – rising asset prices constitute one of the ways that expansionary monetary policy works.
>
> But I have less sympathy with the argument that monetary policy should explicitly ‘lean against the wind’ of a suspected inflating asset price bubble, which is implicit in the criticism of US monetary policy at that time.
>
> In my view, to lean against the wind and do more good than harm requires a level of understanding about the likely future path of a suspected asset bubble that is simply unrealistic. Without that understanding, attempting to use monetary policy to lean against the wind is as likely to be destabilising for the wider economy as it is to be stabilising.

It is good to see that Adam Posen, author of one of the better social democratic [critiques](http://www.iie.com/publications/wp/wp06-1.pdf "critiques") of ‘bubble’ popping, has just been [appointed](http://www.hm-treasury.gov.uk/press_55_09.htm "appointed") to the BoE’s MPC.
