---
title: "Canberra is the Problem, Not Beijing"
date: "2009-04-01"
categories: ["Economics", "Foreign Investment"]
---

I have a column in today’s [Business Spectator](http://www.businessspectator.com.au/bs.nsf/Article/Fear-Canberra-not-Beijing-$pd20090401-QNQWS?OpenDocument "Business Spectator") arguing that it is Australia’s regulatory regime for FDI that is responsible for perceptions of inappropriate Chinese influence over the federal government:

> China may well have the world’s most restrictive FDI regime, but Australia has the fifth most restrictive regime, based on one OECD measure. Australia’s highly politicised FDI controls more closely resemble those found in China and Russia than comparable countries like the United Kingdom and the United States. Is it any wonder that Chinese politicians finds themselves on familiar ground when lobbying Australian politicians over potential acquisitions?
>
> If Australians are really concerned about the potential for Chinese influence over foreign investment policy, they should support making Australia’s regulatory regime for FDI less like China’s and more like the UK’s.
>
> The priority for any reform should be removing ministerial discretion from the FDI approval process. This is the main source of the politicisation of foreign investment in Australia and the nexus for potential influence-peddling by sectional interests, including by foreign firms and governments…
>
> The real scandal is not the potential for Chinese influence over Australian politicians. It is the Whitlam-era, Chinese-style foreign investment regulatory regime we have inflicted on ourselves.
