---
title: "CIS Policy Point Lecture: Stern Hu and Stern China"
date: "2009-08-24"
categories: ["Economics", "Foreign Affairs & Defence"]
---

CIS Policy Point Lecture: Stern Hu and Stern China - Why Beijing did it and what it means for Australia-China Relations.

Since the arrest of Rio Tinto executive Stern Hu in mid July, Beijing has stood firm by reiterating several times that evidence against Mr. Hu for commercial espionage causing massive losses to the Chinese state is serious and irrefutable. What has Stern Hu actually done, why has China chosen to charge Mr. Hu and others for espionage, rather than commercial theft, and what will the consequences of this action be for diplomatic and political relations between Australia and China? Join research fellow at CIS and visiting fellow at the Hudson Institute in Washington, Dr John Lee and Paul Kelly, Editor-at-Large of The Australian, as they discuss this issue.

Venue: The Library, The Centre for Independent Studies, Level 4, 38 Oxley Street, St Leonards.\
Parking is available across the road at the Hume Street Car Park.

Date: Tuesday, 25 August 2009\
Time: 6:00pm – 7:15pm followed by drinks.

Cost: Members – free, Non Members \$10 payable in advance by credit card.

Booking: Places are limited and reservations essential. To book please email CIS Events Assistant, Alanna Elliott, at aelliott AT cis.org.au or call (02) 9438 4377.
