---
title: "Colloque Lippmann 71 Years On: Paris 1938 versus New York 2009"
date: "2009-02-27"
categories: ["Economics"]
---

Blogging will be light at best in coming weeks.  New member registrations will be queued and comments temporarily disabled.

I will be busy attending a special meeting of the [Mont Pelerin Society](http://www.montpelerin.org/mpsAbout.cfm "Mont Pelerin Society") along with a Liberty Fund conference in New York.  Readers who will be at either event, feel free to get in touch.

The Mont Pelerin Society had a less well known precursor that met in Paris in August 1938, discussed in a recent [article](http://www.standpointmag.co.uk/node/828/full "article") by Jeremy Jennings.  Many people have traced the origins of so-called ‘neo-liberalism’ to this meeting, but Jennings (a leading scholar of socialist thought) notes that the Colloque Lippmann could just as easily be viewed as contributing to the idea of a ‘social market economy’ in post-war Germany (something you won’t hear from Kevin Rudd). 

New York 2009 hopefully won’t be quite as scary as Paris 1938.  But it’s a close call.
