---
title: "Complete Confusion"
date: "2009-10-24"
categories: ["Economics", "Foreign Investment"]
---

You know it’s Friday whenever the government slips out another late afternoon FDI approval.  The government continues to micro-manage FDI in Australia, with another [long list of conditions](http://ministers.treasury.gov.au/DisplayDocs.aspx?doc=pressreleases/2009/081.htm&pageID=003&min=njsa&Year=&DocType= "long list of conditions") attached to Yanzhou Coal Mining Company Limited’s acquisition of Felix Resources, while creating even [more uncertainty](http://www.theaustralian.news.com.au/story/0,25197,26251680-643,00.html "more uncertainty") about government policy:

> One adviser to Chinese companies trying to invest in Australian resources, who has had potential takeovers of Australian public companies quashed by FIRB before they were made public, expressed frustration at the lack of consistency.
>
> “It creates complete confusion as to what the policy is,” he said.
>
> “All we can see is that there is no policy.”
>
> Senator Sherry’s office would not comment on what could be gleaned from the decision in terms of policy.

Because there is none.
