---
title: "Debunking Bad Narratives on Stimulus"
date: "2009-06-05"
categories: ["Economics", "Financial Markets", "Fiscal Policy", "Monetary Policy"]
---

[Henry Ergas](http://www.theaustralian.news.com.au/story/0,25197,25588239-7583,00.html "Henry Ergas") responds to the [21 economists](http://andrewleigh.com/?p=2104 "21 economists") rounded-up by Nic Gruen to defend the federal government’s stimulus measures (as if the government were not big and ugly enough to defend itself):

> The open letter 21 highly respected Australian economists published earlier this week in The Australian Financial Review strikingly illustrates the trend. Endorsing the “too much rather than too little” approach, that letter claims “there is no more effective way to stimulate the economy” than cash handouts.
>
> In reality, the efficacy of that spending is far from established. Rather, much as economic theory would predict, the striking fact is just how smooth the path of consumption has been, despite a substantial spike in income associated with the Government’s cash splash.

Sinclair Davidson makes similar points in [The Age](http://business.theage.com.au/business/the-recession-no-ones-sure-were-having-20090604-bx7w.html "The Age"):

It would be surprising indeed if the 21 economists were prepared to defend any of the \$800 million in ‘community infrastructure’ boondoggles listed [here](http://www.economicstimulusplan.gov.au/community_infrastructure/pages/default.aspx "here"). 

[RBA Governor Glenn Stevens](http://rba.gov.au/Speeches/2009/sp_gov_040609.pdf "RBA Governor Glenn Stevens") has also been out highlighting the limits of macro policy stimulus:

> *Macroeconomic policies have not been able to prevent an economic downturn. They rarely can, especially in the face of a global recession of this magnitude. Indeed, attempts to do so have as often as not run into trouble by stoking up bigger problems a few years down the track.*
