---
title: "Does the RBA Still Feed the Media Chooks?"
date: "2009-10-07"
categories: ["Economics", "Financial Markets", "Media", "Monetary Policy"]
---

Speculation about [RBA media backgrounding](http://www.businessspectator.com.au/bs.nsf/Article/interest-rate-RBA-hike-Gittins-Mitchell-pd20091007-WL6C8?OpenDocument&src=sph "RBA media backgrounding") in relation to future interest rate decisions is back again.  Even if no such backgrounding has taken place, the perception that this still occurs is very damaging, not only for the integrity of financial markets, but also for the supposed beneficiaries of the backgrounding.  It is well understood that politicians engage in selective leaks in order to control journalists.  There is nothing more damaging to the credibility of a press gallery journalist than to be seen as the mouthpiece for a politician.  The relationship between the RBA and journalists should not be viewed any differently.

The RBA could put a stop to the speculation by denying that the practice takes place or at least foreswearing its use in future.  Not only would this benefit the integrity of financial markets, it would also give us more confidence that the rather generous treatment the RBA receives from many in the media was actually deserved.
