---
title: "FDI Liberalisation Falls Short"
date: "2009-08-05"
categories: ["Economics", "Foreign Investment"]
---

Following hot on the heels of the New Zealand government’s announcement of reforms to its regulation of foreign direct investment, the Australian Treasurer has also [announced](http://ministers.treasury.gov.au/DisplayDocs.aspx?doc=pressreleases/2009/088.htm&pageID=003&min=wms&Year=&DocType= "announced") changes to the thresholds for screening FDI applications.  My take on the changes can be found in an op-ed in The Canberra Times today (text below the fold).  I’m also quoted on the subject in a story on page three of the AFR today.

The federal Treasurer has announced measures to liberalise Australia’s regulatory regime for foreign direct investment (FDI).  While a step in the right direction, the reforms do nothing to address the continued uncertainties created by the Treasurer’s open-ended discretion to reject foreign investment proposals under the Foreign Acquisitions and Takeovers Act.

The government’s reforms are the most significant liberalisation of Australia’s regulatory regime for FDI since the Australia-US Free Trade Agreement came into effect in 2005.  It follows last week’s announcement by New Zealand’s National Party-led government that it will liberalise its scrutiny of FDI applications, placing increased competitive pressure on Australia in attracting foreign investment.

The government’s reforms will reduce the number of foreign investment proposals requiring screening by combining the current four thresholds for review into a single threshold of a 15% stake in businesses worth \$219 million or more.  The new single threshold will also be indexed to inflation to ensure that the screening process no longer becomes increasingly restrictive by default.

Potential United States investors will still be subject to the higher threshold of \$953 million under the Australia-US Free Trade Agreement that is already indexed to inflation.

The higher single threshold will reduce the number of business applications requiring approval by around 20%, reducing costs and uncertainties not only for foreign investors but also the Australian vendors of domestic assets.

However, the government has missed an opportunity to deliver a more substantial reform of Australia’s foreign investment regulatory regime.  In particular, the government could have raised the new single review threshold to converge with the more liberal benchmark set by the Australia-US Free Trade Agreement. 

More seriously, the reforms do not address the problems that Australia’s regulatory framework presents for larger investment proposals that will still be caught in the screening process.

At the heart of these problems is the enormous discretion the Treasurer continues to enjoy under the Foreign Acquisitions and Takeovers Act to reject foreign investment applications on the basis of an open-ended ‘national interest’ test.

This discretion causes enormous uncertainty for foreign investors, while adding nothing useful to the overall regulatory framework for business investment in Australia.  The Foreign Investment Review Board already defers to the Australian Competition and Consumer Commission on key economic issues.

The only purpose the national interest test serves is to provide a mechanism for political intervention in the market for the ownership and control of Australian equity capital.

The Treasurer has increasingly used this discretion to micro-manage business in Australia by attaching conditions to foreign investment approvals.  Many of these conditions are redundant because they merely reiterate legal obligations with which all businesses operating in Australia must comply, regardless of ownership.

But some of these conditions have been absurdly prescriptive, ranging from governance arrangements to the levels of output and employment to be maintained at specific mining operations.  These conditions are explicitly protectionist in intent, with the Treasurer stating that they are aimed at protecting local jobs. 

Treasurer Swan has increasingly turned foreign investment policy into an arm of domestic industry and employment policy.  The message to foreign investors is that large investment proposals must not only run the gauntlet of ministerial approval, but also comply with politically-determined ministerial directions not otherwise mandated by Australian law.

Indeed, the Treasurer has even sought to micro-manage Australian investment in China through the conditions attached to Ansteel’s acquisition of an increased shareholding in Gindalbie Metals.  Among other conditions, Ansteel must maintain agreed levels of Australian participation in a pellet plant in China’s Liaoning Province.

The foreign investment approvals process lacks transparency and is not subject to administrative or judicial review.

This can only lead to foreign perceptions that FDI approvals in Australia are the outcome of a political process rather than the impartial application of the rule of law.  These perceptions are likely to be as damaging to Australia’s reputation as they have been for China’s.

Further reform is needed to remove ministerial discretion from the process.  This could be done by making the Foreign Investment Review Board an independent statutory body able to make binding recommendations to the Treasurer.

The current national interest test also needs to be replaced. 

Australia already has a robust framework for the regulation of business investment, regardless of ownership.  We should put more trust in that framework rather than ministerial discretion.
