---
title: "Five Reasons Why Fiscal Stimulus Won’t Work"
date: "2009-02-09"
categories: ["Economics", "Fiscal Policy"]
---

From [Henry Ergas](http://www.theaustralian.news.com.au/story/0,25197,25025517-7583,00.html "Henry Ergas"):

> *the expectation of future deficits may have immediate, adverse consequences for confidence and output. However, the Government’s announcement merely sets a vague commitment to return to surplus through future reductions in spending growth. It does not say how great the cuts in spending will need to be or where those cuts will be made, and it ignores the obvious point that if there is wasteful spending that can be cut tomorrow, it ought to be cut today.*

While fiscal stimulus is assumed to be popular, [opinion polling](http://www.theaustralian.news.com.au/story/0,25197,25026302-5013871,00.html "opinion polling") is remarkably divided on the issue:

> *According to the Newspoll survey, 57 per cent of voters believe the economic stimulus package, which includes \$12 billion in short-term cash giveaways to boost retail spending, will be good for the economy. Almost half those surveyed, 48 per cent, believe they would be personally better off as a result of the package.*
