---
title: "Gold as an Option on the End of the US"
date: "2009-09-17"
categories: ["Economics", "Financial Markets", "Gold"]
---

[Spengler](http://www.atimes.com/atimes/Global_Economy/KI15Dj08.html "Spengler") (aka David Goldman) makes the case for gold as a hedge against the Obama Administration:

> The scurrilous fringe of financial journalism likes to speculate as to when China will dump the dollar, without asking the obvious question: what would China do in the absence of the dollar? The billion people who inhabit China’s interior are no substitute for the 300 million in the American market. They have a fraction of the purchasing power, they have little access to financial services, they have no credit bureaus to calculate their capacity to carry debt, and they have no means to make liquid their limited assets through mortgage markets. Perhaps over a dozen years of Herculean efforts, the situation might be changed - but that is then, and this is now.
>
> The world not only is stuck with the United States for the time being, but wants to be stuck with the United States. But the Barack Obama administration’s attempt to substitute government spending for collapsing consumer spending makes US assets less attractive, while its attempt to diminish America power on dubious ideological grounds forces other countries to act as rivals, unsuited and unwilling as they might be to do so.
>
> That is why options on the end of the US are trading well in the form of the gold price. Gold will have no official role unless America’s international role really does collapse, and the world is reduced from a system of trust (or imperial dictates, which amounts to the same thing) to a kind of barter at the international level. That would be a situation much to be abhorred, but it is not to be excluded. The world may need an alternative to the dollar if Obama persists in his present course.
