---
title: "Government Bonds to Underperform?"
date: "2009-05-15"
categories: ["Economics", "Financial Markets", "Fiscal Policy"]
---

[Jeremy Siegel](http://finance.yahoo.com/expert/article/futureinvest/162715 "Jeremy Siegel"), on the poor prospects for returns on government bonds:

> 40 years ago \[US\] treasury bonds were yielding over 6.3 percent, about twice their yield today. It is mathematically impossible for government bonds to come close to matching those 12 percent returns in future decades. Stocks, on the contrary, can easily repeat their returns over the past four decades, since those returns were near their historical average…
>
> For the 55-year period from December 1925, when the well-known Ibbotson stock and bond series begins, through January 1982, total real government bond returns were negative. This means that, by rolling over in long-term government bonds, reinvesting all the coupons, and thereby taking no income, investors’ bond portfolios were sinking in value.
>
> Most strikingly, for the 40-year period from 1941 through 1981, government bond investors lost a whopping 62 percent of their value after inflation. A loss in purchasing power over this long a period has never happened in stocks. There has never even been a 20-year period when real returns in stocks have been negative. In fact, the worst 30-year real return for stocks is plus 2.6 percent per year, just slightly below the average real return investors earn with government bonds.
>
> Looking at today’s markets, the forward-looking prospects for government bonds are very poor. Yields on 30-year inflation-protected bonds are 2.3 percent, and yields are only 4 percent on 30-year Treasuries. In contrast, after stocks have fallen 50 percent from their previous high, as they did in March of this year, their subsequent 30-year real returns have always been in excess of 10 percent per year.
>
> The 40-year outperformance of government bonds over large stocks has ended.
