---
title: "HSBC to Retail Gold Bugs: Get Your Own Damn Vault, Ours is Full"
date: "2009-11-25"
categories: ["Economics", "Financial Markets", "Gold"]
---

Gold is all about capital gain (or loss, as the case may be).  After storage and insurance costs, gold has a negative yield.  These costs may be about to go up, with retail gold bugs being booted out of gold storage facilities to make way for institutional investors.  From the [WSJ](http://online.wsj.com/article/SB125902295608261455.html?mod=WSJ_hps_LEFTWhatsNews "WSJ"):

> Amid gold’s rise—it has gained 32% this year and reached a record on Monday—investors have been loading up on bullion and coins. One big problem now is where to store it. The solution from HSBC, owner of one of the biggest vaults in the U.S.: somewhere else.
>
> HSBC has told retail clients to remove their small holdings from its fortress beneath its tower on New York City’s Fifth Avenue. The bank has decided retail customers aren’t profitable enough and is demanding those clients remove their gold to make room for more lucrative institutional customers…
>
> HSBC’s decision has created a logistical nightmare for both the investors and the security teams in charge of relocating the gold, silver and platinum to new vaults across the country…
>
> HSBC is telling clients to either move their metal, or prepare for it to be delivered to their doorsteps. In a July letter, seen by The Wall Street Journal, HSBC said the precious metal “will be returned to the address of record… at your expense,” unless instructed otherwise. HSBC recommended clients move their holdings to Brink’s Global Services USA Inc., which has a vault in Brooklyn, N.Y.
