---
title: "‘I Have Been Corrupted, A Little’: How Spin-Resistant Are Economics Bloggers?"
date: "2009-11-06"
categories: ["Economics", "Financial Markets", "Politics"]
---

The US Treasury has been running high level briefing sessions for economic bloggers.  Officialdom has obviously recognised that bloggers are an influential voice and need to be managed like old media.  Fortunately, economics bloggers are proving a little more spin-resistant than Treasury perhaps expected.  Here is what [Naked Capitalism](http://www.nakedcapitalism.com/2009/11/curious-meeting-at-treasury-department.html "Naked Capitalism") thought about the briefing:

> *It wasn’t obvious what the objective of the meeting was (aside the obvious idea that if they were nice to us we might reciprocate. Unfortunately, some of us are not housebroken).*

And [Steve Waldman](http://www.interfluidity.com/posts/1257407150.shtml "Steve Waldman"):

> The second thing I’d like to discuss is corruption. Not, I hasten to add, the corruption of senior Treasury officials, but my own. As a slime mold with a cable modem, it was very flattering to be invited to a meeting at the US Treasury. A tour guide came through with two visitors before the meeting began, and chattily announced that the table I was sitting at had belonged to FDR. It very clearly was not the purpose of the meeting for policymakers to pick our brains. The e-mail invitation we received came from the Treasury’s department of Public Affairs. Treasury’s goal in meeting with us was to inform the public discussion of their past and continuing policies. (Note that I use the word “inform” in the sense outlined in a previous post. It is not about true or false, but about shaping behavior.)
>
> Nevertheless, vanity outshines reason, and I could not help but hope that someone in the bowels of power had read my effluent and decided I should be part of the brain trust. The mere invitation made me more favorably disposed to policymakers. Further, sitting across a table transforms a television talking head into a human being, and cordial conversation with a human being creates a relationship. Most corrupt acts don’t take the form of clearly immoral choices. People fight those. Corruption thrives where there is a tension between institutional and interpersonal ethics. There is “the right thing” in abstract, but there are also very human impulses towards empathy, kindness, and reciprocity that result from relationships with flesh and blood people. That, aside from “cognitive capture”, is why we should be wary of senior Treasury officials spending too much time with Jamie Dimon. It is also why bloggers might think twice about sharing a conference table with masters of the universe, public or private. Although the format of our meeting did not lend itself to forging deep relationships, I was flattered and grateful for the meeting and left with more sympathy for the people I spoke to than I came in with. In other words, I have been corrupted, a little.

In Australia, it is worth noting that most of the running on the issue of [RBA media backgrounding](../2009/the_rba_and_the_media_revisited.qmd "RBA media backgrounding") has been from new media like Business Spectator and bloggers, although old media have since picked-up the story too.  Spin control becomes a lot more difficult when dealing with a proliferation of unregulated media with no stake in the status quo.
