---
title: "In Search of the Real Austrian School"
date: "2009-01-02"
categories: ["Austrian School", "Economics"]
---

Time magazine’s economics columnist [Justin Fox](http://curiouscapitalist.blogs.time.com/2008/12/31/must-a-journalist-listen-to-the-true-believers-in-austrian-economics/#more-3754 "Justin Fox") goes in search of the real Austrian School:

> People in the U.S. who self-identify as believers in Austrian economics, though, tend to follow a much narrower path, that of Mises and his American disciple Murray Rothbard. They are extremely libertarian (at the first meeting of the Mont Pelerin Society, a libertarian group organized by Hayek in 1947, Mises stormed out saying “You’re a bunch of socialists”). They yearn for a return to the gold standard. Many possess a near-religious conviction that their beliefs are correct and that all other economic theories are pure folly. Some of them—I’m thinking here mainly of the crowd around Lew Rockwell—combine these beliefs with far loopier stuff. Others—such as financial pundits Peter Schiff and Michael Shedlock—often let their rabid Austrian leanings overpower (and, to my taste, ruin) otherwise trenchant economic analyses. Am I going to go to these people for perspective on the business cycle or Austrian economics? No, I don’t think so.
>
> On the other hand, I’m not going to do like Krugman and dismiss Austrian economics as “about as worthy of serious study as the phlogiston theory of fire.” Just because something is outside the mainstream doesn’t mean it’s wrong. I guess the best thing for me to do would be for me to read more of the source material myself. I’ve dabbled in Hayek and Schumpeter and even Rothbard. If I devoured all of Menger’s Grundsätze der Volkswirtschaftslehre, in German, that ought to give me a certain authority, right?
>
> That’s not going to happen anytime soon, so I’ll keep relying on Tyler Cowen. I will also try to follow Ransom’s advice, though. Roger Garrison of Auburn and Steve Horwitz of St. Lawrence University, the two modern Austrian-school economists he recommends, seem on first examination to be more interesting than loopy or strident, so I’ll start looking out for their writings. First step, adding the Austrian Economists blog, to which Horwitz contributes, to my feed reader.
