---
title: "Is Australia the Freest Country on Earth?"
date: "2009-01-14"
---

Australia moves up to third place in the [Heritage Foundation-Wall Street Journal Index of Economic Freedom](http://www.heritage.org/Index/Country/Australia "Heritage Foundation-Wall Street Journal Index of Economic Freedom") for 2009, behind only Hong Kong and Singapore.  The construction of the score for Australia contains some questionable elements.  For example, Australia loses five points from its monetary freedom score because ‘retail gas and electricity prices are regulated.’  Yet these regulations are a relatively minor infringement of economic liberty, while ignoring other more serious price controls (ask [Andrew Norton](http://andrewnorton.info/ "Andrew Norton") about price controls in higher education, which limit freedom to invest in human capital).  The statement on ‘investment freedom’ is self-contradictory:  ‘Foreign and domestic investors receive equal treatment… Foreign investment in media, banking, airlines, airports, shipping, real estate, and telecommunications is subject to limitations. Foreign investors may own land, subject to a number of restrictions.’

The index does not purport to measure political freedom.  But since Australia’s political institutions are at least as free as any other country, and certainly more free than those in Hong Kong and Singapore, Australia could make a plausible case for being the world’s freest country if sufficient weight were given to the political as well as the economic dimensions of freedom (at least as measured by Heritage).
