---
title: "Kevin Rudd’s China Crisis"
date: "2009-07-13"
categories: ["Economics", "Foreign Investment"]
---

[Greg Sheridan](http://www.theaustralian.news.com.au/story/0,25197,25770796-7583,00.html "Greg Sheridan") and [John Garnaut](http://business.theage.com.au/business/how-we-got-china-so-wrong-20090712-dhfw.html?page=-1 "John Garnaut") both have good analyses of the issues arising from China’s detention of Australian Rio Tinto executives for alleged espionage.  Both emphasise that this is a critical test of Kevin Rudd’s leadership and China credentials, although Garnaut maintains that Rudd’s leadership has already failed:

> With the exception of his famous “Zhengyou” speech at Peking University last year, he ducked the responsibility to lead on China. His Government’s policy ambivalence towards Chinese investment encouraged those in Australia who believed that Chinese money was something to be feared. His advisers played up the China military threat, or encouraged journalists to believe that his Defence White Paper had played up that threat.
>
> The leadership vacuum on China was quickly filled by the shrill and ill-informed.
>
> Australia’s business and political leaders needed to be assisting those in China who saw the world as an economic opportunity rather than a security threat. The risk of doing otherwise, of playing up the threat of “China Inc”, was that it would become self-fulfilling.

While there is an element of truth to this, China still bears primary responsibility for these developments.

Greg Sheridan was an opponent of the proposed Rio-Chinalco tie-up (a position he uncharacteristically shared with arch-enemy Peter Costello), which explains why he perhaps did not appreciate the irony of these comments:

> The Chinese have made it clear they can regard any commercial matter as a matter of their **national interest**...
>
> Under this system, they can intervene legally in any business deal they do not like…
>
> the Chinese authorities have explicitly said that commercial matters are matters of national security

Exactly the same could be said in relation to Australia’s regulation of FDI.  The Australian government has routinely made use of bogus national security and national interest arguments to rationalise political interventions in the market for foreign ownership and control of Australian equity capital. This is not to say that we are as bad as the Chinese, but the differences are ones of degree rather than kind.

Sheridan says that:

> The implications for Chinese conduct of investments in Australia is clear.
>
> The Foreign Investment Review Board, perhaps at the direction of the Rudd government, needs to factor this information in to all future decisions about proposed Chinese strategic investments in Australia.

China’s actions will cost it dearly.  But it would not be in Australia’s interest to make the same mistake by becoming even more like China in its regulation of FDI.
