---
title: "Lu Kewen Thought ‘Shallow and Crude’"
date: "2009-06-19"
categories: ["Economics", "Politics"]
---

A Chinese economist [rejects](http://www.theaustralian.news.com.au/story/0,25197,25657881-5013871,00.html "rejects") Lu Kewen Thought:

> KEVIN Rudd has been accused by a leading Chinese economist of being “either short of economic knowledge or misleading his readers” in his famous essay attacking neoliberalism.
>
> In a scathing assessment, Xu Xaonian, economics professor at China Europe International Business School in Shanghai, lambasts the essay, now translated and published in China, as “shallow and crude”.
>
> Dr Xu says “Lu Kewen” - Mr Rudd’s Chinese name - made a “big, big mistake” in forming his “confident opinions” based on “the observation that the crisis came as a result of neoliberalism and the absence of supervision”.
>
> Dr Xu, one of China’s leading liberal economists, has savaged the Rudd essay in the weekly Chinese newspaper The Economic Observer after the Prime Minister’s work was translated and reprinted in China’s leading business magazine, Caijing.
>
> Dr Xu, who has a doctorate from the University of California and was formerly managing director of the country’s biggest investment bank, says it is not time to resurrect Keynesianism, as Mr Rudd proposes.
>
> “Instead, it’s time to announce Keynesianism’s failure, time to announce the emperor Lord Keynes has no clothes.”
>
> He says the Prime Minister “has used electioneering-style tactics to brand neoliberalism as dogmatic, to paint a clownish portrait of it, seeking to pioneer popular antipathy to this artificial enemy, casting a moral verdict without seeming to care about truth or logic”.
