---
title: "Markets in Everything: Autographed P J O’Rourke Promotional Banners"
date: "2009-12-11"
categories: ["CIS"]
---

CIS is auctioning three 3m x 1.5m promotional banners autographed by P J O’Rourke as part of his Australia and New Zealand tour earlier this year.  Images of the banners and bidding instructions can be found [here](http://www.cis.org.au/temp/pj_banners.html "here").

**UPDATE (14 December 16:35 AEDT):**

The highest bids received to date for the personally autographed PJ O’Rourke banners are as follows:

Banner 2 \$300.00 “Government does not cause affluence. Citizens of totalitarian countries have plenty of government and nothing of anything else.”

Banner 3 \$120.00 “The free market is a bathroom scale. You may hate what you see when you step on the scale. ‘Jeeze, 230 pounds!’ But you can’t pass a law making yourself weigh 185.”

No bids have been received for banner 1 as yet. “Bringing the government in to run Wall Street is like saying, ‘Dad burned the dinner, let’s get the dog to cook.’”

If you would like to place a bid, please visit the link below and follow the instructions.  Note: If you are outbid, you will receive notification so that you have the opportunity to place a counter-bid.
