---
title: "Minsky Remembered"
date: "2009-09-16"
categories: ["Economics", "Financial Markets", "Fiscal Policy", "Monetary Policy"]
---

[Eric Falkenstein](http://falkenblog.blogspot.com/2009/09/minsky-keynesian-sockpuppet.html "Eric Falkenstein") recalls Hyman Minsky:

> I was Minsky’s TA while a senior at Washington University in St.Louis in 1987, and took a couple of his advanced classes, which regardless of the official name, were all just classes in Minskyism. He was a maverick, but perhaps a bit too much, being a little too dismissive of others, as he hated the traditional Samuelson/Solow Keynesians as much as the Friedmanite Monetarists. He always thought a market collapse was just around the corner…
>
> Most articles celebrating Minsky have a strong subtext, kind of like Krugman’s wistful remembrance of his undergraduate macro based on the General Theory, that if we only go back to the days when Nixon famously said ‘we are all Keynesians now’, we would have more faith in government top-down solutions. That was when Federal spending was 30% of GDP. Now it’s 40%. Economists did not abandon Keynesianism because they are capitalist dupes, rather, it was inconsistent, generated poor models of economic growth, and it neglected the micro economic factors that make all the difference between a North Korea and South Korea: free markets, property rights, decentralized incentives. A Keynesian thought he could steer the economy via two controls, the budget deficit and the Fed Funds rate, and indeed in the short run these are very powerful tools, but in the longer run, rather unimportant.

It is reassuring that the critics of mainstream macro have nothing better than Minsky to turn to, but still no less excusable.
