---
title: "More FDI Protectionism from Treasurer Swan"
date: "2009-05-09"
categories: ["Economics", "Foreign Investment"]
---

Not content with micro-managing foreign direct investment in Australia, the Rudd government’s [latest approval](http://www.treasurer.gov.au/DisplayDocs.aspx?doc=pressreleases/2009/045.htm&pageID=003&min=wms&Year=&DocType "latest approval") under the Foreign Acquisitions and Takeovers Act also seeks to micro-manage Australian FDI in China:

> *My approval under the Foreign Acquisitions and Takeovers Act 1975 is conditional upon Ansteel supporting the wider development of infrastructure in the Mid West, and maintaining agreed levels of Australian participation in a greenfields joint venture in China’s Liaoning Province.*

Using the FATA to obtain leverage for Australian FDI in China sets a dangerous precedent and ignores the basic reality that Australia benefits from Chinese FDI even in the absence of Chinese reciprocity.  The answer to Chinese FDI restrictiveness is not to make our system more like China’s. 

As with other [recent FDI approvals](../2009/a_new_era_in_fdi_protectionism.qmd "recent FDI approvals"), the Treasurer has once again made explicit the protectionist intent behind the exercise of his discretionary powers under the Act:

> *These undertakings support Australian mining jobs, and protect Australia’s investment participation in the Chinese resources market.*

The FIRB and Treasury are going to be kept very busy if the Rudd government is going to micro-manage every FDI proposal coming out of China in coming years.
