---
title: "My Secret Life as a Crop-Burning New Dealer"
date: "2009-03-24"
categories: ["Economics"]
---

[Brian Buckley](http://www.businessday.com.au/business/us-doing-a-minimozambique-on-its-debts-20090323-97jx.html "Brian Buckley"), one-time adviser to former federal Treasurer Sir Philip Lynch, exposes my double-life as a crop-burning New Dealer:

> LIKE the French royal House of Bourbon, some contemporary schools of economics have learnt nothing and forgotten everything. Paul Krugman and [Stephen Kirchner (BusinessDay, 19/3)](http://www.businessday.com.au/business/dont-blame-greenspans-monetary-policy-20090318-925f.html "Stephen Kirchner (BusinessDay, 19/3)") provide telling examples. Their nostrums for the world debt crisis are more government spending, or greater volumes of easy credit, or both.
>
> Professor Krugman is a great admirer of Franklin Roosevelt’s New Deal, but he omits to mention that FDR never got unemployment below 14 per cent, and the unemployment figure in the US was 17.2 per cent at the start of World War II.
>
> Like Krugman, Kirchner (and Ben Bernanke), FDR was worried about price deflation — so much that he had farmers’ crops burned to keep prices up. This was in the middle of the 1930s Depression when millions of families were short of food.
