---
title: "‘Neo-Liberalism’ Triumphed in 1978.  Who Knew?"
date: "2009-01-31"
categories: ["Economics", "Politics"]
---

Prime Minister Kevin Rudd has produced a 7,700 word essay on [The Global Financial Crisis](http://www.themonthly.com.au/tm/node/1417 "The Global Financial Crisis").  Only the first 1,500 words are currently available on-line.  Until I have seen the rest, I’ll refrain from commenting on the substance, such as there is.  If any readers have a samizdat copy, please send it through.

However, if the first 1,500 hundred words are any guide, we can safely comment on the Prime Minister’s style.  Kevin Rudd is notorious for the mind-numbing emptiness of his public utterances.  Rudd’s most [overused phrase](http://www.google.com.au/search?q=%22kevin+rudd%22+%22for+the+future%22&ie=utf-8&oe=utf-8&aq=t&rls=org.mozilla:en-US:official&client=firefox-a "overused phrase") is ‘for the future’, so it was no surprise that this made it into the first 1,500 words, along with such awful clichés as ‘throw the baby out with the bathwater.’

As with his ‘Between Hayek and Brezhnev’ speech to CIS in August last year, Rudd posits two straw men and then places himself in the reasonable centre.  Rudd’s approach to argument is thus very similar to his approach to politics.  His strategy is to minimise points of disagreement.  But what works well as political strategy won’t fly as serious argument.
