---
title: "No Time for a Media-Shy Central Banker"
date: "2009-07-24"
categories: ["Economics", "Financial Markets", "Monetary Policy"]
---

I have an op-ed in today’s *Australian Financial Review*, comparing the level of media scrutiny applied to central bankers in Australia and the rest of the world.  Full text below the fold (may differ slightly from edited *AFR* text).

By all accounts, Ben Bernanke is a shy and unassuming man.  Yet this Sunday, the US Federal Reserve Chairman will submit to a televised, hour long grilling from PBS NewsHour anchor Jim Lehrer and take questions from a studio and on-line audience. 

In March, Bernanke twice appeared on CBS’s 60 Minutes program, in addition to his usual public speeches and appearances before Congress.

With the Fed playing an unprecedented role in supporting the US economy, it is no time for a media-shy central banker.

In Australia, the Reserve Bank is also playing an unprecedented role in supporting the economy.  Yet there is no corresponding expectation that the Governor of the Bank should front the media to answer questions.

Former Governor Ian Macfarlane never gave an on-the-record media interview in his 10 years on the job.  The RBA previously resisted efforts to open its Board to greater public scrutiny, opposing applications to obtain the minutes of Board meetings under Freedom of Information legislation.

To his great credit, Governor Glenn Stevens announced measures to increase the transparency of monetary policy in December 2007.  It is no coincidence that this followed the election of a new Labor government determined to demand higher standards of the Bank.  A decade of cosy neglect under former Treasurer Peter Costello had left the Bank languishing near the bottom of international rankings of central bank transparency.

Governor Stevens has also significantly raised his profile relative to his predecessor.  Stevens gave 13 public speeches in 2008, more than double the number of public speeches Macfarlane gave during his last full year as Governor in 2005.

However, this is still a low public profile by international standards.  Ben Bernanke gave 24 public speeches and appeared before Congress 11 times during 2008.

Across the Tasman, the Reserve Bank of New Zealand holds a media conference when it releases its Monetary Policy Statements, at which the Governor takes questions on interest rates and the economy.  The press conference is also the subject of a live webcast, making the proceedings readily available to anyone with internet access.

The Governor of the Bank of England holds a media conference and takes questions when releasing quarterly Inflation Reports.  Regular press conferences are also held by the Governors of the European Central Bank and the Bank of Japan. 

The RBA’s reluctance to assume a greater public profile is understandable.  Like all bureaucrats, central bankers prefer a quiet life. 

Australian media and politicians do not exactly facilitate mature public debate, often seizing on trivial differences of opinion and beating them up into something they are not.  Yet by shunning greater media scrutiny, the Reserve Bank accommodates this immature media and political culture, reducing the quality of the national debate on important economic issues. 

Former Governor Macfarlane argued that a greater public profile might compromise the independence of the Bank.  Yet this has not been a problem in other countries, where independent central bankers are expected to play an active role in the national economic debate.  Former Fed Chairman Alan Greenspan was outspoken on a wide-range of economic and regulatory issues, yet this did not harm the independence of the Fed.

A central bank unwilling or unable to speak-out on issues related to its statutory mandate gives the appearance of timidity and compliance rather than independence.

Treasury Secretary Ken Henry shows less reluctance in inserting himself into public debate, yet it is the RBA Governor that has the greater statutory independence from government.

One of the tragedies of Ian Macfarlane’s time as Governor is that a great mind that could have contributed so much to national debate over economic policy was so rarely heard in public.

The RBA’s low public profile relative to the very noisy fiscal stimulus efforts of politicians is skewing perceptions of the relative importance of these two arms of macro policy in supporting economic activity.

To correct these perceptions, the RBA’s senior officers should follow overseas practice and front a media conference following each monthly board meeting to field questions from accredited media. 

The Bank’s senior officers should also front a media conference following each quarterly CPI release. Under an inflation targeting regime, inflation outcomes are properly seen as the responsibility of the RBA and it should be made to answer for these outcomes when the CPI is released.

This would significantly change the media dynamics surrounding interest rate announcements and inflation in Australia.  Politicians and the talking-heads of financial markets would no longer dominate media coverage of these events.  It would underscore the Reserve Bank’s responsibility for interest rate and inflation outcomes, neither of which are the direct responsibility of politicians. 

The RBA has little to fear from increased public scrutiny and should follow its overseas counterparts in more actively contributing to public debate over economic policy.  The issues are simply too important to be left solely to politicians.
