---
title: "(Not So) Outrageous Predictions for 2010"
date: "2009-12-18"
categories: ["Economics", "Financial Markets"]
---

Saxo Bank has released its [outrageous predictions for 2010](http://www.prnewswire.com/news-releases/saxo-bank-releases-outrageous-predictions-for-2010-79476702.html "outrageous predictions for 2010"), which are actually not outrageous at all.  But how did they go with their [outrageous predictions for 2009](http://www.saxobank.com/Documents/pressreleases/Outrageous%20Predictions%202009%20final.pdf "outrageous predictions for 2009")?  My comments in square brackets.

1)  There will be severe social unrest in Iran as lower oil prices mean that the government will not be able to uphold the supply of basic necessities. \[IE: yes, but not because of oil, half marks\]

2)  Crude will trade at \$25 as demand slows due to the worst global economic contraction since the great Depression. \[IE: WTI bottomed out at \$33.22 in mid-January\].

3\) S&P will hit 500 in 2009 because of falling earnings, vaporizing housing equity and increased cost of funds in the corporate sector. \[IE: S&P 500 made lows at the even more ominous sounding level of 666\].

4\) The EU is likely to crack down on excessive government budget deficits in several member states, and Italy could live up to previous threats and leave the ERM completely. \[IE: if only!\]

5\) The AUDJPY will drop to 40. The decline in the commodities markets will affect the Australian economy. \[IE: AUD-JPY actually bottomed in October 2008.  Lows for 2009 were 55.55.  Australian economy outperformed ROW\]

6)  EURUSD will fall to 0.95 and then go to 1.30 as European bank balances are under tremendous pressure because of exposure to the faltering Eastern European markets and intra‐European economic tensions. \[IE: EUR-USD made lows at 1.2459 and highs at 1.5144 YTD, but half marks for European bank stress\].

7\) Chinese GDP growth drops to zero. The export driven sectors in the Chinese economy will be hurt significantly by the free‐fall economic activity in the Global Trade and especially of the US. \[IE: growth forecast wrong, no marks for stating the obvious implications of global recession already in evidence\]

8)  Pre‐In’s First Out. Several of the Eastern European currencies currently pegged or semi‐pegged to the EUR will be under increasing pressure due to capital outflows in 2009. \[IE: Full marks, although fixed exchange rates spell macro trouble by definition\]

9)  Reuters/ Jefferies CRB Index to drop to 30% to 150. The Commodity bubble is bursting, with speculative excesses so large they have skewed the demand and supply statistics. \[IE: see comments on Australia\]

10)  2009 will see the first Asian currencies to be pegged to CNY. Asian economies will increasingly look towards China to find new trade partners and scale down their hitherto US‐centric agenda. \[IE: wrong on first part, second part hardly unique to 2009\]

So score 2/10 for Saxo in 2009, which is a whole lot better than [Nouriel Roubini](http://wallstcheatsheet.com/breaking-news/economy/a-chart-of-roubinis-horrible-trackrecord-in-2009/?p=3513/ "Nouriel Roubini").
