---
title: "Peter Costello, Economic Nationalist"
date: "2009-02-18"
categories: ["Economics"]
---

In an op-ed for the SMH, Liberal backbencher [Peter Costello](http://www.smh.com.au/opinion/rio-feathers-should-stay-in-our-nest-20090217-8a9a.html?page=-1 "Peter Costello") wears his most disgraceful decision as a badge of pride:

> *I cannot remember Treasury ever recommending that I block or disallow the acquisition of an Australian company by foreign interests. There were specific rules for media, real estate and the like, but in the general economy Treasury always supported foreign investment. In 2001 I rejected the Treasury view that Shell’s application for the oil and gas producer Woodside should be allowed. It caused a great deal of agitation in the department.*

Bad economic decisions tend to do that to Treasury.  Costello also takes pride in frustrating the attempts of Australian businesses to become global companies:

> I was determined to ensure that BHP’s corporate presence did not disappear from Australia in the same way as CRA, so I put conditions on its dual-listed company structure that required the global headquarters to remain in Australia, that this be specified in all public documents, that the majority of board meetings be in Australia, and most importantly, that the chief executive and chief financial officer have their principal residences in Australia. This last condition was opposed by the company.
>
> Several times the company sought to have these conditions eased but they remain in place, and to its credit, the company has scrupulously complied with them. The world’s largest diversified mining company is still Australian…

Costello gives the game away when he says:

> *The head office generates the corporate, financial, legal and insurance services and the highly skilled jobs that come with them.*

In other words, the real rationale for FDI controls is good old-fashioned protectionism.  Needless to say, Peter Costello now also thinks he knows better than Rio Tinto how it should structure its business, a position he shares with Greens leader Bob Brown and the national secretary of the CFMEU.  Costello remains an unreconstructed economic nationalist.
