---
title: "PIMCO: Bail-Out Profiteers"
date: "2009-02-21"
categories: ["Economics", "Financial Markets"]
---

PIMCO’s Bill Gross, [bail-out profiteer](http://money.cnn.com/2009/02/19/news/newsmakers/benner_gross.fortune/index.htm?postversion=2009022012 "bail-out profiteer"):

> in 2008 Gross shifted from Treasuries and corporate bonds into mortgage debt backed by Fannie and Freddie because he believed that the government would ultimately keep those government-sponsored enterprises (GSEs) afloat. By May, Gross had moved 60% of Total Return into GSE-backed bonds, up from 20% the year before. “In a way, we’ve partnered with the government,” says El-Erian. “We looked for assets that we felt the government would eventually have to own or support.”
>
> Pimco also made a bet on GMAC, the struggling finance arm of General Motors, reasoning that Washington would not let the lender fail for fear of crippling the U.S. auto industry. “We tried to move ahead of the government,” says Gross, “to purchase assets before we believe they will have to.”
>
> Once the financial crisis hit, Gross was not shy about calling for a bailout - and he is an especially effective advocate for his causes. Where many big money managers try to keep a low profile, Gross has always maintained a forceful public persona, making regular television appearances to promote his views.
