---
title: "Policymakers Sold Australia Short"
date: "2009-10-14"
categories: ["Economics", "Financial Markets", "Fiscal Policy"]
---

I have an op-ed in today’s *AFR* arguing that the budget economic forecasts are the wrong benchmark to use in evaluating the effectiveness of fiscal stimulus.  Full text below the fold (may differ slightly from edited *AFR* text).

Alan Mitchell’s column on the facing page is worth reading for its discussion of the relationship between the Rudd government and the Treasury Secretary.  Mitchell argues that ambiguity about the nature of this relationship is undermining accountability for government policy.

Key economic data, including GDP growth and the unemployment rate, have come in better than forecast in the May Budget.  The government has argued that these numbers demonstrate the effectiveness of its fiscal stimulus measures.  In reality, they demonstrate only that policymakers sold Australia short in forecasting a more serious economic downturn.

The forecasts in the May Budget were conditioned on Treasury estimates of the effectiveness of the fiscal stimulus packages the government put in place in late 2008 and early 2009.  In a departure from past practice, the Treasury now also conditions its forecasts on expectations for future changes in official interest rates.  The budget economic forecasts thus discounted the effects of both fiscal and monetary stimulus.

The fact that the economy has outperformed these forecasts can be interpreted in one of two ways: either fiscal and monetary stimulus were spectacularly more effective than even the government and Treasury dared to assume; or, the economic forecasts were themselves overly pessimistic and the government over-reacted in implementing one of the world’s largest fiscal stimulus packages as a share of GDP.

Australia’s better-than-expected economic performance can just as easily be interpreted as a forecasting error rather than a vindication of the fiscal stimulus measures.

Benchmarking current economic performance and policy effectiveness to the budget forecasts assumes that these forecasts were correct to begin with and not overly-pessimistic, as now appears to be the case. 

As the financial crisis unfolded, the government was skillful in lowering expectations in relation to future economic performance, a trap the opposition fell into by questioning whether the budget forecasts were too optimistic.  Having successfully lowered expectations, the government was well placed to claim credit when its budget forecasts were exceeded.

One of the most striking features of Australia’s economic performance since the early 1990s recession is how frequently it has defied the doomsayers.  Based on experience with global recessions in the early 1980s and 90s, the Australian economy was widely expected to succumb to both the Asian economic crisis of the late 1990s and the global recession of 2001.  Instead, the Australian economy outperformed through both episodes.

While Australia has not completely decoupled from the global business cycle, it has grown at a faster rate on average than most of its developed country peers for more than a decade.  This outperformance is a structural rather than a cyclical phenomenon, a product of the two decades of economic reform the Prime Minister now derides.  It should not come as a huge surprise that the Australian economy has continued to outperform in the context of the current global downturn.

Australian policymakers have argued that the timely and aggressive nature of their fiscal stimulus measures supported economic growth in the short-run, maintaining that it was better to err on the side of caution in responding to a prospective downturn.  They never mentioned that the long-run multipliers from fiscal stimulus are likely to be negative due to the crowding-out of the private sector by public sector borrowing.  If fiscal policy over-reacted to the prospect of a downturn, then there are little or no benefits to offset these long-run costs.

The lesson from this and other episodes of global economic weakness is not to sell Australia short.  The Australian economy is far more resilient than policymakers have given it credit for. 

The Senate Economic References Committee has recently addressed the question of whether the fiscal stimulus should be withdrawn at a faster pace than allowed for in the budget papers.  If fiscal stimulus really has been more successful than expected in the budget, then withdrawing the stimulus at a faster pace makes sense, especially now that monetary policy is moving to a less stimulatory stance. 

One of the consequences of better than forecast economic growth is that a far greater share of the deterioration in the budget balance has been attributable to discretionary stimulus measures than to weaker economic performance.  In announcing the final budget outcome, Treasurer Wayne Swan made the argument that fiscal stimulus had helped the budget bottom line by supporting growth.  By this logic, the government could simply spend its way back into surplus.

In their testimony before the Committee, Reserve Bank Governor Glenn Stevens and Treasury Secretary Ken Henry conceded that there was a trade-off between monetary and fiscal stimulus.  To the extent that fiscal stimulus has supported economic growth, then official interest rates have been higher than would otherwise have been the case.

Both Stevens and Henry maintained that there are dangers associated with very low interest rates, but they neglected to mention the far more serious and well-known dangers associated with activist fiscal policy.  Not least among these is the difficultly of getting governments to adjust spending measures in a timely fashion when the forecasts used to justify them turn out to be wrong.

Dr Stephen Kirchner is a Research Fellow with the Centre for Independent Studies.
