---
title: "Rudd in Wonderland"
date: "2009-02-02"
categories: ["Economics", "Politics"]
---

[David Burchell](http://www.theaustralian.news.com.au/story/0,25197,24992899-7583,00.html "David Burchell") attempts to deconstruct Rudd’s bizarre [work](../2009/neo-liberalism_triumphed_in_1978._who_knew.qmd "work") of political speculative fiction:

> It’s hard to accept that the flesh and blood Kevin Rudd who lives in the Lodge really believes any of these things. While it’s true that governments around the world have been more inclined to expose national economies to international competition, and to facilitate the flow of capital across national borders, there’s no clear evidence of a general shrinkage of the size or role of governments over the past 30 years, regardless of the ideological presuppositions of specific administrations. The neo-liberal ghoul is just that, a ghoul. And the fantasy that sets states and markets on a path of mortal combat resembles the imaginations of those medieval mystics who saw Christ and the devil locked in struggle across this vale of tears.
>
> This is where the several other authorial Rudds come in. One of them - we’ll call him Rudd 2 - is the dutiful policy technocrat, eager to reassure us about the practical measures necessary to stabilise world finance. But since few of these measures are disputed by orthodox economists, it’s not clear how they toll the death-knell of neo-liberalism. Rudd 3, in turn, is that familiar figure in ministers’ offices, the instinctual party loyalist who wants to spin the fable of neo-liberalism into a partisan account of Labor governments (good) and conservatives (bad). Yet this third Rudd seems equally discordant with the first, given that - as the Old Testament critics of economic rationalism have been instructing us tirelessly since the early 1990s - the Hawke-Keating governments were our neo-liberal pioneers, the unleashers of the locust plague, the vandals of our nation-building state.

What I have seen of Rudd’s essay reads almost like a cyber-punk novel, with the action set in a speculative ‘neo-liberal’ dystopia ([Brutopia](http://andrewnorton.info/2006/11/how-many-people-read-the-monthly/ "Brutopia")?), and where the social democratic hero (guess who?) saves the day.
