---
title: "Rudd Bank Puts Taxpayers Last"
date: "2009-01-28"
categories: ["Economics", "Financial Markets", "Fiscal Policy"]
---

I have an op-ed in today’s *AFR* on the so-called ‘Rudd Bank.’  Text below the fold (may differ slightly from edited *AFR* version).

[Henry Ergas](http://www.theaustralian.news.com.au/story/0,25197,24966998-7583,00.html "Henry Ergas") made related arguments in *The Australian* yesterday.

The Rudd government’s \$2 billion intervention to provide loans to the commercial property sector is rationalised as a measure to save jobs, but once again puts the interests of business and financial institutions ahead of those of consumers and taxpayers. 

This latest intervention in financial intermediation follows the \$8 billion the government is investing in residential mortgage-backed securities. 

This was great news for the mortgage securitisation industry, and may even have saved some non-bank lenders from going bust, but there is no evidence that home borrowers are any better off.  The benefits went straight to the bottom line of financial intermediaries.

Subsidies to first-time home buyers for the purchase newly-built housing stock are a more effective way of stimulating residential construction and the housing sector, rather than relying on the benevolence of the non-banks lenders to share their government support with their customers.

The government’s latest intervention to further socialise financial intermediation suffers similar problems.  Banks and the commercial property industry stand to benefit from the scheme, while taxpayers wear all the attendant risks.

The government talks about the jobs that might be lost in the construction sector. 

There is no question that construction industry jobs are at risk, although this has more to do with general economic conditions than a lack of capital.

The government has arguably got well ahead of events in anticipating the withdrawal of foreign lenders from the Australian marketplace. 

The construction industry is hardly unique in losing jobs because of the emerging economic downturn.  Most industries and firms could make a claim for government assistance on this basis. 

The government cannot possibly hope to save every business or job that is now at risk as a result of a global economic downturn.  Saving jobs in one sector of the economy is likely to come at expense of jobs elsewhere and only encourages others to beg for more intervention.

The government has little basis on which to favour some industries at the expense of others.  The employment intensity of a given industry is a poor basis on which to be allocating government assistance.

In propping-up those politically-favoured firms and industries deemed most in need, the government will only prolong the necessary adjustment to weaker economic conditions. 

The government is likely to be as good at financing commercial property as it is at defence equipment project management or running schools and hospitals. 

There is a risk that some projects that should be allowed to go under will instead be propped-up at taxpayers’ expense.  If the government and the banks get it wrong, taxpayers will end-up footing the bill.

While the government has talked-up the safeguards it intends to put in place to miminse the risk of loss to taxpayers, these safeguards are explicit acknowledgement that the intervention is fraught with danger.

Taxpayers are now serving as lenders of last resort on both residential mortgages and commercial property.

The combined \$10 billion the government is putting into mortgage-backed securities and commercial property substitutes the public sector’s balance sheet for that of the private sector.

The federal budget is likely to go into deficit due to the operation of the automatic stabilisers in the context of an economic downturn. 

But the government is adding to this cyclical downturn in the budget balance through a wide-range of discretionary policy measures.

Regardless of the way the government accounts for its investments in mortgage-backed securities and commercial property loans, the government will soon be making a substantial net call on capital markets for the first time since the mid-1990s.

Last year, the government announced a \$10 billion expansion of its debt issuance program under the guise of ‘enhancing market liquidity.’  The government claimed that the increase in debt issuance was to accommodate increased demand for government bonds.

In fact, the government is accommodating its emerging need to once again tap capital markets to fund its activities.

The government risks crowding-out private capital in already strained capital markets, putting at risk investment and jobs elsewhere in the economy.

The political imperative for the government is to be seen to be doing something in response to the global financial crisis, regardless of relative effectiveness.

As with the intervention in the market for mortgage-backed securities, the government is putting the needs of business and financial institutions ahead of consumers and taxpayers.

Through its interventions in financial intermediation, the Rudd government is constructing a corporate welfare state that will ultimately hold back rather than support the economy.
