---
title: "Self-Inflicted Chinese Influence Peddling"
date: "2009-03-26"
categories: ["Economics", "Foreign Investment"]
---

The ACCC [clears](http://www.accc.gov.au/content/index.phtml/itemId/866066/fromItemId/142 "clears") an increased Chinalco stake in Rio in terms of section 50 of the Trade Practices Act:

> *Chinalco and Rio Tinto would be unlikely to have the ability to unilaterally decrease global iron ore prices below competitive levels. Given this conclusion, it was not necessary for the ACCC to reach a determinative view on the extent to which Chinalco could control and influence Rio Tinto.*

It is noteworthy that the ACCC’s decision was based on the worst-case assumption that:

> *Chinalco and various steel makers are subsidiaries of the same parent entity and therefore may have common commercial interests.*

As I noted in an earlier [op-ed](http://www.theaustralian.news.com.au/business/story/0,,25135036-36418,00.html "op-ed"), given its determination in relation to the formerly proposed merger between Rio and BHP, the ACCC could hardly have concluded otherwise. 

Having cleared the competition policy hurdle, the deal must now be cleared in terms of the Foreign Acquisitions and Takeovers Act.  But with the economic issues now settled from a regulatory standpoint, what does the FATA have to add to this process?  The FATA’s only purpose is to serve as a vehicle for ministerial (in this case, Prime Ministerial) discretion over foreign investment. 

Is it any wonder then that the Prime Minister is being lobbied by some of the [highest echelons](http://www.theaustralian.news.com.au/story/0,25197,25242327-583,00.html "highest echelons") of the Chinese government?  While some see this as sinister, this sort of influence peddling is entirely of our own making, being effectively institutionalised by Australia’s FDI controls.  As I noted in [Capital Xenophobia II](http://www.cis.org.au/policy_monographs/pm88.pdf "Capital Xenophobia II"), these controls are much closer to those used by the Chinese than to those used by comparable countries.  The lesson is, if you don’t want foreign investment policy in Australia being manipulated by the Chinese, then keep Australian politicians out of the process.
