---
title: "Single-Issue Forecasting Tragics"
date: "2009-10-01"
categories: ["Economics", "Financial Markets", "Fiscal Policy"]
---

[Don Harding](http://www.theaustralian.news.com.au/story/0,25197,26147806-5013480,00.html "Don Harding") has a great piece on economic forecasting in today’s Australian:

> In the future there will continue to be financial crises and recessions, all of which economists, bankers, finance gurus, bureaucrats, politicians and the public will fail to predict.
>
> To be sure there will be some who claim predictive success… Most will be single-issue tragics who predict the next calamity in the same way that I, an Essendon tragic, successfully predicted their win over St Kilda in round 20 by predicting that Essendon would win every match. The only information in such predictions is about the tragics who make them.

Harding also notes the appalling state of the debate over fiscal stimulus in Australia:

> *Public policy standards are so low in Australia that my expectation is that we won’t get well-researched, evidence-based answers to these questions from either the bureaucrats or the politicians.  Instead we will get spin, vitriol and blame shifting.*

Here’s a suggestion for the FOI desk at *The Australian*: request all the materials that form the basis for the Treasury’s estimates of the impact of fiscal stimulus on economic growth and employment.
