---
title: "Tens of Billions Lost"
date: "2009-11-09"
categories: ["Economics", "Financial Markets", "Fiscal Policy", "Politics"]
---

RBA Board member [Warwick McKibbin](http://www.theaustralian.com.au/news/outspoken-rba-director-warwick-mckibbin-dropped-from-pms-science-council/story-e6frg6n6-1225795575621 " Warwick McKibbin"), on the resource cost of fiscal stimulus:

> RESERVE Bank director Warwick McKibbin has publicly questioned whether the Rudd government dumped him from the Prime Minister’s science council as payback for saying its fiscal stimulus package was “too big”.
>
> Speaking yesterday after Wayne Swan said the RBA was “entirely comfortable with our fiscal policy”, Professor McKibbin said he had no doubt history would show that the Rudd government had overdone the stimulus.
>
> Professor McKibbin also revealed that part of the motivation behind establishing a new council of eminent economists to debate policy issues was to encourage academics to speak out.
>
> “I think when people look through the entrails of this, they will find billions, if not tens of billions, that was just lost,” he told The Australian.
>
> A few weeks after he suggested that the second part of the stimulus package was too large while giving evidence at a Senate inquiry in May, he was dumped from a government advisory role on the Prime Minister’s Science and Innovation Council, Professor McKibbin said.
