---
title: "The Future of the US Dollar"
date: "2009-11-05"
---

I have an op-ed in the business section of today’s *Australian* on the future of the US dollar (no link, but full text below the fold).  Many commentators mistakenly view the market-clearing price of the US dollar on foreign exchange markets as a reflection on the US dollar’s future role in the international financial system.  As I argue in my op-ed, the US dollar’s role is entirely a function of the role of US capital markets in the international financial system.  It makes the often neglected point that a declining US dollar actually improves the net international investment position of the United States. 

I would also highly recommend Richard Cooper’s PIIE Policy Brief on [The Future of the Dollar](http://www.iie.com/publications/pb/pb09-21.pdf "The Future of the Dollar").  Cooper is particularly good in explaining why it is China that is financially dependent on the US, not the other way around.

Recent US dollar weakness has given added impetus to the sentiment that one hedge fund trader has succinctly called ‘DGDF’ or ‘dollar going down forever’.  Despite a safe-haven bid during the recent global financial crisis, the broad US dollar index has been trending lower since its last major cyclical peak in 2001.  This has led many observers to question whether the US dollar will retain its status as a so-called ‘reserve currency’.

The idea of a ‘reserve currency’ is a legacy of the Bretton Woods system of fixed exchange rates.  Under this system, maintaining a fixed exchange rate depended on a country’s ability to buy and sell currency at a given exchange rate parity to the US dollar.  In this context, central bank holdings of US dollar reserves assumed considerable importance. 

Foreign exchange reserves are much less important under the system of floating exchange rates that has emerged since the demise of Bretton Woods in the early 1970s.  The only reason to maintain significant foreign exchange reserves is to avoid having to borrow in international capital markets to fund intervention in foreign exchange markets.  Since such intervention is generally both unnecessary and ineffective, there is no need for central banks with floating exchange rates to maintain significant foreign exchange reserves. 

Countries like China that remain wedded to managed exchange rate regimes and capital controls must accumulate significant US dollar reserves to maintain their currencies in the desired range against the US dollar.  Given its exchange rate regime, China’s purchases of US dollar assets are not a matter of policy choice. 

China’s view on the likely direction of US dollar-denominated assets is thus largely irrelevant to its decision to accumulate those assets. While China can diversify its reserves at the margin, it is limited by the fact that only the US has capital markets that are deep and liquid enough to accommodate China’s reserve holdings. 

The residual role of the US dollar as a ‘reserve’ currency is thus largely a function of the size and quality of its capital markets and not the willingness of foreign governments to hold US dollars.  There would be little international interest in holding a currency that is not backed by deep, liquid and freely-traded capital markets.  Countries that aspire to displace the role of the US dollar will first need to develop capital markets comparable to those in the US.  This is where the numerous proposals to replace the US dollar as a ‘reserve currency’ come up short.

Global capital flows are the main determinant of international exchange rates and interest rates, but transactions in official reserve assets are small relative to the flows of private capital.  The turnover in foreign exchange markets is anywhere from \$US2-3 trillion daily.  Changes in the holdings of foreign exchange reserves by central banks are just a drop in the bucket of this global market.  Those who look to changes in central bank reserve holdings for clues about the direction of exchange rates are seriously mistaken.

The US dollar is also prominent as a currency in which trade in international goods and services is denominated, reflecting the post-war dominance of the US in international trade.  This role has diminished somewhat relative to emerging economies, but the US dollar remains the dominant unit of account largely because of the central role of US capital markets in the international financial system.

There have been proposals among oil-producing countries to re-denominate the oil trade in currencies other than the US dollar, which countries like Iran and Venezuela intend as a threat to the US.  However, income and wealth are determined by the production of real goods and services, not the units of account in which they are denominated.  The obsession with the ‘reserve currency’ status of the US dollar is a legacy of the mercantilist mentality, which measured national prosperity in terms of hoards of gold rather than in terms of the flow of goods and services.

So where does this leave the US dollar exchange rate?  Exchange rates are relative prices.  Currencies are only strong or weak relative to others.  For all the macroeconomic problems besetting the United States, these problems are not necessarily worse than those facing the economies of other major currency units, such as the euro.

Floating exchange rates are also market-clearing prices.  A weaker US dollar makes US exports more competitive and US dollar-denominated assets more attractive to international investors.  A falling dollar increases the value of US assets abroad, while leaving the value of America’s dollar-denominated debts unchanged.  The weaker dollar thus improves America’s net international investment position. 

Too many commentators look to the US dollar as a measure of US national strength.  But this is to fall victim to the mercantilist ideas that the US needs to resist if it is maintain its central position in the world economy and financial system.

The Nobel laureate Robert Mundell, also known as the ‘father of the euro’, has predicted that the ‘dollar era is going to last a long time, perhaps another hundred years’.  Whether Mundell is right will ultimately depend on whether America continues to uphold the rule of law and property rights that gave rise to its central role in global capital markets. 

In theory, other countries could emerge to replace the US in the provision of deep and freely-traded capital markets.  But do you really want to bet on it?
