---
title: "The Mother of All House Price Booms?"
date: "2009-09-29"
categories: ["Economics", "House Prices"]
---

Recently, I have been drawing attention to the implications of Australia’s population growth, the strongest since the echo of the baby boom in the early 1970s.  Paul Sheehan quotes me on the issue [here](http://www.smh.com.au/opinion/politics/australias-population-fairytale-20090927-g7o5.html "here").

In the latest [Rismark Monthly](http://www.rismark.com.au "Rismark Monthly") (gated), I’m quoted on the fact that Australia is now building fewer dwelling units per addition to the resident population since the early 1980s, based on one measure of dwelling commencements.  On another measure, we are producing fewer dwelling units per person than at any time since the late 1960s. 

The RBA’s head of economic analysis, [Tony Richards](http://www.rba.gov.au/Speeches/2009/sp-so-290909.pdf "Tony Richards"), follows Governor Glenn Stevens in highlighting the implications of this dire supply situation for housing affordability.  The RBA is performing a valuable service in putting this issue on the agenda for public debate.  This is perhaps one of the few public policy issues the RBA can safely touch, because it straddles all three levels of government and so is less likely to be seen as criticism of a particular government’s policies.
