---
title: "The Rio-Chinalco Counter-Factual"
date: "2009-06-16"
categories: ["Economics", "Financial Markets", "Foreign Investment"]
---

[John Garnaut](http://business.theage.com.au/business/secrecy-frustrates-china-20090614-c7di.html?page=-1 "John Garnaut") challenges the widespread assumption that the Rio-Chinalco deal fell-over for commercial rather than political reasons:

> The Economist reported that Rudd wanted the deal to go through. That may well be a message Rudd’s office would like the outside world to have but it is not consistent with dealings I have had with any of Rudd’s ministers, staffers or advisers, and certainly not from the companies involved.
>
> In the normal course of events we would never find out what went on inside FIRB. On this occasion, Rio chairman Jan du Plessis hinted after he walked away from the Chinalco deal just over a week ago and Chinalco president Xiong Weiping more clearly indicated at his press conference on Thursday, that the original deal would have been killed in Canberra without substantial amendments.
>
> “During our engagement and communication with FIRB we received advice in principle in terms of how the transaction should be modified,” said Xiong. And, unusually, Rudd ministers publicly lent against the deal from the start.
>
> My own understanding, from Australian and Chinese sources, is that FIRB expressed its intense displeasure at almost every substantial aspect of the Chinalco deal but never spelt out what it would take for the deal to pass.
>
> FIRB’s displeasure and the range of its concerns increased as time progressed — in correlation with the improving commodities, stock and debt markets — reaching critical levels early last month.
>
> Xiong hoped his large concessions would be enough for Canberra. In fact he had no idea. Would Canberra have allowed him to accept a seat on the Rio Tinto board? He and we will never know.
>
> Rudd may have been right in assuring China and the world that the Chinalco-Rio deal failed for “entirely commercial reasons”. But Australia’s China-like investment review process means we will never know the counter-factual.
>
> Without the delay and uncertainty injected by the political process, which strengthened BHP’s negotiating arm vis-a-vis Chinalco, how would those two parallel commercial negotiations have panned out?

For all the ink spilled on the Rio-Chinalco deal, Garnaut is one of the few journalists to identify the real public policy issue in this debate: [Australia’s Whitlam-era, Chinese-style regulatory regime](http://www.businessspectator.com.au/bs.nsf/Article/Fear-Canberra-not-Beijing-$pd20090401-QNQWS?OpenDocument "Australia’s Whitlam-era, Chinese-style regulatory regime") for FDI.  Once again, that regime has been tested and found seriously wanting.  The collapse of the deal only adds to the uncertainty facing prospective foreign investors and the vendors of domestic equity capital.
