---
title: "The Slow and Secretive FIRB"
date: "2009-07-06"
categories: ["Economics", "Foreign Investment"]
---

Don’t hold your breath waiting for the [Foreign Investment Review Board’s annual report](http://business.theage.com.au/business/secretive-firb-leaves-everyone-in-the-dark-20090705-d96d.html "Foreign Investment Review Board’s annual report"):

> THE Foreign Investment Review Board is reinforcing its reputation as one of Canberra’s most secretive bodies. More than a year after the 2007-08 year there is no sign of its annual report.
>
> In contrast, the companies whose fate depends significantly on the board’s deliberations must deliver their annual reports within four months of the end of the financial year…
>
> Although the board carries out confidential consultations with government departments and takes submissions from interested parties in cases that are already in the public domain, its decision-making remains secretive even to those with a close interest in outcomes. Its recommendations are passed directly to the Treasurer and are rarely made public…
>
> Even when the Treasury-controlled board’s 2007-08 report is eventually made public, it is unlikely to reveal little about its deliberations.
>
> The 2006-07 report reveals the number of applications for foreign investment and the decisions made, but does not identify the companies subject to applications.

I make recommendations for reform of the FIRB in my CIS Policy Monograph, [Capital Xenophobia II](http://www.cis.org.au/policy_monographs/pm88.pdf "Capital Xenophobia II").
