---
title: "The Feral FIRB"
date: "2009-10-06"
categories: ["Economics", "Foreign Investment"]
---

[John Garnaut](http://www.theage.com.au/business/cold-shoulder-a-big-turnoff-for-china-20091004-ghvd.html "John Garnaut") has a story in the SMH highlighting the arbitrary and capricious nature of Australia’s regulation of foreign direct investment and the damage it is doing to Australia’s international reputation as an investment destination.  If Garnaut is to be believed, the FIRB is a bureaucracy turned feral, which would help explain the Patrick Colmer speech debacle.  Extract over the fold, but read the whole thing.

> Experiences like this have led many of China’s top corporate and financial leaders to the view that Australia now has a more restrictive and arbitrary foreign investment regulatory regime than any other developed country.
>
> Patrick Colmer, the head of the Australia’s Foreign Investment Review Board, could not be accused of doing his job half-heartedly. Earlier this year Chinalco and its advisers were not just burnt by their experience in front of Colmer, they were mystified.
>
> They had spent three months studying Australia’s investment laws, principles and precedents before signing their Rio Tinto investment deal in February. They thought they had ticked every box.
>
> But every time they approached the board - and particularly as Chinalco and Rio entered their final frenetic weeks of renegotiations - they were given a new reason to believe that the Australian Government hated the deal and would do anything it could to stop it.
>
> The board spent much of its time grilling Chinalco on whatever allegation had just emerged in the morning’s press. On some days it was concerned with Chinalco appointing directors to the Rio Tinto board, or the raw size of the investment. On other days the problem seemed to be squarely about iron ore.
>
> As May progressed the board’s interrogations appeared to grow more random. It expressed anxiety that if Chinalco was able to deliver Rio Tinto access to exploration rights in China then that would be unfair to BHP Billiton - as if BHP and Australia’s national interest were one and the same.
>
> It was the nature of Chinalco’s dealings with the board, rather than the fact that the Rio deal collapsed, that left Chinese decision-makers with the sense that Australia was hostile towards Chinese capital.
>
> A senior decision-maker in the Government has since told me that Canberra would have let the Chinalco deal go through with workable conditions, including allowing Chinalco directors on the Rio board and its desired iron ore investment.
>
> Rather, he said the Government was concerned with Chinalco buying alumina resources (because it was a downstream consumer) and that it would have helped if Chinalco had planned to invest in Australian processing facilities.
>
> But Canberra never communicated its preferences to Chinalco. Chinalco had no way of knowing that the board - which is legally an adviser to the Treasurer, Wayne Swan, rather than a decision-maker - may have simply been off on a frolic of its own.
>
> And so it remains today.
