---
title: "‘The Last Little Timber from a Sunken Boat of Ideas’"
date: "2009-02-05"
categories: ["Economics", "Fiscal Policy"]
---

Prime Minister Kevin Rudd proudly declared himself to be a Keynesian in his essay for *The Monthly* and now has a massive fiscal stimulus package to prove it.  [John Cochrane](http://faculty.chicagobooth.edu/john.cochrane/research/Papers/fiscal2.htm "John Cochrane"), Professor of Finance at the University of Chicago Booth School of Business, highlights the extent to which Keynesianism has been thoroughly discredited within modern macroeconomics:

> Am I some sort of radical? No, in fact economics, as written in professional journals, taught to graduate students and summarized in their textbooks, abandoned fiscal stimulus long ago.
>
> Keynesians gave up by the 1970s. They saw that fiscal programs took too long to implement. They especially disparaged temporary measures, which would not stimulate the consumption that classic Keynesians thought was important to stimulus.  Every undergraduate text has repeated these conclusions for at least 40 years. I learned this view from Dornbusch and Fisher’s undergraduate text, taught by Bob Solow, in the 1970s…
>
> The equilibrium tradition which took over professional academic economics in the mid-1970s has even less room for fiscal stimulus. Some “equilibrium” analyses do say fiscal stimulus can increase output – but by making us feel poorer, work harder at lower wages, and consume less. That’s not what advocates have in mind! A large fiscal program can affect prices, wages, and interest rates with all sorts of interesting general-equilibrium implications, but these analyses haven’t really converged on anything solid, much less the large “multipliers” necessary to make traditional fiscal stimulus attractive.
>
> More deeply, macroeconomics was revolutionized starting in the 1950s, by the realization that what people think about the future is crucial to understanding how policies work today. Milton Friedman started this, pointing out that consumption does not depend statically on today’s income, but on what people expect of the future. People who learn that their jobs are on the line will consume less and save more, even though today’s income may still be good. As I have emphasized, the effects fiscal stimulus will have now depends crucially on whether people expect the new spending to be paid back by future taxes or whether they expect it to be quickly monetized. Classic Keynesian analysis analyzed policies and each time point in isolation. We do not have to agree if expectations are formed “rationally,” all we have to agree is that expectations of the future matter crucially for how people behave today, and the classic Keynesian analysis of fiscal stimulus falls apart.
>
> In textbooks and graduate curriculums across the country, stimulus is presented at best as quaint “history of thought” with no coherent defense that one should believe it in the context of modern economics.  (For example, David Romer’s classic graduate text Advanced Macroeconomics) At worst, it is presented as a classic fallacy. (My view of the treatment in Tom Sargent’s Dynamic Macroeconomic Theory and Sargent and Ljungqvist’s Recursive Macroeconomic Theory).
>
> “New-Keynesian” thought is devoted to defending the importance of monetary policy, and incorporating specific frictions in the equilibrium tradition, not to rescuing the ancient view that fiscal stimulus is important and abandoning that tradition.  Mike Woodford’s magisterial New-Keynesian opus, Interest and Prices, has no mention at all of fiscal stimulus.  More deeply, new-Keynesian economics is completely devoted to the proposition that expectations of the future matter centrally for how the economy behaves today.  Its central thesis is that central bankers must manage expectations, not manage “demand.”  It has no room at all for the sort of analysis in which one adds up “consumption” “investment” and “government” demands, without considering alternatives for those demands or expectations of the future, to determine output.
>
> These ideas changed because Keynesian economics was a failure in practice, and not just in theory. Keynes left Britain 30 years of miserable growth. Richard Nixon said “we’re all Keynesians now” just as Keynesian policy led to the inflation and economic dislocation of the 1970s, unexpected by Keynesians but dramatically foretold by Milton Friedman’s 1968 AEA address. Keynes disdained investment, where we now all realize that saving and investment are vital to long run growth. Keynes did not think at all about the incentives effects of taxes. He favored planning, and wrote before Hayek reminded us how modern economies cannot function without price signals.  Fiscal stimulus advocates are hanging on to a last little timber from a sunken boat of ideas, ideas that everyone including they abandoned, and from hard experience.
