---
title: "The Contradictions of FDI Protectionism"
date: "2009-05-13"
categories: ["Economics", "Foreign Investment"]
---

The ‘chairman’ of Hancock Prospecting, [Gina Rinehart](http://www.theaustralian.news.com.au/business/story/0,28124,25469010-643,00.html "Gina Rinehart"), argues against a Rio-Chinalco tie-up:

> We cannot wish or assume that Rio-Chinalco (without investment conditions) will then invest in high-cost Australia.
>
> What do India or Africa offer Rio and other mining companies? Massive and high-quality ore reserves and labour costs massively cheaper than in Australia.
>
> What happens when Rio, perhaps enlivened with Chinese assistance, develops these massive projects in Africa and/or India?
>
> Those projects offshore will compete against Australian mines and interests for many decades to come.
>
> How will this help us to create more jobs? How will this help us to repay our growing debt? How will this help us maintain or grow standards of living?

Rinehart views FDI policy in protectionist terms, but her claim that Australian mining projects cannot compete with those in emerging markets is at odds with those who oppose the tie-up on the grounds that Chincalco would *over-develop* Australian resources with a view to lowering prices.  The opposition to Chinese FDI in the Australian mining industry is fundamentally incoherent.

In sharp contrast to Gina Rinehart, [Peter Gallagher](http://www.petergallagher.com.au/index.php/site/article/malcolm-turnbull-on-chinalcos-bid-for-rio/ "Peter Gallagher") has an excellent post responding to Malcolm Turnbull’s concerns about the proposed Chinalco-Rio tie-up.
