---
title: "The RBA and the Media Revisited"
date: "2009-11-03"
categories: ["Economics", "Financial Markets", "Monetary Policy"]
---

I featured in a [Lateline Business](http://www.abc.net.au/lateline/business/items/200911/s2731380.htm "Lateline Business") story last night on Reserve Bank media backgrounding in relation to monetary policy.  Lateline Business supervising producer Richard Lindell deserves considerable credit for pursuing this story in the face of both official and unofficial stonewalling.  Credit is also due to [Alan Kohler](http://www.businessspectator.com.au/bs.nsf/Article/interest-rate-RBA-hike-Gittins-Mitchell-pd20091007-WL6C8?OpenDocument "Alan Kohler"), [Adam Carr](http://www.businessspectator.com.au/bs.nsf/Article/SCOREBOARD-RBA-leaks-pd20091006-WJSP7?OpenDocument "Adam Carr") and [Christopher Joye](http://www.businessspectator.com.au/bs.nsf/Article/What-does-the-RBAs-Board-do-pd20091016-WV43R?OpenDocument "Christopher Joye"), who have all spoken out on this issue.  Some of the people who originally agreed to appear on camera for the story were prevented from doing so by their employers.  As I said to Richard Lindell, ‘now you know why market economists don’t criticise fiscal stimulus.’

A 2001 *AFR Magazine* profile of then RBA Governor Ian Macfarlane by Peter Hartcher quoted a former RBA official as saying:

> *The Bank uses newspapers to manage expectations.  It’s a game the Bank manages very well.  Senior people talk to a small handful of the economics writers from the major papers on a strictly non-attributable basis.*

The quote was re-produced in Stephen Bell’s 2004 book on the Reserve Bank, *Australia’s Money Mandarins* (see my [review](http://www.cis.org.au/policy/spring04/spring04-9.pdf "review")).  Journalists and academics should be the standard-bearers for due process, procedural fairness and public accountability.  Yet many commentators view the RBA’s manipulation of the media as simply a clever use of power. 

The practice is a legacy of a less transparent era at the Reserve Bank.  With so many open channels of communication now available to the Bank, there is no longer any excuse for it to continue.

There is more on Reserve Bank governance [here](http://www.cis.org.au/policy/autumn_08/Links/kirchner_autumn08.pdf "here").
