---
title: "The FIRB and the Rule of Law"
date: "2009-09-28"
categories: ["Economics", "Foreign Investment"]
---

If you need further evidence that the rule of law is largely non-existent with respect to foreign direct investment in Australia, you need look no further than a speech FIRB director Patrick Colmer gave to the Australia-China Business Council last week, as reported in [The Australian](http://www.theaustralian.news.com.au/story/0,25197,26121992-25837,00.html "The Australian"):

> Mr Colmer said many of the foreign investment decisions were matters of “policy” rather than black-letter law.
>
> He said the government had to balance the need for an orderly flow of foreign investment into Australia with the need to ensure continued public support for foreign investment proposals.
>
> “One of the problems we have also seen is where lawyers get involved and try to turn a policy argument into a legal debate,” Mr Colmer said. “It is not effective. The lawyers don’t like us telling them that, but we do try to steer people through the policy issues rather than the legal issues ... Don’t turn it into a legal stoush, and deal with us the way we like to deal with you - in confidence.”

The last thing FIRB wants is a review of decisions on common law grounds (other forms of administrative and judicial review being effectively precluded).  As the ACCC would no doubt tell their FIRB colleagues, legal process and case law are the enemies of bureaucratic discretion. 

Perhaps the most tragic aspect of Colmer’s speech is that it was actually welcomed by [some commentators](http://www.theaustralian.news.com.au/story/0,25197,26121948-7583,00.html "some commentators") as a clarification of the regulatory regime for FDI.  This interpretation would be somewhat less ludicrous if Colmer’s speech were actually a publicly available document, accessible by foreign investors.  FIRB is evidently too busy micro-managing FDI on behalf of the Treasurer to put the speech on its web site.  I have emailed FIRB requesting a copy, but have no expectation of receiving a reply.
