---
title: "The End of Inflation Targeting?"
date: "2009-11-19"
categories: ["Economics", "Financial Markets", "Monetary Policy"]
---

The leader of the opposition New Zealand Labour Party, Phil Goff, has announced the [abandonment of his party’s support for inflation targeting](http://online.wsj.com/article/SB125859982621354935.html "abandonment of his party’s support for inflation targeting") by the Reserve Bank of New Zealand.

It was a Labour government that introduced the Reserve Bank of New Zealand Act in 1989, making New Zealand a global pioneer in the practice of inflation targeting.

I have long suspected that the global trend towards increased central bank independence and inflation targeting would eventually be reversed.  As I noted in my [Bubble Poppers](http://www.cis.org.au/policy_monographs/pm93.pdf "Bubble Poppers") monograph, even the central banking community is increasingly divided on the issue. 

If the bipartisan consensus in favour of inflation targeting can be shattered in New Zealand, it can happen anywhere.
