---
title: "The Terms of Trade: Not Dead Yet"
date: "2009-01-24"
categories: ["Economics", "Financial Markets"]
---

The [December quarter trade prices release](http://www.abs.gov.au/AUSSTATS/abs@.nsf/Lookup/6457.0Main+Features1Dec%202008?OpenDocument "December quarter trade prices release") saw the largest quarterly and annual increases in export prices since the current series began in the September quarter 1974, at 15.9% q/q and 54.9% y/y.  Import prices were up 10.8% q/q and 21.1% y/y, the largest annual increase since the December quarter 1985.  The merchandise terms of trade are up nearly 30% on a year ago.

How did Australia pull-off a further gain in the terms of trade against the backdrop of collapsing world commodity prices?  The depreciation in the Australian dollar over the quarter, which supported Australian dollar commodity prices.  This is a very good illustration of the role of a floating exchange rate in insulating the economy against external shocks. 

Given the magnitude of the external shock now confronting the Australian economy, the appropriate exchange rate response is massive depreciation.  In this context, US dollar strength is perfectly explicable, because weakness in the US economy is an external shock for the rest of the world. 

Unfortunately, this may see pressures for competitive devaluations and foreign exchange market intervention, not least on the part of the new US Administration.  This would be in sharp contrast to the highly principled stance the Bush Administration took against intervention in foreign exchange markets.  The new US Treasury Secretary, Tim Geithner, was a protégé of former Treasury Secretary Robert Rubin, who presided over massive intervention in foreign exchange markets.
