---
title: "The Political Economy of House Price Doom-Mongering"
date: "2009-08-31"
categories: ["Economics", "Financial Markets", "House Prices"]
---

The [Rismark](http://www.rismark.com.au "Rismark") Monthly for August suggests the following explanation for house price doom-mongering:

> It’s very easy to rip into housing since it is a non-institutionalised asset class. All of Australia’s 8.4 million homes are owned by highly dispersed and faceless families.  Australian and international equities, LPTs, unlisted commercial property, hedge funds, and private equity are, by way of comparison, mostly owned and controlled by powerful institutional stakeholders—fund managers, super funds, investment banks, corporates and/or super high net worths.  In turn, most of the analysts, strategists, economists, investors and journalists’ business models are built on these asset-classes succeeding. It therefore makes little commercial sense to bludgeon them with the relentless hysterics we hear about housing.  In contrast, bricks and mortar is easy game. There are few if any institutional constituents to annoy. Just anonymous individual families with little authority and influence.
>
> Making unsubstantiated claims about a forthcoming housing Armageddon is a win-win situation. With one hand you distract attention away from the poor performance of your own Australian equities portfolio, while with the other you boost the likelihood of unsuspecting retail money flowing your way.

While this explains the sell-side bias against housing, it is harder to understand the buy-side interest in doom-mongering.  Presumably, the media know their own market and stories of housing boom and bust undoubtedly sell.
