---
title: "The Running of the Bears"
date: "2009-02-12"
categories: ["Economics", "Financial Markets"]
---

The top seven [attention-hungry doomsayers](http://www.thedailybeast.com/blogs-and-stories/2009-02-11/top-seven-attention-hungry-doomsayers/full/ "attention-hungry doomsayers"):

> The Running of the Bears only happens every ten years or so, so you’ve got to give the likes of Roubini, Whitney, Schiff, and Taleb a break for seeking to monopolize our attention while they’ve got it. After all, nobody likes a pessimist, and we’ll tune them out as soon as we’re brave enough to do so. That said, the depth of the current crisis suggests this bear market may last a little longer than the last few, so get used to hearing their names. Taleb’s got at least one more book in him about how smart he is.
>
> Of course, even a stopped clock tells the correct time twice a day. If the likes of Whitney or Roubini want to truly cement their place in the history of financial prognostication, they will show the foresight to call a turn in the other direction, back to bullish conditions. Elaine Garzarelli made herself famous calling the 1987 crash. She never made another big one again.
