---
title: "The End of America"
date: "2009-08-11"
categories: ["Economics", "Financial Markets"]
---

If people are most bearish near the bottom of the cycle, it is probably a good sign that Slate has been running an interactive feature on [The End of America: How It Will Happen](http://www.slate.com/id/2224425/pagenum/all/#p2 "The End of America: How It Will Happen").  It is even more encouraging that of the top five apocalyptic scenarios most favoured by Slate readers, two are economic crankery deserving little serious consideration: ‘peak oil’ and ‘China Unloads U.S. Treasurys’ \[sic\].

There are more prosaic reasons for considering the ‘end of America’, at least as we once knew it, as suggested in David Goldman’s [Top Ten Reasons Why the Recession Will Last Forever](http://blog.atimes.net/?p=1113 "Top Ten Reasons Why the Recession Will Last Forever"):

> *1. Barack Obama.  Bill Clinton, the last Democratic president, thought in effect, “Let’s get economic growth so I can tax it and pay for all my toys and games.” That was the “New Democrat” approach. Obama knows that if the economy crumbles and he’s the only one left with a checkbook, then everyone has to come to him. Where is the independent base of entrepreneurial business to which the Republicans might turn to raise money against Obama? The banks, the hedge funds, the manufacturers, the municipalities, in fact everyone who is left standing in the economy is beholden to Obama. This is Chicago city politics writ large. Leave aside all of the individual things that Obama is doing that harm economic growth: Obama is the first American president (with the possible exception of FDR) to actually benefit from economic weakness.*
