---
title: "The Myth of an Independent Treasury"
date: "2009-05-16"
categories: ["Economics", "Fiscal Policy", "Media", "Monetary Policy", "Politics"]
---

My CIS colleague and former Treasury official Robert Carling has an op-ed on page 21 of today’s Australian (no link, but see text below the fold) noting that neither Treasury nor the Budget papers are independent of the federal government. 

The claim that Treasury is an institution independent of government fundamentally misconstrues the relationship between the federal government and the Commonwealth public service.  While it is not surprising to see politicians fail Economics 101, it is more surprising to see them also failing Political Science 101. The government now routinely hides behind Treasury and RBA independence and the federal opposition is increasingly accommodating this behaviour through their unwillingness to challenge official sector views.

While the RBA is more independent than Treasury, this independence is limited in scope.  At its most basic, RBA independence means that it is free to set interest rates without the approval of the Treasurer, what is often called ‘operational independence.’  This independence in no sense precludes the government or opposition from taking a different view on monetary policy to the RBA or being publicly critical of central bank policy actions, statements and forecasts.  The RBA has been made progressively more independent of government precisely in order to facilitate differences of opinion with government.  Under the Reserve Bank Amendment (Enhanced Independence) Bill, it is almost impossible to remove the RBA Governor, so public criticism could hardly be viewed as a threat to the Governor’s position.  By the same token, the RBA would not be compromising its independence by speaking out on issues relating to its statutory responsibilities, provided it does so in a non-partisan fashion.

Mistaken notions of Treasury and RBA independence are being used to suppress public debate over economic policy, not least by the current government.  That the federal opposition and media are accommodating this behaviour on the part of the government can only undermine the robustness of public debate and democratic accountability. 

**The Myth of Treasury Independence**\
by Robert Carling, Senior Fellow, Centre for Independent Studies

The Treasury’s ‘independence’ has featured in the post-budget commentary.  As a former Commonwealth and state treasury official I find this surprising, because I can recall very few moments of independence in 27 years.  I suspect that the current generation of treasury officials around the country has even less reason to feel independent. 

Claiming independence for the Treasury, as the Prime Minister did on a post-budget television interview, is a way of ducking government accountability, even though a glance at the budget papers shows that they are “circulated by the Treasurer and the Minister for Finance for the information of honourable members”.

The reality is that the Treasury is a department of state whose constitutional role is to give policy advice to the government, implement policy decisions of the government and administer certain pieces of legislation.  It has statutory obligations which cannot be overridden by ministerial command, but in any other sense it is not ‘independent’.  It is not a think tank or a university.  It is not even like the Reserve Bank, which does have independence in monetary policy and issues its own forecasts. 

So ‘independent’ is the wrong word, but stopping the story there would be selling the Treasury seriously short.  There is something else the Treasury should be allowed to be.  The nature of its responsibilities and the talent and motivation of its staff are such that as an institution it can contribute enormously to the rigour of public policy - provided it is allowed to do what it does best without political second-guessing.  It can be a protector of the public interest and a bastion of fiscal discipline and credibility when there are precious few others to serve in those essential roles.  This is what a former Secretary to the Treasury meant when he often described his department as a ‘national treasure’. 

But it can only be a national treasure if the government of the day allows it to be.  It is up to the government how much free rein Treasury is given to do and present its technical work and participate in the public debate on matters within its domain.  Any government can trash the national treasure by demanding fudged figures and turning the Treasury into just another spruiker for government policy.  That is a power any government would abuse at great damage to its own credibility and that of the nation’s fiscal policy.  A government would be insane to abandon the self-discipline of a treasury kept a safe distance from political interference.

Insanity has not yet taken over, but over many years there has been a gradual weakening of the dividing line between the political work of the government and the technical work of the Treasury.  Even the budget speech was once written by senior Treasury officials.  The result was long, eloquent, credible and boring.  Now it is just theatrical and boring.  And the language of the spruiker now infects the budget papers, like a virus that has mutated from the budget speech.

We are told in Statement 3 that “The government has been prepared to make the hard decisions now in order to position Australia for the future..…”  Really?  One wonders how such a statement got there.  We are also reassured that “There is scope for tax receipts to recover, while maintaining our (sic) commitment to keep taxation as a share of GDP below the 2007-08 level.”  If those words were penned in the Treasury, the author presumably did not feel independent.  Then there is the voluminous ex post rationalization of the fiscal stimulus packages, which contributes to the extraordinarily defensive tone of the budget papers.  The budget papers are devalued by this sprinkling of politically inspired bull dust.

Economic forecasting is technical work, and revenue and expenditure estimation (for a given set of policies) even more so.  The Treasury and others involved must be allowed to do their best technical work without political second-guessing, not because they know all but because they know more and because this work has to be kept beyond political temptation. 

Interference need not be anything as crass as an instruction to substitute one number for another.  I never experienced anything of that kind.  It can take more subtle forms, such as microscopic political scrutiny and questioning of the forecasts and estimates, which can lead public servants sub-consciously to anticipate the politicians’ views in the judgmental overlay that has to go with any technical work.

There is no reason to think that the economic and revenue forecasts in the latest budget are anything other than Treasury’s best guesses.  For all that has been said, they look plausible.  But the more the government feels it necessary to make false claims about the Treasury’s independence, and the more the Treasury is drawn into the political process, the more it seems we really do need a new and truly independent fiscal authority to put the budget basics beyond political temptation.
