---
title: "The Trans-Tasman Battle for FDI"
date: "2009-07-31"
categories: ["Economics", "Foreign Investment"]
---

I have an [op-ed in today’s Age](http://business.theage.com.au/business/nz-tries-harder-for-foreign-cash-20090730-e33z.html?page=-1 "op-ed in today’s Age") contrasting the New Zealand government’s liberalisation of its regulatory regime for foreign direct investment with the Australian government’s growing use of FDI regulation as an extension of domestic industry policy (note that there is a minor sub-editorial error: the third para should read ‘by 40%’ not ‘to 40%’).  I predict that this will add to Australia’s underpeformance in attracting its share of global FDI.

[Bryan Frith](http://www.theaustralian.news.com.au/business/story/0,28124,25849966-16941,00.html "Bryan Frith") wrote-up my proposals to reform Australia’s regulatory regime for FDI in The Australian, concluding that ‘While the Rudd government is in reformist mode, it should take a serious look at Kirchner’s suggestions.’  However, as my Age op-ed notes, the Rudd government is moving in the opposite direction to the one I set out in [Capital Xenophobia II](http://www.cis.org.au/policy_monographs/pm88.pdf "Capital Xenophobia II").
