---
title: "The Ken Henry Speech that Time Forgot"
date: "2009-05-20"
categories: ["Economics", "Fiscal Policy"]
---

Treasury Secretary [Ken Henry](http://www.treasury.gov.au/documents/996/HTML/docshell.asp?URL=Sydney_Institute_speech.htm "Ken Henry"), speaking to the Sydney Institute in 2005:

> By the 1990s, however, a consensus had emerged, in Australia and elsewhere, that fiscal activism had to be limited. Fiscal policy had to be given a medium-term anchor. At the same time, a view emerged that macro stabilisation should be primarily the responsibility of monetary policy. But monetary policy, too, had to have a medium-term anchor….
>
> The last of these observations is particularly striking for a student of post-war economic history: one has to wonder whether the policy debate in this country is not the sort of thing that one might have hoped to see in a ‘classical’ economy of the sort that economists thought existed before the Great Depression and the ensuing Keynesian revolution; a debate about the factors that influence our productive capacity rather than the factors that influence our demand for it…
>
> It might be worth asking the question whether, because of the reform efforts of the past, we should not now consider ourselves to be most often in a ‘classical’ world in which the economy naturally trends toward, and in fact spends most of its time quite close to, its productive capacity, or supply potential, without the need of continuous macro policy stimulus.
>
> Answering this question in the affirmative would not imply a view that we have eliminated the business cycle. There will be future economic downturns. And when we see evidence of one we should not be afraid of responding with activist expansionary macroeconomic policy.  Rather, an affirmative answer implies some conditioning of the exercise of macro policy activism – an acceptance that large swings in macro instruments are to be implemented (only) in extremis…
>
> let me say something about the emerging pressure for increased infrastructure spending. This pressure is mostly well-intentioned – more spending on infrastructure will indeed tend to increase the productive potential of the economy. And, with long-term interest rates and therefore the cost of capital at a cyclical low at the moment, both the public and private sectors are in a relatively strong position to undertake additional spending.
>
> But without appropriate price signals, quality investment decisions will not be made. And present price signals are far from appropriate. The risks of making large infrastructure investment decisions in such an information-poor environment are very great.
