---
title: "The Colmer Doctrine?"
date: "2009-10-02"
categories: ["Economics", "Foreign Investment"]
---

[Matthew Stevens](http://www.theaustralian.news.com.au/business/story/0,28124,26152689-5001641,00.html "Matthew Stevens") coins the phrase ‘the Colmer Doctrine’, but as his own analysis suggests, the real problem is the complete absence of anything that could be called a doctrine:

> There are two quite different conclusion\[s\] to draw from Colmer’s contribution to last week’s Australian China Business Council conference. Either he is a very new kind of beast in FIRB, in that he has seized the opportunity offered by government uncertainty to help shape foreign investment policy.
>
> Or, as is far more likely, the commentary he offered was vetted and approved by a government still unwilling to formally define its preferences on Chinese investment…
>
> That we are 18 months into our national reflection on China’s investment intentions and we are still so unsure about the FIRB process says only that the government had failed to plainly explain its policy.
>
> That failure would seem to reflect either policy uncertainty or a failure of will. Either way, it is time to sort it out.
