---
title: "The Failure of US Fiscal Policy"
date: "2009-01-15"
categories: ["Economics", "Fiscal Policy"]
---

When it comes to activist fiscal policy, it seems that nothing succeeds like failure.  The failure of the economy to respond to previous stimulus measures is always seen as an argument for yet more stimulus, rather than supporting the more obvious conclusion that activist fiscal policy doesn’t work.  As [Philip Levy](http://online.wsj.com/article/SB123189508831779607.html "Philip Levy") notes, if the existing US budget deficit won’t budge its economy, there is nothing the Obama Administration can add that is likely to make a difference:

> The Congressional Budget Office projected last week that even without a stimulus package, the federal budget deficit will hit \$1.2 trillion this year. That’s 8.3% of gross domestic product. Followers of the late John Maynard Keynes should be thrilled. Such a gap between government spending and taxes was just what he prescribed to stimulate a slumping economy.
>
> And yet the stimulus enthusiasts seem unsatisfied. President-elect Barack Obama argues that this level of stimulus would leave us with shattered dreams and long-lasting torpor. Our only chance is to adopt his plan of \$800 billion in additional stimulus spending over the next two years. So \$1.2 trillion in deficit spending leaves us in despair, but \$1.6 trillion in deficit spending brings prosperity…
>
> there is very little science behind arguments that an additional \$800 billion stimulus should do the trick.

Unfortunately, the political imperative is for governments to be seen to be doing something, regardless of whether it works or not.
