---
title: "The Great Pat Colmer Speech Hunt"
date: "2009-10-02"
categories: ["Economics", "Foreign Investment"]
---

[Glenda Korporaal](http://www.theaustralian.news.com.au/business/story/0,28124,26152575-5013510,00.html "Glenda Korporaal") weighs in on the Pat Colmer speech:

> A week later the FIRB says there is no transcript of the speech, and the Australia China Business Council, which is to be commended for organising a conference with a wide range of Australia-Chinese experts, has been deluged with requests for a copy from every lawyer advising on foreign investment.
>
> As of yesterday afternoon none was available…
>
> The fact that the speech is not yet available—and may not be made available—to people who would genuinely like guidance on foreign investment applications can only add to the potential for criticism that Australia’s foreign investment policy is less than clear…
>
> That said, there is still a real hunger for more information and more clarity about both the official policy and the administration of that policy.
>
> This is an issue that should be acknowledged and addressed at higher levels than the FIRB director, but making the speech generally available would be a start.

The Executive Director of the FIRB is the designated [Australian National Contact Point](http://www.ausncp.gov.au/content/contact_point.asp?areaid=18 "Australian National Contact Point") (ANCP) under the OECD Guidelines for Multilateral Enterprises.  According to the government, ‘the ANCP is committed to carrying out these responsibilities in accordance with the Guidelines requirement for NCPs to be visible, accessible, transparent, and accountable.’

All rhetoric, no substance.
