---
title: "‘They will just dig them up and cart them away’"
date: "2009-02-26"
categories: ["Economics", "Financial Markets", "Foreign Investment"]
---

The FT’s [David Pilling](http://www.ft.com/cms/s/0/7b389e4a-0371-11de-b405-000077b07658.html "David Pilling") on the proposed increase in Chinalco’s stake in Rio:

> But to say there is state involvement is not the same as imagining a monolithic apparatus planning world domination. In any case, the west, whose banks, carmakers and god-knows-what else are underwritten by the state, is not in an ideal position to lecture others. If China wants to use its trade surplus to secure mineral resources, one response might be: so what? But Chinese companies, even state-owned ones, are as likely to be engaged in cut-throat competition as in cosy cartels or state-sponsored carve-ups.
>
> That undermines the idea that Chinalco, an aluminium maker with no need of iron ore, would seek to persuade Rio to sell cheaply to China Inc. Even if Chinalco were in a position to influence price negotiations – and with just two board members that seems doubtful – it is more likely to try to maximise prices for its own sake than to minimise them for China’s good.
>
> Evidence that China’s forays abroad have been led by companies, and not orchestrated by an all-knowing state, is plentiful. Chinese companies often compete for the same asset. Both Shanghai Automotive and Nanjing Auto bid for Rover when the UK carmaker went chassis-up. Fears that Beijing is making a huge asset grab while the world reels from financial crisis also ignore the fact that foreign adventures are out of vogue in China. State institutions that invested in sinking foreign banks have faced public outrage for squandering national resources.

Pilling quotes NLP Senator Barnaby Joyce as saying:

> *“If they own the resources, they will just dig them up and cart them away.”*

Yes, Barnaby - that’s how mining works.
