---
title: "Tony Abbott Offers Support for a Carbon Tax"
date: "2009-11-27"
categories: ["Economics", "Financial Markets", "Politics"]
---

[Tony Abbott](http://www.theaustralian.com.au/news/opinion/nation-held-hostage-to-ets/story-e6frg6zo-1225804353196 "Tony Abbott") offers support for a carbon tax as an alternative to an ETS in today’s Australian:

> *many respected economists think a carbon tax would be more certain, less complex and far less open to manipulation than traded carbon permits.*

In government, Malcolm Turnbull showed considerable interest in Warwick McKibbin’s proposal for a hybrid ETS-carbon tax.  This story from February 2007 (’[Turnbull gives tick to McKibbin carbon trading model](http://www.theage.com.au/news/business/turnbull-tick-for-carbon-plan/2007/02/18/1171733612617.html?page=fullpage# "Turnbull gives tick to McKibbin carbon trading model")’) quotes McKibbin as saying that Turnbull ‘understands it completely’, which makes Turnbull’s subsequent support for Labor’s ETS all the more inexcusable.

The Liberals who support Labor’s ETS do so largely because they are too lazy to argue for the alternative policy approaches they know to be better.  I have heard several Liberal frontbenchers maintain that any policy with the word ‘tax’ in it won’t gain political support.  They support an ETS only because they want to neutralise climate change as a political issue, not because they believe it to be the best policy.  This is a monumental failure of leadership.

An obvious way forward for the Liberal Party, and for the Coalition, would be to commission McKibbin to design a hybrid scheme to take to the next election as an alternative to Labor’s ETS.

**UPDATE:** Joe Hockey goes begging for ideas on [Twitter](http://twitter.com/JoeHockey "Twitter"):

> *Hey team re The ETS. Give me your views please on the policy and political debate. I really want your feedback.*

As David Cameron once said, too many tweets make a twat.
