---
title: "Too Much Hand Wringing, Not Enough Hand Raising"
date: "2009-07-07"
categories: ["Economics", "Financial Markets", "Monetary Policy"]
---

The Australian’s FoI desk has [another stab](http://www.theaustralian.news.com.au/story/0,25197,25743833-601,00.html "another stab") at the decision-making processes of the RBA Board, this time seeking voting records, but comes up empty-handed:

> “There are no records as the board seeks to achieve a consensus without the need for formal voting,” the board’s secretary, David Emanuel, wrote in response to The Australian’s request.
>
> “The board now seeks to make decisions by consensus and only the consensus decisions are recorded.”

This remarkable unanimity implies that the RBA Board is little more than a rubber stamp for decisions made by the RBA’s senior officers.  Now that the RBA and Treasury effectively control the appointments process to the Board, there is little chance that this bureaucratic monopoly over monetary policy decision-making will ever be effectively challenged.  I make the case for an alternative model of RBA governance in this [article](http://www.cis.org.au/policy/autumn_08/Links/kirchner_autumn08.pdf "article").
