---
title: "Vindicating Fightback"
date: "2009-09-15"
categories: ["Economics", "Financial Markets", "Monetary Policy", "Politics"]
---

I join the history wars with an op-ed in today’s [Australian](http://www.theaustralian.news.com.au/story/0,25197,26073025-5013479,00.html "Australian") taking issue with Paul Kelly’s claim that ‘the defeat of Dr Hewson’s policy \[of Reserve Bank reform\] laid the basis for the successful monetary policy of the Keating-Howard era.’  I make the case that:

> *Far from being a repudiation of Fightback, as Kelly suggests, subsequent developments have largely vindicated its vision for monetary policy reform.*

 

REVELATIONS in Paul Kelly’s The March of Patriots that then Reserve Bank of Australia governor Bernie Fraser planned to invoke provisions of the Reserve Bank Act to frustrate a Hewson government’s reforms to monetary policy after the 1993 election should not come as a surprise.

The Reserve Bank’s opposition to John Hewson’s plans for reform was well known at the time. Yet within only a few years of the Coalition’s 1993 election defeat, the key elements of this reform agenda would be reflected in the conduct of monetary policy.

The Coalition’s Fightback manifesto, released at the end of 1991, laid out a vision for an independent Reserve Bank with a medium-term price stability mandate and subject toincreased transparency and accountability. Today, these are uncontested features of Australia’s macro-economic policy framework, enjoying bipartisan political support. How is it, then, that between 1991 and 1993 reform of the Reserve Bank could be so politically contentious?

In the early 1990s, the Reserve Bank did not enjoy the largely uncritical press it receives today.

The conduct of monetary policy in the 80s was fundamentally incoherent, unsuccessfully pursuing multiple objectives and shrouded in a veil of secrecy.

Without a policy commitment to price stability, the Australian economy lacked a nominal anchor. Former Reserve Bank governor Ian Macfarlane said in his 2006 Boyer Lectures that “the excessive speculative activity in Australia in the late 80s was partly caused by the fact inflationary expectations had not yet been brought down to a low level”.

Kelly notes in his earlier book The End of Certainty that the Reserve Bank had “made manifestly faulty judgments” in its conduct of monetary policy in the 80s. The then opposition Coalition recognised that control over inflation and inflation expectations was a prerequisite for sustained economic growth.

To this end, the Coalition “formally committed itself to the medium-term objective of price stability” and an independent Reserve Bank in its Fightback manifesto. Formal independence was to be balanced with an accountability and transparency regime, including regular appearances of the governor before a parliamentary committee.

The proposed reforms took their inspiration from the Reserve Bank of New Zealand, which had pioneered central bank independence and inflation targeting in 1990, just a year before the release of Fightback. The Coalition’s plans for Reserve Bank of Australia reform encountered resistance largely because they were so far ahead of their time.

Fightback noted that price stability was “universally conceded to be an inflation rate of (0per cent to 2per cent)”. This worried the Reserve Bank. In the early 90s, Australia did not have a track record of sustained low inflation. The Reserve Bank’s senior officers did not relish the prospect of being held accountable for achieving what had eluded them for the better part of two decades.

In The March of Patriots, Fraser claims he would have not only confronted a Coalition government’s attempts to reform monetary policy but that he would have prevailed in any such conflict. He apparently supposes that a Hewson government would have overridden a decision of the Reserve Bank board and imposed an even tighter monetary policy than the board was prepared to support.

Only then would Fraser and the board have been in a position to table their dissent from the government’s position in parliament.

Yet Hewson’s planned supply-side reforms (such as labour market deregulation) would have made the Reserve Bank’s job of controlling inflation much easier by easing structural pressure on inflation. Unlike in the 80s and early 90s, Australia would no longer have needed a recession to achieve lowinflation.

Assuming a Hewson-led government had succeeded in legislating a medium-term inflation target of 0per cent to 2per cent, the onus would have fallen on the governor and the board to explain any failure to deliver on the statutory mandate given to them by parliament. The newly transparent and accountable Reserve Bank would not have been in a position to defy the will of parliament.

In the years following the Coalition’s 1993 election defeat, the Reserve Bank quietly moved in the direction of an informal inflation targeting regime. Its independence was finally made explicit and its inflation target formalised with the election of the Howard government in 1996.

Following the election of the Rudd government in 2007, the Reserve Bank adopted additional transparency measures and the present government has further entrenched the independence of the Reserve Bank governor.

Far from being a repudiation of Fightback, as Kelly suggests, subsequent developments have largely vindicated its vision for monetary policy reform.

The main point of difference between Fightback and today’s inflation targeting regime is that Fightback sought a medium-term inflation target of 0per cent to 2per cent, rather than the 2per cent to 3per cent that now forms part of the Statement on the Conduct of Monetary Policy.

In this regard, Australia’s inflation targeting regime remains internationally anomalous. Even NZ’s revised 1per cent to 3per cent target has a lower midpoint than Australia’s.

The 2.5per cent average inflation rate considered a policy triumph in Australia would still be regarded as too high in countries such as the US.

Successive statements on the conduct of monetary policy have thus institutionalised a slightly higher average inflation rate than comparable developed countries, where price stability is still “universally conceded” to be in the range of 0per cent to 2per cent.

Little wonder, then, that Australia still has some of the developed world’s highest nominal interest rates, a lasting legacy of Fightback’s political defeat in 1993.

Stephen Kirchner is a research fellow at the Centre for Independent Studies and the author of Reforming Central Banking (CIS, 1997). He was an adviser to the federal Coalition from 1988 to 1993.
