---
title: "What If You Got Pink Bats and a School Hall for Christmas?"
date: "2009-10-19"
categories: ["Economics", "Fiscal Policy"]
---

[Scroogenomics](http://blogs.wsj.com/economics/2009/10/16/qa-scroogenomics-author-on-the-holidays-orgy-of-wealth-destruction/ "Scroogenomics") author Joel Waldfogel, on the welfare costs of poorly chosen Christmas gifts:

> My favorite way to do it is to compare what would you be willing pay for stuff that you receive as a gift per dollar spent versus what would you be willing to pay for stuff you bought for yourself per dollar spent. The surveys converge on the idea that it is about 20% less. U.S. holiday spending per year is conservatively about \$65 billion. So about 20% of that, something like \$13 billion a year, is what’s destroyed through gift giving in the U.S. But it turns out it is by no means limited to the U.S.
>
> You see the same pattern of spending in almost every major western economy, with a big bump in spending in December. You don’t see it in China and you don’t see it in Israel. But you see it in every country that is predominantly Christian, and some that aren’t. Japan also has it in a big way. If you add up that spending in the other major OECD economies you get, instead of \$65 billion alone for the U.S., \$130 billion (in holiday spending). There’s every reason to believe the dead weight loss is as big elsewhere. That would get you to \$25 billion a year around the world in value destroyed through gift giving.

An almost perfectly analogous argument can be made against fiscal stimulus of the non-cash variety, except that the government has even less knowledge about your preferences, has even less of an incentive to satisfy them and you get sent a tax bill for the gifts you didn’t want.  The rush to push stimulus dollars out the door is similar to the mad rush to buy presents before Christmas, resulting in poor quality spending decisions.  The political Santa Claus also has a rather more selective view of who has been ‘naughty’ and who has been ‘nice’. 

Fiscal stimulus spending is often viewed as valuable in its own right, as if it doesn’t matter what the government spends money on.  When asked whether his proposal for less Christmas gift-giving would be bad for the economy, Waldfogel notes:

> *I’m not against spending, I’m just against spending done ignorantly by others… Although George Bush said go out and spend and other folks have exhorted us to spend at times, spending is not really a measure of success or satisfaction… When we say it is good for the economy, we can’t just look at the amount of spending, we want to think about the amount of satisfaction that we’re getting from the spending.*

While Waldfogel’s argument is less applicable to so-called ‘cash splashes’, last year’s cash hand-outs were strategically timed just before Christmas.  We will never know just how much of last year’s pre-Christmas cash splash ended-up in the great national stockpile of unwearable socks and ties.
