---
title: "What is Seen and What is Not Seen: Cow Candy Edition"
date: "2009-01-06"
categories: ["Economics"]
---

From the office of the Treasurer, [Wayne Swan](http://www.treasurer.gov.au/DisplayDocs.aspx?doc=pressreleases/2009/001.htm&pageID=003&min=wms&Year=&DocType= "Wayne Swan"):

> Today I visited the Biocane Mill at Bli Bli on Queensland’s Sunshine Coast and announced the reinstatement of a \$1 million funding grant to help complete the construction of a factory at the site.
>
> The company, Biocane Ltd, will use the factory to manufacture stock feed from sugar cane using technology pioneered in Australia that produces a dry sweet fodder, known as ‘Cow Candy’, which is exported to cattle feedlots in East Asia…
>
> The Minister took an active interest investigating this issue because he understands how important it is to support local businesses and has now reinstated the funding.
>
> Biocane Ltd has advised that it will employ 32 people at the Bli Bli plant to complete the construction and upon completion about 18 permanent jobs will be created initially at the mill, as well as flow-on employment for sugar cane farmers and their employees.
>
> Having grown up at Nambour I know first hand how important this funding will be to the sugar cane industry and the economy of the Sunshine Coast region.

Pity they didn’t teach [Bastiat](http://www.econlib.org/library/Bastiat/basEss1.html#Chapter%201 "Bastiat") at Nambour High:

> But the disadvantage that the taxpayers try to free themselves from is what is not seen, and the distress that results from it for the merchants who supply them is something further that is not seen, although it should stand out plainly enough to be seen intellectually.
>
> When a government official spends on his own behalf one hundred sous more, this implies that a taxpayer spends on his own behalf one hundred sous the less. But the spending of the government official is seen, because it is done; while that of the taxpayer is not seen, because—alas!—he is prevented from doing it.
