---
title: "‘Whatever it Takes’: A Wicked Idea"
date: "2009-04-17"
categories: ["Economics", "Fiscal Policy"]
---

[Jamie Whyte](http://www.timesonline.co.uk/tol/comment/columnists/guest_contributors/article6094001.ece "Jamie Whyte"), on the long-term damage wrought by fiscal stimulus measures:

> So, despite near universal agreement that governments must do “whatever it takes” to avoid a severe recession, this is an absurd idea. Perhaps even a wicked idea. The important question about the kind of actions most governments are now taking – “bailing out” failed companies and massively increasing government spending – is what their long-term effects will be.
>
> Those few commentators who worry about long-term effects tend to focus on the debt burden created by stimulus packages. But this is a trivial and short(ish)-term issue. If there is no structural damage to the economy, servicing these debts will be reasonably easy. A stimulus package would simply transfer wealth from the nation’s future citizens to its present citizens. And that does not constitute a net loss to the population.
>
> Indeed, if the stimulators are right about the effects of their proposals on long-term GDP, even future citizens who bear the debt burden might be grateful for the transfer. Better to be rich with big but manageable debts than to be poor. These future citizens would be like people who had borrowed to get a medical degree.
>
> The serious question about stimulus packages concerns not the short-term accountancy, not the details of jobs today and debt tomorrow, but the structural effects on economies. Are stimulus packages really like borrowing to get a medical degree or are they more like taking brain-damaging drugs to eliminate an acute headache?

[Chris Berg](http://www.theage.com.au/opinion/how-a-joker-sent-battman-to-the-rescue-20090411-a3fo.html?page=-1 "Chris Berg") looks for method in the madness of fiscal stimulus efforts in Australia and decides the government is just making it up:

> *Sure, it seems fun watching the Government conjure up jobs and prosperity out of nowhere, but in retrospect, after none of those jobs appear, the economy keeps going down the toilet, and bureaucrats have eventually admitted they made it all up — it’s actually quite depressing.*
