---
title: "When Behaviouralists Attack"
date: "2009-06-29"
categories: ["Economics", "Financial Markets"]
---

[Scientific American](http://www.scientificamerican.com/article.cfm?id=the-science-of-economic-bubbles&print=true "Scientific American") notes the penetration of the Obama Administration by behavioural economics:

> *The arrival of the Obama administration marks a growing acceptance of the discipline. A group of leading behavioural scientists provided guidance on ways to motivate voters and campaign contributors during the presidential campaign. Cass Sunstein, a constitutional scholar who wrote the well-regarded book Nudge, which President Barack Obama has reportedly read, was appointed head of the Office of Information and Regulatory Affairs, which reviews federal regulations. Other officials who are either behavioral economists or aficionados of the discipline are now populating the White House.*

Alan Wolfe comments on the reactionary and anti-Enlightenment foundations of behaviouralism in [this podcast](http://www.econtalk.org/archives/2009/05/wolfe_on_libera.html "this podcast") with Russ Roberts.

Meanwhile, [Chris Dillow](http://stumblingandmumbling.typepad.com/stumbling_and_mumbling/2009/06/the-guardian-hoax.html "Chris Dillow") uncovers a ‘heartbreaking work of staggering genius, a brilliant illumination of class relations, post-modernism and the crisis of the left.’
