---
title: "When FDI Regulation Turns to Crap"
date: "2009-10-15"
categories: ["Economics", "Foreign Investment"]
---

[John Garnaut](http://www.smh.com.au/business/how-bhp-scuppered-china-inc-20091014-gxhs.html?autostart=1 "John Garnaut") continues to expose the chaos in the regulation of foreign direct investment in Australia:

> *a whole industry of lawyers, lobbyists and retired politicians is springing up to earn fees by promising China that they can divine the mysteries of Australia’s foreign investment laws. Many contacted by BusinessDay are critical of the review board and others are critical of the Australian media. But they are all fearful of speaking publicly, lest they offend the agency they are paid to deal with.*

Garnaut quotes my former colleague Stephen Joske on the government’s failure to construct a coherent framework for dealing with China:

> “There wasn’t strong public resistance to Chinese investment in Australia a few years ago,” he said.
>
> “But indecision from the Government and negative signals created a vacuum in which concerns grew. As soon as FIRB started to define what the national interest is they bound their hands without really resolving the issue; now FIRB is being used to fan public opinion and concerns about state-owned enterprises.”..
>
> He said he was “shocked” at Treasury’s failure to brief its boss, Swan, on the usual pros and cons of foreign investment…
>
> Joske said the investment policy setting was getting worse because of a lack of leadership.
>
> “There is no strategic framework with China,” he said. “I don’t know what caused it but it’s a fact. Because of this vacuum you get crap policy.”
>
> And the result, he said, is that the review board ‘‘has been allowed to depart from the spirit of the open economy and to effectively dominate the entire economic relationship”…
>
> “The thing that’s inexplicable is this is the overall approach to China: you’re setting foundations for Australia’s economic future,” he said. “The business lobbyists have dropped the ball, the bureaucracy is under-resourced, BHP is doing what it always does and the Opposition is making things worse.”
