---
title: "Will Australian FDI Policy Be Any More Comprehensible in Chinese?"
date: "2009-12-10"
categories: ["Economics", "Foreign Investment"]
---

[Treasurer Wayne Swan](http://ministers.treasury.gov.au/DisplayDocs.aspx?doc=speeches/2009/033.htm&pageID=005&min=wms&Year=&DocType= "Treasurer Wayne Swan") has announced an expansion of the Foreign Investment Review Board and a review of the communication of FDI policy in a speech to the Global Foundation.  The government’s first initiative will be to:

> *release an easy-to-read version of the foreign investment review framework for prospective investors, which will be made available in other languages, including Chinese, Japanese and Bahasa.*

One would of thought that such documentation already existed.  The problem is that Australian FDI policy is not going to be any less confusing in a foreign language than it already is in English.  No amount of explanation can eliminate the fundamental source of confusion and uncertainty, which is the sweeping discretion available to the Minister and FIRB under the Foreign Acquisitions and Takeovers Act. 

The debacle of the [Patrick Colmer speech](http://online.wsj.com/article/SB10001424052748704471504574442281091477054.html "Patrick Colmer speech") demonstrated that the basic communication problem stems from the government’s lack of a clear policy framework for the exercise of this discretion.  Foreign investors cannot be expected to understand a policy that the government itself cannot articulate.

**UPDATE**:[The Patrick Colmer saga continues](http://ministers.treasury.gov.au/DisplayDocs.aspx?doc=transcripts/2009/153.htm&pageID=004&min=wms&Year=&DocType= "The Patrick Colmer saga continues"):

> JOURNALIST:
>
> Do you endorse the guidelines put out by Colmer from the FIRB two weeks ago?
>
> TREASURER:
>
> Mr Colmer didn’t put out any guidelines two weeks ago, and you know that.
>
> JOURNALIST:
>
> About the 15, 50 per cent and the…
>
> TREASURER:
>
> Mr Colmer was asked a theoretical question to which he gave a theoretical answer, which I believe has been taken out of context.

Maybe the Chinese translation will be clearer.
