---
title: "Xenophobic, Not Racist"
date: "2009-09-30"
categories: ["Economics", "Foreign Investment"]
---

I have an op-ed in today’s [Wall Street Journal](http://online.wsj.com/article/SB10001424052748704471504574442281091477054.html "Wall Street Journal") on the confusion being created by the government’s discretionary approach to the regulation of foreign direct investment.

This morning I read in one of the US equity analyst reports I receive that ‘we hear out of Australia that its foreign investment regulator wants to impose 15% caps for global purchases of the country’s large companies.’  This is over-stating the situation, but is indicative of the perceptions now being created among offshore investors.

Australian mining magnate [Clive Palmer](http://www.theaustralian.news.com.au/business/story/0,28124,26144717-5005200,00.html "Clive Palmer") is not taking Patrick Colmer’s advice to leave the lawyers and media out of it and quietly cut deals in Canberra.  He is threatening to take an FDI case to the High Court.  Palmer is also calling Australia’s regulatory regime for FDI racist.  I think ‘xenophobic’ is a better characterisation (hence the title of my [monograph](http://www.cis.org.au/policy_monographs/pm88.pdf "monograph") on the subject).  Colmer effectively conceded as much when he said that part of FIRB’s role was to maintain public support for foreign direct investment by managing an ‘orderly’ flow of FDI transactions.
