---
title: "‘You Will Not Ask Me Any Questions’"
date: "2009-09-25"
categories: ["Economics", "Fiscal Policy", "Politics"]
---

Academics speaking truth to Doug Cameron at the [Senate Economics References Committee](http://www.aph.gov.au/hansard/senate/commttee/S12457.pdf "Senate Economics References Committee"):

Senator CAMERON—Who would want an academic running the economy? I said that this morning and the more I hear from academic economists the more I believe that it would be a fatal mistake.

Prof. Makin—Ben Bernanke is an ex-academic economist and he seems to be getting a lot of credit for what he has done.

\* \* \*

Senator CAMERON—Do you believe the government has made any positive economic decisions since it has come to power?

Prof. Davidson—Yes. The government delivered on the tax cuts that were promised by the Howard government.

Senator CAMERON—Is there anything else?

Prof. Davidson—The government scrapped the Fuelwatch scheme.

Senator CAMERON—Is there anything else?

Prof. Davidson—The government scrapped the GroceryWatch scheme.

\* \* \*

Senator CAMERON—Are you seriously putting to this inquiry that the federal government should play no role in investing in the nation’s road infrastructure?

Prof. Davidson—I am putting it to you that if you wanted to build roads that you would give the money to the states and allow the state governments to make decisions as to what roads they wish to build.

Senator CAMERON—That is an interesting point of view!

Prof. Davidson—We have a constitution that actually has states that make decisions about these things. You do represent the states, don’t you?

Senator CAMERON—I am here to ask the questions, not you.

Prof. Davidson—Actually, I am a taxpayer. I will ask questions too.

Senator CAMERON—You will not ask me any questions.
