---
title: "A ‘Fork in the Road’ Best Left Untravelled"
date: "2006-12-06"
categories: ["Economics"]
---

It is long time since we have heard the traditional industry policy mantra about Australia becoming ‘more than a farm and a quarry.’  One reason for this is that it is not even remotely accurate as a characterisation of the sectoral composition of the Australian economy.  Agriculture and mining combined accounted for less than 10% of gross value added in the year ended in September.  Moreover, the rationale for Australia adopting strategic industry policies designed to promote the manufacturing sector is weaker than ever.  Global manufacturing is grossly over-supplied and this is reflected in declining prices for manufactured goods.  While many people have highlighted the contribution of the commodity price boom to the improvement in Australia’s terms of trade, declining prices for imported manufactured and other goods has also made an important contribution to the increase in national welfare represented by the record level of the terms of trade.

So it was disappointing to hear newly elected opposition leader Kevin Rudd revive the old mantra with his stated desire for Australia to be ‘more than a mine for China and a beach for the Japanese.’  Unfortunately, as [Alan Wood](http://www.theaustralian.news.com.au/story/0,20867,20879835-601,00.html "Alan Wood") notes, industry policy remains alive and well in Rudd’s Australian Labor Party:

> Rudd, as with Crean and Beazley before him, denies he is interested in protectionism or, although he doesn’t use the expression, picking winners. He says, rightly, that he has sound free-trade credentials.
>
> Even so, his promise of a “detailed manufacturing blueprint out from us in the months ahead” has a disturbing echo of policies past.
>
> Rudd acknowledges his belief in industry policy “may be heretical in some quarters”. But, as he also says, he has been a long-term believer in industry policy and government intervention in markets. It is a central theme of his maiden speech to parliament in 1998.

As [Treasury Secretary Ken Henry](../2006/economic_policy_at_full_employment.qmd "Treasury Secretary Ken Henry") has pointed out, in a fully employed economy, resources diverted into manufacturing by government policy are resources that are necessarily denied to other sectors with more highly valued uses.  Kevin Rudd is proposing to lower Australia’s standard of living for the sake of his manufacturing fetish.

Industry policy is not the only blast from the past when it comes to the new ALP leadership team.  As [Andrew Norton](http://andrewnorton.info/blog/2006/12/06/whitlamite-nostalgia-in-higher-education/#more-85 "Andrew Norton") notes, when it comes to higher education policy, Rudd and his new deputy are offering little more than Whitlam era nostalgia.
