---
title: "A Roubini Forecast that is Dead on Arrival"
date: "2006-03-29"
categories: ["Economics"]
---

It is not often you can dismiss a forecast as soon as it’s made, but [Nouriel Roubini’s](http://www.rgemonitor.com/blog/roubini/122420 "Nouriel Roubini’s") latest bit of doom-mongering is DOA.  Nouriel suggests that Australia and New Zealand, among others, are set to experience a disruptive currency and financial crisis:

*Runs on currency and liquid local assets may still occur with severe and disruptive effects on currency values, bond markets, equity markets and the housing market.\*
\
In the case of Australia and New Zealand, this prospect can be dismissed out of hand (I wouldn’t necessarily make this claim for some of the emerging market economies Nouriel lumps in with Australia and NZ).  The best evidence against Roubini’s scenario is the experience of both countries in 2001, when the Australian and NZ dollars fell below 0.5000 and 0.4000 respectively.  Not only was there no significant disruption to the domestic economy and financial markets of either country, the boost to competitiveness added to the strength of both economies.  Nouriel’s assumption that a falling currency woud lead to a dumping of local currency-denominated assets by foreign investors didn’t play out then, not least because many foreign investors are significantly hedged against currency risk.  The Australian and NZ dollars are currently falling in part because their debt markets are outperforming the US.  If anything, a cheaper currency makes local asset markets even more attractive to fresh inflows of foreign capital. 

In recent months, New Zealand authorities have not only welcomed a falling currency, they have even been actively trying to scare-off foreign investors - hardly the actions of a government worried about a currency crisis.  The main risk to the NZ economy has been the domestic policy tightening that had seen the NZD trade weighted index to post-float record highs at the end of last year.  An exchange rate driven easing in overall monetary conditions is exactly what NZ needs right now.

Roubini’s forecast in relation to Australia and NZ is also difficult to square with his bearishness on the US dollar. According to Nouriel:

*U.S. policymakers - both at Treasury and even some, but not all, at the Fed - live in this LaLa Land dream that the U.S. current account deficits and fiscal deficits do not matter and that the U.S. external deficit is all caused by a global savings glut or is actually a “capital account surplus” as it allegedly represents the foreigners’ desire to hold U.S. assets.  They - and financial markets and investors - may soon wake up from this unreal dream and face a nightmare where the U.S. looks like Iceland more than they have ever fathomed.*

Roubini would have us believe that both the US dollar and the dollar bloc peripheral currencies are at risk, yet this would imply that the AUD-USD and NZD-USD exchange rates should remain relatively stable.  It is even harder to envisage an Australian and NZ currency or financial crisis, when the most important exchange rate, that with the US, is largely stable.

Nouriel is the one living in LaLa Land.
