---
title: "A Tale of Two Stock Market Forecasts"
date: "2006-01-06"
categories: ["Economics"]
---

*Fortune* profiles the views of Roger Ibbotson in its [investment review for 2006](http://money.cnn.com/magazines/fortune/fortune_archive/2005/12/26/8364640/index.htm "investment review for 2006"):

In May 1974, in the depths of the worst bear market since the 1930s, two young men at a University of Chicago conference made a brash prediction: The Dow Jones industrial average, floundering in the 800s at the time, would hit 9,218 at the end of 1998 and get to 10,000 by November 1999.

You probably have a good idea how things turned out: At the end of 1998, the Dow was at 9,181, just 37 points off the forecast. It hit 10,000 in March 1999, seven months early. Those two young men in Chicago in 1974 had made one of the most spectacular market calls in history.

Curiously, the profile then presents the work of Robert Shiller as a challenge to Ibbotson’s approach.  [Brad DeLong](http://delong.typepad.com/sdj/2005/12/musings_on_asse.html "Brad DeLong") recently reviewed the original forecast that later became the foundation for Shiller’s (2000) [Irrational Exuberance](http://www.amazon.com/exec/obidos/ASIN/0691123357/institutional-20?creative=327641&camp=14573&link_code=as1 "Irrational Exuberance"):\
*\
In 1996 Yale economist Robert Shiller looked around, considered the historical record on the performance of the stock market, and concluded that the American stock market was overvalued. Prices on the broad index of the S&P 500 stood at 29 times the average of the past three decades’ earnings. In the past, whenever price-earnings ratios had been high future long-run stock returns had turned out to be low. On the basis of econometric regression studies carried out by him and by Harvard’s John Campbell, Shiller predicted in 1996 that the S&P 500 would be a bad investment over the next decade. In the decade up to January 2006, he predicted, the real value of the S&P 500 would fall, and even including dividends his estimate of the likely real inflation-adjusted returns to be earned by investors holding the S&P 500 was zero.*

The rest, as they say, is now history.
