---
title: "Alan Reynolds on Income and Wealth"
date: "2006-10-26"
categories: ["Economics"]
---

Alan Reynolds, who often gets a favourable mention on these pages, has a new book out, [Income and Wealth](http://www.amazon.com/gp/product/0313336881/002-2118763-5021629?ie=UTF8&tag=institutional-20&linkCode=xm2&camp=1789&creativeASIN=0313336881 "Income and Wealth"):

> *This volume explains the dynamics of income generation, how it is measured, and how such dramatic disparities in distribution come about. Citing numerous cases of distortion in the popular press, and among academics, policymakers, and pundits, Reynolds exposes many popular myths concerning income and wealth, and presents a balanced perspective on this critical aspect of economics and social policy. The book first defines various characteristics of income, with an emphasis on the gap between the rich and the poor, and reviews several theories to explain the disparities. Subsequent chapters focus on such timely topics as the “vanishing” middle class and the sky-high salaries of CEOs, Hollywood stars, and athletes. The final chapters consider the implications of policies, such as the minimum wage, taxes, immigration, and trade quotas, and expand the discussion to consider international comparisons. Featuring graphs and charts, a glossary of key terms, and a listing of references and resources, Income and Wealth explains the intricate, and often controversial, effects of economic policies on individuals, families, and communities. Moreover, it demonstrates how the numbers can be manipulated by policymakers, pundits, journalists, and academics to promote various agendas, and shows readers how to recognize hyperbole and make better-informed decisions.*
