---
title: "An ‘October Surprise’ on US Q3 GDP?"
date: "2006-10-11"
categories: ["Economics"]
---

[Kevin Hassett](http://www.aei.org/publications/filter.all,pubID.24994/pub_detail.asp "Kevin Hassett") argues that US Q3 GDP may play a role in the upcoming US congressional elections:

> *here is the kicker for Republicans: The data calendar indicates that GDP for the third quarter will be reported by the Bureau of Economic Analysis on Oct. 27, right before Americans enter the voting booths.*

> *You might call it the “October surprise,” but in this case, economists will have seen it coming. Republicans, who have found themselves in the political equivalent of a nightmarish ballgame for some months now, will probably not be surprised that this break has gone against them as well.*

My associates at [Action Economics](http://www.actioneconomics.com "Action Economics") are arguing that any ‘October surprise’ will be up:

> *The market seldom watches U.S. wholesale trade reports, but this morning’s figures have revealed a robust growth trajectory for both sales and inventories that has further reduced prospects for a meaningful slowdown in GDP growth in Q3, as some still fear.  We have not revised our 2.7% GDP growth estimate for Q3, but economists focused on a “1-handle” will have difficulty supporting such low forecasts.*

Meanwhile, [Nouriel Roubini](http://www.rgemonitor.com/blog/roubini "Nouriel Roubini") is arguing that falling oil prices are a negative for the US economic outlook.  [Back when Nouriel was forecasting oil at \$100/barrel](http://www.rgemonitor.com/blog/roubini/135166 "Back when Nouriel was forecasting oil at $100/barrel"), it was a different story:

> *I fully agree that oil prices will remain high for a long time; worse, they are likely to significantly rise towards \$100 in the medium term (and some are already expecting oil at \$90 by year end). Indeed, the factors that \[Robert\] Feldman suggested that may lead to lower oil prices in the future are all unlikely to take place. So, expect higher and higher oil prices and, at some point, another ugly stagflationary outcome.*

Nouriel has only ever been interested in one story: his perverse hankering for macroeconomic ruin for the United States.
