---
title: "Andy Xie’s Commodity Mercantilism"
date: "2006-03-18"
categories: ["Economics"]
---

[Andy Xie](http://www.morganstanley.com/GEFdata/digests/latest-digest.html#anchor3 "Andy Xie"), Morgan Stanley’s house mercantilist, recommends that China resort to central planning to combat higher iron ore prices:

*Without government involvement, China’s industries cannot organize to negotiate down the ore price, because the industry is so new and fragmented.  Limiting import prices is a good choice, I believe.  If the negotiations with the major suppliers do not work out, China’s government should just dictate import prices for the whole year.*

This would be a breach of China’s obligations under the WTO, but that doesn’t seem to bother Xie.  He goes onto argue:

*If China does unilaterally limit import prices, it would not affect supply that much.  The ore producers have huge profit margins and have to sell.  To whom would they sell without selling to China?*

Well everyone apart from China for a start.  The desperation of Chinese steel producers is already evident from this [story](http://today.reuters.co.uk/news/newsArticle.aspx?type=oddlyEnoughNews&storyID=2006-03-17T080421Z_01_SHA6490_RTRIDST_0_OUKOE-UK-CHINA-IRON.XML "story"):

Chinese trading companies are surfing a local version of eBay, Alibaba, to scour the world for an increasingly state-controlled resource—iron ore.

Small steel mills, desperate to find iron ore from Brazil, India, Indonesia or New Zealand, can find it on Alibaba, China’s top online business-to-business Web site, which is backed by Yahoo Inc.

Some of the 237 offers available on Friday included photos of a lump of the ore used to make steel.

“We use the Internet as an extension of our services, to let more people know what we have,” said Sun Gongmin, who handles Internet marketing for Beijing Hero Trade Co. “We only started posting iron ore late last year. Before that we’d been pretty successful with rugs.”

“A lot of people have contacted us already, mostly other trading companies helping their clients source a few thousand tonnes here or there. We’re basically just the middlemen.”…

the Shanghai Huozhiyao Import Export Trade Co. offers Indonesian spot ore at \$67 (38 pounds) a tonne, illustrated by a photo of a tropical shoreline. Brazilian ore is \$69 a tonne.

Spot Indian iron ore in Chinese ports is now valued around \$72 to \$73 a tonne, traders said. Brazilian ore sold on a term basis is now valued around \$67 a tonne, cost and freight.\
