---
title: "Apocalypse Now:  Doomsday Cultism as Generational Solipsism"
date: "2006-10-01"
categories: ["Culture & Society", "Economics"]
---

While this blog likes to make fun of economists who perpetually forecast gloom and doom, at least most economists would generally concede that secular trend is up, whatever the cyclical ups and downs along the way. 

By contrast, [Kurt Andersen](http://www.printthis.clickability.com/pt/cpt?action=cpt&title=Why+Everyone+Has+Apocalypse+Fever+--+New+York+Magazine&expire=&urlID=19603585&fb=Y&url=http%3A%2F%2Fwww.newyorkmetro.com%2Fnews%2Fimperialcity%2F21697%2Findex.html&partnerID=73272 "Kurt Andersen") notes an apocalyptic zeitgeist that seems to unite ‘Christian millenarians, jihadists, Ivy League professors, and baby-boomers:’

> *Not so long ago, it was only right-wingers and old crackpots making decline-and-fall-of-Rome claims about America. But Niall Ferguson is a young superstar Harvard professor, and he argues that we—undisciplined, overstretched, unable to pay our bills or enforce our imperial claims, giving ourselves over to decadent spectacle (NASCAR, pornography), and overwhelmed by immigrants—do indeed look very ancient Roman. He suggests, in fact, that Gibbon’s definitive vision—the “most awful scene in the history of mankind”—is about to be topped.*

Andersen suggests that this preoccupation with apocalyptic scenarios may partly come down to baby-boomer pathology:

> *It’s also a function of the baby-boomers’ becoming elderly. For half a century, they have dominated the culture, and now, as they enter the glide path to death, I think their generational solipsism unconsciously extrapolates approaching personal doom: When I go, everything goes with me, my end will be the end.*

It should be said that economists are not entirely off the hook in terms of being excessively pessimistic, as this paper by [Robert Fogel](http://www.nber.org/papers/w11125 "Robert Fogel") notes:

> At the close of World War II, there were wide-ranging debates about the future of economic developments. Historical experience has since shown that these forecasts were uniformly too pessimistic. Expectations for the American economy focused on the likelihood of secular stagnation; this topic continued to be debated throughout the post-World War II expansion. Concerns raised during the late 1960s and early 1970s about rapid population growth smothering the potential for economic growth in less developed countries were contradicted when during the mid- and late-1970s, fertility rates in third world countries began to decline very rapidly. Predictions that food production would not be able to keep up with population growth have also been proven wrong, as between 1961 and 2000 calories per capita worldwide have increased by 24 percent, despite the doubling of the global population. The extraordinary economic growth in Southeast and East Asia had also been unforeseen by economists…
>
> One of the points \[Kuznets\] made was that if you wanted to find accurate forecasts of the past, don’t look at what the economists said. The economists in 1850 wrote that the progress of the last decade had been so great that it could not possibly continue. And economists at the end of the nineteenth century wrote that the progress of the last half century has been so great that it could not possibly continue during the twentieth century. He said you would come closest to an accurate forecast if you read the writers of science fiction.
