---
title: "Are Australian Economists Really Cowed by Political Pressure?"
date: "2006-09-18"
categories: ["Economics", "Financial Markets"]
---

[Ross Gittins](http://www.smh.com.au/news/business/exposing-howards-big-lie/2006/09/17/1158431585299.html?page=fullpage#contentSwap2 "Ross Gittins") launches another one of his regular martyrdom operations:

> *except for people in privileged positions like mine, economists do have to be brave to stand up to the Howard Government with its behind-the-scenes bullying.*

This is all a little bit precious, not least because it was a practice for which the former Labor Treasurer and Prime Minister, Paul Keating, was equally notorious, which is to say that none of this is anything new (and therefore hardly newsworthy).  While there may be some economists at certain investment banks touting for government business who have to worry about such political pressure, that is a conflict of interest within the bank, not a problem with political pressure as such.  If CEOs or their economists cave in to political pressure, it says more about them than it does about the government.

There was one occasion when I was working for Standard & Poor’s when I managed to get a phone call from the Prime Minister’s office, the Treasurer’s office and the office of the leader of the Opposition, all on the same day.  Far from feeling any political pressure, I took considerable comfort from the fact that both sides of politics had been more or less equally annoyed.  What was undoubtedly intended as political pressure was if anything useful feedback!
