---
title: "Australian Foreign Direct Investment Abroad"
date: "2006-03-27"
categories: ["Economics"]
---

We have previously noted the under-reported business investment boom in Australia, which has taken the investment share of GDP to post-war record highs and which largely explains the widening in Australia’s current account deficit.  An even lesser known phenomenon is the fact that Australia is increasingly a net exporter of direct investment capital.  Australia is one the biggest suppliers of foreign direct investment capital in the US, a phenomenon noted in this LA Times story from 18 March, reproduced in today’s [SMH](http://www.smh.com.au/news/business/us-slowly-noticing-the-big-inflow-of-funds-from-down-under/2006/03/26/1143330929703.html "SMH"):

Last year Australian companies sank \$US6.1 billion into US real estate, up from \$US3.5 billion the previous year…

Real estate isn’t the only area benefiting from Australian investors, who have been enjoying a relatively strong currency and 14 years of growth. Macquarie has also sunk money into major US infrastructure projects, including toll roads in San Diego, Chicago and Washington.

This week, Australia’s Woodside Petroleum unveiled a plan to build a liquefied natural gas terminal off the California coast and BHP Billiton announced similar plans for a floating LNG facility farther north.

Ben Thornley, a New York investment specialist with the Australian Government, said US investment in Australia also was increasing, spurred by the recent completion of a bilateral trade pact.

But he said the US still had the stronger allure, with at least “100 billion Aussie dollars” seeking a home in the US at any given time.

“There’s more money flying out of Australia than going the other direction,” he said.\
Some US investors are bypassing Wall Street and heading straight to Australia.

In 2004 Tishman Speyer, the private New York developer, raised \$400 million through a property fund it listed on the Australian Stock Exchange.

Rob Speyer said it was much easier to raise capital in Australia than in the US.\
