---
title: "Bernanke, Warsh, Inflation Targeting and the Fed"
date: "2006-02-22"
categories: ["Economics"]
---

[Brian Wesbury](http://online.wsj.com/article/SB114057637795579762.html?mod=opinion_main_commentaries "Brian Wesbury") on the internal politics of the Fed:

Issues with the press and internal Fed battles are much more complicated, as well as interrelated. For example, last week’s public attacks on Kevin Warsh—a key White House staffer and one of President Bush’s recent nominees for Federal Reserve Board governor—appear to be part of this nexus.

These attacks violated an unwritten rule that former Fed members do not publicly disagree with the Fed or its chairman. They were orchestrated by a retired Fed governor who claimed that Mr. Warsh was not qualified to be on the Fed as he was not trained by academics to be an economist. Instead, he is a lawyer with extensive Wall Street experience and knowledge of the capital markets. Given that Mr. Bernanke worked with him in the White House, and likely had veto power, we can assume he supported the nominee. So someone else inside the Fed may have encouraged the attacks in order to send a warning shot about any moves toward inflation targeting that might be made by the new chairman and his newest colleagues. Like any D.C. institution, the Fed abhors change and accountability, and inflation targeting would force both.
