---
title: "Bin Laden the Blogger"
date: "2006-05-03"
categories: ["Foreign Affairs & Defence"]
---

Brendan O’Neill makes the case for [bin Laden as blogger](http://www.reason.com/0605/co.bo.the.shtml "bin Laden as blogger"):

The latest statement reveals the extent to which bin Laden borrows from Western discussions of the Middle East. He seems less a man with a clear religious or political agenda than a parasite feeding off the fear and loathing of his enemies…

Bin Laden’s reliance on Western theorizing about the reasons for Al Qaeda’s existence and actions is clear in Messages to the World. Reading his statements from 1994 to 2004, one can see clearly that he transforms himself from a religious crank obsessed by Saudi Arabia (circa 1994) to a self-described warrior for Palestine (around 2001–02) to a full-fledged Bush basher (from 2004 onward). His campaign is shaped less by his own program of ideas or aims than it is by the West’s interpretation of that campaign.\
\
O’Neill is wrong to suggest that the echo chamber quality of bin Laden’s statements is symptomatic of a lack of purpose.  The fact that bin Laden is cynical and opportunistic enough to position himself within Western intra-mural debates shows that he studies his enemies’ internal divisions and seeks to exploit them…even to the point of having [a position on Kyoto](http://observer.guardian.co.uk/worldview/story/0,11581,845725,00.html "a position on Kyoto").
