---
title: "BlogAds Political Blog Reader Demographics Survey"
date: "2006-03-01"
categories: ["Misc"]
---

[BlogAds](http://www.blogads.com "BlogAds") is conducting a [survey](http://www.surveymonkey.com/s.asp?u=84511800967 "survey") of political blog readers.  BlogAds will break-out the results obtained from this blog and pass them on to me (make sure you mention Institutional Economics in question 23).  If the sample is large enough, I will post the results, which will give you a better picture of your fellow Institutional Economics readers.

You might wonder why this blog is being included in the survey, even though it is not mainly concerned with politics.  This is due to the fact that I classified the blog as ‘libertarian’ when I signed-up for BlogAds.  While my own politics should be fairly obvious to regular readers, it has never been my intention to run an overtly political blog.  The most successful blogs in terms of traffic are strongly partisan, but these sites serve mainly to confirm rather than challenge readers’ views.  I have always aimed to appeal to a more diverse readership and I’m hoping this is reflected in the survey results.
