---
title: "Bono as International Tax Arbitrageur"
date: "2006-08-09"
categories: ["Economics"]
---

U2’s Bono is not averse to a little [international tax arbitrage](http://www.telegraph.co.uk/news/main.jhtml?xml=/news/2006/08/08/nbono08.xml "international tax arbitrage"):

> The rock band U2 came under criticism yesterday after reports that it has moved a portion of its multi-million-pound business empire out of Ireland for tax reasons.
>
> The band, fronted by Bono, the anti-poverty campaigner, has reportedly transferred some of its publishing company to Holland.
>
> Based in Dublin, U2 have long benefited from the artists’ tax exemption introduced by Charles Haughey, the late prime minister. It is reported that the band’s move has been made in response to a £170,000 cap on the tax-free incomes introduced in the last Irish budget.

Bono is also apparently a founder and partner in a USD 1.9 billion private equity fund that has [just taken a stake](http://www.forbes.com/home/digitalentertainment/2006/08/07/forbes-elevation-bono_cx_lh_0808forbes.html "just taken a stake") in Forbes media.  Perhaps he is just following [Lang Hancock’s](http://en.wikipedia.org/wiki/Lang_Hancock "Lang Hancock’s") dictum that the best way to help the poor is not to become one of them.
