---
title: "Bringing Currency Competition to the Euro Zone"
date: "2006-02-28"
categories: ["Economics"]
---

John Gillingham, speaking at an [Open Europe seminar](http://www.openeurope.org.uk/media-centre/article.aspx?newsid=1163 "Open Europe seminar") on his book, [A Design for a New Europe](http://www.amazon.com/exec/obidos/redirect?tag=institutional-20&camp=14573&creative=327641&adid=05NSWASNB3NF977EC3NP&link_code=as1&path=tg/stores/offering/list/-/0521686644/all/ASIN/0521686644 "A Design for a New Europe"):

I propose in my book an idea that has considerable circulation within the City and which was at one point on the Treasury agenda in Britain. That is changing the euro, not destroying it, but changing its operating mechanism from being the sole currency in a single economic area to a parallel currency that finds its market value in competition to reissued national currencies.

It does two things: first of all I believe that it is technically credible and sensible because it allows the currencies to adjust against one another on a daily basis. It eliminates the life of the major shock that the euro could still face once it becomes apparent that a currency that was designed for a political goal, that is to be a step towards a closer economic and political union, has been organised for a country that will never exist…

I think that the currencies of the euroland should be reissued and any attempt to regulate the values of the currencies by an overall single monetary and fiscal straight jacket should be dropped. The values of the currencies will depend on the strength of the individual national economies. The euro is a good “numéraire” because the EU can’t run a deficit. So it can be a depositary bridge and has a real value to discipline governments.

Hayek would approve.
