---
title: "‘Bubble Man’ Revisited"
date: "2006-08-14"
categories: ["Economics", "Financial Markets"]
---

Late last year, I had occasion to [review](http://www.institutional-economics.com/index.php/section/comments/bubble_man_alan_greenspan_the_missing_7_trillion_dollars_by_peter_hartcher/ "review") Peter Hartcher’s [Bubble Man](http://www.amazon.com/gp/product/0393062252/ref=ase_institutional-20/002-5247213-4341622?s=books&v=glance&n=283155&tagActionCode=institutional-20 "Bubble Man").  For some reason, the book is only now receiving critical scrutiny in the US.  [Daniel Drezner reviews the book in the WaPo](http://www.washingtonpost.com/wp-dyn/content/article/2006/08/10/AR2006081001350.html "Daniel Drezner reviews the book in the WaPo"), although notes on his [blog](http://www.danieldrezner.com/archives/002849.html "blog") that:

> *It was difficult, in the space allotted, to list all the reasons I thought this book sucked eggs.*

Dan also links to Steven Mufson’s review in [The Washington Monthly](http://www.washingtonmonthly.com/features/2006/0606.mufson.html "The Washington Monthly"):

> *By overemphasizing the damage done in the market and economic downturn in 2000-2001, Hartcher skews the answer to the question of whether Greenspan or any other Fed chairman ought to use the powers of his office to protect investors from bubbles given the Fed’s other, arguably bigger, responsibilities. The hot economy of the late 1990s had real benefits for many workers, especially those lower down on the income scale who didn’t have any stock portfolios. And while a disproportionate chunk of economic gains flowed to America’s wealthy, some job gains among middle- and lower-class Americans were real and a surprising number survived the recession.*
