---
title: "Capital Repression in China"
date: "2006-03-23"
categories: ["Economics"]
---

[James Dorn](http://online.wsj.com/article/SB114306802396905636.html?mod=opinion_main_europe_asia "James Dorn") on the origins of China’s national saving glut:

Of the world’s top 10 biggest trading nations, only China has extensive capital controls. Sure, current-account transactions, or trading in goods and services, are liberalized. But Chinese citizens are barred from investing overseas, interest rates are heavily regulated and domestic stock markets are limited mostly to state-owned enterprises.

China pays a high price for such controls, which distort investment decisions and misallocate capital. Ordinary Chinese suffer too. Denied the right to seek higher returns overseas for their hard-earned savings, they have no choice but to take their chances with poorly regulated domestic investments. And that, in turn, helps explain why China’s savings are so high—and why the much-discussed U.S.-China trade deficit remains intact.
