---
title: "Capitalist Acts Between Consenting Adults"
date: "2006-05-25"
categories: ["Economics"]
---

A Wall Street lawyer tries to [auction](http://www.nypost.com/business/68931.htm "auction") his social security entitlements on Ebay:

Wojcik says he’s not breaking any laws or securities regulations.

“It’s not a security; it’s a person-to-person contract at a negotiated price, provided it’s allowed,” he said.

Wojcik, also a securities lawyer, believes he’s avoiding any Securities and Exchange Commission violations by including boilerplate clauses warning of “risk factors” in his deal, such as that of being prohibited by the government from ever transferring his future checks, or his death.

Ebay took a different view, yanking the auction.  This is unfortunate, since it might have yielded some insight into the expected future value of social security benefits.  Given that the social security system is expected to be insolvent at reasonable horizons based on current policy settings, one suspects that these benefits would be heavily discounted.

Meanwhile, the [NYT](http://www.nytimes.com/2006/02/28/health/28conv.html?ex=1148616000&en=5c0e25f5fb1eb69a&ei=5070 "NYT") discovers that Harvard women produce more valuable eggs than Colombia women:

Q. At Columbia University, there are ads in the student newspaper offering to pay tall blondes with high SAT’s \$8,000 to \$20,000 for eggs to be used by infertile couples. Is this a good price?

A. Hmm. I think the price for Harvard eggs is higher, around \$25,000. There have been ads offering even \$50,000 and \$100,000 for “exceptional eggs” though no one’s ever come forward to say they’ve gotten that much.

(via [MR](http://www.marginalrevolution.com/marginalrevolution/2006/05/futures_markets.html "MR") and [Ben Muse](http://benmuse.typepad.com/ben_muse/2006/05/sorry_columbia.html "Ben Muse") respectively)
