---
title: "Capitulation of the Cyclical US Dollar Bears: Doomsday Postponed (Again)"
date: "2006-07-22"
categories: ["Economics", "Financial Markets"]
---

Even the [cyclical US dollar bears](http://www.morganstanley.com/GEFdata/digests/latest-digest.html#anchor3 "cyclical US dollar bears") are capitulating:

> We have argued for more than two years now that the dollar is structurally sound, and the market’s fixation on using the dollar as the key tool of C/A adjustment is a fundamentally flawed notion, reflecting a lack of understanding of the effects of globalization.  To us, outsized global imbalances are a logical consequence of globalization of the goods and the assets markets.  We won’t repeat the details of our thesis on the dollar, but only stress that our call this year for the dollar to correct has been based purely on cyclical considerations.  We are not sympathetic to the popular notion that the dollar ‘must’ correct sharply or crash, and that 2005 was a bear market rally in a secular dollar decline.  This is why the changing cyclical outlook of the US and the global economies has such a major impact on the trajectory of the dollar…
>
> As US inflation trends higher and global interest rates continue to rise, the dollar will be supported.  The nominal short-term cash premium of the USD has reached 2.7%, and is still rising.  We have long warned about the impact of the upside surprise in US inflation on the dollar and how it could alter our currency forecasts.  We now believe that the cyclical dollar correction we had expected to take place in 2H this year may be further postponed to 4Q this year.

A recent [IMF Working Paper](http://www.imf.org/external/pubs/cat/longres.cfm?sk=19382 "IMF Working Paper") sheds light on the structural underpinnings of the USD:

> *the presence of negative dollar risk premiums (i.e. expectations of a dollar depreciation net of interest rate effects) amid record capital inflows could suggest that investors may favor U.S. assets for structural reasons. One possible explanation could be that the Asian crisis created a large pool of savings searching for relatively riskless investment opportunities, which were provided by deep, liquid, and innovative U.S. financial markets with robust investor protection. Moreover, the continued attractiveness of U.S. financial markets to European investors suggests that they offer a large array of assets, with different risk/return characteristics, that facilitate the structuring of diversified investment portfolios. Looking forward, this suggests that the allocative efficiency of U.S. financial markets could mitigate risks of a disorderly unwinding of global current account imbalances.*
