---
title: "Costello and the Deakinite Left"
date: "2006-07-13"
categories: ["Politics"]
---

Peter Costello is arguing for a ‘smooth’ transition, but this presupposes that there is a case for a leadership change in the first place.  If such a case existed, he would have no difficulty mounting a successful challenge.  As [Greg Sheridan](http://www.theaustralian.news.com.au/story/0,20867,19769514-601,00.html "Greg Sheridan") notes:

> *The extraordinary thing about the Costello challenge is that there is absolutely no rationale for it beyond Costello’s petulant self-regard. There is no policy or political imperative for Costello to go forward. This challenge is about Costello, not about the Australian people. As Treasurer, Costello has been a lukewarm reformer at best. For years Costello was the last socialist politician defending Australia’s absurd, incentive-sapping top marginal tax rate. After a decade he managed to reduce it by 2 per cent.*

Peter Costello entered parliament amid the purge of the Victorian Liberal Party’s Deakinite left in the late 1980s.  It is not a little ironic that Costello now appeals mainly to the left of the party room, who are the least troubled by his lack of policy substance.
