---
title: "Debunking Nouriel Roubini on UK, Australian and NZ Housing"
date: "2006-10-07"
categories: ["Economics"]
---

[Nouriel Roubini](http://www.rgemonitor.com/blog/roubini/150552 "Nouriel Roubini") attempts to argue that the benign experience of housing booms and subsequent downturns in rest of the Anglo-American world fails to invalidate his US recession calls based on a downturn in US housing.

First, Nouriel tries to argue that central banks in the UK, Australia and NZ have been more pro-active in targeting asset prices, in this case house prices, than the Fed.  This is mere assertion on Nouriel’s part.  The BoE, RBA and RBNZ have certainly referenced housing as one of many factors behind their recent tightening cycles, but all three central banks view their conduct of monetary policy as being squarely within the standard Taylor rule framework and are just as cautious as the Fed about the notion of central banks targeting asset prices.  Indeed, if these central banks have been targeting house prices, they have done a lousy job of it.  House price inflation in the rest of the Anglo-American world has if anything been even more pronounced than in the US and remains strong in NZ (this is ironic, because the RBNZ has actually given the strongest emphasis to housing in its official rhetoric).  I highly recommend [Adam Posen’s](http://www.iie.com/publications/wp/wp06-1.pdf#search=%22%22adam%20posen%22%20asset%20prices%22 "Adam Posen’s") paper on the subject for a thorough debunking of Nouriel’s argument that monetary policy should target asset prices.  [Ben Bernanke](http://www.federalreserve.gov/boarddocs/speeches/2003/20031002/default.htm "Ben Bernanke") also gave a speech on the subject before becoming Fed Chairman, in which he demonstrates how dangerous and misguided it would be for central banks to attempt to manage asset prices.  To argue that the Fed is completely out of step with the rest of the world in its conduct of monetary policy simply beggars belief.  If anything, the US under Volcker, Greenspan and Bernanke has set the standard that was subsequently emulated by other central banks by the adoption of formal inflation targets that sought to match the Fed’s record on inflation.

Second, Roubini argues that ‘What prevented a hard landing of the economy in the UK, Australia and New Zealand has been – among other factors – the fact that all three countries have experienced sharp positive terms of trade shocks that have boosted overall GDP at the time when the housing market was going into a sharp slump following the bursting of their housing bubbles.’  This statement somewhat contradicts his first argument that the soft-landings in these countries were a function of monetary policy.  But it also ignores the fact that these terms of trade booms are not nearly as important to measured GDP growth as many people assume.  The sectoral composition of the other Anglo-American economies is little different from that of the US, being overwhelming in services.  Strength in commodity prices should not be confused with strength in commodity output, which is what real GDP measures.  As we have noted previously, mining output in Australia fell 8.3% in the year to June.  Net exports have made a flat or negative contribution to Australian GDP growth in every quarter since Q3 2001.  As John Edwards likes to point out, Australian export volumes have even underperformed US export volumes.  The increased national purchasing power due to a rising terms of trade has resulted in the substitution of imports for domestic production, which actually subtract from GDP, so terms of trade booms have mixed implications for measured GDP growth.  Perhaps the best measure of the lack of importance of commodities for the overall Australian economy is the simple fact that some of the strongest GDP growth rates in the current Australian expansion were achieved during the 1998-2001 global commodity price slump.

Even Nouriel’s prolific colleague, [Felix Salmon](http://www.rgemonitor.com/blog/economonitor/150561 "Felix Salmon"), is unconvinced by Nouriel’s arguments:

> *after looking at all the housing bubbles \[sic\] all over the world in the past decade, it’s hard to find a single one that has yet resulted in a hard landing. Nouriel seems to be saying that Australia, New Zealand, and the UK are all somehow special cases, but in fact, to me, they actually seem closer to the norm. Could the United States have a hard landing? Of course it could. But that would make it the exception, rather than the rule.*
