---
title: "Discretionary Fiscal Policy: Not Dead Yet"
date: "2006-05-16"
categories: ["Economics"]
---

Treasury Secretary Ken Henry addresses some fiscal policy misconceptions in the traditional [post-Budget address to ABE](http://www.treasury.gov.au/contentitem.asp?NavId=008&ContentID=1112 "post-Budget address to ABE"):

Clearly fiscal policy is relatively tight – especially by international standards. Should it be tighter? Some think it should, because there is the potential for the terms-of-trade to fall sharply and for income growth to slow. As I have noted, we have already taken out some insurance for this eventuality through our projection assumptions. And while this insurance does not fully unwind the increase in commodity prices, it is substantial, with nominal GDP projected to grow at a rate a full percentage point below its longer term average.

But there are other metrics for ascertaining the suitability or otherwise of the stance of fiscal policy, and these relate to the behaviour of the real economy. Over the recent period, the real economy has been growing at around trend, with output close to full capacity. Furthermore, we have had no significant increase in inflation in this period – no rapid acceleration in prices – with little change in monetary policy settings. It is far from obvious that an alternative fiscal policy approach would have generated superior macroeconomic outcomes.

Some of the criticism of the fiscal strategy appears based on a couple of misconceptions. Let me quickly address those. Having a medium-term fiscal framework does not imply there will only be fiscal surpluses in the future even if the recent increase in commodity prices turns out to be persistent. Importantly, it also doesn’t imply that there can never be deficits. And it does not presage the death of discretionary fiscal policy, as has been suggested by some commentators.\
\
There is an interesting discussion of the long-run implications of recent gains in Australia’s terms of trade.\
[\
Liberal MHR Malcolm Turnbull](http://www.news.com.au/story/0,10117,19147372-421,00.html "<br />
Liberal MHR Malcolm Turnbull") also gives his take on the Budget:

*the budget did not target childless, 58-year-old lesbian poets.*
