---
title: "Dollar Crashes, Comets and Yield Curve Inversions"
date: "2006-01-09"
categories: ["Economics"]
---

[Alan Reynolds](http://www.cato.org/pub_display.php?pub_id=5361 "Alan Reynolds") reviews forecasts for 2006, before giving us something real to worry about:

Washington Post columnist Steven Pearlstein just wrote about the “remarkably rosy scenario” of the “economic pundocracy” (though he’s a member). On the same day, Robert Samuelson brushed off all the “sunny predictions” and offered a variation of Pearlstein’s shopping list of things that might go wrong. The dollar might crash, for example, which they almost certainly said last year. Or we might be hit by a comet…

Because inflation is going to be drifting down to 2.4 percent or less for the foreseeable future, there is no “conundrum” in explaining why 10-year bond yields remain low. And there is no plausible rationale for pushing the fed funds rate higher while inflation is heading lower. If the Fed does that, it will be a mistake. Maybe a big mistake.

The federal funds rate was deliberately pushed above the 10-year bond yield in 1969, 1973-74, 1979-81, 1989 and 2000. By no coincidence, the economy was in recession in 1970, 1974-75, 1980-82, 1990 and 2001.
