---
title: "Doomsday Cultists Suffering for their Beliefs"
date: "2006-11-02"
categories: ["Economics"]
---

Regular readers will know that we are not averse to indulging in a bit of Schadenfreude over the foreign exchange losses of those who ‘robotically trash the US dollar’ (as Singapore fund manager Dr V put it when he first wrote about macroeconomic anti-Americanism as a kind of doomsday cult).

Schadenfreude is rather more warranted in the case of Bob Rubin, who as US Treasury Secretary presided over an incredibly expensive episode of regulatory capture of international economic policy by institutional investors.  According to [David Leonhardt](http://www.nytimes.com/2006/11/01/business/01leonhardt.html?ex=1320037200&en=036ab20bb5bb104a&ei=5088&partner=rssnyt&emc=rss "David Leonhardt"), the one-time architect of the ‘strong dollar policy’ lost USD one million on his own account taking on non-USD exposures.  Still, the market is a great teacher and Rubin now seems to take a more agnostic view:

> *“I think I was right, probabilistically,” he said recently, sitting in his Citigroup office overlooking Park Avenue. “But I don’t know. I really don’t. I don’t think anyone does. It’s also possible that none of this could happen. It’s possible that for reasons none of us can see that this will work itself out in a very copacetic way.”*
