---
title: "Easterly vs Sachs"
date: "2006-11-15"
categories: ["Economics"]
---

Bill Easterly, author of [The White Man’s Burden](http://www.amazon.com/dp/1594200378?tag=institutional-20&camp=0&creative=0&linkCode=as1&creativeASIN=1594200378&adid=1ZW73AQ0KJV562Z85B5E& "The White Man’s Burden"), [responds](http://online.wsj.com/article/SB116355956112023480.html?mod=opinion_main_commentaries "responds") to Jeffrey Sachs’ anti-Hayek outburst in Scientific American:

> Mr. Sachs (in his book “The End of Poverty”) is peddling his own administrative central plan—449 steps in all—to end world poverty. In his plan, the U.N. secretary-general (to whom he is an adviser) would supervise and coordinate thousands of international civil servants and technocratic experts to solve the problems of every poor village and city slum everywhere. Mr. Sachs is not in favor of central planning as an economic system, but he offers it as a solution, anyway, to the multifold problems of the world’s poorest people. If you want the best analysis of why the approach of Mr. Sachs and his confreres in Hollywood and the U.N. will fail to end world poverty this time (as similar efforts failed over the past six decades), you can find it in Hayek.
>
> Third, Mr. Sachs’s attempt to make the case for his best possible society, the Scandinavian welfare state, is a little shaky. If this is what passes for the scientific method in Scientific American, American science is in even worse shape than we thought. Economics is usually about the incentives that cause people to solve their own or other peoples’ problems, but to Mr. Sachs, problem-solving seems always to be about raising more public money for whatever cause he is concerned with at the moment.
