---
title: "Economic Consequences of War in the Middle East"
date: "2006-07-18"
categories: ["Economics", "Financial Markets"]
---

[Kevin Hassett](http://www.aei.org/publications/filter.all,pubID.24663/pub_detail.asp "Kevin Hassett") extrapolates from historical experience:

> A 37 percent move up from \$78, pushing even past \$100, is certainly possible given past oil-price responses to war in the Middle East. During the 1948 Arab-Israeli War, oil prices increased by exactly that percentage during the course of the fighting…
>
> Given that there are many signs the U.S. economy has already been slowing, such a surge in oil prices might well be enough to push the economy into a recession.
>
> There is significant historical precedent. The 1956 war in Egypt shut the Suez Canal to oil tankers. Oil producers cut output by 1.7 million barrels a day, roughly a 10 percent decrease in world oil production. Prices surged, and by August 1957, we were formally in a recession.
>
> The outbreak of the Iran-Iraq war in 1980 caused world oil production to drop 7.2 percent. By July 1981, there was a recession. Iraq invaded Kuwait in 1990, and the same pattern held.
>
> With that likelihood, expect the normal “flight-to-safety” assets to rally if full-scale war erupts. Gold prices would head way up, interest rates on government securities way down. During the 1982 Lebanon War, the 10-year Treasury bill rate dropped 12 percent in the 11 weeks from just before war began in early June to Aug. 24, 1982, the day after the PLO agreed to withdraw its forces.
>
> The stock market would also take a big hit, history shows. During the course of the Suez Crisis in 1956, the Standard & Poor’s 500 Index dropped 5 percent.
