---
title: "Ed Prescott at UNSW"
date: "2006-05-03"
categories: ["Economics"]
---

2004 Nobel Prize in Economic Science winner Ed Prescott will be giving a [lecture at UNSW](http://www2.banking.unsw.edu.au/nps/servlet/portalservice?GI_ID=System.LoggedOutInheritableArea&maxWnd=_News_ProfEdwardPrescottSeminar "lecture at UNSW") on 1 June, titled ‘Unmeasured Investment and the 1990s US Boom.’  Here is the abstract:

*During the 1990s, market hours in the United States rose dramatically. The rise in hours occurred as gross domestic product (GDP) per hour was declining relative to its historical trend, an occurrence that makes this boom unique, at least for the postwar U.S. economy. We find that expensed plus sweat investment was large during this period and critical for understanding the movements in hours and productivity. Expensed investments are expenditures that increase future profits but, by national accounting rules, are treated as operating expenses rather than capital expenditures. Sweat investments are uncompensated hours in a business made with the expectation of realizing capital gains when the business goes public or is sold. Incorporating expensed and sweat equity into an otherwise standard business cycle model, we find that there was rapid technological progress during the 1990s, causing a boom in market hours and actual productivity.*

Follow the link for some related papers.
