---
title: "FDI Protectionism: Australia Gets Some of its Own Back"
date: "2006-06-05"
categories: ["Economics"]
---

One of the great success stories of the Australian economy that we have sought to highlight on this blog has been the rise of Australia as a net exporter of direct investment capital, a reflection of the globalisation of Australian business.  As [this story](http://www.theaustralian.news.com.au/story/0,20867,19364446-643,00.html "this story") notes, Australia is the eighth largest investor in the US, with leading Australian companies like Macquarie Bank, BHP Billiton, Santos, Woodside, Westfield, Rinker and Visy owning more than \$US130 billion in assets and employing more than 80,000 people in the US.

Given Australia’s sorry record of FDI protectionism on spurious national interest grounds, often at the behest of local producer interests, there is a certain justice in Australian firms now being on the receiving end of similar protectionist sentiment in the US.  As the story cited above notes:

AUSTRALIA might have a free trade agreement with the US but it hasn’t stopped this country being caught in an outbreak of xenophobia towards foreign investors, particularly Macquarie Bank…

The multi-billion-dollar leases for toll roads in the US that Macquarie is acquiring with its Spanish partner Cintra appears to be falling into the definition of “critical infrastructure” that some congressional members want foreigners banned from buying.

The notion that Australian ownership of US infrastructure poses a threat to the US is absurd, but no more so than similar arguments routinely run in the Australian context.  The Australian government proposed to limit foreign ownership in the Snowy Hydro privatisation before the whole thing collapsed amid an outbreak of nationalism and parochialism that would shame even Pauline Hanson.  Australia runs one of the most restrictive FDI regimes in the OECD and the US-Australian FTA left in place sweeping ministerial discretion over foreign investment in Australia. 

FDI protectionism is a silly game to play, especially on the part of firms with global business interests and economies dependent on foreign investment to finance their current account deficits.
