---
title: "Flying on One Engine:  The Bloomberg Book of Master Market Economists"
date: "2006-01-27"
categories: ["Economics"]
---

[Flying on One Engine: The Bloomberg Book of Master Market Economists](http://www.amazon.com/gp/product/1576601765/ref=ase_institutional-20/102-2458248-6112949?s=books&v=glance&n=283155&tagActionCode=institutional-20 "Flying on One Engine: The Bloomberg Book of Master Market Economists") contains 14 essays by leading market economists on the US and world economies.  Economists working in financial markets produce some of the best analysis of contemporary macroeconomic developments, yet much of this research is only ever seen by wholesale clients.  While many economists enjoy high media profiles, the relentless dumbing-down of reporting on the economy and financial markets makes it difficult for some of the better economists’ voices to be heard.  Anyone looking for more considered analysis of economic and market developments that goes beyond the one line grabs in the mainstream media will find this book of interest.

The essays represent a range of views on the US and world economies, but remain largely ‘bubble’ and doomsday cult free.  David Malpass is typically upbeat in his essay ‘America’s Optimistic Future,’ demolishing the myth that US households don’t save and dismissing the notion of a ‘bubble’ in US housing. 

Thomas Mayer is suitably downbeat in his essay ‘Europe’s Political and Economic Future,’ concluding that ‘whether the readers of these lines will live to see Europe’s economic revival is an entirely different matter.’

John Ryding’s essay ‘Monetary Policy, Wicksell and Gold’ argues for a Wicksellian interpretation of US monetary policy at the expense of what he sees as the dominant Phillips curve paradigm.  Ryding fails to appreciate the extent to which US monetary policy is already firmly neo-Wicksellian and that the Phillips curve trade-off, however unreliable, is not necessarily incompatible with a neo-Wicksellian interpretation of monetary policy.

Ryding is one of several authors who point to the gold price as being indicative of the stance of US monetary policy.  The problem with this view is that gold is correlated with commodity prices in general, so it is far from obvious that it has any special properties as an indicator relative to other commodities.  David Rosenberg’s essay highlights the very restrained pass through of the recent bull market in commodity prices to producer and consumer prices, suggesting that commodity prices (including gold) are now a much less reliable guide to inflation pressures than they have been in the past.

Michael Rosenberg writes on US dollar cycles, arguing for a 20 to 30 decline in the US dollar’s value over the next two to three years.  However, Rosenberg is also sympathetic to the possibility that there has been an increase in the ‘sustainable’ current account deficit for the US, implying greatly reduced downside for the US dollar to restore external ‘balance.’  Indeed, there are those (like myself) who argue that the US current account deficit should if anything be wider, and that the recent deterioration in the current account balances of the Anglo-American economies contains a significant structural component that is here to stay.

The book’s only major flaw is the gushing and cringe-inducing introductions that editor Thomas Keene inserts at the beginning of each essay.  The biographies of the contributors speak for themselves and hardly require any embellishment from Keene.
