---
title: "Forecast Evaluation"
date: "2006-12-13"
categories: ["Economics"]
---

[A few reasons](http://www.econbrowser.com/archives/2006/12/2006_and_the_ec.html "A few reasons") why you should be reading James Hamilton rather than [Dr Strangelove](http://www.rgemonitor.com/blog/roubini "Dr Strangelove").

Meanwhile, [Alex Robson](http://www.theaustralian.news.com.au/story/0,20867,20910105-7583,00.html "Alex Robson") reviews the long-range forecasting performance of some local economists:

> Just after John Howard came to office in 1996, several academic economists - including many professors at our best universities - distributed a petition in response to the new PM’s proposal to reduce government spending and cut the size of the commonwealth public service.
>
> The professors claimed that the cuts were economically irresponsible and socially damaging, and would “inevitably cause job losses” due to “downward multiplier effects” that would flow from the public sector to the private sector. They also claimed that “the consequent reduction in jobs and incomes would result in lower tax revenues”. They said there would be “a strong possibility of precipitating a substantial economic recession”.

The rest, as they say, is [history](http://www.lowyinstitute.org/Publication.asp?pid=506 "history"):

> *After fifteen years of uninterrupted growth, Australia’s quiet economic boom shows no signs of ending. The longest expansion in Australian history, it has seen wealth more than double, average income increase by half as much again, and unemployment tumble to a rate last experienced more than quarter of a century ago.*
