---
title: "Friedman on Greenspan"
date: "2006-01-31"
categories: ["Economics"]
---

[Milton Friedman](http://online.wsj.com/article/SB113867954176960734.html?mod=opinion_main_commentaries "Milton Friedman") on Alan Greenspan:

Over the course of a long friendship, Alan Greenspan and I have generally found ourselves in accord on monetary theory and policy, with one major exception. I have long favored the use of strict rules to control the amount of money created. Alan says I am wrong and that discretion is preferable, indeed essential. Now that his 18-year stint as chairman of the Fed is finished, I must confess that his performance has persuaded me that he is right—in his own case…

It has long been an open question whether central banks have the technical ability to maintain stable prices. Their repeated failures to do so suggested that they did not—whence, in part, my preference for rigid rules. Alan Greenspan’s great achievement is to have demonstrated that it is possible to maintain stable prices. He has set a standard. Other central banks around the world, whether independently or by following his example, are following suit. The timeworn excuses for central bank failure to stem inflation will no longer do. They will have to put up or shut up.
