---
title: "Friends the ‘Austrian School’ Could Do Without"
date: "2006-06-24"
categories: ["Economics"]
---

Should we be surprised when PIMCO’s Paul McCulley writes ‘[A Kind Word for the Austrian School](http://www.pimco.com/LeftNav/Late+Breaking+Commentary/FF/2006/FF+July+2006.htm "A Kind Word for the Austrian School")’?  We have previously drawn attention to the rather bizarre views of the senior officers at PIMCO, not least [McCulley’s](../2005/pimco_to_the_fed_regulate_me.qmd "McCulley’s") call for the re-regulation of financial markets, and [Bill Gross’](../2006/pimcos_bill_gross_the_end_is_nigh.qmd "Bill Gross’") doomsday cultism in relation to the US dollar.  But the PIMCO crew are not only ones invoking Austrian business cycle theory on behalf of bizarre macro views.  The ‘Austrian School’ has received favourable mention from central bankers at the [BIS](../2006/who_spiked_the_drinks_at_the_bis.qmd "BIS"), not exactly the traditional home of Austrian School thinking.  [The Economist](http://www.economist.com/business/globalexecutive/dialogue/displayStory.cfm?Story_id=4221685 "The Economist") magazine loves to say that ‘the Austrian school of economics offers perhaps the best framework to understand what is going on,’ and a few years ago ran a special feature on the world economy that was explicitly Austrian.  One could almost be forgiven for thinking that Austrian business cycle theory is undergoing something of a revival.

It is not coincidental that all of the sources cited above have also been prominent in arguing that ‘bubbles’ are the main driver of the business cycle and asset prices.  But what causes ‘bubbles’ in the first place?  Austrian business cycle theory seemingly provides the answer: ‘it was the central bank wot done it!’  This is actually a fundamental explanation, but if people choose to label the process a ‘bubble,’ then so be it.

The notion that the monetary authority is largely to blame for business cycle and asset price fluctuations is appealing in its mono-causality, but also dangerous, because it promotes the idea that a more activist monetary policy could effectively smooth the economy and asset prices.  Needless to say, this is not the preferred conclusion of those in the Austrian School, who focus instead on changes in monetary regime.  But they should not be surprised by the misuse of their theory, which lends itself to exaggerating the importance of monetary policy to economic outcomes. 

This is especially true in a world of interest rate and inflation targeting, where monetary policy is largely an endogenous response to economic activity and the exogenous component of monetary policy is very small - so small, in fact, that many academic researchers question whether the exogenous component of monetary policy is large enough to have important macroeconomic implications.  In the Anglo-American economies, it is now probably more accurate to say that the economy drives monetary policy, not the other way around, which is actually fairly close to the Austrian ideal of a market-determined monetary system.
