---
title: "Fundamentals of House Price Inflation"
date: "2006-03-28"
categories: ["Economics"]
---

From [The Australian](http://www.theaustralian.news.com.au/common/story_page/0,5744,18627237%255E2702,00.html "The Australian"):

According to a [report](http://www.propertyoz.com.au/ "report") commissioned by the Property Council of Australia, government charges associated with a typical house and land package had risen an average of \$77,000 since 2000.

In southeast Queensland’s Redlands Shire those charges had soared 583 per cent in five years to \$135,799, while government charges on a house and land package in Adelaide rocketed 331 per cent to \$53,003.

But the problem was most pronounced in Sydney’s northwest where 35 per cent - or almost \$200,000 - of the price of a new home was eaten up by government charges.

In comparison the cost of the land was only \$116,667…

In the five years to 2005 government costs associated with buying a house and land package in northwest Sydney grew 197 per cent to \$198,670.

In Melbourne and Canberra those costs grew 146 per cent to \$91,135, and 237 per cent to \$108,011, respectively.\
