---
title: "Fundamentals of House Price Inflation: Single Eye for the (Straight) Melbourne Guy Edition"
date: "2006-02-24"
categories: ["Economics"]
---

Previous posts have noted the convergence in capital city house prices with those in Sydney and suggested, as has RBA Governor Macfarlane, that internal migration is one of the equilibrating factors at work.  The latest [ABS release on regional population growth](http://www.abs.gov.au/AUSSTATS/abs@.nsf/ProductsbyReleaseDate/797F86DBD192B8F8CA2568A9001393CD?OpenDocument "ABS release on regional population growth") is consistent with this view, as reported in [The Australian](http://www.theaustralian.news.com.au/common/story_page/0,5744,18255199%255E2702,00.html "The Australian"):

SYDNEY’S population growth is lagging behind that of Brisbane and Melbourne, with fresh evidence people are abandoning the nation’s largest city to escape inflated property prices and reduced job opportunities.

Australian Bureau of Statistics figures released yesterday show Melbourne and Brisbane outstripped Sydney’s population growth rate last financial year.

The figures are further evidence the NSW economy has slowed, with Melbourne attracting a net 41,300 people last year, a growth rate of 1.1 per cent, compared with Sydney’s 29,800, or 0.7 per cent.

Brisbane remains the fastest-growing city, with a growth rate of 1.9 per cent, while coastal regions continued to lure those in search of a sea change…

The lower growth rate came despite 37,000 migrants arriving in NSW during 2004-05.

However, 26,000 people left NSW for another state during the same period.

ABS statistician Andrew Howe said Melbourne had been growing faster than Sydney since 2001.

The figures show southeast Queensland continues to boom, growing by 53,300 people, or more than 1000 a week.

The Australian report (channeling the tabloid style of the SMH), goes for this supposedly illustrative vox pop:

Management consultant Janet Martin is among those making the shift south. Having lived in Sydney for 10 years, Ms Martin decided six months ago to move from Annandale in Sydney’s inner west to South Yarra in Melbourne’s inner east in search of a more vibrant culture and cheaper housing.

Ms Martin, 34, said the increased proportion of single men in the city had proved an added bonus. She had spent the last year and a half in Sydney single, but found a boyfriend within two months of moving to Melbourne.

“All I know is now I have a boyfriend who’s my age, who has two cats and wants to make babies,” Ms Martin said.

Increased proportion of straight men perhaps!  For the record, the median Sydney house price actually rose 1% in Q4, consistent with the argument I made some time ago that Sydney house price growth would bottom relative to trend by the middle of 2006.  But as the [ABS release](http://www.abs.gov.au/AUSSTATS/abs@.nsf/Lookup/6416.0Main+Features1Dec%202005?OpenDocument "ABS release") shows, it is the differences in annual growth rates among the capital cities that are the more interesting story.
