---
title: "Greenspan’s Legacy"
date: "2006-01-13"
categories: ["Economics"]
---

The Economist has a tired and predictable [piece](http://www.economist.com/finance/displaystory.cfm?story_id=5381959 "piece") on Greenspan’s legacy:

*The Economist’s long-running quarrel with Mr Greenspan is that he chose not to restrain the stockmarket bubble in the late 1990s or to curb today’s housing bubble.*

My long-running quarrel with The Economist is that this argument is nonsense.  Peter Hartcher attempted to string a [book](http://www.amazon.com/exec/obidos/ASIN/0393062252/institutional-20?creative=327641&camp=14573&link_code=as1 "book") out of this argument, with disastrous consequences that I review [here](http://www.institutional-economics.com/index.php/section/comments/bubble_man_alan_greenspan_the_missing_7_trillion_dollars_by_peter_hartcher/ "here").  [Elsewhere](http://www.economist.com/opinion/displaystory.cfm?story_id=5385434 "Elsewhere"), The Economist says ‘One should not exaggerate Mr Greenspan’s influence—both good and bad—over the economy,’ before going on to do precisely that.  The Economist’s cover story, ‘Danger Time for America,’ contains the usual tired predictions of housing-related economic ruin.  According to The Economist:

*The problem is not the rising asset prices themselves but rather their effect on the economy. By borrowing against capital gains on their homes, households have been able to consume more than they earn. Robust consumer spending has boosted GDP growth, but at the cost of a negative personal saving rate, a growing burden of household debt and a huge current-account deficit.\*
\
The Economist just assumes that all this is a bad thing.  It is in fact a sign of economic strength, not weakness.  The Economist remains as wedded as ever to Bretton Woods era economics.

I picked up a copy of the second edition of Peter Garber’s classic [Famous First Bubbles](http://www.amazon.com/exec/obidos/ASIN/0262072041/institutional-20/103-3650639-0974267?creative=327641&camp=14573&link_code=as1 "Famous First Bubbles") the other day.  The conclusion has a great passage explaining why The Economist’s incantations in relation to ‘bubbles’ are the hallmark of intellectual confusion:

*“bubble” characterizations should be a last resort because they are non-explanations of events, merely a name that we attach to a financial phenomenon that we have not invested sufficiently in understanding.  Invoking crowd psychology - which is always ill defined and unmeasured - turns our explanation to tautology in a self-deluding attempt to say something more than a confession of confusion.*
