---
title: "‘Guardians’ of the Future Fund"
date: "2006-03-11"
categories: ["Economics"]
---

[Alan Wood](http://www.theaustralian.news.com.au/common/story_page/0,5744,18418208%255E31478,00.html "Alan Wood"), on the governance of the Future Fund:\

\
Choosing the members of the curiously named board of guardians is up to the responsible ministers - currently Peter Costello and Nick Minchin. (Pursued in senate estimates on the legal standing of the term “guardian” compared with the more familiar term “trustee”, the Government’s Senator George Brandis, a barrister, said the only common law about guardians was in relation to children and the insane.)

The process is much the same as the one that led to the appointment of Rob Gerard to the Reserve Bank board.

Governance issues aside, Wood gets to the heart of why the Future Fund is such a bad idea:

Unfunded public service superannuation liabilities are not a problem.

The size of the liability is not large relative to future budgets and will steadily decline now the Government has closed off most of its defined benefit funds. And there is a strong economic argument for not using budget surpluses to fund these liabilities, put by economist Nicholas Barr from the London School of Economics, an international authority on pension funds. Barr’s basic point is simple but profound - what matters for an ageing population is not how much money it has put away, but availability of goods and services to satisfy its demands. That is, the level of output.

“The point is central,” Barr says. “Pensioners are not interested in money (that is, coloured bits of paper with portraits of national heroes), but in consumption - food, clothing, heating, medical services, seats at football matches, and so on. Money is irrelevant unless the production is there for pensioners to buy.”

Former treasury secretary Ted Evans made the point this way: “Let’s be clear that the ability of future generations, and their governments, to meet the needs of their day will be entirely dependent on the size of the economy they command at the time. Hence the greatest contribution that today’s population can make to the living standards of future generations is to ensure that today’s policies are directed towards maximising future GNP.”

Evans suggested the best way to do this wasn’t through an inter-generational fund like the Future Fund, but by leaving the tax revenue in the hands of taxpayers to spend as they see fit, that is, tax cuts.

Putting surpluses in the Future Fund amounts to increasing tax on this generation of taxpayers. Does increasing the tax burden over the next few years really sound like the best way of increasing GDP in, say, 2020? Hardly.\
\
CIS has a [much better idea](http://www.cis.org.au/IssueAnalysis/ia66/IA66.pdf "much better idea").
