---
title: "Guest Blogger: Andrew Norton"
date: "2006-09-05"
categories: ["Misc"]
---

Andrew Norton will be guest posting temporarily at Institutional Economics.  Andrew will already be known to most of you.  He is a Research Fellow at the Centre for Independent Studies and an acting editor of its journal Policy.  Andrew is a political theorist by training rather than an economist.  This is something we actually have in common.  I started out as a political scientist before re-training an economist, so we are both refugees from academic political science.  His first post is below this one.

This is a good time to remind people about procedures for commenting at Institutional Economics. Access to comments requires completion of a one-time registration and log-in process (click [here](http://www.institutional-economics.com/index.php/member/register/ "here") to register).  You must use a valid email address to register, but this need not be displayed in comments.  If you access this site from more than one computer, you may need to log-in again to comment (if you are asked to enter an alpha-numeric character string with your comment, it means you are not logged on.  Click ‘log-in’ in the black bar at the top right hand side of this page to log-in again.  Andrew will be responsible for editorial decisions in relation to comments on his posts.
