---
title: "Hillary and the Candlemakers"
date: "2006-06-24"
categories: ["Economics"]
---

Senator Clinton [breaths new life](http://www.cato-at-liberty.org/2006/06/23/hillary-and-the-candlemakers-not-a-parody/#more-426 "breaths new life") into an old classic:

> One of the most famous documents in the history of free-trade literature is Bastiat’s famous “[Candlemakers’ Petition](http://bastiat.org/en/petition.html "Candlemakers’ Petition").” In that parody, the French economist and parliamentarian imagined the makers of candles and street lamps petitioning the French Chamber of Deputies for protection from a most dastardly foreign competitor:
>
> “We are suffering from the ruinous competition of a rival who apparently works under conditions so far superior to our own for the production of light that he is flooding the domestic market with it at an incredibly low price; for the moment he appears, our sales cease, all the consumers turn to him, and a branch of French industry whose ramifications are innumerable is all at once reduced to complete stagnation. This rival…is none other than the sun.”
>
> For after all, Bastiat’s petitioners noted, how can the makers of candles and lanterns compete with a light source that is totally free? Thank goodness we wouldn’t fall for such nonsense today. Or would we?
>
> Last month, Sen. Hillary Rodham Clinton and nine colleagues (ranging from Barbara Boxer to Tom Coburn) endorsed a petition from — you guessed it — the domestic candlemaking industry asking the secretary of commerce to impose a 108.3 percent tariff on Chinese candle producers.
