---
title: "‘I am an old-fashioned Christian socialist’"
date: "2006-12-15"
categories: ["Politics"]
---

Kevin Rudd, like the Labor Party itself, [can’t decide](http://www.theaustralian.news.com.au/story/0,20867,20930265-2702,00.html "can’t decide") whether he is a socialist or not.

As [Paul Kelly](http://blogs.theaustralian.news.com.au/paulkelly/index.php/theaustralian/comments/labor_must_push_market_reforms/ "Paul Kelly") notes:

> It is disappointing that Kevin Rudd has given heart to the economic throwbacks with his rhetoric attacking “market fundamentalism”. This panders to the focus groups, short-term politics and ideological convictions that only consign Labor to a dead end…
>
> Depicting John Howard as a neo-liberal is the staple for “true believer” dinner tables but bunkum as an analysis of Australian politics. Howard has not won four elections by being a neo-liberal.
>
> The task of the next ALP government will be to cut the fat from government spending, expand competition policy, de-regulate the universities, introduce more market signals into health, education, transport and energy, eliminate red tape from business, simplify the tax and industrial systems, cut marginal tax rates, encourage the welfare to work transition, invest more in education and training, encourage entrepreneurs in the market place and aspire for a more competitive economy. Railing about market fundamentalism is a stunt.
>
> Rudd’s choice is clear. He can either present as a serious economic policy-maker or engage in the populist positioning that has damaged Labor for too long.
