---
title: "Ian Macfarlane’s Boyer Lectures"
date: "2006-11-27"
categories: ["Economics"]
---

Former RBA Governor Ian Macfarlane’s [Boyer Lectures](http://www.abc.net.au/rn/boyerlectures/stories/2006/1769925.htm#transcript "Boyer Lectures") give a misleading account of monetary policy developments in the late 1980s and their role in the early 1990s recession.  Macfarlane notes that:

> *The risk that worried most observers was the large deficit on the current account or the balance of payments, and the associated build-up of foreign debt. Most politicians, businesspeople, economists, journalists, and the community in general, regarded this as public economic enemy No.1.*

Unfortunately, this was also a view then fully shared by the Reserve Bank, which had disastrous consequences for the conduct of monetary policy.  In relation to the recession that followed the tight monetary policy of the late 1980s, Macfarlane says:

> What adjustments to monetary policy could have prevented this situation from arising? There were many critics who believe that we should have had tougher monetary policy in place, and suggestions were made for stricter arrangements including such exotic ones as currency boards and commodity standards. Calls for monetary policy to take a harder line continued to be the refrain right through to the 1993 election, with the Fightback policy of the Coalition Opposition parties as its logical conclusion. But interest rates were already extremely high in real and nominal terms, and had been for most of the decade. Any monetary policy that could have prevented the surge in credit and asset prices in the second half of the 1980s, would have involved even higher interest rates. But how could the regular parts of the economy, those parts relying on cashflow from producing goods and services, and those competing with the rest of the world, have coped with higher interest rates…
>
> The issue of how monetary policy could have been better conducted in the 1980s will probably never be resolved. I think we can conclude, however, that to the extent that there was a failure of monetary policy, it was not due to the traditional problem of the government and the central bank being unwilling to take tough measures, but was instead due to a failure to understand the implications of a sudden financial deregulation.

This misrepresents the nature of the debate over monetary policy in the late 1980s and early 1990s.  The underlying issue was not about whether policy was too tight or too loose, but the framework within which monetary policy was conducted.  The critics of the RBA at the time argued that Australia had high interest rates because monetary policy lacked credibility and could only establish credibility via institutional reform.  This is why the federal Coalition’s 1993 Fightback manifesto advocated the adoption of NZ-style inflation targeting.  Macfarlane’s reference to currency boards and commodity standards is an attempt to muddy the waters, by associating the advocates of reform with arrangements which no longer have much support.  The only reason some of these more exotic arrangements were seriously discussed in the Australian context was that monetary policy had become such a mess that some reform advocates were doubtful that monetary policy credibility could be established in any other way.  That view proved too pessimistic, but such pessimism could easily be forgiven in the early 1990s.

The RBA’s adoption of inflation targeting from the early 1990s was a vindication of the Bank’s critics, who had always stressed the need to focus on a single policy objective.  It is thus wrong to say that ‘The issue of how monetary policy could have been better conducted in the 1980s will probably never be resolved.’ 

John Edwards, former economic adviser to Prime Minister Paul Keating, has also taken issue with Ian Macfarlane’s interpretation of history in his Lowy Institute paper, [Quiet Boom](http://www.lowyinstitute.org/Publication.asp?pid=506 "Quiet Boom"):

> *This interpretation of the period seems to me quite wrong…. For some of the key players the tightening of monetary policy was not mainly about inflation.  The Reserve Bank officially claimed in its 1988 annual report that the tightening began as a response to higher imports threatening ‘the improving trend in the balance of payments’, as well as a response to growth in earnings and prices threatening ‘the downward trend in inflation’. So far as Treasurer Paul Keating and his cabinet colleagues were concerned, the policy objective was not inflation so much as the current account deficit. This objective made the tightening episode vastly more difficult because after a period of stability the current account deficit began to widen again. In the mid eighties Prime Minister Bob Hawke and Treasurer Paul Keating had used the rising current account deficit to illustrate the necessity of faster economic reform. In doing so they made the size of the current account deficit a test of economic success. As Keating would later remark, the government was ‘hoist on its own petard’ by the sudden widening of the deficit in the late nineteen eighties. When it began to increase with rising business investment, they were convinced that it must be narrowed by slowing domestic demand. What began mildly enough with ‘the sound of a harp’ became a struggle to rein in the current account deficit before the next election… The political and economic impact of the subsequent recession was conditioned by the fact that it began after the Reserve Bank had began to cut interest rates.*
