---
title: "‘It’s An Inflation Target Jim, But Not as We Know It.’"
date: "2006-03-15"
categories: ["Economics"]
---

Back in January, I argued in [Business Week](../../files/Will_Japan_Target_Inflation_in_2006_.pdf "Business Week") that the BoJ would probably relax its previous opposition to an inflation target, in association with the end to quantitative easing and a return to an official interest rate as the BoJ’s main operating instrument.  In the event, the BoJ moved a month sooner that I expected.  But the BoJ’s ‘[New Framework for the Conduct of Monetary Policy](http://www.boj.or.jp/en/seisaku/05/pb/k060309b_f.htm "New Framework for the Conduct of Monetary Policy")’ falls well short of fully fledged inflation targeting.

The new framework defines an inflation rate of 0-2% as desirable over the medium to long term, with the central tendency of BoJ policy board’s view of price stability said to be 1%.  As I noted in the article in Business Week, this is consistent with Japan’s long-run average inflation rate.  The BoJ says that it ‘will review its basic thinking on price stability, and disclose a level of inflation rate that its Policy Board members currently understand as price stability from a medium to long-term viewpoint, in their conduct of policy.’  This is something that will be ‘reviewed annually’ and the BoJ will ‘conduct monetary policy in the light of such thinking and understanding,’ but otherwise there is no explicit link between inflation outcomes and monetary policy.  The inflation target thus does not limit the BoJ’s policy discretion in any way.  While announcing an inflation rate deemed consistent with price stability might help in anchoring long-term inflation expectations, it will do little to condition expectations for the near term path of inflation or interest rates.  The BoJ’s experience with the zero bound and deflation shows that expectations management is essential to the effective conduct of monetary policy.  The BoJ’s new policy framework is a missed opportunity.
