---
title: "Kirchner the ‘Cornucopian’"
date: "2006-02-22"
categories: ["Economics"]
---

Via my server stats, I found this rather amusing [link](http://forestpolicy.typepad.com/economics/2006/01/through_a_glass.html "link") to Institutional Economics:

Skirchner seems well-educated, a good writer, and glowingly optimistic. Yet within the span of a few posts, beginning with his January 24th “The Doomsday Cult Comes to Reno,” Skirchner says “Warren Buffet is sounding more and more ridiculous,” “Stephen Roach is having trouble getting his colleagues and clients to take him seriously,” “PIMCO’s Bill Gross \[is\] keeping the doomsday cult alive,” and “The Economist has a tired and predictable piece on Greenspan’s legacy.” All of this, and likely more on his blog pretty much contradicts all of what I post here.

So what gives? How is it that Skirchner can be so optimistic and me so pessimistic? Does he see more than I? Less? Do we both see pretty much the same stuff, yet draw radically different conclusions as to what is and what might come? I dont’ know.

Maybe Skirchner and others can help me to see the world differently, or at least to better understand how those I call “Cornucopians” can be so glowingly optimistic.

I’m here to help!  But if Bretton Woods era economics is really more your thing, you can always go check out [Brad and Nouriel](http://www.rgemonitor.com/ "Brad and Nouriel"), the [Stadler and Waldorf](http://www.houseofhum.com/stephen/lj/stadler-waldorf2.jpg "Stadler and Waldorf") of international macro.

As far as the contrarian optimist versus doomsday cult scorecard goes, [Kevin Hassett](http://www.aei.org/publications/filter.all,pubID.23910/pub_detail.asp "Kevin Hassett") notes that Q1 GDP growth in the US is shaping up as a boomer (and yes, I know about the weather.)
