---
title: "More of What Nouriel Roubini Won’t Tell You About the US Economy"
date: "2006-12-14"
categories: ["Economics", "Financial Markets"]
---

[Larry Kudlow](http://kudlowsmoneypolitics.blogspot.com/2006/12/looking-good-goldilocks.html "Larry Kudlow") notes that the US November retail sales report almost single handedly tanks Roubini’s call for zero US growth in Q4:

> *The key point here is that it virtually eliminates the zero percent Q4 scenario from recession bears like Nouriel Roubini. You can’t get zero here - toss that scenario in the garbage.*

This is what my associates at [Action Economics](http://www.actioneconomics.com "Action Economics") had to say about the report:

> The U.S. retail sales report should be a game-changer for those positioned for an imminent hard landing for the U.S. economy, with sizable housing sector “pass-through.” Hard landing estimates increasingly need to address why pass-through during the first 15-18 months of the housing correction is taking so long to materialize if it is really going to prove more dramatic than most economists assume.
>
> And time is not on the side of those with a near-term doom-and-gloom view, as both the firming evident in most housing market data since the big June-August downsizing, and the robust uptrend in the MBA mortgage data over the last three weeks and other recent signs of reversal in the real estate market suggest that the correction for sales is likely approaching the end, though there will be lagged construction sector effects.
>
> To be sure, most economists, as well as most FOMC members, have stuck to their guns that pass-through of weakness from the housing sector is thus far limited even if it remains the risk, and that the slowdown is proving orderly, with growth “at a moderate pace” as described in yesterday’s FOMC statement.
>
> Today’s U.S. retail sales report removes much of the controversy associated with this view.
