---
title: "Lunch with Mark Latham"
date: "2006-09-26"
categories: ["Politics"]
---

Former federal Labor minister [Barry Cohen](http://www.theaustralian.news.com.au/story/0,20867,20474697-7583,00.html "Barry Cohen"), on lunch with Mark Latham:

> Latham also has memory lapses. He forgot to mention what happened during lunch. Having raised three sons, we should have known better than leave my wife Rae’s prized piece of porcelain on the coffee table. Oliver, a two-year-old, picked it up and smashed it into a thousand pieces - at his father’s feet. It was not Oliver’s fault, but ours.
>
> Rae showed remarkable restraint. White knuckles, an intake of oxygen and a gurgled “Oh, dear”, was her only indication of pain.
>
> Mark showed even greater restraint. He didn’t even notice. No apology. No “I’m sorry”. No attempt to clean up the debris. Nothing. It was a minor incident in life’s rich tapestry but it revealed the true nature of Mark Latham.
>
> As he departed, the First Lady hissed through gritted teeth: “If that bastard ever becomes leader of the Labor Party, I’m voting Liberal.” She kept her promise. Fortunately for Australia, she was not alone.
