---
title: "Macro Myth-busting with Ed Prescott"
date: "2006-12-11"
categories: ["Economics"]
---

[Ed Prescott](http://online.wsj.com/article/SB116579723019846033.html?mod=opinion_main_commentaries "Ed Prescott") tackles five macroeconomic myths, including some of this blog’s favourite targets:

> Myth No. 3: Americans don’t save. This is a persistent misconception owing to a misunderstanding of what it means to save. To get a complete picture of savings we need to investigate economic wealth relative to income. Our traditional measures of savings and investment, the national accounts, do not include savings associated with tangible investments made by businesses and funded by retained earning, government investments (like roads and schools) and business intangible investments.
>
> If we want to know how much people are saving, we need to look at how much wealth they have. People invest themselves in many and varied ways beyond their traditional savings accounts. Viewing the full picture—economic wealth—Americans save as much as they always have; otherwise, their wealth relative to income would fall. We’re saving the right amount.
