---
title: "Milton Friedman, 1912-2006"
date: "2006-11-17"
categories: ["Economics"]
---

Friedman was a giant of 20th century economics, as well as the post-war revival of classical liberalism.  Ben Bernanke paid this tribute to Friedman at the 2003 Dallas Fed Symposium on [The Legacy of Milton and Rose Friedman’s Free to Choose](http://www.dallasfed.org/news/research/2003/03ftc.html "The Legacy of Milton and Rose Friedman’s Free to Choose"):

> *Friedman’s monetary framework has been so influential that, in its broad outlines at least, it has nearly become identical with modern monetary theory and practice. I am reminded of the student first exposed to Shakespeare who complained to the professor: “I don’t see what’s so great about him. He was hardly original at all.  All he did was string together a bunch of well-known quotations.” The same issue arises when one assesses Friedman’s contributions. His thinking has so permeated modern macroeconomics that the worst pitfall in reading him today is to fail to appreciate the originality and even revolutionary character of his ideas, in relation to the dominant views at the time that he formulated them.*

Of course, Friedman’s influence extended well beyond monetary theory and policy.  He was an enormous influence on my own thinking about economics and public policy.  He is one of the few 20th century intellectuals who changed the world for the better.
