---
title: "More Gold Buggery"
date: "2006-02-07"
categories: ["Economics"]
---

One of the reasons why it is hard to take gold bugs seriously is that much of the hype around gold seems to be linked to the selling of gold stocks.  A number of people have pointed me in the direction of this [report](http://www.gata.org/CheuvreuxGoldReport.pdf "report") from the Cheuvreux broking house, which contains this rather bullish forecast under the heading ‘Remonetisation of Gold: Start Hoarding’:

*We also believe that there is a reasonable chance that we could see the gold price\
spike up much further, possibly to USD2,000/oz or even higher.*

The report is a good summary of the gold bugs’ rather conspiratorial worldview, but I find very little of it convincing, for reasons articulated in previous posts.  Remarkably, the report argues that both inflation and deflation are good for the gold price, so gold seemingly can’t lose.  It is also quite possibly the longest buy recommendation for a gold stock (specifically, Anglo-American) ever penned.
