---
title: "More of What Nouriel Roubini Won’t Tell You About the US Economy"
date: "2006-09-15"
categories: ["Economics"]
---

More of what Nouriel Roubini won’t tell you about the US economy, from my associates at [Action Economics](http://www.actioneconomics.com "Action Economics"):

> Today’s U.S. data on sales, prices, the labor market, and inventories all suggest that the widely assumed slowdown in the U.S. economy through the second half of the year is proving more modest than some fear, with none of the periodic and clumsy downside adjustments that have thus far been contained entirely to the housing market.
>
> For retail sales, the report revealed slightly stronger than expected total sales through August, but a shift in the mix of sales to vehicles from other goods that reduce prospects for consumption growth in Q3—given that the auto data in the retail sales report are not “source variables” for the GDP calculation.
>
> Retail sales overall continue to post healthy growth, with a return in y/y growth to the 6.7% area that is just below the lofty 7% figures generally seen through the prior twelve high-growth quarters of this expansion. The August y/y pop in growth followed a temporary dip in July to 4.5% that entirely reflected the hard comparison to last year’s July vehicle sales binge.
>
> We now expect a hearty 3.5% real growth clip in consumption in the Q3 GDP report, following a 2.6% clip in Q2 that might be bumped down to 2.5%, and 4.8% rate in Q1. The implied downward adjustment to Q2 consumption in the final GDP report for the quarter was \$1.5 bln.
>
> Nominal consumption growth is poised to slow somewhat in Q3, in keeping with a modest slowdown in growth, despite the bounce in real growth. We project a stabilization of the savings rate around -0.7% in Q3 and Q4. The high 6.8%-7% nominal growth rates for consumption in Q1 and Q2 will be followed by a solid though lower 6% rate in Q3, and a projected 5%-6% rate in Q4 and beyond that is in line with the assumed economic slodown.
>
> In total, the variations in consumer spending as gauged by this report through August are right in line with normal monthly and quarterly volatility, and are showing no sign that the economy is undergoing any sizable slowdown, as some fear. Though we continue to expect the downtrend in the savings rate through this expansion to transition to a sideways pattern through the second half of the year, and the monthly data are cooperating with this assumption, the transition is proving gradual.
