---
title: "North Korean Missile Launches for Fun and Profit"
date: "2006-06-22"
categories: ["Financial Markets", "Foreign Affairs & Defence"]
---

[Intrade](http://www.intrade.com/apply.jsp?heardFromPromotionDetail=s0545138709r "Intrade") has a contract available on a North Korean missile launch outside its airspace by 31 July, but not if [Ashton Carter and William Perry](http://www.washingtonpost.com/wp-dyn/content/article/2006/06/21/AR2006062101518.html?sub=AR "Ashton Carter and William Perry") get their way:

> *if North Korea persists in its launch preparations, the United States should immediately make clear its intention to strike and destroy the North Korean Taepodong missile before it can be launched. This could be accomplished, for example, by a cruise missile launched from a submarine carrying a high-explosive warhead. The blast would be similar to the one that killed terrorist leader Abu Musab al-Zarqawi in Iraq. But the effect on the Taepodong would be devastating. The multi-story, thin-skinned missile filled with high-energy fuel is itself explosive—the U.S. airstrike would puncture the missile and probably cause it to explode. The carefully engineered test bed for North Korea’s nascent nuclear missile force would be destroyed, and its attempt to retrogress to Cold War threats thwarted. There would be no damage to North Korea outside the immediate vicinity of the missile gantry.*
