---
title: "Permabears Seek Validation in the Cycle"
date: "2006-06-14"
categories: ["Economics", "Financial Markets"]
---

Markets are sending very strong signals of late.  The yield curve inversion in the US and elsewhere, falling stock and commodity prices are all pointing to a weaker global growth outlook.  The curve flattening in particular reflects a ‘stagflation trade’ which anticipates central banks overdoing monetary policy tightening to contain inflation pressures. 

The permabears have been busy recasting their long-running structural bear call into a cyclical one, hoping the cycle will finally validate them.  It is increasingly likely that the cycle will finally oblige them on at least some counts.  If nothing else, they have the law of averages on their side.  Yet markets have not yet delivered much joy to the purveyors of macroeconomic anti-Americanism.  Just ask anyone who followed their advice and bought non-USD denominated asset markets, particularly Asian equities, as a hedge against USD weakness.  So far, the USD has been a beneficiary of recent market developments and Asian equities have been crunched.  Some hedge!
