---
title: "Peter Costello’s International Tax Beauty Contest"
date: "2006-02-27"
categories: ["Economics"]
---

Treasurer Costello has [instituted a study](http://www.treasurer.gov.au/tsr/content/pressreleases/2006/008.asp "instituted a study") to ‘internationally benchmark’ Australia’s taxation system to those found in other countries.  The inquiry will report in April, just before the May Budget.  The Treasurer has already indicated that he thinks that Australia’s tax system compares favourably to other OECD countries.  While this is almost certainly true, it is also completely irrelevant. 

The most obvious benchmark for Australia is the US.  The US is itself the scene of a major debate about tax reform, reflecting what many regard as fundamentals flaws in their tax system (for one contribution to the US debate, see [here](http://www.aei.org/books/filter.all,bookID.820/book_detail.asp "here")).  To say that Australia compares favourably to other countries is simply to highlight the woeful state of revenue raising systems throughout the OECD.  This reflects the simple reality that taxation is an area of public policy that is particularly vulnerable to corruption via rent-seeking and, once corrupted, becomes very difficult to reform.

Costello will almost certainly use the report’s findings to re-assert his authority over the tax debate, while at the same time seeking to counter demands for a renewed tax reform effort in Australia.  It confirms Costello’s position as the most conservative politician in Australia, in the non-political sense of the term.
