---
title: "Peter Costello: Author of His Own Beauty"
date: "2006-03-31"
categories: ["Economics"]
---

Dick Warburton and Peter Hendy as fig leaves for Treasury:

Late last month, the Treasurer appointed leading business figures Dick Warburton and Peter Hendy to conduct a study comparing Australia’s tax competitiveness with other nations.

But [The Australian](http://www.theaustralian.news.com.au/common/story_page/0,5744,18661794%255E2702,00.html "The Australian") has learned that almost all the work is being done by a team of nine Treasury officials who are conducting the research and drafting the report in order to meet the April 3 deadline set by Mr Costello.

It is understood that the Treasury team has been sending Mr Warburton, the chairman of Caltex Australia and a former Reserve Bank director, and Mr Hendy, the chief executive of the Australian Chamber of Commerce and Industry, drafts of chapters detailing their conclusions for the authors’ comments.

But it is understood Treasury failed to include some of the authors’ amendments and suggested changes in revised drafts.

Mr Warburton admitted yesterday that the report was being written by Treasury officials but said any comments he believed should be included would be in the report. “Peter Hendy and I would not have the time to write this material,” he told The Australian.

He defended the process as necessary given the tight deadline set by Mr Costello, which will allow the Treasurer to consider its findings before making any changes to the tax system in the May budget.

Mr Warburton and Mr Hendy were reviewing Treasury’s work yesterday, four days before the report’s Monday deadline.

Mr Warburton denied that the review’s independence was compromised by Treasury’s role in sourcing the evidentiary material. He agreed those involved in the review were working “long hours” but denied an overseas trip he is due to make next week had compromised the inquiry.\
