---
title: "Peter Costello: The Heir Unapparent"
date: "2006-03-02"
categories: ["Politics"]
---

The 10th anniversary of John Howard’s ascent to the Prime Ministership has not surprisingly seen increased scrutiny of his Deputy, Peter Costello.  In part, Costello has drawn this attention to himself, with the announcement of his [international tax beauty contest](../2006/peter_costellos_international_tax_beauty_contest.qmd "international tax beauty contest"), as well as a recent foray outside his portfolio responsibilities.  The punditocracy was unimpressed with both efforts.  His speech on citizenship has drawn this response from [Greg Sheridan](http://www.theaustralian.news.com.au/common/story_page/0,5744,18318771%255E601,00.html "Greg Sheridan") (or at least the sub-editor’s paraphrase):

*This shallow, lazy, lucky and opportunistic Treasurer does not deserve to run the country.*

On tax, [Sinclair Davidson](http://www.smh.com.au/news/opinion/unnecessary-review-reflects-lack-of-initiative/2006/03/01/1141191731131.html "Sinclair Davidson") notes:

*Apart from some tinkering at the margins, he has done nothing…The top marginal tax rate of 47 per cent has remained unchanged since Paul Keating was treasurer…By calling for a review of the basic facts of the tax system, Costello has shown himself to be years out of date and uninformed.  Costello has relied on three arguments to stymie tax reform. First, that Australian tax rates aren’t that high; second, that the tax take is small; and third, that tax reform would only benefit a small number of Australians. Each of these arguments is false.*

[Alan Wood](http://www.theaustralian.news.com.au/common/story_page/0,5744,18320015%255E601,00.html "Alan Wood"), by contrast, attempts this rather lame defence of Costello:

this time Australia has avoided the boom’s inflationary consequences, and “there are grounds for optimism it can avoid a subsequent bust”.

If we do, it will be because of the better economic policy framework Costello has played an important role in putting in place.\
\
Peter Costello has cited ‘Reserve Bank independence’ as one of his greatest achievements as Treasurer.  The August 1996 exchange of letters between the Treasurer and RBA Governor was in fact a mere codification of existing practice.  In 1996, the RBA was already doing what the Treasurer now claims credit for.  This fell well short of the comprehensive statutory reform of central banking institutions seen in other countries during the 1990s.  Along with the US Fed, this has left Australia with one of the most antiquated frameworks for monetary policy governance among the major industrialised countries.
