---
title: "Policy and Process at the RBA"
date: "2006-10-17"
categories: ["Economics"]
---

While most journalists remain preoccupied with monetary policy outcomes at the expense of processes, at least [some journalists](http://www.smh.com.au/news/business/rba-board-needs-to-let-more-light-in/2006/10/16/1160850869181.html?page=2 "some journalists") remain interested in the procedural aspects of monetary policy formulation:

> These outside \[RBA Board\] members are already expected to leave their private and business interests at the boardroom door. Publishing the minutes would only confirm this, wouldn’t it?
>
> To insist on secrecy, ostensibly to protect the commercial sensitivities of board members’ comments in the course of debate, begs the perception, at least, that they may have something to hide. It also hints that the real reason may be to keep under wraps the occasional board conflict over rate decisions.
>
> The Reserve Bank has come a long way from the obscurantism of the past. And, undoubtedly, the present approach has served Australia well in the way the bank has conducted policy in the past decade.
>
> But shedding even more light on its decision making by publishing its board deliberations could only help Australians better understand where their mortgage payments and business borrowing costs are headed, and why.
