---
title: "Putting Central Bankers to the Flesch-Kincaid Test:  Greenspan Beats Bernanke"
date: "2006-09-14"
categories: ["Economics"]
---

ICAP economist [Michael Thomas](http://www.bloomberg.com/apps/news?pid=20601081&sid=afWWKo5Rb35M&refer=australia "Michael Thomas") runs the speeches of leading central bankers through the Flesch-Kincaid test:

> Australia’s central bank chiefs are easier to understand than their U.S. peers, though both lose out to straight-talking Bank of England Governor Mervyn King, according to a study by stockbroker ICAP Australia.
>
> U.S. Federal Reserve Chairman Ben Bernanke’s speeches require listeners to hold a bachelors degree with honors, said Michael Thomas, ICAP Australia’s head of economics. By contrast, high-school leavers could understand the speeches of incoming Reserve Bank of Australia Governor Glenn Stevens, and \`\`on a good day, King could hold court at his local primary school,’’ Thomas said.
>
> The study of recent speeches by central bankers used the Flesch-Kincaid test, which measures syllables per word and words per sentence, to assess how clearly a person speaks, and the education level a listener would need to understand the speaker. Former Fed chairman Alan Greenspan was famous for his sometimes obscure language—or, as Thomas put it, \`\`in his heyday, Greenspan could make a grocery list indecipherable.’’
>
> Still, Greenspan outperformed Bernanke in the Flesch-Kincaid test, while both lagged Australia’s Stevens and the outgoing Reserve Bank Governor Ian Macfarlane.
