---
title: "RBA Governor Macfarlane Unplugged"
date: "2006-08-12"
categories: ["Economics"]
---

RBA Governor Macfarlane is interviewed by [The Australian](http://www.theaustralian.news.com.au/story/0,20867,20099120-643,00.html "The Australian") ahead of his departure from the top job next month.  Macfarlane made precious few public appearances during his term as Governor and the interview gives some insight into why this is the case:

> *Macfarlane says the relationship between the governor and the Treasurer is a critical one - one which he has had no intention of jeopardising by getting up on a soap box on all sorts of issues.” We have been entrusted or delegated with independence,” he says. “It is a very valuable thing. I think it would be very foolish to jeopardise it by deciding you want to pontificate on subjects that are not relevant to your field.”*

This degree of timidity is unwarranted.  Both former Fed Chair Alan Greenspan and former RBNZ Governor Don Brash were quite outspoken on a wide range of issues, without compromising the independence of their respective central banks.  Brash subsequently became leader of the opposition New Zealand National Party.  Central bank independence does not mean being uncritical of government, it requires only that such criticism be expressed in a non-partisan fashion.  To stay silent on issues which have a bearing on inflation and interest rate outcomes so as not to embarrass the government of the day is potentially even more compromising to the independence of a central bank. 

Macfarlane is nonetheless correct in dismissing the notion that fiscal policy has had a material influence on monetary policy outcomes in recent years:

> Macfarlane rejects suggestions that the last budget was highly expansionary, putting more pressure on the bank to raise rates.
>
> “In the lead-up to the last budget, the Treasurer was under intense pressure to give massive tax cuts which he resisted and gave rather modest ones,” he says.
>
> Macfarlane argues it is too soon to tell whether the tax cuts of the May budget will be stimulatory - particularly given the propensity of the Government to be on the receiving end of larger than expected tax revenues.
>
> “The rather modest tax cuts he gave mainly consisted of returning the excess tax collections to the public,” he says. “Taxes may still come in faster than expected.”

Macfarlane goes on to defend the RBA’s antiquated governance framework, making this rather extraordinary argument in favour of not revealing minutes of the RBA Board’s proceedings:

> He says board members who come from different interest groups need to be able to freely discuss their views without feeling they have to be publicly accountable. He says board members “have to be able to overcome their allegiances”.
>
> “They wouldn’t be able to if it (their vote at board meetings) was relayed back to the sectors from which they came.
>
> “If their votes were recorded it would be very hard for them at times to make decisions from the national perspective.”

Macfarlane is effectively conceding that the non-ex officio members of the Board are conflicted in their role as monetary policymakers.  The notion that these conflicts of interest can be eliminated by cloaking them in a veil of secrecy would not be accepted in any other context and it is amazing that journalists - of all people - should continue to uncritically buy this argument from the Bank.

Meanwhile, opposition leader Kim Beazley has trouble telling [one Ian Macfarlane from another](http://www.news.com.au/story/0,23599,20106912-1702,00.html "one Ian Macfarlane from another").
