---
title: "RBA Governor-Designate Glenn Stevens"
date: "2006-08-02"
categories: ["Economics"]
---

[Stephen Gordon’s](http://worthwhile.typepad.com/worthwhile_canadian_initi/2006/08/the_new_governo.html "Stephen Gordon's") recollection of RBA Governor-designate Glenn Stevens:

> We both did our MA at the University of Western Ontario during the academic year 1984-85. I’m pretty sure that Glenn Stevens was the best student of our cohort (I think I was second), and I remember him telling me that UWO tried very hard to persuade him to stay on to do a PhD. He thought that it would be a waste of time, since he wasn’t interested in academia. Thinking of the Bank of Canada - where it’s well-nigh impossible to go very far without a doctorate - I asked him if he was worried about limiting his options. He didn’t think he was - and it turns out the he was right.
>
> In his picture, he has much less hair than I remember. But then again, so do I.
>
> Good on you, Glenn; I wish you well from the other side of the world.

Another profile of Glenn Stevens [here](http://www.theaustralian.news.com.au/story/0,20867,19989223-28737,00.html "here").
