---
title: "RBA Governor Macfarlane: ‘Shamefully Misquoted’"
date: "2006-09-05"
categories: ["Economics"]
---

RBA Governor Macfarlane presides over his final RBA Board meeting today.  Macfarlane has given more newspaper interviews in the last few weeks than in the last 10 year combined.  In the [latest interview](http://www.smh.com.au/news/National/RBA-governor-questions-rising-surplus/2006/09/05/1157222098799.html "latest interview"), he complains about being verballed on the issue of tax cuts:

> On the eve of his departure, Mr Macfarlane told The Australian Financial Review he saw little need to amass large budget surpluses just because the economy was growing solidly.
>
> “I have heard people\* say, \`Oh, we should let the fiscal stabilisers work,’” Mr Macfarlane told the newspaper.
>
> “I think they are working. I think if you have an economy that is growing at 3 per cent, as we have, there’s no reason why you would need bigger and bigger surpluses, in other words, why you would need to restrain it with some sort of fiscal restraint.
>
> “What we have got is a tax system which is unintentionally much more income-elastic than anyone designed it to be or even thought it was, and so that even with the economy going at trend growth, we are pulling in a huge amount of taxes and pushing ourselves into surplus.”
>
> Mr Macfarlane also endorsed Treasurer Peter Costello’s decision to deliver income tax cuts in his budget worth \$36.7 billion over four years.
>
> He said his comments on fiscal policy had been “shamefully misquoted” all year.
>
> “I had no problem with what the Treasurer did in the May budget,” Mr Macfarlane said.
>
> “The great irony - and I feel sorry for him in this respect - is that the same people who are urging him to make huge tax cuts have now turned around and said that what he did is pushing up interest rates.”

\*  \[That would be you Ross Gittins! - ed\]
