---
title: "Schmoozing in Davos"
date: "2006-01-27"
categories: ["Economics"]
---

Vanguard’s [John Bogle](http://online.wsj.com/article/SB113832422704457702.html?mod=opinion_main_commentaries "John Bogle"), heaping derision on the great and the good assembled at Davos:

*This year I’ve decided not to call the pilot, pop on to Vanguard’s G-4 and jet to Davos. Partly because we don’t “do” corporate airplanes…I confess I looked at this year’s program before I made my decision. I’m only truly sorry to miss Morgan Stanley’s Steve Roach, whose persistent gloomy warnings about the global economy have yet to come home to roost.*

By contrast, doomsday cultist [Nouriel Roubini](http://www.rgemonitor.com/blog/roubini/114886 "Nouriel Roubini") is completely star-stuck:

*Hopefully, one will also have time to schmooze with celebrities: this year Angelina Jolie is not around as she is pregnant to Brad Pitt but a stable of glitterati, glamoratas, artistata and hollywoodatas is certain to add glamour cachet to the highest concentration of gurus, eggheads, policy wonks, corporate leaders, net geeks and nerds and movers&shakers ever put together…*

Cringe!

**UPDATE:**  Another failed Roubini forecast:  ‘[Jolie tells starstruck summit to stay focused’](http://abcnews.go.com/Entertainment/wireStory?id=1548446&ad=true "Jolie tells starstruck summit to stay focused'")

DAVOS, Switzerland (Reuters) - Angelina Jolie told a summit of business leaders and politicians, many driven to distraction by the Hollywood siren, to concentrate on the real issues.

The Oscar-winner and her beau Brad Pitt, whose child she is carrying, have reduced the global elite at Davos to star-struck autograph hunters, scrambling over each other to get a glimpse of the actress and her man.

**UPDATE II:**  Italy’s Economy Minister tells Nouriel [where to go](http://www.rgemonitor.com/blog/roubini/115624 "where to go").  I happen to agree with Nouriel on EMU, except that I don’t see its prospective break-up as a ‘disaster.’  Still, it makes Nouriel’s bearishness on the USD all the more curious.
