---
title: "Setser’s Complaint"
date: "2006-03-29"
categories: ["Economics"]
---

The Economist (or more specifically, Lexington) is insufficiently left-wing for [Brad Setser](http://www.rgemonitor.com/blog/setser/122108 "Brad Setser"):

*Lexington could not find any public intellectuals (or ideas) from the center, the center-left or the left worthy of mention…I would say that the interesting policy debate on globalization currently is found on the left, not the right…The left takes seriously idea that the US needs to find ways to share the benefits of globalization more broadly and address growing concerns about economic insecurity and income volatility.*

These are more homilies than serious ideas, but the notion that this burden necessarily falls on the United States goes to the heart of Brad’s misdiagnosis of issues such as global imbalances.  Whatever institutional short-comings might be found in the US and other Anglo-American countries, it is the rest of the world, not the US, that needs to get its house in order.
