---
title: "Snowy Hydro: Myth versus Reality"
date: "2006-06-03"
categories: ["Economics"]
---

[Myth](http://www.bloomberg.com/apps/news?pid=10000081&sid=astx9EG5SDcs&refer=australia "Myth"):

*‘This is an unique piece of infrastructure with a cultural ethos,’ said Bernie Fraser, governor of the Reserve Bank of Australia between 1989 and 1996, and whose father Kevin worked on the Snowy. ‘The plan to sell related around short-term fiscal gains, and that is mad ideology for this icon,’ he said in an interview.*

[Reality](http://www.smh.com.au/news/business/snowy-becomes-a-monument-to-selfinterest/2006/06/02/1148956541310.html "Reality"):

The Snowy Hydro electric scheme is no more iconic than the Loy Yang power station, the national phone network or even the TABs. In withdrawing it from sale the Government has capitulated to the paranoid and cynical campaigns of vested interests.

As discussed in this column two weeks ago, Snowy Hydro is, in fact, an investment bank - selling derivatives and insurance products to the electricity industry. It is not even really a power company and certainly not an iconic one. The “vast majority” of its revenue, according to the company, comes from investment banking activities, in competition with investment banks.
