---
title: "Speaking Truth to Gittins"
date: "2006-09-23"
categories: ["Economics"]
---

Terry McCrann (sadly, no link, but see the dead tree edition of the *Weekend Australian*) responds to Ross Gittins’ latest [martyrdom operation](../2006/are_australian_economists_really_cowed_by_political_pressure.qmd "martyrdom operation"):

> There is nobody in the media or economic policy and tax circles in any doubt that Costello looks at \[George\] Megalogenis in the same way he would at a rabid dog which had literally bit into his belly.
>
> And that sits in this paper’ broader sustained, coherent and consistent critique of Howard government policy - especially on tax, but more broadly.  If any single paper has got under Costello’s skin - but in a substantive not a snide sniping, Fairfax, way - it is The Australian.  Just think Freedom of Information…
>
> Someone like Gittins is “authorized” to write column after column of bilious personal opinion: essentially, I hate Howard.  Occasionally if unintentionally interrupted by some substantive argument or fact.
>
> And if Howard - in truth, someone in his office - were to respond, up goes the cry, a la this last column: bully-boy, attack on free speech, and really inanely pompous sentences like this one: “One isn’t supposed to write about such behind-the-scenes bullying, of course.”…
>
> Gittins claims that Howard’s “big lie” was his scare campaign over interest rates.  Yet in the very same column he argues that budget surpluses are critical to low rates; and attacks the government for not having bigger surpluses - causing rates to be a “fraction higher than otherwise.”

McCrann is just getting warmed up.  Go get the print edition for more.
