---
title: "Take Out the Black Helicopters and You’ve Got Bill Gross"
date: "2006-06-30"
categories: ["Economics", "Financial Markets"]
---

Caroline Baum’s [Just What I Said](http://www.amazon.com/gp/product/1576602192/ref=ase_institutional-20/103-5440280-5567053?s=books&v=glance&n=283155&tagActionCode=institutional-20 "Just What I Said"), a collection of her Bloomberg columns from the late 1990s through to the early 2000s, contains a chapter on financial market conspiracy theories.  She also reproduces some of the correspondence she received in response to these columns:

> *Do you really believe the US dollar is worth anything?  Print what you want but look in the mirror if you want to see a “truly duped” conspirator!  The black helicopter you hear…it is coming for you Caroline*.

Take out the black helicopter references and you’ve almost got [Bill Gross](../2006/pimcos_bill_gross_the_end_is_nigh.qmd "Bill Gross").

At least some of Baum’s mailbag would appear to be tongue-in-cheek, but you can never be entirely sure:

> *Yes, Caroline, there are black helicopters and the day of pecuniary recompense for the filthy idolaters of usury is at hand.  Right now, even as I type, the reptilian mercenaries from Cygnet 61 and Zeta Reticuli are emerging from their base camps to lay siege to the money houses of Wall Street…Soon, you’ll start to notice iguana-like chalky stool droppings in banks and financial offices all over Wall Street.  That is the sign it’s time to get out of town and head for the nearest subterranean shelter.*
