---
title: "‘Tax Cuts Cause Higher Interest Rates,’ But Government Spending Doesn’t?"
date: "2006-12-21"
categories: ["Economics", "Financial Markets"]
---

Treasurer Costello and Finance Minister Minchin are quick to raise the spectre of higher interest rates whenever the subject of tax cuts comes up and a justification is needed for continued Commonwealth revenue hoarding.  Apparently, the same logic doesn’t apply to new government spending, as [Alan Wood](http://www.theaustralian.news.com.au/story/0,20867,20960720-601,00.html "Alan Wood") notes in relation to the government’s [Mid-Year Economic & Fiscal Outlook](http://www.treasury.gov.au/contentitem.asp?NavId=&ContentID=1214 "Mid-Year Economic & Fiscal Outlook") (MYEFO):

> Peter Costello and Finance Minister Nick Minchin have also been making noises about tightening the reins.
>
> So what about Appendix A of the update, headed “Policy Decisions Taken Since the 2006-07 Budget” - that is, over the past six months.
>
> This runs to more than 130 pages of the 250-page mid-year economic outlook.
>
> And guess what the total spending adds up to over four years - \$17.3 billion.

In fact, with the budget balance as a share of GDP little changed over the projection period, there is little reason to expect Commonwealth fiscal policy to have any impact on interest rates.  This illustrates the point that when revenue collections are coming in much stronger than expected, tax cuts need not be any more stimulatory than the government’s new spending since the Budget.  Yet if the government were to announce \$17 billion in tax cuts, the ‘tax cuts lead to higher interest rates’ brigade would be out in force and the next interest rate increase would almost certainly be blamed on tax cuts.

This strange double standard is partly a product of the prevailing prejudice against people being allowed to spend their own money.  The commentariat are largely of the view that the public are incompetent to spend tax cuts appropriately.  Yet there are good reasons for thinking that a good portion of any tax cuts would go straight to the bottom-line of household balance sheets in the form of debt reduction, rather than being spent.  The government’s much vaunted surpluses are simply displacing private sector saving, leaving national saving unchanged, with no implications for interest rates.
