---
title: "Tax Cuts Don’t Cause Higher Interest Rates: Part IV"
date: "2006-05-17"
categories: ["Economics"]
---

[Alan Wood](http://www.theaustralian.news.com.au/story/0,20867,19158624-31478,00.html "Alan Wood") continues the education campaign:

Why this obsession with interest rates? You could be forgiven for thinking the only role for fiscal policy is to hold them down. John Howard and Costello actually do think this, so they can hardly complain if others view their budgets through the same lens.

In fact, not long ago Costello was fending off calls for tax reform by warning it could drive up interest rates. However, if the RBA does raise rates again, as it may, it won’t be because of the budget. Costello will only have himself to thank if he gets the blame.

If he wants to avoid this fate, the Treasurer would be well advised to stop rushing to hold a press conference every time the RBA puts rates up. It associates him with the decision. He should let the RBA get on with its job and shut up.\
