---
title: "Tax Cuts Don’t Cause Higher Interest Rates: Round-Up the Usual Suspects"
date: "2006-05-09"
categories: ["Economics"]
---

Tonight’s federal budget has the usual suspects (that means you, Chris Richardson) lining-up to tell us that any fiscal stimulus, whether in the form of tax cuts or new spending, will put upward pressure on interest rates.  This would come as news to RBA Governor Macfarlane, who has told the House Economics Committee on at least two occasions that fiscal policy has not been a significant influence on monetary policy in recent years.

What made the government’s claims about interest rates during the last federal election campaign so silly was that the 17% mortgage interest rates of the late 1980s were in fact associated with much larger federal budget surpluses as a share of GDP than we have now.  The 1988-89 underlying cash surplus was 1.8% of GDP.  The best Peter Costello has engineered to date is an estimated 1.1%.

If anything, we would expect strong budget surpluses to be associated with higher interest rates, because both are a reflection of the strength of the economy.  This is correlation, not causation.  As a general rule, the budget balance is a very poor guide to interest rates, both over time and across countries.  The industrialised country with the lowest interest rates in recent years has been Japan, which has also seen the worst fiscal deficits.

Readers are invited to submit entries for the silliest or most overwrought comment and analysis on the budget, either in comments or via email.  A small prize may ensue for the best entry.
