---
title: "Tax Cuts Don’t Cause Higher Interest Rates: Part II"
date: "2006-05-10"
categories: ["Economics"]
---

Updating the numbers from the previous post, the 1988-89 and 1989-90 underlying cash surpluses are now both put at 1.7% of GDP, compared to an estimated 1.5% of GDP for 2005-06.  The high interest rates of the late 1980s were thus associated with the strongest budget surpluses as a share of GDP since 1973-74 and still stronger than any Peter Costello has delivered. 

The budget surplus falls to 1.1% of GDP in 2006-07 and is essentially unchanged after that, yielding a fiscal impulse from the budget of 0.4% of GDP.

[Alan Wood](http://www.theaustralian.news.com.au/story/0,20867,19086589-601,00.html "Alan Wood") gets it:

wouldn’t all this tax cutting and spending force the Reserve Bank to put up interest rates again?

The answer is an unequivocal no. Why not? Because what matters to our central bankers, as Governor Ian Macfarlane has explained ad nauseam, is the budget bottom line…

As a per cent of GDP the size of the surplus is forecast to be 1.5 per cent in 2005/06 and 1.1 per cent in 2006/07.

This implies a stimulatory change, using the Macfarlane rule of thumb, of 0.4 per cent of GDP—too small to be even a blip on the RBA’s radar screen.

And, if the experience of Costello budgets is a guide, the forecast surplus of \$10.8 billion for 2006-07 will turn out to be a substantial underestimate.

In other words, the actual swing in the surplus is more likely to be mildly contractionary, rather than mildly expansionary.

[Ross the Wowser](http://www.smh.com.au/news/budget-2006/an-embarrassment-of-riches/2006/05/09/1146940549459.html?page=2 "Ross the Wowser") doesn’t:

it’s by spending our tax cuts that we risk adding to inflation pressure and making the Reserve Bank want to raise rates further.

It’s likely that part of the reason for last week’s increase was the Reserve’s knowledge that a tax cut was coming, but I doubt it was expecting anything half as big as what we got. We now have budgetary policy and interest-rate policy pulling in opposite directions - not a recipe calculated to minimise the risk of further rate rises.

Somehow, I don’t think Peter Costello is too worried on that score.  And since Ross thinks money makes you unhappy anyway, why would he care?
