---
title: "The Doomsday Cult Comes to Reno"
date: "2006-01-25"
categories: ["Economics"]
---

[Warren Buffett](http://www.forbes.com/entrepreneurs/feeds/ap/2006/01/18/ap2456947.html "Warren Buffett") is sounding more and more ridiculous:

*“Right now, the rest of the world owns \$3 trillion more of us than we own of them,” Buffett told business students and faculty Tuesday at the University of Nevada, Reno. “In my view, it will create political turmoil at some point. ... Pretty soon, I think there will be a big adjustment,” he said without elaborating.*

One of the difficulties confronting the doomsday cult is that it requires a vivid imagination like Buffett’s to construct plausible scenarios that would give rise to serious concern about external imbalances, at least for countries with floating exchange rates.  Their worst case scenario - a ‘disorderly’ adjustment in foreign exchange markets - is something the doomsday cult should in fact welcome, since it is the shortest and most painless route to reducing imbalances.  It makes no sense to worry about the supposed disease as well as the cure.  One of the main advantages of having a floating exchange rate is that it insulates the domestic economy against external shocks.  It is far preferable to wear any adjustment to external imbalances on the exchange rate than on domestic growth.
