---
title: "The AEI’s Bretton Woods Revivalist"
date: "2006-03-21"
categories: ["Economics"]
---

[Desmond Lachman](http://www.aei.org/publications/filter.all,pubID.24077/pub_detail.asp "Desmond Lachman") continues to trash the AEI’s free market credentials:

*If ever over the past sixty years the global economy needed an IMF to effectively discharge its original mandate of helping to safeguard the international exchange system, it has to be now at a time of such large and disturbing global economic imbalances.\*
\
There was a time when conservative think-tanks criticised the IMF as a redundant institution in the post-Bretton Woods era.  The IMF’s former role in helping countries with the balance of payments problems that emerged under fixed exchange rate regimes was no longer needed once the industrialised world moved to a system of floating exchange rates and open capital accounts.  Problems have remained in emerging market economies with fixed exchange rate regimes, but even there, the IMF has played a less than constructive role, as Lachman himself notes.  Indeed, reserve asset accumulation on the part of East Asian central banks is partly driven by their view that IMF intervention in the East Asian financial crisis of 1997-98 was a failure.

The argument for doing away with the IMF is compelling, yet growing global ‘imbalances’ have many people arguing for a revival of Bretton Woods era institutions.  This is ironic, since it was only under the Bretton Woods system that global imbalances were a serious problem.  It is even more ironic that these calls now come from conservative think-tanks.  It demonstrates that even they fail to comprehend the free market case for taking a benign view of global imbalances.

Lachman’s argument that global imbalances promote protectionism is quite ridiculous.  It is in fact those who fret about global imbalances who are doing the most to promote protectionist sentiment, by promoting the view that these imbalances are somehow a problem requiring a solution.
