---
title: "The House Price Bust that Wasn’t"
date: "2006-08-24"
categories: ["Economics"]
---

Remember those 20-30% declines in house prices that were meant to have thrown Australia into recession by now?  Neither do I.  The [ABS median established house price index](http://www.abs.gov.au/AUSSTATS/abs@.nsf/Lookup/6416.0Main+Features1Jun%202006?OpenDocument "ABS median established house price index") rose 3.1% q/q and 6.4% y/y for the June quarter, based on a weighted average of capital cities.  The weighted average once again concealed considerable variation between capital cities, ranging from a 0.5% y/y decline in Sydney to a 35.4% y/y increase in Perth. 

The ABS has been doing a lot of work trying to improve the quality of its data on house prices, partly in response to RBA demands for a more timely series that is less prone to compositional distortions.  The latest data suggest that the trough in the weighted average of capital city house prices was seen in the March quarter of 2005, when house prices were essentially flat compared to the March quarter 2004.  This coincided with the peak decline in Sydney house prices of -5.9% y/y.  This was enough for [Robert Shiller](../2005/robert_shiller_on_australias_house_price_bubble.qmd "Robert Shiller") to pronounce that Australia had suffered a burst housing ‘bubble,’ yet with the exception of Sydney and Canberra, none of the other capital cities recorded a decline in nominal house prices at an annual rate.  Melbourne got down to +0.4% y/y at the end of 2004, one quarter ahead of the Sydney trough.  Cities like Perth never even managed a decline over a quarter, much less a year.

The upswing in global commodity prices that began in 2002 explains much of this regional variation, adding to incomes in the resource-rich states and driving the inter-state migration flows that the RBA has identified as an important source of weakness in Sydney house prices, which have now largely converged back to the same ratio to other capital cities seen in the early 1990s.  While many people have argued that, but for the commodities boom, the rest of Australia would look like Sydney, it is more plausible to argue that Sydney is only as weak as it is because the commodities boom has drawn people away from Australia’s largest city.  What many analysts saw as a prospective national house price bust emanating from Sydney that would wreck the Australian economy was in fact just one aspect of an exogenous commodity price boom that has been anything but harmful.
