---
title: "The IMF & Global Imbalances"
date: "2006-04-27"
categories: ["Economics"]
---

The [WSJ](http://online.wsj.com/article/SB114610012701937139.html?mod=opinion_main_review_and_outlooks "WSJ") editorialises on the IMF’s on-going fight against its own redundancy in a world of floating exchange rates and international capital mobility:

These are grim times at the International Monetary Fund; the world economy is too good. Global GDP has expanded by nearly 5% over the past three years, capital and trade are reaching far corners of the earth, and millions of the world’s poor are being lifted out of poverty. So naturally the IMF is worried.

That’s the backdrop of the weekend agreement in which the world’s developed nations agreed to give the Fund the task of lobbying to correct “global imbalances.” The idea is that the world’s trade and capital flows are out of whack, and are thus a grave threat to all of this prosperity. What the world needs now, said IMF Managing Director Rodrigo Rato, is “coordinated action” to unwind these “imbalances.” And who better to lead it but the Fund, through “multilateral surveillance” of problem countries.

There are few things more dangerous than a global bureaucracy looking to fix something that isn’t broken. Trade and capital flows are a function of millions of private decisions, so it’s far from clear that “imbalances” need addressing. Yes, the U.S. is importing huge amounts of capital and traded goods. But this is in part because the U.S. economy is growing so well, while Europe’s big three—Germany, France and Italy—are dead in the water. If Mr. Rato wants to roll a boulder up a hill, how about lobbying those countries to shape up?
