---
title: "The ‘October Surprise’ that Wasn’t"
date: "2006-12-01"
categories: ["Economics"]
---

More of what Nouriel Roubini won’t tell you about the US economy, from my associates at [Action Economics](http://www.actioneconomics.com "Action Economics"):

> The U.S. Q3 GDP revision to 2.2% from 1.6% reflected all the component revisions that were expected, but an over-sized bump to inventories and trade, and a bonus upward revision to consumption of services. The revision eliminated the “1-handle,” and will go a long way toward marginalizing the market’s recession fears given the more optimistic spending trajectory as we enter Q4.
>
> The service consumption boost will help close the income/spending gap through October, as will downward Q2 income revisions in this report. The mix leaves a more persistent and seemingly bullet-proof broad down-trend in the saving rate, despite the price-impacted “pop” we should see in the October personal income data tomorrow. The combination will reinforce our forecast of a robust outlook for Q4 consumer spending, and considerable upside risk to the consumption reports over the November-January period as the savings rate moves back toward trend.
>
> We continue to expect a 2.6% GDP growth rate in Q4, and a 3% rate by Q1, as the growth undershoot of the middle quarters of 2006 scrolls by, and is replaced with trend-growth in the 3%-3.5% area.  Indeed, we see upside risk to these estimates despite the market’s focus on signs that downside risks are emerging.
