---
title: "The Vastly Overrated G20"
date: "2006-11-11"
categories: ["Economics"]
---

The G20 meets in Melbourne next week and the Treasury has been busy telling us how important its work is (a line faithfully regurgitated by [Ross Gittins](http://www.smh.com.au/news/business/g20-attracts-top-four-bankers/2006/11/10/1162661896744.html "Ross Gittins") today).  While the G20 is undoubtedly good for the self-importance of Treasury and the Treasurer, the [list of apologies](http://www.smh.com.au/news/business/g20-attracts-top-four-bankers/2006/11/10/1162661896744.html "list of apologies") attests to its real significance:

> The Bush Administration’s glamour appointee, Henry “Hank” Paulson, who was poached this year from Goldman Sachs to head the US Treasury, has been grounded to focus on domestic economic challenges in the wake of the Republican Congressional elections debacle.
>
> The British Chancellor of the Exchequer, Gordon Brown, will also stay home to prepare for next week’s Queen’s Speech…
>
> And the well-regarded Governor of the Bank of England, Mervyn King, has a personal commitment.

Walking the dog perhaps.\

UPDATE: Treasurer Costello [explains](http://www.abc.net.au/insiders/content/2006/s1786567.htm "explains") the significance of the G20 to Barrie Cassidy:

> BARRIE CASSIDY: All right. Let’s move on to the G20 now and its involvement next weekend under your chairmanship. 90 per cent of the world’s economies under one roof, but could you identify one key result you would like to see emerge from the conference?
>
> PETER COSTELLO: First of all, let’s say, Barrie, this is the biggest financial conference Australia has ever hosted and ever will. This organisation, where Australia not only has a seat at the table, of the 20 most important economies of the world, but is chairing it, that brings together the developed world and the developing world, **is important in itself. That’s significant in itself.**

So now you know.  Costello then goes on to talk about what sounds like international price fixing of world commodity markets:

> *If we can get an agreement on adequate supply, adequate security, proper international pricing, then I think we can actually ensure that what could otherwise become jostling and instability over resources over the next couple of decades will be taken out of the system. Prices would be better and that will benefit consumers.*

The sort of ‘agreement’ we could well do without.
