---
title: "The US Dollar: Cyclical versus Structural"
date: "2006-12-05"
categories: ["Economics", "Financial Markets"]
---

[Stephen Jen](http://www.morganstanley.com/views/gef/index.html "Stephen Jen"), on why it’s dangerous to write-off the USD:

> For two-and-a-half years, I have strenuously warned investors not to under-estimate the dollar.  The current dollar sell-off is, to me, a cyclical, not structural development.  The dollar index is fairly valued, and financial globalization should keep the US external imbalance well-financed.  Many investors worry about wholesale central bank diversification.  I am more skeptical: it is still hard to find good liquidity in markets outside major economies.  Even compared to Euroland, the US offers much larger risky asset markets.  Also, if central banks really have begun to diversify out of USD assets, there should be traces of this in US bond markets. 
>
> On the cyclical front, the US is likely to go through several quarters of sub-potential (i.e., sub-3.0%) growth.  What this means is that the unemployment rate is likely to rise in the period ahead, which is likely to be another negative for the dollar.  But I believe that the Fed is right that the US economy will eventually re-assert itself, most likely in the second half of 2007:  I keep reminding myself that, since 2002, the Fed has had the best record of anyone at forecasting US growth.
