---
title: "The Ultimate in ‘Downshifting’"
date: "2006-02-18"
categories: ["Economics"]
---

Proving that you can make anything fashionable in the name of environmental awareness, the neo-socialist Australia Institute identifies [the latest in inner-city environmental trends](http://smh.com.au/news/national/skip-dippin-away-how-the-bin-became-a-convenience-store/2006/02/17/1140151818747.html "the latest in inner-city environmental trends"), ‘skip-dipping:’

IT IS supposed to be the domain of the destitute and desperate, but scavenging through other people’s rubbish is emerging as a favourite pastime of well-heeled city dwellers.

Research by the Australia Institute suggests the practice of searching through bins for unused food, clothing and household goods, known as “skip dipping”, is becoming popular among well-educated professionals sick of contributing to increasing landfill.

Interviews by the Australia Institute conducted between December and February revealed that people of all ages and from all walks of life, including computer programmers, designers, public servants and retirees, do their shopping in other people’s bins.

Scavenging through other people’s garbage is a logical extension of the ‘downshifting’ to a less affluent lifestyle favoured by the Australia Institute.  Indeed, if the Institute were ever to get its way, many more people could look forward to living out of garbage bins, although more out of necessity than environmental awareness. 

(via [Catallaxy](http://badanalysis.com/catallaxy/?p=1562 "Catallaxy"))
