---
title: "The Dr Strangelove of Global Macro"
date: "2006-07-29"
categories: ["Economics", "Financial Markets"]
---

It doesn’t take much to get Nouriel Roubini excited these days.  US Q2 GDP falls short of expectations, and [Nouriel starts salivating](http://www.rgemonitor.com/blog/roubini/138387 "Nouriel starts salivating") over the prospect that the cycle might finally validate his years of perverse doom-mongering:

> *this Q2 GDP report is as bad as it could be. I thus stick with my prediction that, by Q4, the growth rate will be close to zero and by early 2007 the U.S. will be in a recession. Panglossian optimists have been proven wrong again. They’d better start adjusting their wishful-thinking forecasts of H2 growth (still close to a 3% consensus) to a reality of an economy rapidly slipping into an \[sic\] nasty recession.*

Nouriel is nothing if not thorough in his bearishness.  If Nouriel is to be believed, not a single asset class or region will be spared:

> In 2006 cash is king and all risky assets (equities, EM bonds, currencies and equities, commodities, credit risks and premia) will be battered once the markets finally comes \[sic\] to the realization that a U.S. recession followed by a serious global slowdown is coming.
>
> Finally the other delusion in the market is that, even if the U.S. were to slow down, the rest of the world (EU, Asia, China, Japan, Emerging Markets) will be able to “decouple” from the U.S. slowdown and keep on growing perkily…quite simply, when the U.S. sneezes the rest of the world gets the cold.  The decoupling fairy tale will be proven as wrong as the U.S. soft landing Panglossian fairy tale.

So Nouriel pretty much has all bases covered for anything that might go wrong anywhere in the world for the foreseeable future.
