---
title: "The Deputy-less Reserve Bank"
date: "2006-11-15"
categories: ["Economics", "Financial Markets"]
---

It seems Treasurer Costello has been so busy solving the world’s problems at the G20, he has [neglected his portfolio responsibilities](http://www.smh.com.au/news/business/governor-navigates-storm-alone/2006/11/14/1163266549762.html "neglected his portfolio responsibilities"):

> TREASURER Peter Costello is in no hurry to appoint a deputy to the Reserve Bank’s governor, Glenn Stevens.  With the delay now stretching into its ninth week, Mr Costello told the Herald he “may” fill the position by Christmas…
>
> Yet the Reserve Bank Act empowers only a deputy governor to run the bank in the governor’s absence - raising questions about who could make crucial decisions if a financial shock hit while Mr Stevens was on a plane or otherwise uncontactable.
>
> When asked whether he has a shortlist of candidates, Mr Costello said: “When I’ve got some news for you I’ll let you know.”
>
> Asked whether the position would be filled by Christmas, he said: “It may be, yep.”
>
> The position has been vacant since September, but the vacancy has been expected since July 2003, when the former governor, Ian Macfarlane, was appointed for a shortened second term.
>
> A recruitment firm engaged by Mr Costello was making initial contacts with potential candidates in September.
>
> Observers speculated that Mr Costello does not see the appointment as a priority.
>
> Mr Costello is also yet to fill a board vacancy that has been open since December.
>
> The bank’s separate payments system board has had a seat unfilled since its creation in 1998 - and two vacancies since July.

[The Australian](../2006/the_wheels_of_government_turn_slow.qmd "The Australian") recently highlighted last minute re-appointment of Warwick McKibbin to the RBA Board in July.

The government’s Mid-Year Economic and Fiscal Outlook will be released in coming weeks, but as usual, the government will not commit to a release date and time.  The MYEFO is usually flung out at the Treasurer’s convenience, sometimes with as little as a few hours notice, yet the Treasury likes to lecture the rest of the world on transparency.
