---
title: "The Wheels of Government Turn Slow"
date: "2006-09-20"
categories: ["Economics"]
---

[News Ltd](http://www.theaustralian.news.com.au/story/0,20867,20442596-25090,00.html "News Ltd") maintains its scrutiny of the Reserve Bank by way of FoI legislation:

> *GREAT to see the due process that goes into appointing the people who set our interest rates. While Glenn Stevens took over this week from Ian Macfarlane as governor of the Reserve Bank, an appointment properly trumpeted several weeks ago, there was no such announcement about the future of board member Warwick McKibbin, whose five-year term was to end on July 30. As business closed on Friday, July 28, there was still no official announcement about his future, which was a bit of a concern as board members are usually sent the board papers by secure courier the Friday\* before a Tuesday meeting. So, with no official announcement, did the bank send McKibbin the papers for the meeting on August 1? A Freedom of Information request to the bank has revealed that they did, but only after a third “oral reassurance” from Treasury that McKibbin was staying in his job. RBA secretary David Emmanuel was told by Treasury on July 19 that the re-appointment had been cleared but Treasurer Peter Costello had yet to sign the letter. By Thursday, July 27, Treasury told the bank the Treasurer had signed off and the announcement would be made on Friday. It wasn’t, but Treasury still advised that it was all legal and would go ahead. McKibbin got his papers, the board met and increased interest rates. Phew.*

\* \[actually Thursday, if memory serves - ed\]
