---
title: "The Dr Strangelove of Global Macro, Part II"
date: "2006-08-06"
categories: ["Economics", "Financial Markets"]
---

Nouriel Roubini has engaged in a furious linking frenzy over at [Doomsday Cult Central](http://www.rgemonitor.com/blog/roubini/139147 "Doomsday Cult Central") in support of his US recession call.  Nouriel seems oblivious to the paradox that makes recession forecasting so difficult.  Recessions are inherently difficult to predict, because if they could be forecast with reasonably accuracy, policymakers would take action to avert them and the public would change their behaviour in ways that would mitigate their effects.  The news and data flow that Nouriel points to in support of his recession call is the same information that the Fed will be responding to when it (more than likely) decides to pause its tightening cycle in August.  Nouriel now acknowledges this possibility in his [latest post](http://www.rgemonitor.com/blog/roubini/139556 "latest post"), but argues that a new Fed easing cycle will be too little, too late to avert recession.

All this conveniently ignores the fact that Nouriel has been prominent in arguing that monetary policy should respond to asset price ‘bubbles,’ particularly the supposed US housing ‘bubble.’ If the Fed had taken Nouriel’s advice, US interest rates would presumably be even higher than they are now, greatly increasing the risk of the recession Nouriel claims is now imminent.  Indeed, the central bank that has most explicitly targeted house prices in its official explanation of policy, the Reserve Bank of New Zealand, had a narrow brush with recession in the second half of 2005.

Nouriel is not alone in trying to have his monetary policy cake and eat it too.  Even conservative commentators who should know better, like [Des Lachman of the AEI](http://www.aei.org/publications/filter.all,pubID.24734/pub_detail.asp "Des Lachman of the AEI"), have sought to argue that the Fed *both* failed to ease quickly enough in the wake of the tech ‘bubble’ and then eased *too* much to prevent the housing ‘bubble.’  Lachman and Roubini are effectively claiming that they know of some alternative path for Fed policy that would have better smoothed both asset prices and the real economy, leading to better macro outcomes.  This is nothing but after the fact hubris.  [Adam Posen](http://www.iie.com/publications/wp/wp06-1.pdf "Adam Posen") has presented a definitive debunking of Nouriel’s arguments in favour of central banks targeting asset prices.  I make similar arguments [here](http://www.institutional-economics.com/index.php/section/reviews/bubble_man_alan_greenspan_the_missing_7_trillion_dollars_by_peter_hartcher "here") against those who argue that the Fed could and should have prevented the US tech ‘bubble’ of the late 1990s.

Nouriel was spectacularly wrong in his structural bear call on the US dollar in 2005, not because the USD failed to collapse as he predicted, but because even if it had, it would have had none of the consequences he predicted (remember that this too was meant to have caused a recession!)  It is not enough simply to be a permabear and then wait for the cycle to finally deliver vindication.  You have to be right for the right reasons.
