---
title: "The G20’s Dubious Achievements"
date: "2006-11-14"
categories: ["Economics"]
---

Given the chance to impress us with the G20’s achievements, [Treasurer Peter Costello](http://www.theaustralian.news.com.au/story/0,20867,20751361-7583,00.html "Treasurer Peter Costello") can name but two:

> *The G-20’s breakthrough commitment to new higher standards of transparency to prevent harmful tax practices in 2004 is an example of this, as is the significant IMF quota and governance reforms achieved this year under Australia’s stewardship.*

‘Harmful tax practices’ is OECD-speak for tax competition.  See [David Burton’s](http://www.cis.org.au/POLICY/summer02-03/polsumm0203-2.htm "David Burton’s") discussion of the OECD’s efforts to cartelise the international tax system, about which Peter Costello is so enthusiastic.  The Treasurer might have been better served paying more attention to the tax practices of former RBA Board member Bob Gerard.  The current Australian government is normally more dismissive of multilateralism, but the Treasurer is clearly the victim of bureaucratic capture when it comes to the G20.
