---
title: "The Failure of Multilateralism"
date: "2006-07-29"
categories: ["Economics"]
---

[Clive Crook](http://nationaljournal.com/crook.htm "Clive Crook") on the failure of the Doha Round:

> The saddest part is that the process itself is no longer mitigating that problem but compounding it. The World Trade Organization and its precursor, the General Agreement on Tariffs and Trade, were designed as a forum in which governments could demonstrate to their electorates that trade liberalization was a win-win game. Rather than convincing voters that lowering their own tariffs is good for them (as it is), the process relied on showing that other countries would lower their tariffs as well. The model was based on an exchange of “concessions”—trade reform as shared sacrifice. It was intellectually dishonest but, undeniably, it worked. In the decades after 1945, the world moved from comprehensively managed trade to a more liberal trading order, with fabulous economic results.
>
> Big exceptions remained—notably agriculture, ever the sticking point—but nobody was complaining. The system was apt to wobble from time to time, as you might expect, because it was based on a lie. But for a good few decades it effectively mobilized export interests against groups demanding protection, and the politics worked.
>
> Progress was slowing even before the Doha Round. But this week the “exchange of concessions” model finally fell in on itself. The WTO process is no longer assisting liberalization. It is blocking it and, worse, legitimizing the failure. The world has settled for less-than-liberal trade. It is a multitrillion-dollar error; a crime, truly, against the world’s poor; and, it seems, a story barely worth reporting.
