---
title: "‘These Western People Didn’t Know What They Were Talking About’"
date: "2006-10-06"
categories: ["Economics", "Financial Markets"]
---

A [Bloomberg](http://www.bloomberg.com/apps/news?pid=20601087&sid=aK7UIXigIxjM&refer=worldwide_news "Bloomberg") story hints that the recent departure of Morgan Stanley Sinophile and ‘bubble’ drone Andy Xie may have had something to do with an internal email he wrote attacking Singapore as the host of the recent IMF and World Bank annual meetings.  According to Bloomberg:

> He questioned why Singapore was chosen to host the conference and said delegates “were competing with each other to praise Singapore as the success story of globalization.”
>
> “Actually, Singapore’s success came mostly from being the money laundering center for corrupt Indonesian businessmen and government officials,” said Xie, who was based in Hong Kong before leaving Morgan Stanley on Sept. 29. “Indonesia has no money. So Singapore isn’t doing well.”…
>
> “I tried to find out why Singapore was chosen to host the conference,” Xie wrote in the e-mail. “Nobody knew. Some said that probably no one else wanted it. Some guessed that Singapore did a good selling job. I thought it was a strange choice because Singapore was so far from any action or the hot topic of China and India. Mumbai or Shanghai would be a lot more appropriate.”
>
> At a dinner party hosted by Singapore Prime Minister Lee Hsien Loong, “people fawned him like a prince,” Xie wrote. “These Western people didn’t know what they were talking about,” he wrote.

One could say the same about Andy.
