---
title: "Will Universities Australia be more effective than the AVCC?"
date: "2006-09-05"
categories: ["Higher Education"]
---

At a meeting yesterday, the Australian Vice-Chancellors’ Committee [agreed to change their structure](http://www.theaustralian.news.com.au/story/0,20867,20354920-12332,00.html "Australian report") and rebrand themselves as ‘Universities Australia’. This followed a [highly critical review](http://www.avcc.edu.au/content.asp?page=/news/media_releases/2006/avcc_media_33_06.htm) released last month.

From a public choice perspective, higher education interest groups have always been rather unusual. As [I argued](http://www.ipa.org.au/files/Review52-4%20The%20topsy%20turvy%20world.pdf#search=%22topsy%20turvy%20higher%20education%22) some years ago, they are among very few interest groups to campaign against their own financial interests by supporting restrictions on their fee-charging capacity. That’s a less common view today than when I wrote - somewhat reluctantly, they did agree to 25% increases in student charges back in 2003 - but it is still widely held. This is only partly conventional egalitarian concerns about student access. Rather, it is concern about inequality in Australian society as a whole, which they believe would be exacerbated by some universities becoming more ‘elite’ than they are today on the strength of high student fees. That’s why every public university is quite happy to enrol thousands of full-fee overseas students, but in many cases refuse to offer full-fee places to local students and suffer ideological angst when they do. The overseas students go home without changing Australia’s social structures.

Because these ideological hang-ups are still so prevalent, Universities Australia probably won’t be much more successful than the Australian Vice-Chancellors’ Committee. The central agencies wonder why they should spend taxpayer dollars on institutions that are so reluctant to take financial responsibility for themselves. Politicians wonder why they should spend money on institutions that rank lowly in the public’s spending priorities, and where the highest praise they are likely to get for spending initiatives is ‘a good start’. A new name, a new structure, and more effective lobbying methods are all part of what universities need in Canberra, but until they change their message they are never likely to remedy their serious financial problems.
