---
title: "US versus UK Housing and the Housing-Consumption Nexus"
date: "2006-09-30"
categories: ["Economics"]
---

[David Miles and Melanie Baker](http://www.morganstanley.com/GEFdata/digests/latest-digest.html#anchor3 "David Miles and Melanie Baker") discuss the differences between the US and UK housing markets, suggesting that only so much can be inferred from the UK experience for the US.  While there are structural differences between the UK, Australian and NZ housing markets and their financing, I don’t think these differences make a compelling argument that the cyclical implications of housing weakness in the US will differ substantially from the generally benign experience of the rest of the Anglo-American world.  Indeed, Miles and Baker share my view that the nexus between housing and consumption that Dr Strangelove (aka Nouriel Roubini) relies on for his US recession call is not as strong as conventionally assumed:

> one should be sceptical on the strength of the link between housing markets and consumer spending.  Although we agree that there is a degree of linkage (e.g., through changes in housing market activity driving purchases of certain types of household goods and through changes in the available collateral for household borrowing — home equity withdrawal is more than 5% of disposable income in both the US and the UK), this linkage is probably variable over time and may not even be especially strong. 
>
> Three points are significant: 1) just because house price movements and consumer spending movements may be correlated, this does not imply a causal relationship between them.  An observed correlation may simply reflect movement in other factors which affect both house prices and consumer spending, e.g., interest rates, labour market fundamentals and income expectations; 2) Just because housing constitutes the largest part of household wealth (at around 54% in the UK once pension and life insurance assets are included), it does not follow that the value of housing has a very strong influence on consumer spending.  Housing is not like other types of wealth.  Most people live in the house that they own.  If an owner is preparing to trade up, i.e., move to a bigger house (as many throughout the housing market are), then national house price rises do not make that household better off; 3). Those who trade down may gain from house price rises and those who trade up lose; these winners and losers should largely cancel each other out across the aggregate economy.
