---
title: "Warren Buffett’s Expensive Convictions"
date: "2006-03-06"
categories: ["Economics"]
---

[Warren Buffett](http://www.berkshirehathaway.com/letters/2005ltr.pdf "Warren Buffett"), on the high price of his doomsday cultism:

*My views on America’s long-term problem in respect to trade imbalances, which I have laid out in previous reports, remain unchanged. My conviction, however, cost Berkshire \$955 million pre-tax in 2005.\*
\
Buffett is seeking supposedly less costly ways of shorting the US dollar, via apparently unhedged acquisitions of foreign equity capital:

*We reduced our direct position in currencies somewhat during 2005. We partially offset this\
change, however, by purchasing equities whose prices are denominated in a variety of foreign currencies and that earn a large part of their profits internationally. Charlie and I prefer this method of acquiring nondollar exposure. That’s largely because of changes in interest rates: As U.S. rates have risen relative to those of the rest of the world, holding most foreign currencies now involves a significant negative “carry.”  The carry aspect of our direct currency position indeed cost us money in 2005 and is likely to do so again in 2006. In contrast, the ownership of foreign equities is likely, over time, to create a positive carry – perhaps a substantial one.*

...and turning equity bets into currency plays.
