---
title: "What China Really Does with its Foreign Exchange Reserves"
date: "2006-08-29"
categories: ["Economics", "Financial Markets"]
---

> [SHANGHAI, Aug 29 (Reuters)](http://today.reuters.com/news/articlebusiness.aspx?type=tnBusinessNews&storyID=nHKG214198&imageid=&cap=&from=business "SHANGHAI, Aug 29 (Reuters)") - Beijing is expected to inject a large amount of capital into China Reinsurance (Group) Co., the country’s biggest reinsurer, to help it compete with foreign rivals, sources close to the situation said on Tuesday.
>
> Central Huijin, the investment arm of the central bank, has submitted a proposal for the capital injection to the State Council, China’s cabinet. The plan could win approval before the end of this year, the sources said.
>
> After approval, the central bank and China’s foreign exchange regulator would authorise Central Huijin to use part of the country’s more than \$940 billion in foreign exchange reserves as capital for China Reinsurance, the sources said.
>
> The size of the proposed injection is unclear, but one financial source close to the State Council said it was unlikely to exceed 10 billion yuan (\$1.25 billion).
