---
title: "What Kind of Bird is That?"
date: "2006-06-11"
categories: ["Economics"]
---

Bird-watching with [James Hamilton](http://www.econbrowser.com/archives/2006/06/hawk_or_dove.html "James Hamilton"):

What does Bernanke really believe? Well, for starters, that:

“the evidence of recent decades, both from the United States and other countries, supports the conclusion that an environment of price stability promotes maximum sustainable growth in employment and output and a more stable real economy.”

That’s what he believes, that’s what he’s going to do, and you can take that to the bank. If that makes him a “hawk” in your book, so be it. But he also has no desire to plunge the U.S. unnecessarily into a recession. So then he’s really a “dove”? Then the limitation is in the vocabulary with which you’re determined to describe him, not in the quality or consistency of his ideas.

Some people find that level of complexity unsettling. But personally, I prefer to have the U.S. Federal Reserve run by a human rather than a bird.
