---
title: "What Nouriel Roubini Won’t Tell You About the US Economy, Part II"
date: "2006-08-23"
categories: ["Economics", "Financial Markets"]
---

More of the stuff that hits the cutting room floor at [Doomsday Cult Central](http://www.rgemonitor.com "Doomsday Cult Central"), from my associates at [Action Economics](http://www.actioneconomics.com "Action Economics"):

> A surprising array of major U.S. macro indicators continue to defy expectations of a slowdown, beyond pocketed weakness in the housing. Indeed, even here, construction activity remains solid despite housing due to robust business and public sector growth. Consumers are spending, factories are humming, profits are booming, and trade is turning the corner. Even the labor market clearly remains tight, despite the seemingly meaningful yet notably isolated restraint in monthly payroll growth.
>
> The most important discrepancy between expectations and outcomes has come from the consumer, where nearly all economists projected some pull-back this year, even though spending strength has remained unwavering. As is evident below, nominal consumer spending growth was solid in both Q1 and Q2, and has actually gained steam in Q3. The “real” spending figures were hit in Q2 from soaring gasoline prices, but the hit was temporary. Since consumption accounts for 2/3rds of GDP, this steady growth is providing an important driver of economic growth.
