---
title: "What Nouriel Roubini Will Not Tell You about the US Economy"
date: "2006-08-12"
categories: ["Economics", "Financial Markets"]
---

My associates at [Action Economics](http://www.actioneconomics.com "Action Economics") take on the emerging bearish consensus:

> Despite the market’s nearly uniform belief that a significant economic “slowdown” is underway, today’s retail sales, trade price, and inventory data join our reference yesterday to the litany of indicators that are refusing to cooperate with the consensus view.
>
> For the record, we are seeing virtually no signs of a slowdown in consumer spending as we enter the second month of Q3, As gauged by today’s retail sales report as well as nearly all the consumer confidence and income statistics. The surge in July tax receipts revealed late yesterday, combined with the solid growth trajectory of hours-worked through the month from last Friday’s payroll report, ensures that income posted another round of solid growth on the month.
>
> In addition, all the major factory sector indicators suggest continued solid growth in this bellwether sector, and industrial production to be released next Wednesday will reveal a big 0.6% July gain that follows the even bigger 0.8% June increase.  In addition, as noted yesterday, both exports and imports entered Q3 on a robust growth path as signaled in the June trade report. And, the construction sector is continuing to post solid growth despite housing sector fears thanks to a booming commercial and public sector, as signaled by continued strength in building material prices, alongside steady 9%-13% y/y growth in sales of building materials that received a big boost from the 1.8% July sales surge. Inventories posted solid gains through Q2, though the ratio of inventories to sales remains remarkably lean.
>
> We continue to believe that economic growth is moderating in these middle years of the expansion by about 0.5 percentage points, from a 3.7% clip over the last thirteen quarters to about a 3.2% rate, as Fed policy moves to neutral from accommodative. But this slowdown in real growth will be hard to see in many of the volatile monthly reports that the markets watch, and larger price gains in the second half of the expansion may diminish the effects of this moderation on the reports that are not inflation adjusted, like retail sales, or inventories.
>
> For today’s data, note that retail sales grew at a solid 7.6% rate in Q2 despite a market focus on the “draining” effect of surging gasoline prices on the “real” spending component in the last quarter, which is an “above trend” growth clip despite notions in the market that the slowdown began with the consumer in Q2.  In Q3, retail sales are on track to grow at a 7% rate, and with less of the gasoline “drain” on the real figures that will leave real consumption growing at a 3.3% Q3 rate that is right in line with our 3.0% Q3 GDP forecast.
