---
title: "While I Was Away"
date: "2006-04-27"
categories: ["Economics"]
---

I have only recently returned from a few weeks in Europe.  Thanks to all those who made it such an enjoyable trip.  It was good to meet with some IE readers for the first time and to get some great first-hand insights into the UK and European economies.  There was considerable interest in Australia’s experience with the housing cycle and other developments in the dollar bloc periphery.

While I was away, Treasurer Costello used the Hendy-Warburton [report](http://comparativetaxation.treasury.gov.au/content/report/executive_summary.asp "report") to remind us how wonderful the Australian taxation system is in comparison with the rest of the OECD.  Having just visited some of the other OECD countries in question, I’m even more unmoved than usual by such lame comparisons. 

The Treasurer’s accompanying [press release](http://www.treasurer.gov.au/tsr/content/pressreleases/2006/021.asp "press release") noted that “The Report will stand as a significant reference point to assist in framing policy to improve taxation policy.”  Yet the press release does not explicitly identify a single area in which Australian tax policy might actually be lacking.
