---
title: "Why Aren’t More Japanese Officials in Jail?"
date: "2006-03-10"
categories: ["Economics"]
---

Yesterday’s announcement of the termination of quantitative easing by the Bank of Japan was pre-empted by Japan’s publicly-funded broadcaster, NHK, by some 45 minutes. 

Leaks in relation to BoJ policy are hardly unprecedented.  Part of the rationale for the adoption of a two-day meeting format several years ago was to prevent leaks, by holding the policy discussion without a break on the second day.  Since yesterday’s meeting ran longer than usual, I’m guessing that there was a break during which the policy discussion was leaked, most likely by the government representatives on the policy board, or their subordinates, rather than the policy board members themselves.

In any event, such leaks are damaging to the credibility of the BoJ and the integrity of Japanese monetary policy and financial markets.  In any other country, such indiscretions in relation to official and market sensitive information would be viewed as a serious criminal offence.
