---
title: "Why Glenn Stevens Will Enjoy a Smoother Transition than Ben Bernanke"
date: "2006-07-08"
categories: ["Economics", "Financial Markets"]
---

Ian Macfarlane’s current three year term as RBA Governor ends in September.  The SMH [profiles](http://www.smh.com.au/news/business/your-house-in-his-hands/2006/07/07/1152240492832.html?page=fullpage#contentSwap2 "profiles") his likely successor, Deputy Governor Glenn Stevens:

> *Your mortgage may soon be in the hands of a guitar-playing amateur pilot from Sylvania Waters.*

Glenn Stevens is likely to enjoy a much smoother transition than Ben Bernanke.  An incredible amount of nonsense was written about Bernanke as he moved into his role as Fed Chairman and markets are probably still less than fully sold on his inflation-fighting credentials.  This is a reflection of the weakness of the institutional framework for monetary policy in the US and Alan Greenspan’s promotion of a highly discretionary approach to policy he euphemistically termed ‘risk management.’  It is hardly surprising then that markets view the Fed’s inflation-fighting credentials as being only as good as the next Fed Chairman.

I would be surprised if anyone were to raise similar questions about Stevens.  The key difference is the RBA’s commitment to an inflation targeting regime.  As it happens, the RBA’s inflation targeting framework is only very loosely defined and the associated governance framework remains thoroughly antiquated.  The RBA makes up for this, however, by having articulated the relationship between policy and its inflation target.  The RBA’s approach to policy is now reasonably well understood, in a way that Fed policy arguably isn’t.  The RBA’s experience shows that even the most basic commitment to an inflation target can give a central bank credibility that doesn’t just walk out the door when the central bank head leaves.

Glenn Stevens will be speaking on The Conduct of Monetary Policy on Thursday.  Should be an interesting speech.
