---
title: "Why Do Economists Blog?"
date: "2006-08-04"
categories: ["Economics"]
---

[The Economist](http://www.economist.com/finance/displaystory.cfm?story_id=7258939 "The Economist") asks why economists blog.  I’ve always thought the opportunity to make fun of The Economist magazine was reason enough, but that’s just me!  The Economist raises the obvious question about the opportunity cost of blogging.  The most frequent question I get asked about blogging is ‘where do you find the time?’ but I have never found blogging particularly time consuming.  I put this down to the fact that my blogging is more often than not an extension of work I am already doing.  Leveraging this into a blog post is not particularly demanding.

In some respects, economics blogging is a return to an older tradition in economics that had a much stronger public orientation and interest in substantive issues.  This tradition has been lost as the discipline has become increasingly consumed by technique.  Dan Klein has written eloquently about this in [What Do Economists Contribute?](http://www.amazon.com/gp/product/081474723X/ref=ase_institutional-20/002-5247213-4341622?s=books&v=glance&n=283155&tagActionCode=institutional-20 "What Do Economists Contribute?")  It is no accident that the economics faculty at George Mason University are such active bloggers.  They are some of the best representatives of this older tradition and among the most interesting academic economists in the world today.
