---
title: "Why the Kiwis Have Not Become Tigers"
date: "2006-06-13"
categories: ["Economics"]
---

The New Zealand Business Roundtable has released Frederic Sautet’s report, [Why Have Kiwis Not Become Tigers?](http://www.nzbr.org.nz/documents/publications/publications-2006/kiwi_tigers.pdf "Why Have Kiwis Not Become Tigers?")  Sautet concludes:

*New Zealand has not become a growth dynamo like Ireland because the reforms implemented did not go beyond OECD standard practice. To become tigers, Kiwis must adopt more radical reforms. Unfortunately, the Labour-led government in its 2005 Budget (and in its new incarnation after the September 2005 election) shows little inclination to improve the institutional environment in which entrepreneurial activity takes place. Rather, it prefers to continue increasing the size of government and, through regulation, to tinker at the margin with the rules of the economic game.  In the absence of changes, New Zealand’s economic outlook seems likely to be mediocre rather than exciting.*
