---
title: "Why there is No Money in Monetary Policy"
date: "2006-01-22"
categories: ["Economics"]
---

[David Altig](http://macroblog.typepad.com/macroblog/2006/01/why_theres_no_m.html "David Altig") has a short history of the demise of monetary aggregates in the conduct of US monetary policy.  The recent outcry over the Fed’s decision to discontinue publication of the M3 aggregate suggests many people viewed M3 growth as being somehow a more reliable guide to the stance of US monetary policy than the Fed funds rate.  The implication among some of the populist investment newsletter writers has been that the Fed has something to hide.  A [previous post](../2005/what_do_money_and_credit_aggregates_really_tell_us.qmd "previous post") has argued why this view is mistaken.  Altig nonetheless argues that it’s a pity that the role of money in monetary policy has been downgraded, without saying why in his post.  Let me suggest at least one reason.

Changes in the stock of real money balances have the capacity to push individuals off their demand curves for these balances, inducing portfolio balance effects that may in turn influence the economy-wide asset prices and yields that determine aggregate demand.  Changes in the stock of real money balances are likely to first work their way through goods and financial market disequilibria well before impacting prices.  This is both a real and nominal story (as argued in [this post](../2005/m3_the_fed_and_inflation.qmd "this post"), even in the long-run, the neutrality of money could conceivably fail).  M3 and other monetary aggregates could thus have some predictive power for asset prices and real output.  This is ultimately an empirical question, but does suggest that growth rates in money are something that policymakers might want to consider as an information variable, even when targeting an interest rate as their main operating instrument.  As I argued in a [review](http://www.institutional-economics.com/index.php/section/reviews/ "review") of Tim Congdon’s book, *Money and Asset Prices in Boom and Bust*, this is the only sense in which we should care about growth in broad money under an interest rate targeting regime. 

However, this is a far cry from saying that one can simply read-off from growth rates in money and credit that the stance of monetary policy is too loose or too tight, based on some a priori view of what constitutes reasonable growth rates in these aggregates.  The people most inclined to do this are the fever-swamp Austrians, who argue that every tick in the business cycle must be attributable to a fiat money supply error on the part of the Fed.  These are the same people who argue that money demand is too complex a phenomenon for the Fed to be able to calibrate an appropriate growth rate in the money supply.  That is perfectly true, which is why the Fed doesn’t even try.  Yet the fever-swamp Austrians are implicitly claiming enough knowledge about money demand to determine whether monetary policy is too loose or too tight, just by observing simple growth rates in money, credit and even asset prices.  This is what Hayek would term a ‘fatal conceit’ and is a travesty of Austrian economics.

**UPDATE:**  [Larry White](http://divisionoflabour.com/archives/002188.php "Larry White") challenges me to name names.  The fever swamp reference is my attempt to distinguish between respectable and less respectable exponents of views that draw on the Austrian tradition.  Larry White, George Selgin, Kevin Dowd, and Leland Yeager all fall within the respectable category and I would be very surprised to find them holding to the self-contradictory position I’m attributing to others.

However, there are plenty of examples over at the Mises Institute blog of this phenomenon and it is a common enough theme in popular libertarian and conservative discourse about monetary policy that claims inspiration from Austrian ideas.  Anyone who asserts that given growth rates in broad money, credit or asset prices are in themselves proof of a fiat money supply error is implicitly making a statement that they know what the correct growth rates should be.  Since these growth rates are largely market-determined and only loosely connected with monetary policy, they are also implicitly criticising the market process.

It should also be noted that those claiming the Austrian mantle are hardly alone in this.  The Economist magazine does it all the time and it is routine for popular economic commentary to point to point to growth rates in money, credit and asset prices as being symptomatic of ‘excess liquidity.’  My point is that anyone claiming to represent the Austrian tradition should know better.  Larry White clearly does. I just wish there were more of him.
