---
title: "Will We Get a Five Year Plan from Kevin Rudd?"
date: "2006-12-12"
---

[Sinclair Davidson](http://www.theage.com.au/news/business/rudds-fork-in-the-road-looks-to-be-heading-backwards/2006/12/11/1165685616171.html?page=fullpage "Sinclair Davidson") laments the appointment of Kim ‘Il’ Carr as shadow industry policy spokesman:

> Where will Rudd’s fork in the road take us? So far, it looks to be heading backwards. Reintroducing industry policy in any guise is poor economics. Putting a socialist in charge of a poor economic program must be poor politics.
>
> Rudd opposes “market fundamentalism” and is worried about family relationships. Will his solution involve reregulating the economy, reregulating working conditions and imposing draconian shopping hours? It appears a return to anti-market and anti-consumer choice policies may be on the cards.

Meanwhile, the [CIS crew](http://www.theaustralian.news.com.au/story/0,20867,20910102-7583,00.html "CIS crew") discuss the implications of the federal government’s so-called ‘market fundamentalism:’

> Nine out of 10 families therefore now receive a fortnightly welfare payment from the Government.
>
> There is an argument, which we broadly support, that families with dependent children should be treated more favourably than other households earning equivalent incomes, for they have more mouths to feed.
>
> But the best way to do this is to reduce their tax burden. The way the Government does it is to tax them as stringently as everybody else but then compensate them with handouts from Centrelink.
