---
title: "A New Broom at the FIRB?"
date: "2012-05-12"
categories: ["Economics", "Foreign Investment"]
---

New FIRB chairman Brian Wilson promises greater openness in an [interview](http://www.theaustralian.com.au/business/financial-services/new-firb-boss-keen-to-lift-lid-on-agency/story-fn91wd6x-1226353377917) with Glenda Korporaal:

> The former investment banker, who has been on the board of FIRB since 2009 and took over as chairman last month, says FIRB is making a greater effort to communicate the government’s foreign investment policies through its website and in briefing sessions for advisers. “It is important for all our constituencies—the Australian public, Australian business, foreign investors and their governments—to understand that the processes FIRB goes through are sensible and rigorous, and open and consistent,” he says. “Being a little more forthcoming, and having a little more transparency, will actually reduce, for some, the suspicion that we hear or read about from time to time.”
>
> Wilson says FIRB is now putting up a lot more on its website about Australia’s foreign investment policies.

The FIRB [has some catching up to do](http://www.theaustralian.com.au/news/opinion/more-inscrutable-than-the-chinese/story-e6frg6zo-1225831954203) when it comes to posting things on their web site. The fundamental problem with the legislation the FIRB administers remains:

> *“There is only one test—is the proposal contrary to the national interest? What that may be varies over time depending on economic circumstances, community attitudes, geopolitics, a whole gamut of things.”*

Then there is this:

> *“So, I wouldn’t have thought talking to FIRB about a concept or a possible transaction would tip you over the ASX disclosure threshhold.”*

Probably not quite the level of certainty investors are looking for, but perhaps a good quote for the M&A lawyers to file away for future reference.
