---
title: "A Sub-‘Prime’ Sovereign Wealth Fund"
date: "2012-03-16"
categories: ["Economics", "Financial Markets"]
---

Former Treasurer [Peter Costello](http://www.abc.net.au/7.30/content/2012/s3454575.htm) says that the Future Fund he created is a ‘prime sovereign wealth fund’ and ‘probably the most respected’ in the world. But that is not the conclusion of the Washington think-tank the [Peterson Institute](http://www.iie.com/), which has compiled the most comprehensive international ranking of sovereign wealth funds (SWFs). The Peterson Institute gave the Future Fund a score of only 80 out of 100, which is below the average of 84 given to the other pension funds in its sample of 53 SWFs in 37 countries. Thirteen other sovereign wealth funds were given a higher overall score in the Peterson Institute rankings, including those in Timor-Leste and Trinidad and Tobago.

In terms of accountability and transparency, the Future Fund scored only 75 out of 100, below the 89 out of 100 given to the State Oil Fund of Azerbaijan. On governance, the Fund scored 86, a little below the average of 87 for other pension funds in the sample. By contrast, New Zealand’s Superannuation Fund ranks third overall with a score of 94 and a perfect score of 100 for governance as well as accountability and transparency.

The Future Fund’s fractious board and the controversy surrounding the process for appointing the new Future Fund chairman only serves to underscore the Peterson Institute’s finding that the Future Fund falls well short of world’s best practice.

For more on the Future Fund, see our Policy Monograph [Future Funds or Future Eaters?](http://www.cis.org.au/images/stories/policy-monographs/pm-126.pdf)
