---
title: "Give Bernie 50 and He Will Want 100"
date: "2012-05-01"
categories: ["Economics", "Financial Markets", "Monetary Policy"]
---

Some of us have long memories:

‘No Risk In 1% Rate Cut, Says Fraser’,  PAUL CHAMBERLIN, 4 December 1996, The Age:

> The former governor of the Reserve Bank, Mr Bernie Fraser, said last night he believed November’s cut in official interest rates should have been doubled. As an overheated dollar retreated in markets yesterday, amid concern about its effect on exports, Mr Fraser said he thought the 0.5 per cent reduction announced last month by the central bank could have been 1 per cent.
>
> “I thought at the time with inflation pretty well under control, very much under control really, and the economy being a bit sluggish in some sectors, that we could have accommodated a 1 per cent cut without any risks,” he said on the ABC’s The 7.30 Report.

Bernie’s comments in December 1996 tanked AUD so hard, the RBA did not cut at that month’s regularly scheduled Board meeting. The RBA waited until 14 December while markets recovered from Bernie’s open mouth operations. So monetary policy ended-up being marginally tighter for longer thanks to Bernie. During his time as Governor, Bernie gave us an average cash rate of 8.7% and an average inflation rate of 3.6%.
