---
title: "Good and Bad Reasons for a Budget Surplus"
date: "2012-05-09"
categories: ["Economics", "Financial Markets", "Fiscal Policy", "Monetary Policy"]
---

The government’s stated motivation for returning the budget to surplus next financial year is to give the Reserve Bank ‘maximum room to move’ on interest rates. Yet a fiscal contraction is no more effective in restraining the economy than a fiscal expansion is effective in stimulating it. In an open economy with a floating exchange rate and an inflation-targeting central bank, changes in fiscal policy do not have significant macroeconomic implications. That is why the reaction of financial markets to budget statements is so negligible. The Reserve Bank’s statements also make clear that fiscal policy is a very minor consideration in its decision-making.

During the financial crisis, the government tried to have it both ways, arguing that its fiscal stimulus saved us from recession, but had no implications for interest rates. The second part of the argument was correct, but not the first. If the first part had any truth, then monetary policy must have been much tighter during the financial crisis as a result of the government’s stimulus spending.

The government should have no concern over the macroeconomic implications of changes in the budget balance, so long as it is balancing its budget over time and conducting fiscal policy in a sustainable manner. This should free the government to focus on what fiscal policy can do effectively, namely, changing microeconomic incentives to work, save and invest.

The government and opposition’s mistaken belief in a trade-off between fiscal and monetary policy is dangerous, because it leads to fiscal policy decisions that are more about window-dressing the budget balance and claiming credit for reductions in official interest rates that would have happened anyway, rather than improving incentives. For example, the mistaken belief that tax cuts stimulate demand and lead to higher interest rates can prevent sensible tax reform that has positive implications for the supply-side of the economy. Similarly, the fiscal stimulus of 2008-09 was bad primarily because it misallocated resources. Take away the macroeconomic rationale and the stimulus measures look indefensible on microeconomic grounds, even if the spending had been administered perfectly (which it was not).

A budget surplus target can be defended as a fiscal rule designed to impose additional discipline on government decision-making that might otherwise be absent. But there is no reason to subordinate fiscal policy to monetary policy and fiscal targets should not be pursued at the expense of the microeconomic incentives that are the ultimate source of both economic growth and long-term fiscal sustainability.
