---
title: "Intergenerational Conflict: Pagan versus Gruen"
date: "2012-05-21"
categories: ["Economics", "Fiscal Policy"]
---

I have an article at [The Conversation](http://theconversation.edu.au/independent-body-needed-to-preserve-integrity-of-fiscal-forecasts-7063) referencing the Pagan-Gruen exchange at the Melbourne Institute’s Intergen+10 Workshop (you can listen to the exchange [here](http://benews.unimelb.edu.au/2012/treasury-figures-massaged-for-politics/)). As I note in the article, whether the 2010 IGR growth assumptions were really the outcome of a political process is less important that the perception on the part of serious observers that they could be. This is something that needs to be addressed.

It is interesting to compare how the last IGR compiled under the Howard government in 2007 characterised Australia’s long-term debt position compared to the 2010 IGR. The 2007 IGR said that:

> *Demographic and other factors are projected to place significant pressure on government finances over the longer term and result in an unsustainable path for net debt towards the end of the projection period.*

If Adobe Acrobat’s search function is right, the word ‘unsustainable’ never appears in the 2010 IGR. The 2007 IGR was a much more candid document in relation to the long-run fiscal outlook.
