---
title: "Some Political Leadership on Foreign Direct Investment"
date: "2012-03-12"
categories: ["Economics", "Foreign Investment"]
---

Trade minister [Craig Emerson](http://www.theaustralian.com.au/business/world/tap-asia-for-farm-funding-says-craig-emerson/story-e6frg90o-1226296517429) has called for increased foreign direct investment in agriculture, in contrast to the federal Coalition’s calls for increased Foreign Investment Review Board scrutiny of foreign investment in the sector. It is one of the few acts of political leadership in this policy area since the late 1980s.

It is hard to believe now, but in the 1980s there was something of a bidding war between the federal Labor government and the opposition Coalition to liberalise the regulation of FDI. It culminated in then opposition leader John Howard’s undertaking to abolish the FIRB in his 1988 Future Directions manifesto. Both sides of politics recognised that restricting FDI increased foreign debt at the expense of foreign equity. The federal Coalition took a principled stand not to make a political issue of the Hawke-Keating government’s liberalisation measures.

Australia has often relied on external pressure rather than domestic political leadership in liberalising FDI. The 2005 Australia-US Free Trade Agreement resulted in a significant liberalisation of FDI screening thresholds in response to US concerns that would have been unlikely in the absence of the agreement.

The conventional wisdom holds that the existing discretionary regime for the regulation of FDI is as much liberalisation as the Australian political system can sustain. Yet the current system replaced an open-door regime that was in place until the early 1970s, at least if we ignore the statutory restrictions in certain sectors. The Australian political system has historically supported a more liberal FDI regime at times when economic nationalism and xenophobia were even more pronounced than they are today.

The shift to a discretionary regulatory regime from the early 1970s has normalised the idea that foreign direct investment should be regulated at the border rather than in-country on a national treatment basis. It is a legacy of the economic nationalism of Gough Whitlam and Rex Connor that continues to hold Australia back.
