---
title: "Taxing US Human Capital Flight"
date: "2012-06-02"
categories: ["Economics", "Population & Migration"]
---

From this week’s [Ideas@TheCentre](http://www.cis.org.au/publications/ideasthecentre/issue/269-ideasthe-centre-21-2012):

US embassies around the world are accustomed to queues of people seeking to migrate to America. More recently, a new type of queue has been developing: American ex-pats lining up for the 10-minute and \$450 ceremony in which they renounce their US citizenship. According to the Federal Register, the number of Americans renouncing their US citizenship or residency increased from 231 in 2008 to 1,781 in 2011. The US embassy in Bern, Switzerland, was recently reorganised to clear a growing backlog of citizenship renouncers.

This human capital flight gained prominence with the decision of Brazilian-born Facebook co-founder Eduardo Saverin to renounce his US citizenship and take up residency in Singapore. This led to accusations of tax avoidance, ingratitude and disloyalty levelled at the former immigrant to the US.

The accusation of tax avoidance is wrong. Under US tax law, expatriation is a deemed disposal for capital gains tax purposes. Saverin will pay taxes on his accrued Facebook capital gains while he was a US citizen. Only subsequent gains, if any, will benefit from the absence of capital gains taxes in Singapore.

The Saverin case nonetheless prompted senators Charles Schumer and Bob Casey to propose a new law, the Ex-Patriot Act, which would ban expatriates from ever re-entering America and tax an ex-citizen’s capital gains at a punitive 30% for 10 years. The Ex-Patriot Act has obvious similarities with the laws imposed by some of history’s worst regimes.

The US government has long made life difficult for its expats, taxing them on their global income, but the growing human capital flight from America has little to do with tax minimisation. The compliance burden resulting from the Foreign Account Tax Compliance Act and other new laws have made it increasingly costly to be an American abroad. Foreign firms are becoming reluctant to hire Americans, and foreign financial institutions increasingly refuse to deal with them because of the US government’s growing administrative overreach.

Rather than persecuting human capital flight, US senators would do well to consider why American citizenship is increasingly seen as a burden and not an asset.
