---
title: "Wayne Swan at Home and Abroad II"
date: "2012-06-14"
categories: ["Economics", "Politics"]
---

Wayne Swan in front of a [Euromoney forum in Sydney](http://www.bloomberg.com/news/2012-06-13/australia-s-swan-implores-europe-to-muster-political-courage.html):

> *“In a pattern now all too familiar, European politicians are still well behind the curve, having failed to take advantage of the months of relative calm,” Swan said in the text of a speech to be delivered at a Euromoney forum in Sydney today. “Put simply, what is required is some basic political courage.”*

[Wayne Swan](http://www.theaustralian.com.au/national-affairs/cabinet-split-on-free-trade-push/story-fn59niix-1226039362945) in federal cabinet:

> *Sources confirmed yesterday that Trade Minister Craig Emerson won approval for the shift with the backing of Ms Gillard, but only after her deputy, Wayne Swan, attacked the policy as lacking a political constituency. The sources said that, although the Treasurer, who has a long record of advocacy for trade liberalisation, did not attack the principles of the policy, he questioned the political wisdom of proceeding with the change at a time when the government was already fighting for reform on a range of other fronts, including the carbon tax.*
