---
title: "We Welcome Foreign Investment, Except When We Don’t"
date: "2012-08-06"
categories: ["Economics", "Foreign Investment"]
---

I have an op-ed in today’s [Australian](http://www.theaustralian.com.au/national-affairs/opinion/coalition-tightening-of-foreign-investment-policy-a-step-backwards/story-e6frgd0x-1226443380419) arguing the federal coalition had the right policy on foreign direct investment 24 years ago when it was committed to abolishing the Foreign Investment Review Board. The recent debate on this issue within the coalition almost perfectly mirrors a similar debate in the late 1980s, only this time, the National Party seems to be getting its way. Full text below the fold (may differ slightly from published version).

When then opposition leader John Howard released his ‘Future Directions’ policy manifesto in 1988, it included a commitment to abolish the Foreign Investment Review Board (FIRB).

Throughout the 1980s, Labor and the Coalition competed to liberalise Australia’s regulatory regime for foreign direct investment (FDI). Lower barriers to FDI were seen by both sides of politics as essential to better integrating Australia into the world economy. Abolition of the FIRB was the logical next step in this process.

A quarter of a century later, opposition leader Tony Abbott has released a discussion paper that proposes to expand the membership of the FIRB rather than abolish it. If the discussion paper is any guide to future policy under an Abbott government, the FIRB will need all the additional help it can get.

It proposes to lower the threshold for scrutiny of foreign acquisitions of agricultural land from \$244 million to a cumulative \$15 million, while acquisitions of agribusiness will be caught in the FIRB net at \$53 million or 15% of the current review threshold of \$244 million, whichever is lower.

An over-stretched FIRB that already considers nearly 11,000 applications a year will be kept very busy under these proposed arrangements. The discussion paper’s proposals go against the recent trend to raise the threshold for scrutiny for foreign acquisitions to relieve both the FIRB and foreign investors from having to process transactions that are simply too small to raise any ‘national interest’ concerns.

It is unlikely that this additional scrutiny will raise the explicit rejection rate for foreign acquisitions, since the discussion paper does not propose significant changes to the criteria by which they will be assessed.

The proposals may, however, result in a higher implicit rejection rate as foreign investors decide that the uncertainties, delays and expense involved with the FIRB process are not worth the trouble. By reducing the number of potential buyers, the coalition’s proposals will devalue the stock of equity of capital in Australia and reduce the ability of farmers to capitalise on and re-invest their equity.

The coalition’s proposal to introduce a national register for foreign-owned land is a good idea, although not for the reasons that many might think. Too much of the debate about foreign ownership of agricultural land and residential property is driven by anecdote rather than data. This creates an environment in which cynical politicians can more easily exploit community anxieties for electoral advantage.

The state register of foreign ownership in Queensland has put foreign ownership in proper perspective. By contrast, the FIRB’s notorious lack of transparency has undermined community support for foreign investment.

The coalition’s concerns about FDI sit uneasily with its aspiration to turn Australia into the ‘food bowl of Asia.’ The agricultural sector is becoming increasingly capital intensive. Expanding agricultural output depends on capital-driven productivity improvements rather than acreage. Together with the mining sector, Australian agriculture needs massive injections of foreign capital.

Foreigners want to invest in Australian agribusiness because it gives them increased exposure to growing markets in Asia. Foreign interest in expanding the global supply of agricultural commodities is perfectly harmonious with Australia’s interest in expanding domestic production, exports and employment.

Agricultural commodities are sold in world markets at world prices. There is limited scope for domestic or Australian export prices to deviate from world prices. Foreign interests pursuing vertical integration strategies have little or no effective pricing power in these markets. The Australian Taxation Office has sweeping powers to address transfer pricing issues.

The coalition’s discussion paper otherwise endorses Australia’s Whitlam-era regulatory framework for FDI, the result of an inward turn from the open-door policy Australia maintained until the early 1970s.

This framework enjoys bipartisan support. Yet it adds nothing useful to the regulation of business investment in Australia. Its only function is to provide a mechanism for politicians to interfere in the market for the ownership and control of Australian equity capital that is inconsistent with the rule of law and devalues the domestic capital stock.

Australia’s regulation of FDI at the border rather than on a national treatment basis jeopardises economic growth, exports and jobs. The coalition had the right policy 24 years ago. It should commit to the repeal of the Foreign Acquisitions and Takeovers Act and the abolition of the Foreign Investment Review Board.
