---
title: "A Beginners Guide to Oil"
date: "2008-12-12"
categories: ["Economics", "Oil"]
---

A [review](http://www.nationalpost.com/opinion/columnists/story.html?id=af71154b-8d92-49d7-a82a-d43bb3051560&p=1 "review") of Vaclav Smil’s new book, *Oil*:

> The list of big-name economists, commentators and forecasters who hung their hats—and their investment plans—on variations of peak oil theory is too big for this page, but some day somebody should post it prominently for all to see.
>
> One of the rare exceptions, a name not on any such list, is Vaclav Smil, perhaps one of Canada’s greatest unsung academics. Let me now sing his praises. Prof. Smil is a distinguished professor in the environment faculty at the University of Manitoba. One of his many books, usually dense and written for scholars, is a new popular Beginners Guide, simply titled Oil (Oneworld Publications, 200 pages, 2008).
>
> Back in June, 2006, Prof. Smil wrote a commentary for FP Comment dismissing the peak oil crowd as a “new catastrophist cult.” In 2000, he warned in a science journal that the experience of long-range forecasting, especially in energy, had been dismal. He predicted more. “There will be no end to naive, and ... incredibly short-sighted or outright ridiculous, predictions.”
>
> Prof. Smil’s new contribution to the absurdity of peak oil theory, Oil, is more than just a critique of the latest crackpot forecasting theories. In 200 pages, he packs everything most people—including most economists and investment advisors—should know about the physics and economics of oil.
>
> As time goes on the world will slowly sever its dependence on fossil fuels, but any such transition is decades away. Peak oil enthusiasts are wrong for scores of reasons. They assume that oil reserves are know with some degree of precision; that reserves are fixed; that demand and supply can be projected with accuracy over long periods of time.
>
> As Prof. Smil wrote on this page in 2006: “Unless we believe, preposterously, that human inventiveness and adaptability will cease the year the world reaches the peak annual output of conventional crude oil, we should see that milestone (whenever it comes) as a challenging opportunity rather than as a reason for cult-like worries and paralyzing concerns.”
