---
title: "An Own Goal in the ‘War on Inflation’"
date: "2008-02-04"
categories: ["Economics"]
---

The Rudd government seeks to fight inflation and promote housing affordability – by giving people [more money to spend on housing](http://www.treasurer.gov.au/DisplayDocs.aspx?doc=pressreleases/2008/004.htm&pageID=003&min=wms&Year=&DocType= "more money to spend on housing").  This is good news for incumbent property owners, who will see the increase demand for housing capitalised into house prices, but will only worsen housing affordability. 

According to the government:

> First Home Saver Accounts are also part of the Rudd Government’s five point plan to win the war on inflation, encouraging private savings \[sic\] and helping put downward pressure on inflation and interest rates.
>
> This initiative will help boost national savings \[sic\], with the accounts anticipated to hold around \$4 billion in savings \[sic\] after four years.

It is more likely the scheme will simply see substitution between different types of private saving, with households diverting funds from other types of saving to take advantage of the government co-contribution, with no gain to overall private or national saving.  As we argue [here](http://www.cis.org.au/policy/Spring_07/links/spring07_kirchner.html "here"), the level of domestic and national saving is only a minor influence on interest rates in a small open economy like Australia.
