---
title: "Another Own Goal in the ‘War on Inflation’"
date: "2008-02-06"
categories: ["Economics", "Politics"]
---

Fighting inflation – with [higher tariffs](http://www.businessspectator.com.au/bs.nsf/Article/Government-to-review-tariff-freeze-BJNFF?OpenDocument "higher tariffs"):

> The Rudd Government is looking at the possibility of a tariff freeze, in a bid to protect Australia’s remaining car makers, after Mitsubishi confirmed the closure of it’s Australian manufacturing operations with the loss of 930 jobs, according to media reports.
>
> The automaker’s departure is expected to prompt the federal government to carry out a review of subsidies allocated to the industry, as players left in the local automotive sector struggle to cope with increased global competition and a shrinking share of the market.
>
> Car industry tariffs are due to be cut from 10 per cent to 5 per cent by 2010, but manufacturers have asked the government to maintain the current protection and boost funding for the industry.
