---
title: "Are the RBA and Treasury ‘Ideologically and Factually Flawed’?"
date: "2008-09-26"
categories: ["Economics", "Financial Markets"]
---

AussieMac proponent [Joshua Gans](http://economics.com.au/?p=1783 "Joshua Gans") says:

> *It is not hard to imagine that Labor politicians are left wondering how they appear to have gotten themselves alligned \[sic\] with Terry McCrann and the CIS. The answer is that the advice they are getting is flawed both ideologically and factually*.

Since this is much the same advice that the government has been getting from those notorious right-wing think tanks, the RBA and Treasury, one can only assume that Joshua thinks that these institutions are similarly in error.  What exactly does it mean to be ‘ideologically flawed’ anyway?

The main reason the Treasurer is uninterested in AussieMac is that we already have institutions such as the RBA that stand ready to supply market liquidity, to the extent that it is needed.  The experience both in Australia and overseas has been that central bank liquidity operations have been undersubscribed.  [Governor Stevens](http://www.aph.gov.au/hansard/reps/commttee/R11086.pdf "Governor Stevens") complained at the most recent House Economics Committee hearing that they practically had to brow-beat the market into stumping-up enough RMBS.

The government can also assist home buyers directly, without needing to intermediate that assistance through a GSE and the mortgage securitisation industry.  The UK government has taken this more direct approach, but we are a long way from needing that sort of intervention in Australia.

The RBA can be expected to calibrate its new easing cycle to conditions in credit markets.  If the banks fail to fully pass on cuts in the official cash rate, the RBA will just cut by larger amounts to get the desired change in retail lending rates.
