---
title: "AussieMac? No Thanks"
date: "2008-05-03"
categories: ["Economics", "Financial Markets"]
---

[Alan Wood](http://www.theaustralian.news.com.au/story/0,25197,23636593-31478,00.html "Alan Wood") on the Gans-Joye proposal to harness government guarantees to under-write mortgage lending:

> The creation of a government - that is, taxpayer - subsidised institution, largely for the benefit of non-bank mortgage lenders, would need to be justified either by the existence of a long-term structural problem in the provision of housing finance in Australia, or evidence of a short-term collapse in the availability of home loans.
>
> Neither problem is evident, and in any case it would take too long to set up such a body for it to be of any use in the current credit crisis. Nor is it warranted as a hedge against future crises.
>
> Interestingly, in his upbeat press release, Greg Medcalf was obliged to include the following sentence: “While the proposal has received encouraging feedback, Mr Medcalf said there was some concern the enhancements were addressing a short-term market issue that did not require a long-term fix”. Just so.
