---
title: "Australia’s Fiscal Gang Problem"
date: "2008-02-07"
categories: ["Economics", "Financial Markets", "Politics"]
---

Finance Minister Lindsay Tanner says ‘Australia has a gang problem, and I’m part of it.’  He is referring, of course, to the ‘razor gang.’  Tanner was [announcing](http://www.financeminister.gov.au/media/2008/mr_062008.html "announcing") a ‘modest down payment’ of \$643m in budget cuts, ahead of larger cuts to be announced in the May Budget.  No doubt the aim of this announcement is to be seen to be doing something about inflation in the week of an increase in official interest rates.  Among the causalities are some of the former government’s more outrageous pork-barrelling projects, including the Fishing Hall of Fame and the National Rugby Academy. 

The more significant cuts will take longer to put together, but the returns to what has supposedly been a line-by-line examination of government spending programs are already looking rather paltry.  They are also small relative to the enormous amount of political capital the government has available to spend in the wake of its election victory.  One suspects that the [legendary Lu Kewen](../2008/the_legendary_lu_kewen.qmd "legendary Lu Kewen") could literally spit on some voters at the moment and still have them come away thinking it was a religious experience.  When it comes to cutting spending, there is no time like the present. 

We [previously noted](../2008/how_to_be_a_fiscal_conservative_without_really_trying.qmd "previously noted") that the new Labor government’s target for the underlying cash surplus of 1.5% of GDP for 2008-09 was not exactly ambitious, merely maintaining the status quo on recent budget outcomes and representing only a small contractionary impulse on forward estimates that probably would have been bettered anyway.  The ugly reality for the government is that Commonwealth fiscal policy is already the tightest it’s been in two decades and further spending cuts of the magnitude being contemplated by the government will not put a dent in inflation or interest rates.
