---
title: "Australia & the EBRD: A Little Known Victory for Taxpayers"
date: "2008-05-23"
categories: ["Economics"]
---

Looks like budget cuts may have finally ended Australia’s role in the [European Bank for Reconstruction and Development](http://online.wsj.com/article/SB121148203341214927.html?mod=opinion_main_commentaries "European Bank for Reconstruction and Development"):

> A reality check comes from Down Under. Speaking at the Kiev meeting, Peter Reith, EBRD director for Australia and New Zealand, said that “the EBRD has achieved a great deal in its 17 years.” “It is in this context of a job well done,” he announced, “that the Australian government intends to withdraw from the bank by 2010.”
>
> Australia has given the EBRD €52.5 million since the bank’s founding, about a quarter of the €200 million it originally committed. The EBRD’s biggest shareholder, the U.S., committed €2 billion and has so far paid in €525 million. David McCormick, Treasury Undersecretary for International Affairs, says the bank is at a “crossroads,” but that the U.S. “remains a strong supporter.” Australia looks smarter.

Australia was none too smart to sign-up for the EBRD in the first place, especially given its focus on a region far removed from Australia’s interests.  I recall researching the institution when the capitalisation bill came before parliament in the early 1990s and was [appalled at what I found](http://www.cato.org/pubs/fpbriefs/fpb-008.html "appalled at what I found").  It was apparent even then that this would be another scandal-ridden multilateral development bank. 

As the WSJ article notes, the EBRD suffers from the same problem as all the other multilateral development banks.  Redundancy has bred mission creep:

> At its annual meeting in Kiev this week, the European Bank for Reconstruction and Development—founded in 1991 to assist the former Soviet bloc states—confirmed that, among other things, it wants to explore projects in Turkey.
>
> That’s an odd idea for a bank whose mission is to “foster the transition towards open market-oriented economies and to promote private and entrepreneurial initiative in the Central and Eastern European countries committed to and applying the principles of multiparty democracy, pluralism and market economics.” Turkey is a democracy, has an open market, and isn’t in Central or Eastern Europe…
>
> In recent years, the bank has moved south and east as Soviet bloc countries have grown richer. Fully 42% of its investments last year went to Russia. Never mind that Russia is rolling in oil revenues and also receives subsidized capital from the International Finance Corporation, an arm of the World Bank. EBRD President Thomas Mirow, who took office on Monday, says he supports Turkey’s request to have the EBRD invest there.
