---
title: "Australia 2020 or 1930"
date: "2008-04-22"
categories: ["Economics", "Politics"]
---

[Henry Ergas](http://www.theaustralian.news.com.au/story/0,25197,23576958-7583,00.html "Henry Ergas") finds little new in the 2020 summit:

> This reliance on government, which sets the tone for the summit outcomes, is hardly “new thinking”. Rather, it brings eerily to mind W. K. Hancock’s great work Australia, published more than 70 years ago, where he noted the tendency among Australians to “look upon the state as a vast public utility, whose duty it is to provide the greatest happiness to the greatest number”. Though “generally matter-of-fact people who distrust fine phrases and understand hard realities”, Australians are, he concluded, “in politics, incurable romantics” who, out of intellectual laziness and profligacy born of the country’s wealth, “constantly confuse ends and means (and are) reluctant to refuse favours, to count the cost, to discipline the policies which they have launched”.
>
> History shows all too clearly where that path leads: not to the glorious future the summiteers have in mind, but to waste and inefficiency, disappointed hopes and dashed expectations. If that is the best we can come up with, the road ahead will be painful indeed.
