---
title: "Bilby Pork"
date: "2008-05-21"
categories: ["Economics"]
---

The government’s budget cuts may not amount to much, but they certainly [range widely](http://www.abc.net.au/news/stories/2008/05/21/2250890.htm?site=westqld "range widely"):

> *Plans for a \$5 million national [bilby](http://en.wikipedia.org/wiki/Bilby "bilby") centre in south-western Queensland have been shelved, after the Federal Government pulled out of a funding deal.*

However, the bilby lobby seem to understand the political economy of government spending all too well:

> Manager Jane Morgan says that money was to be used to build a new observatory, but those plans have also now been shelved with the funding cut.
>
> “Yes we are a little bit disappointed, but it’s not as if they’ve said ‘forever and a day there will be no more grant programs in this area’,” she said.
>
> “This is the looking at Government expenditure that they went through and it is disappointing because we had some great plans, but we’re not going to put those plans away.
>
> “We’re just going to put them on a shelf which is easily reached and pull them out again.”

**CORRECTION:**  The quote is actually not from the bilby people, but from those involved with another project that got cut.  Same point applies, however.
