---
title: "‘Bubbles’ in Everything: Indonesian Seaweed Edition"
date: "2008-10-21"
categories: ["Economics", "Financial Markets"]
---

[At least one](http://online.wsj.com/article/SB122454073909251775.html "At least one") ‘bubble’ they will be hard pressed to pin on US monetary policy:

> a few months ago, parts of the \$14 billion global seaweed market started soaring. The price for a key type of Indonesian seaweed suddenly more than tripled, to as much as 18,000 rupiah (or \$1.80) per kilogram, from about 5,000 rupiah.
>
> Then, just as quickly, the seaweed bubble burst, adding the spindly plant to the long list of the world’s assets—including oil, stocks and houses—that have tumbled in value. By early September, prices skidded to 12,000 rupiah. By October, they were down to 10,000, and they may be headed lower.
>
> “Nothing like this has ever happened before,” says Asu Hasna, a 42-year-old seaweed farmer in this coastal community on the island of Sulawesi, which, along with parts of the Philippines, is a tropical seaweed hot spot. Before, she says, seaweed prices never fell. “These are bad times.”
>
> Despite recent declines, prices are still higher than they were a year ago. But the recriminations over what went wrong have begun, complete with calls for more government involvement, efforts to make the industry more transparent and reforms to restore market confidence.
