---
title: "Budget Wrap"
date: "2008-05-14"
categories: ["Economics", "Financial Markets"]
---

The Labor government’s first budget had more in common with those of its predecessor than it would care to admit.  The chief fiscal problem confronting policymakers is not fighting inflation, but finding a home for the revenue growth that continues to exceed Treasury forecasts and for which the government has no current use after delivering on its election tax cuts and other commitments.  At 1.8% of GDP, the underlying budget surplus is larger than at any time since 1999-00, but still a trivial tightening on the 1.5% of GDP seen in 2007-08.  The Commonwealth has now been running surpluses of 1% of GDP or more since 2002-03 and at least 1.5% of GDP since 2004-05.  As [Alan Wood](http://www.theaustralian.news.com.au/story/0,25197,23695703-30538,00.html "Alan Wood") notes ‘The cynicism born of many budget lock-ups says that this is a remarkably convenient pattern of surpluses.’

Peter Costello’s solution to the problem was a combination of tax cuts and hoarding revenue in the Future Fund, which is much the same approach taken by Labor with its Building Australia Fund and revamped higher education fund.  Whether revenue is better used buying financial assets or invested in as yet unspecified infrastructure is far from clear.  If infrastructure needs were so pressing, the government would not need a body like Infrastructure Australia to go in search of suitable projects and would instead have no problem drawing up a list and timetable of projects in the Budget itself.  Investment spending has been at post-war record highs as a share of GDP, so there is no shortage of investment on the part of the private sector.  The danger is that the BAF becomes a public sector white elephant fund.

At the same time, Labor has still not fully funded the ‘aspirational’ part of its election tax cuts, which aim to reduce the existing four tax scales to three by 2013: 15%, 30% and 40%.  These aspirational tax cut commitments would have more credibility if they had been fully funded in the budget and could conceivably even have immediate supply-side benefits if the public were convinced they would be delivered.  The failure to fully fund them suggests that the ‘aspirational’ part of the tax cuts will remain just that.  Social democrats like [John Quiggin](http://johnquiggin.com/index.php/archives/2008/05/13/instant-budget-reaction/ "John Quiggin") are openly looking forward to the inflation tax that will claw back the tax cuts.

Ross Gittins and Chris Richardson still seem to think that the main role of the Budget is to save RBA Governor Stevens from having to do any work.  According to [Gittins](http://business.smh.com.au/weve-been-hoodwinked-more-pain-required/20080513-2dug.html?page=1 "Gittins"):

> *Even if further interest-rate increases don’t prove necessary, the budget does nothing to bring forward the day when the Reserve Bank is able to start cutting rates.*

Just as predictably, [Chris Richardson](http://www.abc.net.au/lateline/content/2007/s2243888.htm "Chris Richardson") said that:

> *Tax cuts are clearly inflationary and clearly dangerous in an economy that is still at full stretch.  Much of them will be spent.*

The budget has [no relevance](http://www.cis.org.au/policy/Spring_07/links/spring07_kirchner.html "no relevance") for inflation and interest rate outcomes, but even if it did, why would we prefer restraint in demand to come from higher taxes than higher interest rates?  On political economy grounds, we should prefer higher interest rates.  The interest rate cycle will eventually turn, whereas the expansion of government probably won’t.  The real agenda of those who oppose tax cuts is to support the secular expansion of the state.
