---
title: "Building Approvals, House Price Inflation and Rents"
date: "2008-02-06"
categories: ["Economics", "Financial Markets"]
---

If you thought the double-digit annual growth rates for [established house prices](../2008/australian_versus_us_house_prices.qmd "established house prices") in the December quarter were impressive, then you should be even more impressed with the [December building approvals release](http://www.abs.gov.au/AUSSTATS/abs@.nsf/ProductsbyReleaseDate/0545FFC6A101264DCA25719F007F6F1F?OpenDocument "December building approvals release").  Private house approvals fell off a cliff, with the overall level of approvals at its lowest since September 2005. 

In financial markets, it is common to give the building approvals release a demand-side interpretation, but the supply-side implications are more compelling in the current environment.  The strong increases in dwelling rents, a direct contribution to CPI inflation, and house prices are symptomatic of a national shortage of dwelling stock which, on these numbers, is not about to be eased any time soon.  Of course, rising rents and house prices should eventually induce an increase in approvals and supply.  The November release seemed to herald exactly that, but those gains and more were given away in December. It remains to be seen how much of this is just one-off month on month volatility.  The fact that Christmas fell on a Tuesday may have been a factor.  There would not have been many people working Monday and, knowing council workers, it is hard to imagine too many hanging around on the previous Friday afternoon either, so there may be a trading day effect that is not picked-up by the usual seasonal adjustment process.

In any event, together with yesterday’s increase in official interest rates, the implications for housing affordability are fairly dire.  During the previous boom in house prices earlier this decade, many people decried the tax breaks on investment property and predicted massive over-supply and a subsequent crash in property prices.  Yet at best we saw a flattening in prices at the national level, suggesting that the national housing market was never seriously oversupplied.  In the absence of the augmentation of the housing stock that we saw as a result of the previous boom and the concessional tax treatment of capital gains on investment property after 1999, the supply situation, housing affordability and inflation outcomes may have turned out even worse than they are now.
