---
title: "Chicago School Unwelcome at Chicago"
date: "2008-06-19"
categories: ["Economics"]
---

University of Chicago academics [oppose](http://www.chicagotribune.com/news/local/chi-milton-friedman-flap-18-jun18,0,5015442.story "oppose") naming a new research centre after Milton Friedman:

> In a letter to U. of C. President Robert Zimmer, 101 professors—about 8 percent of the university’s full-time faculty—said they feared that having a center named after the conservative, free-market economist could “reinforce among the public a perception that the university’s faculty lacks intellectual and ideological diversity.”
>
> “It is a right-wing think tank being put in place,” said Bruce Lincoln, a professor of the history of religions and one of the faculty members who met with the administration Tuesday. “The long-term consequences will be very severe. This will be a flagship entity and it will attract a lot of money and a lot of attention, and I think work at the university and the university’s reputation will take a serious rightward turn to the detriment of all.”
>
> ...faculty critics are concerned that it will be one-sided, attracting scholars and donors who share a point of view.

The opposition probably tells us more about the lack of diversity and the ideological biases at the rest of the university than at the new research centre.
