---
title: "Embrace the ‘Bubble’"
date: "2008-06-13"
categories: ["Economics", "Financial Markets"]
---

Business Week’s [Chris Farrell](http://www.businessweek.com/investor/content/jun2008/pi20080611_987593.htm "Chris Farrell"), on why we should welcome so-called ‘bubbles’ in asset prices as a normal part of the functioning of a market economy:

> Let’s go back to the dot-com example. What’s remarkable is just how quickly the Internet economy was established during that so-called era of fictitious value. “The conventional wisdom is that the period of exuberance during the boom period—especially 1999 and 2000—was a bubble,” writes BusinessWeek Chief Economist Michael Mandel in his book Rational Exuberance. “It carries connotations of something fragile, which was never quite real in the first place.”
>
> But rather than a bubble, argues Mandel, the second half of the 1990s could just as easily be called an “age of exploration.” “The low cost of capital enabled risk-taking people and companies to try out lots of new ideas simultaneously, and on a large enough scale that they got a fair test,” he writes…
>
> Bubble moralizers greatly underestimate the vital role of speculators and speculative markets in allocating resources toward an economy’s fast-growing sectors and away from stagnant industries.
