---
title: "Fiscal Stimulus Doesn’t Work - Ever"
date: "2008-12-19"
categories: ["Economics", "Fiscal Policy"]
---

[Tyler Cowen](http://www.marginalrevolution.com/marginalrevolution/2008/12/fiscal-policy-a.html "Tyler Cowen") suggests the historical record argues against the effectiveness of fiscal stimulus:

> it is very hard to find examples of successful fiscal stimulus driving an economic recovery.  Ever.  This should be a sobering fact…
>
> It’s up to the advocates of the trillion dollar expenditure to come up with the convincing examples of a fiscal-led recovery.  Right now we’re mostly at “It wasn’t really tried.”  And then a mental retreat back into the notion that surely good public sector project opportunities are out there.
>
> So what you have is the possibility of faith—or lack thereof—that our government will spend this money well.
>
> And that is under “emergency” conditions, with great haste (“use it or lose it”), with a Congress eager to flex its muscle, and with more or less one-party rule.

Another way of looking at this issue is to ask why we would ever need to experience a significant economic downturn if policymakers could effectively smooth the business cycle with fiscal policy. 

Meanwhile, [Centrebet](http://centrebet.com/cust?action=GoSports&ev_sub_type_id=10135 "Centrebet") is offering \$1.22 for a local recession by the December quarter 2009.  Assuming an 8% bookie’s margin, this implies a recession probability of around 75%.  Needless to say, the [Treasurer](http://www.canberratimes.com.au/news/local/news/business/centrebet-taking-wagers-on-recession/1388841.aspx "Treasurer") is not happy with betting shops speaking truth to power:

> *I think that sort of talk is utterly irresponsible.*
