---
title: "Foreign Oil is Your Friend"
date: "2008-11-29"
categories: ["Economics", "Oil"]
---

[Roger Howard](http://online.wsj.com/article/SB122791647562165587.html "Roger Howard"), author of *The Oil Hunters*, on how foreign oil creates interdependence rather than dependence:

> to identify America’s “foreign oil dependency” as a source of vulnerability and weakness is just too neat and easy.
>
> This identification wholly ignores the dependency of foreign oil producers on their consumers, above all on the world’s largest single market—the United States. Despite efforts to diversify their economies, all of the world’s key exporters are highly dependent on oil’s proceeds and have always lived in fear of the moment that has now become real—when global demand slackens and prices fall. The recent, dramatic fall in price per barrel—now standing at around \$54, less than four months after peaking at \$147—perfectly exemplifies the producers’ predicament.
>
> So even if such a move were possible in today’s global market, no oil exporter is ever in a position to alienate its customers. Supposed threats of embargoes ring hollow because no producer can assume that its own economy will be damaged any less than that of any importing country. What’s more, a supply disruption would always seriously damp global demand. Even in the best of times, a prolonged price spike could easily tip the world into economic recession, prompt consumers to shake off their gasoline dependency, or accelerate a scientific drive to find alternative fuels. Fearful of this “demand destruction” when crude prices soared so spectacularly in the summer, the Saudis pledged to pump their wells at full tilt. It seems that their worst fears were realized: Americans drove 9.6 billion fewer miles in July this year compared with last, according to the Department of Transportation.
>
> Instead, the dependency of foreign oil producers on their customers plays straight into America’s strategic hands.
