---
title: "Freddie and Fannie: Poster Children for Corporate Welfare"
date: "2008-09-12"
categories: ["Economics", "Financial Markets"]
---

Peter Wallison [argues](http://online.wsj.com/article_print/SB122117569863425755.html "argues") that the Paulson rescue plan will further entrench Freddie and Fannie:

> Recent statements by Barney Frank (D., Mass.), the chairman of the House Financial Services Committee, and Chuck Schumer (D., N.Y.), a powerful member of the Senate Banking Committee, make clear that Congress will never let them be privatized, broken up, slimmed down, nationalized or any of the other options hopeful reformers are putting forth today. Fannie and Freddie in their current form are just what Congress wants: an inexhaustible source of campaign contributions and funds for favored groups.
>
> Here’s how it works. Fannie and Freddie are backed by the federal government, which allows them to borrow money at interest rates lower than any other shareholder-owned company. With these cheap funds, they buy and hold mortgages and mortgage-backed securities with considerably higher yields.
>
> But the huge profits from this government-subsidized arbitrage do not mean lower mortgage rates for the American homebuyers. Studies by the Federal Reserve have shown that Fannie and Freddie have essentially no effect on mortgage rates. The profits instead go to shareholders and managements, lobbyists, favored community groups, and of course to members of Congress through campaign contributions.
>
> The Paulson plan, regrettably, will restore these two companies to their positions as poster children for corporate welfare.

Wallison et al were [sounding the alarm](http://www.aei.org/books/filter.all,bookID.794/book_detail.asp "sounding the alarm") on Freddie and Fannie back in 2004.
