---
title: "Glenn Milne’s Thinly Disguised Class Warfare"
date: "2008-04-07"
categories: ["Economics", "Financial Markets", "Politics"]
---

[Glenn Milne](http://www.theaustralian.news.com.au/story/0,25197,23494251-7583,00.html "Glenn Milne") joins the tabloid attack on Glenn Stevens, complaining that the RBA Governor is not phoney enough:

> Central bankers might argue that they’re not meant to behave like politicians. But the reality of public life is that if you are the individual who is seen to have the power to decide whether people keep a roof over their heads, you must behave in an accountable fashion, or at least pretend to.
>
> Stevens is not behaving in this way.

The whole point of having an independent central bank is to have economic policymakers who will tell it like it is and not give in to economic populism.  Milne says that ‘Stevens now has few friends in Canberra.’  That is how it should be.  A more adversarial relationship between the RBA and politicians would strengthen, not weaken, public accountability in the conduct of economic policy.

Then there is this bizarre and nonsensical bit of parochialism:

> *Stevens, with his Teutonic lustre and mid-Atlantic conference accent, comes from nowhere recognisable in the Australian suburban landscape…*

Glenn Stevens can do no more about his appearance than Glenn Milne.  Stevens actually looks and sounds more authentically Australian to me than Milne, but what of it?  Milne is indulging in thinly disguised class warfare.

The unfortunate consequence of these tabloid attacks is that it will make the RBA’s senior officers even less willing to maintain a public profile, weakening the very accountability Milne says he is in favour of.
