---
title: "Glenn Stevens’ 2010 Christmas Wishlist"
date: "2008-05-09"
categories: ["Economics", "Financial Markets"]
---

The RBA’s quarterly [Statement on Monetary Policy](http://www.rba.gov.au/PublicationsAndResearch/StatementsOnMonetaryPolicy/statement_on_monetary_0508.html "Statement on Monetary Policy") contained an inflation forecast consistent with the 2-3% medium-term target range, assuming you don’t mind waiting until Christmas 2010 to get it.  This was achieved largely by way of a dramatically lower economic growth forecast.  Non-farm GDP is now expected to slow to 1.75% by the end of this year, compared to the 2.75% forecast in the February Statement.  This is an annual growth rate not seen since 2001 in the wake of the recession in domestic final demand that followed the introduction of the GST in the second half of 2000.  In effect, the RBA has dramatically raised the bar on the weakness we will have to see in the activity data this year for the RBA not to further raise interest rates.  The RBA’s forecasts highlight the growth sacrifice that will now need to be made to tame inflation.  Even then, inflation will still be sitting at the upper-end of the target range.
