---
title: "Glenn vs Glenn"
date: "2008-04-09"
categories: ["Economics", "Financial Markets", "Politics"]
---

[Alan Wood](http://www.theaustralian.news.com.au/story/0,25197,23508726-7583,00.html "Alan Wood") defends one Glenn against tabloid populism, while rejecting the claims of another Glenn who should know better:

> I cannot recall a previous occasion where there has been such a scurrilous personal attack on the governor of the bank as the one on Glenn Stevens in Sydney’s The Daily Telegraph on Saturday, when he was labelled the most useless man in Australia for simply stating the facts about rising bank interest rates. This economically illiterate piece of populism is offensive but, fortunately, irrelevant in the broader debate on monetary policy…
>
> However, what is disturbing is Glenn Milne’s report in his column on this page on Monday that Stevens “in the view of Canberra’s economic and governance elite is at a tipping point in personal, presentational and policy terms”. Milne also said there was a view at the most senior levels of the Rudd Government that Stevens needed to urgently improve his presentation, not least because he had spectacularly contradicted Treasurer Wayne Swan’s narrative that independent rate rises by Australia’s banks were not always justified….
>
> According to Milne, Stevens has few friends in Canberra. If the view that the Rudd Government has lost confidence in the central bank governor became widespread, it could have dangerously destabilising effects on already unstable financial markets. Is it true? Having spoken to a few of Canberra’s “economic and governance elite”, I haven’t detected any loss of confidence in Stevens, with one government source describing his Friday remarks as spot-on.

[Terry McCrann](http://www.news.com.au/heraldsun/story/0,21985,23503029-664,00.html "Terry McCrann") adds:

> So the chairman of a group which had led one of those boom-time private equity - meaning, loaded with debt - buyouts of the Myer stores doesn’t like rising rates which cut consumer discretionary spending.
>
> Now that’s a surprise. And an obvious lesson. We must immediately hand interest rate decisions to Bill Wavish.

McCrann is being ironic, but the fact is that we do allow retailers to sit on the RBA Board.
