---
title: "Governments are Making Things Worse"
date: "2008-10-11"
categories: ["Economics", "Financial Markets"]
---

[Jonathan Macey](http://online.wsj.com/article/SB122367942018324645.html "Jonathan Macey"), writing in the *WSJ*, calls for an end to the demonisation of markets:

> Despite all the hard work and good intentions on the part of our public officials, when economists and historians look back on the current financial crisis they are likely to conclude that government intervention prolonged and deepened it. In particular, officials at the Federal Reserve, the Securities and Exchange Commission and the Treasury Department are to blame for publicly losing confidence in the very economic system they are supposed to protect.
>
> The Fed, the Treasury and the SEC appear to be in a state of panic. A crisis mentality led the custodians of the U.S. capital markets publicly to jettison their lifelong commitments to the capital markets in favor of a series of short-term regulatory quick fixes…
>
> Letting markets work is messy and costly. Nevertheless, the only sensible way to deal with the current crisis is to force the companies who created the mess to bear at least some of the costs of their mistakes. Most of all, if the markets are to get back on track our regulators must put an immediate stop to their current practice of publicly demonizing the markets and work to restore confidence in the system.
