---
title: "Greenspan Defends His Legacy"
date: "2008-04-08"
categories: ["Economics", "Financial Markets"]
---

Former Fed Chair Greenspan defends his legacy in an [interview](http://online.wsj.com/article/SB120760341392296107.html?mod=hpp_us_whats_news "interview") with the WSJ:

> Mr. Greenspan now admits he was wrong about the improbability of a housing bubble. Yet he has long maintained that bubbles are an unavoidable feature of a dynamic economy. He pulls out a 1999 speech and shows, underlined in green marker, passages in which he warned of recurring but unpredictable patterns of overconfidence followed by investor panic. He does not share some foreign central bankers’ belief that their job is to defend against excessive asset-price inflation: No sensible policy, he maintains, could have prevented the housing bubble.
>
> “I am reasonably certain that I am right here,” Mr. Greenspan says. If proved wrong, he says, “I will change. I do not have a vested interest in holding wrong ideas.”…
>
> Unable to find out how many homes are bought with subprime mortgages, Mr. Greenspan spent several months designing his own data system. Some of what he has learned is going into a new chapter for the paperback edition of his book, to be released Aug. 26. It will explain events after last June, when he finished writing the original.
>
> The biggest question mark over Mr. Greenspan’s record is his decision to slash interest rates to 1% in 2003 and wait to raise them until 2004, and then only slowly.…
>
> To prevent deflation, the Fed spurred growth by keeping interest rates low. At the time, he notes, the only dissenting votes on the Fed policy committee were those who wanted to set rates even lower. The Fed, he said, initially raised rates gradually to give businesses and investors time to prepare. In 2004 and 2005, it raised rates faster than private economists expected…
>
> In Mr. Greenspan’s view, if the Fed’s policies were to blame, the housing bubble would have been mostly limited to the U.S. Yet, he argued, many other countries had housing bubbles, too. A better culprit, he suggested, was the glut of savings globally.
