---
title: "Interest Rates & Housing Affordability: Mike Rann’s Blame Shifting"
date: "2008-04-30"
categories: ["Economics", "Financial Markets", "Politics"]
---

[SA Premier Mike Rann](http://www.news.com.au/business/money/story/0,25479,23621403-5016110,00.html "SA Premier Mike Rann") writes to RBA Governor Stevens asking him not to raise interest rates in order to ‘maintain housing affordability.’  As RBA Deputy Governor Ric Battellino noted in his recent [presentation](http://www.rba.gov.au/PublicationsAndResearch/SubmissionsToParliamentaryCommittees/inquiry_into_housing_affordability_australia.pdf "presentation") to the Senate Select Committee on Housing Affordability, mortgage interest rates in Australia are no higher now than in the mid-1990s, when housing affordability was at record highs.  Instead, Battellino suggests another culprit in record low housing affordability:

> *the rise in house prices has been much faster than that in construction costs, so the implication is that most of the increase in house prices has been due to increases in the price of land.*

That would be the responsibility of state governments.

If [APM](http://www.theaustralian.news.com.au/story/0,25197,23620584-25658,00.html "APM") are to be believed, higher interest rates are improving housing affordability as we speak.
