---
title: "Labor’s Manufacturing Fetish"
date: "2008-06-12"
categories: ["Economics", "Financial Markets"]
---

The ALP’s manufacturing fetish was evident when it was in opposition.  Kevin Rudd [said back in 2006](../2006/a_fork_in_the_road_best_left_untravelled.qmd "said back in 2006") that he wanted Australia to be ‘more than a mine for China and a beach for the Japanese.’  The subsequent appointment of the left’s Kim ‘Il’ Carr as industry minister in the new government was also a bad sign.  Australians will now start paying the price for this manufacturing fetish through local production of hybrid cars, one of the worst industry policy decisions in 20 years.  As [Henry Ergas](http://www.theaustralian.news.com.au/story/0,25197,23849172-7583,00.html "Henry Ergas") notes:

> *In an economy that is pushing over-full employment, increased subsidies to assembling cars only diverts resources from more productive uses. In addition, according to recent estimates from the Productivity Commission, “more than \$1 billion is redistributed each year to the automotive industry (a majority of which is foreign owned)”. The consequence is that these subsidies will attract further inputs to an industry that is already far from making productive use of scarce resources, magnifying the waste. It would have been better had Rudd and Brumby scattered the dollars on the streets of Melbourne.*
