---
title: "Mac Attack II: Gans Responds"
date: "2008-09-08"
categories: ["Economics", "Financial Markets"]
---

[Joshua Gans](http://economics.com.au/?p=1750 "Joshua Gans") has responded to my CIS paper, [Government Intervention in Mortgage Finance: The Case Against ‘AussieMac.’](http://www.cis.org.au/issue_analysis/IA99/ia99.pdf "Government Intervention in Mortgage Finance: The Case Against ‘AussieMac.’")

Gans suggests that the main difference between us is that I don’t ‘believe that markets work imperfectly.’  In fact, all markets are necessarily imperfect to some degree and I do not know of many economists who argue otherwise.  The issue is whether government intervention can improve on market-based outcomes. 

We probably do have different interpretations of the credit crisis, reflecting a somewhat different view of the functioning of markets.  Market efficiency does not mean that markets never make mistakes.  What matters is whether they are ultimately self-correcting.  We may not particularly like the price signals generated by this process, but that does not mean that the price signals are wrong. 

Gans suggests that ‘to spend time attacking Freddie and Fannie is not particularly useful for the Australian debate.’  Since AussieMac was explicitly modelled on Freddie and Fannie (hence the name), the US experience must be relevant, unless one can point to significant differences between AussieMac and the US GSEs.

Gans correctly singles out the implicit government guarantee as the main problem with Freddie and Fannie, but making the guarantee explicit, as the US has done now, does not entirely solve the problem.  As Gans concedes, this still leaves taxpayers on the hook, which may create perverse incentives.  Gans says ‘Kirchner appears here to be arguing that the government should come out and say that it will not bail-out any Australian bank or large non-bank should it get into financial difficulty.’  My view is that government should if anything guarantee certain classes of depositors rather than financial institutions.  Policymakers should aim to keep private financial risk off the government’s balance sheet.  Gans wants Australian taxpayers to take effective ownership of 5-10% of the market for residential mortgage-backed securities, but with no mechanism to ensure that the government’s funding advantage in capital markets would be passed on to consumers.

On housing affordability, Gans says that:

> *Kirchner also argues that our proposal will increase the demand for housing and therefore, not improve housing affordability. This is a common mis-conception. Put simply, the ONLY way our proposal will increase the demand for housing is by making the financing of that housing more affordable.*

I should have been clearer on this point.  Lower lending rates would only add to demand all else being equal.  But as Gans correctly points out, all else is not equal.  Lower rates would likely feed through to house prices, with adverse implications for both housing affordability and demand.  Housing affordability is really a function of the supply and demand for houses rather than the supply and demand for housing finance. 

Gans says of the US rescue plan for Freddie and Fannie that ‘the big losers will be shareholders in Fannie and Freddie, the very people Kirchner were arguing were the big winners in this game.’

It is quite likely that shareholders in Freddie and Fannie will be wiped-out, but only after decades of using public guarantees to secure private profits.  The fact that shareholders may ultimately be wiped-out is of no comfort to anyone.  Gans has not addressed the issue of the failure to pass through their funding advantage to consumers. 

He has also not addressed the issue of whether the Reserve Bank would trade-off any reduction in retail lending rates against changes in the official cash rate.  The [calculator on the AussieMac web site](http://aussiemac.org/AussieMac/Home.html "calculator on the AussieMac web site"), which purports to show the cost of not proceeding with AussieMac, actually works against the proposal.  Could the RBA ignore an easing in credit conditions of the magnitude suggested by their calculator?  I doubt it.
