---
title: "Meganomics: Demand Without Supply"
date: "2008-03-15"
categories: ["Economics"]
---

[George Megalogenis’s](http://www.theaustralian.news.com.au/index/0,25201,5013592,00.html "George Megalogenis’s") proposed solution to record low housing affordability – make investment in housing less attractive through higher taxes:

> *It can only be done by making property less attractive than other investments…bricks-and-mortar should lose its taxpayer supports.*

The analytical error Megalogenis makes is to assume that the attractiveness of housing as an investment only contributes to demand and higher house prices, but not to supply.  It is the same error he and many others make in assuming that tax cuts are necessarily inflationary, contributing only to demand, while the supply-side of the equation is completely ignored.  Megalogenis is not alone in this.  Chris Richardson has also argued that abolishing the principal residence exemption from capital gains tax would improve housing affordability, because he views house prices as being largely driven by demand and not supply.

As we have noted previously, the record low in housing affordability has only one solution: build more houses.  A very simple reform that would quickly address Australia’s growing shortage of dwelling stock and its inflationary consequences would be to abolish capital gains tax on investment property, to put it on the same footing as owner-occupied housing.  Since assets are acquired out of after-tax income, capital gains tax is a form of double taxation on saving and serves only to lower the nation’s capital stock, including the stock of houses.
