---
title: "Monetary and Fiscal Policy Effectiveness in a Globalised World"
date: "2008-12-22"
categories: ["Economics", "Financial Markets", "Fiscal Policy", "Monetary Policy"]
---

Alan Greenspan, interviewed in [Die Zeit](http://www.zeit.de/online/2008/05/interview-greenspan-english "Die Zeit"), on the effectiveness of monetary and fiscal policy:

> Global forces can now override most anything that monetary and fiscal policy can do. Long-term real interest rates have significantly more impact on the core of economic activity than the individual actions of nations. Central banks have increasingly lost their capacity to influence the longer end of the market. Two to three decades, ago central banks were dominant throughout the maturity schedule. Thus, the more important question is the direction of long-term real interest rates…
>
> The resources of central banks relative to the size of global forces have markedly diminished. We have 100 trillion dollars of arbitragable long-term securities in the world today so that even large movements initiated by central banks have little impact. Until the seventies, central banks and finance ministries were able to hold exchange rates fairly stable. Since then, the ability to intervene in the exchange markets and stabilize the rates has gone down very dramatically. And that is also true for other financial markets. Global forces fostering global equilibrium have become by far the most dominant influence for financial and economic activity. Governments have ever less influence on how the world works.

The way it should be.
