---
title: "More Monetary Policy Central Planning from the AEI"
date: "2008-04-14"
categories: ["Economics", "Financial Markets"]
---

The AEI’s [John Makin](http://online.wsj.com/article/SB120813349057411671.html?mod=opinion_main_commentaries "John Makin") wants the Fed to print money and centrally plan asset prices:

> The monetary easing I’m recommending can occur by having the Fed print money to purchase mortgages directly, or purchase Treasury securities directly…
>
> The postbubble period has yielded some very unattractive policy alternatives.  They clearly underscore the rationale for having the Fed target asset prices – in a world where asset markets affect the real economy more than the real economy affects asset markets.

Makin’s argument is that this is preferable to a nationalisation of the mortgage industry.  In fact, a temporary nationalisation of the mortgage market to facilitate an orderly work out would be relatively harmless in comparison.  In any event, there is no guarantee that one policy option would prevent the other.

As we have noted previously, John Makin and Desmond Lachman have consistently positioned the AEI as one of the most interventionist think-tanks in Washington on macro policy issues.  By way of contrast, the Peterson Institute’s [Adam Posen](http://www.petersoninstitute.org/publications/wp/wp06-1.pdf "Adam Posen") has argued cogently against the dangers of asset price targeting on the part of central banks.  As Posen notes, if we live in ‘a world where asset markets affect the real economy more than the real economy affects asset markets,’ then only by engineering massive booms and busts in the real economy could central banks hope to manage asset prices.
