---
title: "Nelson, Swan and RBA Independence"
date: "2008-04-08"
categories: ["Economics", "Financial Markets", "Politics"]
---

[Treasurer Wayne Swan](http://www.theaustralian.news.com.au/story/0,25197,23503888-5013871,00.html "Treasurer Wayne Swan"), responding to opposition leader Brendan Nelson’s view that the RBA has gone too far in raising interest rates, says that:

> *The fact that Dr Nelson and the Liberals can’t decide whether they still support the independence of the Reserve Bank or not shows just how badly the Liberals have lost their way on the economy.*

This is a common misunderstanding of what it means for the RBA to be independent of government.  At its most basic, RBA independence means that it is free to set interest rates without the approval of the Treasurer.  The RBA enjoys what is often called ‘operational independence.’

This is no sense precludes the government or opposition from taking a different view on monetary policy to the RBA or being publicly critical of central bank policy actions.  The RBA has been made progressively more independent of government precisely in order to facilitate differences of opinion with government.  Divided authority in relation to monetary and fiscal policy is a valuable institutional protection against macroeconomic policy mistakes.  Under the Reserve Bank Amendment (Enhanced Independence) Bill, the RBA Governor will enjoy such a high level of statutory independence that public criticism could hardly be viewed as a threat to the Governor’s position.

By the same token, the RBA would not be compromising its independence by speaking out on issues relating to its statutory responsibilities, provided it does so in a non-partisan fashion.  Former RBNZ Governor Don Brash would frequently lecture the New Zealand government on structural issues, because monetary policy is necessarily conditioned on structural factors over which the central bank has no direct control.  Brash would frequently point out that if politicians want strong growth, together with low inflation and low interest rates, then various structural measures outside the scope of monetary policy could assist in this task.  When he was Chairman of Federal Reserve, Alan Greenspan would also publicly canvass a wide-range of economic policy issues beyond the immediate scope of monetary policy.

In Australia, by contrast, mistaken notions of RBA independence are used to suppress public debate over economic policy.
