---
title: "New Role"
date: "2008-08-05"
categories: ["Economics"]
---

I have a taken up a new position as a Research Fellow with the [Centre for Independent Studies](http://www.cis.org.au "Centre for Independent Studies").  I will still be using the blog to highlight the work I’m doing at CIS, so stay tuned.  The weekly newsletter has been discontinued.  The Business Spectator column will also be discontinued in its current format.

Part of my role is to involve other economists in the work of the Centre.  If you are interested in contributing to the CIS research program, I would encourage you to get in touch (skirchner-at-cis.org.au).  CIS has several formats for publishing economic and other research, ranging from short journal articles to Occasional Papers and Policy Monographs.

The easiest way to stay across the work of CIS is to become a [member](http://www.cis.org.au/support_cis/support_membership.html "member"), which entitles you to receive all CIS publications by mail, including my output.  Donations over and above the annual membership rate are tax deductible.  You will be helping to ensure that some of the ideas developed on this blog over the years are given increased prominence.
