---
title: "None Dare Call it Conspiracy"
date: "2008-02-09"
categories: ["Economics", "Financial Markets"]
---

[Terry McCrann](http://www.theaustralian.news.com.au/story/0,25197,23182453-14743,00.html "Terry McCrann") on the AFR’s conspiracy theorists:

> Despite the “best” efforts of The Australian Financial Review during the week to concoct an absurd conspiracy out of the Treasurer and Prime Minister’s “shock discovery” of an inflation problem.
>
> Did anyone down at the Fin notice that the Reserve Bank increased the official interest rate smack in the middle of the election campaign? Something that it had never previously done, and was regarded by many as something it would never - or even should - do?
>
> That sorta, kinda, suggested someone in the official family was worried about inflation. Worried enough that it couldn’t wait a couple of weeks until the election was out of the way.
>
> The very strong suggestion from some quarters that that was exactly what the RBA should do, so as not to “politicise” rates, provides an interesting counterpoint to the Fin’s (completely untrue and quite outrageous) slur.
>
> Surely for the RBA to have postponed its rate rise would have been to engage in exactly the subterfuge about inflation becoming a problem that the Fin accused Treasury and in particular Treasury head Ken Henry of doing.
>
> There was no conspiracy, there was no inflation surprise. Treasury upped its inflation forecasts even before seeing the all-important September quarter CPI numbers. And it was those CPI numbers that set inflation alarm bells ringing all over town, and especially above Martin Place in Sydney.
>
> Self-evidently. There was no official rate rise in September or in October. But there had been in August; again a pointer to the beginning of concern.
