---
title: "Oil Aplenty: Debunking the Peakniks"
date: "2008-03-04"
categories: ["Economics", "Financial Markets"]
---

[Nansen Saleri](http://online.wsj.com/article/SB120459389654809159.html?mod=opinion_main_commentaries "Nansen Saleri"), former head of reservoir management for Saudi Aramco, debunks the peakniks in the WSJ:

> The world is not running out of oil anytime soon. A gradual transitioning on the global scale away from a fossil-based energy system may in fact happen during the 21st century. The root causes, however, will most likely have less to do with lack of supplies and far more with superior alternatives. The overused observation that “the Stone Age did not end due to a lack of stones” may in fact find its match.
>
> The solutions to global energy needs require an intelligent integration of environmental, geopolitical and technical perspectives each with its own subsets of complexity. On one of these—the oil supply component—the news is positive. Sufficient liquid crude supplies do exist to sustain production rates at or near 100 million barrels per day almost to the end of this century.
>
> Technology matters. The benefits of scientific advancement observable in the production of better mobile phones, TVs and life-extending pharmaceuticals will not, somehow, bypass the extraction of usable oil resources.
