---
title: "Peak Oil Nutters"
date: "2008-01-26"
categories: ["Culture & Society", "Economics", "Financial Markets"]
---

The [WSJ](http://online.wsj.com/article/SB120128939885117541.html?mod=hpp_us_pageone "WSJ") profiles some typical Peak Oilers:

> It was around midnight one evening in November when Aaron Wissner shot up in bed, jolted awake by a fear: He wasn’t fully ready for the day when the world starts running low on oil.
>
> Yes, he had tripled the size of the garden in front of the tidy white-clapboard house he shares with his wife and infant son. He had stacked bags of rice in his new pantry, stashed gold valued at \$8,000 in his safe-deposit box and doubled the size of the propane tank in his yard.
>
> “But I felt panicky, like I needed more insurance,” he says. So the 38-year-old middle-school computer teacher put on his jacket and drove to an all-night gas station, where he filled three, five-gallon jugs with gasoline.
>
> “It was a feel-good moment,” says his wife, Kimberly Sager. “But he slept better.”

Not sure how a few bags of rice, a propane tank and a few grand in gold is meant to help with [TEOCAWKI](http://en.wiktionary.org/wiki/TEOTWAWKI "TEOCAWKI"), but like they say, whatever helps you sleep at night.

At least someone is out there trying to give the peak oilers an education:

> *Three weeks after their first immersion, the couple drove to a peak-oil conference in Ohio, where lecturers showered them with statistics on demand curves and oil-field depletion rates. Then, at a conference in Denver, a man in a chicken suit called them crazies as he passed our fliers arguing that the world still has plenty of oil.*

I’m with chicken suit guy.
