---
title: "Peak Oil as Doomsday Cult"
date: "2008-03-09"
categories: ["Economics"]
---

[Derek Brower](http://commentisfree.guardian.co.uk/derek_brower/2008/03/scraping_the_barrel.html "Derek Brower"), editor of the [Petroleum Economist](http://www.petroleum-economist.com/ "Petroleum Economist"), on peak oil cultism:

> Worries about a peak in oil production, however, are not moving the oil markets. I doubt Jeremy Leggett thinks they are, but his article yesterday implicitly linked the peak oil theory with high oil prices. It also claimed that a growing number of oil executives, like Total boss Christophe de Margerie, now support the theory.
>
> Not really. What worries executives like de Margerie isn’t a geological peak. Industry studies show remaining reserves to be literally trillions of barrels greater than the figures offered by the peak oil theorists. They’re worried about getting access to the good stuff. Increasingly, it lies in countries that don’t much like western companies. De Margerie and other executives are simply doing what they always do: putting pressure on producer countries to open up.
