---
title: "Peak Oilers in Simon-Ehrlich Wager"
date: "2008-02-08"
categories: ["Economics", "Financial Markets"]
---

A group of Peak Oilers [put their money where their mouth is](http://blogs.wsj.com/environmentalcapital/2008/02/07/peak-oilers-put-money-where-mouths-are/ "put their money where their mouth is"):

> Reveling in the role of the fly tweaking the elephant, a group of peak-oil proponents has challenged prominent oil-industry consultancy Cambridge Energy Research Associates to a not-so-friendly wager.
>
> If CERA proves correct in its prediction that global oil production will rise by 20 million barrels per day by 2017, then the challengers, the Association for the Study of Peak Oil & Gas, will hand CERA a check for \$100,000 nine years hence. If oil production falls short of CERA’s projection, as the group known as ASPO projects, ASPO will get the bragging rights and the check – and donate the money to charity.
>
> CERA, the Boston-based company headed by prominent consultant Daniel Yergin, forecasts that global oil-production capacity could rise to 112 million barrels per day in 2017. Today, according to CERA, capacity is about 91 million barrels.
>
> “That’s a vision in search of reality,” Steve Andrews, co-founder of ASPO’s U.S. branch, said in a statement it sent out yesterday. Who knows whether ASPO’s finances will peak before then. But along with its press release, ASPO sent a copy of what it said is a bank letter of credit guaranteeing its \$100,000 bet.

While it’s scary to think the peak oilers have this much money to throw around, their willingness to back their view with an [Ehrlich-Simon type bet](http://en.wikipedia.org/wiki/Simon-Ehrlich_wager "Ehrlich-Simon type bet") is praiseworthy.  Having said that, the criticism of peak oil does not necessarily turn on specific outcomes for oil production, but on whether a prospective peak in production has any long-term relevance.
