---
title: "Raining on ‘Rainy Day’ Richardson"
date: "2008-05-10"
categories: ["Economics", "Financial Markets"]
---

[Terry McCrann](http://www.theaustralian.news.com.au/story/0,25197,23672843-14743,00.html "Terry McCrann") poses some questions to Chris ‘[Rainy Day](http://www.google.com.au/search?q=%22chris+richardson%22+%22rainy+day%22&hl=en&cr=countryAU&start=0&sa=N "Rainy Day")’ Richardson:

> What would have been - dangerously - fiscally irresponsible is to have not had the cuts each year. If Costello had listened to the twitterings of Access Economics, which opposed every single one of the yearly cuts, the budget would be groaning under surpluses of \$70 billion a year or more.
>
> Ceteris paribus - all other things being equal - as the economists like to say. When, of course, they wouldn’t have been, either in terms of the impact on the economy or the political process.
>
> It was hard enough keeping the hands of his cabinet colleagues, from the prime minister down, off even the tax cut-reduced surpluses.
>
> Even the team at Access would - should be forced to - concede the literal impossibility of letting those surpluses mount ever higher. But perhaps Access’s Chris Richardson could say when over the last five years and how such huge surpluses would have been spent.
>
> And/or how they would be dispersed today and tomorrow. He objects to the current \$31 billion of tax cuts over the next four years, at the supposed cost of higher interest rates.
>
> I doubt, though, that he would be endorsing cuts of \$100 billion over that time frame. Just to take the last three years of Costello’s tax cuts.
