---
title: "Rate Cuts by Christmas?  Good Luck with That!"
date: "2008-03-05"
categories: ["Economics", "Financial Markets"]
---

If you believe the interbank futures market, then there is a small chance the RBA will be cutting the official cash rate by November this year.  This is partly based on the market’s reading of the statement accompanying yesterday’s increase in official interest rates, in which the RBA focused on the expected moderation in domestic demand and inflation.  This is simply a reiteration of the RBA’s February SOMP forecasts, but these forecasts look increasingly aspirational. 

Today’s December quarter national accounts confirmed headline and non-farm GDP growth were both running above the RBA’s forecasting assumptions.  Domestic demand, far from slowing, accelerated over the December quarter to 1.6% q/q and 5.7% y/y in real terms.  The first bottom-up estimates for March quarter CPI inflation point to an increase of 1.3% q/q and 4.2% y/y.  With a nominal official cash rate of 7.25%, this points to a real cash rate of only 3.05%, although market-determined rates are significantly higher.

This is not the first time this tightening cycle that financial markets have priced in future reductions in interest rates.  Markets condition their view in large part on what the RBA says, or more importantly, what it does not say.  Yesterday’s statement gave no explicit forward policy guidance, but neither did the February tightening statement.  It was not until the February SOMP and Board minutes were released that the RBA bothered to mention its view that further significant increases in official interest rates would be required.

While an easing by Christmas is not impossible, this leaves markets grossly underpricing the risk of further intervening increases in official interest rates.
