---
title: "Rent-Seekers Gone Wild: ‘Shovel-Ready’ Edition"
date: "2008-12-20"
categories: ["Economics", "Fiscal Policy"]
---

Fiscal stimulus rent-seeking is not just for people:

> The [Association of Zoos and Aquariums](http://www.aza.org/newsroom/IntrastructureImportant/ "Association of Zoos and Aquariums") (AZA) today called for shovel-ready zoo and aquarium infrastructure projects to be eligible for Federal stimulus funding…
>
> “Zoos and aquariums are woven into the fabric of American life,” said AZA President and CEO Jim Maddy. “They are viewed by the public as important to the quality of life in their communities.”
>
> Many zoos have their roots in the Great Depression, when the Federal Work Projects Administration (WPA) helped build many zoos across America.
>
> “Zoos and aquariums will deliver incredible value for the Federal government,” added Maddy. “Investment in these institutions will pay-off twice, first in immediate job creation, and second, in the environmental education of our children for years to come.”

The same children can also look forward to paying for them for years to come. 

Come to think of it, I also have some ‘shovel-ready’ projects in my backyard that could do with some stimulus.
