---
title: "Robert Shiller’s Subprime Solution: The Democratisation of Finance or the Socialisation of Risk?"
date: "2008-09-22"
categories: ["Economics", "Financial Markets"]
---

Following is a review of Robert Shiller’s *The Subprime Solution*, part of a longer review essay I’m preparing on ‘Depression Economics.’

Robert Shiller’s *The Subprime Solution* illustrates the extent to which New Deal mythology still has a stranglehold on contemporary thinking about the recent credit crisis.  Shiller romaticises the New Deal, maintaining that ‘somehow a spirit of cooperation and change developed… ultimately embodied in the New Deal; while there was great unrest, there was also a sense of positive institutional change and progress, which offset the despair of the Depression.  Hostility between labor and management, and between rich and poor, was tempered by the sense that we were all moving together toward a more enlightened world’ (p. 99).  Shiller argues against ‘waging war on the financial elite’ (p. 177) in response to the recent credit crisis.  But as Amity Shlaes demonstrates in her history of the Great Depression, the New Deal was anything but cooperative and enlightened and waged an indiscriminate war against all levels of society.

Shiller sees the New Deal as a model for approaching many of the issues raised by the credit crisis: ‘the soundness of the ideas implemented in response to the financial crisis of the 1930s is evident in the durability of the institutions created.’  Shiller cites the government-sponsored enterprises Fannie Mae and Freddie Mac as examples of these institutions (pp. 13 and 106), as well as the Office of Federal Housing Enterprise Oversight (OFHEO), which arose in response to the housing crisis of the 1980s and was until recently responsible for regulating Fannie and Freddie.  Yet as Shiller himself notes the ‘OFHEO never showed any recognition of the housing boom… regulators did not seem to see the risk and they allowed Freddie and Fannie to go on supporting the housing boom’ (p. 53).  These institutions not only failed to prevent the most recent housing and credit crisis, but were in fact deeply implicated in promoting over-investment in US housing and diffusing mortgage debt instruments throughout the international financial system.  The failure of existing regulatory institutions to foresee or prevent the recent credit crisis highlights the fact these bodies are just as error prone as the private sector. 

There is a strong case for overhauling and rationalising the hundreds of institutions that already regulate the US financial system, but Shiller has a somewhat different focus.  Shiller claims that ‘we do not understand, or know how to deal with speculative bubbles’ (p. 3) and this is the fundamental cause of the recent credit crisis.  Shiller doesn’t define what he means by a ‘speculative bubble,’ perhaps because he realises that his previous attempts to do so were unsatisfactory.  The New Palgrave defines a bubble as ‘asset prices that exceed an asset’s fundamental value because current owners believe they can resell the asset at an even higher price.’  A moment’s reflection reveals that this definition is hopelessly inadequate, since it can be used to account for almost any innovation in asset prices.  Few people buy or hold an asset in the expectation of selling it at a lower price.  Attributing asset price inflation and deflation to speculative psychology begs more questions than it answers. 

The widely held notion of bubbles in asset prices has its origins in historical episodes that recent scholarship has exposed as myths.  Like many commentators, Shiller cites the Dutch tulip ‘mania’ of the 1630s as the paradigmatic example of a bubble, unaware that this episode, along with many other supposed historical examples of asset price bubbles, has been debunked by scholars such as Peter Garber and Anne Goldgar.  Like the romaticisation of the New Deal, the historical myth of financial ‘bubbles’ heavily conditions contemporary thinking about the recent credit crisis.

Shiller maintains that the ‘sub-prime crisis was essentially psychological in origin, as are all bubbles.  The crisis was not caused by the impact of a meteor or the explosion of a volcano’ (p. 24).  Yet Shiller’s ‘bubble thinking’ explanation might as well be a meteor or volcano for the all the light it sheds on asset price determination.  Shiller suggests that the propagation of ‘bubble thinking’ relies on ‘social contagion’, but otherwise has no explanation for why people make what he considers to be systematic and forecastable errors in relation to asset prices.  In contrast to Shiller, Peter Garber has it right when he says that:

> *‘“bubble” characterizations should be a last resort because they are non-explanations of events, merely a name that we attach to a financial phenomenon that we have not invested sufficiently in understanding.  Invoking crowd psychology - which is always ill defined and unmeasured - turns our explanation to tautology in a self-deluding attempt to say something more than a confession of confusion.  Fascinated by the brilliance of grand speculative events, observers of financial markets have huddled in the bubble interpretation and have neglected an examination of potential market fundamentals.’*

Not a single asset class has escaped being characterised as a ‘bubble’ in recent years: stocks, real estate, credit markets, oil, gold and even uranium prices have all apparently qualified as bubbles.  Shiller maintains that Sydney suffered a burst housing bubble on the strength of no more than a 2.4% decline in real house prices in 2004.  The widespread over-use of the ‘bubble’ characterisation is a strong indication that the term is empty of analytical content and describes no more than the normal functioning of markets.  Shiller himself describes both housing and oil markets as ‘inherently and deeply speculative’ (p. 63), without realising the obvious implication that speculation is a normal and essential element of market behaviour.

Despite his emphasis on speculative psychology, Shiller often lapses into fundamental explanations for the ‘bubble’ in US house prices.  In addition to the already noted regulatory failures, Shiller observes that the collapse in house prices was concentrated in the lower end of the market, where sub-prime lending activity was also concentrated (p. 36).  He also notes that ‘there are certain basic economic laws that – while they may be bent over shorter intervals – ultimately always assert themselves in the long run’ (p. 34).  Shiller’s earlier work, *Irrational Exuberance*, was largely built around the observation of statistical mean reversion in asset prices, with the behavioural finance component tacked on in an effort to disguise the fact that he had nothing new to say about the determination of asset prices. 

*Irrational Exuberance* was based on an inaccurate prediction Shiller made in 1996, that the S&P 500 stock market index would show no real appreciation over the next 10 years and that ‘long run investors should stay out of the market for the next decade.’  In the event, between December 1996 and December 2006, the S&P 500 saw annualised returns of 5.89% after inflation and the reinvestment of dividends (4.22% without re-investment), despite a significant market downturn between 2000 and 2003.  Not surprisingly, Shiller demurred on predicting the future course of the stock market when he published *Irrational Exuberance* in 2000, contrary to the now widely held view that the book predicted the downturn in equity prices in that year.  Alan Greenspan’s December 1996 ‘irrational exuberance’ speech noted that ‘we should not underestimate or become complacent about the complexity of the interactions of asset markets and the economy… asset prices particularly, must be an integral part of the development of monetary policy.’  But Greenspan also took the view that the Fed should not second-guess the market on asset prices.  Greenspan’s intellectual humility was vindicated, whereas Shiller’s suggestion that he could forecast an irrational market was profoundly mistaken.

To his credit, Shiller argues against the widely held notion that ‘easy’ monetary policy was an exogenous cause of house price inflation.  Changes in the Fed funds rate had little relation to US mortgage interest rates and cannot account for a nine year uptrend in house prices (pp. 48-49).  That the Fed funds rate fell to 1% in 2003 only demonstrates the lack of traction the Fed enjoys over the US economy. 

As a leading exponent of behavioral finance, it is ironic that Shiller has no behavioral model.  He views a ‘speculative bubble’ as a sufficient explanation for any observed innovation in asset prices, relying on well known theoretical and empirical exceptions to the efficient markets hypothesis to support his view.  The efficient markets hypothesis is analogous to the idea of perfect competition in markets for goods and services.  No one believes that any real-world market for goods and services is perfectly competitive, but that does not invalidate the model’s analytical usefulness.  The same is true of the efficient markets hypothesis.  Just as the routine violations of perfect competition are often viewed as automatically justifying government intervention to correct market failure, exceptions to the efficient markets hypothesis have been combined with the historical bubble myth to argue that free markets deliver inefficient outcomes, without bothering to establish whether regulatory interventions could improve on these outcomes.\
\
The final chapter of Shiller’s book is devoted to a number of proposals designed to promote ‘the democratisation of finance,’ although some of these proposals could be more accurately characterised as ‘the socialisation of risk.’  His motivation is to ‘reduce the long-run incidence of speculative bubbles’ (p. 115).  Taking a leaf out of the literature on free banking, he argues for prices to be quoted in an inflation-adjusted unit of account to cure the money illusion he says is partly responsible for bubbles.  Yet the idea of inflation-adjusted or real returns as a benchmark for asset prices is already well understood and widely reported in the popular financial press.  His call for an improved ‘information architecture’ in relation to retail and wholesale financial products is for the most part unobjectionable, but is also an implicit admission that it is imperfect information and not speculative psychology that leads to inefficiencies in asset pricing - exactly what the efficient markets hypothesis would predict.

Shiller has been actively involved in the development of financial derivatives tied to house prices.  He maintains that the lack of opportunities for short-selling in real estate has promoted housing bubbles.  Yet there are ample opportunities to short-sell commodities such as oil and Shiller views these markets as equally bubble-prone.

Shiller’s most dangerous proposal is for ‘continuous work-out mortgages’, which are explicitly aimed at socialising risk.  Shiller is well aware of the moral hazard these instruments could create, but argues that ‘if it nevertheless encourages undesirable behaviour, it is at least undesirable behaviour whose costs have been covered’ (p. 159).  This is small comfort for those who would have to bear these costs. Shiller says we ‘must institutionalise generosity to the unfortunate’ (p. 174), but the already well-established institutions of the welfare state show disastrous social results when people are freed of the financial and other consequences of imprudent behaviour.  In socialising risk, Shiller’s proposals could encourage more financial risk-taking, with adverse consequences for the stability of financial markets and the real economy.  Shiller’s *Subprime Solution* illustrates how loose thinking about ‘bubbles’ in asset prices very quickly leads to proposals to replace free markets with permanent regulatory interventions that may do more harm than good.
