---
title: "Rudd and Greed"
date: "2008-10-29"
categories: ["Culture & Society", "Economics", "Financial Markets"]
---

I have an op-ed in today’s [Australian](http://www.theaustralian.news.com.au/story/0,25197,24567563-7583,00.html "Australian") responding to the Prime Minister’s attacks on ‘the culture of greed’:

> Scottish Enlightenment philosopher David Hume noted as long ago as 1741: “Avarice, or the desire of gain, is a universal passion which operates at all times, in all places and upon all persons.” One cannot explain episodic phenomena such as financial crises with reference to a constant such as human nature or rationality.
>
> The principal mistake the critics of free markets make is to assume that self-interest, greed and irrationality affect only private sector decision-makers. Politicians and regulators are just as prone to self-interested behaviour and do not become saints by virtue of elected or unelected office. The public sector and regulators are populated by the same species that is found in the private sector and financial markets. We should always be suspicious of claims to superior moral virtue coming from politicians.
