---
title: "The Futureless Future Fund"
date: "2008-02-28"
categories: ["Economics", "Financial Markets", "Politics"]
---

It says a lot about the Future Fund that our first real insights into its investment strategy and performance should come via a Senate Estimates Committee hearing.  As we have noted [previously](../2007/the_future_fund_versus_the_republic_of_azerbaijan.qmd "previously"), the Future Fund’s ranking in international comparisons of sovereign wealth fund transparency and accountability lies somewhere between that of the State Oil Fund of the Republic of Azerbaijan and the National Oil Fund of Kazakhstan. 

Given recent market conditions, it should not come as a huge surprise to learn that the Fund remains around 75% invested in cash.  This is little different from leaving the funds on deposit with the RBA, the more traditional home of budget surpluses.  This did not stop the headline writers (‘[Future Fund’s \$700m hit](http://news.google.com.au/news/url?sa=t&ct=au/4-0&fp=47c53a82616ecc0d&ei=PvPFR6fmN43oqwOjtdmRBg&url=http%3A//www.news.com.au/story/0%2C23599%2C23261282-2%2C00.html&cid=0 "Future Fund’s $700m hit")’; ‘[Future Fund Flounders](http://www.news.com.au/heraldsun/story/0,21985,23260967-661,00.html "Future Fund Flounders")’) and Coalition Senators from making hay out of the Fund’s few non-cash investments.  As we predicted [here](http://www.institutional-economics.com/index.php/section/articles/future_fund_or_future_eater/ "here"), the Future Fund’s investments will inevitably become a political football and today’s headlines are just a taste of what we will see as the Fund expands the scope of its investments.

Unfortunately for the Coalition, the Future Fund is very much a creature of its own making and in many ways emblematic of the political and intellectual exhaustion that led to the former government’s defeat.  This effectively lets the new government off the hook in relation to the Fund’s future performance under its current mandate

The new government is promising to hoard any increase in the budget surplus over and above the forward estimates. The government could very quickly notch-up budget surpluses of around 2% of GDP without any real effort, adding more than \$20 billion annually to the Fund’s assets.  With the Fund already set to meet its original mandate to provide for public sector super liabilities, Coalition Senators could make themselves useful by asking what further contributions to the Future Fund are actually for.
