---
title: "The Future Fund and the Statism of the Commentariat"
date: "2008-05-15"
categories: ["Economics", "Financial Markets"]
---

There is something about the Future Fund that brings out the latent statism of the commentariat.  Here’s [Alan Kohler](http://www.businessspectator.com.au/bs.nsf/Article/Future-fund-gets-even-bigger-EMSUX?OpenDocument " Alan Kohler"), praising the growing amount of revenue being hoarded by the Australian government:

> Sometime next year Australia will have its own \$US100 billion sovereign wealth fund (SWF) and the Government will have a positive net worth for the first time.
>
> …it finally puts Australia on the right side of global decoupling, as one of the world’s resource rich nations building wealth for the future. It’s been that for a while, except the proceeds have been frittered over the past few years.
>
> We still have the Anglo-Saxon west’s propensity for lots of personal and household debt, but at least the Government will be entirely debt-free (including \[sic\] pension obligations) and building real wealth.

What Kohler doesn’t seem to understand is that the Future Fund and its sister funds announced in this week’s Budget are simply holding vehicles for future government spending.  If the government were spending all of these funds today, Kohler would likely deem it irresponsible.  But it makes no difference whether future government spending is paid for out of current or future taxes (the investment returns on the Fund are simply compensation for the opportunity cost of not spending the money today).  It is far more likely that these funds will be ‘frittered away’ by government than by taxpayers.  All the Future Fund does is ensure that current taxpayers are now paying for the government frittering of the future, as well as the present.

The ‘real wealth’ being ‘built’ in the Future Fund is no such thing.  It comes entirely at the expense of the current wealth-generating capabilities of the private sector.
