---
title: "The Blindsiding of Peak Oil"
date: "2008-09-24"
categories: ["Economics", "Financial Markets"]
---

T Boone Pickens [pays the price](http://online.wsj.com/article/SB122221505732769415.html?mod=testMod "pays the price") for being long peak oil:

> the downturn in energy has blindsided the industry veteran, leaving one of his hedge funds that focuses on energy stocks down almost 30% through August. A smaller commodity-focused fund is down 84%.
>
> All in, the funds have lost around \$1 billion this year, a figure that includes \$270 million of personal losses. “It’s my toughest run in 10 years,” said Mr. Pickens, a former geologist who earned billions by building an oil company and investing in energy. “We missed the turn in the market, there’s nothing fun about it.”…
>
> Mr. Pickens says he’s shifted his funds’ portfolios to a more neutral stance, to keep his losses in check. That means he hasn’t fully benefited as oil prices jumped in the past few days to \$106.61 a barrel from about \$90.
