---
title: "The Real Ron Paul"
date: "2008-01-10"
categories: ["Politics"]
---

Regular readers will be aware that we are none too fond of the Ludwig von Mises Institute or Republican presidential candidate, Ron Paul.  [TNR](http://www.tnr.com/politics/story.html?id=e2f15397-a3c7-4720-ac15-4532a7da84ca "TNR") has an expose on them both.  The story is largely built around Paul’s old newsletters, revealing:

> decades worth of obsession with conspiracies, sympathy for the right-wing militia movement, and deeply held bigotry against blacks, Jews, and gays. In short, they suggest that Ron Paul is not the plain-speaking antiwar activist his supporters believe they are backing—but rather a member in good standing of some of the oldest and ugliest traditions in American politics…
>
> To understand Paul’s philosophy, the best place to start is probably the Ludwig von Mises Institute, a libertarian think tank based in Auburn, Alabama. The institute is named for a libertarian Austrian economist, but it was founded by a man named Lew Rockwell, who also served as Paul’s congressional chief of staff from 1978 to 1982. Paul has had a long and prominent association with the institute, teaching at its seminars and serving as a “distinguished counselor.” The institute has also published his books…
>
> The people surrounding the von Mises Institute—including Paul—may describe themselves as libertarians, but they are nothing like the urbane libertarians who staff the Cato Institute or the libertines at Reason magazine. Instead, they represent a strain of right-wing libertarianism that views the Civil War as a catastrophic turning point in American history—the moment when a tyrannical federal government established its supremacy over the states. As one prominent Washington libertarian \[not [Tom Palmer](http://www.tomgpalmer.com/archives/042375.php "Tom Palmer") - ed.\] told me, “There are too many libertarians in this country ... who, because they are attracted to the great books of Mises, ... find their way to the Mises Institute and then are told that a defense of the Confederacy is part of libertarian thought.”

[Bryan Caplan](http://econlog.econlib.org/archives/2008/01/pathological_in.html "Bryan Caplan") finds himself being ‘weirded out’ by Ron Paul:

> *I’m so used to being completely against everything that any publicly visible group is for, I don’t even know how to respond. When a teen holding a Ron Paul sign walks past me on the street, what am I supposed to do? Give him a thumbs up? Cheer? Stop him and start arguing about immigration? When my flight attendant asks me what I want to drink, do I say “I sympathize with your button”?  You tell me.*

To which someone replies in comments:

> *Just stop supporting Ron Paul. Solves the problem.*

[Virginia Postrel](http://www.dynamist.com/weblog/archives/002695.html "Virginia Postrel") wonders why people are surprised:

> *Thanks to The New Republic, libertarians who weren’t paying attention in the 1990s, don’t read Texas Monthly, and didn’t do their candidate research have now discovered that Ron Paul said—or, more likely, allowed to be said in his name (probably by Lew Rockwell)—nasty things in his newsletters. Much reaction can be found at Hit & Run, as well as Andrew Sullivan’s blog and The Volokh Conspiracy. The disclosures are not news to me, nor is the Paul campaign’s dismissive reaction a surprise. When you give your political heart to a guy who spends so much time worrying about international bankers, you’re not going to get a tolerant cosmopolitan.*
