---
title: "The Gittinomics of Stink"
date: "2008-03-26"
categories: ["Economics"]
---

[Ross Gittins](http://business.smh.com.au/now-for-the-shower-without-glory/20080325-21hf.html?page=2 "Ross Gittins") wants you to wash less and stink more:

> In the old days, if you got a bit sweaty you allowed the sweat to dry and thought nothing of it. These days, many people can’t rest until they’ve showered.
>
> And then there’s underarm body odour. It’s completely and utterly natural, we all have it, but since the spread of deodorant we’ve convinced ourselves it’s offensive and a sign of ill-breeding.
>
> So, much of our incessant showering arises not from a desire to be clean but from a relatively modern desire not to have a smell. I suspect many people have a quite exaggerated notion of the extent to which they smell - or would smell if they didn’t take as many showers as they do.
>
> Many of us feel a social obligation to maintain what we believe to be the prevailing standard of personal washedness.
