---
title: "The Collapse of the Development Expert Paradigm"
date: "2008-05-30"
categories: ["Economics"]
---

[Bill Easterly](http://www.ft.com/cms/s/0/4ee1a00e-2cb6-11dd-88c6-000077b07658.html "Bill Easterly") on the World Bank’s Growth Commission:

> The report of the World Bank Growth Commission, led by Nobel laureate Michael Spence, was published last week. After two years of work by the commission of 21 world leaders and experts, an 11- member working group, 300 academic experts, 12 workshops, 13 consultations, and a budget of \$4m, the experts’ answer to the question of how to attain high growth was roughly: we do not know, but trust experts to figure it out.
>
> This conclusion is fleshed out with statements such as: “It is hard to know how the economy will respond to a policy, and the right answer in the present moment may not apply in the future.” Growth should be directed by markets, except when it should be directed by governments.
>
> My students at New York University would have been happy to supply statements like these to the World Bank for a lot less than \$4m.
>
> Why should we care about the debacle of a World Bank report? Because this report represents the final collapse of the “development expert” paradigm that has governed the west’s approach to poor countries since the second world war. All this time, we have hoped a small group of elite thinkers can figure out how to raise the growth rate of a whole economy. If there was something for “development experts” to say about attaining high growth, this talented group would have said it.
