---
title: "The Revenge of the Revenue Hoarders"
date: "2008-02-08"
categories: ["Economics", "Financial Markets"]
---

The legislation to implement the government’s promised tax cuts will be introduced to parliament next week, but like a zombie army immune to intelligent argument, the advocates of increased Commonwealth revenue hoarding are [not beaten yet](http://www.theaustralian.news.com.au/story/0,25197,23178336-601,00.html "not beaten yet"):

> WAYNE Swan has called an end to the Howard government policy of returning excess budget surpluses as tax cuts, saying the Reserve Bank had been allowed to shoulder too much responsibility for controlling inflation with interest rate rises.
>
> The Treasurer said that under the Rudd Government, any windfall revenue would be allowed to mount up as a larger budget surplus and would be quarantined, either with the Reserve Bank or the Future Fund.
>
> “We will be banking any upward revisions to revenue, if they occur,” he told The Australian.
>
> Mr Swan said the previous government placed too much emphasis on the use of interest rates - or monetary policy - to control inflation, and did not do enough to control the budget with fiscal policy.
>
> “Monetary policy is a blunt instrument and that is why it is really important that fiscal policy plays a bigger role,” he said.

This has things exactly backwards.  It is fiscal policy that is the blunt and unwieldy policy instrument and Australia’s current inflation problem is first and foremost a failure of monetary not fiscal policy.

Increased Commonwealth revenue hoarding also runs counter to Treasury advice, which points to the positive implications for labour supply and potential output of lower taxes.  If the previous government had not cut taxes, labour market constraints would be an even greater threat to inflation and interest rates than they are now.  By contrast, Commonwealth revenue hoarding has no pay-off in augmenting the supply-side of the economy.
