---
title: "Who Lost the ‘War on Inflation’?"
date: "2008-01-23"
categories: ["Economics", "Financial Markets"]
---

The [December quarter CPI](http://www.abs.gov.au/AUSSTATS/abs@.nsf/ProductsbyReleaseDate/938DA570A34A8EDACA2568A900139350?OpenDocument "December quarter CPI") is nothing less than disastrous.  The 3.6% y/y average outcome for the statistical underlying measures is the worst result for underlying inflation since the great disinflation of the early 1990s and well above the 3.25% forecast in the RBA’s November Statement on Monetary Policy.  It is sobering to recall that these measures are preferred by the RBA because they capture the persistent component of inflation that forecasts future inflation outcomes. 

The government talks about a ‘war on inflation,’ but that war was lost by the RBA long before today’s CPI release.  Amid all the finger-pointing between the federal government and opposition, few have bothered to point out that the Reserve Bank is the only public institution in Australia with a specific mandate to control inflation.  Inflation is not some unfortunate exogenous event, unrelated to past monetary policy actions.  The inflation target breach tells us that the RBA was not doing its job properly 12-18 months ago.  In the US, the current and former Fed Chair are widely criticised for their supposed role in financial market problems not of their own making.  Yet in Australia, the RBA’s senior officers still enjoy almost unimpeachable authority while at the same time failing to meet their core mandate. 

If the RBA’s November Statement on Monetary Policy forecasts were realised, the RBA could perhaps have sat on its hands with a view to riding out the inflation target breach over the next 12 months and hope that international and domestic growth weaken sufficiently to return inflation to target in 2009.  The risk in doing so is that the RBA ends up validating an acceleration in domestic inflation, requiring an even more aggressive tightening response down the track, with greater downside risks for the domestic economy.  The tragedy of the RBA’s policy error on inflation is that it now has much less flexibility in responding to the deteriorating global growth outlook.  The RBA can be expected to raise rates at its February Board meeting, despite continued equity market volatility and aggressive Fed easing.
