---
title: "Australia must avoid America’s demographic stagnation"
date: "2020-11-23"
categories: ["Population & Migration"]
---

I have an op-ed in [The Mandarin](https://www.themandarin.com.au/145617-australia-must-avoid-americas-demographic-stagnation/) on why Australia must avoid America’s demographic stagnation. Text below the fold.

Australia must avoid America’s demographic stagnation

Even before the pandemic, the United States was experiencing its slowest population growth in a century, a combination of record low fertility and an increasingly restrictive approach to immigration. Previously a source of economic dynamism, productivity and innovation, demographics are now a drag on US national power.

America’s demographic stagnation is partly self-inflicted, the product of the Trump Administration’s war on immigration. Through more than 400 executive orders, President Trump steadily eroded cross-border people flows. The pandemic afforded his Administration a convenient cover to accelerate this anti-immigration agenda.

The US has tightened eligibility for key visa categories, most notably H1-B visas for skilled workers, already subject to a numerical cap, leading to a surge in denial rates.

The refugee program has been slashed to a record low of just 15,000, not much larger than Australia’s recently reduced program of 13,750. Historically, the US was a haven for as many as half the world’s refugees. It is now all but closed to asylum-seekers. 

The contribution of net migration to growth in the US working age population has fallen by 60% compared to its peak in the 1990s.

Contrary to much anti-immigration sentiment, net migration to the US on the part of low skilled workers has been negative over the last decade.

While a Biden Administration, in conjunction with Congress, could be expected to relax some of these measures, political inertia makes it unlikely policy will be quickly reversed.

According to the US Census Bureau, under a zero net migration scenario, the US population could be expected to peak at 333 million as soon as 2035, before going into outright decline and reach a low of 320 million by 2060.

This scenario may not be the most likely outcome, but it demonstrates the extent to which America’s demographic future is hostage to policy on immigration.\
The role of immigration in driving US economic growth has been significant. By one estimate, as much half of the aggregate productivity growth in the US between 1990 and 2010 was attributable to inflows of foreign science, technology, engineering and mathematics (STEM) workers.

With the US turning away skilled and other migrants, Australia has the opportunity to tap the global talent that might otherwise go there.

The US, Canada, UK and Australia normally receive around 70% of the world’s skilled migrants, with the US taking close to a half share for the OECD and a one-third share for the world as a whole.

Australia will increasingly be in competition with Canada for top talent. Canada has expanded its permanent immigration program to take as many a one million permanent migrants between now and 2022, around 350,000 per year.

The closing of Australia’s international borders to those on visitor and temporary migration visas and the rationing of inbound arrival and quarantine capacity have seen net overseas migration collapse. Treasury is assuming there will be net outflows in the current and next financial years, something Australia has not seen since 1946.

Population growth is assumed to slump to just 0.2% this financial year, the slowest since 1916-17 and weaker than the pre-pandemic US rate of just 0.5%.\
More seriously, the Australian government is assuming that there is no attempt to make-up for this lost net migration in future. Australia will suffer a permanent loss of population and productive potential relative to its pre-pandemic trajectory.

This permanent loss of population is not just a technical assumption, it is a policy choice. Australia could aim to make-up these pandemic-induced losses through its future migration program.

Before the pandemic hit, the government reduced the planning cap on permanent migration from 190,000 to 160,000. The cap is unlikely to be binding in the short-term given pandemic border closures and the labour market downturn, but should be set aside to allow NOM to play catch-up as the international border is re-opened.

The government should fund, partly through user charges, a scaled-up managed isolation and quarantine capacity to ease the current rationing of international arrivals.

Last year’s reduction in the permanent migration program pre-empted a new Population Planning Framework that was put in place before the pandemic. The Framework includes some useful transparency and inter-governmental coordination mechanisms, but also risks state government capture of federal immigration policy.

The NSW government used the process to argue for immigration to the state to be halved.

Against the backdrop of a higher unemployment rate, the Australian government needs to better link immigration and population growth to pandemic recovery and national security imperatives.

America’s inward turn on immigration is Australia’s demographic opportunity, but only if policymakers choose to embrace it.

Dr Stephen Kirchner is program director, Trade and Investment, at the United States Studies Centre at the University of Sydney. He is the author of Avoiding US-Style Demographic Stagnation: The Role of Immigration and Population Growth in Australia’s Post-Pandemic Recovery.
