---
title: "Avoiding US-style demographic stagnation: The role of immigration and population growth in Australia’s post-pandemic recovery"
date: "2020-11-16"
categories: ["Population & Migration"]
---

I have a new report out with USSC [Avoiding US-style demographic stagnation: The role of immigration and population growth in Australia’s post-pandemic recovery](https://www.ussc.edu.au/analysis/avoiding-us-style-demographic-stagnation-the-role-of-immigration-and-population-growth-in-australias-post-pandemic-recovery).

In the report, I compare recent demographic trends in Australia and the US, in particular, the decline in the US population growth rate to the lowest in a century, even before the onset of the pandemic. This is the product of record low fertility and the Trump Administration’s tightening of US immigration policy, which the Biden Administration will not be able to unwind quickly.

In Australia, population growth is set to slow to its lowest rate since 1916-17, mainly as a result of pandemic-related international border closures. Treasury is assuming no attempt is made in future to make-up the loss in net overseas migration, implying a permanent loss of populaiton and productive potential relative to a no-pandemic counterfactual.

In the report, I call for a federal government-funded increase in managed isolation and quarantine capacity to ease the rationining of international arrivals in the short-term. The government should also set aside its budget planning cap on permanent migration numbers with a view to making-up for lost NOM and reducing the permanent hit to Australia’s population.

I also argue that the government’s National Population and Planning Framework risks state government capture of federal immigration policy.

There is write-up of the report by Shane Wright in the [SMH/Age](https://www.smh.com.au/politics/federal/no-recovery-without-migration-drive-to-revisit-population-growth-20201114-p56enm.html).
