---
title: "China’s behaviour warrants increased scrutiny of foreign investment"
date: "2020-07-09"
---

I have an op-ed in [The Mandarin](https://www.themandarin.com.au/135984-opinion-chinas-behaviour-warrants-increased-scrutiny-of-foreign-investment/) on the government’s new national security test for foreign acquisitions. Full text below the fold.

China’s behavior warrants increased scrutiny of foreign investment\
The Australian government has joined a global trend to expand the scope of its foreign investment screening process based on national security concerns. While notionally non-discriminatory in application, the new measures are clearly aimed at potential Chinese acquisitions.\
Following recent cyberattacks on Australia, it Is no surprise that Western governments are reviewing foreign investment laws in response to China’s behavior. Yet the cyberattack also demonstrates that there are numerous and potentially more threatening vectors of foreign attack than just foreign ownership.\
Blocking foreign investment at the border may lead to a false sense of security given vulnerabilities behind the border.\
Yet even as Western governments have increased their scrutiny of foreign investment, Chinese outbound investment has collapsed, with Beijing increasingly focused on investment at home rather than abroad.\
According to the Rhodium Group, in the first five months of 2020, China’s outbound acquisitions fell 71% in volume terms and 88% in value terms compared to the same period last year.\
Fears that depressed asset values due to COVID-19 would lead to a Chinese foreign shopping spree have not yet eventuated. Chinese regulators are suspicious of their own outbound capital flows, even if only for economic reasons. This helps explain why China remains relatively under-invested abroad for a country of its size.\
The Australian government will introduce legislation to impose a new national security test on foreign investments that raise national security concerns but would otherwise fall below existing monetary screening thresholds.\
The increased focus on national security concerns is consistent with the recommendations of my 2018 United States Studies Centre report with Jared Mondschein, which argued that national security should be the main focus of Australia’s foreign investment screening regime. It is also consistent with the Productivity Commission’s recommendations in its report on foreign investment released this week.\
However, both our report and the Productivity Commission envisaged national security taking over from the laundry list of policy concerns that have been the focus of the foreign investment review process under the existing national interest test.\
Some of the more traditional economic and other issues that have arisen in the screening of foreign investment are better left to behind-the-border regulation by domestic regulators rather than ministerial determinations of the national interest.\
These open-ended national interest concerns have often served as fig leaves for ministerial interference in cross-border transactions that became politicised for various reasons. Previous Treasurers have often ignored the advice of domestic regulators in rejecting an acquisition.\
These essentially political decisions invoking the national interest undermine confidence in the foreign investment review process, particularly on the part of investors.\
Now that the government faces genuine threats to the national interest from foreign actors, it must address the challenge of devising a screening process that protects those interests, while maintaining investor certainty and confidence.\
The new national security test will operate alongside the existing national interest test. The government says that where the broader national interest test applies, only that test will be used in assessing foreign investment, since it already takes in national security as a consideration.\
The new national security test is thus designed to capture investments that would not otherwise be triggered by the existing screening framework.\
The proposed test represents an expansion of the scope of the existing review process rather than a rationalisation designed to prioritise national security.\
The new test will apply to a ‘sensitive national security business’ that will be defined by regulation, but the definition is likely to be expansive.\
The government should aim to develop and publish clear and consistent principles for the application of the new test, something that has traditionally been lacking in Australia’s regulation of foreign investment.\
Moreover, now that the foreign investment review process has serious national security issues to consider, the government should do away with the largely superfluous regulation of foreign investment at the border in relation to non-security concerns in favour of behind the border regulation on a national treatment basis.\
In the 45-year history of the Foreign Acquisitions and Takeovers Act, it is hard to point to many actual or prospective foreign acquisitions that threatened the national interest, as opposed to politicians’ perceptions of their own interests.\
But China’s behavior since 2012 means that the balance of those risks has now changed, justifying wider scrutiny of security risks at the border.\
With national security concerns looming larger than ever before, the bilateral investment relationship with the United States, our biggest investment partner, will only grow in importance.\
Dr Stephen Kirchner is Program Director, Trade and Investment, at the United States Studies Centre at the University of Sydney. He is the author with Jared Mondschein of Deal-breakers? Regulating foreign direct investment for national security in Australia and the United States.
