---
title: "Don’t bank on US dollar demise"
date: "2020-01-09"
categories: ["Financial Markets"]
---

I have an op-ed in the [AFR](https://www.afr.com/markets/currencies/don-t-bank-on-us-dollar-demise-20200108-p53pos) arguing that the perennial predictions of the US dollar’s demise reflect a fundamental misunderstanding of the sources of its dominant role in the world economy. The US dollar’s advantages are not easily replicated by putative rivals (text below the fold).

Don’t bank on US dollar demise

Predictions of the US dollar’s demise are a recurring staple of financial market commentary. The equally routine failure of these predictions reflects widespread misunderstanding of the sources of the US dollar’s role in the world economy.

This role has little to do with so-called ‘reserve currency’ status, which is more symptom than cause. It owes more to the unrivalled size, depth and liquidity of US dollar capital markets, backed by relatively sound political and economic institutions.

These institutions are under challenge, giving new impetus to old predictions of the end of the dollar era. Under the Trump Administration, the US dollar exchange rate has become increasingly politicised. Trump has called for a weaker exchange rate, a move away from a long-standing and bipartisan rhetorical position favouring a ‘strong dollar.’

This increased politicisation is partly a symptom of the bouts of strength in the US dollar exchange rate since Trump assumed office, although on net it is little changed since the 2016 Presidential election. 

These episodes of US dollar strength are not inconsistent with a chaotic trade war and the Federal Reserve cutting interest rates. The US dollar exchange rate often appreciates on increased political and macroeconomic risk.

The United States is the premier producer of safe assets that act as stores of value for the world’s savers. The demand for these assets has increased at a faster pace than the US can produce them.

Changes in the regulation of financial institutions and markets since the 2008 financial crisis have increased the quantity of safe assets financial intermediaries are required to hold. This increased demand helps explains why yields on US Treasuries have been in low in recent years. 

One way the excess demand for US dollar assets can be satisfied is through an appreciation in the US dollar exchange rate so these assets becomes more expensive for those outside the US.

The US dollar also appreciates in response increased economic policy uncertainty. Menzie Chinn has shown that a 1% increase in the Global Economic Policy

Uncertainty Index raises the real value of the US dollar by 0.2%, controlling for relative interest rate, inflation and economic growth differentials with the rest of the world.

The 60% increase in policy uncertainty under Trump has added around 12% to the real value of the US dollar, holding these other influences constant.  The appreciation exacerbates trade tensions by weighing on US export competitiveness.

Contrary to popular myth, the US dollar’s role owes very little to its status as a so-called ‘reserve currency.’ The fact that the US dollar makes up much of the world’s official foreign currency assets held by central banks is a symptom, not a cause, of the US dollar’s dominant role.

Nor does the role of the US dollar depend on a ‘strong dollar’ policy. So long as the US enjoys a floating exchange rate and an independent Federal Reserve continues to target domestic inflation, the US does not have a meaningful or effective exchange rate policy.

While President Trump has shifted US official rhetoric by signalling a preference for a weaker exchange rate to boost US export competitiveness, this preference means little without backing from Federal Reserve monetary policy.

The US Treasury, with or without the support of the US Federal Reserve, could intervene in foreign exchange markets with a view to influencing the value of the exchange rate. However, such intervention on its own would have little to no sustained effect and would do little to change US export competitiveness in the long-run.

For all the talk of ‘currency wars,’ exchange rates are difficult to weaponise.

In principle, the US dollar’s role could be supplanted by other currencies. But the US dollar’s nearest potential rivals are beset with problems. The euro is part of a dysfunctional monetary union, giving rise to political and diplomatic tensions that are tearing the European Union apart. There has been little net change in the euro’s share of the international monetary system in the two decades since its launch, despite the high hopes held for it in the late 1990s.

China’s campaign to internationalise its renminbi from 2009 as part of an effort to leverage domestic reform efforts has failed. China’s leadership quickly backed away from reforms to make the RMB exchange rate more market-based in 2015, viewing the associated volatility as a sign of disorder. Standard Chartered’s measure of RMB globalisation has flatlined since 2016.

For all the concerns about the health of US domestic politics and the sustainability of its public finances, the US dollar’s dominant global role looks set to persist.

Dr Stephen Kirchner is Program Director, Trade and Investment, United States Studies Centre at the University of Sydney. He is the author of The ‘Reserve Currency’ Myth: The US Dollar’s Current and Future Role in the World Economy.
