---
title: "Failure to converge? The Australia-US productivity gap in long-run perspective"
date: "2020-04-16"
categories: ["Free Trade & Protectionism"]
---

I have a new [report](https://www.ussc.edu.au/analysis/failure-to-converge-the-australia-us-productivity-gap-in-long-run-perspective) out with the United States Studies Centre on the Australia-US productivity gap in long-run perspective.

The report discusses the relationship between US and Australian productivity and how the openness of the Australian economy has allowed us to import productivity trends from the global frontier represented by the United States.

A key implication is that the globalisation of the Australian economy is an important determinant of Australian productivity growth. The slower pace of globalisation since the mid-2000s explains the slowdown in productivity growth in ways that competing explanations do not.

The report concludes that re-establishing and improving Australia’s international connectedness must be a priority for Australian policymakers in the aftermath of the pandemic.
