---
title: "Globalisation and labour productivity in the OECD: What are the implications for post-pandemic recovery and resilience?"
date: "2020-06-04"
categories: ["Economics"]
---

I have a new [report](https://www.ussc.edu.au/analysis/globalisation-and-labour-productivity-in-the-oecd-what-are-the-implications-for-post-pandemic-recovery-and-resilience) out with the United States Studies Centre on ‘Globalisation and labour productivity in the OECD: What are the implications for post-pandemic recovery and resilience?’

Globalisation is measured on the basis of both the depth and breadth of international connections and so is consistent with seeking greater diversification among trading partners to increase resilience to international shocks.

The report finds a positive relationship between globalisation and productivity for the OECD over the period 1970-2017 and provides a basis for measuring the loss of productivity due to the COVID-19 de-globalisation shock.

The report also finds a negative relationship between the government share of consumption spending and labour productivity, pointing to the need to wind back COVID-19 stimulus measures in the long-run, although these should not be withdrawn prematurely.

The report underscores the importance of restoring and improving Australia’s international connectedness as part of the government’s effort to boost post-pandemic productivity and resilience.
