---
title: "A FIRB with Chinese Characteristics"
date: "2010-03-29"
categories: ["Economics", "Foreign Investment"]
---

I often accuse Australia’s regulation of foreign direct investment as having disturbing parallels with China’s regulatory environment.  I was amused therefore to see the following headline:

[China to Set Up Foreign Investment Review Board](http://www.eeo.com.cn/ens/Industry/2010/03/25/166060.shtml "China to Set Up Foreign Investment Review Board"):

> “The new agency will work independently of the current anti-monopoly investigation system,” the above source revealed.
>
> Stating that the Ministry of Commerce’s anti-monopoly review of foreign mergers and acquisitions is only focused on the level of influence that certain mergers and acquisitions may have on competition, not on national nor industrial security.
>
> As for the approval process under any possible future foreign investment review board, “\[The process\] will basically be the same as before, we are merely adding one extra procedure.”
