---
title: "‘A Politician with Rage at His Core’"
date: "2010-06-07"
categories: ["Economics", "Fiscal Policy", "Politics"]
---

Samantha Maiden [reviews](http://www.theaustralian.com.au/news/nation/rage-powering-kevin-rudd-on-his-journey/story-e6frg6nf-1225875696467 "reviews") David Marr’s profile of Kevin Rudd and the barely contained rage that motivates the Prime Minister. At the same time, [Paul Kelly](http://www.theaustralian.com.au/news/opinion/government-that-knows-best/story-e6frg6zo-1225875683928 "Paul Kelly") discusses Kevin Rudd’s Whitlamite experiment in big government:

> Kevin Rudd is taking Australia on to a new policy trajectory of state intervention, control and faith that “government knows best”.
>
> This looms as the decisive judgment on the Rudd era. It constitutes a break from Australia’s post-1983 tradition of pro-market, middle-ground economic reform. It is not necessarily unpopular but raises the alarm that Australia is marching a false policy path…
>
> Yet Labor keeps moving in the direction of Rudd’s maiden speech philosophy. “I believe unapologetically in an active role for government,” he said. He repudiated the view that “markets rather than governments are better determinants of not only efficiency but also equity”. It is a sweeping statement. And it is entirely consistent with his interventionist car industry agenda, plans to build 12 new submarines, compulsion for new spending programs, government-directed nation-building across several fronts and declared timetables to reduce homeless levels and close the gaps for indigenous Australians.
>
> The unifying idea is that government direction or intervention or ownership is the way forward. It fits into a more personal theme: Rudd knows best.

Sadly, Rudd has no shortage of enablers, including the likes of Paul Kelly, who continues to cheer the fiscal stimulus in the linked story. Kelly does not seem to understand that the problems with the stimulus spending are not simply problems of implementation.
