---
title: "A ‘Small Australia’ Will Limit Our Creativity"
date: "2010-09-07"
categories: ["Economics", "Population & Migration"]
---

I have an op-ed in today’s [SMH](http://www.smh.com.au/opinion/society-and-culture/a-small-australia-limits-our-creativity-20100906-14xvj.html "SMH") arguing that a ‘small Australia’ will not only limit economic progress, but also scientific and cultural creativity:

> Like the US, Australia provides an environment in which people and their ideas can flourish. But while the tyranny of distance has receded with advances in communications technology, Australia’s small scale remains an obstacle to economic and other forms of progress. How often do Australian innovators complain about a lack of local commercialisation opportunities and local markets? How often do customers complain of an apparent lack of competition in industries dominated by a small number of companies?
>
> Entrepreneurs, scientists, writers, artists, actors and filmmakers often find Australia too small for their talents. They move to other countries, even if it is with reluctance. While their talents are not lost to the world, Australia is the poorer for them leaving.
>
> Similarly, New Zealanders move to Australia because it provides opportunities that are either non-existent or in insufficient supply in a country with a population no greater than Sydney. Australia’s relatively large and crowded cities are beacons to New Zealanders. While New Zealand enjoys the same institutions and a similar culture to Australia, few Australians would choose to make a new life there. The reluctance is hard to explain with reference to anything other than the limiting effects of scale on life and opportunities in New Zealand.
