---
title: "America’s Third World Politics"
date: "2010-11-13"
categories: ["Politics"]
---

America’s gerrymandered electoral system makes it very difficult to unseat incumbents. As [John Sides](http://www.themonkeycage.org/2010/11/2010_was_a_pretty_good_year_fo.html "John Sides") notes, the November mid-term elections barely put a dent in incumbents, who enjoyed an 86% re-election rate. The number of contests with no incumbent running also remained little changed. This basic lack of contestability in the US political system explains a lot about the US.

In Australia, we can be thankful for the independence of the Australian Electoral Commission, which routinely unseats incumbents through electoral redistributions and ensures that the political system as a whole remains contestable. Had an Australian political party done to Australia what Congress has done to the US, we can be fairly confident that not only would many of their MPs lose their seats, but the party responsible would probably never govern again.
