---
title: "Andrew Charlton as Political Liability"
date: "2010-06-13"
categories: ["Politics"]
---

[Peter Van Onselen](http://www.theaustralian.com.au/news/nation/why-cabals-calling-the-shots-miss-the-target/story-e6frg6nf-1225878641583 "Peter Van Onselen"), on Andrew Charlton’s role in the wholesale political collapse of Kevin Rudd:

> As the polling tightens and the Prime Minister’s security as leader starts to be questioned, he is recoiling more and more into a closed forum with his personal staff—chief of staff Alister Jordan, press secretary Lachlan Harris and his senior economics adviser, Andrew Charlton. All three are early 30s political apparatchiks who Rudd listens to more than anybody else, with the possible exception of his immediate family.
>
> Some Labor MPs worry that they are too narrow a set of opinions to give Rudd the perspective he needs to regain the trust of ordinary voters. As one senior Labor source noted: “The advisers around him work on the idea that we are smart; the punters are dumb; they won’t recognise that we are running a scam.”

Andrew can’t take credit for Rudd’s political successes and then shirk responsibility for Rudd’s failure.
