---
title: "Atlas Shrugged in Pre-Production from June 11"
date: "2010-06-03"
categories: ["Rand"]
---

According to [Deadline New York](http://www.deadline.com/2010/05/atlas-shrugged-rights-holder-sets-june-production-start-whether-or-not-stars-align/#more-43840 "Deadline New York"):

> *Atlas Shrugged will be directed by Stephen Polk, an actor/producer whose father, Louis Polk, was once MGM chairman. He considers Atlas Shrugged to be his feature directing debut, though Polk acknowledges he stepped in and helmed the 2008 indie Baggage. Aglialoro was unavailable to speak directly, but sent a missive indicating that he’s courting actresses like Theron and Maggie Gyllenhaal to play Taggart. Sources in the camps of both actresses were aware of the project, but neither is planning to go to work on Atlas Shrugged next month.*

[Charles Murrary](http://www.claremont.org/publications/crb/id.1708/article_detail.asp "Charles Murrary") reviews the two recent Rand bios (my review can be found [here](../../files/randreview.pdf "here")). [Brooks](http://www.aei.org/article/102127 "Brooks") and [Barone](http://www.aei.org/article/102129 "Barone") expound on themes that would have been all too familiar to Rand.
