---
title: "Behavioural Economics at the Mont Pelerin Society"
date: "2010-10-08"
categories: ["Classical Liberalism", "Economics"]
---

Blogging will be even lighter than usual next week, as I will be attending the [Mont Pelerin Society General Meeting](http://www.mps2010.org "Mont Pelerin Society General Meeting") in Sydney. I will be the lead discussant for a paper by Doug Ginsburg and Joshua Wright, ‘Behavioural Economics, Law and Liberty’. The paper should be topical, with the Nobel prize for economics announced next week and behaviouralists currently leading the field of potential winners at [iPredict](https://www.ipredict.co.nz/app.php?do=browse&cat=99 "iPredict"). While Richard Thaler would be a deserving recipient, it would be unfortunate if Robert Shiller were a co-recipient (indeed, it would be a tacit admission that Shiller should not win in his own right). Oddly enough, I was on the same Sydney-New York flight as Shiller when I went to the MPS special meeting in February last year, but did not spot him until after we had landed. Shiller can thank Qantas for not putting me next to him for 22 hours (that would have been an interesting conversation).
