---
title: "Bond Market Vigilantes No Check on Fiscal Excess"
date: "2010-04-13"
categories: ["Economics", "Financial Markets"]
---

I have an op-ed in today’s [SMH](http://www.smh.com.au/business/bond-market-vigilantes-should-weigh-risks-of-continued-inactivity-20100412-s43b.html "SMH") questioning whether higher inflation and interest rates are the most likely outcome from the fiscal policy excesses that have followed the global financial crisis.  Classical liberals fret about rising inflation and interest rates, but this is not entirely consistent with their view that the expansion of the state is bad for long-run growth prospects, which could be expected to depress both.  This is not necessarily good news for bonds, as it points to an environment of depressed returns across all asset classes.

The latest unsolicited review copy to cross my desk is *Accelerating out of the Great Recession: How to Win in a Slow-Growth Economy*, by two partners at the Boston Consulting Group.  Like many business books, it is useful mainly for what it tells us about the zeitgeist.  The sub-title says a lot about current expectations for future growth, but I was also struck by this recommendation from the authors:

> *Prepare for government intervention and changes in the external environment, which will likely include a reduction in consumers’ disposable income and restrictions in free trade.*

If this is what sells business books, then we have a problem and it’s not higher interest rates.
