---
title: "Bonfire of Kevin Rudd’s Vanity"
date: "2010-08-22"
categories: ["Politics"]
---

Whoever forms government in the wake of Saturday’s federal election, the result is as comprehensive a repudiation of Kevin Rudd and his legacy as one could reasonably hope for. Any suggestion that Kevin Rudd’s liquidation as Prime Minister in June was a net negative for the ALP withstands little scrutiny. It is ill-advised for members of the conservative side of politics to suggest otherwise or confect sympathy over the manner of Rudd’s demise. We should always be thankful to the ALP caucus for taking the action they did in removing a dysfunctional central planner from office. Perhaps the highlight of last night’s election coverage was the ABC’s decision to cut Kevin Rudd off mid-speech as the producers realised that amid the usual profusion of words coming out of his mouth, he had nothing to say. Rudd suffered a 9% primary swing against him in his own seat.

The election result is one that Malcolm Turnbull said could never happen if the Coalition failed to join a bipartisan policy cartel behind Kevin Rudd’s ETS. Malcolm’s stand undoubtedly helped him in Wentworth, where he now sits on a massive 60% of the primary vote. What Malcolm never understood and what Tony Abbott demonstrated was that public opinion on the ETS was not independent of the opposition’s stand on the issue. Ironically, Rudd dropped the ETS for the same reason Malcolm supported it: neither of them wanted to fight an election on the issue.

Any new government will now be hostage to some combination of Greens and rural protectionists. Unfortunately, both have a common interest in frustrating economic and other reforms. While there is now little prospect of good legislation coming out of any new government, it will also be difficult to push bad legislation through such a finely balanced legislative process. Legislative and policy paralysis are underrated as political outcomes and could even set the stage for new elections in which real policy issues might actually be at stake.
