---
title: "Canadian FDI Protectionism"
date: "2010-09-16"
categories: ["Economics", "Foreign Investment"]
---

An important reason for opposing FDI protectionism at home is that Australia is also a significant exporter of direct investment capital. Australian firms are potentially vulnerable to FDI protectionism abroad. [Terry Corcoran](http://opinion.financialpost.com/2010/09/14/terence-corcoran-let-bhp-buy-potash-corp/ "Terry Corcoran") discusses the protectionist and nationalist backlash in Canada over BHP Billiton’s takeover of Potash Corp. The arguments made against foreign investment in Canada almost perfectly echo those made in Australia, but somehow sound even less convincing when an Australian listed company is on the receiving end:

> *Jeffrey Simpson at the Globe, David Crane at the Toronto Star, Maude Barlow of the Council of Canadians, investment guru Stephen Jarislowsky, and now former Calgary resource executive Dick Haskayne — together they have become the ersatz Paul Reveres of the Canadian economy, riding through the pages of newspapers to alert the population to the looming menace of foreign ownership of our vital natural resources. In this case, the threatened sacred trust is potash. Collectively, our midnight riders of economic nationalism have assembled a wrong-headed and misguided series of arguments against BHP Billiton’s \$40-billion takeover of Potash Corp. of Saskatchewan.  If ever Canada sought to become a backwater in the global mining economy, moving to block the Potash deal would be a good place to begin.*
