---
title: "Central Bankers Behaving Badly and Not So Badly"
date: "2010-11-24"
categories: ["Economics", "Monetary Policy"]
---

[Larry White, George Selgin and William Lastrapes](http://www.cato.org/pub_display.php?pub_id=12550 "Larry White, George Selgin and William Lastrapes") recently argued that the Fed has been a failure by comparing the periods before and after its establishment in 1914. Yet there are enormous differences in the way the Fed has approached monetary and other policies in the period since 1914 that would seem to be more important in explaining these outcomes than the existence of the Fed itself. [Charles Calomiris](http://www.aei.org/docLib/CalomirisMonetaryPolicyNovember2010.pdf "Charles Calomiris") notes that for the period 1914-1951, the Fed was beholden to fallacious economic doctrines, which makes its failures readily explicable. Monetary theory and policy practice have come a long way since then. As [Henderson and Hummel](http://www.cato.org/pub_display.php?pub_id=9756 "Henderson and Hummel") note, Fed policy has been far more benign than the critics would suggest.
