---
title: "China’s Underappreciated Boost to Global Resource Supply"
date: "2010-07-18"
categories: ["Commodity Prices", "Economics", "Foreign Investment"]
---

China’s contribution to global resource demand is well known, but its important contribution to augmenting global resource supply is underappreciated, frequently misunderstood, and often feared. Concerns over Chinese intentions in relation to commodity production and pricing were readily apparent in the Australian debate over Chinalco’s failed bid for Rio Tinto last year, but have also been raised in relation to other acquisitions.

These issues are examined in a new study, [China’s Strategy to Secure Natural Resources: Risks, Dangers, and Opportunities](http://bookstore.piie.com/book-store/5126.html "China's Strategy to Secure Natural Resources: Risks, Dangers, and Opportunities"), published by the Peterson Institute and authored by Theodore Moran, a member of the US Director of National Intelligence Advisory Panel on International Business Practices. Rather than just raising abstract concerns, Moran examined the actual record of China’s 16 largest foreign resource procurement arrangements between 1996 and 2006, including several in Australia.

Moran concludes that ‘looking at the effect of Chinese procurement efforts on the structure of the global supplier base for energy and minerals, the empirical record to date suggests a predominant thrust … toward diversification of output and enhanced competition among producers.’ It is for these reasons that competition regulators in Australia, Germany and the United States did not raise significant objections to Chinalco’s proposed increased stake in Rio.

Moran argues that Chinese involvement in the development of rare earth elements (REEs) ‘may constitute a significant exception’ and warrants greater ‘circumspection.’ But even here, concerns have been exaggerated. Despite the name, these elements are not particularly rare. The least abundant REEs are still 200 times more abundant than gold. The idea that REEs are scarce is belied by the fact that low prices have often been the main obstacle to the development of more diversified sources of supply.

Australians tend to see China through the prism of growing export demand and higher commodity prices, although there are also significant benefits to Australia’s terms of trade through the import side of the trade relationship. China’s real long-term significance to the global resource sector may be as a source of the much-needed investment that will increasingly alleviate global supply constraints, putting downward pressure on global commodity prices by boosting output, employment and exports in countries like Australia.
