---
title: "Constitutional Challenge to the Bailout of Greece"
date: "2010-04-16"
categories: ["Economics", "Financial Markets"]
---

Law professors’ [constitutional challenge](http://www.telegraph.co.uk/finance/financetopics/financialcrisis/7591027/Greek-aid-in-doubt-as-German-professors-prepare-court-challenge.html "constitutional challenge") to EU plunder:

> Dr Karl Albrecht Schachtschneider, law professor at Nuremberg and author of the complaint, told The Daily Telegraph that he will be ready to file within days and will ask the court for an expedited procedure. A ruling could occur within a week, but may take as long as six months.
>
> The complaint will argue that the rescue contains an illegal rate subsidy, threatens monetary stability as encoded in the Maastricht Treaty, and breaches the ‘no bail-out’ clause. Greece is clearly responsible for its own mess.
>
> “It is a question of law. The duty of the court to defend the German constitution. They have no choice other than reaching a lawful decision. This may cause a great crisis in Europe but we already have a crisis,” he said.
>
> He will ask the court to freeze rescue aid while the case is pending. There is a precedent for this. It ordered Berlin to halt implementation of the Lisbon Treaty while it reviewed the treaty last year. Such a move would cause havoc on Europe’s bond markets.
>
> “This court hearing is going to be very dangerous,” said Hans Redeker, currency chief at BNP Paribas. “It could lead to Germany itself being catapulted out of the currency union. Once investors begin to fear this, there will not be single euro in further financing for the EMU periphery.”

Sounds like a plan!
