---
title: "Crowding Out and the BER"
date: "2010-07-29"
categories: ["Economics", "Fiscal Policy"]
---

Crowding out effects were [built-in to the BER](http://www.theaustralian.com.au/national-affairs/builders-told-to-add-10pc-for-ber-cost-escalation/story-fn59nlz9-1225898202297 "built-in to the BER"):

> BUILDERS and architects tendering for work under Julia Gillard’s school stimulus program were told to include a “cost escalation” of up to 10 per cent to cover the expected inflationary impact of the scheme.
>
> The hidden cost of the Building the Education Revolution, revealed in documents submitted to a Victorian parliamentary inquiry, suggests that as much as \$250 million of taxpayers’ money could have been spent to cover a surge in building material and labour costs created by the state’s \$2.5 billion share of the stimulus program.
>
> Contract details provided by an architecture firm reveal it was required by the Victorian Education Department to provide a 7 per cent “contingency fee” and a 10 per cent “cost escalation” in the tenders it submitted for work on four primary schools in Melbourne’s east.
>
> Government sources confirmed last night the department specifically included escalation costs in BER projects “because the stimulus was going to be a significant injection into the market/economy and prices could be expected to increase with greater levels of work being undertaken”.
