---
title: "Did the US Treasury See the Inflation Nutters Coming?"
date: "2010-01-20"
categories: ["Economics", "Financial Markets", "Fiscal Policy", "Monetary Policy"]
---

I have a column in today’s [Business Spectator](http://www.businessspectator.com.au/bs.nsf/Article/Whats-stopping-the-recovery-pd20100119-ZU2SJ?OpenDocument&src=sph "Business Spectator") arguing that the global debate about whether monetary and fiscal stimulus will prove inflationary reflects poorly on the credibility of policymakers.  One of the lasting effects of the discretionary policy responses to the global financial crisis may be the damage it will do to the credibility of monetary and fiscal policy frameworks.

[David Merkel](http://alephblog.com/2010/01/19/my-tips-treasuries-and-inflation-model-ii/ "David Merkel") has updated the inflation expectations implied by US Treasuries, noting that ‘rapidly rising long-term inflation expectations indicate that the average investor does not trust monetary policy to succeed over the next 20+ years’.  At the same time, Merkel argues that since this outcome is already priced, it may be time to short US Treasury Inflation Protected Securities (TIPS).  The US Treasury may well be taking the inflation nutters for a ride:

> *there is a lot of demand for long TIPS.  If the US Treasury thinks it can get things under control, the rational thing to do is to stuff the long TIPS buyers with as much product as they can gulp before it becomes obvious that low inflation will continue because the government will soon balance the budget and pay down debt, as they did after WWII.*

But Merkel also concedes that:

> *I don’t know which direction the US Government and Fed intend to go with policy.  They likely have no idea as well…if the US Treasury can’t get things under control, the long TIPS buyers will do well, as they have the most sensitivity to rising forward inflation expectations*.

The enormous uncertainty created by the discretionary policy responses of governments to the crisis will weigh on economic activity, regardless of how these issues are ultimately resolved.
