---
title: "Don’t Blame Migrants for Home Grown Problems"
date: "2010-04-27"
categories: ["Economics", "Population & Migration"]
---

I had an op-ed in yesterday’s *Canberra Times* (‘Migrants add to growth hopes’) arguing that politicians are using migrants as scapegoats for the many public policy problems they have been unwilling or unable to tackle themselves. No link, but full text below the fold (text may differ slightly from published version).

The highly readable Chris Berg made similar arguments in a piece for [ABC The Drum Unleashed](http://www.abc.net.au/unleashed/stories/s2877576.htm "ABC The Drum Unleashed").

‘Migrants add to growth hopes’, *Canberra Times*, 26 April 2010.

Population growth has become a political issue, with the federal government establishing a population portfolio tasked with developing a ‘population strategy,’ while the opposition has threatened to reduce net migration. 

However, it would be a mistake to tailor population policy and the size of the migration intake to domestic policy failures in areas such as housing, infrastructure and the labour market.  The pressures of a growing population should instead be seen as adding to the case for the much-needed structural reforms that have been neglected by successive governments at both the state and federal level.

Although the government has disavowed the notion of a population target, there is still a persistent view that the task for government is to find the correct level or growth rate for the Australian population. 

Official projections for population growth have often been mistaken for ‘targets’ in the current debate.  Yet these projections are very sensitive to underlying assumptions.  The dramatic revisions to the official population projections resulting from changes in these assumptions frequently capture the headlines and the attention of commentators. 

However, these revisions only serve as a reminder that the government’s ability to plan for an inherently unknowable future is very limited.  Why would we expect the same governments that have done such a poor job of planning for the present to do any better at planning for Australia’s future in the year 2050?

It was not so long ago that the treasurer in the former Howard government was enjoining Australians to have one child for mum, one for dad and one for the country.  Natural population increase was seen as a good thing and politically-motivated handouts such as the baby bonus were given a pro-natalist veneer of respectability.

Few politicians or commentators point the finger at natural population increase as a source of current or future problems.  By contrast, migrants are easy scapegoats for those who are unwilling or uninterested in facing-up to the need for structural reforms that would, for example, make housing more affordable and provide the right incentives for investment in productivity-enhancing infrastructure.

Opposition to immigration has a long and disreputable history in Australia.  Traditionally, this opposition was motivated not so much by racism as by trade and labour market protectionism.  More recently, it has become closely associated with misanthropic environmentalism.  There is little daylight between Pauline Hanson and Bob Brown on the question of immigration. 

Much of the debate has been predicated on the mistaken view that population growth and immigration policy should be conditioned on existing capacity constraints, whether it be in the areas of housing, infrastructure, water or the environment.  Taken to their logical extreme, many of these concerns would have ruled out the founding of the colony of New South Wales in 1788, when the infrastructure to support the first European settlers was non-existent.

A growing population adds to demand for existing resources, but also supplies the incentives and additional human capital that are essential to overcoming temporary resource constraints.  Dick Smith has absurdly suggested that Australia might run out of food if population growth is not contained.  Yet it is from the ranks of new born Australians and migrants that we will find the future Dick Smiths, the successful entrepreneurs who will rise to the challenge of these and other problems. 

Cross-country differences in livings standards have less to do with population size, growth or density than with the freedoms, incentives and opportunities enjoyed by the resident population.  Human ingenuity in solving resource constraints is limitless and population growth only adds to the supply of that ingenuity.

To condition population policy on existing capacity constraints is to deny Australia’s enormous future potential.  It would mark a return to the parochialism and insularity of Australia’s protectionist past.

While the Prime Minister has declared himself in favour of a ‘big’ Australia, he seems incapable of articulating or defending what this might mean in policy terms, creating a political opportunity for the opposition. 

If population growth, including migration, forces politicians to confront the need for structural reform and greater flexibility in areas such housing, infrastructure and the labour market, that is all for the good.  The danger is that we allow them to scapegoat immigration for all the home-grown problems they had neither the imagination nor the guts to address themselves.
