---
title: "Ferraris for All"
date: "2010-06-30"
categories: ["Economics"]
---

[Sean Collins](http://www.spiked-online.com/index.php/site/reviewofbooks_article/9082/ "Sean Collins") reviews Daniel Ben-Ami’s *Ferraris for All*:

> Ben-Ami maintains that, rather than challenging growth scepticism, the 2008 recession gave it greater impetus. The growth-sceptic outlook that prevailed prior to the downturn encouraged us to explain it by reference to unbridled greed, instead of structural economic factors. And this greed and excess were said to characterise all of us, not just a few bankers. Ben-Ami cites Neal Lawson of the UK Labour Party-linked think-tank Compass, whose book All Consuming criticises mass consumption. The subtitle of Lawson’s book – ‘How shopping got us into this mess and how we can find our way out’ – makes it clear we are all to blame…
>
> The limits to growth that critics cite are not insurmountable, says Ben-Ami. For example, he argues that the answer to climate change is more and better technology, rather than reduced energy use and cutting back on economic growth. But technology is expensive, which is why growth is so important. Cynicism about growth is negative because it denies us the resources to deal with problems.

Ben-Ami’s blog can be found [here](http://danielbenami.com/ "here").
