---
title: "First They Came for the Light Bulbs…"
date: "2010-07-10"
categories: ["Economics"]
---

…and then the [appliances](http://www.theaustralian.com.au/news/nation/pm-julia-gillard-told-to-slow-down-on-climate/story-e6frg6nf-1225890026331 "appliances"):

> *The Prime Minister’s special taskforce on energy efficiency has concluded its report to hand to Ms Gillard, calling on her to adopt a national energy efficiency target. The target will lead to bans on many energy-sapping appliances being sold in Australia.*

Meanwhile, sales of the centrally-planned [Rudd Car](http://www.theaustralian.com.au/news/nation/buyers-browned-off-with-hybrid-green-cars/story-e6frg6nf-1225890001019 "Rudd Car") languish:

> The Hybrid Camry, which began rolling off its Melbourne assembly lines six months ago, was expected to attract 10,000 buyers this year, but fewer than 3000 had been registered at the halfway mark, this week’s figures reveal.
>
> A string of record months for vehicle sales and an aggressive marketing campaign by Toyota failed to stimulate demand for the Hybrid Camry, hailed as a new era in Australian manufacturing by Kevin Rudd when he launched it in December, just before he flew to Copenhagen for the ill-fated climate change summit, and the project was granted \$35 million from the green car scheme.
