---
title: "Fiscal Policy After the Election"
date: "2010-08-30"
categories: ["Economics", "Financial Markets", "Fiscal Policy"]
---

[Tony Makin](http://www.theaustralian.com.au/national-affairs/saddled-with-legacy-of-fiscal-extravagance/story-fn59niix-1225911594527 "Tony Makin") argues in The Australian that:

> Whichever side forms government, it will have to live with the legacy of the fiscal extravagance since October 2008. Just as present budgetary actions have implications for future economic activity, past actions have economic implications for the present and the near future.
>
> Questions that will most likely arise during the term of the next government include the following: Why are long-term interest rates and the cost of obtaining funds from abroad continuing to rise? Why is private investment not improving as expected? Why is future economic growth now likely to be lower than otherwise? Why are inflationary pressures continuing to build?
>
> The answer to each of these questions is the same. It’s either mostly, or partly, due to the excessive fiscal stimulus of the past two years.

My view is that activist fiscal policy in Australia and abroad will have negative consequences through a rather different channel: a negative wealth effect from increased government debt that will weigh on economic growth and consequently lower rather than raise long-term interest rates globally. I made this argument in a recent [op-ed](http://www.smh.com.au/business/bond-market-vigilantes-should-weigh-risks-of-continued-inactivity-20100412-s43b.html "op-ed"). Recent developments in global long-term interest rates have been consistent with this view.

For those interested, I will be discussing these issues as part of a panel at this year’s [Australian Conference of Economists](http://www.ace10.org.au/ "Australian Conference of Economists") on the topic of ‘Monetary-Fiscal Interactions: How to Improve Policy Outcomes.’ Other panellists include Don Brash (ex-RBNZ), Jacopo Cimadomo (ECB), Carl Wash (UCSC) and Jan Libich (La Trobe).
