---
title: "Gangster Government"
date: "2010-06-18"
categories: ["Economics", "Politics", "Rule of Law"]
---

[Matthew Stevens](http://www.theaustralian.com.au/business/tax-theory-all-at-sea-in-pms-push-for-a-fair-share/story-e6frg8zx-1225881089017 "Matthew Stevens") on government by intimidation:

> YESTERDAY we observed, like many others, that the PM has a jaw of crystal when it comes to criticism, after he dubbed unspecified Australian miners as “ugly”. Our words were prescient, because in the wee hours before The Australian hit the streets the PM had again stunned his fellow Australians gathered at the Canberra Press Gallery’s Midwinter Ball with an acerbic aside that carried with it a bleak threat to the mining industry.
>
> “The mining industry are here tonight,” Rudd said in a prime ministerial speech that, in more normal times, would have been protected by Chatham House rules but was circulating widely yesterday.
>
> “I extend my greeting to each and every one of them. I notice there’s a small fire which has been erected down the back. I understand that myself and Wayne Swan and Martin Ferguson will soon be erected above that fire. Can I say, guys, we’ve got a very long memory.”
>
> This is not the first time representatives of the mining industry have been warned of retribution by this government.
>
> I’ve been told, for example, that one very senior member of Rudd’s team made even more pointed threats to a table of mining industry folk dining in the hours after the recent federal budget. They were warned that the government intended to secure a mandate for the super-profits tax at the election and then, with victory in hand and tax in place, it would come after all those who had been dense enough to challenge Rudd’s reform.

UPDATE. [Alexander Downer](http://newstaging.spectator.widearea.co.uk/print/australia/6086928/meet-the-real-kevin-rudd.thtml "Alexander Downer") on the bursting of the Rudd bubble:

> *It has taken an incredible three years for the Australian public to realise who their national leader really is. I sat with a Labor luminary having a late-night drink in June 2008. He turned to me and said: ‘Mate, one day the Australian public will grow to hate Kevin Rudd as much as I do.’ That day has arrived.*
