---
title: "Glenn Stevens Goes Where Ian Macfarlane Feared to Tread"
date: "2010-03-29"
categories: ["Economics", "Financial Markets", "Monetary Policy"]
---

Former RBA Governor Ian Macfarlane took pride in never having given an on-the-record media interview in his 10 years in office.  Macfarlane’s public appearances were about as common as those for your average [thylacine](http://en.wikipedia.org/wiki/Thylacine#Unconfirmed_sightings "thylacine").  Macfarlane only drew attention to the problem by engaging in a post-retirement media blitz that sought to set the record straight on all the issues where he claimed to have been misquoted or misrepresented while Governor. 

Stevens has more than doubled the annual number of public speeches that Macfarlane gave in his last full year as Governor.  If the last two months are anything to go by, Stevens will double his own record this year.  His senior officers have also been considerably more active in terms of public appearances.

In a further break with the RBA’s secretive past, Governor Stevens has even put in an [appearance on the Sunrise program](http://petermartin.blogspot.com/2010/03/this-is-where-it-all-happens-now-where.html "appearance on the Sunrise program").  David Koch is not exactly Kerry O’Brien or Tony Jones, but the program’s reach is much greater.  It sets an important precedent, but could be taken further.  As I have [argued previously](../2009/no_time_for_a_media-shy_central_banker.qmd "argued previously"), the RBA Governor should be made to front a media conference after every Board meeting and CPI release.  A Treasurer with half a brain would insist on it.

The Governor’s comments on house prices during the program were somewhat risky, in that they could easily give the impression that house prices are a target rather than merely one of many indicators for monetary policy.  If the public think Stevens is targeting house prices, then the Bank will end up owning them (figuratively, not literally, as with the US Fed).  A better strategy would be to go on highlighting the supply-side constraints on the housing market.  The public is smart enough to figure out who is to blame for those.
