---
title: "Goldman Sachs and Gangster Government"
date: "2010-04-22"
categories: ["Economics", "Financial Markets", "Rule of Law"]
---

[Michael Barone](http://www.aei.org/article/101947 "Michael Barone") highlights the real lesson from the fraud case brought against Goldman Sachs:

> Republicans have been accurately attacking the Dodd bill for authorizing bailouts of big Wall Street firms and giving them unfair advantages over small competitors. They might want to add that it authorizes Gangster Government—the channeling of vast sums from the politically unprotected to the politically connected.
>
> That can boomerang even against the latter. Goldman Sachs employees gave nearly \$1 million to the Obama campaign and \$4.5 million to Democrats in 2008. That didn’t prevent the Goldman from being shoved under the SEC bus. Gangster Government may look good to those currently in favor, but, as some of Al Capone’s confederates found out, that status is not permanent, and there is always more room under the bus.

[Eric Falkenstein](http://falkenblog.blogspot.com/2010/04/will-california-default-bring-goldman.html "Eric Falkenstein") asks whether investments banks are committing fraud by selling State of California debt:

> I bet all of the major investment banks are facilitating debt issuance by the State of California and its various agencies, counties, and municipalities. I bet also there is a small but spirited set of shorts, trying to make money off of the inevitable bankruptcy. With hindsight it will be obvious, and everyone currently buying California-related debt will develop amnesia and claim they never liked California debt, and were hoodwinked by greedy bankers.
>
> At that point, should all the investment banks be liable? If so, is every bank facilitating California debt issuance committing fraud right now?
