---
title: "How Republican Populism Gave Us the Dodd Bill"
date: "2010-05-21"
categories: ["Economics", "Financial Markets", "Rule of Law"]
---

The US Senate [passes](http://online.wsj.com/article/SB10001424052748703559004575256352143175906.html?mod=WSJ_hps_LEADNewsCollection "passes") what is potentially the most devastating regulatory attack on the foundations of US prosperity since the New Deal.  [Pete Wallison](http://online.wsj.com/article/SB10001424052748703691804575254401645329716.html?mod=WSJ_Opinion_LEFTTopOpinion "Pete Wallison") blames Republican populism:

> How did this happen? After Scott Brown’s election to Ted Kennedy’s Senate seat, Republicans had the votes to prevent the closing of debate and keep the Dodd bill off the Senate floor. They could have argued that legislation this important should not be rushed through Congress. They could have pointed out that there were no hearings on most of the major elements of the bill. And they could have reminded the Democrats that the commission Congress appointed to advise them on the causes of the financial crisis would not be reporting until mid-December.
>
> They did none of these things. Instead they backed away from cloture, allowing the legislation to go to the Senate floor where the bill, bad enough to begin with, became steadily worse. Amendments to allow the Fed to regulate interchange fees on debit cards, and to force banks out of the derivatives business are only two examples. This was fully predictable, since the unpopularity of Wall Street and the banks would encourage amendments hostile to business and finance.
>
> Why was the GOP unable to stand united and filibuster the bill before it reached the Senate floor? For the least meritorious of reasons, it seems: unwillingness to go to the voters this November without having done “something” to punish Wall Street and the banks.
