---
title: "How to Kill Animal Spirits: Banking Banana Skins"
date: "2010-02-03"
categories: ["Economics", "Financial Markets"]
---

The [PWC/CSFI Survey of Bank Risk](http://www.pwc.com/gx/en/banking-capital-markets/banana-skins/assets/banking-banana-skins-2010.pdf "PWC/CSFI Survey of Bank Risk"), aka Banking Banana Skins 2010, finds political interference is the number one risk facing the banking industry:

> *Having bailed the banks out, governments are pushing them to keep lending through the recession, against their better judgment. A director at a large UK bank said that “political meddling in the financial sector is almost universally contradictory and negative. One can’t lend more to support the economy and build up capital bases at the same time”. A credit analyst at a large Japanese bank said that “political interference in both banking and regulation is likely to lead to a mis-allocation of resources, which will probably increase, not decrease, the risk profile of the system”*.

In 2005 and 2006, ‘too much regulation’ topped the list of concerns and is still the main concern in the Asia-Pacific region. 

Here is [another](http://www.theaustralian.com.au/news/broker-caught-assessing-kerrs-assets/story-e6frg6n6-1225826045130 "another") banking banana skin.
