---
title: "How to Shut Down Freddie and Fannie"
date: "2010-11-11"
categories: ["Economics", "Financial Markets"]
---

[Withhold approval for new debt issuance](http://online.wsj.com/article/SB10001424052748704635704575604570042260954.html?mod=rss_opinion_main "Withhold approval for new debt issuance"):

> the Treasury doesn’t need Congress or an academic assessment in order to tackle the most important reform goal: eliminating the GSEs and moving their activities to the private sector. Mr. Geithner himself can immediately reshape the mortgage markets—by withholding his approval of new debt issuances by the GSEs. That’s the best way to begin curtailing the GSEs, and it can be done unilaterally.
>
> Congress chartered the GSEs and in their charters required that the Treasury secretary approve all of their new debt. For decades, the Treasury exercised this duty, and the GSEs submitted each new debt issuance to the department for prior approval.
>
> But the Clinton administration found this process cumbersome and a strain on Treasury staff. It established a new process that weakened the administrative approval process for GSE securities offerings. This hands-off approach represented an abdication of Treasury’s essential oversight powers.
>
> The bloating and strategic drift of the GSEs began soon thereafter.
