---
title: "Inflation for the Long-Run"
date: "2010-01-21"
categories: ["Economics", "Financial Markets", "Fiscal Policy", "Gold", "Monetary Policy"]
---

[Jim Hamilton](http://www.econbrowser.com/archives/2010/01/inflation_fears.html "Jim Hamilton") points to his Phillips curve relation, which is forecasting deflation over the near-term.  For the long-run, he suggests we should look to the fiscal theory of the price level:

> The value of the new Federal Reserve liabilities ultimately will be determined by the long-term fiscal soundness of the U.S. government….Inflation is not something you should be afraid of for 2010. But what we need is a convincing commitment from the government to both near-term stimulus and longer-term fiscal responsibility in order to be assured that it’s not a concern over the next decade.
>
> And that’s not what I’m seeing from the U.S. Congress.

Meanwhile, [Thomas Frank](http://online.wsj.com/article/SB20001424052748703837004575013373812096744.html "Thomas Frank") contemplates an evil plot to stick it to the gold bugs: putting Fort Knox on eBay.  Not that it would work, but there is a certain irony in those who fear inflation taking refuge in the one real asset that is potentially the most vulnerable to a surge in supply from central banks and governments.
