---
title: "iPredict Australian Federal Election Market and Election Timing"
date: "2010-06-11"
categories: ["Economics", "Financial Markets", "Politics"]
---

[iPredict](https://www.ipredict.co.nz/app.php?do=browse&cat=11 "iPredict") has launched a market on the outcome of this year’s Australian federal election, with a Labor Prime Minister (not necessarily Kevin) priced at 51% and a Liberal Prime Minister (again, doesn’t have to be Tony) priced at 45%.

[Anthony Green](http://blogs.abc.net.au/antonygreen/2010/06/a-federal-election-in-august.html "Anthony Green") provides a handy primer on likely federal election timing:

> As the Constitution prevents writs for a half-Senate election being issued before 1 July this year, the first possible date on which a House and half-Senate election can be held is 7 August.
>
> Constitutionally the last possible date for the election is 16 April 2011.
>
> However, the fixed term election dates for Victoria on 27 November 2010 and NSW on 26 March 2011 mean that the Federal election will have to be over by the end of October to avoid overlap with state polls.
>
> With football finals in September, and Commonwealth Games in October, that means the date for the Federal election date is likely to be either in August, early September, or between the 16th and 30th of October.
