---
title: "It’s Not the Imbalances, It’s What You Do With Them"
date: "2010-01-22"
categories: ["Economics", "Financial Markets"]
---

I have an op-ed in today’s [Australian](http://www.theaustralian.com.au/business/opinion/imbalances-essential-to-global-economic-system/story-e6frg9if-1225822308564 "Australian") on the subject of global imbalances, arguing that it is distortions to capital allocation that make current account ‘imbalances’ problematic:

> China will need to liberalise its capital account and domestic financial markets, moving its economy away from forced saving and unproductive, state-driven investment to a more market-driven system of capital allocation.
>
> In this respect, China and the US have more in common than many Americans would like to think.
>
> The US government will also need to extricate itself from its disastrous politicisation of housing finance and its post-crisis role in the US financial system.
>
> In this regard, the US congress is likely to prove just as resistant to change as the Chinese Communist Party.
>
> A less distorted system of capital allocation in both China and the US would have resulted in the more efficient use of global saving than was evident in the run-up to the global financial crisis. But it is unlikely to make much difference to the forces of globalisation driving persistent global imbalances.
