---
title: "John Birmingham’s After America"
date: "2010-07-08"
categories: ["Misc"]
---

I attended the Sydney launch for John Birmingham’s new novel, *After America*, part of a planned trilogy that follows from *Without Warning*. In the first instalment, the bulk of the continental US is destroyed on the eve of the Iraq war and the novel speculates about the likely implications for the rest world. Birmingham said that the idea for the first book came from an anti-American rant by a fellow student radical when he was at university. The book is a cautionary tale about what happens when the rest of the world finally gets what it wished for.

Birmingham’s talk did clear up one mystery for me: why he kills off some of his more likeable characters. He randomly pulls names out of a hat to determine who will die. As Birmingham notes, it adds an extra element of unpredictability to the action.

I’m a fan of the speculative fiction genre. As the economist Simon Kuznets once observed,  science fiction is a much better guide to the future than the writing of most economists, who consistently sell the future short. Birmingham’s ‘axis of time’ trilogy, first published in 2004, features the ‘flexipad’, effectively anticipating the iPad of 2010. We didn’t need to wait until 2021 for that one.

Birmingham blogs [here](http://www.cheeseburgergothic.com/ "here").
