---
title: "Journalistic Cheek on Housing and Tax"
date: "2010-06-18"
categories: ["Economics"]
---

[George Megalogenis](http://www.theaustralian.com.au/news/opinion/property-boom-to-end/story-e6frg6zo-1225878639921 "George Megalogenis") wrote in the Weekend Australian (12-13 June 2010) that ‘the Henry review was being cheeky in playing down what previous decisions did to housing affordability.’ He goes on to describe the 1999 Ralph reforms to capital gains tax ‘as the worst revenue decision of the Howard government.’ Megalogenis and many other media commentators may well find the Henry review cheeky, because it effectively repudiates much of their commentary on the subject of capital gains tax, negative gearing, and housing affordability over the last decade. The real cheek is that these commentators have not changed their tired old tune in light of the review.

The Henry review was commendable for rejecting from the outset the comprehensive income view of taxation that has informed most media commentary on these issues. Henry noted that there was no reason why labour and capital income should be taxed at the same rate, favouring an expenditure tax benchmark that seeks to exempt the returns to saving from tax. The final report’s recommendation that saving via owner-occupied housing remain tax-exempt was explicitly based on this benchmark and not, as some have suggested, resignation to political reality. The final report also recommends that the returns to other forms of saving, including capital gains and net residential income and losses, should enjoy a 40% tax discount. Like the Ralph review, the Henry review embraced the principle that capital gains should be concessionally-taxed, along with the returns to other forms of saving such as bank interest.

Contrary to media myth, the Ralph capital gains tax concessions have resulted in more revenue being collected, not less. The capital gains tax share of federal tax revenue has increased since 1998-99, from 3.3% to 4.1%.  Growth in capital gains tax realisations and revenue has been strongest on the part of individual taxpayers who received the largest concessions, a classic supply-side response. The Treasury’s Tax Expenditures Statements are often misinterpreted by journalists as evidence that the Ralph concessions have come at a cost to the revenue. As the Treasury makes clear, its approach measures the benefit to taxpayers, not the cost to the budget, based on the assumption of no behavioural change. It makes no allowance for the positive supply-side response to the Ralph CGT or other concessions.

Henry’s suggested move to a 40% savings income discount is designed, among other things, to remove ‘the current bias towards negatively geared investment in rental property and shares.’ However, this recommendation was made subject to the major proviso that supply-side constraints in the housing market need to be tackled first and that phase-in arrangements should apply to minimise disruption to the housing market. The final report notes that ‘changing the taxation of investment properties could have an adverse impact in the short to medium term on the housing market…reducing net rental losses and capital gains tax concessions may in the short-term reduce residential property investment. In a market facing supply constraints, these reforms could place further pressure on the availability of affordable rental accommodation.’ Many media commentators have argued that the current concessional tax treatment of housing adds to demand, but Henry makes clear that it is also a positive for supply (which is not to say that Henry’s suggested approach to taxing saving is flawed). The demand-supply imbalance in Australian housing that might have occurred in the absence of the current concessional tax treatment makes for a terrifying counter-factual that most journalists and commentators have completely ignored.

Henry correctly concludes that ‘the tax system is not the appropriate tool for addressing the impact of other policies on housing affordability.’  Australia’s housing affordability problem is not due to the principal residence exemption, negative gearing and capital gains tax concessions. The Henry review’s recommendations should be embarrassing to those journalists who have suggested that it is. The failure of many journalists to re-evaluate their previous views on the subject in light of the review is more than just a little cheeky.
