---
title: "Julian Simon Still Winning Against Peak Oil"
date: "2010-07-08"
categories: ["Economics", "Oil"]
---

We reported on the five-year Tierney-Simmons oil price wager [back in 2005](../2005/pundits_putting_their_money_where_their_mouth_is.qmd "back in 2005").  [Mark Perry](http://mjperry.blogspot.com/2010/07/tierney-wins-peak-oil-bet.html "Mark Perry") notes that Tierney has all but won his bet against peak oil crankery:

> In August of 2005, Houston banking executive Matthew Simmons and New York Times columnist John Tierney each put up \$5,000 and made a bet about the price of oil in 2010. 
>
> The wager was based on the price of oil in 2010, specifically on the average daily price for the entire year, adjusted for inflation into 2005 dollars. If the inflation-adjusted oil price this year is \$200 or more per barrel, Mr. Simmons wins \$10,000 plus interest, and if the average price this year is less than \$200, Tierney wins the bet. 
>
> The bet was made public in Tierney’s New York Times column on August 23, 2005 called “The \$10,000.00 Question.”

Julian Simon is still winning from beyond the grave:

> *Julian Simon’s widow put up \$2,500 towards Tierney’s \$5,000 obligation, to honor the tradition of her husband’s famous wager with Paul Ehrlich.*
