---
title: "Just Enough of Me, Way too Much of You"
date: "2010-07-28"
categories: ["Economics", "Population & Migration"]
---

With both major parties offering to retard economic growth by conditioning immigration on existing policy failures in housing, transport and infrastructure, [Imre Salusinszky](http://www.theaustralian.com.au/news/opinion/overpopulation-has-blocked-my-bathroom/story-e6frg71o-1225897740426 "Imre Salusinszky") offers politicians some handy talking points:

> From one perspective, it’s a neat trick: you pander to inner-city prejudice by abandoning road construction, then use what you perceive to be outer-suburban bigotry to paper it over.
>
> But in order to prevent further embarrassment, as politicians attempt to source our problems to the fact there are almost three citizens shoehorned into every square kilometre of Australia, here are some talking-points:
>
> \* Frustrated you can’t get tickets to the big game? Once we block the reffos, convince people to stop having sex, and move across to a sustainable Australia, everybody will be able to attend the AFL or NRL grand final.
>
> \* Sick of waiting around in the morning while other family members use the bathroom? Me too, and I blame the fact there are too many people in Australia.
>
> \* Can’t get the job you want? Can’t win the girl you desire? Can’t own the car of your dreams? Have you noticed the common link? That’s right: there’s always some other bastard who already has these things. Too many Australians!

As best as I can tell, the only political party with a pro-immigration policy platform is the libertarian Liberal Democratic Party (you can read their policy [here](http://ldp.org.au/index.php?option=com_content&view=article&id=1156:immigration&catid=101:policies&Itemid=290 "here")).
