---
title: "Ken Henry, Then and Now"
date: "2010-07-06"
categories: ["Economics", "Politics"]
---

[Niki Sava](http://www.theaustralian.com.au/news/opinion/will-ken-spit-the-dummy-as-tax-takes-a-hiding/story-e6frg6zo-1225888223486 "Niki Sava") on the Ken Henry speeches of yore:

> KEEP checking the Treasury website. Any day now a speech by Ken Henry, meant to be private, will appear. In it, he will distance himself from the Gillard government, condemn it for its profligacy, for its weakness, for ignoring Treasury advice and for poor policy formulation in the run-up to an election.
>
> It should say something like this: “\[Treasury\] will be under pressure to respond to the growing number of policy proposals leading up to the calling of an election, and once the election is called.
>
> “At this time, there is a greater than usual risk of the development of policy proposals that are, frankly, bad.”
>
> And: “There is a temptation to think that all problems can be solved by government spending.”
>
> If previous practice is observed, that is what would happen, followed swiftly by the appearance of those supposedly private observations to staff, on the front pages of newspapers.
>
> Then again, maybe not.
>
> But that is what happened in 2007. The quotes above are taken from a speech by Henry in March that year, a few weeks after prime minister John Howard released the \$10 billion water security plan to save the Murray Darling Basin.

Here is another [Ken Henry speech that time forgot](../2009/the_ken_henry_speech_that_time_forgot.qmd "Ken Henry speech that time forgot").
