---
title: "Ken Henry and the Club of Rome"
date: "2010-05-22"
categories: ["Commodity Prices", "Economics", "Fiscal Policy"]
---

[Terry McCrann](http://m.theaustralian.com.au/OpinionNews/pg/0/fi195025.htm "Terry McCrann") on the resource scarcity assumptions motivating the RSPT:

> It is also clearly founded on the assumption of a long-term—Club of Rome-flavoured—secular upward trend in commodity prices. Thanks to China and India, demand is ever rising, while supply is limited. There’s only so much copper, etc. We must surely run out.
>
> This is a merging of Henry’s green tendencies with his intellectual faith in the purity and reliability of econometric modelling—a blend most dramatically on view in the ludicrous Treasury modelling of the emissions trading scheme.
>
> Henry implicitly rejects the view that non-fuel commodity prices are necessarily on a long-term secular down-trend—as revealed in graphs of aluminium and copper prices through the 20th century.
>
> “Observed trends are sensitive to the commodity selected and the choice of time period,” he notes. So a chart of the copper price over a shorter period, between 1930 and 1970, showed the price “trended quite sharply upward”.
>
> What he didn’t do was reproduce the shorter time period graph for aluminium. I don’t know why. It would have shown the exact opposite of the copper graph—the aluminium price on a long and short down trend.
>
> There is more to this than selective charting. The anti-Club-of-Rome perspective—reality—of mineral supply and demand is not compatible with the logic of the super-profits tax. There is no alternative to developing our resources, even if the government takes 40 per cent more of the profits.
>
> More exquisite was the graph with which he started his presentation. Taken from the budget, it showed the difference between Treasury’s GDP forecasts and projections in last year’s budget, and the ones in this year’s document.
>
> What a very big difference a year makes. Henry is completely unable to see how Treasury’s failure, and the failure of its models, to get even close to predicting the present.
