---
title: "Kevin Rudd’s Lesson for US Politicians"
date: "2010-06-25"
categories: ["Politics"]
---

A [US perspective](http://blog.american.com/?p=15884 "US perspective") on the repudiation of Kevin Rudd:

> Six months ago, Kevin Rudd was one of Australia’s most popular prime ministers in history. The brainy and intense Labourite had beaten four-time Prime Minister John Howard in a smashing victory and his Australian Labour Party was comfortably ahead in the polls. Today he’s gone, resigning midterm rather than be dumped by his own party. What happened?
>
> Cap-and-trade.
>
> Rudd had made the pursuit of cap-and-trade a hallmark of his tenure, calling it “the greatest moral, economic, and social challenge of our time.” But once the opposition coalition picked a new leader, Tony Abbott, in December, prospects of an agreement that could send cap-and-trade through the Australian Senate faded. Abbott labeled the plan ”a great, new big tax” and the coalition started to climb in the polls. When Rudd announced in late April that he would not push his plan until 2013, well after the next scheduled elections, his support collapsed. Recent polls show the coalition in the lead, a stunning turnaround that if repeated in the elections due within a year would constitute the largest swing between elections in modern Australian history. Meanwhile, support for the Green Party has surged to record heights as disappointed climate activists have abandoned Labour in droves.
>
> There’s a moral here for American politicians. Voters understand that cap-and-trade is not a free lunch; pointing out the real costs will resonate with voters.
