---
title: "Labor Voters More Confident Following the Demise of Kevin Rudd"
date: "2010-07-16"
categories: ["Economics", "Financial Markets", "Opinion Polls", "Politics"]
---

The 11.1% surge in [consumer confidence](http://www.melbourneinstitute.com/subreports/reports/CSI201007.pdf "consumer confidence") between June and July shows a clear partisan divide, with confidence on the part of Coalition voters up 19.8% compared to a more modest 3.9% for ALP voters, but this is still a big surge in confidence among Labor voters for a series that has an historical standard deviation of 5.1%. The \~75-80% probability of a Labor victory being priced in [betting](http://blogs.crikey.com.au/pollytics/2010/07/16/betting-market-friday-16/ "betting") and [prediction](https://www.ipredict.co.nz/app.php?do=contract_detail&contract=AUS.NEXTPM.LABOR "prediction") markets suggests that Rudd’s demise has significantly improved Labor’s election prospects.

Meanwhile, [Frank Brennan](http://www.theaustralian.com.au/news/opinion/rudds-suffered-enough-so-can-we-lay-off/story-e6frg6zo-1225892367838 "Frank Brennan") thinks we should give Rudd credit just for showing up to work:

> *Having resigned as prime minister, Rudd had the good grace to turn up to question time, taking his place on the backbench.*
