---
title: "Libertarian Paternalism without the Libertarianism"
date: "2010-07-19"
categories: ["Economics", "Financial Markets"]
---

Superannuation system review chair Jeremy Cooper, [interviewed](http://www.abc.net.au/insidebusiness/content/2010/s2956936.htm "interviewed") by Alan Kohler:

> ALAN KOHLER: In fact you call it “libertarian paternalism” in your report. And I must say reading your report it seems to leans toward the paternalism rather than the libertarian.
>
> JEREMY COOPER: Possibly but go back to the original idea it’s very paternalistic. Compulsory superannuation, which really only exists in a very few countries, is very paternalistic.
>
> It’s saying, well unless we force the population to put money away for retirement they’re not going to do it, so we’re going to work out what we think what they’re best interest is and we’re going to force them to hold back wages which would otherwise would be spent on school shoes and petrol and all those important things.
>
> That money is held back by the government, that’s very paternalistic. So to criticise these ideas because they’re paternalistic forgets what the system, what super actually is.

Perhaps the most honest assessment of the motivation behind compulsory super I have heard to date.
