---
title: "Matt Ridley’s Rational Optimism"
date: "2010-05-17"
categories: ["Economics"]
---

[Matt Ridley](http://women.timesonline.co.uk/tol/life_and_style/women/the_way_we_live/article7127536.ece "Matt Ridley") discovers Julian Simon:

> Furthermore it is possible, indeed probable, that by 2110 humanity will be much much better off than it is today and so will the ecology of our planet. This view — which I shall call rational optimism — may not be fashionable but it is compelling.
>
> Rational optimism holds that the world will pull out of its economic and ecological crises because of the way that markets in goods, services and ideas allow human beings to exchange and specialise for the betterment of all. But a constant drumbeat of pessimism usually drowns out this sort of talk. Indeed, if you dare to say the world is going to go on getting better, you are considered embarrassingly mad.
>
> If, on the other hand, you say catastrophe is imminent, you can expect a MacArthur Foundation genius award…
>
> The more human beings diversified as consumers and specialised as producers, and the more they exchanged goods and services, the better off they became. And the good news is there is no inevitable end to this process.
>
> As more people are drawn into the global division of labour and more people specialise and exchange, we will all become wealthier. Along the way, moreover, there is no reason why we cannot solve the problems that beset us — economic crashes, population explosions, climate change, terrorism, poverty, Aids, depression, obesity.
