---
title: "Maybe the Banks Just Don’t Want Your Business"
date: "2010-11-12"
categories: ["Economics", "Financial Markets", "Monetary Policy"]
---

The big four banks have now set their post-November RBA tightening [mortgage interest rates](http://www.theaustralian.com.au/business/industry-sectors/nab-rate-hike-just-shy-of-cbas-shock-move/story-e6frg96f-1225952717436 "mortgage interest rates"). Amid the shameful public vilification of the banks by politicians and others who should know better, almost no one has considered the possibility that, at least at the margin, the banks probably don’t want our business. People in the banking industry tell me that Westpac and CBA in particular have full mortgage books and don’t want to take on additional exposure to housing. Not surprisingly, they have the highest mortgage rates on offer. Notice too how ANZ and NAB are much more aggressive in their advertising? In any other business, using price signals to manage excess demand would be viewed as completely unexceptional.

Far from being greedy, the banks are being prudent, while the government tries to induce them into taking on additional risk. Of course, we could always go back to the days of regulated interest rates and non-price credit rationing, when getting money from the bank was a beauty contest that saw housing credit go only to the rich.
