---
title: "Nassim Taleb’s DIY Black Swan Event"
date: "2010-05-14"
categories: ["Economics", "Financial Markets"]
---

From the [WSJ](http://online.wsj.com/article/SB10001424052748704879704575236771699461084.html "WSJ"):

> *The working theory among traders and others involved in the exchange meltdown is that the “Black Swan”-linked fund may have contributed to a “Black Swan” moment, a rare, unforeseen event that can have devastating consequences*.

As [Eric Falkenstein](http://falkenblog.blogspot.com/2010/05/nassim-dream-top-tics-it.html "Eric Falkenstein") notes, this episode may shed light on how Nassim Taleb really makes his money:

> A
>
> ll the while, however, he makes huge fees, because 1% on \$4B is a lot of money, and his wealth will serve as proof that he’s an investing genius. More importantly, he then selectively presents to a credulous press he makes billions off his market savvy.
>
> Gee, someone should write a book about blow-hard traders who misrepresent their track records and take excessive risk with other-people’s money, all due to cognitive biases they are too shallow to notice in themselves. Oh yeah, Taleb has done that! I guess his insider status gives him better insight.
