---
title: "Never Let the Facts Get in the Way of a Dumb Story"
date: "2010-06-20"
categories: ["Economics", "Media"]
---

Chris Joye points to a piece by [Michael Pascoe](http://www.smh.com.au/business/rba-myth-busters-explode-debt-headlines-20100618-yk37.html "Michael Pascoe"), reporting on a speech by [RBA Deputy Governor Ric Battellino](http://www.rba.gov.au/speeches/2010/sp-dg-150610.html "RBA Deputy Governor Ric Battellino"):

> Reserve Bank deputy-governor Ric Battellino quietly destroyed a bunch of major myths this week – turns out we’re actually good savers, our household debt isn’t a problem, the housing affordability crisis has been exaggerated and our foreign debt is sustainable. In short, most of the usual scary headlines about the domestic economy are rubbish.
>
> You’d think that would be worth a few headlines, but the RBA made a couple of mistakes in the timing of what is really a very good news story.

Pascoe thinks the speech got buried by the RBA minutes, released the same day. But Pascoe is mistaken if he thinks Battellino’s comments were newsworthy in the usual sense. Battellino and other RBA officials have been arguing along these lines for years. The comments are only news to those who haven’t been listening. If Battellino’s comments were under-reported, it is perhaps because his remarks are embarrassing to the lazy prejudices peddled by so many media commentators over the years.

As noted in the previous post in relation to the Henry review, the media are more than capable of ignoring arguments that are inconvenient to established narratives. Commentators like George Megalogenis and Mike Steketee could hardly ignore the most comprehensive review of the Australian tax system ever undertaken, but they still managed to write it up in way that pretended it was something other than a wholesale repudiation of most of what they have previously written on the subject.
