---
title: "No Benefit for Borrowers in RMBS Support"
date: "2010-12-14"
categories: ["Economics", "Financial Markets"]
---

I have an op-ed in today’s [Age](http://cis.org.au/media-information/opinion-pieces/article/2292-borrowers-lose-as-mortgage-industry-takes-its-4bn-win "Age") arguing that the government’s expanded support for the mortgage securitisation industry is of no benefit to retail borrowers. [Henry Ergas](http://www.theaustralian.com.au/news/opinion/four-pillars-will-become-shaky-house-of-cards/story-e6frg6zo-1225970529319 "Henry Ergas") makes related points in The Australian:

> where is the evidence that the benefits from the subsidy outweigh its costs? Indeed, where are the estimates of just how large that subsidy is likely to be, and to whom it will accrue? And where is the analysis showing that what Australia needs is yet more lending on houses, this time funded by taxpayers?
>
> Don’t waste your time looking, for the answers are nowhere to be found.

As [Michael Stutchbury](http://www.theaustralian.com.au/business/opinion/package-gives-policy-a-bad-name/story-e6frg9p6-1225969800721 "Michael Stutchbury") notes, the whole banking package was premised on Joe Hockey’s lies about the big banks. But what does it say about the government that it allows public policy to be driven by the cynicism and opportunism of a populist federal opposition?
