---
title: "No Disgrace in Pointing Out the Obvious"
date: "2010-11-27"
categories: ["Economics", "Politics"]
---

In a previous post, I speculated about the likely media reaction to any comment by RBA Governor Stevens that might be seen to be critical of the NBN. Unsurprisingly, the need for a cost-benefit analysis of the NBN came up during the Governor’s appearance before the House Economics Committee. [Michael Stutchbury](http://www.theaustralian.com.au/news/opinion/governor-casts-aside-reserve/story-e6frg6zo-1225961746930 "Michael Stutchbury") says:

> *It’s a disgrace that the Reserve Bank governor has had to be dragged into political hot water to point this out*.

As I argued in a previous [op-ed](../2009/no_time_for_a_media-shy_central_banker.qmd "op-ed"), this is a misreading of the role of an independent central bank governor in public debate. The ability to speak out on important public policy issues is a mark of the Reserve Bank’s independence, not a threat to it. While the government may be in hot water as a result of the Governor’s comments, that is hardly a problem for Glenn Stevens.
