---
title: "No Future in Future Funds"
date: "2010-07-15"
categories: ["Economics", "Financial Markets", "Fiscal Policy"]
---

I have an op-ed in today’s [Australian](http://www.theaustralian.com.au/business/opinion/the-mining-tax-debate-highlights-the-terms-of-trade-boom/story-e6frg9if-1225891819484 "Australian") arguing that improved fiscal responsibility legislation is a better approach to managing the fiscal consequences of terms of trade cycles than sovereign wealth funds such as the existing Future Fund:

> a sovereign wealth fund provides no guarantee current revenue will be spent more wisely in the future than it is today.
>
> If governments are unwilling to commit to binding fiscal responsibility legislation that improves on the existing Charter of Budget Honesty, there is no reason to believe greater use of a sovereign wealth fund will lead to better long-term fiscal management.

Part of the op-ed that hit the cutting room floor noted that Australia is not like Norway, Timor Leste or Nauru, dependent on a single export commodity. Australia’s resource endowment and overall economy is much more diversified, making Australia less vulnerable to some of the macroeconomic and other problems associated with dependence on a single commodity export.
