---
title: "Nouriel Roubini’s Secret IMF Speech"
date: "2010-05-18"
categories: ["Economics", "Financial Markets"]
---

[Eric Falkenstein](http://falkenblog.blogspot.com/2010/05/nouriel-roubinis-missing-speech.html "Eric Falkenstein") goes in search of Nouriel Roubini’s 2006 speech to the IMF:

> In Michiko Kakutani’s NYT book review of Nouriel Roubini’s Crisis Economics, and in the book’s foreward, a September 7, 2006 IMF speech is highlighted as containing specific warnings about US housing, and how this would lead to a financial contagion. This would seem to be highly prophetic. So I went to his website looking for this speech. It linked to something from 2009. To get to this point I had to register at his site, and they sent me a an email message, asking what I wanted to know (they seem to sell different levels of access at the Roubini Global Economics—a sort of CNBC with only negative spin). I asked to see the 2006 speech mentioned in the NYT book review, and they pointed me towards a different speech in 2006 that was rather vague. So I asked again for the rather prominent September 7 2006 speech, and they did not answer.
>
> I bet the speech mentions not merely the housing problems, but a bunch of things that could go wrong that did not, which would suggest indiscriminate crisis prediction that is not so impressive.

[Here is an IMF account of the speech](http://www.imf.org/external/pubs/ft/survey/2006/101606.pdf "Here is an IMF account of the speech"). Oliver Hartwich and I also referenced the speech in our profile of Roubini for [Juedische Allgemeine](http://www.juedische-allgemeine.de/article/view/id/1475/highlight/kirchner&hartwich "Juedische Allgemeine") (English version [here](http://www.theage.com.au/business/economist-with-a-nose-for-trouble-20090909-fho8.html "here")), for which we had to rely on second-hand accounts.
