---
title: "Part-Time Work at the RBA Board"
date: "2010-10-20"
categories: ["Economics", "Financial Markets", "Monetary Policy"]
---

The so-called part-time members of the RBA Board [were even more part-time than usual in October](http://www.theaustralian.com.au/business/markets/half-rba-board-absent-on-rates/story-e6frg926-1225940903029 "were even more part-time than usual in October"):

> The minutes of the October board meeting, released yesterday, reveal that only three of the six independent board members attended the meeting, with the key voices on the health of retailing, manufacturing and the global economy absent. It was the lowest board meeting attendance in the four years that the Reserve Bank has been releasing its minutes.
>
> The chairman of Bluescope Steel and Brambles, Graham Kraehe, former Woolworths chief executive Roger Corbett, who is also a director of US retailer Walmart and chairman of Fairfax, and the board’s resident academic economist, Warwick McKibbin, all had other commitments.

It only takes five of the nine members to form a quorum.
