---
title: "Peak Oil and the Doomsday Myth"
date: "2010-09-08"
categories: ["Economics", "Oil"]
---

Vaclav Smil has a new book out, [Energy Myths and Realities Bringing Science to the Energy Policy Debate](http://www.aei.org/book/100052 "Energy Myths and Realities Bringing Science to the Energy Policy Debate"). [Here is a taste](http://blog.american.com/?p=19063 "Here is a taste"):

> *There is a finite amount of liquid oil in the Earth’s crust, but estimates of the grand total remain uncertain. Until we explore the entire planet as carefully as we did Oklahoma and Texas, our assessment of global oil reserves will have plenty of room for surprises. Improvements in production also mean that we are now recovering more oil than ever before. And, in addition to our supply of conventional liquid oil, there are vast, untapped reserves of unconventional hydrocarbon fuels, some of which are already being refined for use. A combination of new discoveries, higher recovery rates, and increased use of unconventional resources means that the near-term future of global oil production will not drop off precipitously, as alarmists claim, but will more likely resemble an undulating plateau. Appraisals of the oil future tend to focus on dwindling supply and assume that demand will inexorably grow. But this is not the case. Rising oil prices and economic downturns exert clear downward pressure on demand, and we can reinforce this pressure through more efficient fuel conversions, by promoting sensible alternatives, and, above all, by turning to natural gas. This abundant fuel can do everything oil can, and is already the most important fuel for heating houses and the second most important fuel for generating electricity. The United States already has natural gas reserves sufficient for nearly a century at the current rate of consumption.*
