---
title: "Peter Costello Shows Canada How to Argue Against FDI"
date: "2010-11-01"
categories: ["Economics", "Foreign Investment"]
---

Former Australian Treasurer Peter Costello [tells the Canadians](http://www.nationalpost.com/todays-paper/Aussie+trade+rules/3751433/story.html "tells the Canadians") that his bogus national interest arguments for FDI protectionism are much better than their bogus national interest arguments.

In an [op-ed](http://www.smh.com.au/opinion/rio-feathers-should-stay-in-our-nest-20090217-8a9a.html?page=-1 "op-ed") for domestic rather than Canadian consumption, Costello opposed Chinalco’s proposed acquisition of Rio Tinto and noted that his government sought to stifle the globalisation of BHP to protect Australian jobs:

> I was determined to ensure that BHP’s corporate presence did not disappear from Australia in the same way as CRA, so I put conditions on its dual-listed company structure that required the global headquarters to remain in Australia, that this be specified in all public documents, that the majority of board meetings be in Australia, and most importantly, that the chief executive and chief financial officer have their principal residences in Australia. This last condition was opposed by the company.
>
> Several times the company sought to have these conditions eased but they remain in place, and to its credit, the company has scrupulously complied with them. The world’s largest diversified mining company is still Australian…
>
> The head office generates the corporate, financial, legal and insurance services and the highly skilled jobs that come with them.
