---
title: "Political Leadership on Foreign Investment"
date: "2010-11-30"
categories: ["Economics", "Foreign Investment"]
---

[Andrew Leigh](http://www.onlineopinion.com.au/view.asp?article=11288 "Andrew Leigh") gives News Ltd a taste of its own pitchfork:

> An iron law of populism is that while Australian businesspeople investing abroad are portrayed as job-creating entrepreneurs, foreign investors are depicted as rapacious robber-barons.
>
> And so it is with the latest tabloid campaign against foreign investment. Under headlines such as ‘Chinese buying up our farms’, ‘It’s time to stop selling off the farm’, and ‘It’s time to save our farms from foreign investors’, News Ltd tabloids have recently embarked upon a fear campaign against foreign investment in Australian agriculture. With anecdotes taking the place of statistics, foreign investment has been labelled ‘a dramatic global land grab’, fed by ‘a looming global food shortage’...
>
> Most ironic about the recent tabloid campaign against foreign ownership in agriculture is the fact that the newspapers responsible are themselves owned by US citizen Rupert Murdoch. Indeed, if a campaign were to be waged against foreign ownership in the media industry, you would expect these newspapers to be among the first to describe it as economic populism. It’s funny what happens when the pitchfork is in the other hand.
