---
title: "Population Growth and Capacity Constraints"
date: "2010-05-12"
categories: ["Economics", "Population & Migration"]
---

I have an op-ed in today’s [Australian](http://www.theaustralian.com.au/news/opinion/population-zealots-aim-at-the-wrong-targets/story-e6frg6zo-1225865198595 "Australian") on the issue of population growth and capacity constraints:

> Much of the debate has been predicated on the mistaken view that population growth and immigration policy should be conditioned on existing capacity constraints, whether it be in the areas of housing, infrastructure, water or the environment. Taken to their logical extreme, many of these concerns would have ruled out the founding of the colony of NSW in 1788, when the infrastructure to support the first European settlers was nonexistent.
>
> A growing population adds to demand for existing resources but also supplies the incentives and additional human capital essential to overcoming temporary resource constraints.

Yes, this is the same op-ed that ran in the Canberra Times some time ago.  It got another run as a result of an error made at the Oz. Not that I’m complaining, but we don’t generally make a practice of double-dipping on op-eds.
