---
title: "RBA’s Kraehe Highlights Supply-Side Constraints"
date: "2010-01-22"
categories: ["Economics", "Financial Markets", "Monetary Policy"]
---

RBA Board member [Graham Kraehe](http://www.theaustralian.com.au/business/rbas-focus-is-on-the-battle-with-inflation/story-e6frg8zx-1225822309232 "Graham Kraehe") highlights the capacity constraints driving monetary policy tightening:

> Asked if there was a risk of too much policy tightening choking off recovery, Mr Kraehe said the focus should be on price rises rather than supporting demand.
>
> “The risk is more to cost pressure and inflation than it is to the demand side,” he said.
>
> “Our unemployment has clearly now peaked. We’ve got increasing and continuing demand for employment in the resources sector that will put pressure on wages,” said Mr Kraehe, who is also chairman of Bluescope Steel.
>
> “As an economy, one of the issues for us will be our ability on the supply side, whether it be on housing or the labour market, to supply enough resources to be able to take some of the pressure off cost inflation. Wages is one thing, housing another,” Mr Kraehe said.
