---
title: "Requiem for Clive Hamilton"
date: "2010-05-29"
categories: ["Economics"]
---

Tim Black reads [Clive Hamilton](http://www.spiked-online.com/index.php/site/reviewofbooks_article/8928/ "Clive Hamilton"), so you don’t have to:

> What’s worse for Hamilton, is that this most sinister of modern social types – the shopper – has also appeared in that most populous, and potentially most polluting of countries, China. Not even the disciplined, production-oriented outlook of the Chinese Communist Party could ‘counter the lure of consumption among deprived people’. And not even that clause gave Hamilton pause for thought. No, for him, our desire to consume, to acquire things we want, luxury or not, is irrational and blinding.
>
> Given our collective reluctance to face up to truth, our ‘casual denialism’ as Hamilton calls it, there has to be something to sustain his all-encompassing pessimism. And luckily for manically depressed readers, he finds it: ‘The only good news is provided by the global recession, which may provide a couple of years of breathing space.’ Sadly, he feels that is all it will be: breathing space. Once the economies pick up, we’ll carry on shopping and carry on denying all the way into the flooded, scorched future.

Clive was one of the economists putting his name to the letter supporting the RSPT. That says something about the tax, his co-signatories and Clive.
