---
title: "Rudd’s Way: Working with Australia’s Most Dysfunctional Central Planner"
date: "2010-08-18"
categories: ["Politics"]
---

[Graeme Dobell](http://www.lowyinterpreter.org/post/2010/08/17/How-did-Oz-come-to-this.aspx "Graeme Dobell") reviews Rudd’s Way:

> While this column needed a three-part series last year to grapple with the dysfunctional nature of the Rudd experience, Stuart nails it in one paragraph:
>
> ‘Rudd appeared unable to delegate. His office was nicknamed the ‘black hole’, because briefs would vanish and nothing would emerge. The government’s agenda appeared to swing suddenly and wildly. One moment there would be frenzied progress on an issue until, if it seemed intractable, it would simply be left in limbo.’
>
> As a columnist for The Canberra Times and author of two previous books on The Kevin, Nick Stuart is an experienced journalist who is a known part of the Canberra milieu. Thus, he could quietly gather the quotes and insights that light up Rudd’s Way. Here’s the acid judgement of a senior public servant on Rudd’s mode of operation:
>
> ‘The man’s output is negligible. He gets wound up around the detail, and loses the plot. You’d be concerned if a dep sec (deputy secretary) was working like this, but because he’s PM, he can get away with it.’
>
> Or consider this from a Labor minister, not long after taking office, as the polls were still soaring. The minister complained that Rudd was ‘a bloody perfectionist micro-manager’ who, more seriously, ‘couldn’t give a rat’s about what the party’s policy actually is.’ Then the minister paused for a long moment before concluding: ‘Thank goodness he’s no good at it; otherwise we’d really be up the creek.’…
>
> Consider this line last Friday from Verona Burgess, who has spent more years than she wants to remember writing on the machinations and machinery of the Canberra public service: ‘It is difficult to explain to people outside the capital just how loathed Kevin Rudd had become among large sections of the Australian Public Service (let alone the caucus) and why.’
