---
title: "Rudd Down, Hayek Up, Pundits Red-Faced"
date: "2010-06-28"
categories: ["Politics"]
---

The [exclusion](http://www.theaustralian.com.au/politics/gillard-names-new-ministry/story-e6frgczf-1225885199669 "exclusion") of Kevin Rudd from the first Gillard cabinet completes the wholesale political collapse of the Rudd bubble. It may be coincidental, but still highly poetic, that Rudd’s demise coincides with F A Hayek’s Road to Serfdom [going to number one on Amazon](http://online.wsj.com/article/SB10001424052748704911704575326500718166146.html?mod=WSJ_Opinion_LEFTTopOpinion "going to number one on Amazon"). Rudd was the author of a ham-fisted critique of Hayek, presented to CIS in 2006, which effectively foreshadowed his intellectual, personal and policy failings in government.

When I worked in federal politics, I was struck by how much media punditry reflected personal relationships between pundits and politicians at the expense of journalistic objectivity. [Andrew Bolt](http://blogs.news.com.au/heraldsun/andrewbolt/index.php/heraldsun/comments/will_the_media_learn_from_rudd/ "Andrew Bolt") rounds up some of the casualties on this occasion.  [The Australian’s Cut and Paste](http://www.theaustralian.com.au/news/opinion/a-source-who-kept-the-smh-on-message/story-e6frg6zo-1225884500509 "The Australian’s Cut and Paste") also does its usual compare and contrast, courtesy of Mark Latham, who should know a thing or two about the bursting of media-driven leadership bubbles:

> Peter Hartcher in The Sydney Morning Herald on Wednesday:
>
> WHEN Kevin Rudd talked confidently on Monday about the strength of Labor support for his leadership it was not based solely on bravado, he has been discreetly checking that his party is still behind him. The Herald has learnt from a number of MPs that the Prime Minister’s chief of staff Alister Jordan has been talking privately to almost half the caucus. While some caucus members are edgy about their electoral prospects, Mr Jordan’s exercise evidently discovered no defectors from the Rudd camp.
>
> Mark Latham in The Australian Financial Review yesterday:
>
> A DEFINING feature of Rudd’s prime ministership was his constant briefing of Hartcher on the behind-the-scenes processes behind big decisions, invariably to glorify his own contribution. As one caucus wag told me earlier this year, “Kevin doesn’t change his underpants these days without telling Hartcher about it.” It would have been obvious to his colleagues (Gillard in particular) that the Herald’s story came from the PM’s office, a stunning valedictory to Rudd’s misreading of his colleagues and his ineptitude as a caucus tactician.

[Alex Robson and Sinclair Davidson](http://www.nationals.org.au/News/LatestNews/tabid/94/articleType/ArticleView/articleId/3577/categoryId/2/Ruddonomics.aspx "Alex Robson and Sinclair Davidson") provided perhaps the most prescient assessment of Rudd’s likely performance in government in a Wall Street Journal editorial published before the last federal election:

> *If Ruddonomics wins the day, Australia could find itself back in a 1970s mindset, with bigger government and a less competitive economy.*
