---
title: "Sell the Gold Stock, Burn the Gold Bugs"
date: "2010-10-22"
categories: ["Economics", "Financial Markets", "Fiscal Policy", "Gold", "Monetary Policy"]
---

[Ed Truman](http://www.piie.com/publications/opeds/oped.cfm?ResearchID=1681 "Ed Truman") makes the case for the US Treasury to follow the IMF and offload its gold stock:

> the US Treasury holds 261.5 million fine troy ounces of gold. The government has been sitting on that gold since the Great Depression, receiving no return. At the current market price of \$1,300 per ounce, the US gold stock is worth \$340 billion. The Treasury secretary, with the approval of the president, has the power to sell (and buy) gold on terms that the secretary considers most beneficial to the public interest. Revenues from sales must be used to reduce the national debt.
>
> If the United States were to sell its entire gold stock at the current market price, it would reduce the gross government debt by 2.25 percent of gross domestic product. Based on the average interest cost from 2005 to 2008, this reduction in debt would trim the budget deficit by \$15 billion annually. Thus, the Obama administration would be doing something about the US fiscal debt and deficit without reducing near-term support for the ailing economy.

This would of course be incredibly lazy public policy, but should nonetheless give gold bugs pause. As I have noted previously, there is a certain irony in people who fear an over-supply of money taking refuge in an asset in which governments hold substantial stocks and for which the price is arguably in a stock rather than a flow equilibrium.
