---
title: "Sentences You Won’t Read from the Reserve Bank of Australia"
date: "2010-01-28"
categories: ["Economics", "Financial Markets", "Fiscal Policy", "Monetary Policy"]
---

From today’s Reserve Bank of New Zealand [intra-quarter policy review](http://www.rbnz.govt.nz/news/2010/3886943.html "intra-quarter policy review"):

> *As growth becomes self sustaining, fiscal consolidation would help reduce the work that monetary policy might otherwise need to do.*

This is more the RBA’s style (see if you can guess when the RBA said it before clicking [here](http://www.rba.gov.au/media-releases/2000/mr-00-14.html "here")):

> The purpose of my answer was to explain why it was wrong to claim that rises in interest rates were due to the stance of fiscal policy.
>
> My answer in no way constituted an attack on the Government’s fiscal policy.

Governor Macfarlane was right to argue that fiscal policy was then irrelevant to inflation and interest rates.  But more recently, Governor Stevens has [argued](http://www.cis.org.au/executive_highlights/EH2009/eh92209.html "argued") that fiscal stimulus has supported economic activity and that there is a trade-off between monetary and fiscal stimulus.  Just don’t expect him to spell out the implications of that logic in a policy announcement as candid as that from the RBNZ.
