---
title: "Steve Keen’s Latest Media Stunt"
date: "2010-02-16"
categories: ["Economics", "House Prices"]
---

In an attempt to snatch victory from the jaws of defeat in his wager with Rory Robertson, [Steve Keen](http://www.smh.com.au/business/summer-in-the-city-wins-a-short-rollover-20100215-o2yg.html "Steve Keen") seeks to lead a lemming-like march of housing doomers up the slopes of Mt. Kosciuszko:

> rather than accept the victory of his more bullish opponent, it appears the professor is trying to muster the biggest gathering of market bears in Australian economic history. He has already coined the event ‘‘Walking Against Australia’s Property Mania.’’
>
> Keen will start his 224-kilometre walk from Parliament House in Canberra on April 15, and aside from a documentary crew, his girlfriend and a masseuse, he hopes to be accompanied by some of the 3000-odd members of his Debtwatch blog.

The [other side](http://www.abc.net.au/news/stories/2010/02/16/2821232.htm "other side") of the bet is unimpressed:

> “Betting the house on an economist’s forecast typically is not a smart move. Unfortunately, Dr Keen recklessly encouraged everyday Australians to sell their homes at what turned out to be the peak of the global financial crisis, and the trough in local house prices,” Rory Robertson responded.
>
> “That’s why he’s getting set to walk from Canberra to Mt Kosciuszko wearing a t-shirt saying, ‘I was hopelessly wrong on house prices. Ask me how!’”
