---
title: "Sticking it Up the Wrong People"
date: "2010-04-17"
categories: ["Economics", "House Prices"]
---

Steve Keen’s [housing doomsday cult](http://www.theage.com.au/national/academic-walks-off-bet-20100415-shmh.html "housing doomsday cult") is wending its way up Mt Kosciuszko with an ETA of 23 April. By my count, only ten people turned up to see him off from Canberra, but Keen is quoted as saying:

> *’‘This has actually garnered me support,’’ he said. ‘‘People are saying, thank god someone is sticking it up the property industry.’‘*

A theme of Keen’s housing doomsday cult is that hapless home buyers are being manipulated into buying property, resulting in a ‘housing mania.’  Like many of his fellow travelers, Keen sees housing affordability as a demand-side rather than a supply-side problem. 

Yet it should be obvious that it is in the interests of the property industry to promote housing affordability so that it can sell more houses.  The industry’s lobby groups and industry associations consistently argue for an easing of the tax burden on housing, development restrictions and other supply-side constraints on the provision of new homes.  The property industry’s interest in building and selling more homes is aligned with the consumer interest in making housing more affordable.  Keen is sticking it to the wrong people.  Like any industry, it has its share of spruikers and shonks, but the property industry in general is the solution and not the problem.
