---
title: "Sydney: Too Many People in 1912?"
date: "2010-08-19"
categories: ["Economics", "Population & Migration"]
---

I have an [op-ed](http://www.theaustralian.com.au/national-affairs/commentary/city-got-big-but-never-grew-up/story-e6frgd0x-1225907040578 "op-ed") in today’s Australian referencing an article in the Sydney Morning Herald from 1912 about how Sydney’s then transport system supposedly could not cope with a population of 700,000.

The text below the fold is a slightly longer version that went out on Friday in the Ideas@TheCentre series. You can subscribe to Ideas@TheCentre [here](http://www.cis.org.au/media-information/e-news/user "here").

‘Small Capacity for a Great City Properly So-Called’

On 24 July 1912, an article on page 16 of the Sydney Morning Herald noted on the occasion of the opening of a new state parliament that ‘there were few more really vital concerns referred to than that of the traffic of Sydney.’ With a population of only around 700,000 people, it seemed Sydney could not cope. The article described Sydney as a ‘criminally congested city’ and declared that ‘the streets of Sydney…are a disgrace to a modern community.’

Among the litany of transport problems facing Sydney in 1912 were ‘the breakdown of the tramway system under the population growth, the futility of tramways where railways are called for, the congestion of the narrow central streets under a tramway system strained beyond reasonable limit of traffic service and jostled into confusion by the steady increase of motor car and other wheeled traffic.’ The article lamented the lack of foresight and action by the authorities, saying that ‘we have known for years what was best to do and we have constantly postponed the actual doing…that shilly-shally must come to an end once and for all.’

While these problems sound all too familiar, they did not prevent Sydney adding more than three million people to its population in the subsequent 98 years. No doubt the author of the article would have found the prospect of a city of 4.3 million people inconceivable and yet here we are, confronting similar challenges, only on a larger scale.

This little bit of Sydney history nicely illustrates the point that transport, infrastructure and other problems have nothing to do with the level of the population, but how well we handle the challenges that inevitably accompany a growing population and economy. The author of the1912 article understood this well: ‘the fact that we have come upon traffic chaos with our population argues a very small capacity for handling the difficulties of a great city properly so-called…Sydney is proclaimed as grown beyond governing itself.’

While Sydney has grown, the ‘small capacity’ of our governments and politicians arguably remains the same.
