---
title: "Taking the Myth Out of The Myth of the Rational of the Market"
date: "2010-01-12"
categories: ["Economics", "Financial Markets"]
---

Justin Fox tells me that the UK-Australian edition of his *The Myth of the Rational Market* is out this month.  My review of the US edition can be found over the fold.

Justin Fox, T*he Myth of the Rational Market: A History of Risk, Reward and Delusion on Wall Street* (HaperCollins, 2009).

The *Myth of the Rational Market* is an intellectual history of the efficient market hypothesis (EMH) and its role in shaping modern financial markets.  The book also chronicles the rise of behavioural finance and its putative challenge to the EMH.  An epilogue gives a balanced assessment of the factors at work in the global financial crisis that unfolded from mid-2007.  The book is a worthy successor to Peter Bernstein’s *Capital Ideas* (1993) and *Against the Gods* (1998) and Fox acknowledges his debt to Bernstein’s earlier work. 

Despite its title, the book is not a critique of the role of rationality in understanding financial markets.  Fox is ultimately unable to come to firm conclusions about the validity of the EMH, declaring that ‘during my years working \[on the book\] I’ve continued to struggle with what to make of the conflicting but not diametrically opposed worldviews of Fama and Thaler’ (p. 299) (among the best known exponents of the EMH and behavioural finance respectively).  While this sounds unsatisfying, it is the right conclusion to draw. 

It is unlikely that there will ever be a definitive empirical test of the EMH, a reality that most of its proponents should readily concede.  This is partly a technical problem driven by model uncertainty, but it is also an issue that goes to the very heart of our understanding of the role of markets.  The issue turns on whether markets are viewed as an equilibrium process or as an evolutionary process.  The former view finds deviations in financial prices from the predictions of the EMH problematic, in the same way that departures from the perfectly competitive model are often assumed to be problematic in markets for goods and services.  Ironically, most financial markets come closer to satisfying efficiency norms than markets in goods and services, yet it is financial market prices that are more likely to be viewed with suspicion. The evolutionary view (which this reviewer shares) finds departures from efficiency norms neither surprising nor problematic for the central implication of the EMH, which is that asset prices are not generally forecastable. 

The EMH is also commonly assumed to require that market prices yield truth judgments, but this view is mistaken.  Fox is confused by the critical distinction between a price that is informationally efficient and one that is deemed to be ‘right’ or ‘correct’ in the sense of accurately reflecting fundamentals or predicting the future.  Informationally efficient markets may have these properties more often than not, but they can also be completely ‘wrong’ in this sense without invalidating the EMH.  Fox elaborates on Eugene Fama’s 1969 definition of the EMH with the claim that this led to ‘a market in which prices were *right*’ (p. 297 emphasis in original).  This is an all too common mistake and Fox should have been more alert to the fact that is for the most part behavioralists who make this claim, not proponents of the EMH.  Fox quotes Shiller declaring that it ‘is one of the most remarkable errors in the history of economic thought.  It is remarkable in the immediacy of its logical error and the sweep and implications of its conclusion’ (p. 197).  But the error is all Shiller’s.  Unlike Shiller, proponents of the EMH are generally very careful about this distinction.  Fox argues that proponents of the EMH have been ‘defining efficiency down’ (p. 297), when in fact it is the behaviouralists who have defined efficiency up. Fox gives the game away when he says that behaviouralists ‘believed that financial markets did a pretty good job of getting prices right.  They just didn’t think the market did a *perfect* job’ (p. 253 emphasis in original).  Markets that are held to an impossible norm are bound to be found wanting. 

Proponents of the EMH and behavioural finance are both equally wedded to equilibrium assumptions.  Their differences are mostly about the extent to which financial markets conform to efficiency norms derived from equilibrium conditions.  Fox only briefly mentions the Austrian and institutional traditions in his review of heterodox schools of thought (p. 301).  It is these evolutionary approaches to market behaviour that offer a way forward and the potential to reconcile insights from both the EMH and behavioural finance.  Fox is to be commended for producing an even-handed and open-minded intellectual history.
