---
title: "‘That’s an Eternity from Now’: The Day of Reckoning for the Tierney-Simmons Wager"
date: "2010-12-29"
categories: ["Commodity Prices", "Economics", "Oil"]
---

[John Tierney](http://www.nytimes.com/2010/12/28/science/28tierney.html?_r=1&ref=science "John Tierney") collects on his ‘peak oil’ bet with the late Matthew Simmons:

> Five years ago, Matthew R. Simmons and I bet \$5,000. It was a wager about the future of energy supplies — a Malthusian pessimist versus a Cornucopian optimist — and now the day of reckoning is nigh: Jan. 1, 2011…
>
> When I found a new bettor in 2005, the first person I told was Julian’s widow, Rita Simon, a public affairs professor at American University. She was so happy to see Julian’s tradition continue that she wanted to share the bet with me, so we each ended up each putting \$2,500 against Mr. Simmons’s \$5,000.
>
> Just as Mr. Simmons predicted, oil prices did soar well beyond \$65. With the global economy booming in the summer of 2008, the price of a barrel of oil reached \$145. American foreign-policy experts called for policies to secure access to this increasingly scarce resource; environmentalists advocated crash programs to reduce dependence on fossil fuels; companies producing power from wind and other alternative energies rushed to expand capacity.
>
> When the global recession hit in the fall of 2008, the price plummeted below \$50, but at the end of that year Mr. Simmons was quoted in The Baltimore Sun sounding confident. When Jay Hancock, a Sun financial columnist, asked if he was having any second thoughts about the wager, Mr. Simmons replied: “God, no. We bet on the average price in 2010. That’s an eternity from now.”
>
> The past year the price has rebounded, but the average for 2010 has been just under \$80, which is the equivalent of about \$71 in 2005 dollars — a little higher than the \$65 at the time of our bet, but far below the \$200 threshold set by Mr. Simmons.
>
> What lesson do we draw from this? I’d hoped to let Mr. Simmons give his view, but I’m very sorry to report that he died in August, at the age of 67. The colleagues handling his affairs reviewed the numbers last week and declared that Mr. Simmons’s \$5,000 should be awarded to me and to Rita Simon on Jan. 1…
