---
title: "The Behavioural Economics of the Public Sector"
date: "2010-10-27"
categories: ["Economics"]
---

An important insight of the public choice literature is that relocating people from the private to the public sector does not miraculously transform them into promoters of the public interest. In my discussion of Doug Ginsburg and Joshua Wright’s paper ‘Behavioural Economics, Law and Liberty’ at the Mont Pelerin Society General Meeting in Sydney, I noted that relocating people from the private to the public sector does not make them any more rational either. This has mostly fatal implications for the attempt to hijack behavioural economics for the purposes of promoting increased government intervention discussed by Ginsburg and Wright. [Matt Ridley](http://online.wsj.com/article/SB10001424052702304410504575560323807741154.html?KEYWORDS=Matt+Ridley "Matt Ridley") references a paper by [Slavisa Tasic](http://brunoleonimedia.servingfreedom.net/Mises2010/Papers/IBL_Mises2010_Tasic.pdf "Slavisa Tasic") which develops the point I was making in much greater detail.
