---
title: "‘The Full Omelette’: Treasury After the RSPT"
date: "2010-07-04"
categories: ["Economics", "Fiscal Policy", "Politics"]
---

The post-RSPT backlash against [Treasury](http://www.theaustralian.com.au/business/treasury-tarnished-by-turn-of-events-over-mining-super-tax/story-e6frg8zx-1225887313787 "Treasury"):

> A key figure in the negotiating team of one of the major mining houses puts it more bluntly: “Clearly Ken Henry was on a mission from God. The fact that Treasury had got religion was not the biggest surprise. What we were especially amazed at was the level of sheer naivete and incompetence. The grasp of fundamental economics—more specifically commercial reality—was barely past what you learn in year 12 at high school.”…
>
> In the end the miners were not provided with Treasury’s modelling until last Wednesday. These were the numbers that, according one insider, had come from “planet Mars”.
>
> “They had made it up and had no idea how to back it up. It was like sitting university professors down to lecture primary school students,” one of the miners’ advisers claimed yesterday.
