---
title: "The Real Giant Vampire Squid"
date: "2010-04-20"
categories: ["Economics", "Financial Markets"]
---

Sucking up \$381 billion and counting, according to the CBO. [Pete Wallison](http://online.wsj.com/article/SB10001424052748704671904575193910683111250.html?mod=WSJ_hps_sections_opinion "Pete Wallison") lays responsibility firmly at the feet of Barack Obama:

> It was in 2005 that the GSEs—which had been acquiring increasing numbers of subprime and Alt-A loans for many years in order to meet their HUD-imposed affordable housing requirements—accelerated the purchases that led to their 2008 insolvency. If legislation along the lines of the Senate committee’s bill had been enacted in that year, many if not all the losses that Fannie and Freddie have suffered, and will suffer in the future, might have been avoided.
>
> Why was there no action in the full Senate? As most Americans know today, it takes 60 votes to cut off debate in the Senate, and the Republicans had only 55. To close debate and proceed to the enactment of the committee-passed bill, the Republicans needed five Democrats to vote with them. But in a 45 member Democratic caucus that included Barack Obama and the current Senate Banking Chairman Christopher Dodd (D., Conn.), these votes could not be found.
>
> Recently, President Obama has taken to accusing others of representing “special interests.” In an April radio address he stated that his financial regulatory proposals were struggling in the Senate because “the financial industry and its powerful lobby have opposed modest safeguards against the kinds of reckless risks and bad practices that led to this very crisis.”
>
> He should know. As a senator, he was the third largest recipient of campaign contributions from Fannie Mae and Freddie Mac, behind only Sens. Chris Dodd and John Kerry.
