---
title: "The Bronze Medal for Economic Freedom"
date: "2010-01-20"
categories: ["Economics"]
---

Australia maintains its third place in the [Heritage Foundation-Wall Street Journal Index of Economic Freedom](http://online.wsj.com/article/SB10001424052748704541004575011684172064228.html?mod=WSJ_hpp_sections_opinion "Heritage Foundation-Wall Street Journal Index of Economic Freedom") for 2010, once again trailing Hong Kong and Singapore.  The US crash-dives to 8th place, behind Canada.

The index does not purport to measure political freedom.  Australia’s political institutions are at least as free as any other country, and certainly more free than those in Hong Kong and Singapore.  Australia could thus make a plausible case for being the world’s freest country after giving sufficient weight to the political as well as the economic dimensions of freedom, at least as measured by Heritage. 

CIS will be holding an event on ‘Valuing and Measuring Economic Freedom’ on 28 January at which I will be speaking.  Details [here](http://www.cis.org.au/events/current_events.html "here").
