---
title: "The Right Policy Toward China"
date: "2010-10-26"
categories: ["Economics", "Financial Markets"]
---

Send them flowers and chocolates argues [John Cochrane](http://online.wsj.com/article/SB10001424052702303467004575574101493496596.html?mod=rss_opinion_main "John Cochrane"):

> They put a few trillion dollars worth of stuff on boats and sent it to us in exchange for U.S. government bonds. Those bonds lost a lot of value when the dollar fell relative to the euro and other currencies. Then they put more stuff on boats and took in ever more dubious debt in exchange. We’re in the process of devaluing again. The Chinese government’s accumulation of U.S. debt represents a tragic investment decision, not a currency-manipulation effort. The right policy is flowers and chocolates, or at least a polite thank-you note.
>
> Yet Mr. Geithner thinks that the Chinese somehow hurt us. There is at work here a strange marriage of Keynesianism and mercantilism—the view that U.S. consumers supported the world economy by spending beyond our means, so that other people could have the pleasure of sending things in exchange for pieces of paper.
>
> This is all as fuzzy as it seems. Markets and exchange rates are not always right. But it is a pipe dream that busybodies at the IMF can find “imbalances,” properly diagnose “overvalued” exchange rates, then “coordinate” structural, fiscal and exchange rate policies to “facilitate an orderly rebalancing of global demand,” especially using “medium-term targets” rather than concrete actions. The German economics minister, Rainer Brüderle, called this “planned economy thinking.” He was being generous. Planners have a clearer idea of what they are doing.
