---
title: "The Dodd Bill and Crony Capitalism"
date: "2010-05-15"
categories: ["Economics", "Financial Markets", "Rule of Law"]
---

[Cliffford Asness and Aaron Brown](http://online.wsj.com/article/SB10001424052748704250104575238841836433282.html "Cliffford Asness and Aaron Brown") on the rise of the Treasury-financial complex:

> The Dodd bill is perfectly designed to create the largest and most powerful crony system in history. It’s not that the people, regulator or regulated, are personally corrupt. It’s that the system will itself select for, reward and enforce corruption.
>
> No financial professional will be able to turn down a “request” for a campaign contribution, and all financial institutions will hire former staffers as advisers or directors. No regulator can afford to antagonize a potential future employer. Regulators themselves must kowtow to Congress, which can use them for under-the table subsidies to favored groups. None of this is new to politics, of course, but the scale and lack of defined powers are.
