---
title: "The Repudiation of Kevin Rudd"
date: "2010-06-24"
categories: ["Politics"]
---

Congratulations to the ALP caucus for acting decisively to remove Kevin Rudd as Labor leader and Prime Minister. To be repudiated by his own party on the eve of an election is a well-deserved humiliation for Australia’s worst Prime Minister since Gough Whitlam. The fact that Rudd was still burbling inanely about the G20 at the press conference announcing the leadership spill must surely have convinced many members of the ALP caucus of Rudd’s disconnectedness from reality, born of his spectacular hubris and vanity.

It is noteworthy that their handling of the ETS was decisive in the demise of both Kevin Rudd and Malcolm Turnbull. The cynicism and opportunism of the Rudd-Turnbull ETS was one of the most shameful episodes in the history of Australian federal politics. It is testimony to the remarkable efficiency of the Australian political system that it is capable of so swiftly liquidating its own errors.

**UPDATE:**Australian dollar-denominated asset markets outperform on change of leadership.
