---
title: "The Official Lies that Underpin the Euro"
date: "2010-03-12"
categories: ["Economics", "Financial Markets"]
---

[Der Spiegel](http://www.spiegel.de/international/europe/0,1518,682432,00.html "Der Spiegel") on the official lies that underpin European Monetary Union:

> *Since joining the euro zone, the 16 euro countries have violated the deficit rule, under which net new debt cannot exceed 3 percent of GDP, 43 times. Most of the infractions have occurred in the last two years. Greece is at the top of the list of violators. Only once did the country manage to push its deficit rate below the magic limit, and only with an extremely creative trick: The Greeks sugarcoated their statistics by including prostitution, black-market trade and gambling in the calculation of economic output. As a result, GDP rose by a stunning 25 percent in 2006, and the deficit dropped to 2.9 percent.*

While this is a remarkable story coming from Der Spiegel, the authors still can’t quite come to terms with giving up on the euro, suggesting that its problems could be solved through a common financial policy and an IMF-like European Monetary Fund.  Still, as [Anne Appbaum](http://www.slate.com/id/2247257/ "Anne Appbaum") notes, opinion in Germany is shifting.
