---
title: "The FHA as Predatory Lender"
date: "2010-12-01"
categories: ["Economics", "Financial Markets"]
---

[The FHA takes over from Freddie and Fannie](http://www.american.com/archive/2010/november/how-the-government-is-creating-another-housing-bubble "The FHA takes over from Freddie and Fannie"):

> While everyone has been watching Fannie and Freddie, the administration has quietly shifted most federal high-risk mortgage initiatives to FHA, the government’s original subprime lender. Along with two other federal agencies, FHA now accounts for about 60 percent of all U.S. home purchase mortgage originations. This amounts to more than \$1 trillion and is rising rapidly. The administration justifies this policy by saying it is necessary to support the mortgage market, yet borrowers are once again receiving high-risk loans…
>
> The Dodd-Frank Act, however, exempts FHA and other government agencies from appropriate standards on mortgage quality. This will give low-quality mortgages a direct route into the market once again; it will be like putting Fannie and Freddie back in the same business, but with an explicit government guarantee.
>
> For example, thanks to expanded government lending, 60 percent of home purchase loans now have down payments of less than 5 percent, compared to 40 percent at the height of the bubble, and the FHA projects that it will increase its insured loans total to \$1.34 trillion by 2013. Indeed, the FHA just announced its intention to push almost half of its home purchase volume into subprime territory by 2014-2017, essentially a guarantee to put taxpayers at risk again.
