---
title: "The Bipartisan Failure on Immigration"
date: "2010-06-04"
categories: ["Economics", "Population & Migration"]
---

A [WSJ editorial](http://online.wsj.com/article/SB10001424052748704366504575277892136791312.html?mod=WSJ_Opinion_LEFTTopBucket "WSJ editorial") wags its finger at Scott Morrisson:

> *This marks a bipartisan failure. While government and opposition duke it out over a few thousand asylum seekers, neither party seems overly concerned about expanding legal work opportunities. Mr. Rudd’s government is oddly proud that net immigration will likely fall to around 250,000 this year. Representative Scott Morrison, the opposition point man on the issue, told us his party supports skilled migration but that immigration levels “need to be sustainable”—code for sympathy to restrictionism. Both sides miss the key point: Australia doesn’t know what skills it will need in the future or who has those skills. If that “low-skilled” but bright and hardworking teenager from Malaysia can’t get into Australia to wash dishes while he goes to night school, he’ll one day start a billion-dollar company somewhere else*.
