---
title: "The Biggest Bail-Out: Where’s The Outrage?"
date: "2010-03-30"
categories: ["Economics", "Financial Markets"]
---

[Matthew Richardson](http://www.nypost.com/p/news/opinion/opedcolumnists/fannie_freddie_the_biggest_bailout_rAyIYVNxCGXc4UrUntXkCK "Matthew Richardson") on the missing outrage over Freddie and Fannie:

> There’s a chance that the support thrown at the rest of the financial sector—\$465 billion of direct capital, \$285 billion of loan guarantees and insurance of \$418 billion of assets—isn’t all money down the drain. \$175 billion has been returned, the loan guarantees look much safer, and the insurance program, mainly for Citigroup, has been terminated.
>
> Even the poster child for financial excess, AIG, may be able to fully pay off the government if the housing market doesn’t deteriorate further or the economy substantially improves.
>
> But the chances are slim to none that Fannie or Freddie will be able to pay back the funds. It is highly likely that taxpayers will lose well over \$200 billion—and it may well pass \$300 billion. When the history of the crisis is all written, these two institutions will turn out to be the most costly of the financial sector—worse than AIG, Citigroup or Bank of America/Merrill Lynch.
>
> So where is the outrage?
>
> It’s not the pay packages: Compensation at Fannie and Freddie was right up there with other financial firms. For example, in 2006 and 2007, as housing conditions were weakening and the crisis started, the CEO salaries of Fannie were \$14.4 and \$12.2 million, and Freddie were \$15.5 million and \$19.8 million.

As Eric Falkenstein has also noted, the losses attending Freddie and Fannie are equal to around 90 Nick Leesons.
