---
title: "The Irrelevance of Modern Political Science"
date: "2010-09-15"
categories: ["Economics", "Politics"]
---

[Steven Hayward](http://american.com/archive/2010/september/the-irrelevance-of-modern-political-science "Steven Hayward") on why nobody notices political scientists:

> Ask yourself this question: Among policy makers in Washington, are you more likely to find academic economic journals in their offices, or academic political science journals? Why do economists not face the same kind of worry about their “relevance,” even though their mathematical approaches to the subject matter can be even more esoteric and forbidding?...
>
> As my late friend Tom Silver once wrote: “Imagine yourself marooned on a desert island with only ten books to read, but in this case ten books not of your choosing. Suppose them all to be books written by behavior political scientists during the past twenty years. Question: Do you think that you would die first of boredom, or of self-inflicted wounds?”
