---
title: "The Four Horsemen of the Acropolis"
date: "2010-07-03"
categories: ["Economics", "Financial Markets"]
---

[Der Spiegel](http://www.spiegel.de/international/germany/0,1518,703613-2,00.html "Der Spiegel") profiles the four German professors valiantly trying to bring down the euro and the bailout of Greece:

> *The court in Karlsruhe dismissed their request for a court injunction against the Greek bailout. But now that the Constitutional Court is reviewing at length whether to consider their complaint, Schachtschneider believes that it stands a chance of succeeding after all. In any event, he intends to publish the 60-page brief as a legal reference book, thereby going down in the history of the anti-euro movement once again. Hankel is against the idea. He would prefer that the group publish a book that is more accessible to the general public, something along the lines of their 1998 book “Die Euro- Klage. Warum die Währungsunion scheitern muss” (“The Euro Suit: Why the Monetary Union Must Fail”) or the 2001 work “Die Euro-Illusion” (“The Euro Illusion”).*
