---
title: "The Year RBA Watchers Got an Involuntary Early Retirement"
date: "2010-12-10"
categories: ["Economics", "Financial Markets", "Monetary Policy"]
---

Ross Gittins, giving his traditional address to the Australian Business Economists’ annual forecasting conference:

> *It’s become a lot harder for you guys to predict now the nation’s economics editors have retired from the prediction game. But that’s the way the more loud-mouthed of your brethren seem to have wanted it.*

A loud-and-proud [Chris Joye](http://christopherjoye.blogspot.com/2010/12/ross-gittins-slaps-me-and-adam-carr.html "Chris Joye") translates:

> *Ross Gittins delivered a fascinating speech this week during which he gave me a subtle slap for forcing the RBA to stop tipping-off journos about the internal executive’s rate recommendations prior to its Board meetings, which in and of itself is an acknowledgement that demonstrates how right we were to push this line (our actions also brought about the demise of the former Shadow Governor, Terry McCrann, after the October meeting).*

Gittins’ remarks effectively concede that the economic writers in question can’t play the prediction game nearly as well now that they have a more circumscribed relationship with the Bank. [Glenn Stevens denies that Board decisions have ever been leaked](../2010/the_rba_and_the_media.qmd "Glenn Stevens denies that Board decisions have ever been leaked"), but there is a distinction between the outright leaking of a Board decision and the backgrounding and nudging of economics writers that previously took place.
