---
title: "The Irrelevance of Bank Interest Rate Margins"
date: "2010-03-23"
categories: ["Economics", "Financial Markets", "Monetary Policy"]
---

At least [one journalist](http://www.theaustralian.com.au/business/opinion/more-gouging-building-schools-than-in-home-loans/story-e6frg9p6-1225843988867 "one journalist") gets the irrelevance of bank interest rate margins when the Reserve Bank is explicitly targeting credit conditions:

> *This means that the Reserve Bank, rather than bank gouging, is effectively targeting and setting the interest rate charged to mortgage borrowers because this is what influences the demand for credit. If the 20-25 basis point increase in the banks’ net interest margin suddenly disappeared, the Reserve Bank would simply hike its cash rate by the same amount so as to return mortgage lending rates back toward their more normal 7 per cent-plus levels.*

As Stutchbury notes, bank bashing is little more than an attempt by politicians to divert attention from the implications of their own policies for interest rates.  At least [one bank](http://news.smh.com.au/breaking-news-business/westpac-looks-to-big-rate-rises-report-20100323-qroo.html "one bank") is privately telling its shareholders to brace for more political thuggery:

> Westpac is under financial pressure to raise its interest rates but fears a political backlash, chief executive Gail Kelly has reportedly told a private shareholder briefing.
>
> Mrs Kelly told the briefing political pressure from Canberra could make it tough for the bank to increase home and business loan interest rates ahead of the federal election, due later this year

Mrs Kelly might also care to explain to Westpac shareholders why it is [donating money to political parties](http://periodicdisclosures.aec.gov.au/Donor.aspx?SubmissionID=11&ClientID=34096 "donating money to political parties") that are actively seeking to damage the bank’s franchise.
