---
title: "The Psychopathology of Kevin Rudd"
date: "2010-07-04"
categories: ["Politics"]
---

Staff writers at [The Australian](http://www.theaustralian.com.au/news/features/rudd-undone-by-the-enemy-within/story-e6frg6z6-1225887059051 "The Australian") have compiled a comprehensive psychopathology of former Prime Minister Kevin Rudd, showing him to be every bit as bizarre as former Labor leader Mark Latham. I was particularly struck by this passage:

> In April 2008, at the height of his power and popularity, he gave an address to the Sydney Institute annual dinner that completely misjudged his audience.
>
> Many of those there groaned inwardly as Rudd failed to read the occasion or recognise the sheer power in the room.

Rudd did exactly the same thing at the closing dinner of a private CIS function I attended in July 2008, except people groaned outwardly on that occasion. The audience included a large number of the country’s most senior business people. Half way through the speech, the people at my table were looking at each other with a WTF? expression on their face. I could not tell whether the speech was a calculated insult, or whether Rudd sincerely thought the speech was appropriate to the occasion. It was an extraordinary performance in any event.
