---
title: "The Downside of China’s Managed Exchange Rate"
date: "2010-11-22"
categories: ["Economics", "Financial Markets", "Monetary Policy"]
---

[Inflation and price controls](http://online.wsj.com/article/SB10001424052748704648604575620342009025512.html?KEYWORDS=china+inflation "Inflation and price controls").  As we have often noted, China’s managed exchange rate is a much bigger problem for them than it is for the rest of the world. [Former RBA Governor Ian Macfarlane](http://www.rba.gov.au/speeches/2005/sp-gov-120505.html "Former RBA Governor Ian Macfarlane") told the Chinese as much in 2005, when he compared China to Australia in the 1970s:

> surpluses may be more difficult to sustain in the long run than deficits are for some other countries. I speak from experience here as Australia faced this problem in the early 1970s and did not handle it successfully. At that time, Australia briefly experienced a current account surplus and also became a favourable destination for capital flows. As the money poured in from both these sources it had to be sterilised or it would flow directly into the banking system and through that into money and credit aggregates, with obvious inflationary results.
>
> The problem we found was that in order to sell the official paper in sufficient volumes to soak up the inflow, interest rates had to be raised, and this induced further inflow. In the end, the monetary aggregates grew too quickly and inflation soon rose to an unacceptable rate. We came to the conclusion then that it was not possible to restrain an over-exuberant and inflation-prone economy only by domestic tightening. Exchange rate adjustment was required in order to take away the ‘one way bet’ aspect of the exchange rate. We eventually did this, but we were too slow and the inflation had already become entrenched.
>
> So far, China has made a much better job of handling this situation than we in Australia did 30 years ago. And, of course, it is made easier by the fact that it is occurring in a world environment of low and stable inflation rather than the rising inflation of 30 years ago. But, ultimately, I think the point will be reached where domestic restraint has to be augmented by action on the exchange rate.

Five years on, Macfarlane’s speech remains highly relevant. He could usefully give the same speech in Washington today.
