---
title: "The Misanthropic Origins of Declinism"
date: "2010-06-02"
categories: ["Economics"]
---

[Tim Black](http://www.spiked-online.com/index.php/debates/copenhagen_article/8944 "Tim Black") reviews Matt Ridley’s The Rational Optimist:

> *Just after the end of the First World War, Britain’s Liberal prime minister David Lloyd George lamented: ‘How can Britain run an A1 empire with a C3 population \[medical categories for army recruits\]?’ This was no isolated complaint – it was indicative of a wider sense of Britain’s national decline refracted through the prism of biology. ‘If you go back to the turn of the twentieth century’, Ridley says, ‘there was an absolute domination of the book-publishing world by “declinism” literature, particularly about the so-called “degeneration of the race”. In the view of many at the time, this was because “stupid” people were having too many babies, the lower classes were evil, nasty and full of tuberculosis, and didn’t have the requisite physical strength. All this ludicrous stuff was hugely dominant.’*

The web site for the book can be found [here](http://www.rationaloptimist.com/ "here").
