---
title: "The G20 and ‘Balanced’ Trade"
date: "2010-11-16"
categories: ["Economics", "Financial Markets"]
---

I have a column at the [ABC’s Drum Unleashed](http://www.abc.net.au/unleashed/41084.html "ABC’s Drum Unleashed") arguing that the G20 is doing more harm than good:

> The G20 is still saddled with the same mercantilist thinking that underpinned these earlier episodes of international policy coordination. That thinking mistakenly blames the global financial crisis on cross-border capital flows, rather than the role of America’s government-sponsored enterprises in misdirecting these capital flows. The Obama administration’s call for the G20 to set numerical targets for trade ‘imbalances’ would do more to threaten free trade and global economic growth than to sustain it.
>
> Since the early 1990s, Australian policymakers have embraced the ‘capitalist acts between consenting adults’ view of current account imbalances, not least because Australia’s economic success has been built on the global trade in saving and investment that the Obama administration now wants to constrain through the G20.
>
> More recently, however, Treasury has seemingly re-embraced mercantilist notions of ‘balanced’ trade. Treasurer Swan called the Obama administration’s proposal “constructive”. Yet the 4 per cent limit on current account imbalances proposed by US treasury secretary Geithner would condemn Australia to permanently slower economic growth and lower living standards.
