---
title: "The $389 Billion Third Rail of American Politics"
date: "2010-08-18"
categories: ["Economics", "Financial Markets"]
---

The US Treasury Department convened a conference on the vexed issue of housing finance reform. Remarkably, even the [New York Times](http://www.nytimes.com/2010/08/17/business/17sorkin.html?_r=2&ref=business "New York Times") saw straight through the politics of GSE reform in its reporting on proceedings:

> *The consensus was that neither Democrats nor Republicans wanted to touch an issue that would dredge up decisions made by both parties over the last decade that looked bad in light of the financial crisis. Fannie and Freddie was now the third rail of American politics.*

‘Looked bad’ doesn’t even begin to cover what has been a catastrophic failure of America’s political institutions for which there has been little or no accountability.

The de facto nationalisation of US housing finance through its Congressional-mandated GSEs may have been a catastrophe for the US, yet for [PIMCO’s Bill Gross](http://www.businessweek.com/news/2010-08-17/gross-urges-full-nationalization-of-housing-finance.html "PIMCO’s Bill Gross"), nothing succeeds like failure:

> Bill Gross, who runs the world’s biggest bond fund at Pacific Investment Management Co., said the U.S. should consider “full nationalization” of the mortgage- finance system…
>
> “To suggest that there’s a large place for private financing in the future of housing finance is unrealistic,” Gross said today at a U.S. Treasury Department conference in Washington. “Government is part of our future. We need a government balance sheet. To suggest that the private market come back in is simply impractical. It won’t work.”

Gross conveniently ignores the fact that the housing GSEs have effectively been on the books of the US government for their entire existence.
