---
title: "The G20: Last Refuge of Political Failure"
date: "2010-07-02"
categories: ["Economics", "Politics"]
---

Former Prime Minister [Kevin Rudd](http://www.theaustralian.com.au/news/opinion/a-pm-who-phoned-foreign-friends-too-often/story-e6frg6zo-1225886882821 "Kevin Rudd"), on the eve of his execution:

> We have large challenges ahead, not least of which is an upcoming G20 summit in Toronto, at which I am currently scheduled to lead an Australian delegation. This G20 summit will deal with a whole range of fundamental reforms to the financial system, which goes to the interests of the Australian banks and the cost of credit in this country.
>
> These are important national interests to pursue, it is one reason why I’ve decided, apart from others, that its important to resolve this matter of the leadership as a matter of urgency.

Former Treasurer [Peter Costello’s](http://www.openaustralia.org/debates/?id=2009-06-15.19.2&s=speaker:10149#g21.1 "Peter Costello’s") farewell speech to the House, after he decided being opposition leader was too much like hard work:

> *I do not need to say that, from our perspective, a seat at the table which represents 90 per cent of global GDP is a very, very important diplomatic position for us and for our country.*

Former Treasurer [Peter Costello](http://www.abc.net.au/insiders/content/2006/s1786567.htm "Peter Costello"), explaining why the G20 is very, very important:

> BARRIE CASSIDY: All right. Let’s move on to the G20 now and its involvement next weekend under your chairmanship. 90 per cent of the world’s economies under one roof, but could you identify one key result you would like to see emerge from the conference?
>
> PETER COSTELLO: First of all, let’s say, Barrie, this is the biggest financial conference Australia has ever hosted and ever will. This organisation, where Australia not only has a seat at the table, of the 20 most important economies of the world, but is chairing it, that brings together the developed world and the developing world, is important in itself. That’s significant in itself.

[Alan Beattie](http://blogs.ft.com/rachmanblog/2008/07/the-g8-and-alan-beattie/ "Alan Beattie"), on how to write-up a G20 communique:

> By reporters everywhere
>
> An ineffectual international organisation yesterday issued a stark warning about a situation it has absolutely no power to change, the latest in a series of self-serving interventions by toothless intergovernmental bodies.
>
> “We are seriously concerned about this most serious outbreak of seriousness,” said the head of the institution, either a former minister from a developing country or a mid-level European or American bureaucrat. “This is a wake-up call to the world. They must take on board the vital message that my organisation exists.”
>
> The director of the body, based in one of New York, Washington or an agreeable Western European city, was speaking at its annual conference, at which ministers from around the world gather to wring their hands impotently about the most fashionable issue of the day. The organisation has sought to justify its almost completely fruitless existence by joining its many fellow talking-shops in highlighting whatever crisis has recently gained most coverage in the global media.
>
> “Governments around the world must come together to combat whatever this year’s worrying situation has turned out to be,” the director said. “It is not yet time to panic, but if it goes on much further without my institution gaining some credit for sounding off on the issue, we will be justified in labelling it a crisis.”
>
> The organisation, whose existence the White House barely acknowledges and to which hardly any member government intends to give more money or extra powers, has long been fighting a war of attrition against its own irrelevance. By making a big deal out of the fact that the world’s most salient topical issue will be placed on its agenda and then issuing a largely derivative annual report on the subject, it hopes to convey the entirely erroneous impression that it has any influence whatsoever on the situation.
>
> The intervention follows a resounding call to action in the communiqué of the Group of \[number goes here\] countries at their recent summit in a remote place no-one had previously heard of. The G\[number goes here\] meeting was preceded by the familiar interminable and inconclusive discussions about whether the G\[number goes here\] was sufficiently representative of the international community, or whether it should be expanded into a G\[number plus 1, 2 or higher goes here\] including China, India or any other scary emerging market country that attendees cared to name.
>
> The story was given further padding by a study from an ambulance-chasing Washington think-tank, which warned that it would continue to convene media conference calls until its quixotic and politically suicidal plan to ameliorate whatever crisis was gathering had been given respectful though substantially undeserved attention.
