---
title: "The Making of Dick Smith’s Population Puzzle"
date: "2010-08-13"
categories: ["Economics", "Population & Migration"]
---

In February this year, I was contacted by Dick Smith’s researcher Sarah Gilbert to provide some background for his anti-population growth documentary, Dick Smith’s Population Puzzle. She mentioned a column by [Paul Sheehan](http://www.smh.com.au/opinion/politics/australias-population-fairytale-20090927-g7o5.html?skin=text-only "Paul Sheehan"), which had quoted me making the point that faster population growth required faster economic growth to maintain living standards. No doubt they saw this as a bad thing, but must have finally twigged that I thought it wasn’t, because I heard no more from them, even though Dick and the production crew were on campus a few weeks later and could have easily dropped in to see me. They did interview my UTS colleague Jock Collins, but they obviously didn’t like what he had to say either, because it was not included in the final cut.

Dick later wrote to me taking exception to an [op-ed](http://www.theaustralian.com.au/news/opinion/population-zealots-aim-at-the-wrong-targets/story-e6frg6zo-1225865198595 "op-ed") I had written for The Australian, in which I called some of his arguments absurd. I took the opportunity to try and steer Dick in the right direction by referring him to some books by [Julian Simon](http://www.amazon.com/dp/0691003815?tag=institutional-20&camp=0&creative=0&linkCode=as1&creativeASIN=0691003815&adid=0K5WNFG464VV4T9N1M45 "Julian Simon"), but he gave no indication he ever bothered to read them.

The documentary screened on the ABC last night. Dick gave significant air time to only one pro-growth advocate, Bernard Salt, but could not help impugning his expertise and motivation. There may be plenty of things wrong with Bernard Salt, but being a historian and working with KPMG are not among them. If Salt is as unqualified as Dick would have us believe, why include him in the documentary? Because Dick has a completely closed-mind on the issue and is uninterested in giving the other side of the argument a fair go.
