---
title: "The Economic Consensus We Could Do Without"
date: "2010-06-23"
categories: ["Economics"]
---

Treasury Secretary Ken Henry’s call for economists to shut-up and ‘serve the national interest’ finds little favour with [Warwick McKibbin](http://www.smh.com.au/business/academics-have-no-choice-but-to-speak-out-against-policy-20100622-yvvd.html "Warwick McKibbin"):

> Warwick McKibbin, the director of the Australian National University’s research school of economics, said he was stunned by a call from Mr Henry on Monday for academics to ‘‘put down their weapons’’ rather than nit-pick over government proposals such at the emissions trading scheme. ‘‘I don’t know whether Ken was fingering me but there weren’t too many other people out there arguing against an ETS,’’ he said.
>
> ‘‘I have enormous respect for Ken Henry but he can’t believe that you should have consensus because it is better to have bad policy that everyone agrees with than eventually get good policy that will work.
>
> ‘‘The ETS was a flawed scheme. Had the government got it through it would be dead by now because of the financial crisis.
>
> ‘‘I also disagreed with the scale of the stimulus package … It wasn’t evidence-based policy; they panicked. The government rammed those decisions through the economy even though they were fraught with risk. No one was consulted about an alternative view and if you did say anything you were attacked by the Treasurer and the Prime Minister in public.’‘…
>
> ‘‘If the government won’t engage you behind closed doors then an academic has no other choice than to express their opinion in the public interest, in public, for the public to assess.
>
> ‘‘The stimulus created a problem. The government overspent but they had enough in reserve. Then they decided that because of politics they had to get their spending back so they could claim they had fiscal surplus - for which there is no economic basis, by the way - so they come up with a really badly designed resource tax to try and get the position to look good three years from now, and in the middle of a sovereign risk crisis exposed the economy to a reassessment of sovereign risk.
>
> ‘‘The review of the tax system should have been independent of the Treasury and then critiqued by it and other economic agencies.
>
> ‘‘Treasury, as far as I can tell, has become an arm of political policy. Historically they have always been the ones who have said, ‘Wait a minute, this policy of subsidising green cars to try and save the constituents of a particular electorate is not a very sensible way to spend \$8 billion.’ You just don’t see that now.’‘
