---
title: "The Rare Earths that are Neither Rare nor Earths"
date: "2010-10-25"
categories: ["Commodity Prices", "Economics"]
---

[Tim Worstall](http://www.foreignpolicy.com/articles/2010/09/29/you-dont-bring-a-praseodymium-knife-to-a-gunfight?page=full "Tim Worstall") on why we shouldn’t worry about China’s interest in rare earths:

> But the non-rarity of the rare earths themselves means that China’s position isn’t sustainable. That California mine, for instance, could potentially supply 20 percent of world demand, currently around 130,000 tons a year. Another facility, Lynas Corp.‘s Mount Weld in Australia, has the capacity to produce a similar amount. In fact, there are enough rare earths in the millions of tons of sands we already process for titanium dioxide (used to make white paint) to fill the gap, while we throw away 30,000 tons a year or so in the wastes of the aluminum industry. There’s that much or more in what we don’t bother to collect from the mining of phosphates for fertilizers, and no one has even bothered to measure how much there is in the waste from burning coal.
>
> If rare earths are so precious, why isn’t the United States working harder to collect them? The main reason is that, for these last 25 years, China has been supplying all we could eat at prices we were more than happy to pay. If Beijing wants to raise its prices and start using supplies as geopolitical bargaining chips, so what? The rest of the world will simply roll up its sleeves and ramp up production, and the monopoly will be broken.
