---
title: "Three Wasted Years"
date: "2010-04-29"
categories: ["Economics", "Politics"]
---

Former federal Labor minister [Gary Johns](http://www.theaustralian.com.au/news/opinion/government-without-a-cause-attacking-its-friends/story-e6frg6zo-1225859601078 "Gary Johns") on three wasted years of government:

> a government without purpose roams the stage with nothing to show and looks to pick a fight or blame others, in this case state governments for allegedly choking the hospitals.
>
> The Department of Prime Minister and Cabinet is overwhelmed by constant requests from the Prime Minister’s office for new and better schemes and promotions and photo opportunities. There is no agenda, no priority setting and no point at all except to get Rudd on the front page…
>
> The electoral timidity, the profligacy, the spin, the lack of reason, the internal bullying, the vast waste of money, the interminable photos with children, the transparent use of religion with the photos at church on Sunday, have all embittered his already unimpressed caucus colleagues.
