---
title: "Too Big to Nail: Why There Will Never be an Investigation into Freddie and Fannie"
date: "2010-07-30"
categories: ["Economics", "Financial Markets"]
---

[Jonathan Weil](http://noir.bloomberg.com/apps/news?pid=20601039&sid=a5c8W3Vom.58 "Jonathan Weil") asks why there is no investigation into Freddie and Fannie:

> Still absent from the government’s agenda is any serious effort to hold anyone accountable for their ruin or investigate why they collapsed.
>
> Back in December 2003, after Freddie disclosed what in retrospect was a relatively mild accounting scandal, its regulator published an exhaustive 185-page report cataloguing the company’s financial-reporting abuses. In May 2006, the same regulator disclosed similar findings about Fannie’s books in a report covering 348 pages.
>
> Strangely, there’s no similar examination under way today by the Federal Housing Finance Agency into the reasons why Fannie and Freddie imploded in 2008, or whether anyone at the companies did anything improper. That’s probably because the agency and its predecessor, the Office of Federal Housing Enterprise Oversight, bear responsibility for letting the companies resume their natural tendency to run amok.
>
> So here we go again. This month Congress passed the 2,323- page Dodd-Frank Act without any clear understanding of why the financial crisis happened—and without doing a thing to address Fannie and Freddie, which were central players. Now the Obama administration says it will deliver a reform proposal to Congress by January on the nation’s housing-finance system, including Fannie and Freddie. Yet the government still hasn’t undertaken any comprehensive inquiry into why these companies blew up and who was at fault.

I can only assume Weil’s column is rhetorical, because it is shriekingly obvious why there will never be an inquiry into the failure of Freddie and Fannie. The two GSEs did exactly what Congress mandated them to do, while Congress also stymied the attempt to reform them in 2004-05. Politicians are not interested in establishing an inquiry that can only lead to one conclusion: they were the authors of the global financial crisis of 2008.
