---
title: "Treasury Hand-Wringing on House Prices"
date: "2010-11-20"
categories: ["Economics", "House Prices"]
---

The FOI desk at The Australian uncovered the following, which it then beats-up into ‘[Treasury warning on home bubble](http://www.theaustralian.com.au/business/property/treasury-warning-on-home-price-bubble/story-e6frg9gx-1225956866267 "Treasury warning on home bubble")’:

> Phil Garton, the manager of Treasury’s Macro Financial Linkages Unit, sent colleagues a draft paper on the rise in household debt, prospects for further growth in the debt-to-income ratio and the potential implications of slower household debt growth.
>
> His email prompted an exchange with Steve Morling, currently the general manager of the Domestic Economy Division, who argued the paper should “make a bit more about the risks”.
>
> “The elephant in the room is house prices or more specifically the risk of a precipitous drop in them, perhaps from an external shock \[SK: didn’t we just have one of those?\] or perhaps from their own internal dynamics when affordability constraints or capacity debt levels see prices and expectations of house prices start to move in the opposite direction,” Mr Morling wrote on June 15.
>
> “(I) know there are very supportive fundamentals, but prices rose by 50-60 per cent in three to four years in the early part of this decade, with largely unchanged fundamentals, so they can have a life of their own.
>
> “And given what’s happened elsewhere I’m far less sanguine about this - and the interplay with debt - than in the past.”
>
> Mr Garton agreed that there would be risks if the fundamentals of low interest rates, unemployment, and financial deregulation “reversed significantly”. But he maintained the price growth in the early 2000s was based on a “lagged response” to improvements in the fundamentals, and questioned how Australia could have maintained a bubble for more than six years.
>
> Mr Morling said other bubbles had lasted that long, and the fundamentals were often used to justify price rises - including in Britain where a debate over lack of supply drove property prices higher “before the British property bubble burst”.
>
> “(I) think price expectations can take over from the fundamental drivers that you have identified for extended periods, including generating house price falls,” he wrote.

The only remarkable thing about this analysis is how pedestrian it is. It’s not much better than the kind of hand-wringing you would expect from the writers at left-wing scandal sheet Crikey, who have long viewed the Australian housing market as an anti-capitalist morality play that can only have one ending.

Asked for reaction, the Treasurer’s office had this to say:

> *it is the considered position of the Treasurer and the Treasury that our housing market reflects the fundamentals of supply and demand and not a bubble - specifically that Australia is simply not building enough new houses*.

Not that they will do anything about it.
