---
title: "US Dollar Bulls Who Can’t Get Enough"
date: "2010-01-13"
categories: ["Economics", "Financial Markets"]
---

[Follow the ETF money](http://online.wsj.com/article/SB10001424052748704055104574652730461676484.html?mod=WSJ_PersonalFinance_PF4 "Follow the ETF money"):

> Some ETF investors appear to be positioning hedging against a continually rising dollar in 2010, based on the surging popularity of PowerShares DB U.S. Dollar Index Bullish Fund (UUP), which holds nearly \$3 billion in assets.
>
> The fund follows the movement of the U.S. dollar against a basket of six major currencies: the euro, the Japanese yen, the British pound, the Canadian dollar, the Swedish krona and the Swiss franc. As its name suggests, the ETF profits when the dollar strengthens against global currencies.
>
> The fund has been such a hot seller that, twice in late 2009, it was forced to halt the creation of new shares when it ran out and awaited regulatory clearance to issue more shares.
>
> Its mirror image, the PowerShares DB U.S. Dollar Index Bearish Fund (UDN), is geared to make money from a weakening dollar. It is much smaller with just under \$300 million in total assets.
