---
title: "Yet Another New Tax on NSW Housing"
date: "2010-05-13"
categories: ["Economics", "House Prices"]
---

The NSW government has introduced yet another [new tax on housing transactions](http://www.theaustralian.com.au/politics/state-politics/m-housing-slug-sneaked-in/story-e6frgczx-1225865754516 "new tax on housing transactions"). Yesterday, I gave a post-budget presentation to a [business group in Western Sydney](http://www.westernweekender.com.au/index.php?option=com_content&task=view&id=1761 "business group in Western Sydney"), together with Westpac’s Matthew Hassan. Matthew presented some stunning charts showing the growth in the tax burden on housing in each state, with NSW the clear winner. Indeed, the tax burden on a new house and land package on Sydney’s suburban fringe is now such as to make it unprofitable to bring to market, which helps explain why new housing supply in the state is running at 1950s levels.

If only some of the outrage directed against negative gearing and capital gains tax concessions by ignorant journalists and commentators could be marshalled against the taxes and charges that are really responsible for putting upward pressure on house prices.
