---
title: "How Important is an Australia-China FTA to Kevin Rudd?"
date: "2013-07-16"
categories: ["Economics", "Foreign Investment"]
---

I have an op-ed in the [Business Spectator](http://www.businessspectator.com.au/article/2013/7/16/china/seizing-sino-free-trade-moment) noting that the Australia-China free trade deal sought by Prime Minister Kevin Rudd would be best facilitated by Australia giving up its micro-management of Chinese FDI. As noted in the op-ed, this is not something that comes naturally to the Prime Minister. While an agreement could be struck that excludes investment, this would be a wasted opportunity. It would also stand in contrast to the growing likelihood of a US-China investment agreement.

> Under current arrangements, very little Chinese FDI in Australia escapes scrutiny because of Canberra’s policy of screening all investment by foreign government-related entities, regardless of transaction size.
>
> Canberra maintains that this policy is applied in a non-discriminatory fashion to all foreign government-related investors. But the rules for these entities were only publicly articulated subsequent to the surge in Chinese investment from 2008 onwards. The Chinese can thank the US Embassy in Canberra and Wikileaks for confirming their suspicions that the policy is unofficially directed at them.
>
> The marked deterioration in Australia-China relations during Kevin Rudd’s previous occupancy of the Lodge was in no small part due to the inability of his government to articulate a coherent policy on FDI from China.
>
> Most Chinese FDI proposals are ultimately approved, which in itself is strong evidence that the current level of regulatory scrutiny at the border is costly and unnecessary.
>
> Chinese direct investment in Australia is subject to the same competition, tax, industrial relations, planning, development and environmental laws that apply to other investors.
>
> The additional layer of regulatory scrutiny Australia imposes at the border adds little to these robust regulatory frameworks behind the border. It serves mainly as a vehicle for political interference in commercial transactions the government does not like.
>
> The rejection or modification of foreign investment proposals has often been explicitly protectionist in intent.
>
> Former Treasurer Wayne Swan rejected Singapore Exchange’s bid for the Australian Securities Exchange in part because it would “risk us losing many of our financial sector jobs”.
>
> Minmetals’ acquisition of OZ Minerals was made subject to conditions that were, to quote the former treasurer again, “designed to protect around 2000 Australian jobs”.
>
> The Australian government has even sought to use the FDI screening process to regulate the level of output and employment in local mining operations.
>
> Such micro-management of FDI trivialises the concept of the ‘national interest’ that is meant to inform the application of the treasurer’s discretion under the Foreign Acquisitions and Takeovers Act.
