---
title: "Scott Sumner in Australia"
date: "2013-07-22"
categories: ["Classical Liberalism", "Economics", "Monetary Policy"]
---

Scott Sumner will be in Australia next month as a guest of the Centre for Independent Studies. He will be attending our Consilium conference on the Gold Coast, but will also be doing a seminar with the Economic Society of Australia (NSW) in Sydney.

Scott has written an article in the latest issue of our journal [Policy](http://digitaledition.cis.org.au/), ‘A New View of the Great Recession.’ It is an excellent introduction to some of the ideas informing what Lars Christensen has dubbed ‘the new market monetarism.’

I’m also pleased to [read](http://www.themoneyillusion.com/?p=22393) that Scott will be attending next year’s [Mont Pelerin Society](https://www.montpelerin.org/montpelerin/mpsAbout.html) meeting, where he will be on a panel on The Coming Threat of Inflation. As Scott notes on his blog:

> *The 500 classical liberals in the audience will be surprised to learn that the threat is that inflation will be too low over the next 5 years.*

In fact, MPS includes quite a few market monetarists, especially among the younger members (I’m young by MPS standards!) This should not be surprising since the new market monetarism is firmly in the orthodox monetarist tradition of Milton Friedman, one of the Society’s founding members. Unfortunately, many of the older MPS members are still wedded to fighting the inflation battles of the 1970s. They need to move on!
