---
title: "Scott Sumner Enjoyed His Time in Australia"
date: "2013-08-29"
categories: ["Economics", "Monetary Policy"]
---

Scott Sumner enjoyed his time in Australia, presenting at the Centre for Independent Studies’ Consilium conference on the Gold Coast and the Economic Society of Australia (New South Wales) in Sydney. You can read Scott’s account [here](http://www.themoneyillusion.com/?p=23188).

Scott’s presentation covered similar ground to his article in the Winter issue of our journal [Policy](http://digitaledition.cis.org.au/#folio=1). I did a video interview with Scott that should be available soon. Watch this space.

Scott says some nice things about the Centre for Independent Studies in the post linked above. Many potential overseas speakers are reluctant to make what is admittedly a long trip to Australia. But take it from Scott, if you come to Australia, we will show you a good time!

One thing I learned as a result of my presentation at Consilium was that then Treasurer Jim Cairns offered the RBA Governorship to Charles Goodhart in the early 1970s (who wisely turned it down). This was quite possibly the only good idea Jim Cairns ever had. So there is at least some historical precedent for my long-standing suggestion for an internationally competitive process for filling senior positions at the RBA.
