---
title: "Strengthening Australia’s Fiscal Institutions"
date: "2013-12-12"
categories: ["Economics", "Fiscal Policy"]
---

I have a new paper in the CIS Target 30 series, [Strengthening Australia’s Fiscal Institutions](http://www.cis.org.au/images/stories/target30/t30.06.pdf), that re-states the case for legislated fiscal rules to be monitored and enforced by an independent statutory Fiscal Commission.

It is often argued that fiscal rules are unlikely to serve as an effective discipline on fiscal policy in the absence of political will. This is undoubtedly true, but fiscal rules can be seen as a mechanism through which the political will to tackle issues in relation to long-run fiscal sustainability can find more effective expression. If politicians are unwilling to put into law what they say they are committed to doing, then it is less likely that they will deliver on these commitments. The willingness to adopt fiscal rules can thus be seen as a test of the degree of political commitment.

Measures to strengthen Australia’s fiscal institutions should be a key recommendation of the Abbott government’s Commission of Audit.
