---
title: "The CIS Journal ‘Policy’ has a New Editor"
date: "2013-03-22"
categories: ["Centre for Independent Studies"]
---

I have taken over as the editor of [Policy](http://www.cis.org.au/publications/policy-magazine), journal of the Centre for Independent Studies. I am currently finalising the Autumn (southern hemisphere!) issue, but I am looking for contributions to the Winter issue with a deadline of 30 April.

Please keep Policy in mind as an outlet for your ideas. Policy reaches an influential audience and we are planning a number of initiatives to extend its reach and build the subscriber base.

We are open to feature articles, interviews, review essays and book reviews covering a wide range of policy issues and ideas from any disciplinary perspective. Note that contributions are subject to a refereeing process.

Feel free to get in touch to discuss any ideas you may have. Contributor deadlines for future issues are as follows:

Winter 2013: 30 April\
Spring 2013: 30 July\
Summer 2013/14: 30 October
