---
title: "Time to Dump Australia’s Anti-Dumping System: My New Paper with CIS"
date: "2013-06-05"
categories: ["Economics", "Free Trade & Protectionism"]
---

The Centre for Independent Studies has released my new paper [Time to Dump Australia’s Anti-Dumping System](http://www.cis.org.au/images/stories/issue-analysis/ia141.pdf). The paper notes the multi-decade failure to have public interest considerations incorporated in the administration of anti-dumping in Australia:

> The Productivity Commission argued that ‘the highest priority for reform of Australia’s anti-dumping system is to introduce consideration of the broader public interest.’  The commission (under its previous names) has been arguing for this position since at least 1985.  This multi-decade failure to incorporate public interest considerations into Australian anti-dumping and countervailing law suggests the system is unlikely ever to serve the public rather than private producer interests. The government’s rejection of the commission’s proposal for even a bounded public interest test ensures that Australia’s anti-dumping system will continue to serve the interests of a small number of Australian producers at the expense of other Australian businesses and consumers. The ‘reforms’ implemented by the federal government and supported by the federal opposition set the stage for creeping protectionism via anti-dumping actions that will impose growing costs on the Australian economy. This is part of a broader trend on the part of the federal government to extend assistance to Australian industry at the expense of consumers and taxpayers, and to stand in the way of a structural adjustment in the Australian economy.
>
> The public interest will be best served by repealing the anti-dumping and countervailing provisions of Australian law and dismantling the associated bureaucracy within Customs. This was a recommendation of the 1989 Garnaut review that remains un-implemented nearly a quarter of a century later. Doing so would send a powerful signal to Australian industry that it must adapt to the structural changes in the world and domestic economies rather than going cap-in-hand to the federal government for assistance at the expense of consumers and taxpayers.
>
> Australia can also set a powerful example on the world stage as a country that prospers because it has abandoned recourse to these protectionist measures.
