---
title: "Australia has become a net exporter of human and financial capital"
date: "2021-12-22"
categories: ["Financial Markets", "Free Trade & Protectionism", "Population & Migration"]
---

I have an op-ed in the [AFR](https://www.afr.com/policy/economy/australian-capital-and-talent-is-leaving-home-20211221-p59j84) noting that Australia has become a net exporter of human and financial capital. I argue that reversing these net outflows should be a priority for post-pandemic recovery. Full text below the fold. Note AFR is responsible for ‘savings’ instead of ‘saving’!

For almost all of its history, Australia was a net importer of both people and capital. The reasons are straightforward enough. Australia offered a better life for migrants and attractive investment opportunities for foreign capital.

But in the last few years, these people and capital flows have seen a dramatic reversal. While the pandemic is heavily implicated in these outcomes, public policy is not doing enough to restore the inflow of human and financial capital.

For the year-ended in June, net overseas migration (NOM) was minus 88,800 people. Net overseas migration has now been negative for five quarters. In the June quarter alone, over 47,000 people emigrated from Australia.

The population grew by just 0.2% over the year to June. There was an outright decline in Australia’s population in the September quarter last year.

The government upgraded the outlook for net overseas migration in its Mid-Year Economic and Fiscal Outlook relative to the May Budget on the assumption of a gradual relaxation of border controls from the end of this year.

But the outlook for net overseas migration remains subdued. A net outflow of 41,000 people is still expected for this financial year. NOM is positive in 2022-23, but does not approach pre-pandemic levels until 2024-25.

On this basis, the population is expected to grow by only 0.3% this financial year, 1.2% in 2022-23 and 1.4% by the end of the forward estimates.\
Australia will be 1.5 million people short in 2030-31 relative to what was expected at the time of the pre-pandemic budget update at the end of 2019.

Australia’s border controls were key to controlling the pandemic in 2020. Closed borders were very forgiving of policy mistakes behind the border, at least until the middle of this year.

The federal government, in cooperation with the states, could have scaled-up managed isolation and quarantine capacity, even if still short of that needed to sustain pre-pandemic levels of international arrivals. Instead, international arrivals were heavily rationed.

The government should consider catch-up increases in net overseas migration to offset the losses due to the pandemic border closures. This could include uncapping permanent migration numbers, similar to the temporary migration program.

As well as net outflows of human capital, Australia has also seen massive outflows of financial capital.

In the year-ended September, Australia exported a net \$74 billion in capital, the flip-side of a current account surplus running at a massive 4.4% of GDP. The current account has been in surplus since the June quarter 2019, averaging 2.6% of GDP.

While the contribution of iron ore exports to the current account surplus is well understood, the underlying cause of the surplus is an excess of domestic saving over investment.

Australia is now sending more capital abroad than the rest of the world is investing in Australia. In gross terms, Australia invested a massive \$172 billion in foreign stocks and bonds and a further \$9.2 billion in direct investment abroad in the year-ended in September.

There is nothing wrong with Australians investing abroad. But it is a problem to the extent that it reflects a lack of investment opportunities at home.\
Much of this capital outflow is directed to the United States, one of the few countries with capital markets large enough to accommodate the rest of the world’s excess saving. But US investment in Australia has been declining over the last three years. Australia has underperformed peer economies in attracting US investment.

Border closures have weighed on foreign investment in Australia by making due diligence on cross-border acquisitions more difficult.

While Australian policymakers use to fret about persistent current account deficits, those deficits for the most part reflected strong investment outcomes. Persistent current account surpluses due to excess saving and a lack of investment are arguably more problematic.

The current account surplus should narrow as the economy recovers from the pandemic. The government’s mid-year budget update expects the current account to be back in deficit next financial year. But it is worth recalling Australia was running current account surpluses in the three quarters before the onset of the pandemic in March last year.

To the extent that the legislated increase in the Superannuation Guarantee compulsory contribution rate to 12% increases national saving, it will make\
Australia’s excess saving problem worse. Domestic capital markets are awash with conscripted saving, which is increasingly finding a home offshore.\
Public policy needs to focus on increasing investment rather than saving. Raising saving will not by itself lift domestic investment performance.

Increasing net overseas migration would help raise investment demand. Greater inflows of human and financial capital should be viewed as complementary and a key element of post-pandemic recovery.

Dr Stephen Kirchner is program director, International Economy, at the United States Studies Centre, University of Sydney.
