---
title: "Australia-US bilateral investment in 2020: Taxing times"
date: "2021-07-05"
categories: ["Foreign Investment"]
---

I have a new report out with the United States Studies Centre, [Australia-US bilateral investment in 2020: Taxing times](https://www.ussc.edu.au/analysis/australia-us-bilateral-investment-in-2020-taxing-times). The report highlight Australia’s underperformance in attracting US investment since the passage of President Trump’s Tax Cuts and Jobs Act in 2017. While President Biden’s proposed corporate tax changes will improve Australia’s attractiveness on a relative basis, they also weigh on US corporate investment globally, with ambiguous implications for future US investment in Australia.

US direct investment in Australia is not completely fungible with other forms of foreign capital inflow. Many of the benefits of FDI, like knowledge and intellectual property transfers, access to managerial talent and global supply-chains is firm- and country-specific. The US remains the world’s most innovative economy and US FDI abroad is a major channel through which US productivity gains spillover to the rest of the world, including Australia. Portfolio investment and investment from other countries is not a perfect substitute for US direct investment.
