---
title: "G7 tax deal is a threat to reformers"
date: "2021-06-08"
categories: ["Economics"]
---

I have an op-ed in the [AFR](https://www.afr.com/policy/economy/g7-tax-deal-is-a-threat-to-reformers-20210606-p57yla) arguing that the G7’s proposed cartelisation of the international tax system threatens reform-oriented small open economies, but Australia could perversely benefit given its high tax burden on capital. Ironically, the proposed 15% minimum corporate tax could backfire and become a floor target for international tax competition. Full text below the fold.

The finance ministers of the G7 countries have reached in-principle agreement on a global minimum corporate tax rate of at least 15 per cent, as well as taxing more of the income of multinational companies in the locations where it is generated.

While yet to be formally agreed and implemented, the proposals threaten to cartelise the international tax system in favour of high-tax and relatively closed economies at the expense of more reform-oriented small open economies.

The latest push for a global minimum tax has been led by the US under the new Biden Administration. It is part of a broader US effort to signal a return to global leadership and a renewed commitment to multilateralism.

The Biden Administration originally proposed a 21 per cent minimum, but this has been trimmed to 15 percent in an effort to win broader agreement.

The next hurdle is endorsement by the G20 countries at their meeting in Venice next month. The aim to is multilateralise the new tax arrangements under the auspices of the OECD.

The US interest in a global minimum tax is partly driven by the Biden Administration’s commitment to raise the US corporate tax to 28 percent. When combined with state taxes, this would give the US a combined statutory rate over 32%, the least competitive in the OECD.

This compares to a current combined federal and state average rate of just under 26% put in place under former President Trump’s Tax Reform and Jobs Act of 2017.

The higher tax rate would otherwise penalise US companies relative to foreign competitors and reduce investment and incentives to produce in the US relative to the rest of the world.

The US also wants to put a stop to the proliferation of digital services taxes (DST) that discriminate against US tech giants by agreeing on a multilateral framework for profit allocation. The US has threatened to impose retaliatory tariffs on six countries, including the UK, if they proceed with unilateral DSTs.

Australia shelved its proposed DST pending the outcome of these multilateral negotiations.

The OECD’s multilateral tax reform agenda has been driven by high-tax and relatively closed economies that face competition from low-tax and reform-oriented small open economies, although the average corporate tax rate in the OECD excluding the US is little changed over the last decade.

The global minimum tax would enable the high-tax countries to ‘tax back’ income earned in low-tax jurisdictions.

While meant to prevent a ‘race to the bottom’ on corporate tax, the changes could backfire and trigger a new race to the global floor of 15%.

Otherwise, the proposals will have effects that go beyond the distribution of global taxing powers. They would affect the global allocation of capital and encourage high-tax jurisdictions to maintain their existing barriers to cross-border trade and investment.

Small open economies like Ireland, the Netherlands and Singapore that have served as a haven for innovative, knowledge-intensive multinational enterprises at the forefront of globalisation and that have propagated new business models around the world would be rendered less attractive as destinations for new investment.

Instead, the proposals would redistribute global tax revenue and capital to some of the world’s worst performing governments and economies.

As a relatively high-tax jurisdiction for capital, Australia could perversely benefit from the proposed global tax redistribution framework. Australia has one of the highest corporate tax rates in the OECD and an average tax burden on capital of 46%.

Australia’s high corporate tax burden relative to the more competitive tax settings put in place by the former Trump Administration has seen a collapse in US investment in Australia.

While overall foreign direct investment (FDI) in Australia fell in 2020 in line with the OECD average, FDI from the US significantly underperformed.

Australian Bureau of Statistics data shows that US investment in Australia has fallen over the last three years.

Data from the US Bureau of Economic Analysis shows the US FDI position in Australia has fallen by 4.3% since 2017.

Australia has underperformed peer economies like Canada, the UK and New Zealand as a destination for US investment, partly because these economies have had more competitive corporate tax rates.

Foreign capital inflow from other countries is a poor substitute because of the knowledge transfers that uniquely attach to US FDI.

A study by the European Centre for International Political Economy found that eliminating the corporate tax differential among the OECD economies at a minimum\
rate of 12.5% would raise foreign investment in Australia by 20% by making Australia more competitive with currently lower-tax jurisdictions. High-tax France was the only OECD country that would gain more.

Having abandoned corporate tax reform at home, the US and Australia have a common interest in promoting higher taxes abroad, but at the cost of a less dynamic and innovative global economy.

Dr Stephen Kirchner is program director, Trade and Investment, at the United States Studies Centre, University of Sydney.
