---
title: "Omicron is the least of the problems for global trade"
date: "2021-11-30"
categories: ["Free Trade & Protectionism"]
---

I have an op-ed in the [AFR](https://www.afr.com/policy/economy/omicron-is-the-least-of-the-problems-for-global-trade-20211129-p59d6k) noting that logistics are the least of the problems facing the WTO’s MC12 when the world’s two largest economies no longer seek greater integration.

The indefinite postponement of the World Trade Organization’s (WTO) 12th Ministerial Conference in Geneva due to a new COVID variant represents yet another setback for the multilateral trading system. Logistics aside, the WTO faces fundamental questions about its future. In particular, it is far from clear whether the world’s two largest economies, the United States and China, are committed to greater global economic integration.

The delay to MC12 comes ahead of the 20th anniversary of China’s accession to the WTO on 11 December. WTO membership was an important element of China’s integration into the world economy, as well as its domestic economic reform program.

But 20 years on, China’s role in the world economy is now seen as increasingly problematic. The 8th review of China’s trade policy by the WTO in October 2021 saw 50 delegations, including Australia’s, line-up to criticise China’s state-led development model, adherence to WTO rules, as well as its use of coercive economic statecraft. 

WTO accession in 2001 only served to make permanent access China already enjoyed to US markets since the 1980s, but removed the substantial implicit trade barrier represented by uncertainty around whether the US Congress would renew China’s most favoured nation status each year. More importantly, WTO accession saw China lower its trade barriers to the rest of the world, including the United States.

The ‘China shock’ literature has highlighted the number of US manufacturing jobs lost to import competition from China in recent decades. However, a broader assessment of the economic impact of that shock shows that it has been a net positive for the US economy. Had the US resisted China’s integration into the global economy, greater import-competition would have almost certainly arisen from other developing economies. The China shock was not really specific to China, but part of a much broader globalisation shock to manufacturing that benefited the US and world economy.

Greater US economic engagement with China was never expected to lead to top-down political liberalisation on the part of the Chinese Communist Party (CCP), but it was expected to lead to bottom-up changes in Chinese society that would present long-run challenges to CCP rule. Increased political and economic repression under Xi Jinping, including recent leftist ‘rectification’ campaigns against successful Chinese firms and industries, are symptomatic of increased regime insecurity and counter-intuitively vindicate the view that China’s integration into the world economy would challenge the regime.

President Trump’s trade war and sanctions against China have also led the CCP to question the extent of economic interdependence with the United States. President Trump’s ‘American First’ policies and President Biden’s ‘foreign policy for the middle class’ are mirrored in China by Xi’s advocacy of a concept of national security that embraces economic self-sufficiency, aspires to global technological leadership, engages in economic statecraft and seeks to diversify away from economic engagement with the US.

Far from calling out and discipling China’s behaviour, President Trump’s trade policies, largely maintained by the Biden Administration, have encouraged China to double-down on its state-led development model.

Many of the complaints about China’s trade and other practices are actionable in terms of WTO rules, but these rules and dispute settlement mechanisms have been underutilised by the US and other countries.  There has been a collective failure to hold China’s feet to the fire on its WTO accession commitments, which went beyond those of other members. To the extent that there are gaps in existing WTO rules and processes, these gaps are not specific to China. While China is the bigger offender in terms of subsidies and other discriminatory trade measures, the US, EU and other G20 economies have also undermined the multilateral trading system with similar measures of their own.

Far from of being a champion of globalisation, the US has increasingly disengaged from the world economy over the last twenty years, beginning with the failure of the WTO ministerial conference in Seattle in 1999 and culminating most dramatically in its failure to join the Trans-Pacific Partnership in 2017.

The 1999 Seattle conference failed in part because its US hosts failed to book the convention centre for long enough to enable an extension of talks. The meeting had to give way to a convention of optometrists.

Meeting logistics are now the least of the WTO’s problems when the world’s two largest economies no longer have greater economic integration as a common goal.

Dr Stephen Kirchner is program director, International Economy, at the United States Studies Centre, University of Sydney.
