---
title: "US investors cool on Australia"
date: "2021-07-06"
categories: ["Foreign Investment"]
---

I have an op-ed in [The Mandarin](https://www.themandarin.com.au/162068-us-investors-cool-on-australia/) summarising my latest report on the Australia-US bilateral investment relationship. Text below the fold.

There is an even longer version in [Australian Outlook](https://www.internationalaffairs.org.au/australianoutlook/the-australia-us-bilateral-investment-relationship-in-2020-taxing-times/).

The United States has traditionally been Australia’s most important investment partner. The bilateral investment relationship was valued at just under \$1.8 trillion in 2020. However, even before the pandemic, there were emerging signs of weakness in that relationship. US investment in Australia significantly underperformed in 2020, continuing a three-year trend.

More competitive US tax settings due to former President Trump’s tax reforms have been an important factor in this underperformance. The Biden administration will again revamp the US corporate tax system, with the G20 also agreeing to re-write global tax rules. In this context, Australia will need to pay careful attention to the competitiveness of its own tax and other policy settings to maintain the interest of US and global investors.

For the OECD area, foreign direct investment (FDI) inflows fell 51% in 2020. Australia’s experience was in line with this performance, with a 48% decline in inbound FDI. However, US investment in Australia fell by even more, with an outflow of \$12 billion, the first such outflow since 2005. The US share of the stock of FDI in Australia has declined for two straight years, while the US share of total foreign investment in Australia has been declining for three years.\
Data from the US Bureau of Economic Analysis shows that since the passage of President Trump’s Tax Cuts and Jobs Act in 2017, Australia has underperformed peer economies and regions in attracting US FDI. Canada, Europe, the UK, New Zealand and the Asia-Pacific region ex-Australia all outperformed Australia in attracting US investment.

A number of factors explain the weakness in US investment in 2020 in particular. The pandemic saw significant repatriation flows, as global investors, including those in the US, sold foreign assets to raise cash. The main outflow of US investment in Australia in 2020 was holdings of Australian debt securities and unwinding derivatives hedging those positions.

Australia has also seen a dramatic change in its external finances. Increased saving and weak domestic investment have resulted in record current account surpluses. In flow terms, Australia has become a net lender rather than a borrower internationally, reducing the overall need for foreign capital inflow.\
Australian investment in the US continues to grow, in particular portfolio investment, with domestic capital markets increasingly saturated with superannuation saving. The increase in the Superannuation Guarantee from 1 July will only make this excess saving problem worse.

Australia’s increased regulation of FDI and application fees for foreign investors have also weighed. Treasurer Josh Frydenberg lowered the monetary screening thresholds to zero during 2020 to guard against the opportunistic acquisition of distressed Australian firm by foreign interests. But the foreign buying spree never eventuated. China’s overseas investment fell to a 13-year low in 2020, having now declined every year since 2016.

While unofficially targeted at China, Australia’s increased scrutiny of FDI weighs more heavily on the US due to its non-discriminatory application and because the US is traditionally the larger investor. Australia saw more FDI from China in 2019 and 2020 than from the US, even as the Chinese authorities limited outbound capital flows.

More competitive US corporate tax settings since 2017 were always expected to weigh on US investment in Australia, with Australia having one of the least competitive corporate tax rates in the OECD and one of the highest tax burdens on capital.

The Biden plan will tax US corporates more heavily, which will improve Australia’s attractiveness to foreign investors on a relative basis. However, it will also weigh on US corporate investment at home and abroad, so the implications for US investment in Australia are ambiguous.

In the context of international negotiations, the US and Australia have both promoted a minimum corporate tax designed to limit tax competition in favour of high-tax jurisdictions.

Both the US and Australia could have used these negotiations to promote a global minimum corporate cash flow tax that fully expenses investment. This more investment-friendly approach was previously considered by the OECD. As much as 40% of FDI globally flows through low-tax investment hubs.

In Australia, policymakers have recognised the need for corporate tax reform, but have mostly failed to deliver. A higher corporate tax burden in the US, together with a global minimum corporate tax, will make Australia more attractive to foreign investors on a relative basis.

However, this is likely to come at the expense of US and global investment in absolute terms. The recent underperformance of US investment in Australia highlights the sensitivity of global cross-border investment to changes in international tax rules.

As Australia recovers from the pandemic, it will return to being a net borrower in international capital markets. US investment in Australia is not completely fungible with other forms of foreign capital inflow. The recent weakness is US investment should remind Australian policymakers that they cannot take our appeal to global investors for granted.

Dr Stephen Kirchner is program director, International Economy, at the United States Studies Centre, University of Sydney. His report, Australia-US Bilateral Investment in 2020: Taxing Times, is released this week.
