---
title: "A New Era of RBA Independence or the Bureaucratisation of Monetary Policy?"
date: "2007-12-06"
categories: ["Economics", "Financial Markets", "Politics"]
---

The RBA Governor and Treasurer have announced a new Joint Statement on the Conduct of Monetary Policy, which [Treasurer Swan](http://www.treasurer.gov.au/DisplayDocs.aspx?doc=pressreleases/2007/003.htm&pageID=003&min=wms&Year=&DocType=0 "Treasurer Swan") has hailed as a ‘new era’ of central bank independence.  The Statement maintains the existing inflation target of 2-3% on average over the economic cycle.  The main change is that the positions of the Governor and Deputy Governor will have their level of statutory independence raised to be equal to that of the Commissioner of Taxation and the Australian Statistician. Their appointments will be made by the Governor-General in Council, and could be terminated only with the approval of each House of the Parliament in the same session of Parliament. 

In relation to appointments of external members to the RBA Board, the Secretary to the Treasury and the RBA Governor will maintain a register of ‘eminent’ candidates of the ‘highest integrity,’ from which the Treasurer will make new appointments to the Reserve Bank Board.

The improvements to the statutory independence of the Governor and Deputy Governor are welcome in that they serve to augment the existing provisions of the RBA Act that have always given the RBA Governor a high degree of independence from the government of the day.  Contrary to the myth propagated by former Treasurer Peter Costello, RBA independence did not begin in August 1996 with the first Joint Statement.  But these measures are unlikely to afford the Governor and Deputy Governor much additional independence in practice.  The best protection for the Governor and Deputy Governor is their own reputation, which would make any politically-motivated dismissal very damaging for the government of the day.  International capital markets could also be expected to punish any government that sought to overtly compromise the independence of the Bank.

The changes in relation to the external Board appointments are designed to remedy the situation by which these appointments have been used for political patronage, most recklessly in the case of former Treasurer Peter Costello’s appointment of Robert Gerard.  This may protect the appointments process from undue political influence, but creates a new problem in that it will effectively limit Board appointments to those who meet with approval from the official family of RBA and Treasury.  This is a backward step, which will work against promoting a diversity of viewpoints in the policymaking process. 

Under the former government, bureaucratic capture of the executive was just as big a problem as executive politicisation of the bureaucracy.  In the Treasury portfolio for example, Peter Costello was the subject of aggressive bureaucratic capture in relation to a broad-range of policy areas, from international tax harmonisation to the G20, allowing Treasury to promote its own interests.  The new appointments process for external Board members risks entrenching the influence of the RBA’s senior officers over the monetary policy decision-making process, at the expense of those who have been critical of past or current policy.  Given that the RBA is currently presiding over an inflation rate in breach of its mandate, this seems an odd time to be further entrenching bureaucratic influence over policy.

The involvement of the Treasury in this process is also at odds with international trends in central bank reform, which generally seek to increase the degree of separation between monetary policy and the fiscal authority.  The new register will serve to increase the influence of Treasury over policy.  The Treasury Secretary should be excluded from a direct role in monetary policy, with either no representation on the RBA Board, or non-voting representation only.  The Treasury should play no role in the appointments process for the RBA Board.

Ultimately, politics cannot be completely removed from the appointments process for both the Bank’s senior officers and the external Board members.  The RBA is a government creation and must at some level be answerable to the government of the day.  The best protection for the integrity of monetary policy is an extremely high level of transparency in monetary policy decision-making.  Unfortunately, the new arrangements for the release of the Board minutes will still keep secret the decisions of individual Board members in relation to monetary policy.  Coupled with the effective internalisation of the appointments process to those approved by the Treasury-RBA official family, the new arrangements may serve to entrench the de facto monopoly that the RBA’s senior officers enjoy over decision-making and minimise effective external participation in, and scrutiny over, monetary policy.
