---
title: "‘A Society Like Sweden’"
date: "2007-11-14"
categories: ["Economics", "Politics"]
---

As the government and opposition compete to see who can add the most complexity to the federal tax-spending churn, [Rupert Murdoch](http://www.theaustralian.news.com.au/story/0,25197,22748877-5013948,00.html "Rupert Murdoch") suggests an alternative approach:

> Mr Murdoch, the chairman and chief executive of News Corporation, owner of The Australian, said: “We are very lucky in Australia, there are no huge economic challenges. But taking a macro view, all political parties seem to be making an effort to become a society like Sweden, to create a dependency mentality as against an aspirational one.”
>
> Mr Murdoch, in an interview with The Australian in Melbourne ahead of a News shareholder briefing in Adelaide today, declined to answer any questions on the election campaign.
>
> He said he was not close enough to it. “I don’t want to say anything remotely close to Australian politics,” Mr Murdoch said.
>
> However, he noted that “all governments are raking in indecent amounts of tax, which they should do something with, either by investing in infrastructure or handing it all back to the people”.
>
> “Australia should certainly slash the capital gains tax,” he said. “There are people who hold shares for 20 years and won’t sell because they will lose it in tax. When the US cut its tax to 15 per cent, revenue doubled and people did something with it.”
>
> He praised the more aspirational nature of American society, “where people want to change and do something about it, accelerating change with innovation”.
