---
title: "Another Redundant International Financial Institution"
date: "2007-10-02"
categories: ["Economics", "Financial Markets"]
---

[Bill Easterly](http://online.wsj.com/article/SB119127382735945494.html?mod=opinion_main_europe_asia "Bill Easterly") on the Asian Development Bank:

> Given all the economic success stories in today’s Asia, you’d think the ADB could pat itself on the back for a job well done and then pack up and go home. But not so fast, says the ADB, which is desperately trying to find new things to do with its 2,000 employees and \$6 billion of annual lending.
>
> To that end, the ADB is working on a Long Term Strategic Framework 2020, a project best read as bureaucratic jargon for the ADB’s promise to keep producing bureaucratic jargon through the year 2020. For help with the framework, the ADB commissioned an Eminent Persons Group to tell it what to do with itself. The learned committee was chaired by Supachai Panitchpakdi, Secretary-General of the United Nations Conference on Trade and Development, a body that has long distinguished itself by promoting all the bad ideas that stifle both trade and development. The end result was a report called “Toward a New Asian Development Bank in a New Asia.” The eminences have pointed out to the ADB what should be obvious to anyone who reads this newspaper: The ADB’s original raison d’etre of providing capital is obsolete in a capital-surplus region with a large excess of saving over investment.

Australia is the fifth largest shareholder in the ADB.
