---
title: "At the Treasurer’s Convenience"
date: "2007-08-30"
categories: ["Economics", "Financial Markets"]
---

Next week’s Q2 national accounts release has been [moved to Tuesday](http://www.treasurer.gov.au/tsr/content/pressreleases/2007/083.asp "moved to Tuesday"), to avoid clashing with APEC:

> I have requested the Australian Statistician release the June quarter 2007 National Accounts one day early on Tuesday, 4 September 2007, in view of the fact that meetings surrounding the APEC Summit will be occurring on Wednesday 5 September.
>
> The acting Australian Statistician has agreed to this request and indicated that he will release the June quarter 2007 National Accounts one day earlier, on Tuesday 4 September 2007, at 11.30 am.
>
> The usual Treasurer’s press conference will occur in Canberra on that day.

This is not the first time that the national accounts release has been re-scheduled to suit the Treasurer’s schedule.  On a previous occasion, the national accounts were released earlier simply because the Treasurer wanted to go overseas.  The willingness of the ABS to accommodate ministerial requests to re-schedule data releases to suit the Treasurer’s schedule is not a good look for an independent authority.

The Treasurer has also been busy [instructing](http://www.abs.gov.au/AUSSTATS/abs@.nsf/Latestproducts/5302.0Main%20Features1Jun%202007?opendocument&tabname=Summary&prodno=5302.0&issue=Jun%202007&num=&view= "instructing") the ABS to maintain secrecy on the Future Fund’s transactions:

> *During the June quarter, the Future Fund commenced investment activity. The Future Fund has been classified as a General Government unit and thus the investment activity and associated holdings of assets are recorded as part of the General Government sector. In order to maximise the availability of information about the activities of the General Government sector, ABS legislation allows the publication of identifiable information about this sector except where a request for confidentiality has been received from the relevant Minister. A request has been received and the relevant estimates have been confidentialised in this publication. The estimates will remain confidentialised in all releases published up to and including 30 June 2008.*

The secrecy around the Future Fund’s investment activities is a tacit admission of the capacity of the Fund to distort financial market prices.
