---
title: "Ben Bernanke’s Diary"
date: "2007-03-06"
categories: ["Economics", "Financial Markets"]
---

[Dow Jones Newswires](http://online.wsj.com/article/SB117314647360127802.html?mod=home_whats_news_us "Dow Jones Newswires") have obtained Ben Bernanke’s visitor log through an FoI request:

> Topping a list that included Wall Street heavyweights like Bear Stearns Cos. and Morgan Stanley, however, was a small St. Louis-based forecasting firm: Macroeconomic Advisers….
>
> Former Fed Gov. Laurence Meyer and former Fed economist Brian Sack, both now with Macroeconomic Advisers’ Washington office, enjoyed the greatest access to Mr. Bernanke among private-sector economists, the Fed chairman’s visitor logs show.
>
> The pair met with Mr. Bernanke three times last year, in March, August and September. Mr. Sack met with Mr. Bernanke an additional time in July, the logs showed…
>
> It lists only the names of people cleared through security to meet with him specifically. He may have also met with other people who were cleared to meet with other Fed officials.
>
> Since taking the helm at the Fed in February 2006, Mr. Bernanke has sat down with several Wall Street economists, including Richard Berner of Morgan Stanley, David Malpass of Bear Stearns and several members of the American Bankers Association’s economic advisory panel.
>
> Top academics on his visitor logs include: Martin Feldstein, head of the National Bureau for Economic Research; Princeton Prof. and former Fed Vice Chairman Alan Blinder, and C. Fred Bergsten of the Peterson Institute for International Economics.
