---
title: "‘Beyond Insane’"
date: "2007-11-24"
categories: ["Economics", "Financial Markets"]
---

[Terry McCrann](http://www.theaustralian.news.com.au/story/0,25197,22812055-14743,00.html "Terry McCrann") continues to do battle with those who favour more Commonwealth revenue hoarding:

> Imagine if Costello was handing Swan a \$60 billion annual surplus—close to a quarter of a trillion dollars over the next four years. The same Swan who is absolutely dedicated to keeping “downward pressure on interest rates”.
>
> Now, of course, we cannot assume either the Mandate of Heaven or the dollars it bestows are already “in the bank” for even the next four years. Further, we still face the fundamental uncertainty of whatever comes out of the US over the next year or so.
>
> This, though, does not validate the depressingly ubiquitous demand from too many economists that such surpluses should be “banked” to allow the “automatic budget stabilisers” to work and/or to target lower or stable interest rates.
>
> The idea of running a “flexible fiscal policy” to target a stable interest rate is beyond insane. And which rate would be appropriate? An official rate of 7 per cent, 6 per cent, 5 per cent?
>
> When we have experienced a structural (upward) shift in budget revenues, the money has to be spent. The only question is whether in tax cuts or in service delivery or infrastructure…
>
> The increases in official rates over the past few years have only succeeded in getting rates back to a sensible level, commensurate with an economy growing at 7 per cent-plus in nominal terms.
