---
title: "Blame Martin Place III"
date: "2007-11-07"
categories: ["Economics", "Financial Markets", "Politics"]
---

The [statement](http://www.rba.gov.au/MediaReleases/2007/mr_07_20.html "statement") accompanying today’s increase in official interest rates on the part of Reserve Bank confirms what was already effectively implied by the Q3 CPI outcome:

> *By the March quarter of next year, both headline and underlying measures of inflation are likely to be above 3 per cent.*

This forecast presumably includes the anticipated impact of today’s tightening.  The RBA will be unable to publish a target-consistent inflation forecast in its November Statement on Monetary Policy. The RBA is effectively admitting to a monetary policy mistake.  It is Governor Stevens rather than John Howard who should be in the dock. 

The question that has to be asked now is, what path will official interest rates have to follow to bring the inflation forecast back into the 2-3% target range?  On this, the RBA was characteristically silent.  There is really no excuse for the RBA failing to spell this out in today’s statement or next week’s quarterly Statement on Monetary Policy.  The RBA continues to short-change the public with its lack of transparency in relation to its future policy intentions.  The Bank is only making its job harder, by robbing itself of the ability to let market-determined interest rates do some of the required tightening work.  Interbank futures are still giving less than a 40% chance to a follow-up tightening in December.
