---
title: "Blame Martin Place"
date: "2007-10-24"
categories: ["Economics", "Financial Markets", "Politics"]
---

Today’s Q3 [CPI](http://www.abs.gov.au/AUSSTATS/abs@.nsf/Latestproducts/6401.0Main%20Features1Sep%202007?opendocument&tabname=Summary&prodno=6401.0&issue=Sep%202007&num=&view= "CPI") outcome cements the case for further RBA tightening at the November Board meeting.  The government will inevitably cop a lot of flack as a result of the mid-election campaign tightening.  For this, the government largely has itself to blame.  Having taken credit for the cyclical downswing in interest rates in 2001, it can hardly avoid taking responsibility for the other side of the cycle.  The irony is that the government’s campaign on interest rates in 2004 set it up to be a victim rather than a beneficiary of future prosperity.

This is unfortunate, since it distracts attention from the fact that it is the RBA that is ultimately responsible for interest rates and inflation outcomes.  As then Deputy Governor Ian Macfarlane once said, ‘blame Martin Place.’  It is now clear that the RBA has fallen behind the curve in its task of inflation control.  The RBA was already forecasting an increase in inflation for 2008 in its August Statement on Monetary Policy, even with the benefit of the August tightening.  The baseline for the underlying inflation forecast in the November Statement will be 3.0%, based on the average of the statistical core series published today.  Even with the benefit of a November tightening, it will now be difficult for the RBA to publish a target-consistent inflation forecast in the November Statement.  The RBA really needs to raise rates by 50 bp in November, although will probably stick with 25 bp, with a follow-up 25 bp in December.

The smartest thing a new Labor Government could do would be to demand that Governor Stevens start giving press conferences after each monthly Board meeting.  This would significantly change the media dynamics surrounding interest rate changes and make clear to the public who is really responsible for inflation control and changes in interest rates.
