---
title: "Bretton Woods Revivalism in the WSJ"
date: "2007-09-27"
categories: ["Economics", "Financial Markets"]
---

More tiresome hard money ratbaggery in the WSJ, this time from Bretton Woods revivalist, [Judy Shelton](http://online.wsj.com/article/SB119085584337640853.html?mod=opinion_main_commentaries "Judy Shelton"):

> The massive currency swings that reign between the dollar, the euro, Japanese yen, British pound, Canadian dollar, Swedish krona and Swiss franc wreak havoc on demand-and-supply outcomes for goods traded across borders. The New York Board of Trade’s U.S. Dollar Index, which tracks the dollar’s value relative to a basket of those six other currencies, has tumbled 34% since its July 2001 peak. Why pontificate about the importance of eliminating tariffs to promote open markets when the impact of a gyrating dollar is far more devastating, far more protectionist in its effect on global free trade?
>
> It is time for the U.S. to acknowledge what we have tried to wave off under the pretense of allowing free markets to decree the value of our currency.
>
> If we truly believe in a global marketplace where outcomes are determined by competition and competence, not localized monetary policies, we need a global monetary unit of measure. We need a meaningful global currency.

Bretton Woods broke down precisely because fixed exchange rates wrecked havoc by transmitting economic shocks, including monetary and fiscal policy mistakes, around the world.
