---
title: "Bubble Denialism"
date: "2007-09-17"
categories: ["Economics", "Financial Markets"]
---

Some refreshing bubble skepticism from [Peter Gordon](http://www-rcf.usc.edu/~pgordon/blog/2007/09/bubbles.html "Peter Gordon"):

> I still do not know what asset price “bubbles” are. If I did, then I would also know what the “correct” prices are.
>
> There is plenty of talk about prices that cannot be justified by “fundamentals” but most of that is in hindsight. The latest of many such discussions from The Economist clarifies nothing.
>
> The current credit problems are prompted by house price declines that, in turn, further crimp liquidity. But this is not the implosion of the “house price bubble” that was the talk for so long.
>
> This evening’s 60-Minutes interview with Alan Greenspan shows him saying that he had no idea that there would be a sub-prime credit contraction—or that there would be a serious problem.
>
> Good for his candor and good for his helping to unravel the current problem from all of the media herd housing bubble chorus.
