---
title: "Can Greenspan Write?"
date: "2007-10-16"
categories: ["Economics", "Financial Markets"]
---

[Michael Kinsley](http://www.nytimes.com/2007/10/14/books/review/Kinsley-t.html?_r=1&books&pagewanted=all&oref=slogin "Michael Kinsley") reviews Alan Greenspan’s [The Age of Turbulence](http://www.amazon.com/gp/product/1594201315/103-8893387-0259015?ie=UTF8&tag=institutional-20&linkCode=xm2&camp=1789&creativeASIN=1594201315 "The Age of Turbulence") and pronounces:

> *So the suspense is over: Alan Greenspan is able to express himself in clear English prose.*

That is just the first of many things wrong with Kinsley’s ridiculously partisan review of Greenspan’s memoirs.

I’m about half-way through Greenspan’s book and my first reaction was that Greenspan did not write it.  Greenspan himself acknowledges the assistance of a collaborator in the writing and it is clear that whatever Greenspan contributed has been heavily re-written.  Greenspan’s distinctive voice is evident in his many speeches as Fed Chairman, but it is not to be found in this book.  With the publisher having paid a USD 8.5 million advance, it is hardly surprising they would want the book professionally written. 

As for the substance of the book, more later…
