---
title: "Capital Xenophobia"
date: "2007-07-23"
categories: ["Economics", "Financial Markets"]
---

[Stephen Mayne](http://www.theage.com.au/news/opinion/eaten-by-singapore/2007/07/21/1184560106866.html?page=fullpage#contentSwap2 "Stephen Mayne") attempts to whip-up capital xenophobia against Singapore’s ‘financial imperialism:’

> Planes, child-care centres, shopping centres, department stores, satellites, hotels, power lines, gas pipelines and mobile phones: the Singapore Government owns all that and more in Australia yet this is barely mentioned in public debate.
>
> Does anybody else out there feel a little uneasy about this phenomenon, especially given the secretive, autocratic and undemocratic tendencies of the Singapore Government?

Mayne can’t bring himself to fully explain why we should feel uneasy, probably because he realises how close he is to sounding like Pauline Hanson.

In fact, we should be grateful that Singapore saves so much that it needs to export direct investment capital on a large scale (as indeed, does Australia, albeit on the part of mostly private rather than government-linked businesses).  Australia is the beneficiary of this cheap foreign capital, which allows us to sustain higher rates of consumption and investment than would otherwise be possible. 

Since foreign-owned businesses operating in Australia are subject to Australian law, their activities can hardly be considered objectionable.  Indeed, investing in Australia makes the activities of Singapore’s government-linked corporations more transparent, something a shareholder activist like Mayne would surely welcome.

As Mayne suggests, if you don’t like these foreign ownership arrangements, there is also no obligation to transact with these businesses:

> *I, for one, switched my mobile phone contract from Optus to Telstra as a small consumer protest when Australian drug trafficker Van Nguyen was executed by the immovable Singapore authorities in 2005.*

Most of us have a somewhat better sense of perspective.
