---
title: "‘Carbon Neutral Grannies’: Global Warming Self-Parody Alert"
date: "2007-02-17"
categories: ["Culture & Society"]
---

If it were the first of April, I would assume that this was a cruel parody of global warming hysteria.  Unfortunately, it is just self-parody, with front page billing in [The Weekend Australian](http://www.theaustralian.news.com.au/story/0,20867,21239884-601,00.html "The Weekend Australian"):

> All forms of flatulence - from cats, dogs, even from Dad - contain methane, a greenhouse gas thought to contribute to climate change.
>
> If you’ve been feeling guilty about it, help is at hand. For just \$8, a Sydney-based company, Easy Being Green, can now make your cat carbon-neutral, so it can “live guilt-free for a year”…
>
> The scheme can be applied to any product, animal or person. For \$20, the company made Jenny Cracknell into a “carbon-neutral granny” last year. Her daughter, Emily, gave her a gift certificate to offset two years’ worth of flatulence. “I don’t like to brag, but I actually don’t have much flatulence,” Mrs Cracknell says. “But when I do, I feel OK about it, because the damage to the planet has been offset.”
