---
title: "Carbon Offsets"
date: "2007-07-09"
categories: ["Economics", "Financial Markets"]
---

Live Earth helps [Chris Dillow](http://stumblingandmumbling.typepad.com/stumbling_and_mumbling/2007/07/the-point-of-li.html "Chris Dillow") reduce his carbon footprint:

> *The moment it came on, I turned the TV off.*

At the same time, Live Earth Sydney was held against the backdrop of a [terrifying drought](http://www.smh.com.au/news/music/fifty-bucks-for-a-beer-it-was-livid-earth-in-sydney/2007/07/08/1183833341702.html "terrifying drought"):

> Faced with record beer queues, thirsty fans at Saturday’s Live Earth concert at Sydney’s Aussie Stadium were seen by the Herald offering others \$50 for their beer rather than wait an hour to buy refreshments.
>
> Thousands, deprived of the traditional rock ‘n’ roll accompaniment, went to a Coca-Cola stand, forgetting that its manufacturers had been under fire in India for allegedly creating water shortages and pollution around their bottling facilities.
>
> Scores were seen leaving within the first two hours of the nine-hour festival, fed up with the lack of basic services, cutting their losses on a \$99 ticket. Gate attendants were heard telling the human tide that they should complain to the promoter.
>
> It was “unAustralian”, one spectator protested. “This is what happens when you let hippies organise a big event,” another said. One woman, asked by Missy Higgins “how you all are back there”, earned a wry round of applause from the stands when she shouted: “Sober.”

Be sure to put your TV back on for [this](http://www.abc.net.au/tv/swindle/default.htm "this").\
**\
UPDATE:** More global warming ‘denialism’ from [Scott Armstrong and Kesten Green](http://www.forecastingprinciples.com/Public_Policy/WarmAudit31.pdf "Scott Armstrong and Kesten Green"):

> *We asked scientists and others involved in forecasting climate change to tell us which scientific articles presented the most credible forecasts. Most of the responses we received (30 out of 51) listed the IPCC Report as the best source. Given that the Report was commissioned at an enormous cost in order to provide policy recommendations to governments, the response should be reassuring. It is not. The forecasts in the Report were not the outcome of scientific procedures. In effect, they present the opinions of scientists transformed by mathematics and obscured by complex writing… We have been unable to identify any scientific forecasts to support global warming. Claims that the Earth will get warmer have no more credence than saying that it will get colder.*
