---
title: "China’s Credit Crunch II"
date: "2007-12-21"
categories: ["Economics", "Financial Markets"]
---

China continues to rely on [quantitative lending controls](http://www.reuters.com/article/rbssFinancialServicesAndRealEstateNews/idUSPEK20072020071221 "quantitative lending controls") to address the inflationary implications of its peg to the USD:

> China will limit next year’s commercial bank loan growth to 15 percent and has urged banks to adhere to quarterly lending targets or risk punishment, the official Shanghai Securities News reported on Friday.
>
> The government also urged lenders to spread new loans more evenly through 2008 and indicated they should lend out 35 percent of the full-year quota in the first quarter, 30 percent in the second, 25 percent in the third and 10 percent in the fourth, the newspaper said, citing unnamed banking sources.
>
> Those that lend more excessively than told may face administrative penalties, be issued with central bank bills at below-market interest rates or be ordered to set aside more deposits at the central bank as reserves, the newspaper said.

Meanwhile, Morgan Stanley gets a [capital infusion](http://www.ft.com/cms/s/0/ae7c754c-af2b-11dc-880f-0000779fd2ac.html?nclick_check=1 "capital infusion") from Chi-com sovereign wealth fund, China Investment Corp.  As [Macro Man](http://macro-man.blogspot.com/2007/12/top-ten-things-yet-to-be-purchased-by.html "Macro Man") notes, all those years of sucking-up by Morgan’s resident Sinophile, Stephen Roach, have finally paid-off.
