---
title: "Collective Responsibility and RBA Board Secrecy"
date: "2007-12-12"
categories: ["Economics", "Financial Markets"]
---

RBA Governor Stevens has elaborated on the rationale for the RBA’s new transparency regime in a [speech](http://www.rba.gov.au/Speeches/2007/sp_gov_111207.html "speech") to the Sydney Institute.  Stevens was careful to disassociate the new measures from the change in government, saying that the RBA had ‘reflected on this for some time this year,’ and that he ‘was very pleased to learn when I met the new Treasurer a couple of weeks ago that he supported the changes.’  It is likely that the new measures have as much to do with the change at the top of the RBA last year as the change in government this year, although their announcement at the first Board meeting after the federal election is surely not entirely coincidental.

Much of the speech is given over to the ‘limits of transparency,’ with Stevens arguing that:

> The nature of the Reserve Bank Board – a majority of whom are part-time members, drawn from various parts of the Australian community, but seeking to make decisions in the national interest as opposed to any industry, geographical or sectional interest – needs to be considered when thinking about disclosure practices…
>
> Readers will also observe that the pattern of votes of individuals is not recorded \[in the new minutes\], only the outcome. That is a point of difference with other central banks which publish minutes. But in those cases the decision-makers are full-time appointees, in some cases in systems with expressly individual, as opposed to collective, responsibility for their decisions. That is not the system Australia operates, and our pattern of disclosure reflects the institutional arrangements.

Stevens’ argument about collective responsibility is an embellishment of the RBA’s traditional argument for Board secrecy, which is that the backgrounds of the external Board members would subject them to undue external pressure if their behaviour on the Board in relation to monetary policy became known.  Stevens is smart enough not to make explicit what is really being argued here: that some of the external Board members are too conflicted to discharge their responsibilities in relation to monetary policy in a transparent fashion.  In any other setting, this argument would be considered absurd.  Indeed, the potential for such conflicts argues if anything for more transparency, not less.  More fundamentally, it is an argument for the removal of responsibility for monetary policy from the RBA Board.

Stevens says that the Bank of England ‘MPC’s culture is expressly, by the intention of its creators, one of individual accountability.’  The implication is that the RBA has a different institutional make-up and culture, so that ‘it would not make sense to “cherry pick” the high transparency aspects of every other system and assume that they should simply be grafted onto the Australian system.’  But this is exactly why more fundamental statutory reform of monetary policy governance is required.  The RBA Board and its statutory responsibilities date back to 1960, and are little changed on the central banking arrangements of the 1930s.  The RBA’s governance structures as they are currently constituted are simply incompatible with a fully transparent monetary policy regime. 

Stevens also cites the fact that the ECB does not publish minutes: ‘it is argued, not unreasonably, that publication of minutes and voting might prejudice the capacity of the national governors to take a euro area, rather than national, perspective.’  This is just one of many arguments against European Monetary Union rather than a valid defence of a lack of transparency in the conduct of monetary policy.

We argued in the previous post that the new statutory protections for the RBA Governor and Deputy Governor and the new appointments process for external Board members runs the risk of entrenching bureaucratic influence over monetary policy at the expense of the increased external participation and scrutiny that could be expected from a Bank of England MPC-type arrangement.  Indeed, the new arrangements substantially diminish accountability for monetary policy, in that there is no mechanism for the removal of the Governor or Deputy Governor for non-performance, which remains poorly benchmarked in any event.  Overlaying this with a doctrine of collective responsibility for monetary policy decision-making means that the new arrangements may actually serve to detract from transparency and accountability in the conduct of monetary policy.  The RBA has put in place many of the trappings of transparency, but without the substance that would ensure genuine accountability for decision-making.
