---
title: "Costello Stole First"
date: "2007-03-29"
categories: ["Economics", "Financial Markets"]
---

Treasurer Peter Costello has a particularly silly op-ed in [The Australian](http://www.theaustralian.news.com.au/story/0,20867,21464410-7583,00.html "The Australian"), accusing opposition leader Kevin Rudd of being a ‘burglar’ and ‘raiding the savings of future generations’ with his proposal to dip into the Future Fund to pay for the Labor Party’s broadband initiatives.  This conveniently ignores the fact that Peter Costello is a step ahead of Rudd, having already raided the savings of current generations to endow his Future Fund.  It make no difference whether Rudd funds his broadband initiatives from the Future Fund or some other source, just as it makes no difference whether public service superannuation liabilities are funded out of current or future revenue.  A dollar is a dollar.

There is plenty to criticise in Rudd’s broadband proposals.  The issue is whether the money should be spent on broadband at all, not whether it comes from the artificial lock-box the government has created to quarantine its budget surpluses.

My critique of the Future Fund can be found [here](http://www.cis.org.au/policy/spring_06/PDF%27s/spring_06_kirchner.pdf "here").
