---
title: "Cullen Rejects the Consensus – Or Does the Consensus Reject Him?"
date: "2007-08-18"
categories: ["Economics", "Financial Markets"]
---

In recent years, we have documented the steady erosion of the RBNZ’s once pioneering approach to monetary policy governance under Treasurer Cullen and Governor Bollard.  In a [speech](http://www.beehive.govt.nz/ViewDocument.aspx?DocumentID=30340 "speech") to Ernst & Young, Cullen expresses his misgivings about the fundamental basis for a monetary policy focused on long-run price stability:

> The accepted consensus has been that our monetary policy framework doesn’t have an impact on long run growth. In other words, monetary policy helps keep the economy stable by moderating economic cycles, without impacting on the sustainable rate of growth of the economy.
>
> My overriding concern is that this view no longer holds…
>
> So I think we need to look seriously at the monetary policy framework and whether it can be made more effective at curing the inflation disease without killing the patient in the process.
>
> We should not be afraid of exploring new ideas and openly debating them.

Unfortunately, this process is more likely to dredge-up some very old and bad ideas, rather than new ones.
