---
title: "Data in the Eye of the Beholder"
date: "2007-06-02"
---

[James Hamilton](http://www.econbrowser.com/archives/2007/06/dont_worry_be_h.html "James Hamilton") notes that everyone is playing the ‘I told you so game,’ but the one person whose view really matters stands out as being right:

> It is curious that both bulls like Dave Altig and bears like Barry Ritholtz and Nouriel Roubini are pointing to the recent data to say “I told you so.” Here’s Nouriel’s take:
>
> “a hard landing can take two forms: a growth recession (i.e. a period when growth is well below potential and ranging in the 0% to 1% range) or an outright recession (i.e. negative growth). Thus, in Q1 of this year the US entered in a growth recession, and a pretty serious one indeed.”
>
> I find that perspective interesting, since slow growth for the start of 2007 is exactly what people like Dave and I had been expecting all along, and indeed is precisely what the Fed has been aiming for. Bernanke’s program from day one, in my opinion, has been to slow growth down sufficiently so as to contain inflation, but not go so far as to produce a recession. The latter phenomenon has a very clear and unambiguous data signature, including such features as a spike in the unemployment rate and significant declines in real GDP.
>
> That may yet come, but let’s be clear—you can’t declare it to have started yet on the basis of the data currently in hand. If anybody wants to crow “I told you so,” in my opinion the one person who could legitimately claim that right would be Ben Bernanke.

The Hamilton emoticon indicator has yet to turn, but my associates at Action Economics remain upbeat.  You can hear Action Economics Chief Economist Mike Englund talk about the US outlook in this Bloomberg [podcast](http://media.bloomberg.com/bb/avfile/BBRECON/vCBYm9yP2kp0.mp3 "podcast").
