---
title: "David Murray as Sen Groupie"
date: "2007-07-25"
categories: ["Economics", "Financial Markets"]
---

In an interview with the [WSJ](http://online.wsj.com/article/SB118514080177174310.html?mod=googlenews_wsj "WSJ"), Future Fund Chairman David Murray shows a somewhat reassuring preference for serious economics over business school schlock:

> WSJ: Do you have a favorite business book?
>
> Mr. Murray: No. The book that really made an impression on me was a book by \[Indian economist and Harvard University professor\] Armartya Kumar Sen called “[Development As Freedom](http://www.amazon.com/gp/product/0385720270/102-8086920-1375329?ie=UTF8&tag=institutional-20&linkCode=xm2&camp=1789&creativeASIN=0385720270 "Development As Freedom").” It explains the linkage between the system of government and democracy on one hand and business on another, and they are interrelated; they can’t be as easily separated as people make out.  Business has no chance of thriving reliably for its owners under a rule of law that doesn’t embody democracy, freedom and property rights.

Here’s [another book](http://www.amazon.com/gp/product/0470102101/102-8086920-1375329?ie=UTF8&tag=institutional-20&linkCode=xm2&camp=1789&creativeASIN=0470102101 "another book") we hope Murray has read.
