---
title: "Depression Era Exchange Rate Regimes"
date: "2007-06-25"
categories: ["Economics"]
---

[Amity Shlaes](http://online.wsj.com/article/SB118272808412346544.html?mod=opinion_main_commentaries "Amity Shlaes"), on exchange rate policy under Roosevelt:

> *At some points Roosevelt seemed to understand the need to counter deflation. But his method for doing so generated a whole new set of uncertainties. Roosevelt personally experimented with the currency—one day, in bed, he raised the gold price by 21 cents. When Henry Morgenthau, who would shortly become Treasury Secretary, asked him why, Roosevelt said that “it’s a lucky number, because it’s three times seven.” Morgenthau wrote later: “If anybody ever knew how we set the gold price through a combination of lucky numbers, etc., I think they would be frightened.”*

You can hear Amity talk about her new book, [The Forgotten Man: A New History of the Great Depression](http://www.amazon.com/gp/product/0066211700/002-4101138-7600814?ie=UTF8&tag=institutional-20&linkCode=xm2&camp=1789&creativeASIN=0066211700 "The Forgotten Man: A New History of the Great Depression"), in this [podcast](http://media.bloomberg.com/bb/avfile/BBRECON/vSp_jH69vXII.mp3 "podcast").
