---
title: "Doomsday in Davos"
date: "2007-01-23"
categories: ["Economics", "Financial Markets"]
---

[Brian Wesbury](http://www.ftportfolios.com/retail/research/viewresearcharticle.aspx?Id=244 "Brian Wesbury") reviews the sorry record of the great and the good assembled in Davos:

> In January 2006, the global glitterati of business, politics and economics gathered in Davos, Switzerland at the World Economic Forum.  A number of participants including Martin Wolf of the Financial Times, Stephen Roach and Lawrence Summers argued that the global economy was unbalanced, and they warned of a potential “adjustment.”
>
> This “adjustment,” many felt, could have serious negative consequences for the global economy.  But, even though global economic activity slowed in the second-half of 2006, led by a sharp slowdown in the US housing market, global real GDP growth was 3.9% - an acceleration from 2005 and the third year in a row of robust global growth.
>
> Ironically, this excellent worldwide economic performance, and a continued surge in global liquidity is fueling another round of pessimism this year.  With just a few days remaining before the 2007 World Economic Forum in Davos kicks off, there are already news stories that some of these same themes will be discussed again.
>
> As reported by Bloomberg News, Lawrence Summers and ECB Bank President Jean-Claude Trichet will tell the world that it has “become too complacent about risks ranging from trade imbalances to terrorism.”  Dr. Summers will warn that markets were very upbeat in mid-1914 before the world turned very ugly.  He says that, “complacency can be a self-denying prophecy” - whatever that means.
>
> According to some Nervous Nellie’s, a recent 25% drop in Venezuela’s stock market is a stress fracture in the global financial architecture and indicative of potential problems.  But, this is not a very good example.  Venezuela’s president Hugo Chavez has just pledged to nationalize many industries, which will cause a huge drop in investment.  Economic catastrophes do not happen out of the blue, just because people are complacent, they happen because governments make mistakes.
>
> Freedom and good public policy are the keys to long-term economic growth and market performance, not trade balances, the price of oil or how optimistic private-equity firms become.  A sharp movement away from freedom, or a significant mistake in monetary policy are what markets should really worry about.  Right now, these mistakes do not appear likely.  As a result, the ice cold water at Davos is unlikely to spill over the globe.

Needless to say, Nouriel Roubini will be there again this year, having [failed to take the advice](../2006/schmoozing_in_davos.qmd "failed to take the advice") of Italy’s economy minister last year.  Note that Nouriel is now [quietly backing away](http://www.rgemonitor.com/blog/roubini/174065 "quietly backing away") from his recession forecast:

> *The US is also fragile as it is not clear whether the bust of the housing bubble in the US will lead to a soft landing as the consensus view goes or a hard landing that could take the form of a growth recession or, less likely now, an outright recession.*

Since when does a ‘growth recession’ qualify as a hard-landing?  This sounds like a desperate fudge.  Nouriel, we know what you did last summer!

Incidentally, when in Davos, be sure to check out the excellent [Kirchner Museum](http://www.kirchnermuseum.ch/ "Kirchner Museum").
