---
title: "Election Timing and Interest Rates"
date: "2007-08-14"
---

[Terry McCrann](http://www.news.com.au/heraldsun/story/0,21985,22240119-664,00.html "Terry McCrann") suggests the government might choose an election date to pre-empt not just the November RBA Board meeting, but the Q3 CPI outcome at the end of October as well:

> The CPI is released on Wednesday, October 24. It would be a ‘courageous’ prime minister who risked a high CPI number and a tsunami of media and market comment on the certainty of another rate rise.
>
> Depending on where we were in the actual election cycle and how Stevens and the RBA board played their hand—we would literally be in virgin monetary policy territory—two alternatives would be possible.
>
> We actually got a rate rise on the day after the Melbourne Cup, as we did last year. Ironically, the first with Stevens as governor. Or a decision was taken to hike but with implementation postponed.
>
> It is difficult to know which, with associated commentary and market speculation, would be worse for the government. Again presumably, so close to a—still, coming—election.
