---
title: "Financial Markets Judge Peter Costello"
date: "2007-11-26"
categories: ["Economics", "Financial Markets"]
---

For all the former government’s claims to superior economic management, financial markets have greeted the change in government with indifference.  The Australian dollar is firmer against the USD this morning, as well as against those currencies with which it is traditionally correlated such as NZD and EUR.  This may partly reflect relief at a decisive election outcome compared to the possibility of a hung parliament or minority government, but firmer commodity prices would also be playing a role.  The NZD had to contend with a wider than expected October trade deficit this morning

December 10-year bond futures are around 6 bp weaker in price, but this largely reflects a similar weakening in US Treasuries Friday.

The S&P/ASX 200 is up 1.4% in early trade, but this reflects similar gains in US stocks Friday and the improvement in commodity prices. 

Financial markets are effectively saying that there is no difference between the Coalition and Labor in terms of Australia’s economic prospects.  This is as much a condemnation of the Coalition as an endorsement of Labor.  Outgoing Treasurer Peter Costello would do well to reflect on the financial market reaction to the dismissal of New Zealand’s reformist Finance Minister, Sir Roger Douglas, in December 1988, when the NZD fell off a cliff.  That is the measure of an effective Treasurer.

Financial markets will be looking to the content of the new Joint Statement on the Conduct of Monetary Policy between the new Treasurer and RBA Governor Stevens.  It is likely the new agreement will be little changed, although there is always the possibility the ALP will surprise us with a more comprehensive attempt at reforming Australia’s monetary policy governance, to bring it into line with world’s best practice after a decade of neglect under Peter Costello.
