---
title: "Glenn Stevens’ Declaration of Independence"
date: "2007-08-17"
categories: ["Economics", "Financial Markets"]
---

RBA Governor Glenn Stevens, in his [testimony](http://www.aph.gov.au/hansard/reps/commttee/R10393.pdf "testimony") before the House Economics committee on Friday, gave the clearest indication yet that the upcoming federal election need not to stand in the way of further monetary policy tightening.  Stevens told the committee that:

> *If it’s clear that something needs to be done, I don’t know what explanation we can offer to the Australian public for not doing it.  I don’t think there’s any case for the Reserve Bank board to cease doing its work in the month the election is going to be.  I doubt that members of the public would see that as appropriate.*

Last week, we suggested that the RBA might still be reluctant to raise rates in the period between the formal calling of an election and the election date.  Taken literally, Stevens’ comments imply no such reluctance.  Indeed, as we noted last week, to delay taking policy action in this context would be an act every bit as political as a decision to change policy.  The right approach for an independent central bank would be to do as Stevens suggests.

Further policy tightening will likely be required by November to maintain a target-consistent medium-term inflation forecast.  There is thus a strong chance that the RBA will be contemplating further tightening in the context of the federal election campaign.  A mid-campaign tightening would be a welcome display of institutional independence on the part of the Reserve Bank.
