---
title: "Gold Buggery"
date: "2007-07-05"
categories: ["Economics", "Financial Markets"]
---

The WSJ is peddling more gold buggery on its op-ed pages, this time from [David Ranson and Penny Russell](http://online.wsj.com/article/SB118360038319657757.html?mod=opinion_main_commentaries "David Ranson and Penny Russell"):

> Depreciation of currencies relative to gold has become unpredictable, chronic and planet-wide…
>
> currencies depreciating against gold across the board is a sign of world-wide inflation—and it has begun to set off alarm bells in many major economic capitals. But in Washington, our own central bankers remain placidly confident that everything will turn out all right.
>
> The unfortunate result is that the current crisis of confidence in paper money goes largely undiagnosed by the bulk of economists and policy makers.

One could equally say ‘appreciation of \[insert name of commodity here\] has become unpredictable, chronic and planet-wide.’  In other words, commodity prices have been going up.  The ‘depreciation’ in the USD against gold is matched by a similar depreciation against base metals, as well as a broad range of other commodities.  Commodities are becoming more expensive in terms of a broad-range of currencies because of supply-demand imbalances in the global markets where commodity prices are determined.  The appreciation in commodity prices in terms of a broad-range of currencies tells us this is a real, not a monetary phenomenon.  Far from signaling a ‘crisis of confidence,’ it points to the current strength of the global economy.
