---
title: "Gordon Brown Wants You for the BoE MPC"
date: "2007-06-18"
categories: ["Economics", "Financial Markets"]
---

Outgoing Chancellor of the Exchequer Gordon Brown [wants to advertise for new members](http://www.ft.com/cms/s/67df882e-1adc-11dc-8bf0-000b5df10621.html "wants to advertise for new members") for the Bank of England’s Monetary Policy Committee:

> Gordon Brown yesterday bowed to pressure to reduce the secrecy surrounding appointments to the Bank of England’s rate-setting body by pledging to advertise the positions.
>
> Making his final appearance before the Treasury select committee as chancellor, the prime minister-elect said he would invite “expressions of interest’’ from economists and other experts for the four outside appointments to the nine-member monetary policy committee.
>
> The advertisements would be more specific about the criteria and skills the Treasury was looking for than under current rules, he said, amid fears that under-qualified people might be appointed.
>
> Last year, four former MPC members raised concerns that Mr Brown might have received advice to appoint a non-economist to replace Stephen Nickell, an economics professor who now heads Nuffield College, Oxford.
>
> The House of Lords’ economic affairs committee last year described the appointments process as one which was “shrouded in mystery and may not always recommend the most suitable candidates”.
>
> Mr Brown also pledged to lay out a timetable for appointments. Mervyn King, Bank governor, has criticised the Treasury for a “very informal” approach resulting in appointments being made “very much at the last minute” instead of in a “timely” fashion.

In Australia, we know all about [timely appointments](../2006/the_deputy_less_reserve_bank.qmd "timely appointments") of [qualified persons](../2005/the_gerard_affair_and_rba_governance.qmd "qualified persons") to the Board of the Reserve Bank.
