---
title: "Governor Bollard’s Prop Trading Operation"
date: "2007-07-13"
categories: ["Economics", "Financial Markets"]
---

This week, the RBNZ joined the RBA in effectively entering the foreign exchange proprietary trading business.  The RBNZ [announced](http://www.rbnz.govt.nz/news/2007/3065318.html "announced") that it would abandon its practice of matching its foreign currency assets with foreign currency liabilities.  The RBNZ is now looking to increase its foreign exchange reserves on an unhedged basis.  The official rationale for the move is to give the RBNZ access to internally funded foreign exchange reserves in the event of a ‘crisis’ in which the NZ dollar falls sharply.

For a small open economy with an open capital account and a floating exchange rate, such a ‘crisis’ seems an extremely remote possibility.  Regular readers will recall that we ridiculed [Nouriel Roubini](../2006/a_roubini_forecast_that_is_dead_on_arrival.qmd "Nouriel Roubini") last year for predicting that Australia and NZ were about to suffer an exchange rate crisis.  The Australian and NZ dollars have since marched to new multi-decade highs in another one of Nouriel’s many spectacular forecasting failures.  As recently as 2001, the New Zealand economy weathered a depreciation in the NZD-USD exchange rate to 0.3900 without recourse to intervention and with no adverse macroeconomic consequences.  Indeed, the circumstances that might give rise to a negative exchange rate shock are likely to be those in which a sharp depreciation in the exchange rate would be an entirely appropriate and stabilising response.  Sharp exchange rate depreciations can be invaluable in insulating the domestic economy from negative external shocks, just as the current appreciation in the NZ dollar is partly insulating the NZ economy from the positive external shock associated with a rising terms of trade.  Countries that experience exchange rate ‘crises’ typically do so because of their commitment to managed exchange rate regimes.  The problem simply doesn’t arise with floating exchange rates.

The RBNZ argues that by not having to borrow in international capital markets to fund future intervention to support the NZD, it is avoiding the risk of capital losses on these borrowings.  This is a tacit admission of the likely ineffectiveness of foreign exchange market intervention, since an effective intervention operation to support NZD should yield capital gains, not losses.  Since a central bank’s balance sheet is denominated in its own, ultimately irredeemable, monetary liabilities, it is not clear why the RBNZ should be at all concerned with capital losses in this context.

Like other central banks, the RBNZ will be able to take a long view on the management of its foreign exchange reserves, buying the NZD low and selling high, which should earn the RBNZ a tidy profit over the long-run, although maintaining an unhedged foreign exchange exposure will be more expensive than the former approach to reserves management, given the high yield on NZD denominated assets.  In that sense, the new approach to foreign exchange reserves management is harmless enough.  But it does highlight the fact that the RBNZ under Governor Bollard has little faith or no faith in the stabilising properties of open capital markets and floating exchange rates.  In some respects, this is just the flip side of Bollard’s misguided preoccupation with the domestic-saving investment imbalance in his rationalisation of monetary policy.  The real danger is not anything the RBNZ might do in relation to intervention or the management of its foreign exchange reserves, but that Governor Bollard, like Nouriel Roubini, simply doesn’t understand open economy macro.
