---
title: "Greenspan: A Lifelong Libertarian Republican"
date: "2007-12-16"
categories: ["Economics", "Financial Markets"]
---

[Alan Greenspan’s memoir](http://www.amazon.com/gp/product/1594201315?ie=UTF8&tag=institutional-20&linkCode=xm2&camp=1789&creativeASIN=1594201315 "Alan Greenspan’s memoir") was released the day before his successor as Federal Reserve Chairman presided over a reduction in US interest rates of 0.50 percentage points, the first easing in US monetary policy since 2003.  Many have argued that the current economic problems in the US are attributable to Greenspan’s legacy as Fed Chairman.  Greenspan defends the policy actions of the Federal Open Market Committee (FOMC) during his tenure, but does not fully engage with his critics.  This is unfortunate, because Greenspan’s book could have served as a much needed corrective to those who argue that monetary policy is the principal driver of the business cycle and asset price dynamics.  This view has almost no empirical support, but has popular appeal as a simple, mono-causal explanation for economic developments that are not otherwise well understood.  Under Greenspan and his predecessor, Paul Volcker, US monetary policy focused more successfully on anchoring the long-run price level of the US economy than had been the case in earlier decades.  Greenspan and the other members of the FOMC did not and could not aim to eliminate the business cycle or asset price inflations and deflations, which are a normal part of the functioning of the economy and financial markets.  Those who argue otherwise are effectively calling for a kind of central planning via monetary policy that is likely to be far more destabilising than the current focus on long-run inflation control.

The early autobiographical material at the beginning of the book contains little that has not been covered in previous biographies, in particular, Justin Martin’s [Greenspan](http://www.amazon.com/gp/product/0738205249?ie=UTF8&tag=institutional-20&linkCode=xm2&camp=1789&creativeASIN=0738205249 "Greenspan").  We learn of his somewhat unconventional dating techniques, including inviting Andrea Mitchell back to his apartment on the pretext of showing her an ‘essay I’d written on antitrust for Ayn Rand’ (p. 97).  Greenspan certainly does not downplay the influence of Rand, saying that ‘Ayn Rand became a stabilizing force in my life’ (p. 51), quite possibly the only person for whom this was true (Barbara Branden’s biography, [The Passion of Ayn Rand](http://www.amazon.com/gp/product/038524388X?ie=UTF8&tag=institutional-20&linkCode=xm2&camp=1789&creativeASIN=038524388X "The Passion of Ayn Rand"), also noted that Greenspan was one of the few among Rand’s inner circle who came through the experience unscathed).  Greenspan was among the handful of Rand’s acolytes who aspired to, and subsequently achieved, a role in the public policy mainstream: ‘by the time I joined Richard Nixon’s campaign for the Presidency in 1968, I had long since decided to engage in efforts to advance free-market capitalism as an insider, rather than as a critical pamphleteer’ (p. 52).  Much of the value in Greenspan’s memoir comes from his perspective as a ‘lifelong libertarian Republican’ (p. 208), who progressed to the upper echelons of US economic policymaking.

One the issues confronting US policymakers in the late 1990s and early 2000s was what to do with a growing federal budget surplus and the prospect of paying down outstanding federal government debt.  Greenspan quotes Republican Congressman Bill Archer, who characterised the problem in ironic terms that would be all too familiar to Australian readers: ‘because of record-high taxation, the surplus is raging out of control’ (p. 185).  Greenspan found himself ‘picturing American government officials becoming the world’s largest investors’ and coming to ‘a stark realization: chronic surpluses could be almost as destabilizing as chronic deficits’ (p. 218).  The recession of 2001 meant that the US no longer faces this peculiar problem, but Greenspan’s disquiet is still highly relevant in the Australian context.  While much has been made of Greenspan’s supposed criticisms of the Bush Administration, Greenspan’s harshest criticism is that Bush did not exercise his veto powers more aggressively to stop Congressional fiscal excesses.

Greenspan says that ‘Australia has always fascinated me as a microcosm of the United States’ and that he looked to Australia ‘as a leading indicator of many aspects of US economic performance’ (p. 292).  He took particular comfort from Australia’s ability to run persistently large current account deficits, noting that these had ‘no significant macroeconomic impact’ (p. 292).  Elsewhere in the book, he notes that ‘I do not recall a decade free of surges in angst about the mounting debt of households and business.’  As Greenspan argues, ‘rising debt goes hand in hand with progress…debt will almost always rise relative to incomes so long as we have an ever-increasing division of labour and specialization of tasks, increasing productivity and a consequent rise in both assets and liabilities as a percentage of income.  Thus, a rising ratio of debt to income for households…is not in itself a measure of stress’ (pp. 346-7).  Greenspan argues that current account imbalances are here to stay and are a natural consequence of increased specialisation and division of labour spilling across borders due to globalisation.

Greenspan also effectively debunks some of the myths surrounding the role of official reserve assets and related transactions in asset price determination, myths that still have a substantial hold on the thinking of even sophisticated investors in wholesale financial markets.  He notes that because of depth and liquidity of US dollar-denominated asset markets, ‘large accumulations or liquidations of US Treasuries can be made with only modest effects on interest rates.  The same holds true for exchange rates’ (p. 349).  Greenspan cites the most obvious example of the irrelevance of official reserve asset transactions when notes that ‘Japanese monetary authorities, after having accumulated nearly \$40 billion a month of foreign exchange, predominantly in US Treasuries, between the summer of 2003 and early 2004, abruptly ended that practice in March 2004.  Yet it is difficult to find significant traces of that abrupt change in either the prices of the US Treasury ten-year note or the dollar-yen exchange rate.  Earlier, Japanese authorities purchased \$20 billion of US Treasuries in one day, with little result’ (pp. 487-8).  Despite evidence such as this, there are still many fund managers who premise their investment strategies on second-guessing government actions in relation to official reserve assets.

Looking out to 2030, Greenspan foresees an end to the current glut of global saving and the disinflationary impulse from the globalisation of the labour force, as developing economies like China mature.  He doubts US policymakers will have the resolve to address the fiscal challenges associated with an aging population or to resist future inflationary pressures, predicting a 4.5% inflation rate and an 8% yield on US 10-year Treasuries, with real interest rates rising by around one percentage point (p. 484).  While this scenario is necessarily speculative, it is one that follows logically enough from his analysis of recent global economic conditions. 

Greenspan’s book will likely disappoint those looking for a more robust and detailed engagement with his many critics on the finer points of the conduct of monetary policy.  The book’s main value lies in bringing a free-market perspective on global economic developments and public policy issues before a wider audience.
