---
title: "Greenspan and Coincident Indicators"
date: "2007-09-21"
categories: ["Economics", "Financial Markets"]
---

[Robert Krulwich](http://blogs.wsj.com/economics/2007/09/20/greenspan-no-dope-but-a-nose-for-it/ "Robert Krulwich") recalls Greenspan’s fondness for unusual coincident indicators of economic activity:

> *He once told me that if you think about all the garments in the household, the garment that is most private is the male underpant, because nobody sees it except people like in the locker room, and who cares? Your children need clothes. Your wife needs clothes that have to change. The children grow. You need clothes on the outside. But, the last purchase that you don’t have to make is underpants. … If you look at the sales of men’s underpants, it’s just pretty much a flat line, it hardly ever changes. But on those few occasions where it dips, that means that men are so pinched that they are deciding not to replace underpants. And he said that is almost always a sort of foreshadow of ‘here comes trouble.’*

Of course, Greenspan also has a very well-developed sense of humour.
