---
title: "Has the RBA Pre-Empted Labor on Reform?"
date: "2007-12-05"
categories: ["Economics", "Financial Markets"]
---

The RBA has [announced](http://www.rba.gov.au/MediaReleases/2007/mr_07_22.html "announced") new arrangements for communicating with the public.  The RBA will now release a statement following each monthly Board meeting, even when policy is left unchanged.  The Board’s decision on interest rates will be announced at 2:30pm on the day of the meeting, rather than the following day.  The RBA will now also release minutes of the monthly Board meetings, with a two week lag.

The RBA said that it has been reviewing its communications practices ‘for some months.’  To that extent, the new measures can be seen as independent of the change in government.  However, it is likely that the RBA has been working on these measures in anticipation of demands for increased transparency and accountability from the incoming Labor government.  The measures may well be a pre-emptive strike against demands for more meaningful reform, designed to ensure that any changes are made on the RBA’s own terms and preserve the effective monopoly that the Bank’s senior officers enjoy over monetary policy decision-making. 

The new measures will certainly be an improvement.  The statement accompanying today’s steady interest rate decision saw a rally in bond futures and a weaker Australian dollar, implying that the statement conveyed new information to the market, resulting in more efficient pricing of financial instruments.

The minutes of the November meeting released today are largely descriptive and backward-looking in their discussion of economic conditions, a problem which also afflicts the quarterly Statements on Monetary Policy.  This is in contrast to the more forward-looking statements released by the Bank of England and the RBNZ.  The section on ‘considerations for monetary policy’ has the potential to be more informative, but it appears as though the RBA will be presenting only the consensus view, with the views of individual Board members not discussed. 

There will be no record of any vote taken. It is likely that what little dissent there is on the Board will be suppressed in the minutes.  The RBA has long argued that identifying the views of individual members would subject them to external pressures, given the numerous potential conflicts of interest of the external Board members.  This highlights the continued incompatibility of the current Board arrangements with increased transparency and accountability. 

This conflict can only be resolved by separating monetary policymaking from the Bank’s Board and placing it in the hands of an independent, professional Monetary Policy Committee, with substantial external representation and excluding the Treasury Secretary, who may serve as a vector for political influence on monetary policy. 

The votes of the Committee should then be made public immediately following each meeting, ensuring increased transparency and accountability for decision-making and protecting the integrity of the monetary policy process.  It would also end the RBA’s de facto monopoly on decision-making, by ensuring that members of the Committee had the expertise and experience to challenge the views of the RBA’s senior officers.

Today’s measures are an attempt by the Bank to give the appearance of increased transparency and accountability, but without seriously challenging the status quo.  Most rankings of central bank transparency and accountability are based on check-lists of factors that are quantitative rather than qualitative in nature.  The changes will thus have the effect of lifting the RBA from its current position at the bottom of international rankings of central bank transparency and accountability.  Qualitatively, however, the RBA will continue to lag world’s best practice in monetary policy governance.
