---
title: "Household Sector Debt and Wealth Accumulation"
date: "2007-10-02"
categories: ["Economics", "Financial Markets"]
---

[Steve Burrell](http://www.smh.com.au/news/business/were-all-richer-we-just-dont-realise-it/2007/10/01/1191091029764.html "Steve Burrell ") highlights the extent to which household sector borrowings underpin the accumulation of financial and other assets:

> we are taking on more debt to accumulate wealth and this leveraging has paid off handsomely. Figures earlier this year showed Australians on average had debts of just over \$25,000. Not only is that dwarfed by the value of assets they hold, but the ratio of wealth to debt was the highest in nine years.
>
> Last Friday’s figures showed that, overall, net household financial wealth in the June quarter was up by 23.3 per cent on a year ago to \$1208 billion.
>
> That means that, after allowing for borrowings, every Australian has a record \$57,400 in net financial assets - up more than 21 per cent in a year and by 48.6 per cent in the last two years, the largest jump on record.
>
> And that’s before we take into account the wealth tied up in homes. Other recent figures show the value of Australian dwellings rose by almost 10 per cent over the past year to stand at \$3.3 trillion at the end of June. The latest figures on overall wealth show the average Australian worth nearly \$400,000 at the end of March, a record high and a doubling in the past five years.
