---
title: "How to Announce a Steady Interest Rate Decision"
date: "2007-09-13"
categories: ["Economics", "Financial Markets"]
---

The RBNZ is now [webcasting](http://www.r2.co.nz/20070913/rbnz-384.asx "webcasting") Governor Bollard’s Monetary Policy Statement press conferences (you can see a replay by following the link), a further enhancement in the transparency of NZ monetary policy.

These press conferences make a sharp contrast to the almost non-existent public profile of the RBA Governor.  There are good reasons why the RBA Governor should be required to hold a press conference after each Board meeting and following each quarterly Statement on Monetary Policy. 

Quite apart from the increased public scrutiny of monetary policy this would provide, it would also change the character of electronic reporting of monetary policy.  As things stand, the electronic media in Australia report interest rate decisions from banks’ dealing rooms, which provide the colour and movement they need to illustrate the story.  The story then becomes centered around financial market reaction.

The Treasurer is the only responsible public official who makes a media appearance in the wake of monetary policy decisions, which contributes to the peculiar and undesirable Australian habit of interpreting interest rates decisions almost exclusively through the prism of political competition.  This is partly a hang over from the bad old days before 1996, when interest rate decisions were jointly announced by the RBA and the Treasurer, but it still heavily skews the electronic reporting of Australian monetary policy.  Having the RBA Governor front the media could significantly change this dynamic and would help serve to educate the public about how monetary policy is determined.

The RBA protests that it would not have anything to talk about when rates were left unchanged.  As Bollard’s press conference shows, there is always plenty to talk about, even when interest rates are left unchanged.  The RBA just doesn’t want the scrutiny.

If I were opposition Treasury spokesman Wayne Swan, one of my first acts on becoming Treasurer would be to request that Governor Stevens front the media after every Board meeting.  I would then get to work re-writing the RBA Act to remove responsibility for monetary policy from the RBA Board and put it in the hands of a dedicated Monetary Policy Committee, on which the Bank’s senior officers would be a minority.  The rest would be made up of appointees from outside the Bank.
