---
title: "‘I am not proposing that money be free, but…’"
date: "2007-02-22"
categories: ["Economics", "Financial Markets"]
---

Glenn Stevens’ first appearance before the [House Economics Committee](http://www.aph.gov.au/hansard/reps/commttee/R9961.pdf "House Economics Committee") in his capacity as Governor of the Reserve Bank saw very little change in the dynamics of these hearings.

Committee Chair and federal member for Qantas, Bruce Baird, did his usual thing of reading out loud newspaper articles and seeking the Governor’s reaction, which says a lot about his level preparation for these hearings.  The Labor Party’s Sharon Grierson disgraced herself with this contribution:

> *I am not proposing that money be free, but why can’t Australians enjoy the low interest rates being enjoyed by countries like New Zealand.*

New Zealand’s official interest rates are of course 100 bp higher than in Australia, but I guess we can take comfort from the fact that she is not, afterall, proposing ‘free money.’

Glenn Stevens avoided addressing the monetary policy outlook directly in his prepared statement, only to make a more explicit statement under questioning (see [Terry McCrann](http://www.news.com.au/couriermail/story/0,23739,21273226-3122,00.html "Terry McCrann") on the significance of Stevens’ remarks).  This only serves to highlight the fact that the Bank is being less than candid in its Statements on Monetary Policy and in its opening statements before the Committee.

Governor Stevens’ informed the Committee that his own home was ‘a piece of spec rubbish, built in the 1970s,’ which was somehow meant to be reassuring.  Former Governor Ian Macfarlane also had occasion to note the appalling standard of housing in Australia in his own youth.  Much of the silly prejudice against housing investment among the commentariat in Australia stems from the failure to recognise how woefully undercapitalised Australia’s housing stock has been, at least until the most recent boom in residential investment.

Stevens laid to rest a long-standing myth that there is a convention against the RBA adjusting interest rates in the context of federal election campaigns:

> *There seems to be a view abroad that there is some almost unspoken tradition that we do not adjust rates in an election year. I have seen a number of references to my predecessor supposedly having said that. I do not recall that he did say that. What I can recall is that he said we would not be all that keen to be changing them in the election campaign. I know that the political process often talks about being in permanent campaign mode, but what I think he meant by that was the formal campaign in the months prior. He also said if it had to be done it would be. So I do not accept, and I do not think we ever could accept, the idea that in an election year—which, after all, is one year out of three—you cannot change interest rates. When you think about that, I do not think any central bank could accept the notion that somehow a rate change is off limits for one year out of three. That would be crazy. So the answer to the question is: if in August it needs to be done it will be done.*

Unfortunately, these myths have a life of their own, and this one will almost certainly feature in pre-election commentary this year.
