---
title: "‘I for one welcome our new social-democratic overlords…’"
date: "2007-11-25"
categories: ["Economics", "Financial Markets", "Politics"]
---

Australia’s federal election has seen a change of government, with the Labor Party set to win 86 seats in the House of Representatives against the incumbent conservative Coalition’s 62 seats.  The Labor Party secured a two-party preferred swing of around 6%, to win its largest two-party preferred vote share in the post-war period of around 54%.  It is likely that incumbent Prime Minister John Howard will lose his seat in parliament.  The Coalition will also lose its majority in the Senate.  The decisive nature of the Labor win should minimise any negative implications for financial markets that might have arisen from the possibility of a hung parliament or minority government.

The change in government opens up a number of possibilities for positive change.  There is a good chance the Labor Party will finally address the Coalition’s legacy of failure in relation to statutory reform of central bank governance, which has left the Reserve Bank of Australia as one of the developed world’s [least accountable and transparent central banks](http://www.econ.cam.ac.uk/faculty/geraats/tpindex.pdf "least accountable and transparent central banks").  Outgoing Treasurer Peter Costello cites central bank reform as one of his greatest achievements when it is in fact one of his many failures as Treasurer. 

Costello’s other great failing as Treasurer was to withhold the benefits of national prosperity from the Australian people, by hoarding Commonwealth revenue on an unprecedented scale.  Rather than continuing to nationalise private equity capital and other assets via the [Future Fund](http://www.cis.org.au/policy/spring_06/PDF's/spring_06_kirchner.pdf "Future Fund"), it is to be hoped that the ALP will lower the record federal tax burden Peter Costello inflicted on the Australian people.

Malcolm Turnbull has held on to the seat of Wentworth against the odds, almost securing a majority in his own right on the primary vote.  The anti-pulp mill left were repudiated, despite a massive campaign against Turnbull.  The Labor Party’s George Newhouse was [literally bitch-slapped](http://www.news.com.au/heraldsun/story/0,21985,22816258-5005961,00.html "literally bitch-slapped").  The result gives Turnbull ample authority to contest the leadership of the federal parliamentary Liberal Party.  Turnbull is the Liberal Party’s best chance for renewal.

Perhaps the worst aspect of the federal election is that the balance of power in the Senate will be held either by anti-gaming wowser Nick Xenophon in combination with Family First’s Steve Fielding or the Greens.  It is hard to know which of these two possibilities is least friendly to our liberties.

**UPDATE:**  As we [predicted back in June](../2007/turnbull_and_costello.qmd "predicted back in June"), [Costello does not have the stomach to lead](http://www.theaustralian.news.com.au/story/0,25197,22818235-601,00.html "Costello does not have the stomach to lead").

**UPDATE II:** [Turnbull declares](http://www.theaustralian.news.com.au/story/0,25197,22818511-601,00.html "Turnbull declares")!
