---
title: "I Know What Nouriel Roubini Did Last Summer III"
date: "2007-02-01"
categories: ["Economics", "Financial Markets"]
---

Nouriel Roubini’s [forecast of flat US GDP growth in Q4](http://www.rgemonitor.com/blog/roubini/159887 " forecast of flat US GDP growth in Q4") lies in ruins.  Reaction from [Brian Wesbury](http://www.ftportfolios.com/retail/research/viewresearcharticle.aspx?Id=249 "Brian Wesbury"):

> Real GDP increased at an annual rate of 3.5% in Q4, beating the consensus forecast of 3.0%.  Real GDP was up 3.4% versus a year ago…
>
> Today’s GDP report shows that the economy remained strong in Q4 and suggests robust growth ahead.  There are still no signs that the on-going correction in the housing market is damaging the rest of the economy.  Excluding housing, real GDP growth would have been 4.8%. Consumption and business investment, combined, contributed 3 percentage points to the real GDP growth rate.  Although business investment declined for the first time in almost four years, we believe this will be reversed quickly as firms make use of the past few years of high profit growth and strong corporate balance sheets.  Moreover, the decline in inventory investment in Q4 makes room for more GDP growth in early 2007.  We also note that the growth rate of nominal GDP over the past two years shows the Fed is still loose and higher inflation is in the pipeline.  Nothing in today’s data alters our 2007 outlook for both better growth and more inflation than the consensus expects.

And from [Action Economics](http://www.actioneconomics.com "Action Economics"):

> *Whereas some analysts in 2006 focused on whether the growth slowdown was excessive, the real issue is whether it will prove adequate to relieve pressure on inflation, as was our concern, and the stated concern of the FOMC since the start of the policy “pause.”*

Nouriel [now](http://www.rgemonitor.com/blog/roubini/175615 "now") ludicrously refers to his ‘current view of a 2007 hard landing with a growth recession.’  As with all his previous forecasts of gloom and doom, Nouriel’s recession call is forever receding into the distance. 

**UPDATE:** Reaction from the [WSJ](http://online.wsj.com/article/SB116960346089285778.html?mod=hpp_us_at_glance_opinion "WSJ"):

> *you may have noticed that 2006 ended without a recession. This follows the recessions of 2003, 2004 and 2005, all of which also never occurred, though they were widely warned about in the press and even forecast by many economists at some point during each of those years.*
