---
title: "In Defence of Sub-Prime Lending"
date: "2007-03-30"
categories: ["Economics", "Financial Markets"]
---

Chicago’s [Austan Goolsbee](http://www.nytimes.com/2007/03/29/business/29scene.html?em&ex=1175313600&en=e827d4e75d704fa3&ei=5087%0A "Austan Goolsbee") defends innovations in mortgage markets against economic and financial Luddites like Nouriel Roubini:

> Almost every new form of mortgage lending — from adjustable-rate mortgages to home equity lines of credit to no-money-down mortgages — has tended to expand the pool of people who qualify but has also been greeted by a large number of people saying that it harms consumers and will fool people into thinking they can afford homes that they cannot…
>
> These innovations mainly served to give people power to make their own decisions about housing, and they ended up being quite sensible with their newfound access to capital…
>
> The traditional causes of foreclosure, even before there was subprime lending, were job loss, divorce and major medical expenses. And the national foreclosure data seem to suggest that these issues remain paramount. The latest numbers show that foreclosures have been concentrated not in places where real estate bubbles have supposedly been popping, but rather in places whose economies have stagnated — the hurricane-torn communities on the Gulf of Mexico and the industrial Midwest states like Ohio, Michigan and Indiana, where the domestic auto industry has suffered. These do not automatically point to subprime lending as the leading cause of foreclosure problems.

Goolsbee must be a member of the ‘[cabal of supply side voodoo ideologues](http://www.rgemonitor.com/blog/roubini/184125 "cabal of supply side voodoo ideologues").’
