---
title: "Inflation, Interest Rates, the RBA and John Howard"
date: "2007-01-26"
categories: ["Economics", "Financial Markets"]
---

Take two central banks, both with 3% as the upper bound of their inflation targets.  One is presiding over an inflation rate of 3.3%, the other 2.6%.  Which central bank would you think is more likely to raise interest rates?  According to financial markets, it’s the latter, otherwise known as the Reserve Bank of New Zealand.  RBNZ Governor Bollard this week warned that further increases in interest rates were likely, causing NZ interest rate futures to tumble and the New Zealand dollar to rally. 

Yet across the Tasman, interest rate futures in Australia rallied and the Australian dollar fell sharply as the Q4 CPI came in lower than expected, causing markets to all but price out any future interest rate increases by the Reserve Bank of Australia.  The RBA’s preferred measures of underlying inflation are all running at the top end of the 2-3% target range and Australia faces capacity constraints almost as severe as those in NZ, yet there is a much higher level of complacency about inflation and interest rates in Australia than in NZ.  This says a great deal about the very different operating styles of the RBA and RBNZ, despite having superficially similar inflation targeting regimes.

The RBA will likely leave its inflation forecast unchanged in its February Statement on Monetary Policy.  Coupled with its usual reluctance to venture any meaningful discussion of the policy outlook, this will almost certainly lead many observers to conclude that the interest rate cycle in Australia has peaked, a conclusion that has been erroneously drawn after several Statements this cycle. 

The Australian Financial Review’s discussion of the Q4 CPI and interest rates was conducted almost entirely in terms of its implications for federal politics, as if interest rates determined election rather than inflation outcomes.  In particular, it was suggested that Prime Minister John Howard might be ‘fortunate’ enough to go into this year’s federal election with interest rates heading down rather than up.  But [as we have pointed out previously](../2006/who_do_you_trust_to_keep_the_unemployment_rate_low.qmd "as we have pointed out previously"), turning points in the official cash rate are closely related to turning points in the unemployment rate in the opposite direction.  If interest rates are heading lower into the federal election, the unemployment rate will almost certainly be heading higher.  Which has better predicative power for the two-party preferred vote?  According to the models, it’s the unemployment rate.  Higher interest rates reflect good economic news, not bad.  As an incumbent, I would rather go into a federal election with rising interest rates and a falling unemployment rate than vice versa.  My suggestion for John Howard’s next campaign slogan: ‘Who do you trust to keep the unemployment rate low?’
