---
title: "Jeffrey Sachs as Central Planner"
date: "2007-07-03"
categories: ["Economics", "Financial Markets"]
---

[William Easterly](http://www.foreignpolicy.com/story/cms.php?story_id=3861&page=0 "William Easterly"), on the ideology of development:

> The ideology of Development is not only about having experts design your free market for you; it is about having the experts design a comprehensive, technical plan to solve all the problems of the poor. These experts see poverty as a purely technological problem, to be solved by engineering and the natural sciences, ignoring messy social sciences such as economics, politics, and sociology.
>
> Sachs, Columbia University’s celebrity economist, is one of its main proprietors. He is now recycling his theories of overnight shock therapy, which failed so miserably in Russia, into promises of overnight global poverty reduction. “Africa’s problems,” he has said, “are … solvable with practical and proven technologies.” His own plan features hundreds of expert interventions to solve every last problem of the poor—from green manure, breast-feeding education, and bicycles to solar-energy systems, school uniforms for aids orphans, and windmills. Not to mention such critical interventions as “counseling and information services for men to address their reproductive health needs.” All this will be done, Sachs says, by “a united and effective United Nations country team, which coordinates in one place the work of the U.N. specialized agencies, the IMF, and the World Bank.”
>
> So the admirable concern of rich countries for the tragedies of world poverty is thus channeled into fattening the international aid bureaucracy, the self-appointed priesthood of Development. Like other ideologies, this thinking favors collective goals such as national poverty reduction, national economic growth, and the global Millennium Development Goals, over the aspirations of individuals. Bureaucrats who write poverty-reduction frameworks outrank individuals who actually reduce poverty by, say, starting a business. Just as Marxists favored world revolution and socialist internationalism, Development stresses world goals over the autonomy of societies to choose their own path. It favors doctrinaire abstractions such as “market-friendly policies,” “good investment climate,” and “pro-poor globalization” over the freedom of individuals.
