---
title: "Kevin Rudd’s Anti-Market Ideology"
date: "2007-10-20"
categories: ["Economics", "Politics"]
---

‘Traditional Labor voter’ [Paul Kerin](http://www.theaustralian.news.com.au/story/0,25197,22614727-5013871,00.html "Paul Kerin") exposes the ignorance and intellectual laziness underlying Kevin Rudd’s anti-market ideology:

> The best glimpses of Rudd’s philosophy are contained in a couple of articles he wrote in The Monthly last year before becoming Opposition Leader. His social aspirations - and genuine passion about them - are admirable, although not ambitious enough. But his economic philosophy, or lack thereof, is worrying. The ideologically driven uni-dimensional view of the world outlined in the essays prevents him from entertaining the thought that freer markets could help him better achieve his social aspirations. Rudd depicts the “real battle of ideas in Australian politics” as the “battle between free market fundamentalism and the social-democratic belief that individual reward can be balanced with social responsibility”.
>
> This depiction - replete with false mutual exclusivities (free market v social responsibility) and put-down labels (free market fundamentalism) - implies that anyone who supports free markets must be a selfish bastard who doesn’t care about social goals. Nothing could be further from the truth…
>
> Rudd attacks “market fundamentalists”, a label he liberally attaches to Hayek and modern economic liberals, for believing that humans are “almost exclusively self-regarding” and for holding self-regarding values themselves. He contrasts this with “other-regarding values of equity, solidarity and sustainability” of social democrats such as him.
>
> Ironically, he claims fundamentalists “distort Smith, adopting his Wealth of Nations while ignoring ... his The Theory of Moral Sentiments”. I can’t believe that an intelligent, reflective man such as Rudd has read either book. If he had, he would not have drawn this conclusion. It is a gross distortion. Smith’s views on human behaviour in both works are perfectly consistent…
>
> Rudd clearly hasn’t read Hayek either. His only evidence on Hayek’s values are quotes from former communist and non-economist David McKnight.
