---
title: "Labor’s Tax Policy"
date: "2007-10-26"
categories: ["Economics", "Financial Markets", "Politics"]
---

[Sinclair Davidson and Alex Robson](http://www.theaustralian.news.com.au/story/0,25197,22648596-7583,00.html "Sinclair Davidson and Alex Robson") on Labor’s tax policy:

> Treasurer Peter Costello is correct when he claims there is a higher tax burden for some taxpayers under the ALP plan: all taxpayers earning between \$37,000 and \$102,000 will be worse off under Labor.
>
> But the flip side is that some taxpayers will have a lower tax burden and be better off under Labor.
>
> This can be confirmed simply by inspecting the table of figures released by the Treasurer on Sunday. After 2013, for example, those on incomes of \$102,000 and above will be better off under Labor because they face lower marginal and average tax rates.
>
> This part of Labor’s plan makes good economic sense. Nobel laureate James Mirrlees, who is leading a comprehensive review of tax policy in Britain, has shown that, even allowing for changes in income inequality, marginal tax rates should fall, not rise, as income increases. This is because the negative supply-side consequences of higher income taxes tend to swamp the inequality effects.
>
> The most recent economic evidence from the US suggests higher income earners - those who will benefit most from Labor’s plan - tend to be the most responsive to changes in their taxable income. By flattening the tax structure, both tax plans move in the right direction.
