---
title: "Long Isotopes"
date: "2007-03-05"
categories: ["Economics", "Financial Markets"]
---

Hedge funds [capitalise](http://online.wsj.com/article/SB117306351498226632.html?mod=hps_us_pageone "capitalise") on the opportunity the nuclear industry missed:

> Adit Capital, a small hedge fund in Portland, Ore., was an early uranium investor, buying millions of pounds for as little as \$20 a pound beginning in December 2004, said Bob Mitchell, its founder.
>
> It jumped into the uranium market after Mr. Mitchell noticed nuclear utilities allowing inventories to dwindle when the material was cheap, to avoid the cost of storing it. Meanwhile, some mining companies had been selling more future production than Mr. Mitchell figured they would be able to produce, and mines were closed when prices were depressed in the 1990s—all evidence of a coming shortage…
>
> The uranium market hasn’t had a down week since June 2003, according to Ux Consulting Co., a Roswell, Ga., price-reporting service.
>
> Production shortfalls at uranium mines around the world are helping drive up the price, says Jim Cornell, president of Connecticut nuclear-fuel trading firm NUKEM Inc \[gotta love that name - ed\]...
>
> When selling uranium, the Energy Department makes no distinction between financial investors and end users, so long as it’s held in authorized storage facilities. Bidders must disclose their identity and the nature of their business.
>
> The Nuclear Energy Institute in Washington, which represents utilities and fuel processors and producers, asked the Energy Department on Feb. 5 to exclude anyone but end users from federal auctions. In a letter, the institute asked the government to “protect utilities that cannot procure sufficient uranium in the open market.”…
>
> Financial investors say they are just seizing on buying opportunities that the nuclear industry missed. Moreover, industry players say, high prices are encouraging hedge funds and others to invest in mining companies, which will help finance increased production and possibly drive down prices.
>
> The NEI’s Mr. Fertel conceded as much. In the long run, “I think we’re going to end up with a much better situation than we even had before,” he said…
>
> Indeed, eventually “the price of uranium will collapse,” said Adit’s Mr. Mitchell. “I don’t know when, but the mining companies of the world will get their act together. The guts of the trade was getting into it before anybody even knew you could. But the art of the trade will be getting out before the price turns over.”
