---
title: "Lunch with Kevin Rudd"
date: "2007-10-10"
categories: ["Economics", "Financial Markets", "Politics"]
---

Federal opposition leader Kevin Rudd addressed an Australian Business Economists’ lunch last week.  John Edwards’ observations on the event go a long way to explaining why a booming economy is providing the government with little or no political traction:

> *Rudd ranged widely over Australia’s recent economic record and what he planned to do if elected to government.  He then took questions.  There were just three, none of them memorable.  Given that the polls show Mr. Rudd will highly likely be Prime Minister within eight weeks or so and that Labor has been out of office for over a decade, this was a remarkably small number of questions from what might be expected to be a well informed, concerned and not particularly sympathetic audience…Mr. Rudd wasn’t asked many questions, because there isn’t much worth asking.*

Edwards’ goes on to note the near complete bipartisanship between the government and opposition on economic policy and says:

> *for all its vaunted political brilliance \[the government has\] an amazing inability to shape the economic debate.*
