---
title: "Mischiefs that Ought Justly Be Apprehended from a Rudd Government"
date: "2007-07-12"
categories: ["Economics", "Financial Markets"]
---

The ACCC will be kept very busy doing not very much under a prospective Rudd government.  Rudd wants increased scrutiny of supermarket prices, in addition to the increased surveillance of petrol prices he has already proposed.  As [Jennifer Hewett](http://www.theaustralian.news.com.au/story/0,20867,22058831-643,00.html "Jennifer Hewett") notes, these proposals are redundant at best:

> Labor’s big pronouncement yesterday on referring grocery prices to the Australian Competition and Consumer Commission for review is not just a triumph of populism. It’s also a complete absurdity.
>
> The ACCC already has the power to investigate possible pricing anomalies and does so regularly.
>
> But the idea that Graeme Samuel can do a better job of lowering prices than Coles or Woolies is ludicrous.
>
> The timing of Rudd’s opportunistic announcement only makes that more obvious.
>
> At Woolworths’ release of its sales figures on Tuesday, CEO Mike Luscombe spent a long time justifying to analysts why his business was investing so much money in reducing prices rather than increasing its margins.
>
> Bottom line: it wants to beat Coles by attracting more customers willing to buy more products. That involves a constant battle to lower its own costs as well as the cost to consumers.
>
> Labor Party bleating about unjustified price rises suggests they either don’t understand what drives an aggressively competitive market, or they are just feigning ignorance. It’s difficult to decide which is worse.

Of course, one could say much the same about the ACCC itself.  The ACCC has a [dismal track record in the courts](http://www.mallesons.com/publications/2007/May/8951593W.htm "dismal track record in the courts") on these and many other issues.
