---
title: "Monetary Policy is Not a Morality Play"
date: "2007-09-09"
categories: ["Economics", "Financial Markets"]
---

[Tyler Cowen](http://www.nytimes.com/2007/09/09/business/09view.html?ex=1346990400&en=171a2af8997af52d&ei=5124&partner=permalink&exprod=permalink "Tyler Cowen") argues against the urge to resort to simple monetary policy narratives in the current environment:

> Colorful interpretations of recent monetary policy abound, from both commentators and politicians. Depending on the storyteller, the policy reflects the triumph of the rich over the poor, an atonement for the sins of the Bush administration, a long-awaited comeuppance for the American economy, a continuing hangover from the dot-com bubble, or an inability of the professor (Ben S. Bernanke) to handle a real-world job (running the Fed).
>
> Journalists are especially likely to embrace narratives, if only because their editors and their readers clamor for them. Of course, if there are enough competing stories, some of them will fit or predict some real-world events, if only because of random luck.

Perhaps the most seductive of these narratives is Austrian business cycle theory, because it can be made to fit almost any set of business cycle facts. 

In view of the weak US August employment report, the Fed will now probably ease policy on September 18.
