---
title: "More Currency Speculation from Warren Buffett"
date: "2007-05-19"
categories: ["Economics", "Financial Markets"]
---

Warren Buffett is [back making currency bets](http://www.ft.com/cms/s/ed6e1304-ff23-11db-aff2-000b5df10621.html "back making currency bets"), although this time is saving himself the embarrassment of revealing what they are:

> Warren Buffett, perhaps the world’s most influential investor, sent the foreign exchange markets scrambling this week after revealing that he had made a “surprising” new bet on the currency markets.
>
> Mr Buffett added to the intrigue by indicating he was only actively buying one currency. “We will tell you about it next year,” he said.
>
> At first glance, the Sage of Omaha is not taking his own advice.  “The cemetery for seers has a huge section set aside for macro-forecasters,” he once said…
>
> Mr Buffett’s Berkshire Hathaway did make more than \$2bn overall on a \$20bn-plus bet against the dollar that began in 2002, even after the market moved against him to the tune of \$1bn in 2005. But he has phased out most of the direct bet – which had started to cost money to hold – in favour of investments in companies with sales in other currencies…
>
> Perhaps the most surprising call for him would be to reverse his bearish stance on the dollar.
>
> Paul Mackel, currency strategist at HSBC, says it is possible that Mr Buffett thinks that US economic growth could accelerate, and has bought the currency.
>
> Ultimately, though, Mr Mackel says that Mr Buffett’s views on currencies are unlikely to carry as much weight as his views on companies.
>
> “His currency calls do generate a lot of headlines, but I’m not sure quite how seriously people take it,” adds Mr Mackel.
