---
title: "More Commonwealth Revenue Hoarding"
date: "2007-08-22"
categories: ["Economics", "Financial Markets"]
---

The Federal Treasurer has announced the 2006-07 [Budget outcome](http://www.treasurer.gov.au/tsr/content/pressreleases/2007/079.asp "Budget outcome") on a preliminary basis.  The underlying cash surplus came in higher than expected at \$17.3 billion or 1.7% of GDP, which (ominously enough) matches that seen at the peak of the last cycle in the late 1980s.  Revenue collections continue to exceed Treasury forecasts, backing former RBA Governor Macfarlane’s observation that the tax system is now much more income elastic than ever intended.  The Commonwealth will put \$7 billion in the Future Fund, which, together with the proceeds from T3, means the Future Fund should be able to realise its objective of funding outstanding public sector superannuation liabilities by 2020, without further government contributions.

This still leaves the government with the political problem of what to do with the other revenue it doesn’t need to cover recurrent expenditures.  So the government has been busy creating more lock-boxes in which to warehouse the surplus: the Higher Education Endowment Fund announced in this year’s budget; and the new Health and Medical Investment Fund, which will also be the repository for the proceeds from the sale of Medibank Private. 

With the Prime Minister undertaking to maintain surpluses of around 1% of GDP, the government will need to be increasingly creative in its efforts to keep these surpluses out of the hands of taxpayers.  The government is seeking to window-dress the surplus, by making it appear that it is being devoted to the supposedly worthy causes of higher education and health, but without doing anything new to address the long-term structural issues in these portfolio areas.  The question is whether this will actually ease future pressures on the budget.  It is just as likely that these funds will be used by future governments to avoid taking difficult fiscal policy decisions.

The Intergenerational Report suggests that current government spending programs are not sustainable.  But it is also pretty clear that these issues are not going to be meaningfully addressed on the expenditure side.  Whether future expenditures are meet out of current or future revenue is less important than the issue of the overall tax burden being created by current government spending programs.
