---
title: "More of What Nouriel Roubini Won’t Tell You About the US Economy"
date: "2007-01-21"
categories: ["Economics", "Financial Markets"]
---

Yet more of what Nouriel Roubini won’t tell you about the US economy, from my associates at [Action Economics](http://www.actioneconomics.com "Action Economics"):

> *The robust round of Michigan sentiment figures for January have closed out a week of solid reports that have all but put to rest fears of a hard landing for the economy. These solid confidence readings join solid consumer spending figures, robust labor market reports, solid wage and income trajectories, and an improving outlook for U.S. trade to round out a picture of a healthy overall economy.  The figures have correctly brought the market focus back to the more relevant question all along of whether the slowdown in the economy will prove adequate to reduce inflation pressures, and not whether the slowdown will prove excessive. Though our expectation that the next Fed move would be a tightening looked like quite an outlier two months ago, expectations of any near-term easing are now quickly dissipating with each new upside surprise.*
