---
title: "Mundell’s Long View on the US Dollar"
date: "2007-06-09"
categories: ["Economics", "Financial Markets"]
---

Nobel laureate [Robert Mundell’s](http://online.wsj.com/article/SB118134724082429687.html?mod=opinion_main_commentaries "Robert Mundell's") long view on the big dollar:

> HONG KONG—As the audience at the Asia Society’s May gala dinner here sips their coffee, the moderator allows one more question from the audience for Nobel economics laureate Robert Mundell. A Chinese gentleman stands to ask how much longer the U.S. dollar would remain the world’s reserve currency. The query seems like the perfect set-up for the world’s foremost expert on monetary policy and a well-known “friend of China” to predict the rise to pre-eminence of China’s currency.
>
> Instead, Mr. Mundell says that China is still far behind the U.S. in economic strength and stability. “I think the dollar era is going to last a long time . . . perhaps another hundred years.”

Nouriel Roubini’s worst nightmare.
