---
title: "New Appointments at the RBA"
date: "2007-02-14"
categories: ["Economics", "Financial Markets"]
---

Not before time (see previous post), Treasurer Costello [appoints](http://www.treasurer.gov.au/tsr/content/pressreleases/2007/004.asp "appoints") RBA Assistant Governor (Financial Markets) Ric Battellino to the position of Deputy Governor of the RBA. Graham Kraehe AO, Chairman of BlueScope Steel, has also been appointed as a non-executive member of the RBA Board.  For such a conservative choice for the Deputy Governor’s post, the delay in making this appointment is difficult to fathom.  Graham Kraehe’s appointment is unremarkable, although after the Bob Gerard affair, one can only assume he has no outstanding matters before the Tax Office. 

The non-executive board members generally vote in favour of the monetary policy recommendations put forward by the bank’s senior officers.  As I argue [here](http://www.cis.org.au/policy/spring04/spring04-9.pdf "here"), given the rubber stamp role of the non-executive directors in relation to monetary policy, it would make sense to separate monetary policymaking from the other governance functions of the RBA Board.  As things stand, the main role of the non-executive directors is to allow the Bank’s senior officers to effectively monopolise decision-making.  The non-executive members also provide a convenient, though completely bizarre, argument against releasing the minutes of Board meetings.  The RBA argues that the non-executive board members are too conflicted by their day jobs to have their role in monetary policymaking open to public scrutiny.  In any other governance role, this argument would be completely laughable, but it is one that suits the desire of the Bank’s senior officers to avoid public scrutiny and external interference in monetary policy.
