---
title: "No, Virginia, Tax Cuts Don’t Cause Higher Interest Rates"
date: "2007-05-04"
categories: ["Economics", "Financial Markets"]
---

The Federal government will hand down its 2007-08 Budget next Tuesday facing an all too familiar embarrassment of riches.  On a no policy change basis, the 2006-07 underlying cash surplus could easily exceed \$16 billion compared to a MYEFO estimate of \$11.8 billion, with the 2007-08 surplus likely to be in excess of \$10 billion. 

The actual surplus will then depend on how the government allocates the surplus among new spending, tax cuts and the Future Fund.  The challenge for the government in recent budgets has been to hold the fiscal impulse neutral, by keeping the change in the budget balance broadly steady as a share of GDP, in the face of what would otherwise have been a sharp fiscal contraction brought about by revenue growth that has consistently exceeded previous estimates.  This is consistent with the view that fiscal policy should be focused on microeconomic objectives and not demand management, with the latter task being best left to monetary policy. 

Among financial market economists, there is nonetheless a widely held view that the government should somehow assist the RBA in its demand management task, by favouring the accumulation of surpluses in the Future Fund over tax cuts to avoid putting upward pressure on inflation and interest rates.  The same argument is rarely made against new spending measures, even though ‘crowding out’ is a much more serious problem in relation to new spending than tax cuts.

As Treasury Secretary Ken Henry noted in his [private speech](http://www.treasury.gov.au/contentitem.asp?NavId=008&ContentID=1249 "private speech") to Treasury officers on 14 March, in a fully-employed economy, an expansion in the size of government necessarily comes at the expense of the private sector and implies a misallocation of resources away from more productive uses.  Indeed, this argument applies in the context of an economy operating below potential as well, since government will often make claims on resources that would have been employed by the private sector anyway.

Ken Henry said that ‘expansionary fiscal policy tends to “crowd out” private activity: it puts upward pressure on prices which, all things being equal, puts upward pressure on interest rates.’  Henry did not distinguish between an expansionary fiscal policy brought about by increased spending or reductions in taxes, but did note ‘that there is no policy intervention available to government, in these circumstances, that can generate higher national income without first expanding the nation’s supply capacity’  (emphasis in original).

Tax cuts need not crowd out private sector activity and may be of value in expanding supply.  In relation to crowding out, the key issue is whether budget surpluses raise national saving, resulting in ‘crowding in,’ or alternatively, whether tax cuts reduce national saving, resulting in crowding out.  While the effect on government saving from reductions in taxes is straightforward, the implications for private and overall national saving are not.  In particular, there are good reasons for thinking that increased public saving does not increase national saving, because of offsetting dissaving by the household sector.  Indeed, the much lamented decline in the household saving ratio is largely a function of an increased tax share of household income, along with higher mortgage interest payments from increased household gearing.  After a period of stability in the early to mid-1990s, net household saving fell, coinciding with an increase in net saving on the part of the government sector.  The net contribution of increased government saving to net national saving is far from obvious. 

In any event, the cyclical and international influences on Australian interest rates can be expected to overwhelm any effect from changes in government and national saving.  It is worth recalling that the much maligned high interest rates of the late 1980s were associated with some of the largest ever budget surpluses as a share of GDP.  The direction of Australian interest rates is largely set by global capital markets, not domestically.  Fiscal policy has not had a significant impact on interest rates in recent years, a point made on numerous occasions by former RBA Governor Ian Macfarlane.

Even if we think there is a possibility that a positive fiscal impulse from the budget would reduce national saving and increase demand pressures, this still ignores the supply-side of the equation.  This is a common vice among market economists, who tend to think almost exclusively in terms of demand, while making no allowance for supply-side dynamics.  The 32-year lows in the unemployment rate have been one of the RBA’s main concerns in relation to the inflation outlook.  Yet the record lows in the unemployment rate have also been associated with record highs in the labour force participation rate.  Increased growth in the labour force is important in preventing the labour market becoming a potential source of inflationary pressure.  Changes in both government spending and taxing can be useful in inducing increased labour supply.  While this proposition is readily accepted in relation to increased government spending on things such as childcare, it is less readily accepted in relation to tax cuts.  It is also widely accepted in the context of the government’s baby bonus that small changes in incentives can induce large behavioural responses.  Yet this idea seems to have very little acceptance when discussion turns to tax cuts, perhaps because the mechanisms involved are less obvious than in the case of more targeted government spending programs. 

The benefits of tax cuts extend well beyond their positive implications for labour supply, but also to issues relating to the deadweight losses, compliance and collections costs that flow from the operation of the tax system, all of which suggests tax cuts have the capacity to increase supply.  The main criticism that can be leveled at the government’s tax cuts in recent years is not their non-existent implications for interest rates, but that the government has failed to use budget surpluses to facilitate a more comprehensive overhaul of the federal tax and spending that would, in Ken Henry’s terms, raise national income through increased supply.  Instead, the government has engaged in piecemeal handbacks of previous bracket-creep, expanded a complicated system of poorly targeted tax expenditures, while planning to use current and future surpluses to partially nationalise the stock of equity capital via the Future Fund.  The government’s recent commitment of \$1.4 billion to industry policy initiatives is also a poor use of federal funds that will directly crowd out private sector activity.

The debate over whether federal surpluses should be used to fund reductions in taxes is strongly reminiscent of an identical debate in the US before the 2001 recession, when the US government was running large budget surpluses and faced the prospect of paying down outstanding federal debt.  [Alan Reynolds](http://www.cato.org/pubs/journal/cj21n2/cj21n2-11.pdf "Alan Reynolds") accurately summarised the outcome of that debate as follows:

> *The Mundellian or “supply side” revolution of 1971–86 mainly consisted of assigning price stability to monetary policy while putting much greater emphasis on the microeconomic details of fiscal incentives (marginal tax rates and regulations) rather than the macroeconomic morass of fiscal outcomes (budget deficits and surpluses). The subsequent fiscalist counterrevolution mainly consisted of a renewed fascination with federal borrowing and a revival of theories previously associated with conservative Keynesians of the Eisenhower–Nixon years. The key predictions of this theory were that budget surpluses would increase national savings, reduce real interest rates, and eliminate the current account deficit. All of those predictions proved false*.
