---
title: "Operation Sunlight"
date: "2007-11-27"
categories: ["Economics", "Financial Markets", "Politics"]
---

[More reasons](http://www.theaustralian.news.com.au/story/0,25197,22827010-601,00.html "More reasons") to welcome our new social-democratic overlords:

> INCOMING finance minister Lindsay Tanner is planning far-reaching reform of the budget to improve transparency.  He will overhaul the Charter of Budget Honesty, introduced by Peter Costello in 1996 to govern budget disclosure and Opposition rights to financial information during elections.
>
> Mr Tanner, who held meetings with Finance Department officials yesterday, is expected to take time to implement all of Labor’s proposed budget reforms, but there are likely to be some changes before its first budget in May.
>
> Under the proposals, new government programs that could be influenced by demographic shifts will have to be accompanied by five-year forecasts of their costs.
>
> The International Monetary Fund was critical of the Howard government’s failure to include any long-term assessment of the cost of its decision to make superannuation benefits tax-free for people aged over 60.
>
> Labor intends to include in the budget a statement explaining how welfare, health and education benefits are distributed among different income groups, and the taxes paid by those groups. The idea is to help in the assessment of the merits of government spending and tax levels.
>
> Labor wants the budget papers to contain more information about what individual government departments are spending.
>
> At present, the main budget papers list spending by broad function, so spending on housing might include programs run by the transport and regional services department, defence and family and community services. Although each department publishes its own portfolio budget, these do not include more than one year’s forecasts and do not match the main budget papers.
>
> Labor’s reforms follow an extensive consultation that resulted in the publication of a policy paper, called Operation Sunlight, last year…
>
> The Labor government will expect the Treasury and finance departments to provide continuous disclosure, posting major changes in the budget position on their websites and providing quarterly updates on the size of the surplus. There will be fixed dates for mid-year budget updates and monthly financial reports.
>
> The finance department has not posted a monthly budget report since June.

It may sound like a trivial matter, but the fixed dates for the budget updates will be a great improvement.  Outgoing Treasurer Peter Costello would fling these documents out at his own convenience, often with as little as a few hours notice.  I still shudder at the amount of my time that was wasted trying to find out when these things would be released and obtaining copies of the documentation in a timely manner.
