---
title: "Peter Coleman’s Martyrdom Operation"
date: "2007-11-28"
categories: ["Politics"]
---

[Peter Coleman](http://www.abc.net.au/news/stories/2007/11/28/2104341.htm?section=australia "Peter Coleman") commences martyrdom operations against John Howard on behalf of son-in-law, Peter Costello:

> “What was once seen as his gritty determination started to look like an almost animal egomania and he seemed to be blocking progress and regeneration, rather than advancing the cause,” \[Coleman\] said.
>
> Mr Coleman also says Mr Howard destroyed Mr Costello’s chance to be prime minister.
>
> “There is no doubt that this man of great promise and great ability was blocked by \[Mr\] Howard’s egomania,” he said.
>
> “I don’t think that can be doubted, in fact his colleagues wanted him to go and extraordinarily he refused to go and more than once.
>
> “And that put an end to a lifelong ambition that this very able fellow Costello had.”

Coleman’s loyalty to family is admirable enough, but there is no reason to believe that Peter Costello could have changed the Coalition’s fortunes.  Costello’s ambition was frustrated because there was never a compelling case for leadership change and never any evidence to suggest that Costello could improve the Coalition’s prospects.  That is Costello’s failing, not John Howard’s.  Whatever political success Peter Costello did enjoy was largely parasitic on John Howard’s.
