---
title: "Peter Costello as ‘Old-Fashioned Christian Socialist’"
date: "2007-05-16"
categories: ["Culture & Society", "Economics", "Politics"]
---

At the same time that Treasurer Peter Costello has been [branding](http://www.theaustralian.news.com.au/story/0,20867,21739647-601,00.html "branding") opposition leader Kevin Rudd a socialist, [Jennifer Hewett](http://www.theaustralian.news.com.au/story/0,20867,21739649-601,00.html "Jennifer Hewett") finds that Peter Costello is not above a bit of old-fashioned Christian socialist resentment either:

> An aggrieved Peter Costello certainly won’t be breaking out the champagne to celebrate with Allan Moss or Nicholas Moore.
>
> Their \$30 million-plus salaries will fuel the Treasurer’s anger with what he regards as a culture of greed and arrogance at the multi-multi-millionaires factory.
>
> Costello doesn’t like investment bankers much in general. But the uber-bankers at Macquarie, in particular, represent all that most irritates him.
>
> How, he wonders, can these guys justify earning so much while giving so little back?
>
> Those who know the Treasurer well have learned to expect a private tirade of vitriol about Macquarie whenever the bank’s name comes up.
>
> “He sees people benefiting from his hard work on the economy, enjoying the fruits of the Government’s labour and earning obscene amounts of money that he could never earn,” says one insider.
>
> It’s not so much that Costello wants to earn or spend such vast sums of money himself. His Baptist upbringing in Melbourne has moulded him as much as it has his brother Tim, chief executive of World Vision Australia.
>
> Even if their careers have gone in different directions, Peter Costello still finds personal excess distasteful, rather gross. And it’s not just a matter of disliking Sydney glitz.
>
> What really rankles the Treasurer is what he regards as the sheer and grotesque imbalance in the money equation, given how hard he believes government ministers work. None more so than himself….
>
> Another problem is that the Treasurer sees investment bankers as not actually producing anything.

...unlike politicians.
