---
title: "Peter Costello and Interest Rates"
date: "2007-11-08"
categories: ["Economics", "Financial Markets", "Politics"]
---

A remarkable [story](http://www.businessspectator.com.au/bs.nsf/Article/Costello_does_a_Garrett_on_rates_8Q5BT?OpenDocument "story"), if true:

> Jon Faine on ABC 774 in Melbourne has revealed yet another extraordinarily ill advised conversation between a leading politician and a journalist.
>
> The Treasurer, Peter Costello, was in Faine’s studios in late September and during a break for the news, Faine said to him: “I can’t believe you haven’t called the election to get it out of the way before the cup day interest rate rise.
>
> “He looked me in the eye. He put his thumb down as he sat there in the chair and he said, ‘There will not be a rate rise in November. Take it from me.’
>
> “I said : ‘You might be right, you might be wrong, but you’re prepared to punt on it.’
>
> “And he said : ‘There will not be a rate rise in November.’…
>
> How is it that the Treasurer of the country could so misread the mood of the Reserve Bank Board when virtually every analyst in the country was predicting the opposite?
