---
title: "Pink’s Ban Australia Bullshit (or Biting the Hand that Feeds Me)"
date: "2007-01-18"
categories: ["Culture & Society"]
---

Compare and contrast the Blog Ad at the right hand side bar with the [following story](http://www.smh.com.au/news/fashion/redfaced-pinks-uturn-on-wool-ban/2007/01/17/1168709798426.html "following story"):

> US pop singer Pink has backed down from her call to boycott Australian wool over animal cruelty claims, admitting she failed to fully research the issue.
>
> The singer, who has sold around 200,000 tickets for dozens of shows in her upcoming April tour of Australia, appeared in an animal rights group video last year branding the practice of sheep mulesing “sadistic”.
>
> But today, Pink admitted she was misinformed about the issue and had failed to do enough research.
>
> “I probably could have done a lot more research on my own,” she told the Nine Network.
>
> “That’s the lesson I’m taking from this.
>
> “My message was, in my mind, boycott animal cruelty - not an entire industry, not Australia, obviously, because it’s my favourite country.
>
> “Then going back, I was speaking without thinking and I actually did say ban Australia, which is bullshit. It’s not something that I can agree with.”
>
> Pink made the video as part of the US-based People for the Ethical Treatment of Animals’ (PETA) three-year campaign to end mulesing.

Sorry PETA, no refunds!
