---
title: "Pro-War Libertarians"
date: "2007-07-17"
categories: ["Economics", "Foreign Affairs & Defence"]
---

[Randy Barnett](http://online.wsj.com/article/SB118463507387568429.html?mod=opinion_main_commentaries "Randy Barnett") has a WSJ op-ed on libertarian approaches to war and self-defence, which is partly a response to Ron Paul’s lamentable performance in the Republican presidential candidate debates.  An unfortunate aspect of libertarianism and classical liberalism in the US is its continued fusion with Old Right isolationism, a phenomenon that is largely absent from these traditions outside the US.  As the lead-in to the op-ed notes, ‘first principles tell us little about what constitutes appropriate and effective self-defense.’  There are exceptions to these isolationist views, however, as Barnett notes:

> there are those pro-invasion libertarians who are now following the progress of Operations Phantom Thunder and Arrowhead Ripper. They hope that the early signs of progress in this offensive will continue, so that American and Iraqi forces can achieve the military victory necessary to allow the Iraqi government to assume responsibility for protecting the Iraqi people from terrorists, as well as from religious sectarian violence. They hope this success will enable American soldiers to leave Iraq even before they leave Europe and Korea, and regain the early momentum that led, for example, to Libya’s abandonment of its nuclear weapons program.
>
> These libertarians are still rooting for success in Iraq because it would make Americans more safe, while defeat would greatly undermine the fight against those who declared war on the U.S. They are concerned that Americans may get the misleading impression that all libertarians oppose the Iraq war—as Ron Paul does—and even that libertarianism itself dictates opposition to this war. It would be a shame if this misinterpretation inhibited a wider acceptance of the libertarian principles that would promote the general welfare of the American people.
