---
title: "Promises, Promises…Good Policy, Bad Strategy"
date: "2007-10-15"
categories: ["Economics", "Financial Markets", "Politics"]
---

The government [announces](http://www.theaustralian.news.com.au/story/0,25197,22587386-601,00.html "announces") \$34 billion in tax cuts, the day after calling the federal election for November 24:

> Treasurer Peter Costello has announced five years of progressive reductions of income tax that will see the current tax system eventually reduced to four tax brackets—15, 30, 35 and 40 cents in the dollar.
>
> The plan would see the tax-free threshold raised to \$14,000 next year, while the lowest tax rate would kick in on earnings over \$34,000.
>
> In following years, the top tax rates would be lowered while the tax-free threshold would be lifted again.
>
> Mr Costello has said the goal of the restructure was to arrive at a tax-free threshold of \$20,000 and for there to be only four marginal tax rates, with the top rate set at 40 cents in the dollar.
>
> The changes, to be introduced gradually, will see the tax threshholds for lower income earners increased and the reduction of the percentage of tax paid in the top two tax categories—currently 40 and 45 percent.

This is good policy, but bad political strategy.  These initiatives would have been much more credible had they been announced in the May Budget and legislated ahead of the election.  As things stand, they are just another campaign promise that the public is likely to treat with scepticism.  The electorate may even be resentful that it takes a federal election to induce good fiscal policy from the government. 

Moreover, should the government lose the election, the proposed tax cuts will give way to the as yet unannounced tax policy of the federal opposition.  The government runs the risk of bequeathing to the Labor Party the surpluses it has accumulated in the Future Fund and the other artificial lock-boxes it has used to warehouse revenue it doesn’t need to meet current expenditure commitments.

At least the government is ignoring the advice of the ‘tax cuts equals higher interest rates’ brigade.  No prizes for guessing what Chris ‘[Rainy Day](http://www.google.com.au/search?q=%22chris+richardson%22+%22rainy+day%22&hl=en&cr=countryAU&client=firefox-a&rls=org.mozilla:en-US:official&hs=9jI&pwst=1&start=0&sa=N "Rainy Day")’ Richardson will have to say about it.
