---
title: "‘Quiet Boom’ & ‘The Search for Stability’"
date: "2007-03-27"
categories: ["Economics"]
---

Former Prime Ministerial economic adviser John Edwards’ [Quiet Boom](http://www.lowyinstitute.org/Publication.asp?pid=506 "Quiet Boom") provides an account of the origins and consequences of the current unprecedented 16-year expansion of the Australian economy.  Former RBA Governor Ian Macfarlane’s [The Search for Stability](http://shop.abc.net.au/browse/product.asp?productid=163525 "The Search for Stability") is an overview of the post-war history of macroeconomic stabilisation policy, with particular reference to Australia.  Both Edwards and Macfarlane have been intimately involved in macroeconomic policymaking.  Yet on the defining event of Australia’s recent economic history - the recession of the early 1990s - they provide very different accounts.  Of these two interpretations, Edwards’ is the more compelling.

The strength of the Australian economy through the current expansion has been widely recognised, but few have documented its origins and implications as systematically as Edwards.  In particular, Edwards reviews some of the lesser known aspects of the expansion that speak to its profound implications for national welfare.  Not least, he quantifies how improved macroeconomic performance has translated directly into better living standards:

> Australians in 2005 consumed two-thirds more goods and services than they had at the beginning of the upswing.  This was a markedly faster rate of increase than in the fourteen years to 1991.  Real household consumption per head had increased 40%, nearly twice the gain in consumption per head in the earlier period…
>
> In 1994, one fifth of dwellings had four or more bedrooms, but over half the homes built in the decade to June 2004 had four or more bedrooms and the share had risen to over one quarter of all homes… In the four years to 2005 the number of passenger vehicles per 1000 population increased 6% and (unusually for Australia) the average age of the passenger vehicle fleet declined…
>
> real private wealth per person more than doubled between 1991 and 2004. (pp. 56-59)

These improvements are all the more dramatic when compared to Macfarlane’s account of life in early post-war Australia:

> *Hundreds of thousands of families moved into newly constructed housing, where the streets were not paved, footpaths non-existent, sewerage not connected and telephones unavailable.  The two- or three-bedroom cottage with an outdoor toilet was the norm, at least in the outer suburbs of Melbourne where I was brought up in the 1950s.  In many cases, schools were in temporary accommodation and there were very few universities.  We tend to forget how rough it was; in some ways it resembled the developing world more than the developed world of today.*

Those who now deride the growth in consumption and the alleged over-investment in housing would do well to recall the realities of life in less prosperous times.

This prosperity has its origins in the strong productivity growth over this period (the recent slowdown in productivity growth or ‘productivity puzzle’ notwithstanding). Edwards notes that between 1993/94 and 1998/99, the growth of output per hour worked averaged 3.2% a year, the most rapid rate between peaks of productivity growth in forty years of data (p. 41).  Through the current expansion, productivity growth contributed more than half of the total growth in output (p. 51).  As Macfarlane says, this was not just an impressive performance by Australian standards:

> *In late 2000, the US Federal Reserve Bulletin contained a paper that set out to explain the recent pick-up in US productivity and contrast it with the lacklustre performance in sixteen other OECD countries… but it kept finding an irritating exception to its general thesis: whether it was measuring the growth of labour productivity or multi-factor productivity, Australia either matched or exceeded the excellent US performance (p. 89).*

Edwards highlights numerous lesser known facts about the current expansion.  Real investment has reached a post-war record high as a share of output, largely accounting for the increase in the current account deficit, since national saving as a share of GDP (contrary to popular perception) has been stable.  The much maligned decline in the household saving ratio is largely due to an increased tax and mortgage interest share of household income.  The globalisation of Australian business has seen Australia become a net exporter of direct investment capital, with the stock of foreign assets recently growing faster than the stock of foreign liabilities.  Australian direct investment abroad is now three-quarters as large as the stock of foreign investment in Australia (p. 55).  This puts into proper perspective the habitual alarmism in relation to the current account deficit.

Edwards downplays the role of the commodity price boom and China, pointing out that mining accounts for only five percent of output, while exports to China account for only two percent of GDP.  Edwards also finds the performance of Australian export volumes disappointing, but this is offset by higher export prices.  Even export volumes can be expected to improve as investment in the mining industry, which has seen real annual growth rates as high as 100% in recent quarters, starts to yield higher production.  Since Australia imports more from China than it exports to it, measured GDP growth does not adequately capture China’s contribution to national welfare.  The gains are largely through higher export prices, lower import prices and thus increased national purchasing power, which accrues to national income, but tends to weigh on measured GDP growth due to the substitution of cheaper imports for domestic production.  This in turn largely accounts for the ‘productivity puzzle,’ which Australia shares with other countries benefiting from positive terms of trade shocks.

Edwards gives credit for the growth in productivity to two related factors: deregulation and globalisation.  While this is a familiar story, Edwards put these developments in a broader historical context.  He sees the AIRC decision of 1991 to shift to enterprise bargaining as critical to the subsequent growth in productivity, saying that ‘it completed the removal of an impedient which had hindered Australian output growth for a quarter of a century’ (p. 33).  It was the confluence of domestic reform increasing Australia’s exposure to a new wave of globalisation that accounts for the strength and persistence of the current expansion.  In many ways, this was simply a return to a previous era of free trade and globalisation at the end of the 19th century, before the disastrous inward turn of the Federation ‘settlement.’  In the late 19th century, Australia was even more open to the global economy, the current account deficit and net capital inflow were an even larger share of GDP than today (p. 77) and Australia enjoyed some of the world’s highest living standards.

Edwards is optimistic on the economic outlook, saying ‘there is no compelling reason to believe Australia will not record a twenty year expansion, and perhaps longer’ (p. 15).  Edwards notes the familiar challenges presented by an aging population and the recent moderation in productivity growth.  It is at this point that Edwards takes a curious turn.  Having shown the enormous benefits from previous reform efforts, he argues that, in future, ‘Australian success in increasing output and incomes per head will thus depend much more on advances in the technological frontier of the global economy and much less on internal reform’ (p. 88).  He argues that ‘the gains from more market reforms maybe worthwhile but will be marginal’ (p.  viii).  This partly reflects his view that ‘many of the enhancements in productivity allowed by changed labour organisation \[are\] now fully exploited’ (p. 14).  In fact, Australia’s labour market is still highly regulated, suggesting that potential gains have been far from fully realised.  Edwards also argues:

> *it may well be worthwhile to reduce the top marginal income tax rate, or to encourage more workforce participation by older Australians or to increase the incentives to move from social security support to paid employment…  All of these reforms would help, but none will contribute to a significant change in the rate of growth of output per hour worked (p. 88)*

This is a strong claim, for which Edwards offers no real support.  In fact, there are good reasons for thinking that the gains from further reform could be large, not least because of the evidence Edwards presents in relation to the benefits from previous reform efforts, but also because we would expect these benefits to compound over time.

Instead, Edwards argues for the ‘increasing importance of education, training, innovation and research and development’ (p. viii), themes also currently strongly favoured by the federal opposition Labor Party.  Historically, the returns to public policy initiatives in these areas have been disappointing and Edwards doesn’t provide any evidence to suggest that they would deliver anything like the benefits associated with past microeconomic reform.  Indeed, Edwards provides evidence against this view when he notes that the Keating government’s ‘One Nation’ initiatives of the early 1990s had ‘little apparent impact’ (p. 34).  Edwards notes that ‘at the beginning of the upswing market disciplines, deregulation and “economic rationalism” were widely questioned.  Fifteen years on, there is no call to go back’ (p. 98).  But Edwards does not present a compelling call to go forward either.  Edwards’ rightly emphasises the importance of enhancing future productivity growth, but in the end has few practical suggestions to sustain the gains of the last decade and a half, other than the empty cargo cult-like mantras of the education, infrastructure and R&D lobbies and the federal opposition.

Edwards and Macfarlane are in substantial agreement on the benefits of previous structural reform efforts in sustaining the length of the current expansion.  But they are in sharp disagreement over what is perhaps the defining event of Australia’s recent economic history - the recession of the early 1990s.  The origins of the early 1990s recession and role of monetary policy have been the subject of a highly politicised debate, one that began even before the recession itself.  Macfarlane’s Boyer Lectures gloss over the role of the Reserve Bank in the recession, an issue over which Edwards takes Macfarlane to task.

Macfarlane lays the blame for the recession squarely at the feet of ‘the financial excesses of the 1980s’ (p. 56).  He acknowledges the debate about the role of monetary policy in the recession, but misrepresents the nature of this debate when he says ‘the issue is whether monetary policy was tightened excessively and whether this is what caused the 1990s recession’ (p. 61).  Yet Macfarlane’s own evidence contradicts this view.  He says in relation to the RBA, Treasury and the Treasurer that ‘no-one involved disputed the need to raise interest rates to the high level they reached in 1989 and no-one argued for an earlier reduction from 1990 onwards.  None of the three parties had sought to disassociate themselves from the monetary policy that was pursued through the period’ (p. 65-66).  He also says that ‘to the extent that there was a failure of monetary policy, it was not due to the traditional problem of the government and the central bank being unwilling to take tough measures, but was instead due to a failure to understand the implications of a sudden financial deregulation’ (p. 54).  While there was certainly a political debate over interest rates at the time, then opposition leader John Hewson generally criticised interest rate reductions as being symptomatic of lack of Reserve Bank independence.  The issue was thus not the relative tightness of policy, but why such a restrictive policy stance was widely thought to be necessary.

Macfarlane tries to argue that the recession of the early 1990s and the subsequent disinflation were analogous to the ‘Volker disinflation’ in the US in the early 1980s.  Whereas the US episode was rightly considered a success, Macfarlane notes that in Australia, the early 1990s recession was seen, unjustly in his view, as a policy failure.  Yet there is an important difference between these two episodes.  The Volker disinflation was a deliberate policy to return the US to low and stable inflation.  In Australia, the recession and subsequent disinflation were partly a policy mistake, with costs that would never have been viewed as acceptable had they been known in advance.  Macfarlane acknowledges this when he says ‘I do not want to give the impression that policymakers knew exactly what was happening and were in control throughout.  We did not set out to have a recession in order to reduce inflation’ (p. 70). 

Edwards is dismissive of Macfarlane’s comparison with the Volker disinflation:

> *This interpretation of the period seems to me quite wrong…. For some of the key players the tightening of monetary policy was not mainly about inflation.  The Reserve Bank officially claimed in its 1988 annual report that the tightening began as a response to higher imports threatening ‘the improving trend in the balance of payments’, as well as a response to growth in earnings and prices threatening ‘the downward trend in inflation’. So far as Treasurer Paul Keating and his cabinet colleagues were concerned, the policy objective was not inflation so much as the current account deficit. This objective made the tightening episode vastly more difficult because after a period of stability the current account deficit began to widen again. In the mid eighties Prime Minister Bob Hawke and Treasurer Paul Keating had used the rising current account deficit to illustrate the necessity of faster economic reform. In doing so they made the size of the current account deficit a test of economic success. As Keating would later remark, the government was ‘hoist on its own petard’ by the sudden widening of the deficit in the late nineteen eighties. When it began to increase with rising business investment, they were convinced that it must be narrowed by slowing domestic demand. What began mildly enough with ‘the sound of a harp’ became a struggle to rein in the current account deficit before the next election… The political and economic impact of the subsequent recession was conditioned by the fact that it began after the Reserve Bank had began to cut interest rates. (pp. 28-30)*

Edwards’ point about the current account is an important one.  Macfarlane also notes that:

> *The risk that worried most observers was the large deficit on the current account or the balance of payments, and the associated build-up of foreign debt. Most politicians, businesspeople, economists, journalists, and the community in general, regarded this as public economic enemy No.1. (p. 50).*

He neglects to mention that this was a view fully shared by the Reserve Bank at the time, with the disastrous consequences noted by Edwards. 

The underlying issue in relation to the conduct of monetary policy in the late 1980s and early 1990s was thus not about whether policy was too tight or too loose, as Macfarlane tries to suggest, but the framework within which monetary policy was conducted.  As Macfarlane himself notes ‘on the right, there was a call for…  major institutional changes, especially in relation to monetary policy’ (p. 77).  The critics of the RBA at the time argued that Australia had such high interest rates because monetary policy lacked coherence and credibility.  A sense of the extent to which Australian monetary policy had been discredited can be had from the titles of various think-tank publications at the time:  *Do We Need a Reserve Bank?* (CIS, 1990); *Can Monetary Policy be Made to Work?* (IPA, 1992).  Macfarlane muddies the waters by noting the ‘exotic’ arrangements such as currency boards and commodity standards that were floated by the RBA’s critics, but the fact that such arrangements were being seriously discussed reflected a view that only radical institutional reform could establish credibility for Australian monetary policy given the failure of existing institutional arrangements.  This view ultimately proved too pessimistic, but was understandable at the time.  Macfarlane says that ‘on the subject of the ultimate objective of monetary policy, both economic theory and experience of the past sixty years were clear that it should be the rate of inflation’ (p. 80), yet this view did not come to be fully reflected in the conduct of Australian monetary policy until well into the 1990s. 

Macfarlane himself effectively acknowledges this critique when he notes that one of the main factors behind the asset price boom and bust of the late 1980s was ‘the persistence of high inflation expectations (p. 51)…I certainly thought that the excessive speculative activity in Australia in the late 1980s was partly caused by the fact that inflationary expectations had not yet been brought down to a low level’ (p. 109).  But Macfarlane avoids making the direct link between inflation expectations and the credibility of monetary policy, treating the former almost as if they were an exogenous given, rather than a function of the institutional arrangements for monetary policy.  Only later does he concede that the ‘the second important lesson that was learnt was that a better framework for demand management, particularly better monetary policy, was the key to a better inflation outcome’ (p. 74).  This is about as close as Macfarlane comes to acknowledging past monetary policy failures.  He goes on to note the evolution of inflation targeting, first with the then federal opposition Coalition’s proposal to legislate for an inflation-targeting central bank, Governor Bernie Fraser’s stealth adoption of inflation targeting after 1993 federal election, and finally with the 1996 Joint Statement on the Conduct of Monetary Policy.  Whereas previous approaches to monetary policy ‘lived dangerously and died young’ (Lomax, 2007. p. 1), the Joint Statement and its successors have now governed Australian monetary policy for 10 years and have been associated with a vast improvement in macroeconomic outcomes.  At the same time, Macfarlane and Treasurer Costello failed to reform the statutory basis for Australian monetary policy governance.  Despite some significant improvements, the RBA still lacks many of the rigorous accountability and transparency mechanisms that were introduced in conjunction with statutory reform of central banking institutions in other countries (Kirchner, 2004).  Macfarlane notes that it was not until 1996 that Australian bond yields fell below those in New Zealand (p. 87-88), further evidence for the view that Australian monetary policy lacked credibility until well into the mid-1990s.  It is noteworthy that the chart of the spread between Australian and New Zealand bond yields Macfarlane offers to illustrate this observation shows Australian yields once again approaching parity with New Zealand as Australian inflation outcomes deteriorated in 2006.

It is thus not true to say, as Macfarlane does, that ‘the issue of how monetary policy could have been conducted in the 1980s will probably never be resolved’ (p. 54).  It was resolved decisively in favour of inflation targeting, a policy framework fully embraced only belatedly by the Reserve Bank and in a manner that still falls short of world’s best practice in monetary policy governance (Kirchner, 2004).  The evolution of Australian monetary policy has vindicated the RBA’s critics from the late 1980s.  Australian monetary policy and macroeconomic outcomes are not just accidents of history.  As both Edwards and Macfarlane show, with varying degrees of explicitness, institutional arrangements and the ideas underpinning them have important implications for macroeconomic performance and national welfare. 

**References:**

Economic Policy Unit (1992) *Can Monetary Policy be Made to Work?*  Papers presented at the Institute of Public Affairs Monetary Policy Conference.  IPA: Melbourne.

Kirchner, S. (2004) ‘The Mandarins of Martin Place,’ *Policy*, 20(3): 53-56.

Lomax, R., (2007) *The MPC Comes of Age*, Speech by Rachel Lomax at the De Montfort University, Leicester.  28 February 2007.

White, L., C. Jones and B. Wilkinson (1990)  *Do We Need a Reserve Bank?* CIS: Sydney.
