---
title: "RBA Reform Under Rudd?"
date: "2007-10-30"
categories: ["Economics", "Financial Markets", "Politics"]
---

Opposition Treasury spokesman [Wayne Swan](http://www.smh.com.au/news/National/Labor-may-open-RBA-appointments/2007/10/30/1193618859567.html "Wayne Swan") flags possible changes to the appointment process for the RBA Board under a prospective Labor Government:

> “I am very interested in talking to the reserve bank governor about a new method, open and transparent, of appointing the best possible person available.”
>
> Mr Swan said he would seek the advice of current reserve bank governor Glenn Stevens to discuss ways of implementing a more transparent appointment process.
>
> “I would seek the advice of the current reserve bank governor in constructing a process that would do that,” Mr Swan said.
>
> “We have a number of ex-reserve bank governors around the country, maybe we can put a panel together where they could put together a list of names, for example.
>
> “I want an open transparent process that gives the best person for the job, irrespective of their political affiliation or what fundraising they have done for any political party.

Instead of overhauling the appointments process for the Board, a more significant reform would be to bring the RBA into line with the practices of other central banks and separate monetary policymaking from the Board and place it into the hands of an expert committee, made up of the Bank’s senior officers and outside appointees and excluding the Treasury Secretary.  The monetary policy committee should then be required to release a summary of proceedings and a record of any votes taken at the conclusion of each meeting.  By ensuring a high degree of transparency, there is less of a burden on the appointment process in maintaining the integrity of monetary policy, since the behavior of committee members would be subject to a degree of scrutiny that is entirely absent under current arrangements.
