---
title: "Ron Paul’s Oath"
date: "2007-11-16"
categories: ["Politics"]
---

[John Fortier](http://www.aei.org/publications/filter.all,pubID.27105/pub_detail.asp "John Fortier") calls on US Presidential candidate Ron Paul to uphold his oath of office:

> Last week the media found it remarkable that Ron Paul raised \$4.3 million in one day. But even more remarkable was the way that it was raised. Groups of Paul supporters scheduled a mass Internet fundraiser on Guy Fawkes Day.
>
> Guy Fawkes was the chief plotter in an effort to blow up the British Houses of Parliament and kill the king on Nov. 5, 1606. Nov. 5 also figures prominently in last year’s movie “V for Vendetta,” about a modern Guy Fawkes-inspired rebel who fights against a fascist British government. The fundraising website was ThisNovember5th.com, which includes clips of Paul warning of a descent into military government. The not-so-subtle message is that America is close to a dictatorship and that extreme and violent measures are needed to combat the government.
>
> A Paul spokesman backed off the most egregious rhetoric by noting that he did not favor blowing up government buildings. Instead, Paul “wants to demolish things like the Department of Education, but we can do that very peacefully, in a constructive manner.” These words are a welcome corrective, but Paul still pocketed the money.
>
> Ron Paul is a fringe presidential candidate, but he is also a sitting member of Congress who has sworn an oath to uphold the Constitution and the institution of Congress. Trafficking with those who hint at the violent overthrow of Congress is no way to honor that oath. Give the money back.
