---
title: "Rudd as ‘Unreconstructed Interventionist’"
date: "2007-10-23"
categories: ["Economics", "Politics"]
---

[Sinclair Davidson and Alex Robson](http://online.wsj.com/article/SB119308758819967520.html?mod=opinion_main_europe_asia "Sinclair Davidson and Alex Robson") argue in a WSJ op-ed that federal opposition leader Kevin Rudd is a thinly disguised economic interventionist:

> a closer look at Mr. Rudd’s record reveals that he’s not a reformer, but rather an unreconstructed interventionist masquerading as a free market conservative. Call it “Ruddonomics.”
>
> Take his parliamentary record, for a start. Since coming into the Parliament in 1998, Mr. Rudd has toed the party line and opposed most efforts to further reform the economy. The Australian Labor Party opposed the privatization of Australia’s government-owned telecommunications provider, Telstra; strongly protested industrial relations reform, including Mr. Howard’s recent efforts to reduce union power and abolish unfair dismissal laws; and, most importantly, opposed all significant tax reform over Mr. Howard’s tenure, including cuts in income taxes.
>
> Mr. Rudd’s economic philosophy isn’t a secret. In a speech to the free market Center for Independent Studies in Sydney last year, he openly attacked the free market ideas of Nobel Laureate Friedrich Hayek, branding him a “market fundamentalist.” In Mr. Rudd’s mind, it’s okay to accept “the economic logic of markets but . . . these must be properly regulated and that the social havoc they cause must be addressed by state intervention.” He also argued that public policy should deliver long-term market-friendly reform tempered by “social responsibility.”
