---
title: "Running the CPI-Interest Rate Gauntlet"
date: "2007-10-02"
categories: ["Economics", "Financial Markets", "Politics"]
---

The failure of the Prime Minister to visit Yarralumla over the weekend means that he chosen to run the gauntlet of the Q3 CPI at the end of October and the November meeting of the RBA Board.  [Terry McCrann](http://www.news.com.au/heraldsun/story/0,21985,22515356-5000117,00.html "Terry McCrann") has been highlighting the implications:

> JOHN Howard has ignored the ‘message’ from Reserve Bank governor Glenn Stevens, first ‘revealed’ in these columns on August 14.
>
> That he should consider, seriously consider, holding the election on October 20.
>
> After ‘sitting out’ a trip to Government House in Canberra on Sunday, literally at Telstra stadium in Sydney, the earliest practically the election can now be held is November 10.
>
> Why should he have considered that Saturday in October? Because it came before the next official inflation figures, released on Wednesday October 24.
>
> And Stevens had made it absolutely crystal clear in the RBA’s quarterly monetary statement in mid-August that if it was a bad inflation number, the RBA would lift rates again in November.

Here is what Glenn Stevens said on the subject at his last [appearance](http://www.aph.gov.au/hansard/reps/commttee/R10393.pdf "appearance") before the House Economics Committee:

> *If it’s clear that something needs to be done, I don’t know what explanation we can offer to the Australian public for not doing it.  I don’t think there’s any case for the Reserve Bank board to cease doing its work in the month the election is going to be.  I doubt that members of the public would see that as appropriate.*

Of course, it is by no means obvious that having interest rates front and centre in an election campaign is a negative for the government.  But having decided to run the gauntlet, the risk of an interest rate rise argues for an election at the end rather than the beginning of November.
