---
title: "Sachs Sucks"
date: "2007-04-17"
categories: ["Economics", "Financial Markets"]
---

[Daniel Ben-Ami](http://www.spiked-online.com/index.php?/site/article/3081/ "Daniel Ben-Ami") on Jeffrey Sachs’ Malthusianism:

> For Sachs, the key problems facing the world today are rooted in overpopulation: ‘Our generation’s unique challenge is learning to live in an extraordinarily crowded world.’ He argued that the world is ‘bursting at the seams in human terms, in economic terms and in ecological terms’. So for Sachs every human being is, literally and metaphorically, another mouth to feed. The mass of humanity is leaching the planet of its resources and destabilising the world. He grossly underestimates the significance of humans having hands and brains, as well as mouths. Rather than simply consuming resources, humans have the unique ability to produce more than their own subsistence and to transform the environment for the better.
>
> Sachs breaks this supposed problem of overpopulation into three inter-connected challenges. First, there is what he calls the Anthropocene: ‘the idea that for the first time in history the physical systems of the planet…are to an incredible and unrecognised extent under human forcings.’  In other words, for Sachs the fact that humanity now has a significant degree of control over nature, one of the great achievements of progress, is a threat. Rather than having the potential to liberate humanity, he sees scientific and technological advance as destabilising the planet.
