---
title: "Should Greenspan Blog?"
date: "2007-03-13"
---

[Kevin Hassett](http://www.aei.org/publications/filter.all,pubID.25745/pub_detail.asp "Kevin Hassett") makes the case for Greenspan to turn blogger:

> Greenspan needs to enter the information age he has spoken so wisely about in the past. He needs to start a blog.
>
> Think of it. He could post for all the world to see, his latest assessment of the state of the economy, including the detailed analysis of motor-vehicle scrappage and other arcana that colored his tenure as Fed chairman.
>
> To protect himself against the appearance of impropriety, he could draw on the blog when he speaks publicly, and fully inoculate himself against harmful accusations. He could even sell advertising.
>
> Greenspan is in a unique position to help Americans understand the economy they live in better. It would be a shame for him to retreat into the shadows after a bad week of publicity. The fact is, his opinions need more visibility, not less.

With Greenspan’s memoirs to be published in the not too distant future, a marketing blog would not be surprising.  Afterall, the publisher has an \$8.5 million advance to recoup.  Somehow, I don’t think Greenspan will need the Google ads revenue.

The Hong Kong Monetary Authority’s Joseph Yam maintains [a blog of sorts](http://www.info.gov.hk/hkma/eng/viewpt/index.htm "a blog of sorts").
