---
title: "State Capitalism: The Rise of Sovereign Wealth Funds"
date: "2007-11-03"
categories: ["Economics", "Financial Markets"]
---

[Alan Wood](http://www.theaustralian.news.com.au/story/0,25197,22693222-31478,00.html "Alan Wood") discusses some of the issues around the emergence of sovereign wealth funds, including Australia’s Future Fund:

> An emerging theme in international discussion is the return of state capitalism. After decades of privatisation and the retreat of government from state ownership of enterprises, sovereign governments are becoming a major force in global asset markets…
>
> Although most Australians don’t realise it, Peter Costello’s Future Fund, perhaps soon to become Kevin Rudd’s plaything, is a sovereign wealth fund. And in a world where the lack of transparency and accountability of sovereign wealth funds is a major concern, it is open to criticism…
>
> Their assets are already larger than hedge funds (\$US1 trillion to \$US1.5 trillion) and private equity funds (\$US700 billion to \$US1.1 trillion).
>
> And their assets are growing rapidly.
>
> Standard Chartered estimates they could total \$US13.4 trillion in a decade. They already hold over 1 per cent of the world’s total stock of equities, bonds and bank deposits and could hold 5 per cent or more of the global stock of financial assets in a decade.
