---
title: "Tax Cuts and Interest Rates - Again"
date: "2007-10-27"
categories: ["Economics", "Financial Markets", "Politics"]
---

[Terry McCrann](http://www.theaustralian.news.com.au/story/0,25197,22654909-14743,00.html "Terry McCrann") continues to do battle with the ‘tax cuts lead to higher interest rates’ brigade:

> what would have happened if the Government had taken the advice of, in particular, Access Economics and tried to bank them.
>
> Since that 2005 budget which projected a \$9 billion 2008-09 surplus—itself after spending \$10 billion in the 2008-09 year. That’s to say, the projected 2008-09 deficit even back then could have been \$19 billion but for the 2005 tax cut.
>
> Since then the Government has spent a further \$50 billion, in the 2008-09 year alone. If not spent, ceteris paribus it would now be projecting a \$63 billion surplus for that one year. With similar huge surpluses for this year and the other years in the budget forecasting framework…
>
> Macquarie Bank’s Rory Robertson seems to think he’s rediscovered the fiscal wheel, by arguing that the tax cuts have been fiscally stimulatory.  Well, looked at in isolation, of course they are, Rory. Looked at in the totality of revenue change from one year to the next, not having them would have been contractionary.  If you think going from a \$15 billion surplus in 2005-06 to a \$63 billion surplus in 2008-09 would equate to fiscal neutrality, Rory, we will have to agree to disagree.
>
> Interest rates are as high as they are, and heading slightly higher, not fundamentally because of the tax cuts, but because of the seminal upshift in our prosperity of which the surging budget revenues that fund the tax cuts are the manifestation.

McCrann argues that ‘analytically it is beyond absurd to suggest the Government could have in theory sat on a \$63 billion surplus.’  Indeed, with Commonwealth debt paid off, the government would have little choice but to recycle these surpluses via the accumulation of assets in the Future Fund.  Unless the bulk of these funds were invested offshore, the government would over time effectively nationalise a large share of the domestic stock of equity capital.
