---
title: "That 1969 Feeling"
date: "2007-11-22"
categories: ["Economics", "Financial Markets", "Politics"]
---

[Matthew Johnson](http://www.businessspectator.com.au/bs.nsf/Article/SCOREBOARD-Sell-Australia-96SGG?OpenDocument "Matthew Johnson") argues that financial markets should be getting nervous ahead of this weekend’s federal election in Australia:

> *It’s starting to feel a little bit like Florida 2000 to me. It’s perfectly possible for the Coalition to win in court (Newhouse’s invalid nomination) and to do so with a minority of the vote. Given this risk, I’d sooner not go home long AUD or Aussie equities on Friday – no decision creates complications in all sorts of places (FIRB for example), and it’d be a clear ‘sell Australia’ signal.*

Instead, I would suggest it is starting to feel like 1969, when the Labor Party secured its largest post-war two-party preferred swing of 7.1% and a majority of the national two-party preferred vote, yet failed to secure a majority in the House of Representatives.  Indeed, 21% of post-war elections have been won on a minority of the two-party preferred vote (1954, 1961, 1969, 1990 and 1998).

Amid broad-based USD weakness, the Australian dollar has been a notable underperformer in the run-up to the election.  Recent AUD weakness reflects flight from currencies with negative net international investment positions in favour of the Japanese yen.  But the AUD has also underperformed those currencies with which it is traditionally highly correlated.  AUD-EUR has broken below multi-year trendline support from the October 1998 monthly lows.  AUD is also underperforming its commodity bloc peers NZD and CAD, with AUD-NZD slipping to lows of 1.1529, levels not seen since late August, while AUD-CAD fell to a low of 0.8540, below the highs for the year at 0.9512.  Weakness in base metals prices is the most likely explanation for the underperformance of AUD.  But this weekend’s federal election and the risk of a hung parliament may also be playing a role.
