---
title: "The Dynamic Benefits of Tax Cuts"
date: "2007-11-21"
categories: ["Economics", "Financial Markets", "Politics"]
---

[Alan Wood](http://www.theaustralian.news.com.au/story/0,25197,22793430-7583,00.html "Alan Wood"), on why fiscal policy should not be used for demand management:

> fiscal policy has a higher purpose than keeping interest rates at politically comfortable levels. Would we really be better off, as the Government’s critics suggest, with budget surpluses of 3 per cent, 4 per cent, or 5 per cent of gross domestic product and lower interest rates?
>
> The answer is no. The appropriate role of fiscal policy is to redistribute the revenue windfall from the China boom in economically productive ways, and tax cuts meet this criterion admirably. If this leads to higher interest rates than otherwise, so what?
>
> At worst the contribution is marginal compared with the other forces at work on the economic cycle, and the dynamic economic benefits exceed the costs. For most of the past five years, according to the RBA, fiscal policy has had no impact on monetary policy.
>
> And according to analysis by IPAC’s Johnson, even under the extreme assumption that the tax cuts were entirely responsible for the interest rate rises that did take place, the economy-wide benefits exceeded the cost by several billion dollars.
>
> Howard and Costello’s mistake has not been their tax cuts, but the fact they didn’t deliver more vigorous tax reform earlier in the economic cycle, before the economy ran up against capacity constraints.

As we [noted](../2007/promises_promisesgood_policy_bad_strategy.qmd "noted") at the beginning of the election campaign, Federal government revenue hoarding has also been bad political strategy.  The government’s campaign promises in relation to further tax cuts would have been much more credible had they been announced in the May Budget and legislated ahead of the election campaign.  As things stand, the tax cuts were a one day wonder, long since forgotten amid all the election campaign trivia.
