---
title: "The Euro’s Day Will Not Come"
date: "2007-12-19"
categories: ["Economics", "Financial Markets"]
---

[Adam Posen](http://www.petersoninstitute.org/publications/opeds/oped.cfm?ResearchID=853 "Adam Posen"), on why recent strength in the euro does not herald its rise to greater international status:

> So a strengthening of the euro against the dollar, even for several months in a row, is not indicative of a decline in the dollar’s global role and usage, or for that matter much of anything else. People started talking about a move away from the dollar in the 1970s when US long-term economic prospects were far more uncertain relative to Europe and Japan than they are now compared even to China—and nothing happened in terms of a decline in the dollar’s global role…
>
> No one should read too much into exchange rate swings, including the recent decline of the dollar against the euro. It takes much more than such a depreciation to cause a shift in reserve currency status. The euro may someday play a global role beyond its current use, but until the eurozone’s financial markets integrate, its sustainable growth rate rises, and its willingness to import increases, that day will not come.
