---
title: "‘The Most Important Novel of the 20th Century that was Never a Film’"
date: "2007-01-12"
categories: ["Culture & Society"]
---

The [IHT](http://www.iht.com/bin/print.php?id=4168964 "IHT") on Atlas Shrugged - The Movie:

> Randall Wallace, who wrote “Braveheart” and “We Were Soldiers,” is working on compressing the nearly 1,200-page book into a conventional two- hour screenplay. Howard and Karen Baldwin, the husband-and-wife producers of “Ray,” are overseeing the project, and Lions Gate Entertainment is footing the bill.
>
> Whether Jolie, who has called herself something of a Rand fan, will bring the novel’s heroine, Dagny Taggart, to life on screen, or merely wind up on a list with other actresses who sought or were sought for the role remains to be seen. Until now, at least, no one in Hollywood has figured out a formula that promises both to sell popcorn and to do justice to the original text, let alone to the philosophy that it hammers home endlessly, at times in lengthy speeches. (The final one is 60 pages long.) But Baldwin said he believed that Wallace and the rest of their team were up to the task. “We all believe in the book, and will be true to the book,” he said…
>
> As for how he is distilling Rand’s novel to a two-hour screenplay, Wallace insisted he had the material under control and was on course to deliver a draft this month.
>
> “I can pretty much guarantee you that there won’t be a 30-page speech at the end of the movie,” he said. “I have two hours to try to express what Rand believed to an audience, and my responsibility is not only to Ayn Rand, but to the audience, that this be a compelling movie. More people will see the movie than will read ‘Atlas Shrugged.’ And the movie has to work.”
