---
title: "The Failure of Earth Hour"
date: "2007-04-18"
categories: ["Culture & Society", "Economics"]
---

[David Solomon](http://home.uchicago.edu/~dsolomo1/EarthHour.pdf "David Solomon") of UC GSB estimates the effects of Earth Hour:

> On March 31 at 7:30pm, the residents of Sydney, Australia, held an ‘Earth Hour’, where people were urged to turn off their lights and electrical appliances for one hour. According to poll evidence, over 57% of Sydney took part. To estimate the impact of this event, simply measuring the difference between actual consumption and predicted consumption (as media reports did) gives an incorrect inference, because over 67% of the apparent decline was due to factors common throughout the day, not just ‘Earth Hour’. Once this is controlled for, ‘Earth Hour’ shows a decline of only 2.10%, statistically indistinguishable from zero. Declines as large as those during ‘Earth Hour’ were actually observed throughout the day, starting as early as 5am, suggesting that the gap in consumption is due to omitted variables, not the event itself. The size of the drops is also small within the sample – ‘Earth Hour’-sized drops in electricity consumption actually occur on average every four days. In terms of reducing electricity consumption, ‘Earth Hour’ was, statistically speaking, a failure…
>
> Taking the point estimate of the EarthHour Dummy variable in the full specification after controlling for EarthDay fixed effects, the estimated impact of half of Sydney apparently sitting in darkness using no appliances was to reduce statewide electricity use by around 2.1%. This is a useful, albeit rough, example of the potential economic cost of some currently debated policies that seek to reduce Australian greenhouse gas emissions by 60% by the year 2050.

Of course, the opinion poll results probably grossly overstate participation in Earth Hour, given the levels of fear and loathing generated by climate change hysteria.
