---
title: "The Adam Smith Institute Celebrates Big Government Conservatism"
date: "2007-09-07"
categories: ["Economics"]
---

A rather bizarre [post](http://www.adamsmith.org/blog/index.php/blog/individual/libertarians_should_celebrate_small_government_australia/ "post") at the Adam Smith Institute blog, which (I suspect unwittingly) seeks to defend Treasurer Costello against his classical liberal critics in Australia:

> *Ahead of the upcoming general election (in about two months time) journalists have claimed that the coalition government of John Howard has turned to big government. However, his Treasurer, Peter Costello, in a [blog-style response](http://www.cis.org.au/policy/winter07/links/winter07_costello.html "blog-style response"), crushed this sophisticated distortion of facts and demonstrated that the opposite is true: government spending as a proportion of GDP has actually gone down from 26.1 percent to 25.2 percent over the last ten years. According to him the main factor is the reduction of interest payments for government debts, which the political writers try to belittle.*

Not just journalists or political writers.  The main criticisms of Costello’s fiscal policy have in fact come from classical liberals, who rightly point out that the numbers quoted by Costello are all but meaningless.  Costello’s article was a rather lame response to an [article](http://www.cis.org.au/policy/summer_06/polsummer06_norton.htm "article") in previous edition of Policy.  See also Andrew Norton’s subsequent [response](http://www.cis.org.au/policy/winter07/links/winter07_norton.html "response") to Costello. 

Treasurer Costello can’t be too proud of his government’s record on fiscal policy, given his willingness to [shirk cabinet responsibility and attack the Prime Minister](http://www.abc.net.au/worldtoday/content/2007/s1982600.htm "shirk cabinet responsibility and attack the Prime Minister") over the government’s spending record.
