---
title: "The Andy Xie Club"
date: "2007-05-02"
categories: ["Economics", "Financial Markets"]
---

Andy [‘These Western People Didn’t Know What They Were Talking About’](../2006/these_western_people_didnt_know_what_they_were_talking_about.qmd "‘These Western People Didn’t Know What They Were Talking About’") Xie is [back on the loose](http://www.reuters.com/article/reutersEdge/idUSSIN15117620070430?pageNumber=1 "back on the loose"):

> Xie told Reuters that he plans to set up an “investment club” that would be **open only to people he knows**. The club would invest in unlisted firms, would have total funds of \$200 to \$300 million and would be focused solely on China.
>
> “I’m looking for backers who know me, so there’s a trust element involved and that would make decisions much easier,” he added.
>
> Xie—who worked at Morgan Stanley for nine years and spent five years as an economist with the World Bank—resigned from the U.S. investment bank after an email with disparaging comments about Singapore’s economic policy was leaked to the public.
>
> His email was written shortly after the IMF/World Bank meetings in Singapore in September.
>
> Xie declined to elaborate on his departure, but said he was already considering resigning from the bank before then.
>
> He added that he would not join another firm again and does not rule out heading his own fund in future. He sees himself traveling around China, dispensing economic advice.
