---
title: "The Understrength RBA Board"
date: "2007-02-13"
categories: ["Economics", "Financial Markets"]
---

Treasurer Costello [continues to neglect](http://www.theaustralian.news.com.au/story/0,20867,21216318-2702,00.html "continues to neglect") his portfolio responsibilities:

> PRESSURE is mounting on Peter Costello to appoint a new deputy governor of the Reserve Bank amid unease in the markets and internally at the length it is taking to beef up the under-strength board…
>
> And with an election due this year, there is a risk that further extended delays could politicise new appointments…
>
> It is now five months since deputy Glenn Stevens succeeded Ian Macfarlane as Governor. But the wait to replace controversial independent member Robert Gerard has blown out to 14 months…
>
> Mr Costello raised eyebrows last year when he said he would look for internal and external candidates to fill the deputy role. But private-sector economists believe any of the three leading internal contenders are more than capable and are puzzled as to why it is taking so long.
>
> A spokesman for Mr Costello said: “The Treasurer has indicated that he will look externally and internally at all the best candidates and that is what is going on.”
>
> Leading contenders for deputy governor are assistant governors Ric Battellino, 55, Malcolm Edey, 47, and Philip Lowe, 45.
>
> There have been rumours Mr Costello could appoint a senior bureaucrat from Treasury to join Treasury Secretary Ken Henry on the board. But recently that rumour mill has slowed. Treasury executive directors Martin Parkinson and Mike Callaghan have been touted as candidates.
