---
title: "The Declining Relevance of the Word Bank"
date: "2007-04-20"
categories: ["Economics"]
---

Former World Bank executive director [Robert Holland](http://online.wsj.com/article/SB117703693772776487.html?mod=opinion_main_commentaries "Robert Holland") on the declining relevance of the World Bank:

> Regardless of the fates of Mr. Wolfowitz and the anticorruption initiative, the Bank faces an existential financial problem because of the combined effect of its declining relevance and attractiveness as a funding source for many middle-income countries like China, India, Mexico and Russia, and an annual administrative budget exceeding \$1 billion. It’s a positive development that many countries no longer are dependent on Bank lending, but the income consequences to the Bank need to be addressed because the administrative budget is a serious burden on the world’s poor and donor taxpayers.
>
> The most important cost drivers are staff salaries and headcount, and it is here where some of the most pernicious effects of the staff association’s union characteristics are felt. Over the years, the Bank’s legal department has constructed a complex set of rules and procedures governing employment practices, particularly terminations, designed to avoid a court of law somewhere imposing something more onerous in the name of “due process.”
>
> The unfortunate result is a system of such Dickensian complexity that virtually all bank managers have concluded that no one can be fired. This, and the tendency of many Board members to intervene in individual cases to protect or promote their nationals, has resulted in far too many employees, many of whom are widely viewed as incompetent, and costly salaries and severance packages (compared to which Ms. Riza’s package is a pittance).
>
> Other unfortunate results are an unreasonably low mandatory retirement age of 60 and the retention of an army of consultants nearly as large as the Bank’s regular workforce. Many consultants are former Bank staff. The permanent nature of Bank employment also complicates needed reform of its whistleblower policies, which are frequently abused as another tool of entrenchment.
>
> All of these and other factors have added up to a bloated budget in which an unusually honest and candid senior budget official , who met with Mr. Wolfowitz in my home pending board approval of his nomination to avoid detection by more senior Bank staff, identified specific examples of wasteful spending adding up to about \$300 million annually. Mr. Wolfowitz’s first steps to rein in the Bank’s unsustainable cost structure are another important reason many staff and their board allies want him gone. Unless he and his successors and the board address the cost structure, the Bank will be in danger of collapse.
