---
title: "The Dow Theory Sell Signal"
date: "2007-11-22"
categories: ["Financial Markets"]
---

Financial newsletter tracker [Mark Hulbert](http://www.marketwatch.com/news/story/story.aspx?guid=%7BA7562248%2D7392%2D4891%2D8FDE%2D79619507C729%7D "Mark Hulbert") notes that the Dow Theorists are selling:

> the DJIA seesawed all day Wednesday above and below its August closing low of 12,846. In fact, it wasn’t until the final few minutes of trading that it became clear that it would close below that level, and thereby trigger a Dow Theory sell signal.
>
> The Dow Theory’s popularity should trigger additional selling when investors currently on vacation return from their Thanksgiving holidays, either on Friday, or more likely this coming Monday.

[Barry Ritholtz](http://bigpicture.typepad.com/comments/2007/11/dow-sell-signal.html "Barry Ritholtz") quotes Richard Russell of Dow Theory Letters:

> People don’t understand the significance of the ‘bear market signal’ of November 21. I stated on Wednesday’s site (Nov. 21) that the breakdown of the Industrials signaled THE EXISTENCE of a primary bear market. It didn’t signal the beginning of a bear market, Wednesday’s action gave us the final word via Dow Theory that a primary bear market was in force.
>
> ... A precept of Dow Theory is that neither the duration nor the extent of a bull or a bear market can be predicted in advance. It is far easier to IDENTIFY the end of a bull or bear market than it is to predict their end. Bull markets tend to build extended and often deceptive tops while bear markets tend to build more definite and identifiable and faster bottoms. Therefore, it’s usually easier to identify the bottom of a bear market than it is to identify a bull market top.
>
> ... I expect a lot of wild and confusing movements from the stock market in the days ahead. But I remind subscribers that a rally here, even a powerful rally, will not mean that the bull market has suddenly been reborn. This bear market will not end in four months. But any rally here will allow subscribers to ‘trim their sails’.
