---
title: "The Redundant IMF"
date: "2007-04-13"
categories: ["Economics", "Financial Markets"]
---

[Adam Lerrick](http://www.aei.org/publications/filter.all,pubID.25952/pub_detail.asp "Adam Lerrick") on the IMF’s battle against its own irrelevance:

> The institution’s proud lending portfolio that had totaled \$100 billion in 2003 has since collapsed. It now stands at \$13 billion. Turkey could push that even lower as it dips into a full treasury to pay off a \$9 billion balance. The IMF’s lending accounts are shrinking and its income stream drying up…
>
> There was a windfall for the IMF in the decade of bailouts that began with Mexico in 1995. As its loan portfolio tripled and net income ballooned tenfold to \$1.2 billion in 2004, there was money enough to pay for another big glass headquarters and a 50% increase in staff to 2,700; to more than double administrative costs to almost \$1 billion; and even to poach on the World Bank’s territory of development aid.
>
> Now the Fund is bleeding \$200 million to \$300 million a year. But there is no talk of retrenchment. Instead, the Fund seeks to become the arbiter of global exchange rates and the arbitrator of economic disputes between nations—grandiose positions that are not needed, wanted nor enforceable in the world economy. And the IMF seeks a new wellspring of funding to support the expansive lifestyle to which it has become accustomed.
>
> A Committee of Eminent Persons was assembled to find the money. Central bankers, among them Alan Greenspan of the U.S. and Jean-Claude Trichet of Europe, joined private-sector leaders Andrew Crockett of JP Morgan and Mohamed El-Erian of Harvard Management. But this assembled brainpower was warned off of the real questions that need to be answered: What is the right role, the right size and the right cost of the IMF?
>
> Instead, the Eminent Persons were shunted off to the IMF’s basement where 103 million ounces in ingots had been left behind from the days of the gold standard. Each ounce, deposited by member countries at \$35, is now worth \$650, creating a constant temptation for Funders. Selling this resource rather than leaving it in the basement would yield a gain of \$60 billion and an investment income of \$3 billion a year. The Committee emerged with a proposal to use 13 million ounces, or an eighth of the gold stockpile, to establish an IMF endowment, an independent income stream for the Fund in perpetuity.

The conspiracy theorists at [GATA](http://www.gata.org/ "GATA") will have a field day with this.
