---
title: "The Liberty & Democracy Party"
date: "2007-11-09"
categories: ["Politics"]
---

They may have a name that sounds like a Latin American populist front, but the [Liberty and Democracy Party](http://www.ldp.org.au/ "Liberty and Democracy Party") is the first organised libertarian political party in Australia since John Singleton and Bob Howard’s ironically named Workers’ Party in the 1970s.  John Humphreys laid out on the rationale for the LDP in the Autumn 2007 issue of [Policy](http://www.policymagazine.com/ "Policy").

It would seem unlikely that a libertarian political party could ever enjoy much success in Australia.  US political culture is much more friendly to libertarian ideas, yet it has not been able to sustain an electorally-successful libertarian political movement.  The only identifiably libertarian candidate for the presidency in 2008 is Republican Ron Paul, an Old Right isolationist crank.

Still, small parties can have an influence on political debate that is unrelated to electoral success.  Milton Friedman once pointed to the official platform of the Socialist Party in the United States, which never enjoyed much electoral success, and yet managed to see many elements of its political platform adopted.

I particularly liked the LDP’s [response to the candidate questionnaire](http://www.australiavotes.org/policies/index.php?election_id=1&topic_ids=all&party_ids=17#question1 "response to the candidate questionnaire") from the Australian Christian Lobby.  Needless to say, the answers ACL got are probably not the ones they wanted to hear.  The ACL opportunistically seize upon a [junk report](../2006/exploited_by_the_australia_institute.qmd "junk report") from the Australia Institute to argue for increased censorship of advertising ‘to protect childhood.’  The LDP’s response:

> *• The Australia Institute is a socialist organisation.\
> • Raising a child is the job of parents, not the government.*

The LDP is preferencing against sitting members, with the exception of Wentworth, where it is preferencing Malcolm Turnbull as a reward for his support (sincere or otherwise) for the Tasmanian pulp mill.  In the absence of foot soldiers to hand-out how-to-vote cards, the LDP’s Reps preferences probably won’t matter much.  In the Senate, they are alternating their preferences between the Coalition and Labor and putting the Greens last.
