---
title: "The Australian Dollar’s Carbon Footprint"
date: "2007-07-24"
categories: ["Economics", "Financial Markets"]
---

As the Australian dollar makes new 18-year highs against the greenback, [Terry McCrann](http://www.theaustralian.news.com.au/story/0,25197,22107160-14743,00.html "Terry McCrann") suggests we ponder the relationship between the currency, the terms of trade and carbon emissions:

> The core driver of our rising dollar—and pretty much everything else in and around our economy—is the explosive growth in China’s demand for, and consumption of, commodities.
>
> Principally, so far as we are concerned, iron ore to make steel and coal to generate power. Along with pretty much everything else—globally importantly, oil and copper.
>
> In short, not to put too fine a point on it: our dollar is pivoting on a truly momentous eruption of greenhouse gases. Yet we and the world are—at least hypothetically—committed to not just capping that eruption, but reversing it.
>
> Let me spell that out a little more specifically. We have a dollar challenging conventional currency gravity; on the promise of pumping more and more commodities into the Chinese “greenhouse gas factory”. Yet we want to in effect burn that factory down.
>
> Add on the certainty that even on the assumption that the factory keeps on belching, our dollar will overshoot; what happens if we actually “succeed” in persuading China to please let us leave all the stuff in the ground?
