---
title: "The Anti-Capitalist Origins of the Foundational ‘Bubble’ Myth"
date: "2007-05-13"
categories: ["Economics", "Financial Markets"]
---

A [review](http://www.ft.com/cms/s/50e2255e-0025-11dc-8c98-000b5df10621.html "review") of Anne Goldgar’s [Tulipmania: Money, Honor, and Knowledge in the Dutch Golden Age](http://www.amazon.com/gp/product/0226301257/104-9448699-9787948?ie=UTF8&tag=institutional-20&linkCode=xm2&camp=1789&creativeASIN=0226301257 "Tulipmania: Money, Honor, and Knowledge in the Dutch Golden Age"), which discusses the anti-capitalist origins of the foundational ‘bubble’ myth:

> Some contemporary pamphleteers attacked the trade, baffled by what one Englishman called the “incredible prices for tulip rootes”, and disquieted by the godless materialism of it all. They feared, wrongly, that the trade subverted the social order by making poor people rich. As almost no other contemporaries wrote about tulipmania, these biased pamphlets informed most later accounts.
>
> Most tulip tales we know, scolds Goldgar, “are based on one or two contemporary pieces of propaganda and a prodigious amount of plagiarism”.
