---
title: "The Future Fund versus the Republic of Azerbaijan"
date: "2007-10-20"
categories: ["Economics", "Financial Markets"]
---

Which of the following sovereign wealth funds would you expect to score more highly in terms of transparency and accountability: the State Oil Fund of the Republic of Azerbaijan; Timor’s Petroleum Fund; Singapore’s Temasek Holdings or Australia’s Future Fund?

The answer is that Australia’s Future Fund lags behind all of them according to a scoreboard of sovereign wealth funds compiled by [Ted Truman of the Peterson Institute](http://www.iie.com/staff/author_bio.cfm?author_id=122 "Ted Truman of the Peterson Institute").  The Future Fund scores seven out of a possible 12 for transparency and accountability compared to 9.5 for the State Oil Fund of the Republic of Azerbaijan.  Indeed, the Future Fund scores only half a point better than the National Oil Fund of Kazakhstan ([jagshemash](http://www.urbandictionary.com/define.php?term=jagshemash "jagshemash")!)

In terms of the overall scoreboard, which takes into account additional factors such as structure and governance, Australia’s Future Fund ranks sixth with a score of 17 out of 25, behind New Zealand’s Superannuation Fund, Norway’s Government Pension Fund, Timor’s Petroleum Fund, Canada’s Alberta Heritage Savings Trust Fund and the Alaska Permanent Fund.

Having recently attended a presentation on the NZ Super Fund by its head, Adrian Orr, I think New Zealand’s number one ranking is well deserved.  The NZ Fund is in many ways of a model of public sector accountability and transparency.  Yet for all that, the Fund is also designed to support bad public policy, namely a universal pension system.  You would rather have Australia’s retirement income system than New Zealand’s.  But that is no excuse for the Future Fund to be falling short of world’s best practice in terms of transparency and accountability.
