---
title: "The Demise (Yet Again) of ‘Peak Oil’"
date: "2007-03-06"
categories: ["Economics", "Financial Markets"]
---

An article in the [NYT](http://www.nytimes.com/2007/03/05/business/05oil1.html?pagewanted=1&_r=1&ref=business "NYT") documents how market incentives and technology are working against ‘peak oil’ Malthusianism:

> Within the last decade, technology advances have made it possible to unlock more oil from old fields, and, at the same time, higher oil prices have made it economical for companies to go after reserves that are harder to reach. With plenty of oil still left in familiar locations, forecasts that the world’s reserves are drying out have given way to predictions that more oil can be found than ever before…
>
> There is still a minority view, held largely by a small band of retired petroleum geologists and some members of Congress, that oil production has peaked, but the theory has been fading. Equally contentious for the oil companies is the growing voice of environmentalists, who do not think that pumping and consuming an ever-increasing amount of fossil fuel is in any way desirable.

‘Peak oil’ is one of those hardy perennials that never seems to go away.  Last year, the Weekend Australian Magazine (no link) ran a profile of people who were hoarding tinned food and growing their own vegetables based on the Malthusian idea of economic collapse due to resource depletion.  Rather than ridiculing these people, the article took them quite seriously.
