---
title: "The Euro as Ultimate Sub-Prime Victim"
date: "2007-12-03"
categories: ["Economics", "Financial Markets"]
---

[Liam Halligan](http://www.telegraph.co.uk/money/main.jhtml?xml=/money/2007/12/02/ccliam102.xml&page=1 "Liam Halligan") argues that the euro may be the ultimate victim of the current problems in global credit markets:

> sceptics like me have always said the operational viability of the single currency won’t be known until the system is tested by a serious downturn. That moment may now come soon.
>
> Interest rate spreads between government bonds in France, Spain, Germany and Italy have lately got wider and wider. In other words, believe it or not, the markets are increasingly betting on the eurozone breaking up – as political tensions rise, and the needs of inflation-averse nations like Germany can’t be reconciled with much weaker debt-driven members like Ireland and Spain.
>
> Could it happen? Why not? Every other currency union in the history of man has broken up – unless, like the US and UK, it has been preceded by generations of political union, and held together with a federal tax system.
>
> It sounds far-fetched, I know. But the ultimate victim of this sub-prime crisis could be nothing less than the single currency’s existence.
