---
title: "The World Bank as Rogue Institution"
date: "2007-10-19"
categories: ["Economics", "Financial Markets"]
---

Ahead of this weekend’s meeting of the World Bank in Washington, [Adam Lerrick](http://online.wsj.com/article/SB119275978380264493.html?mod=opinion_main_commentaries "Adam Lerrick") argues that it is a rogue institution that needs to be brought under control by its members:

> While presidents come and go, a bureaucracy, hostile to change and clever at manipulating an unwieldy multinational board, is flouting the bank’s founding articles, distorting the facts, concealing losses, lowering standards and now planning to take on new risks. The bank is desperate to “remain relevant” to middle-income countries that no longer need its money and do not want its advice.
>
> The bank does not, as it claims, lend where the poor live. More than half of loans since 2000 flowed to six upper-middle-income nations which tally less than 5% of the developing world’s hard-core needy. For the creditworthy countries the bank courts, the private sector will underwrite any pro-poor project the bank would consider. Far from generating a surplus for the poorest, fees and interest on middle-income lending now fall \$500 million a year short of the bank’s cost of doing business. The \$2 billion return on the bank’s \$40 billion of zero-cost capital masks the loss.

Australia contributed AUD 176m to the activities of the World Bank in 2004-05.
