---
title: "The Opinion Polls Costello Forgot"
date: "2007-12-01"
categories: ["Politics"]
---

As Peter Costello steps-up [martyrdom operations](http://www.theaustralian.news.com.au/story/0,25197,22851932-5013947,00.html "martyrdom operations") against John Howard, [Greg Sheridan](http://blogs.theaustralian.news.com.au/gregsheridan/index.php/theaustralian/comments/liberals_again_fail_to_honour_a_party_hero_unlike_labor "Greg Sheridan") reminds Costello of his culpability in the Coalition’s defeat:

> It is very difficult to find an interpretation of the facts over the past few years that does not indicate that Peter Costello was the one who played the wrecking, and the dishonourable, role in the Liberal Party.
>
> At least 30 per cent of the Government’s problems came from Costello and his party supporters repeatedly briefing the press and others against Howard. There are numerous public examples of this, such as the bitter comments Costello made to Howard’s biographers, or the famously leaked dinner with senior Canberra reporters during which Costello detailed how he would destroy Howard.
>
> Similarly, Costello’s party lieutenants for years briefed journalists on leadership challenge timetables and why Howard must go.
>
> All of this had two perverse consequences. First, more than any other factor it crippled Howard as a medium-term leader. It forced him to make the leadership compromise commitment that he would hand over to Costello midway through the next term.
>
> This minimised the government’s freedom to manoeuvre. It diminished Howard and was a drag on the Liberal vote. Two non-political members of my extended family told me they would vote Labor because they didn’t want Costello to become prime minister. Costello, you see, was always unpopular.

If [Roy Morgan](http://www.roymorgan.com/news/polls/2007/4191/ "Roy Morgan") is to be believed, Costello would have had a devastating impact on the Coalition:

> Electors were also asked who they would vote for if Peter Costello or Malcolm Turnbull were Prime Minister: neither Costello nor Turnbull lifted the L-NP vote beyond the result Howard achieved. 
>
> Primary support for the L-NP if Peter Costello were leader is a low 31.5% (down 3.5% from the Howard result), while ALP support rose 4.5% to 52.5%.  The ALP’s two-party preferred lead went from 18% with Howard as leader to 26% with Costello as leader (63% cf. 37%).
>
> Malcolm Turnbull fared better with L-NP primary support remaining at the same level as Howard (35%), while ALP support increased 1.5% to 49.5%.  Turnbull achieved the same two-party preferred lead as Howard (ALP 59%, L-NP 41%).
