---
title: "The Market’s US Slowdown Fixation"
date: "2007-04-10"
categories: ["Economics", "Financial Markets"]
---

[David Malpass](http://online.wsj.com/article/SB117607451984663549.html?mod=opinion_main_commentaries "David Malpass") highlights the misplaced concerns about a slow-down in the US economy following the March employment report:

> The U.S. continues to be the biggest contributor to global growth. We grew as fast in 2006 as in 2005, over 3% real growth on a \$13 trillion base, with small businesses making up for the slowdown in U.S. homebuilding and auto production. The “weak” U.S. 2006 fourth quarter showed 2.5% real growth, with the just-ended January-March quarter nearly as fast. Using Friday’s data, man-hours worked in the first quarter grew 1.5% at an annual rate, with productivity growth, though diminished, expected to add another 1% or so. Big business spending on equipment and software has been sluggish, but the impact on GDP may not be as large as expected.
>
> Several factors still contribute to a deep underestimate of the U.S. economy and shade the global outlook. Monetary policy should be measured by the level of interest rates, not the number of Fed increases from 1%. Housing is a small part of job and economic growth (about 4%). Rather than triggering a recession, the sector is merely returning to normal after the 2004-2005 construction boom. The trade deficit, also not a recession trigger, is matched by a capital account surplus, providing an extra source of inexpensive funding for U.S. growth and investment…
>
> The strong labor report should caution those counting on moderations in U.S. growth and inflation to allow U.S. interest rate cuts. In addition to a weak dollar, the related increase in inflation, and high levels of global liquidity, monetary policy is facing a lower-than-expected unemployment rate even as labor-force growth is set to slow further due to demographics. While low unemployment doesn’t cause inflation—it often increases productivity and output, holding prices down—the Fed will probably factor the new jobs report into its thinking on the economy’s growth relative to its potential, still a factor in its interest rate decisions. The theory is that growth is above potential, and possibly inflationary, if it is pushing the unemployment rate down.
>
> The declining unemployment rate is great news for living standards, but is a stiff challenge to the market’s fixation on slowdown theories and a softening of the Fed’s monetary policy.

Look for a similarly strong Australian March employment report this week.
