---
title: "The Party of Fiscal Prudence?"
date: "2007-03-02"
categories: ["Economics", "Financial Markets"]
---

Opposition finance spokesman [Lindsay Tanner](http://www.theaustralian.news.com.au/story/0,20867,21309354-7583,00.html "Lindsay Tanner") would have us believe that the Labor Party is the party of fiscal prudence.  Having detailed the federal government’s own fiscal profligacy, Tanner promises:

> *Labor’s savings strategy would claw back \$3billion over the budget estimates period. That’s just for starters.*

But Tanner then struggles to identify meaningful budget savings, referencing only cuts in administrative waste and duplication.  Needless to say, the savings available in this regard are trivial compared to the big ticket spending programs in health, education, social security and tax expenditures. 

Oppositions routinely promise budget savings in administration, since this is one of the few areas of public spending that can be safely targeted (public servants can’t speak out publicly).  The NSW opposition leader, Peter Debnam, is making similar undertakings in the context of the NSW state election campaign.  But these politically safe promises give the game away.  Neither federal Labor nor the NSW opposition are serious about cutting federal or state spending.
