---
title: "Throwing the Book at ‘Fair Trade’ Coffee"
date: "2007-04-28"
categories: ["Culture & Society", "Economics"]
---

[Tim Wilson and Sinclair Davidson](http://www.theaustralian.news.com.au/story/0,20867,21634518-601,00.html "Tim Wilson and Sinclair Davidson") want the ACCC to throw the book at ‘fair trade’ coffee:

> TWO Melbourne academics have lodged formal complaints against Oxfam Australia over the sale of Fairtrade coffee, saying it should not be promoted as helping to lift Third World producers out of poverty because growers are paid very little for their beans.
>
> Tim Wilson, a research fellow at the Institute of Public Affairs, and Sinclair Davidson, professor of institutional economics at RMIT University, have asked the Australian Competition and Consumer Commission to investigate Oxfam, saying it is guilty of misleading or deceptive conduct under the Trade Practices Act.
>
> Mr Wilson said there was evidence that Fairtrade products could do more harm than good for coffee producers in undeveloped nations. He cited reports alleging producers had been charged thousands of dollars to become certified Fairtrade providers and some labourers received as little as \$3 a day.
>
> In order to lodge the complaint, Mr Wilson purchased a 250g pack of Fairtrade organic decaf ground coffee from the online Oxfam shop.
>
> “We purchased this product in good faith, with the aim of lifting people out of poverty while enjoying our favourite brew,” Mr Wilson said, in his letter to ACCC chairman Graeme Samuel.
>
> Mr Wilson and Professor Davidson have long held doubts about whether Fairtrade products help coffee, tea and cocoa producers in undeveloped nations. Sales of such products in Australia total about \$8million.
>
> The complaint to the ACCC refers to an article published in the Financial Times last September, which said Fairtrade coffee beans were “picked by workers paid below minimum wage”. It claimed workers received the equivalent of \$3 a day.
>
> The coffee is sold at a premium to people concerned about Third World poverty.
>
> The academics quote an analysis of Fairtrade, published in the US-based Cato journal, which says coffee producers in poor nations are charged \$3200 to become certified Fairtrade providers. The producers’ costs are therefore higher than on the open market. The Fairtrade campaign aims to manage the international coffee trade by fixing prices at \$US1.26 (\$1.64) per pound (454g) and eventually fixing supply.

Cato’s analysis of the international coffee market can be found [here](http://www.freetrade.org/pubs/briefs/tbp-016.pdf "here").
