---
title: "Turnbull and Costello"
date: "2007-06-11"
categories: ["Politics"]
---

The Labor Party continues its selective leaking of its internal research, which [Glenn Milne](http://www.theaustralian.news.com.au/story/0,20867,21882594-7583,00.html "Glenn Milne") seizes upon with barely disguised glee:

> *ONE of the finest political demographers on either side of politics has spelled out for the first time the brutal arithmetic that suggests Malcolm Turnbull is facing inevitable defeat if he stays in the seat of Wentworth—a scenario that means he will never be leader of the Liberal Party or prime minister.*

It is a non-sequitur to say that defeat in Wentworth ‘means he will never be leader of the Liberal Party or prime minister.’  But it is true that Wentworth is a marginal seat, even with the effective margin of 4.5% suggested by the Labor Party’s research, which is larger than the 2.6% margin based on the 2004 federal election result and subsequent redistribution. 

Turnbull’s fate is tied in with that of the government as a whole.  Post-war experience suggests that only very large two-party preferred swings are sufficient to ensure that enough seats change hands to change the government.  Turnbull will likely retain Wentworth if the government is returned, but lose if the government loses office. 

Like many others, Milne probably hasn’t given much thought to the implications of a change of government for the leadership of the federal parliamentary Liberal Party.  It is hard to imagine Peter Costello having the stomach for the job of opposition leader.  Even as Treasurer, he complains bitterly about the opportunity cost of the job and this cost will rise dramatically in opposition.  Costello could be expected to decline the leadership and leave politics shortly thereafter.  In a contest of frustrated ambition, Costello would be a clear winner.
