---
title: "Two RBA Tightenings Before Christmas?"
date: "2007-10-12"
---

[Terry McCrann](http://www.news.com.au/heraldsun/story/0,21985,22571219-5000117,00.html "Terry McCrann") speculates on a December RBA tightening, in addition to a November tightening:

> so hot is the economy, it is even possible—but, I hasten to add, nowhere yet likely—that he could raise the rate again in December.
>
> I’ve previously suggested that a November rate rise was only certain with a ‘bad’ inflation number in the September quarter. If ‘baddish’, Stevens and the RBA brains trust would have to weigh all the other evidence.
>
> Consider it ‘weighed’. Now even a ‘baddish’ inflation number will deliver a rate rise. Only a clearly ‘good’ number will avoid one. Or postpone it.

[Malcolm Maiden](http://www.theage.com.au/news/business/election-or-not-theres-no-reason-to-believe-stevens-wont-raiseinterest-rates/2007/10/10/1191695991843.html "Malcolm Maiden") also notes the high probability of an election eve rate rise:

> the bank itself was perceived to be maintaining what could be called an interest rate demilitarised zone around elections.
>
> The dimensions of the interest rate DMZ were never precisely outlined. But the markets believed that the Reserve would not change rates during an election campaign, and was less likely to do so when one was approaching.
>
> The Reserve’s action and inaction tended to bear that out. It began announcing interest rate hikes and explaining them at the start of the ‘90s, when Macfarlane’s predecessor, Bernie Fraser, was in charge. But until August this year there were no examples of a rate rise in an election year, let alone a rate rise in the middle of an election campaign. So the August move set a precedent, and it did so as new governor Stevens was reshaping the view of the bank’s independence.

As I argue [here](../2007/did_the_rba_break_with_convention_yesterday.qmd "here"), the August move set a precedent only in that it is the first time that the electoral and interest rate cycles have coincided in this way.  The current conjunction of political and economic events has made it necessary for Stevens to spell out the implications of RBA independence in a way that has simply not arisen in the past.
