---
title: "UK Conservatives Channel Clive Hamilton"
date: "2007-09-11"
categories: ["Culture & Society", "Economics"]
---

UK Conservatives [reach](http://www.thesun.co.uk/article/0,,2-2007420012,00.html "reach") for the Australia Institute playbook:

> THE Conservatives will propose banning plasma screens and other energy-guzzling electrical goods in a report to be unveiled next week.
>
> The proposals target white goods like fridges and freezers, as well as TVs, personal computers and DVD players that use too much energy or operate on stand-by.
>
> The ideas come from a Conservative group set up by David Cameron to develop policies to protect the environment and although the measures to make household electrical appliances more energy efficient are not binding on Mr Cameron, they are thought likely to be warmly received by the Tory leader.
>
> The group will also suggest scrapping Gross Domestic Product (GDP) as a measure of the nation’s success in favour of a model that measures people’s happiness drawn up up by Friends of the Earth.

See also [Brendan O’Neill](http://www.spiked-online.com/index.php?/site/article/3788/ "Brendan O’Neill") on David Cameron’s promotion of carbon bondage.
