---
title: "Valuing US Financial Markets"
date: "2007-02-22"
categories: ["Economics", "Financial Markets"]
---

RBA Deputy Governor Ric Battellino made the following observation in [testimony](http://www.aph.gov.au/hansard/reps/commttee/R9961.pdf "testimony") before the House Economics Committee yesterday:

> The popular perception is that, somehow or other, the US is out there spending a lot of money and has to go around the world borrowing to fund that expenditure. I am not sure that is the correct interpretation of what is happening. I think that what is really happening is that the investors of the world want to invest in the US financial markets. They are inundating the US with money, and the US economy and US households are responding to those financial pressures.
>
> I am not sure that there is a huge problem of US indebtedness. I think this is really a sign that world investors actually very much value the characteristics of the US financial markets. There is no doubt that they have the deepest, most liquid and most credit-worthy financial markets in the world. People who have excess savings want to put a lot of their money in the US.

Regular readers will not be surprised to learn that I agree with this proposition.  What surprises me is that there seems to be so little appreciation of these institutional strengths of the US economy and financial markets within the US itself.  The mistaken notion that ‘global imbalances’ are somehow a problem stems from the failure to recognise this fundamental institutional reality.
