---
title: "‘Wimps, Ninnies & Pointless Skeptics’: The Anatomy of Davos Man"
date: "2007-02-02"
categories: ["Economics", "Financial Markets"]
---

[Michael Lewis](http://www.bloomberg.com/apps/news?pid=20601039&sid=aaagOLYMd4yg&refer=home "Michael Lewis") gets to the core of what’s wrong with the Word Economic Forum:

> Davos is where people with no talent for risk-taking gather to imagine what actual risk-takers might do. Davos Man needs to sit in judgment; Davos Man needs to brood. So great is this need that he will brood about virtually anything, no matter how little he knows about it.
>
> So why do these people waste so much of their breath and, presumably, thought, with their elaborate expressions of concern? Even if these global financial elites knew something useful that you and I don’t — that, say, 50 hedge funds were about to go under and drag with them half the world’s biggest banks along with a third of the Third World — they would be unlikely to do anything about it.
>
> And if they really believe the markets mispriced risk, or were about to adjust, they must also believe they could make vast sums of money if they quit their day jobs and opened a hedge fund to take the other side of stupid trades. But they don’t really believe that, or at least some of them would be off doing it, rather than spilling the beans to Bloomberg News.
>
> Is perhaps the only point of standing in the snow and expressing your doubts to a television camera to prove that you are the sort of person whose doubts matter?

Speaking of economic girlie men, [Nouriel Roubini](http://www.rgemonitor.com/blog/roubini/176117 "Nouriel Roubini") is now trying to put me out of business, by providing his own self-critique:

> *Readers of this blog may also think that the second paragraph above is a \[sic\] typical Roubini “doom & gloom” fear mongering and describing a scenario that is totally unlikely to occur in 2007.*

Just what Nouriel said!
