---
title: "Yet More Federal Persecution of the Online Payments Industry"
date: "2007-01-21"
categories: ["Economics", "Financial Markets"]
---

The US feds continue their [persecution](http://www.timesonline.co.uk/article/0,,29390-2551592.html "persecution") of those who facilitate capitalist acts between consenting adults:

> Stephen Lawrence and John Lefebvre, founders of Neteller, the UK-listed online payments company, were last night charged with conspiracy in connection with a multibillion-dollar money laundering scheme linked to internet gambling.
>
> The pair were arrested on Monday after an FBI sting operation discovered that Neteller was being used to allow Americans to place illegal bets on sporting events via internet gambling companies based in foreign countries…
>
> Neteller claims to operate the largest independent online money transfer business in the world with 3 million customers in 160 countries and over \$7 billion in annual transactions.
>
> It specialises in providing instant payment services where money transfer is difficult or risky because of issues of identity, trust, currency exchange, or distance. In the past, it handled funds for online gamblers in the US but it is said to have stopped the practice when tough new laws banned internet gambling in America last October.
>
> Last year authorities arrested a number of prominent executives for breaching US gambling laws, including two from Britain. David Carruthers, the former chief executive of BetOnSports, was arrested in July while Peter Dicks, former non-executive chairman of Sportingbet, was arrested in September.
