---
title: "10th Anniversary of World’s First Economics Blog"
date: "2005-09-14"
categories: ["Economics"]
---

The world’s first economics blog [turns ten this month](http://www.morganstanley.com/GEFdata/digests/latest-digest.html#anchor0 "turns ten this month").  I’m talking about Morgan Stanley’s Global Economics Forum.  The GEF obviously predates blogging as we now understand it, but in retrospect it is clear that blogging is what they have been doing all these years.  The GEF is most notable for carrying the work of Robert Feldman, perhaps the best Japan economist in the business.

It is unfortunate that Morgan Stanley chief economist Stephen Roach and Andy Xie have become so preoccupied with ‘bubbles’ in recent years.  Andy Xie is increasingly sounding like a hard-money Austrian, with everything reduced to an excess liquidity story that is indistinguishable from the pop Austrian simplification that the business cycle can be reduced to fiat money supply errors.  I once thought that ‘bubbles’ were a temporary fallback position for those whose analytical frameworks had failed them, but it is now obvious that, for many analysts, ‘bubbles’ are an all-purpose explanation for everything, devoid of any analytical content.
