---
title: "20 Million Future Funds"
date: "2005-12-21"
categories: ["Economics"]
---

The [CIS](http://www.cis.org.au "CIS") gets behind the idea that the Future Fund should instead be used to endow individual private saving accounts:

A better alternative to the Future Fund would be to hand back the surpluses to the taxpayers who are funding them, and to remit future receipts from the sale of Telstra to the Australian public who notionally own these assets. In this way, the government could enable ordinary people to start saving for their own futures, rather than have the government doing it for them.

The Future Fund is expected to exceed \$60 billion by mid-2007. An equal share-out among all permanent residents in Australia (children as well as adults) could at that time provide everyone with their own personal ‘future fund’ (PFF) worth around \$3,000.  Further dividends from the Government as it disposes of surpluses in the future, together with contributions from individuals themselves, could swiftly raise this to around \$5,000 per person.
