---
title: "A Litany of Failed Doom Mongering"
date: "2005-09-17"
categories: ["Economics"]
---

The FT has a very amusing round-up of failed predictions in relation to UK house prices, demonstrating once again the perverse demand for predictions of housing-related economic ruin.  The [author](http://news.ft.com/cms/s/c85003f2-25a9-11da-a4a7-00000e2511c8.html "author") really nails it when he notes the inability of the commentariat to get their head around the concept of capitalist acts between consenting adults:

*And yet house prices continued to defy the reasoning of such commentators. Unlike many other assets, such as gilts or equities - which usually are influenced mainly by professional decisions - housing is an incredibly democratic market. The average price of a home is entirely a function of decisions, sensible or otherwise, by millions of ordinary people buying or selling homes. Should they decide that it is rational to borrow six times their salaries, when renting might be much cheaper, there is little the intelligentsia can do about it.*

The author also quotes this very sound advice from the Bank of England’s Mervyn King, which the RBA would do well to heed:

*The best way to destroy the credibility of the monetary policy committee is to lecture people about house prices.*
