---
title: "An Australian Congressional Budget Office?"
date: "2005-10-13"
categories: ["Economics"]
---

[Simon Banks](http://www.theaustralian.news.com.au/common/story_page/0,5744,16900246%255E7583,00.html "Simon Banks"), formerly of the Chifley Research Centre, argues for an independent fiscal policy institute to improve the quality of public debate about fiscal policy.  This is an excellent proposal and ties in with earlier work by the CRC on fiscal policy rules by [Ric Simes](http://www.chifley.org.au/publications/index.php?publicationID=12 "Ric Simes").  The current arrangements under the Charter of Budget Honesty are inadequate, with the process still dominated by partisan political considerations and ministerial direction.  Costings done privately by hired guns like Access Economics do not carry much authority, since the client is assumed to get what they pay for, and it is very simple for Treasury to pick holes in these analyses, distracting attention from the substance of the policy proposal. 

Unfortunately, while oppositions get very excited about reforming fiscal and monetary policy rules, they quickly lose interest in the subject when in government.  When I worked for the federal opposition in the early 1990s, there was a determination on the part of the Coalition to reform both the RBA Act and institute fiscal responsibility legislation that would prevent what we saw as abuses of process by the then Labor Government.  What subsequently emerged in government fell well short of what many of us would like to have seen implemented.  We can only hope that the Labor Party doesn’t forget what it was like to be in opposition quite as quickly as the Coalition did.
