---
title: "An Irrelevance Proposition for Current Account Deficits?"
date: "2005-11-16"
categories: ["Economics"]
---

[Alan Wood](http://www.theaustralian.news.com.au/common/story_page/0,5744,17258442%255E31478,00.html "Alan Wood") points to [Australian Treasury](http://www.treasury.gov.au/contentitem.asp?NavId=035&ContentID=1033 "Australian Treasury") and [BIS](http://www.bis.org/publ/work169.htm#pgtop "BIS") papers that highlight the extent to which the official community remain appropriately relaxed on the issue of external imbalances:

Based on a paper by Guy Debelle from the Reserve Bank and Gabriele Galati from the Bank for International Settlements, they also note that the historical record does not appear to contain any industrial-country examples of large current account deficits or stocks of net foreign liabilities having caused domestic economic downturns.

Markets treat countries such as Australia, with well developed financial markets and an ability to borrow in their own currency, very differently from developing countries in Asia or Latin America. There is no evidence rising foreign debt has forced Australia to pay any significant risk premium on its foreign borrowings.

To stop our foreign debt rising from around its present level of 60 per cent of GDP will require Australia to run future trade surpluses of between 0.5per cent and 0.75 per cent of GDP, which Gruen and Sayegh describe as not too onerous an adjustment task. Nor is it likely to matter much if it rises a bit further before it stabilises.

The national fear of large current account deficits and foreign debt of the ‘80s has little relevance in the 21st century, as long as we continue to run good economic policies - including labour market reform.

I would go further and argue that these phobias have not had any relevance since the end of Bretton Woods in the early 1970s.
