---
title: "Another US Current Account Beat-Up"
date: "2005-02-25"
categories: ["Economics"]
---

You can’t help but be suspicious of a story reporting on a speech by Australian Treasury Secretary Ken Henry with the headline ‘[US deficits risk crash: Treasury](http://www.theaustralian.news.com.au/common/story_page/0,5744,12364202%255E601,00.html "US deficits risk crash: Treasury").’  My suspicions deepened when the report contained only two direct quotes from Henry. 

Henry’s [actual speech](http://www.treasury.gov.au/documents/959/PDF/Conference%20address%20February%202005.pdf "actual speech") is nothing exceptional and does not use the word ‘crash’ once.  The Australian Treasury has in fact [argued persuasively](http://www.treasury.gov.au/documents/876/PDF/US_current_account_deficits.pdf "argued persuasively") for the sustainability of large US current account deficits.

Australia routinely experiences cyclical deteriorations in its current account balance as a share of GDP that make the current US deficit look small by comparison.  The Australian Treasury has long been converted to the consenting adults view of the current account.  If it views the US differently, it is because of the public sector contribution to the US deficit, which is a fiscal policy issue, not an external imbalance problem.

Next week, Australia is likely to report a monster Q4 current account deficit.  I will be running a competition for the most melodramatic and silly reporting of, or commentary on, this number.  Send me your sightings by email or post them in comments.

**UPDATE:**  [Terry McCrann](http://www.theaustralian.news.com.au/common/story_page/0,5744,12373422%255E643,00.html "Terry McCrann") also notes that:

*Henry was not setting out to ring the alarm on the “coming crash”, and would probably have been surprised—pleasantly or otherwise—to read words on the front of a national newspaper that would inevitably be dished up to the Prime Minister and/or the Treasurer.*
