---
title: "Another Great Post-Budget Address from Treasury Secretary Henry"
date: "2005-05-17"
categories: ["Economics"]
---

Treasury Secretary Ken Henry’s [annual post-Budget address](http://www.treasury.gov.au/contentitem.asp?NavId=002&ContentID=979 "annual post-Budget address") to ABE is invariably one of the most interesting contributions to public debate about economic policy.  This year’s address is particularly pleasing for the fact that it echoes this blog’s criticisms of the popular hysteria about the current account deficit.  As Henry makes clear, the deterioration in Australia’s current account is a reflection of the fact that we are getting richer via the terms of trade:

The sustained gap between growth in ex post (realised) real domestic demand and real output over the past three years does not provide unambiguous evidence of ex ante (planned) demand for domestic product running ahead of increasingly constrained supply. Instead, it can, at least partly, be explained by strong substitution of relatively cheap imports for domestic product.

One should therefore think very carefully before accepting a conclusion that macroeconomic policy should be tightened to slow domestic final demand growth to meet the rate of GDP growth. To do so would amount to targeting the net export contribution to GDP – which would be a curious, but inappropriate, role for macroeconomic policy.

Needless to say, I am not convinced that there is a case for allowing the tax to GDP ratio to rise to off-set the income boost from higher export prices. I don’t think it obvious at all.

And don’t miss the none too subtle dismissal of Ross Gittins in footnote number 2! 

Tomorrow’s headlines will be full of hysterical beat-ups about differences between Treasury and the RBA over policy, which is unfortunate, because it only distracts attention from the substantive issues being raised by Henry.
