---
title: "Austrian School or Austrian Schooled?"
date: "2005-06-21"
categories: ["Economics"]
---

An editorial in New Zealand’s [National Business Review](http://www.nbr.co.nz/home/column_article.asp?id=12257&cid=14&cname=Editor's%20insight "National Business Review") refers to me as ‘Australia’s Austrian school economist.’  NBR must be the only mainstream media publication in the world that doesn’t have to explain ‘Austrian school’ to its readers.  Only in New Zealand!

As careful readers of this blog will have noticed, I am very sympathetic to most Austrian School insights, and I’m a disequilibrium rather than a general equilibrium theorist.  As the article implies, that is partly why I’m a ‘bubble’ sceptic, but it is also what sets me apart from most people who call themselves ‘Austrian,’ especially the fever swamp Austrians of [Auburn Alabama](http://www.mises.org/ "Auburn Alabama").  These people are all too ready to run with ‘bubble’ talk, because it ties in with their naïve, mono-causal explanation of the business and asset price cycle as being entirely attributable to fiat money supply errors. 

An authentic interpretation of the Austrian tradition would see asset price inflation and deflation as a necessary part of the market discovery process, which would emerge under a variety of plausible monetary regimes, including whatever model of free banking one might prefer.  My only reservation about the Austrian School label is the dubious company it has increasingly come to keep.  It’s high time authentic Austrians drained the fever swamp!
