---
title: "Australia-Japan Economic Outlook Conference"
date: "2005-08-04"
categories: ["Economics"]
---

Manuel Panagiotopoulos of Australian-Japan Economic Intelligence has once again staged an excellent Australia-Japan Economic Outlook Conference.  HSBC chief economist John Edwards gave a presentation on the Australian economy, which ran through a host of macroeconomic indicators showing their best performance in 30 to 50 years and a housing downturn that is shaping up as the most modest in 20 years.  Proving that there is no market for good news, this had at least one conference participant demanding to know when it would all end.  While nobody is arguing that the business cycle has been abolished, the many who predicted disaster on the back of the downturn in house prices have been thoroughly discredited.  John Edwards has been one of the few to have argued consistently against this view.  US pundits, take note!

There was also some impromptu ridicule heaped on The Economist magazine (and with absolutely no prompting from me!)  Edwards said that he found The Economist ‘unnecessarily somber,’ a more polite version of the critique of the magazine we have been running here.  While there was also some positive comment about the magazine’s recent coverage of oil prices, this was presented as the exception rather than the rule.  As The Economist’s circulation breaks new records, it seems to be taken less and less seriously in circles where it once commanded considerable respect.
