---
title: "Australia Day, 2005"
date: "2005-01-26"
categories: ["Economics"]
---

After 217 years, this outpost of the Anglosphere is probably in better shape than it has ever been.  The economy has been growing at one of the fastest average rates in the OECD over the last decade, the unemployment rate is at near 30 year lows, real investment as a share of GDP is at the highest levels in nearly half a century and net Commonwealth public sector debt has been all but eliminated.  Consumption growth and a widening current account deficit, far from being a sign of weakness, indicate confidence in Australia’s future growth prospects.  Perhaps less widely known is the fact that Australia has become a net exporter of direct investment capital in recent years.  At least some of Australia’s current account deficit is thus funding the globalisation of Australian business.

Against this backdrop, the Prime Minister’s approval rating is at its highest levels ever.  This is not unrelated to the fact that the federal opposition Labor Party is in disarray following its crushing election defeat last year.  The abandonment of foreign and defence policy bipartisanship under former Labor leaders Crean and Latham is at least partly responsible for this outcome.

Having said all that, Australia still has much unrealised potential.  With the anti-globalisation bloc in the Senate having been marginalised following the last federal election, there is little excuse for not completing the task of modernisation and integration with the global economy begun in the early 1980s.  2005 is likely to go down in history as the year in which this historic opportunity to finally bury isolationism, protectionism and paternalism was either seized or squandered.
