---
title: "Beazley Economics"
date: "2005-06-14"
categories: ["Economics"]
---

If the Labor Party wants to restore its credibility on economic policy, it will have to do much better than [this](http://www.theaustralian.news.com.au/common/story_page/0,5744,15602538%255E7583,00.html "this"):

“Our country is at a crossroads; every day we sink further and further into unsustainable debt,” Beazley told the conference. “On average, foreign debt has gone up by more than \$2.5 billion in every single month of the Howard-Costello Government.

“My deep worry for Australia is this: I believe John Howard and Peter Costello are taking us to the edge of the debt cliff. I fear Australia’s credit card is nearly maxed out.”

Net foreign debt increases under every government, for the very good reason that we need to borrow abroad to make good the shortfall between domestic saving and investment that drives the current account deficit.  If Beazley is seriously proposing to reduce foreign debt, then he is arguing for some combination of increased national saving or reduced investment.  We can maintain higher levels of both consumption and investment by borrowing abroad than would otherwise be possible.  Beazley is effectively proposing to cut our standard of living for the sake of a lower current account deficit, a self-defeating policy prescription.  It is the capital markets equivalent of an import substitution policy.  The gains from trade in goods markets are equally applicable to capital markets.  Australia’s debt servicing ratio is in very respectable bounds and the foreign currency risk is fully hedged, so Australia’s foreign liabilities are well below the level that would give rise to any concern.

Beazley’s populist rhetoric on foreign debt is of course no different from that the government used when it was in opposition, but it doesn’t do much for his credibility.
