---
title: "Ben Bernanke and the Fever Swamp Austrians"
date: "2005-06-12"
categories: ["Economics"]
---

[Bryan Caplan](http://econlog.econlib.org/archives/2005/06/ludwig_von_bern.html "Bryan Caplan") defends Ben Bernanke against the attack of the fever swamp Austrians.  Those who refer derisively to ‘printing press Ben’ would do well to actually read some of Bernanke’s academic work.  Bernanke has done much to revive pre-rational expectations, old school monetarism and once again give it respectability in academic and policy circles after decades of neglect (his 2004 Brookings paper with Reinhart and Sack being a good example).  Even John Taylor, the pre-eminent exponent of interest rate targeting, has spoken of the need to resort to quantitative approaches to monetary policy when low inflation puts a floor under the real rate. 

Leland Yeager once said ‘I sometimes get the impression that Austrians recite their favourite cycle theory as a kind of elaborate password for mutual recognition and encouragement.’  Yeager has shown that acceptance of the importance of monetary disequilibrium actually argues against much Austrian business cycle theory.

Bernanke is currently front runner on the [Intrade](http://www.intrade.com/apply.jsp?heardFromPromotionDetail=s0545138709r "Intrade") contracts to replace Greenspan, although the market is very thin.  My guess is that his lack of extensive experience in government relative to some of the other candidates will count against him, but he would make a fine Fed Chairman.
