---
title: "Betting Against Themselves:  Buffett, Gates and the Dollar"
date: "2005-11-30"
categories: ["Economics"]
---

The AEI’s [John Makin](http://www.aei.org/publications/filter.all,pubID.23498/pub_detail.asp "John Makin") has put together a surprisingly good piece on the US dollar, which begins with an amusing comparison with George W Bush:

*Why is the dollar like a Republican president? Answer: Because the dollar faces incessant predictions of imminent collapse, but in the end it wins out over weaker alternatives.*

Weighing up the fundamental determinants of exchange rates, Makin argues that ‘it is surprising that the dollar has not risen further.’  He also highlights the absurdity underlying the doomsday cultism of Buffett and Gates:

*America’s two richest men, Bill Gates and Warren Buffett, are losing hundreds of millions of dollars having bet against the dollar on the premise that rising U.S. current-account and budget deficits would have to weaken it. Maybe these two remarkable men should have pondered a little more the question of whether they could have become multibillionaires in Europe or Japan, where the environment for growth and innovation is far less friendly and the underlying vigor of the economy is less conducive to a strong currency. Beyond that, I guess they did not notice that the budget deficits and government debt are considerably larger in Europe and Japan than they are in America. Betting against the dollar meant that Gates and Buffett were betting against themselves. I can’t see why they would want to do that.*
