---
title: "Border Security or Tariff Police?"
date: "2005-06-28"
categories: ["Economics"]
---

It is an interesting sign of the times that one of the better rating shows on Australian television is *Border Security*, which goes behind the scenes to document the activities of the Australian Customs Service and Immigration.  For anyone with classical liberal sensibilities, it makes uncomfortable viewing, not least because of the enormous effort that goes into enforcing bad laws.

An example from a few weeks ago was the two Indian shoe salesmen, who were carrying with them 150 shoe samples.  The fact that the shoes were unpaired was not enough to convince Customs that these were samples.  As a Customs officer explained, the other shoes could be brought in separately and then re-paired for local sale!  So the hapless shoe salesmen were required to destroy each shoe by drilling a hole in them. 

The real problem was that the two merchants had not completed the right paperwork, but one Customs officer explained that part of their job was to protect Australian industry from damage that might be inflicted by foreign goods.  We can all sleep easier at night knowing that we have been kept safe from 300 Indian shoes that might have otherwise found their way on to the feet of unsuspecting Australian consumers.
