---
title: "Breaking the RBA’s Cone of Silence"
date: "2005-04-07"
categories: ["Economics"]
---

RBA Board members Jillian Broadbent and Warick McKibbin seemingly break with convention to [comment on yesterday’s interest rate decision](http://www.theaustralian.news.com.au/common/story_page/0,5744,12777891%255E2702,00.html "comment on yesterday’s interest rate decision"), with Broadbent quick to reassure us that the decision was unanimous.  Far from heralding a new age of RBA transparency, my suspicion is that the Bank was keen to pre-empt any speculation about dissent on the RBA Board or that the Bank’s senior officers had been rolled.  Broadbent and McKibbin were given the job of putting the word out.

One can understand the RBA’s desire to quash such speculation, because the media always turn any hint of conflict on the Board into something more than a legitimate difference of opinion.  Yet the reason for this lack of maturity on the part of the media is precisely that they have never been given the opportunity to treat dissent on the Board as a normal and routine part of the policymaking process.  This will only occur when the RBA formalises procedures for disclosing its deliberations in a systematic way.  Ad hoc revelation of the Board’s deliberations only when it suits the convenience of the Bank’s senior officers is a poor substitute for the transparency and accountability mechanisms that are now the norm among the industrialised world’s central banks.
