---
title: "‘Bretton Woods II’ and Sino-Mercantilism"
date: "2005-03-05"
categories: ["Economics"]
---

The ‘Bretton Woods II’ appellation for East Asia’s managed exchange rate regimes is misleading in almost every respect.  IIE scholars have been [taking issue](http://www.iie.com/publications/papers/truman0205.htm "taking issue") with ‘BW II’ as a framework for analysis and are appropriately sceptical about its sustainability.  Whereas many see this as a potential problem for the US, it is a much larger problem for those economies in East Asia running managed exchange rate regimes. [Morris Goldstein and Nicholas R. Lardy](http://www.iie.com/publications/papers/goldstein-lardy0305.htm "Morris Goldstein and Nicholas R. Lardy") highlight some of the problems the ‘BW II’ framework poses for China:

the revived Bretton Woods system is just another ill-informed employment-oriented case for exchange rate undervaluation…the approach underestimates the costs of sterilization, particularly those associated with financial repression.  If, as seems likely, both the US current account deficit and China’s reserve accumulation, currently \$610 billion, (£318 billion), become much larger, these sterilization costs will rise…

The revived Bretton Woods system sets out a faulty development strategy for China. Rather than seeking to promote an enclave economy based on an undervalued exchange rate and on domestic financial repression, China must expedite financial reform, particularly in banking; liberalise interest rates and reduce reliance on administrative controls and guidance. It must move towards greater flexibility in the exchange rate over the medium term, including an immediate 15-25 per cent appreciation of the renminbi relative to a currency basket. These policies will promote domestic financial stability and more balanced employment growth, improve the allocation of investment and the management of the economy, and help ensure continued access for China’s exports.
