---
title: "Candid Cultists"
date: "2005-12-31"
categories: ["Economics"]
---

Brad Setser reviews the year that was in [‘Things I Got Wrong in 2005’](http://www.rgemonitor.com/blog/setser/112784 "‘Things I Got Wrong in 2005’"):

*Alas, this list is rather long.*

To be fair, this sort of candour is quite admirable and not often seen among pundits.

Don Boudreaux has an [extract](http://cafehayek.typepad.com/hayek/2005/12/milton_and_char.html "extract") from a recent interview with Milton Friedman that touched on the subject of global imbalances.  RBA Governor Ian Macfarlane made much the same point in a [speech](http://www.rba.gov.au/Speeches/2005/sp_gov_120505.html "speech") earlier this year, which should have received a lot more attention than it did:

*the scenario whereby world financial markets react to the US current account deficit by withdrawing funding has disappointed those who thought it would come into play. It may happen yet, but people have been predicting it for a long time and yet it seems no closer. A large part of the reason for this is that investors who want to get out of US dollars have to run up their holdings of another currency – they cannot get out of US dollars into nothing. They have to take the risks involved in holding some other currency, possibly at an historically high exchange rate, and they may well be reluctant to do so.*
