---
title: "CIS Liberty & Society Seminar in Sydney"
date: "2005-05-18"
categories: ["Misc"]
---

The Centre for Independent Studies is recruiting for its July [Liberty & Society Seminar](http://www.cis.org.au/L&s/HTML/home.htm "Liberty & Society Seminar").  As a graduate of both the IHS and CIS L&S programs, I can highly recommend the experience:

Liberty and Society, a unique programme for young people living in Australia, New Zealand and other surrounding countries. The goal of Liberty and Society is to create an intellectual environment where ideas and opinions about what makes a free society can be discussed, argued and learnt.

Liberty and Society is for young people who may be questioning the standard answers they are getting regarding social, political and economic issues. You may not see yourself as a fitting into the ‘left’ or ‘right’ mould. This is an opportunity to consider the classical liberal perspective. Classical liberalism promotes individual freedom, private property, limited government and free trade.

In other local seminar news, Bruce Caldwell, author of [Hayek’s Challenge](http://www.lfb.com/cart/affiliate.php?code=10488&stocknumber=FA8818 "Hayek’s Challenge"), will be speaking at the [18th HETSA Conference](http://www.econ.mq.edu.au/hetsa/ "18th HETSA Conference") at Macquarie University, 5-8 July.
