---
title: "Contrarian Optimism versus the Doomsday Cult: A Fund Manager’s View"
date: "2005-08-27"
categories: ["Economics"]
---

This blog’s position of contrarian optimism on the US and Australian economies has made it something of a lone voice amid the rather fevered gloom and doom that characterises many other economic blogs.  Much of this gloom and doom ultimately stems from a curious lack of faith in the most basic market institutions that underpin the success of the Anglo-American economic model. 

I was therefore pleased to read fund manager V. Anantha Nageswaran’s article on [The Doomsday Cult](http://www.libranfund.com/doomsdaycult.pdf "The Doomsday Cult"), which takes the economics blogging community to task for trafficking in ‘stale conventional wisdom.’  It should be said that Dr V comes at this from what I suspect is a very different position from my own.  My impression is that he has also been somewhat partial to the views he now criticizes. As a fund manager, he has no doubt had to accept that market pricing has been particularly unkind to those who bought into these views by underweighting USD asset markets.  While I don’t necessarily share his argument or analytical framework, he nonetheless reaches some very similar conclusions to my own.

**UPDATE:**  More silly doomsday cultism, from [Clyde Prestowitz](http://www.theaustralian.news.com.au/common/story_page/0,5744,16416680%255E28737,00.html "Clyde Prestowitz").
