---
title: "Contrarian Indicators and the Housing ‘Bubble’"
date: "2005-08-01"
categories: ["Economics"]
---

If making the cover of *The Economist* is not enough to convince that talk of a housing ‘bubble’ is nonsense, how about when the ‘bubble’ starts appearing on [T-shirts](http://calculatedrisk.blogspot.com/2005/07/sign-of-times-bubble-t-shirt.html "T-shirts")?

For more evidence that the optimists are now the true contrarians, don’t miss [Victor Niederhoffer’s](http://www.dailyspeculations.com/ "Victor Niederhoffer’s") Open Letter to the Doomsdayists:

I confess that I have read all of the books, and listened to all your fears, and find that they do not contain any reason to think that the conditions of our own day are considerably worse than they ever been before – or, if they were, that this would be bearish. When you consider the record of the proponents of these views, who have been proclaiming them since S&P 300 in 1987, all through the regularly occurring implied volatilities of 25 in 1998 and the 30s in 2002, and their hopes and wishes that America will be doomed unless we scale down consumer spending and retaliations against those who would destroy us, increase our funding of the United Nations and support of the Kyoto agreements, I would commit their books to the flames and indeed insist that they return to the monasteries and austere existences and sabbaticals that many of them have threatened to retire to or engage in since the falsity of their views has been manifest—for they want common sense and do not take into account the resilience of the enterprise system nor the many good things that counterbalance all their misinformed emphasis and hopes for the negative.

Nay, the very prevalence of their views, the extent of the belief that comparisons of the present times to the 1920s and 1970s when there were crashes without reference to any other decades might be predictive of anything, is evidence that the prospects for future returns are even greater than they have been during the 20th century when markets throughout the world scored a 1.5 million percent return.\
