---
title: "Current Account Deficit Angst and Behavioural Finance"
date: "2005-03-12"
categories: ["Economics"]
---

[Terry McCrann](http://www.theaustralian.news.com.au/common/story_page/0,5744,12518014%255E643,00.html "Terry McCrann") on current account deficit angst:

Did any of you spend even a single day in the actual December quarter worrying whether the deficit would be funded by foreigners? Whether “today’s” \$230 million had come in on any single business day, so you could retire to the plasma TV that evening “knowing” that Australia was safe from bankruptcy for another day; and another \$230 million?

Of course not. That \$15 billion was not only funded, but over-funded. More money wanted to come than we needed - so the RBA had to take some of the foreign coin and the Aussie dollar was pushed higher by the excess demand.

The reason most of us don’t lie awake at night worrying about the current account is that we rightly figure that we have taken prudent decisions in relation to our personal finances.  Yet we are also prone to the belief that collectively we are behaving irresponsibly.  Most of those who express public concern about the current account deficit would have personal balance sheets that differ only in degree rather than kind from the current account deficit.

Much of the air of moral panic that surrounds the current account deficit probably stems from the commentariat’s belief that there must be something wrong when the lower middle-class start moving into large, debt-financed homes and enjoying cheap imported goods that were once considered minor luxuries.  When the masses start tapping into what were previously perceived as positional goods that helped set the commentariat apart, there is a natural tendency to assume that economic corners have been cut.

Who said insights from behavioural finance couldn’t be used to support free markets?!
