---
title: "Current Account Sustainability"
date: "2005-06-16"
categories: ["Economics"]
---

[Tony Makin](http://www.theaustralian.news.com.au/common/story_page/0,5744,15624313%255E7583,00.html "Tony Makin") argues against the 5% of GDP rule of thumb on current account sustainability:

an internationally recognised rule of thumb has developed that says an external deficit is excessive if it reaches 5 per cent of GDP. Australia has not been below that for quite some time.  Yet this 5 per cent limit, popular with the IMF, has never been justified analytically and seems arbitrary…

an economy’s productive investment opportunities alone set a feasible upper limit for the current account deficit…judging external account and foreign debt sustainability with reference to the nation’s saving pool would seem to improve on the arbitrary 5 per cent of GDP rule.

On this basis, and given the sizeable fiscal surplus at present, Australia’s current account deficit is easily sustainable, although its feasible limit gets closer as private and public consumption spending rises too quickly.

In the meantime, the high current account deficit remains the best measure of the extent to which foreigners are expressing confidence in the Australian economy. It will persist as long as that confidence is warranted.

It is also worth recalling that the existing record current account deficit was preceded just a few years ago by a record narrowing of the deficit.  Current account balances cycle and this cycle is becoming more pronounced in Australia’s case.  It is no accident that the record narrowing in the deficit followed the AUD making record lows in 2001.  As Makin argues, floating exchange rates provide an adjustment mechanism to external imbalances.
