---
title: "Demographic Underpinnings of US Potential Growth"
date: "2005-06-22"
categories: ["Economics"]
---

A very good critical [review](http://claremont.org/writings/crb/spring2005/krikorian.html "review") of some of the demographic-panic literature in the US, including this observation:

the US is exceptional. Our birthrates have fallen, and thus the average age of our people has increased, but it has happened more gradually than elsewhere. What’s more, our population is projected to keep growing. This is not only because of immigration, as Wattenberg suggests, but because of higher fertility among native-born women; even college-educated, non-Hispanic white women have a total fertility rate of 1.7 children, higher than the overall rates of Canada, Britain, or Australia, not to mention the even lower rates of Japan, Germany, Italy, and Spain.

Within the context of falling birthrates worldwide caused by urbanization, education, and the rest, Americans, as both a more religious and more optimistic people, simply choose to have more children. In fact, the only Census Bureau scenario that foresees a declining U.S. population in this century is based on the highly unlikely assumptions that, first, the fertility of American women will fall to European levels, and second, immigration will be reduced to levels below even what most restrictionist organizations call for. Barring catastrophe, then, the population of the US will not decline during the lifetime of anyone reading this article.
