---
title: "Did the Japanese Ministry of Finance Save the World?"
date: "2005-03-10"
categories: ["Economics"]
---

Richard Duncan, one of the many ‘[US Dollar Crisis](http://www.amazon.com/exec/obidos/tg/detail/-/0470821027/ref=ase_institutional-20/104-1307082-1901504?v=glance&s=books "US Dollar Crisis")’ hysterics, [argues](http://www.financeasia.com/articles/3DECEAD4-9027-7E17-4B1E7ECF8C7906F4.cfm "argues") that Japan’s intervention to weaken the yen in 2003 saved the world and even goes so far as to suggest this might have been a policy coordinated with the US:

Intentionally or otherwise, however, by creating and lending the equivalent of \$320 billion to the United States, the Bank of Japan and the Japanese Ministry of Finance counteracted a private sector run on the dollar and, at the same time, financed the US tax cuts that reflated the global economy, all this while holding US long bond yields down near historically low levels.

In 2004, the global economy grew at the fastest rate in 30 years. Money creation by the Bank of Japan on an unprecedented scale was perhaps the most important factor responsible for that growth. In fact, ¥35 trillion could have made the difference between global reflation and global deflation. How odd that it went unnoticed.

Unfortunately, this subject is getting too much notice.  Duncan is not alone in exaggerating the importance of the recycling of East Asian current account surpluses through USD asset markets.  There is now a veritable cottage industry of blogs dealing almost exclusively with this subject.  But while the amounts sound impressive in flow terms, they are trivial in relation to the total turnover in USD asset markets.  Even *daily* turnover in foreign exchange markets is in the trillions.  East Asian financing of the US current account deficit has at best a marginal influence on the USD and bond yields, because they trade in such deep and liquid markets.  The idea that the US is some how completely dependent on this very small subsidy from East Asian central banks is ludicrous.

Peter Hartcher’s [excellent book](http://www.amazon.com/exec/obidos/tg/detail/-/0875847854/ref=ase_institutional-20/104-1307082-1901504?v=glance&s=books "excellent book") on the Japanese Ministry of Finance was subtitled ‘How Japan’s Most Powerful Institution Endangers World Markets,’ which comes much closer to the truth.
