---
title: "Disappointing Think Tanks on the Left and Right"
date: "2005-03-29"
categories: ["Economics"]
---

The AEI’s [John Makin](http://www.aei.org/publications/filter.all,pubID.22198/pub_detail.asp "John Makin") confidently declares housing to be in a ‘bubble’ and lays it all at the feet of Alan Greenspan.  Makin argues that the Fed should toughen up its rhetoric and tighten by 50 bps in June.  This is somewhat at odds with the [position Makin held](http://www.aei.org/publications/filter.all,pubID.21402/pub_detail.asp "position Makin held") as recently as October last year, when he called for a halt to further rate increases because of what he saw as the risk of recession in 2005.  The AEI has been more dovish and interventionist on monetary and exchange rate policy than many left-liberal think tanks, making any criticism of Greenspan for presiding over a ‘second bubble’ more than a bit rich.

Frank Lowy is to be commended for his philanthropy in establishing the Lowy Institute, but one has to wonder whether he is getting value for money.  The Lowy Institute would seem to be promoting ideas that are already over-represented within academia and among the Labor Party’s foreign policy establishment-in-internal-exile.  As [Greg Sheridan](http://www.theaustralian.news.com.au/common/story_page/0,5744,12686595%5E2702,00.html "Greg Sheridan") notes:

*The Lowy Institute, devoted as it is to Australian foreign policy, is a good thing. It’s full of conscientious folk doing useful work. Unfortunately, it does not look like it’s going to inject any fresh thinking into Australian foreign policy or generate any new voices. Rather it will reinforce the sadly quite narrow range of opinions held among professional academic and quasi-academic foreign policy commentators.*

The same narrow views that led the Labor Party into a catastrophic abandonment of bipartisanship on foreign and defence policy ahead of the last election.
