---
title: "Fever Swamp Austrians versus the Fed"
date: "2005-04-23"
categories: ["Economics"]
---

The [Austrians of Auburn Alabama](http://www.mises.org/ "Austrians of Auburn Alabama") have always had a rather mono-causal view of the business cycle.  Through much of the current cycle, they have been ranting about easy monetary policy fuelling commodity and asset price inflation, while paying little attention to non-monetary fundamentals.  For devotees of free markets, they have little respect for actual market outcomes in relation to growth in credit aggregates and asset prices.

Former Federal Reserve Board member [Wayne Angell](http://online.wsj.com/article/0,,SB111413826455614215,00.html?mod=opinion%5Fmain%5Fcommentaries "Wayne Angell") makes the case for recalibrating our assumptions about what constitutes easy monetary policy:

many have not accepted the reality of lower interest rates that accompany an economy of abundance—and we seem to be not much better at this than Japan in the 1980s. Lower interest rates mean an upward adjustment to asset prices. The present value of houses, land, and capital goods is increased as the flow of rents and dividends are discounted at lower interest rates. The erroneous reaction was to think that higher asset prices spelled out easy money.

Price increases and decreases are the most important motivator and regulator in a market economy. In an economy without inflation, higher price motivates consumers to consume less while motivating business to produce more. High prices are somewhat short-lived as supply-side and demand-side price rationing soon returns the price to a normal level.

The introduction of market-economic growth to China and India added so much to the demand for commodities that their prices had to adjust upward to a new level. At a 9% annual growth rate, China doubles its use of resources every eight years. There is no global inflation consequence as China and India are adding workers to global production, and commodity prices only go up to set off a realignment of global resources producing more of the commodities with higher prices. Yet most observers interpreted rising commodity prices as easy money which they suspected would lead to inflation. That is wrong. If inflationary forces were evident, the supply and demand responses would be blunted by an understanding that prices have not gone up, but that, instead, the value of money has gone down.
