---
title: "Forbes on Economics Blogs, Mark II"
date: "2005-08-03"
categories: ["Economics"]
---

*Forbes* has updated its [story](http://www.forbes.com/bow/b2c/category.jhtml?id=307 "story") on economics blogs from March 2003 and rather kindly suggests that ‘the depth of Kirchner’s discussions…isn’t matched in many other blogs.’  However, the author of the story concludes that ‘if you don’t know the difference between demand-pull inflation and dividend imputation, this probably isn’t the blog for you.’  One of the main motivations behind this blog has been my disappointment at the dumbing-down of economics and financial market reporting in the mainstream press.  There seems to be a working assumption, even in the ‘quality’ press, that you should avoid challenging your readers.  If this blog were not challenging, then I would be wasting my time writing it and there would be no point in you reading it. 

The *Forbes* story also suggests that the blog’s ‘worst feature’ is being ‘Aussie-centric.’  The author of the story is perhaps unaware that one of the other eight economics bloggers profiled is a former resident of Australia.  My other objective in writing this blog has in fact been to challenge the parochialism that sometimes afflicts discussion of public policy issues.  An excellent example of this has been the attempt to frame debates about the US and Australian current account deficits and house price inflation in country-specific terms.  Yet clearly there is a much bigger story here involving changes in the saving-investment preferences and financial technology of the Anglo-American economies.  The cross-national perspective offered in this blog is hopefully a useful corrective to the more parochial perspective often found in the mainstream media, which still depends on a predominately local rather than global audience.
