---
title: "From Nostradamus to Krugman: 450 Years of Economic Doom-Mongering"
date: "2005-06-04"
categories: ["Economics"]
---

[Mark Mahorney](http://www.dailyspeculations.com/ "Mark Mahorney") has compiled an inventory of published economic doom-mongering, showing the remarkable persistence of the genre.  I’m sure there is a great behavioural finance paper to be written about our willingness to believe that the economic end is nigh, which is generally belied by the actual personal financial decision-making of most people.  I can think of at least one prominent market forecaster who must have a lot of canned food stocked in his basement if he takes his forecasts for the S&P 500 at all seriously!

The widespread adoption of general equilibrium theorising by the economics profession has actually encouraged the belief that any observed cycle must somehow be indicative of an irrational, and potentially ruinous, boom and bust.  The great contribution of Austrian economics is to show that disequilibrium is in fact the norm, not the exception.  It is a tragedy that much popular Austrian economics is these days so heavily implicated in doom-mongering, inspired by a gross misreading of its own tradition.
