---
title: "From Impossible to Inevitable: The End-Game for the Euro"
date: "2005-08-26"
categories: ["Economics"]
---

Even [Anatole Kaletsky](http://www.timesonline.co.uk/newspaper/0,,173-1749153,00.html "Anatole Kaletsky") is considering the end-game for the euro:

The most plausible such scenario is Italy withdrawing from the euro, under pressure from mounting unemployment, a weak economy and imploding public finances, exactly the same combination of pressures that forced Italy out of the ERM in 1992. If the possibility of Italian withdrawal were ever taken seriously by the markets, foreign holders of Italy’s €1,500 billion public debt would face enormous losses, since the Italian Government would simply convert its bonds into “new lire” and would legally get away with this conversion…

A break-up of the euro seems highly improbable in the next year or two. But anybody who still believes that such a break-up is impossible should bear in mind the lessons from the break-up of the ERM, the sterling, franc and lira devaluations of the 1960s, the collapse of the dollar-based Bretton Woods system in the early 1970s and the prewar abandonment of the gold standard. In confrontations between politics and financial markets, events can move straight from “impossible” to “inevitable” without ever passing through improbable.
