---
title: "Future Fund Chairman David Murray:  ‘The Money Belongs to the Government’"
date: "2005-11-28"
categories: ["Economics"]
---

Inaugural Chairman of the Future Fund David Murray makes things perfectly plain in this [interview with the Australian](http://www.theaustralian.news.com.au/common/story_page/0,5744,17383342%255E643,00.html "interview with the Australian").  The money in the Fund belongs to the government and it will do with it as it pleases:

the former chief executive of the Commonwealth Bank made it clear he did not see the fund operating at arm’s length from government like the Reserve Bank…

“The money doesn’t belong to the people in the fund, it belongs to the government and the community,” he said. “It has to be managed according to the direction of government…

“The Government has the right to determine what it does on behalf of the taxpayers in the community.”

Mr Murray said he was enthusiastic about accepting the offer to chair the Future Fund, as it was “well suited to my own approach”. “I believe very strongly in the concept of intergenerational equity,” he said.

“I believe in the community being good at saving and investing in the future.”

The Future Fund is based on the premise that the national saving task implied by an aging population should be met by the government setting itself up as an inter-generational financial intermediary, with the result that financial markets are partially nationalised by the Fund.  Does anyone seriously believe that a fund subject to direction by government will do a better job ‘saving and investing in the future’ than individuals?
