---
title: "GetUp!: ‘We Know Where You Live’"
date: "2005-08-15"
categories: ["Politics"]
---

[Glenn Milne](http://www.theaustralian.news.com.au/common/story_page/0,5744,16258916%255E7583,00.html "Glenn Milne") notes some interesting parallels between the corporate governance practices of the latte left and the nativist right:\

\
There is an eerie similarity between GetUp!‘s company structure and One Nation - a structure that could have allowed Pauline Hanson and her fellow company directors to walk away with millions in donations from supporters. And there are questions about the level of personal detail required by GetUp! from new members - detail that involves financial information and profiling tailor-made to establish a database for use in direct-mail campaigns during elections. Or for commercial purposes…

Much of the site is devoted to how to make a donation, starting with \$10 and with no upper limit. Money is also an issue if you choose to become a member of GetUp! But while the up-front pitch is all about political enthusiasm, the company’s actual constitution is much tougher when it comes to the question of money and membership.

It says: “By applying for membership the member agrees to pay the dues, fees, levies and other assessments imposed by the board and be charged interest at 10 per cent on any late payment, plus any expense incurred by the company because of failure to pay or late payment.” Its constitution also states: “The directors are entitled to the aggregate amount of remuneration that the general meeting determines from time to time.”

When you make a donation to the group you’re asked to provide not only your name and address, but your email address and your credit card number. When you become a member you’re also asked for an email picture of yourself plus a brief explanation of why you joined.

In political terms, this sort of information is an election campaign goldmine. While GetUp! states that it won’t “sell, trade or exchange your information without your permission”, it adds, “your information may be used to identify your location (electorate, state) and provide targeted and relevant opportunities for you to be part of our activities”.

...and a free set of steak knives.  In any other context, the left would be deeply suspicious.
