---
title: "Gittins Exposes His Own Bulldust"
date: "2005-09-12"
categories: ["Economics"]
---

Gittins effectively exposes his own caricature of those who argue for reductions in the highest marginal tax rates in [today’s column](http://www.smh.com.au/news/ross-gittins/nobulldust-case-for-cutting-top-tax-rate/2005/09/11/1126377202192.html "today’s column").  Reducing high marginal rates has never been primarily about inducing increased labour supply from high income earners.  Indeed, Gittins is the only person who takes this straw man at all seriously.  Lowering the top marginal tax rate has always been about removing costly distortions, a case he acknowledges in today’s column, albeit with the thinking done for him by ANZ chief economist Saul Eslake. 

Regular readers will note that I have important differences with other reform advocates on this issue.  In particular, I question the emphasis on removing concessions as the best way to lower rates, since this just leaves us with the same tax burden spread over a broader base.  I would prefer the emphasis to be on funding lower rates through net reductions in government spending.  But the general principle of seeking to align rates at lower levels is a sound one.

A closely related reason for lowering high marginal rates is eliminating the enormous waste of resources in tax planning, compliance and collection.  Very few high income earners pay the top marginal rate, but only after they have devoted considerable resources to avoiding it.  These resources all have opportunity costs attached.  What struck me most about being a taxpayer in Singapore was not the low rates (welcome though they were), but how little it cost me to comply with the law: a few minutes of my time and a postage stamp each year, with no need for an accountant, much less a lawyer.
