---
title: "Give Away Telstra"
date: "2005-11-26"
categories: ["Economics"]
---

You might not recommend Telstra shares to your mother, but few Mums and Dads would say no to them if they were given away for free.  In today’s Australian, Terry McCrann (no link) is once again arguing for Telstra to be given away rather than sold.  With a \$14 billion surplus looming in the Mid-Year Economic and Fiscal Outlook, the argument for privatising Telstra by lot seems more compelling than ever.  The government has effectively conceded it does not need the money by undertaking to place the proceeds from privatisation into a Future Fund, along with part of the budget surplus, where these funds will be used to buy other financial assets.  These assets are supposed to provide a revenue stream to fund future expenditures, but there is no real difference between meeting these expenditures out of current or future revenue.

Empowering individuals to provide for their own future needs by endowing them with financial assets is much less problematic than the government setting itself up as an inter-generational financial intermediary.  I have long argued that that any proceeds from the sale of Telstra should be rebated directly to the private superannuation accounts that every working Australian already owns.  Giving away the government’s remaining equity in Telstra amounts to much the same thing.
