---
title: "Globalisation and Current Account Balances"
date: "2005-02-26"
categories: ["Economics"]
---

McKinsey’s [Diana Farrell](http://news.ft.com/cms/s/fae8c6aa-7ad2-11d9-a8c9-00000e2511c8.html "Diana Farrell") on globalisation and the US current account:

Roughly one-third of the current account deficit results from US-owned subsidiaries abroad…

Trade between foreign affiliates (as offshore subsidiaries are called) and US companies and consumers can either inflate or diminish the current account balance. When Ford or General Motors produce vehicles in Mexico they sell many to American consumers, causing US imports to rise. But they also sell a significant number in Mexico, generating a positive income flow to the US current account, and they use technologies and components produced north of the border, boosting US exports.

Any net negative impact on the trade balance caused by foreign affiliates is more of an accounting anomaly than a cause for economic concern. Methods for measuring the current account date back to the 1940s, when few companies had operations outside their home countries.

A similar argument can be made in relation to Australia.  Since Australia has become a net exporter of direct investment capital in recent years, this implies that at least some of Australia’s current account deficit is being used to fund the globalisation of Australian business.

Meanwhile, Cato’s [Dan Griswold](http://news.ft.com/cms/s/3479b194-869b-11d9-8075-00000e2511c8.html "Dan Griswold") argues why the last thing you want is a trade surplus:

By the most basic measures of economic performance - GDP, manufacturing output and the unemployment rate - the US economy performs better in years when the current account deficit is rising than in years when it is shrinking. And it performs especially well in years when the current account deficit is rising most rapidly…

Those who seek the Holy Grail of a trade surplus should be careful what they wish for. Germany last year racked up a global surplus of almost \$200bn. Not entirely coincidentally, its unemployment rate reached 11.4 per cent in December and the number of unemployed reached a post-unification high of 5m people. The last time America’s jobless rate was that high was 1982 - when its own current account deficit was a measly \$5bn.

America’s trade deficit is essentially an accounting abstraction. Our attention should focus on what really matters - economic growth, job creation, industrial output, and the free and open markets that promote real growth.
