---
title: "Gloom, Doom and Boom Competition: We Have a Winner!"
date: "2005-06-01"
categories: ["Economics"]
---

This week’s record current account deficit once again provided rich pickings for our quarterly Gloom, Doom and Boom competition for overwrought reporting.  [AAP](http://www.theaustralian.news.com.au/common/story_page/0,5744,15463609%255E1702,00.html "AAP") deserves the Speedy Banana Award for referring to a ‘banana republic’ in a story just minutes after the release: 

*As a proportion of GDP, the current account deficit is around a record 7.2 per cent, prompting analysts to warn Australia is in danger of becoming a “Banana Republic”.*

Of course, no analyst was actually quoted as saying anything of the sort, suggesting that AAP was engaging in the usual colour-by-numbers financial market journalism.

[John Garnaut](http://www.smh.com.au/news/National/The-ball-is-in-Costellos-court/2005/05/31/1117305622815.html "John Garnaut") gets some credit for running a (somewhat selective) version of the consenting adults view of current account deficits, but [then disappoints](http://www.smh.com.au/news/National/Deficit-hits-another-record-and-retail-spending-slows/2005/05/31/1117305622807.html "then disappoints") when he says:

*The current account deficit, or CAD - which reflects the shortfall between exports and imports as well as financial transactions with the rest of the world - showed Australians paid foreigners \$15.6 billion more than they received from them in the three months to March.*

In fact the CAD shows the opposite – that foreigners lent us \$15.6bn to make-up the shortfall between domestic investment and saving.

[John Quiggin](http://johnquiggin.com/index.php/archives/2005/05/31/how-long-can-this-go-on/#comments "John Quiggin") (in comments) seemed almost ready to concede the consenting adults view, noting:

*Past experience would suggest either a recession or a sustained period of low growth, particularly in consumption. But we’re in uncharted territory here, and the optimists say global financial markets will look after us.*

As RBA Governor Macfarlane noted in his most recent testimony to the House Economics Committee, many people were declaring the US current account deficit unsustainable at 5%.  The new cyclical highs in the US and Australian current account deficits suggest that there has also been a structural deterioration in the current account balances of both countries.  Quiggin questions whether we are heading for a current account deficit of 10% of GDP.  In a world of floating exchange rates and mobile capital, there is no reason why such large deficits should not be possible.  Indeed, deficits of that size would be a massive vote of confidence in the Australian economy.

The lucky winner of our competition, however, goes to…

[Opposition Treasury spokesman Wayne Swan](http://www.smh.com.au/news/National/Deficit-hits-another-record-and-retail-spending-slows/2005/05/31/1117305622807.html "Shadow Opposition Treasury spokesman Wayne Swan"), who rolled out every current account cliché in the book:

*The shadow treasurer, Wayne Swan, said the figures were “humiliating” and jeopardised Australian living standards.*

In fact the figures underwrite Australia’s standard of living.  Lowering the current account deficit would require us to cut either consumption and/or investment to fit the silly prejudices of Swan and others who think they know better than markets what Australia’s saving-investment balance should look like.

*“As a nation, we’re living beyond our means, importing too much and borrowing far too much from the rest of the world,” he said.*

All of which is demonstrably untrue, unless you can make a compelling case for massive and systemic market failure.  You would think the Labor Party would learn from the fact that the Government is now being taunted by its own silly rhetoric on foreign debt from when it was in opposition.  A growing Australian economy requires a rising foreign debt and any political party that promises to reduce it is implicitly condemning us to a lower standard of living.
