---
title: "‘Gloom & Doom Amid Boom’ Competition Winner!"
date: "2005-03-02"
categories: ["Economics"]
---

We have a winner in our competition for the most overwrought commentary on Australia’s Q4 current account deficit. 

Competition was tough.  Stories with headlines screaming ‘banana republic’ were common entries.

I quickly lost count of how many stories made the claim that we are ‘living beyond our means.’  The Opposition Treasury spokesman also claimed ‘we are not paying our way,’ which would come as shock to international investors.  The fact that foreign investors are prepared to underwrite Australia’s consumption and investment make all of these statements demonstrably untrue.  It reflects the mindset behind the old homily, ‘neither borrower nor lender be,’ which taken literally would consign Australia to a state of near autarky.  The implication behind these statements is that we should cut our living standards to match only what we can produce for ourselves, a self-defeating solution to a non-problem.

Variations on this theme were also quite common.  BT Financial Group senior economist [Tracey McNaughton](http://www.theaustralian.news.com.au/common/story_page/0,5744,12416596%255E2702,00.html "Tracey McNaughton") said Australia was increasingly reliant on the ‘kindness of strangers’ to fund the deficit.  Tracey needs to brush-up on her Adam Smith: we rely on their self-interest, not benevolence, for our daily bread.

There were also plenty of stories that had the [air of moral panic](http://www.theage.com.au/news/National/Pressure-for-rate-increase/2005/02/28/1109546797121.html "air of moral panic"):

*Home buyers could be hit by higher interest rates within days after the release of figures showing a nation falling deeper into debt and racking up a massive bill for imported cars, electrical equipment and clothes.*

A nation awash in the excesses of cheap clothes from China?  The real story here is of course the enormous expansion in Australia’s consumption possibilities made possible by free trade in goods, services and, most importantly, capital.

The award for the most overwrought commentary, however, goes to…

[Tim Colebatch](http://www.theage.com.au/news/Tim-Colebatch/Were-on-a-long-and-slippery-slide-to-disaster/2005/03/01/1109546867448.html "Tim Colebatch"), economics editor at the *Spencer Street Soviet* (aka *The Age*), for his piece under the restrained headline ‘We’re on a long and slippery slide to disaster.’  Tim’s prose is not so much overwrought, as adolescent:

*Australia is still borrowing heaps.*

The rest of the piece is the sort of predictable partisan rant you would expect from *The Age*.  Thanks to my (anonymous) tipster, who saved me the bother of consulting the tiresome pages of the *Soviet*.  A copy of Robert Prechter’s *Conquer the Crash* is on its way.  If the current account doesn’t keep you up at night, Prechter just might.
