---
title: "Gloom, Doom and Boom Competition"
date: "2005-05-29"
categories: ["Economics"]
---

It’s time once again for our Gloom, Doom and Boom Competition based on the quarterly current account (released Tue).  Nominations for the most ridiculous and overwrought reporting on this release are now open.  Bonus points for gratuitous ‘banana republic’ references.  Can [Tim ‘Australia is still borrowing heaps’ Colebatch](../2005/gloom_doom_amid_boom_competition_winner.qmd "Tim ‘Australia is still borrowing heaps’ Colebatch") make it a double with his adolescent prose? 

The current account should post a new record deficit, although the Q2 headline GDP outcome should see an upside surprise relative to current market expectations, so this should keep the worst of the doom-mongering in check.

While on the subject of nonsensical reporting on current account balances, it should be mentioned that the less than efficient people at The Economist magazine have finally caught up with the fact that I haven’t paid my bill in more than a year and switched off my access to their web edition.  It would seem perverse to subscribe just to continue poking fun, but I would nonetheless be grateful for reader tips on the Economist’s contents.  This goes for other publications too of course.  I can only keep tabs on so much, so if you think I have missed something, feel free to bring it to my attention.
