---
title: "Government Loses Spin Control"
date: "2005-03-04"
categories: ["Economics"]
---

In the wake of this week’s national accounts and RBA rate rise, [JohnGarnaut](http://www.smh.com.au/news/Business/Standoff-as-PM-warns-on-rate-rises/2005/03/03/1109700614429.html "JohnGarnaut") quotes a ‘government economist’ as saying ‘I don’t know what the hell is going on.’

While I normally take unsourced quotes with a grain of salt, I can well believe this was said.  The PM and Treasurer made a complete hash of spinning this week’s events and give every indication of being poorly briefed.  The Q4 current account deficit, national accounts and RBA rate increase were unambiguous indicators of economic strength, not weakness.  If you believe the economy has ‘stalled,’ as many a headline suggested, then you must also think the RBA is completely insane.

Part of the problem is that the government has long trafficked in simplistic economic rhetoric, not least banging the foreign debt drum when it was in opposition.  You can only dumb things down so much before you get snared by your own nonsense.
