---
title: "Greenspan as Failed Guru"
date: "2005-07-20"
categories: ["Economics"]
---

[Peter Hartcher](http://www.smh.com.au/news/business/why-australia-has-outgrown-the-guru/2005/07/19/1121538973446.html "Peter Hartcher") continues the Greenspan bashing.  Implicit in Hartcher’s criticism of Greenspan, and praise of RBA Governor Macfarlane, is the idea that central banks can and should centrally plan asset prices through monetary policy.  Hartcher ignores the inconvenient fact that Governor Macfarlane has consistently argued against the wisdom of targeting asset prices in general, and house prices in particular.  But why let the facts get in the way of a lame story?

Then there is this anecdote:

\[Prime Minister\] Howard recalls vividly his first encounter with Dr Greenspan more than 20 years ago, when the economist, hearing that Mr Howard was from Australia, remarked: “Ah yes, Australia, the country with the biggest middle class in the world.”

The thought struck Mr Howard forcefully, and much of his political success since derives from his understanding of Australia as an aspirational middle-class society.  For John Howard, Alan Greenspan will always be a guru.

Somehow, I very much doubt John Howard’s famed political instincts owe much to Alan Greenspan.
