---
title: "Greenspan’s Legacy"
date: "2005-08-24"
categories: ["Economics"]
---

[Ken Rogoff](http://news.ft.com/cms/s/0baa9858-1400-11da-af53-00000e2511c8.html "Ken Rogoff") on Greenspan’s legacy:

*although many people believe that monetary stabilisation policy has been more central than ever under Mr Greenspan, his greatest success may have come from making it less so.\*
\
This is true up to a point.  Greenspan’s personal prominence as a central banker has probably led many people to overestimate the importance of monetary policy to macroeconomic outcomes, since people can much more readily identify with the notion of an individual being in personal control of interest rates than the more abstract and complex process by which monetary policy interacts with the economy and asset prices.

Evaluating Greenspan’s legacy on the basis of macroeconomic outcomes distracts attention from his more important institutional legacy.  Greenspan should have done more to ensure that his personal credibility was transferred to the institution of the Fed and formalised in reforms to the governance framework for US monetary policy.  The credibility of US monetary policy should not have to be re-built from scratch with every new Fed Chair.
