---
title: "HKSAR’s Dysfunctional Currency Board"
date: "2005-05-26"
categories: ["Economics"]
---

There is a minority tendency in classical liberal circles that retains a fetish for fixed exchange rate regimes, inspired by various hard money doctrines, despite the terrible havoc these regimes have wrecked on emerging market economies in recent years.  Contrary to what [Steve Hanke](../2005/steve_hankes_currency_board_fetish.qmd "Steve Hanke") might have you believe, Hong Kong’s currency board is no exception.  [Yeung Wai-Hong](http://online.wsj.com/article/0,,SB111696814888042122,00.html?mod=opinion%5Fmain%5Feurope%5Fasia "Yeung Wai-Hong") totes up the damage:

since the peg was put in place there have been repeated bouts of speculative runs on the Hong Kong dollar…In the name of defending the peg, the government ended up nationalizing more than a tenth of the blue chips traded on the stock market.

The hard earned reserves that the HKMA splurged on the foreign exchange and stock markets was not the only thing lost. By nationalizing privately held shares, Hong Kong also lost its long-held faith in the free market.

The peg withstood the financial storm, but a very much shaken Hong Kong suffered a sustained period of deflation that was the worst on record. In a misguided hope to revive the economy, the government took to industrial policy with a vengeance, pouring public funds into developing various “ports.” The most high-profile of these is Cyberport, a project aimed at spurring the growth of information technologies but which has turned out to be nothing more than a property project.

It is clear then the fallout from defending the peg has by no means been confined to the financial sector. Along the way, Hong Kong’s free market economy has taken on increasingly interventionist characteristics…

Currency boards are supposed to be automatic, self-adjusting mechanisms that operate without arbitrary interventions. Time and time again, this has turned out not to be the case.

Hong Kong might have a genuine need to raise local interest rates to let off some of the steam in the property market. The fact that the peg has failed to deliver the required interest rate rise testifies once again to the fact that the peg cannot, as promised, shield the economy from haphazard interventions, the raison d’etre to establish the peg in the first place.

A quarter of a century should be time enough to prove the validity of any theory. The verdict on the Hong Kong dollar peg is out: It has flunked. The need to defend the peg has led Hong Kong down an increasingly interventionist path that is incompatible with a free market economy.
