---
title: "How Many Unemployed Kiwis Would It Take to Fill Telstra Stadium?"
date: "2005-11-10"
categories: ["Economics"]
---

New Zealand’s [unemployment rate](http://www2.stats.govt.nz/domino/external/pasfull/pasfull.nsf/web/Media+Release+Household+Labour+Force+Survey+September+2005+quarter?open "unemployment rate") has fallen to its lowest on record at 3.4% and also the lowest among 27 OECD countries that report standardised unemployment rates.  Labour force participation is also at record levels.  The number of unemployed in New Zealand is now so low, they would leave more than 10,000 empty seats at Telstra Stadium for a Wallabies-All Blacks game.

By contrast, [Australia’s unemployment rate](http://www.abs.gov.au/ausstats/abs@.nsf/Lookup/9FF2997AE0F762D2CA2568A90013934C "Australia’s unemployment rate") in October was 5.2%.  While still close to 27 year lows, the differential with NZ highlights Australia’s failure to tackle labour market reform.  The Australian government’s proposed IR reforms are decidedly inferior to the NZ model.  While they may still assist in lowering Australia’s unemployment rate, the differential with NZ shows the extent to which unemployment in Australia is a deliberate policy choice, wilfully ignoring a superior reform model across the Tasman.
