---
title: "Howard and Minchin as Revenue Hoarders"
date: "2005-03-16"
categories: ["Economics"]
---

If recent comments by the [Prime Minister](http://www.theaustralian.news.com.au/common/story_page/0,5744,12560099%255E2702,00.html "Prime Minister") are anything to go by, we can rule out a meaningful reduction in the overall tax burden in the May Budget and probably for the life of the current Parliament.  The government remains wedded to the view that tax cuts can only be funded out of the surplus, with the PM saying:

*If we are able to give further tax relief **after** we have provided for essential spending, and that’s defence, health and roads and all of those things, **and** provided we have a strong budget surplus.* (emphasis added)

In the government’s view, tax relief is a residual that can only be paid for out of the surplus.  The surplus is simply too small to accommodate a meaningful tax cut.  Tax cuts out of the surplus would only serve to hand back a portion of bracket creep, not reduce the overall tax burden.  The only way in which the government can fund a meaningful reduction in taxes is through reductions in government spending.  Unfortunately, the government’s record on expenditure restraint leaves much to be desired.

Equally disturbing is Finance Minister Nick Minchin’s proposal to take the proceeds from the privatisation of Telstra and invest them in a managed equity fund at arms length from the government.  The alternative of paying down debt would entail the effective elimination of the Commonwealth government bond market.  I have no objection to the elimination of the bond market, but since we are only a recession away from the government again having to raise funds in capital markets, we might as well keep it in place.  But selling equity in Telstra only to acquire an equity portfolio run by private fund managers shows that the government’s primary motivation is to hoard the income stream from this asset. 

If the government were genuinely interested in using the proceeds from the sale of Telstra to offset future demands on government spending, then it could simply deposit the proceeds from the sale of Telstra into the private superannuation accounts that every working Australian already owns.  A formula could be devised to ensure that low income earners benefited most from this process.  This would be very similar to privatisation by lottery and would constitute a transfer of wealth from the public sector to the private sector that would reduce the future demands on government from an aging population much more reliably than an income stream that simply accrues to consolidated revenue.
