---
title: "Howard-Peacock Rivalry"
date: "2005-08-22"
categories: ["Economics"]
---

As a veteran of the Howard-Peacock wars of the 1980s and 1990s, I could not help but notice the juxtaposition of these two stories:

[PRIME Minister John Howard](http://www.news.com.au/story/0,10117,16341734-29277,00.html "PRIME Minister John Howard") tonight becomes the first Australian to receive a prestigious American public service award.

It will be the first time anyone outside North America or Europe receives the Woodrow Wilson Award for Public Service.\
\
\* \* \*

Former federal Liberal Party leader and ambassador to the United States, [Andrew Peacock](http://www.smh.com.au/news/National/Peacock-charged-with-drink-driving/2005/08/22/1124562774963.html "Andrew Peacock"), has been charged with drink driving after a crash in Sydney.

Police were called to a service station on New South Head Road in Rushcutters Bay, in Sydney’s east, about 1.30am Sunday after a 2005 model Mercedes Benz hit a power pole.

Mr Peacock, 66, of Double Bay, was charged with mid-range PCA after a breath analysis allegedly showed a 0.08 blood-alcohol content.

He was released on bail and his licence suspended.

Mr Peacock will face Waverley Local Court on September 13.
