---
title: "Incredulous Cultists"
date: "2005-11-17"
categories: ["Economics"]
---

The latest data confirming record foreign demand for US assets and a decline in official sector purchases leaves the [doomsday cultists](http://www.rgemonitor.com/blog/setser/107949 "doomsday cultists") simply incredulous:

*if you believe the data, almost all the financing came from private investors abroad, who bought about \$114 billion of US securities.  That total includes around \$90 billion of long-term debt.  Corporate bonds were particularly popular.  Central banks only bought \$4 billion.  I don’t believe that.*

Brad is right to highlight the limitations of the TIC data.  However, given recent gains in the USD index to two year highs, a reduction in foreign official sector purchases should come as no surprise, since there is less pressure on the managed exchange rate regimes of foreign central banks.  There have even been suggestions that the Bank of Japan might soon intervene in foreign exchange markets to sell the USD.  I’m far from convinced that such intervention is imminent, but if the BoJ turned a net seller of USD assets, this would pose a serious challenge to the view that the US is in any meaningful sense dependent on foreign central bank purchases of USD assets.
