---
title: "Industrial Relations Reform"
date: "2005-11-04"
categories: ["Economics"]
---

The [real problem](http://www.theaustralian.news.com.au/common/story_page/0,5744,17134438%255E601,00.html "real problem") with the government’s IR reforms:

The Government’s laws, introduced into parliament this week, are much more complicated than the Fightback! industrial relations package that Mr Howard, then a Coalition frontbencher, launched in 1992 with former Liberal leader John Hewson.

New Zealand’s Employment Contracts Act runs to 100 pages, with the core legislation in just 20. By contrast, the Howard Government’s WorkChoices legislation is almost 700 pages long and is accompanied by an explanatory memorandum of 560 pages.

In 1990, New Zealand’s Bolger government took the radical approach of abolishing the country’s highly prescriptive award system and regulating tribunal.

In their place, it imposed a minimum wage and basic employment conditions.  All workers were employed under individual contracts, with conditions left to the market.

Despite disputed figures on productivity, New Zealand now boasts an unemployment rate of 3.5 per cent while Australia’s official rate hovers at about 5per cent - still the lowest here for more than two decades.
