---
title: "Inflation Targeting and Fed Governance"
date: "2005-10-28"
categories: ["Economics"]
---

[Greg Mankiw](http://online.wsj.com/article/SB113046234369582079.html?mod=opinion_main_commentaries "Greg Mankiw") echoes some of this blog’s arguments for reform of Fed governance:

Some recent news reports have suggested that inflation targeting would mean a big change in policy from the Greenspan era. That is not right. Starting where we are today, a switch to inflation targeting is not so much a change in monetary policy as it is a change in the way the Fed communicates about monetary policy. To a large extent, Mr. Greenspan’s policy can be described as “covert inflation targeting.” He has never announced a target inflation rate, but there is little doubt about his goals. As former Fed governor Laurence Meyer pointed out, anyone who doesn’t know that Mr. Greenspan is aiming for a measured inflation rate of about 1% to 2% is just not paying attention…

Alan Greenspan is a rock star, at least by the standards of the American Economic Association… The most negative assessment I have ever heard about Ben Bernanke, from one of my colleagues, is that he is “a bit boring.” For an economist, boring is an occupational hazard. For a central banker, however, it is just the ticket. The central bank’s job is to create stability, not excitement. Ben Bernanke would do well to increase public confidence in the institution of the Federal Reserve: The institution matters more than the individual who happens to be leading it at the moment. It would be ideal if, after a long, successful tenure, Mr. Bernanke’s retirement as Fed chairman were a less momentous event than his arrival.

**UPDATE:**  Free version [here](http://www.aei.org/publications/filter.all,pubID.23389/pub_detail.asp "here").
