---
title: "Johan Norberg in Sydney"
date: "2005-10-12"
categories: ["Economics"]
---

The Centre for Independent Studies has been playing host to [Johan Norberg](http://www.johannorberg.net/ "Johan Norberg") this week.  I attended the launch of the [Australasian edition](http://vs19901.server-store.com/store/products/item311.inetstore "Australasian edition") of his book *In Defence of Global Capitalism* on Monday and his [John Bonython Lecture](http://www.cis.org.au/ "John Bonython Lecture") last night, an op-ed rendition of which can be found [here](http://www.theaustralian.news.com.au/common/story_page/0,5744,16889149%5E7583,00.html "here").  Norberg’s theme of the cognitive biases that motivate anti-globalisation sentiment is remarkably consistent with some of the arguments run on this blog in relation to financial markets and asset prices. 

Norberg’s book is perhaps the most accessible and persuasive defence of globalisation in print.  The book is much more faithful to the classical liberal tradition than the books on globalisation by Jagdish Bhagwati and Martin Wolf.  Both Bhagwati and Wolf concede way too much to globalisation’s critics and have probably done the cause more harm than good, particularly in the case of Bhagwati’s hostility to international capital mobility.
