---
title: "John Howard’s Welfare State"
date: "2005-09-13"
categories: ["Economics"]
---

Guess who wrote the following?

Only John Howard could deliver the socialist dream: a welfare state that supplies more than 14 per cent of household disposable income, up from 9 per cent at the end of the Hawke government and 6 per cent in the Whitlam era.

Since the Howard Government came to office in 1996, real disposable incomes have risen by about 15 per cent and unemployment has fallen to its lowest level in 30 years. That’s good. But it also means welfare dependency has fallen sharply.

So why has the Howard Government increased real social security spending by almost half? The answer has nothing to do with national welfare dependency and everything to do with politics. Howard’s welfare state has been highly effective in taxing single people and couples without children and giving the proceeds to couples with children…

The latest Treasury Economic Round-up backs the findings reported in The Australian. It reveals that almost 40 per cent of families receive more in welfare than they pay in tax…

But the welfare state is out of control. The wealthy do not need government cash handouts and low and middle-income earners don’t need the punishing tax rates used to finance them.

[Labor MP Craig Emerson](http://www.theaustralian.news.com.au/common/story_page/0,5744,16578234%255E7583,00.html "Labor MP Craig Emerson").  We look forward to hearing what the Australian Labor Party intends to do about it.
