---
title: "Ken Henry and the Classics"
date: "2005-06-21"
categories: ["Economics"]
---

The [Secretary of the Treasury](http://www.treasury.gov.au/contentitem.asp?NavId=008&ContentID=996 "Secretary of the Treasury") calls for a return to classical economics as the basis for macroeconomic policy:

one has to wonder whether the policy debate in this country is not the sort of thing that one might have hoped to see in a ‘classical’ economy of the sort that economists thought existed before the Great Depression and the ensuing Keynesian revolution; a debate about the factors that influence our productive capacity rather than the factors that influence our demand for it.

This shift in policy attention – from pre-occupation with the management of effective demand to an interest in the things that affect aggregate supply – is timely since, especially for demographic reasons, the principal macroeconomic issue of the very near future will be inadequate participation, not unemployment – a problem of too few people wanting a job, not too many…

It might be worth asking the question whether, because of the reform efforts of the past, we should not now consider ourselves to be most often in a ‘classical’ world in which the economy naturally trends toward, and in fact spends most of its time quite close to, its productive capacity, or supply potential, without the need of continuous macro policy stimulus.

Answering this question in the affirmative would not imply a view that we have eliminated the business cycle. There will be future economic downturns. And when we see evidence of one we should not be afraid of responding with activist expansionary macroeconomic policy.  Rather, an affirmative answer implies some conditioning of the exercise of macro policy activism – an acceptance that large swings in macro instruments are to be implemented (only) in extremis.\
