---
title: "Libertarian-Conservative Monetary Policy Doves"
date: "2005-05-03"
categories: ["Economics"]
---

[Alan Reynolds](http://www.cato.org/pub_display.php?pub_id=3752 "Alan Reynolds") joins other libertarian and conservative commentators in calling into question the Fed’s tightening bias:

*I have avoided complaining about the Fed being too tight since co-authoring a Wall Street Journal article to that effect in October 2000 (and before that, only in mid-1982 and 1984). If asked today if the Fed should again raise interest rates anytime soon, however, my answer is no. The domestic and global economic risks of raising dollar interest rates are real—the inflation scare is not.*

There has been an interesting role reversal for libertarian and conservative think-tanks in relation to monetary policy over the last 15 years or so.  Whereas their commentary once focussed on the inflationary bias of central banks, the Fed would now appear to be a good deal more hawkish than they would like. 

The [Shadow Open Market Committee](http://www.somc.rochester.edu/ "Shadow Open Market Committee") now focuses much of its effort on encouraging reform of the institutional framework for US monetary policy.  This is the correct focus for debate, since improvements in this framework should generally lead to improved policy outcomes.
