---
title: "Malcolm Turnbull as De Facto Treasurer"
date: "2005-12-16"
categories: ["Economics"]
---

The increased budget surplus reported in Mid-Year Economic & Fiscal Outlook has seen the usual [spate of calls](http://www.theaustralian.news.com.au/common/story_page/0,5744,17584052%255E601,00.html "spate of calls") for further tax reform.  However, the budget surplus should in no sense be viewed as defining the scope for further reform.  Meaningful reform needs to go well beyond a handing back of a portion of the surplus and extend to a complete overhaul of the current system of tax concessions and Commonwealth government spending, particularly the middle class welfare churn, which sees many households paying no net tax.  This makes wholesale tax reform readily affordable out of existing government spending programs.

This point is clearly understood by Malcolm Turnbull, who (perhaps not coincidentally) gave a [speech](http://www.turnbullforwentworth.org.au/news/default.asp?action=article&ID=366 "speech") on tax reform yesterday coinciding with the Treasurer’s release of the MYEFO.  Turnbull draws on President Bush’s Tax Reform Panel to argue for what amounts to a radical re-think of the tax system.  Turnbull is even willing to put a flat tax and the abolition of taxes on saving, such as capital gains tax, on the table:

*A flat tax is not, of course, truly flat. Flat tax systems impose a single tax on income with the broadest possible definition and with very few deductions. Progressivity, or vertical equity, is maintained by having a tax free threshold which can be adjusted for family size. There is no need whatsoever for a flat tax to be regressive.\
 \
The greatest economic benefit claimed for so called flat taxes is that income is taxed only once: either at the business level or at the household (or wage earner) level. This means that income from investments be it interest or capital gains is not taxed in the hands of the recipient, although of course when it is spent it is taxed because it becomes income in the hands of the business or individual who receives it. This reduces the bias against savings and investment which slows capital formation and as a consequence wage growth.*

Compare and contrast Treasurer Costello’s most recent [speech](http://www.treasurer.gov.au/tsr/content/speeches/2005/017.asp "speech") on tax to the Global Tax Forum, which was essentially arguing for the cartelisation of international taxation and enhancing ‘national tax sovereignty.’  Who would you rather have as Treasurer?
