---
title: "Meta Bubbles and Contrarians"
date: "2005-07-17"
categories: ["Economics"]
---

We have previously noted the bubble in bubbles phenomenon, not least in relation to economics blogs.  The [LA Times](http://www.latimes.com/business/la-fi-homeblog16jul16,0,4466799.story?coll=la-home-business "LA Times") notes the growing prevalence of blogs dealing with the alleged housing bubble.  While I am generally dismissive of the notion of bubbles in asset markets, I’m less dismissive of the idea of a bubble in bubble-talk.  Bubble-talk is effectively unpriced, because those who engage in it, unlike participants in asset markets, rarely put their money where their mouth is.  While some have a professional reputation to defend, accountability for bubble-talk can often be fudged.  As for the rationality of bubble-talk, consider the representative housing bubble blogger profiled in the LA Times story, who imagines Alan Greenspan secretly reads his blog:

A self-described “economic activist,” Jones, 41, sees his mission as chronicling a seminal financial event, something future scholars can turn to just as historians today would read an anthology of letters written by Dutch tulip traders in the 1630s.

“In 100 years, economists may be studying the comments of this blog because this was a real-time skeptics’ log in the middle of a financial mania,” said Jones, who rents a house with his wife in Sedona, Ariz., and doesn’t own any real estate.

Traditionally, those who drew attention to bubbles were considered contrarians, ie they were notable for going against the crowd.  The bubble in bubble-talk has resulted in something of a role reversal.  It is the bubble skeptics who are now the real contrarians.
