---
title: "Misguided Monetarism: Tim Congdon’s Money and Asset Prices in Boom and Bust"
date: "2005-10-24"
categories: ["Economics"]
---

My review of Tim Congdon’s (2005) *Money and Asset Prices in Boom and Bust*, London: Institute of Economic Affairs.

Tim Congdon is perhaps best know for his former role as head of Lombard Street Research and his membership of the IEA’s Shadow Monetary Policy Committee, which is loosely modelled on the monetarist Shadow Open Market Committee in the US.  *[Money and Asset Prices](http://www.iea.org.uk/record.jsp?type=publication&ID=291 "Money and Asset Prices")* seeks to motivate a role for broad measures of the money supply in the determination of asset prices.  Congdon subscribes to the ‘active money’ paradigm, which is at odds with the mainstream academic view that money plays an essentially passive role in an economy because it is endogenous to the determination of official interest rates and money demand.  The ‘active’ money view is, however, probably closer to popular conceptions of how monetary policy works.  Popular commentary on monetary policy is often framed in terms of some vaguely defined notion of ‘liquidity,’ even though monetary aggregates play only an incidental role in the determination of official interest rates.

There are a range of views on the monetary policy transmission mechanism within the active money paradigm.  Congdon notes that leading monetarist Allan Meltzer ‘disagrees with the main thesis of this paper’ and that Milton Friedman has supplied ‘some of the best criticism of my work in the last two years’ (p. 17).  Congdon does not indicate what these criticisms were, but those familiar with, or sympathetic to, the monetarist tradition will find plenty to object to in Congdon’s book.  The problem is not so much that he fails to establish a role for broad money in the determination of asset prices (there may indeed be such a role), but that he fails to demonstrate the relevance of this claim for contemporary monetary policy practice.

The demise of the active money paradigm has been closely associated with evolution of central bank operating procedures, which have come to focus exclusively on short-term official interest rates as both the instrument and transmission mechanism of monetary policy.  Monetarists have always objected to this characterisation of the transmission process, arguing that monetary aggregates also play an independent role in the determination of real output, inflation and asset prices.  A key issue for the active money view is whether this role remains when the money supply is endogenous to the determination of an official interest rate and money demand. 

Monetarists like Meltzer have argued persuasively that money retains a role in the transmission process under an interest rate targeting regime.  However, the connection between broad money aggregates and central bank policy actions is likely to be weakened where central banks are targeting an official interest rate.  While the money base can be expected to retain a close relationship with changes in official interest rates given prevailing central bank operating procedures, broader monetary aggregates are likely to have a much looser relationship, with market-driven changes in financial intermediation, technology and preferences potentially dominating observed growth rates in these aggregates.

This is the basis for the ‘narrow’ money interpretation of the monetary policy transmission mechanism favoured by most monetarists, but criticised by Congdon.  In particular, Congdon takes issue with the narrow money views of Patrick Minford, a fellow member of the IEA’s Shadow Monetary Policy Committee and of the rival forecasting firm, Liverpool Macroeconomic Research Ltd.  Congdon maintains that only the broadest of monetary aggregates fully captures the portfolio choices made by the public.  This may well be true, but it is at odds with the main concern of the active money paradigm, which is *exogenously* driven changes in monetary aggregates attributable to central bank policy actions.  Portfolio choices in relation to broader monetary aggregates are probably important to the overall transmission process, but we need to distinguish carefully between those changes that are driven by monetary policy and those that are simply endogenous to broader economic developments.  This is a difficult exercise, since even changes in official interest rates can be viewed as at least partly endogenous to economic conditions.  Economists accordingly devote considerable effort to trying to identify the exogenous and endogenous components of monetary policy.

Congdon does not provide us with any basis for making this crucial distinction.  His case studies of the UK, the US and Japan seek to show a relationship between economic activity, asset prices and developments in relation to broad money aggregates.  Although Congdon claims a causal role for broad money aggregates, his empirical evidence is just as consistent with simple correlation and would not convince anyone not already converted to the active view of money.  While broad monetary aggregates may well have the causal role Congdon claims for them, this leaves open the question of what determines the growth rate in these aggregates.  As Congdon notes, changes in the growth rate for broad monetary aggregates are often associated with changes in official interest rates.  While monetary aggregates may well be important in the transmission of changes in official interest rates, this does not establish a causal role for broad monetary aggregates that is independent of these policy actions. 

Congdon himself seems to recognise this issue when he says in a footnote that ‘a broad money measure may nevertheless be endogenous in the sense that it reflects processes within an economy, and particularly processes inside the banking system, subject to price incentives.  But the endogeneity of broad money in this sense still leaves it with the ability, when disturbed from an equilibrium level, to change asset dispositions and expenditure patterns’ (p. 80).  Indeed it does, but what is the relevance of this claim?  Even if we allow an independent causal role for broad money aggregates in the determination of asset prices, it is not clear that this has significant implications for monetary policy in practice.  If Congdon’s claim is no more than that we should pay attention to whatever information monetary aggregates might contain for asset prices and the broader economy, then this is essentially unobjectionable.  Monetary policy should make use of all available information.  Congdon stops short of arguing that monetary policy should target specific growth rates in monetary aggregates or asset prices.  This is just as well, because for monetary policy to target specific growth rates in a broad measure of the money supply (as opposed to the money base) would probably require the extensive re-regulation of financial intermediation.  Recall that it was the financial deregulation of the late 1970s and early 1980s that brought an end to earlier attempts at targeting broad monetary aggregates, by injecting instability into the money multiplier than converted central bank policy actions into changes in broader monetary and credit aggregates.

Congdon is correct in arguing against the proposition that the volume of credit or bank lending is important in the determination of asset prices.  While he is also correct in assigning a potential role for broad money in the determination of asset prices, this in itself does not establish a basis for significant changes in central bank operating procedures or the intermediate and final targets for monetary policy.  Instead, Congdon risks giving aid and comfort to those who would seek to re-regulate financial markets and manage asset prices in ways that could be far more troublesome than the role of the money supply in asset price fluctuations.  Like asset prices, developments in broad monetary and credit aggregates reflect capitalist acts between consenting adults.  If broad money aggregates have a causal role in the determination of asset prices, then claiming that we know the appropriate growth rates for these aggregates is equivalent to claiming we know the correct level or growth rate for asset prices. 

Congdon is clearly motivated by a desire to reduce the boom-bust cycle that previous monetary and exchange rate policy mistakes have inflicted on the UK economy.  But these mistakes did not occur because of a lack of attention to monetary aggregates and it would be wrong to conclude that the business cycle could be more effectively smoothed or eliminated through their manipulation at the expense of more conventional approaches to the conduct of monetary policy.  While Congdon is right in arguing that we should pay some attention to money as an information variable, he is wrong in claiming such a central role for broad monetary aggregates in the determination of asset prices.  His arguments have at best limited, and at worst dangerous, implications for monetary policy practice.
