---
title: "More Euro Scepticism"
date: "2005-07-14"
categories: ["Economics"]
---

More euro scepticism, this time from investment bank HSBC, as reported in the [Torygraph](http://www.telegraph.co.uk/money/main.jhtml?xml=/money/2005/07/12/cneuro12.xml&menuId=242&sSheet=/money/2005/07/12/ixcity.html "Torygraph"):

In a new paper entitled “European meltdown?”, the world’s second biggest bank said Italy, Germany, and Holland had all been damaged by the perverse effect of the one-size-fits-all interest rate policy, and might be tempted to leave.

It said the euro had pushed Germany to the brink of deflationary spiral, while causing a “dramatic boom and bust” in Holland. At the same time, Italy was now trapped in slump with a “truly appalling export performance” and exorbitant unit labour costs.

The report said the risks of break-up had now reached a point where it had become necessary to “think more carefully about the costs and benefits of exiting”.

HSBC said Germany might choose to leave in order to cut real interest rates, regain control of fiscal policy, and fight deflation by resorting to the sort of “unconventional” monetary methods in vogue in Tokyo and Washington - but denied by EU law to the European Central Bank.
