---
title: "More Monetary Policy Central Planning from the AEI"
date: "2005-07-26"
categories: ["Economics"]
---

The [AEI](http://www.aei.org/publications/filter.all,pubID.22898/pub_detail.asp "AEI") is at it again, advocating that the Fed should fine-tune US house prices:

*the Fed is raising interest rates, a central-bank policy move that has already quelled a housing boom in the United Kingdom, not to mention Australia and New Zealand. We need a “Goldilocks Tightening” that sets the temperature in the real estate sector just right: not too hot and not too cold.*

Unlike many commentators, Makin acknowledges the prevalence of variable rate mortgages in the UK and Australia, but nonetheless argues that ‘the ability of rate increases \[of the magnitude of past US tightening cycles\] to slow the rate of increase of housing prices is not in question.’  Fine tuning house prices via monetary policy is still a risky proposition, even in Australia, where RBA Governor Macfarlane has argued against it along similar lines to the arguments made by Alan Greenspan.  It is an infinitely more risky proposition in the US, where the relationship between the Fed funds rate and mortgage rates is much looser. 

Makin’s article acknowledges the difficulties of fine-tuning monetary policy.  Indeed, as recently as late last year, Makin was arguing against further Fed tightening on the basis that it would plunge the US into recession in 2005.  The obvious conclusion to draw is that the Fed should not determine monetary policy on the basis of house or other asset prices, but because Makin is one of many analysts who take a ‘bubble’ in house prices as a given, he draws the opposite conclusion.  This is a good illustration of how bubble-talk can lead analysts astray.  Indeed, there is something profoundly absurd about the fact that central bankers like Greenspan and Macfarlane have become the de facto defenders of capitalist acts between consenting adults, while right-wing American think tanks have become advocates of the central planning of asset prices.
