---
title: "More on Pop Austrianism and the Business Cycle"
date: "2005-02-22"
categories: ["Economics"]
---

A key element of the pop Austrian critique of contemporary monetary policy is that the inherent unevenness of the process by which newly created base money and inflation work their way through an economy creates a structure of production that a free market economy would not otherwise support (the [Ludwig von Mises Institute](http://www.mises.org "Ludwig von Mises Institute") has plenty of examples of this sort of claim).  In the Austrian view, growth in broad money, credit aggregates and even asset prices is built on a house of cards: fiat money leveraged through fractional reserve banking.  Even those Austrians who accept fractional reserve banking consequently see almost any central bank policy action as inherently destabilising. 

A major problem with this view is that there is no necessary connection between interest rate targeting by central banks and the money base (although in practice they are usually closely linked by the operating procedures currently favoured by monetary authorities).  In principle at least, we could have a market-determined money supply and even non-centralised clearing of overnight inter-bank lending and yet still have a central bank successfully targeting an official short term interest rate through its willingness to buy and sell relevant instruments at given prices.  Unless we define free banking as the complete absence of a central bank, there is no reason why the two institutions could not co-exist.

This is an interesting thought experiment, because it is not a fundamental departure from current monetary policy regimes and yet it severs the link that the pop Austrians take for granted between central bank policy actions and the money supply.  Austrians could no longer rely on the view that growth in monetary and credit aggregates is simply leveraged fiat money created by the central bank. What would such an economy look like?  My guess is much the same as economies under existing monetary regimes, because one of the key transmission mechanisms for monetary policy would still be intact, namely, that from short-term interest rates to economy-wide asset prices.  In my view, Austrians need to refocus their critique of central banking and instead consider the ways in which a market-determined monetary system and its role in the business cycle could in fact be very similar in practice to what we have now.

What this thought experiment also makes clear is that much of the growth in broad money and credit aggregates, as well as asset prices, actually reflects capitalist acts between consenting adults, with central bank influence typically limited to anchoring the short end of the yield curve and base money creation playing a very subordinate role.  Indeed, that is why central banking is ultimately dispensable, which is a more powerful critique than the claim the central banks are destabilising.

Pop Austrian proposals to return to various hard money regimes and outlaw fractional reserve banking are in many ways the antithesis of the sort of monetary system likely to emerge under a free market system in which central banks no longer control either the money base or an official interest rate.  A market-determined money supply is likely to result in an economy very much like the one we have now, with growth in broader monetary aggregates, credit and asset prices determined by individual preferences and the technology of the financial and payments systems.  There will still be a business cycle and asset price booms and busts, driven by decentralised decision-making and the market discovery process.
