---
title: "More Budget Reaction"
date: "2005-05-12"
categories: ["Economics"]
---

The Budget tax cuts are being [criticised](http://johnquiggin.com/index.php/archives/2005/05/11/the-budget/ "criticised") for delivering larger dollar amounts to those at the upper end of the income scale.  In part, this is just a reflection of the fact that those who earn more pay more tax.  The assumption behind this criticism is that tax relief should primarily be about redistribution rather than efficiency.  The most significant welfare costs arising from taxation, however, are attributable to the top marginal rates, not those that apply further down the income scale.  The higher the rate, the greater the distortion to economic decision-making.  What I found most revealing about my experience as a taxpayer in Singapore was how little my decision-making was distorted by tax considerations compared to when I was in Australia. 

[Greg Sheridan](http://www.theaustralian.news.com.au/common/story_page/0,5744,15256514%5E25377,00.html "Greg Sheridan") discusses how this soak-the-rich mindset damages the prospects for genuine tax reform:

Costello and most ministers privately acknowledge the top rate is too high. But if they cut it they fear the media will find some millionaire who gets a huge dollar tax cut and flay them for it. What a custardy bunch of cowards. If ever you were going to enact such a reform it would be now, in the first budget after an election. It could easily be sold on its incentive effects. And abolishing the top rate next year, when it will apply to only 3per cent of taxpayers, would only cost another \$2billion.

You’d never expect Australia to compete with an equally rich society such as Singapore, with its top rate of 22per cent, but that after a decade of a free-market government we can’t even compete with the US, with a top federal rate of 35per cent, or, God help us, New Zealand, with its top rate of 39per cent, shows just how modest recent reforms have been.

For all the talk of our world-beating performance we still have a lower per capita income than many comparable countries.

This weakness in reform reflects a weak Australian conservative intellectual tradition. Nothing is a more perfect illustration of this than the ridiculous new movie Three Dollars.

Don’t miss Sheridan’s review of the film.
