---
title: "More Rubbish from the AEI"
date: "2005-05-10"
categories: ["Economics"]
---

Who would you expect to be a more reliable defender of market outcomes and capitalist acts between consenting adults: a right-wing American think-tank; or a former adviser to an Australian Labor Prime Minister?

The AEI’s [Desmond Lachman](http://www.aei.org/publications/filter.all,pubID.22477/pub_detail.asp "Desmond Lachman") has written to the FT, criticising John Edward’s view (canvassed on this blog previously) that Australia’s current account deficit is a benign product of an investment boom, with national saving as a share of GDP remaining little changed in recent years. 

We have previously discussed Lachman’s views on the US current account, so his take on Australia’s deficit (which unlike the US deficit is *entirely* the product of capitalist acts between consenting adults) should not come as a surprise.  But it is still incumbent upon Lachman to explain why he thinks there has been a market failure in relation to these outcomes.  Otherwise, he is simply imposing his own prejudices in relation to what he thinks are desirable outcomes in relation to the trade balances, dwelling investment and other macro variables.  Either way, the AEI would seem to have little respect for or appreciation of market outcomes and certainly a good deal less than a social democrat like Edwards.
