---
title: "Non!  Right Decision, Wrong Reasons"
date: "2005-05-30"
categories: ["Economics"]
---

France has made the right decision for the wrong reasons on the EU Constitution.  As [David Carr](http://www.samizdata.net/blog/archives/cat_european_union.html "David Carr") puts it:

To all French crypto-communists, syndicalists, marxists, trotskyites, leninists, stalinists, national socialists, socialist nationalists, primitivists, Trade Union dinosaurs, student activists, greenie nutters, neo-fascists, old fashioned fascists, quasi-crypto-troglodyte-Pol-Pottist-year zero-flat-earthers, looney tunes and enviro-goons….Merci Beaucoup!!!!

I could kiss every single one of you.

You first Dave!  Unfortunately, we can take little comfort from the result because, as incredible as it may seem, many French people saw a ‘no’ vote as a rejection of market liberalism. 

It is disturbing the extent to which the EU project is still taken as given among elite opinion, despite being rejected on most occasions when EU institutions are actually put to a popular vote and growing evidence that foundational EU institutions like the euro are hopelessly flawed.  A good example of this thinking is [Anatole Kaletsky’s](http://business.timesonline.co.uk/article/0,,8210-1633498,00.html "Anatole Kaletsky’s") analysis attributing the failure of the referendum to the European Central Bank’s monetary policy:

*Europe’s economic failure can be blamed largely on the mismanagement of the euro project and the incompetence of the European Central Bank (ECB)…\[and\] do-nothing monetarist dogmatism of the ECB…The next recourse should be to call for the resignation of the ECB management, since they should be held accountable for the public rejection of the European project.*

It apparently does not occur to Kaletsky that problem is the euro project itself, no matter how well managed, and that maybe the ECB is doing the best we could reasonably expect within the constraints of a single currency.  Critics of the euro having been warning of these very outcomes for years.  An easier monetary policy would do nothing to address Europe’s structural problems.

The danger is that the more EU institutions fail, the more politicians will resort to ad hoc fixes, rather than re-thinking the EU project itself.  The euro has already seen the Stability and Growth Pact effectively junked, removing an important institutional protection of monetary stability in Europe.  Kaletsky calls for European finance ministers to direct the ECB to engage in foreign exchange market intervention and even goes so far as to suggest that the legislative basis for ECB independence should be renegotiated.  It is in fact Kaletsky who is blinded by dogmatism in refusing to see that the euro project is fundamentally flawed.  In Europe, nothing succeeds like failure.
