---
title: "Not the Federal Budget"
date: "2005-05-05"
categories: ["Economics"]
---

Ahead of next week’s Federal Budget, it is worth pondering what a government serious about tax and expenditure reform could achieve.  [Des Moore, under auspices of the ACCI](http://www.acci.asn.au/text_files/Discussion%20Papers/Cutting%20Government%20Spending.pdf "Des Moore, under auspices of the ACCI"), presents the Budget we would like to see, but almost certainly won’t:

Analysis of Commonwealth spending/revenue concessions indicates immediate potential for saving \$19.5 bn pa or over 2 per cent of GDP. That would allow income tax to be reduced to a top rate of 30 per cent – and additional tax changes.

Savings can mainly be achieved by reducing benefits to higher income groups but by “compensating” most of them through tax cuts. This is possible because those groups receive 30 per cent of social security (including selected education and health) benefits and thus receive back nearly half the taxes they pay. Most of such “churning” is a useless product of a society that has become bureaucratised by political parties buying votes…

The cuts of \$19.5 bn would represent a total percentage reduction of 8.2 per cent. The main potential for savings in expenditure comes from social security and welfare (\$7,278 mn), health (\$2,844 mn), education (\$1,689 mn), housing (\$1,038 mn) and industry assistance (\$457 mn). This would be a percentage cut in expenditure of 8.1 per cent (including a 20 per cent cut in industry assistance). In addition it is proposed that total tax expenditures will be cut by \$2,993 mn or 8.7 per cent.
