---
title: "Oil Doesn’t Make You Rich"
date: "2005-04-18"
categories: ["Economics"]
---

Some controversial ads on Australian television have been berating us for supposedly giving East Timor a rough deal on the proceeds from the oil fields of the Timor Gap.  I suspect part of the motivation for this campaign stems from the popular view that national wealth is a function of resource endowments.  It is easy to refute this proposition by pointing to resource-rich countries that are poor, like Russia, and resource-poor countries that are rich, like Singapore, Hong Kong and Japan.

Oil endowments are no exception, as [Tom Palmer](http://www.tomgpalmer.com/archives/020458.php "Tom Palmer") has been explaining to the Iraqis.  There are obvious reasons why oil has not made Iraq rich (yet).  However, it is also less obviously true of some developed countries that do not have Iraq’s problems as an excuse.  [This American ex pat](http://www.nytimes.com/2005/04/17/weekinreview/17bawer.html?incamp=article_popular_2&pagewanted=all&position= "This American ex pat") in Norway observes that local living standards do not quite match its reputation as the world’s richest country:

*After I moved here six years ago, I quickly noticed that Norwegians live more frugally than Americans do. They hang on to old appliances and furniture that we would throw out. And they drive around in wrecks. In 2003, when my partner and I took his teenage brother to New York - his first trip outside of Europe - he stared boggle-eyed at the cars in the Newark Airport parking lot, as mesmerized as Robin Williams in a New York grocery store in “Moscow on the Hudson.”*

There is also evidence to suggest that overdependence on a single resource encourages rent-seeking behaviour and corruption.  East Timor’s share of the Timor Gap oil revenue by itself will do little to ameliorate its problems and could even make them worse.
