---
title: "Peter Costello and the Attack of the Stone, Episode IV"
date: "2005-10-07"
categories: ["Economics"]
---

Former Treasury Secretary John Stone, doing what he does best - [taunting Treasurer Costello](http://www.theaustralian.news.com.au/common/story_page/0,5744,16837096%255E7583,00.html "taunting Treasurer Costello"):

In his latest essay to establish statesman’s credentials, federal Treasurer Peter Costello has crassly criticised (in an interview with The Australian Financial Review) the tax-cutting policies of President George W. Bush…

Costello’s remarks are all the more extraordinary for having been made a few days after a truly excellent [speech by the governor of our Reserve Bank, Ian Macfarlane](../2005/rba_governor_macfarlane_on_global_imbalances1.qmd "speech by the governor of our Reserve Bank, Ian Macfarlane"). His closely argued and analytically compelling address demonstrated to anyone willing to read it with a mind not poisoned by anti-Americanism that, so far from being a threat to world financial and economic stability, the US deficits (budgetary and current account) are the response we might hope for in a world the rest of which (Japan, China, other parts of East Asia, Middle East oil producers) is running a huge surplus of savings over investment.

Had Costello not read the governor’s speech before unburdening himself of his second-hand musings to the AFR? Or had he read it but simply not understood it?

With momentum building for genuine tax reform (including significant tax cuts) in next year’s budget, Costello runs the risk of being the only senior Liberal still convinced that the Government knows better how to spend our money than we do ourselves. With any luck, though, by then he won’t be making the decisions.

Costello must be truly thankful for Ken Henry.
