---
title: "PIMCO to the Fed: Regulate Me!"
date: "2005-12-12"
categories: ["Economics"]
---

PIMCO MD [Paul McCulley](http://australia.pimco.com/LeftNav/Late+Breaking+Commentary/FF/2005/FF+November+05.htm "Paul McCulley") makes the extraordinary claim that:

the conditions conducive to bubble formation are imminently predictable: 

• A shift from a bank-centric to a capital markets-centric system of savings intermediation,\
• In the context of price stability in goods and services, alongside\
• A central bank unwilling to use regulatory tools to temper credit creation.

In fact, it is the absence of these conditions that is more conducive to systemic mispricing attributable to an inhibited price discovery process.  The Asian crisis of 1997-98, for which the dominance of bank lending over capital market intermediation was a major contributing cause, more than adequately illustrates this.

At least McCulley is clear about the implications of his belief that asset price ‘bubbles’ are now endemic.  He calls on the Fed to:

*embrace a more activist regulatory approach to fine-tuning irrationally exuberant capital market-driven credit creation.*

It is hardly surprising that those who believe asset price ‘bubbles’ are ‘endemic’ should also believe in re-regulating financial markets.  If you think markets are so obviously incompetent to set prices and allocate capital efficiently, then it would seem to follow that the authorities can do better via discretionary intervention.  It is the fatal conceit of the ‘bubble’ brigade.  Fortunately, Ben Bernanke is much smarter than that.
