---
title: "Pricing Clinton, McCain and Rice"
date: "2005-12-15"
categories: ["Politics"]
---

US Senators make lousy Presidential candidates, but [John Fortier](http://www.aei.org/publications/filter.all,pubID.23580/pub_detail.asp "John Fortier") argues that Hillary Clinton and John McCain are the exceptions to the rule:

Senators who look in the mirror think they see the next president of the United States. History, however, has shown that the reflection is that of a losing candidate…

Only two sitting senators have ever won the presidency—John F. Kennedy and Warren Harding—and both had short and relatively undistinguished Senate careers. By contrast, consider the success of governors. Not only have four of our last five presidents been governors but incredibly none had even held a real job in Washington before entering the presidency.

Clinton and McCain are currently the highest priced [Intrade](http://www.intrade.com/apply.jsp?heardFromPromotionDetail=s0545138709r "Intrade") contracts for securing their party’s nomination.  Unfortunately, the market is giving a very low probability to the [Hillary-Condi contest favoured by Dick Morris](http://www.amazon.com/gp/product/0060839139/ref=ase_institutional-20/103-9088557-6962240?s=books&v=glance&n=283155&tagActionCode=institutional-20 "Hillary-Condi contest favoured by Dick Morris"):

*Rice is the only figure on the national scene who has the credentials, the credibility, and the charisma to lead the GOP in 2008…a race between these two commanding, but very different, women is a very real possibility - and would inevitably prove one of the most fascinating and important races in American history.*
