---
title: "Public versus Private Saving"
date: "2005-12-17"
categories: ["Economics"]
---

[Alan Kohler](http://www.smh.com.au/news/business/nerve-needed-to-fix-tax-idiocies/2005/12/16/1134703609152.html?page=2 "Alan Kohler"), referring to Greg Smith’s presentation to the Australian Tax Research Foundation’s [Tax Leader’s Forum](http://www.atrf.com.au/tax_leaders%20_forum.pdf "Tax Leader’s Forum"), highlights the extent to which the increased public saving represented by the federal budget surplus has come at the expense of private saving:

of the \$47 billion in underlying cash budget surpluses accumulated since 1996, \$39 billion, or 83 per cent, came from taxes collected from super funds.

In other words the Howard Government’s accumulated surpluses are largely just a transfer of private savings to public savings. The taxes collected from super funds haven’t even been spent! ...

Greg Smith says: “Australia is one of the very few countries to tax superannuation funds \[on earnings and contributions\]. This essentially transfers private to public savings, substantially neutralising the national economic benefits of running a budget surplus.”

That is, the budget surplus is not a result of excellent economic management or government administration, but is simply the forced transfer of wealth from private savings to public. Nothing has been created.

This is what makes the impounding of part of the budget surplus and the proceeds from the sale of Telstra in the Future Fund so inexcusable.  The financial assets that will acquired by the Fund should instead be residing in the private retirement accounts of individual working Australians, reducing their future dependence on government.
