---
title: "Putting Your Money Where Brad DeLong’s Mouth Is"
date: "2005-06-23"
categories: ["Economics"]
---

One of my frequent complaints about those who indulge in ‘bubble’ talk is that they rarely put their money where their mouth is.  Most people are probably correct in thinking that they have made prudent decisions in relation to their own finances, but they are equally ready to assume that everyone else is being imprudent (inconsistencies of this sort are a common result in behavioural economics/finance).  What amuses me most about those who worry about the current account deficit is that many would have personal balance sheets that are little different in substance from the current account deficit and, indeed, make a direct contribution to it, but few would perceive themselves as part of the ‘problem.’ 

[Mark Kleiman](http://www.markarkleiman.com/archives/macroeconomic_policy_/2005/05/speculative_selling_in_the_la_housing_market.php "Mark Kleiman") would appear to be a notable exception, selling his house for speculative reasons, or as he says, putting his money where Brad DeLong’s mouth is.  Unfortunately, his reasoning is little more than a tautology, combined with Bush Derangement Syndrome:

*If the current fiscal and trade deficits are unsustainable, especially with national economic policy run by the cast of a clown show, then they won’t sustain themselves forever.*

While I think this is incredibly silly, Kleiman gets full marks for consistency.  He is certain to suffer for his beliefs.
