---
title: "RBA Governor Macfarlane: Economic Myth Buster"
date: "2005-08-12"
categories: ["Economics"]
---

RBA Governor Macfarlane’s appearances before the House Economics Committee see some woeful displays of economic ignorance and ham-fisted attempts at political point-scoring on the part of Committee members.  Most of their questions consist of wildly partisan statements with which they then invite the Governor to agree, as if Macfarlane is not smart enough to see them coming.  In what is invariably a very classy performance, Macfarlane and his senior officers patiently listen to these questions and elevate the proceedings by turning them into some much needed education for Committee members and the public. 

Particularly interesting were Deputy Governor Stevens’ remarks on the results of the RBA’s current research into home equity withdrawal.  Stevens said that the early results point to something this blog has been arguing for some time, that very little of this is going into consumption, but instead into other financial assets.  As Stevens pointed out, if home equity withdrawal had all been going into consumption, we would have already seen a massive boom and bust in consumption and this is not remotely supported by the data.  When this research is finally published, it will almost certainly make a lot of commentary on this subject look very silly.

Macfarlane noted that the boom and subsequent correction in Sydney house prices closely matched what was happening with population growth in NSW and suggested that the recent decline in house prices was attributable to net emigration from the state, which in turn is driven by housing affordability.  In other words, there are some sound fundamental reasons for the observed behaviour of Sydney house prices, with feedback from house prices to population growth as falling housing affordability drives people out of the state.  Macfarlane did lapse into using the term ‘bubble,’ but I think this was just a concession to popular usage that is belied by what he had to say on the subject.

Macfarlane also agued, consistent with the consenting adults view, that none of us can know what the ‘right’ net foreign debt to GDP or private debt ratios should be, and also noted that fiscal policy has not had a major impact on monetary policy in the last seven years. 

Perhaps the funniest moment was when a Committee member tried to argue against the privatisation of Telstra, on the grounds that consumption would suffer as people bought newly issued Telstra stock.  Deputy Governor Stevens suggested that the impact on consumption would be zero ‘as a first approximation.’  The member in question probably still does not realise how stupid this made him look.

The Hansard transcript of proceedings should eventually appear on the RBA web site, for those who are interested.
