---
title: "RBA Governor Macfarlane on Global Imbalances"
date: "2005-06-29"
categories: ["Economics"]
---

An excellent speech given by [RBA Governor Macfarlane](http://www.rba.gov.au/Speeches/2005/sp_gov_120505.html "RBA Governor Macfarlane") in China, which argues that the sustainability of current account surpluses under fixed exchange rate regimes is much more questionable than the sustainability of current account deficits under floating exchange rate regimes:

there is a belief that current account deficits are unsustainable, whereas surpluses could go on forever. This was a reasonable assumption for most of the post-war period, particularly under the Bretton Woods system, but may no longer be so. In a world of floating exchange rates and mobile international capital, the old rules may no longer apply. The discipline applied by the international market place on developed countries with current account deficits now may be very weak.

Even under earlier monetary regimes, there are examples of countries that have maintained current account deficits for long periods. The United States in the nineteenth century is a good example, as is Australia in the twentieth. In the 1970s, Singapore ran a current account deficit which averaged 15 per cent for a decade. For developed countries with deep financial markets and little or no foreign currency exposure in their borrowing, current account deficits are not the problem they once were…

the scenario whereby world financial markets react to the US current account deficit by withdrawing funding has disappointed those who thought it would come into play. It may happen yet, but people have been predicting it for a long time and yet it seems no closer. A large part of the reason for this is that investors who want to get out of US dollars have to run up their holdings of another currency – they cannot get out of US dollars into nothing. They have to take the risks involved in holding some other currency, possibly at an historically high exchange rate, and they may well be reluctant to do so.\
\
Macfarlane reproduces a quote of his own from 1998, which shows him to have been remarkably prescient on the rise of East Asian mercantilism in relation to official reserve assets.
