---
title: "RBA Governance"
date: "2005-11-22"
categories: ["Economics"]
---

The federal government will need to make three appointments to the RBA Board between now and July next year, with the expiry of the current terms of Frank Lowy, Don McGauchie and Warwick McKibbin.  There is speculation that former federal Treasurer of the Liberal Party and Fairfax Chairman Ron Walker might be appointed to the Board.  Needless to say, this has the [opposition fretting](http://www.smh.com.au/news/Business/McGauchie-valued-by-RBA-board-Costello/2005/11/21/1132421578572.html "opposition fretting") for the independence of the Bank:\

\
Opposition treasury spokesman Wayne Swan said Mr Costello should rule out making Mr Walker one of the board’s members, who earn around \$50,000 a year for their services.

He said appointing Mr Walker would undermine the independence of the board. “We simply cannot let one of the most important and sensitive organisations in Australia be compromised in this way by becoming a plaything for friends of the Howard government,” Mr Swan said in a statement.

“An independent Reserve Bank board is fundamental to sound economic management and stability, and should not be treated as a destination for Liberal Party mates or a payback for services rendered to the coalition.”

The precedent for political appointments to the Board was set long ago and concerns for the independence of the Bank in opposition are rarely sustained by governing parties.  When Qantas was still in public ownership, it was said that the Qantas Board was like the House of Lords, a dumping ground for political patronage, and the RBA Board has not done much better under successive governments. 

The AAP story notes the McGauchie was appointed to ‘represent rural interests,’ reflecting his past affiliation with the National Farmers Federation, but also that his current role as Telstra Chairman routinely puts him in conflict with both the government and the ACCC.  The long-standing politicisation of the RBA Board is in many ways a secondary issue to the conflicts of interest inherent in the many hats some appointees bring to the Board table. 

This point was effectively conceded in affidavits lodged with the Administrative Appeals Tribunal in the RBA’s attempts to prevent News Ltd gaining access to Board minutes under Freedom of Information legislation, a process that was brought to an end when a conclusive certificate was issued.  This episode demonstrated that the current Board arrangements are simply incompatible with increased accountability and transparency on the part of the Bank.  In the absence of reform to the governance arrangements for Bank, the main qualification for most Board appointments will remain a lack of expertise in monetary policy.  The contrast with the candidates being considered to replace the two vacancies on the Fed Board of Governors (see previous post) is rather telling.
