---
title: "RBA Transparency: Right Up There With Motherhood"
date: "2005-06-09"
categories: ["Economics"]
---

A survey has found a high level of public support for the proposition that the RBA should be required to release the minutes of its deliberations:

The Hawker Britton survey of 500 people found 80 per cent thought it was time the Reserve was forced into releasing its minutes, with just 16 per cent supporting the current closed book.

The Reserve at present does not reveal its monthly meeting minutes.  Only when it changes interest rates does it release a statement, outlining its reasons for moving rates.

But there has been pressure from business groups, economists and others for the Reserve Bank to follow the lead of other central banks by releasing its minutes.

The minutes would give some insight into what the bank’s board members are thinking about the economy, and the prospect of further interest rate changes.

Hawker Britton managing director Bruce Hawker said it was time for the Reserve Bank to be more open.

“The Bank of England and the United States Federal Reserve both release minutes of their board meetings, but not the Reserve Bank of Australia,” he said in a statement.

Of course, transparency is a bit like motherhood and so the high level of support is not really surprising.  Moreover, if the respondents were told about the practices of other central banks, this frames the question in a way likely to elicit a positive response.  Still, it is encouraging to see this issue being actively canvassed.
