---
title: "RBA Transparency and Accountability: You Can’t Keep a Good Issue Down"
date: "2005-05-05"
categories: ["Economics"]
---

Too many journalists are preoccupied with personalities and outcomes at the expense of processes when it comes to reporting on macroeconomic policy.  [John Garnaut](http://www.smh.com.au/news/Business/To-RBA-governor-please-explain/2005/05/03/1115092499564.html "John Garnaut") deserves some kudos for keeping the issue of RBA transparency and accountability alive, using the monthly board meeting as a hook:

The lack of Reserve Bank transparency has been cited as a factor in recent market volatility, with interest rate expectations swinging from rate cuts in January to rate rises six weeks ago and back to rate cuts last week.

“If they had a post-meeting statement … the market wouldn’t have run and priced rate cuts at the end of last year and January, the Reserve Bank wouldn’t have had to issue such a one-sided, unbalanced statement in February, and it wouldn’t have seemed inconsistent for not moving in April,” said Deutsche Bank’s chief economist, Tony Meer.

The central bank’s board issues a statement when it adjusts interest rates but stays silent when it leaves rates on hold.

Graeme Thompson, who sat on the board as one of two deputy governors until 1998, said there was no obvious argument for not releasing a monthly statement. “I don’t quite see the argument against issuing some sort of statement every month for why the board came to a decision.”

Professor Adrian Pagan, a board member until 2001, also supports improved communications, including a statement each month.

It is also good to see some market economists chiming in on this for once.  Many market economists come from RBA and Treasury backgrounds and consequently tend to be rather uncritical of instituional framework for macro policy in Australia.
