---
title: "RBA Governance"
date: "2005-11-29"
categories: ["Economics"]
---

Robert Gerard’s main qualification for serving on the RBA Board were his contributions to the Liberal Party in South Australia.  It now also seems that being involved in a [dispute with the Australian Taxation Office](http://www.theaustralian.news.com.au/common/story_page/0,5744,17401473%255E1702,00.html "dispute with the Australian Taxation Office"), which falls within the Treasury portfolio, is no disqualification to being appointed to the Board:

Adelaide businessman Robert Gerard was appointed to the RBA board in March 2003.

The appointment came as Mr Gerard, who owns the family business Gerard Industries, was fighting the Australian Tax Office (ATO) over a Caribbean tax haven deal described as tax evasion.

A \$150-million settlement in 2003 ended a 14-year investigation, that came after Mr Gerard’s appointment was taken to Cabinet by Treasurer Peter Costello.

Mr Gerard says he told Mr Costello about his ATO dispute before his appointment, and the Treasurer later contacted him and said he had no problem with him being on the board.\
\
This has the federal opposition calling for an inquiry, but it is hardly the first time the business interests of an RBA Board member have been the cause of controversy.  Anyone remember Solomon Lew and Yannon?  Solomon Lew was one of the few outside appointments to the RBA Board not to serve a second term after the Yannon affair blew-up half way through his five year term.

As suggested in previous posts, the problem with the RBA Board is not so much the inevitably political nature of the appointments, but the many hats and potential conflicts of interest that some appointees bring to the Board table.  The RBA’s efforts before the Administrative Appeals Tribunal to suppress the release of the minutes of Board meetings effectively acknowledges these conflicts.  The setting of monetary policy should be kept separate from the other governance functions of the Bank and placed in the hands of a full-time committee of monetary policy experts, with substantial representation from outside the Bank.
