---
title: "RBNZ Governor Bollard Has Lost the Plot"
date: "2005-10-27"
categories: ["Economics"]
---

Former RBNZ Governor (now National Party leader) Don Brash got a lot of bad press for his conduct of monetary policy, most of it undeserved.  But his successor as Governor, Alan Bollard, deserves criticism following today’s decision to raise the official cash rate to a record 7%.  The problem is not the rate increase as such.  A case can be made for further tightening, even if this partly reflects Bollard’s mistake in lowering the cash rate in 2003.  Rather, the problem is Bollard’s rationalisation for the latest tightening, which is contradictory to say the least.  [According to Bollard](http://www.rbnz.govt.nz/news/2005/2141171.html "According to Bollard"):

*The most serious risk to medium term inflation is the continuing strength of household spending, supported by a relentless housing market and rapid growth in mortgage lending.  Significant dis-saving by the household sector is showing through in a worsening current account deficit, now 8 per cent of GDP. Borrowers and lenders alike need to recognise that the current rate of debt accumulation is unsustainable. The correction of these imbalances and associated inflation pressures will require a slowdown in housing, credit growth and domestic spending. We also expect a significantly lower exchange rate. The longer these adjustments in behaviour and asset prices are deferred, the more disruptive they are likely to be.*

This is not only a mischaracterisation of the risks to inflation, it is also contradictory.  Raising the official cash rate will only attract further capital inflow, already very strong, putting further upward pressure on the exchange rate and making the current account deficit even worse.  This is exactly the policy mistake the RBA made in the late 1980s, when it sought to target the current account deficit with tighter monetary policy, resulting in a recession in the early 1990s.  Both Governor Bollard and the Finance Minister have been trying to talk the NZD lower, yet monetary policy has been driving it higher.  This can only cause credibility problems for the Bank.  If anything, Bollard should be talking up the exchange rate. 

The credibility problem is made worse by the fact that the RBNZ recently sought an increase in its capitalisation to facilitate intervention in foreign exchange markets, yet it seems unwilling to back its exchange rate overvaluation rhetoric with actual intervention.  This is just as well, because we would then have a situation in which interest rate and exchange rate policy were at cross purposes, but it highlights the contradiction between what the RBNZ and the government say about the exchange rate and what the RBNZ is actually doing with monetary policy.

Before the current government watered down the RBNZ’s inflation targeting regime, the current rate of inflation might have already seen the RBNZ Board meet to decide whether to recommend dismissal of the Governor to the Minister, although the contribution to inflation from higher oil prices would fall under the caveats to the Policy Targets Agreement.  This is now much harder to do, because the inflation target has been re-defined in such a way as to accommodate a much wider range of outcomes.  By the Bank’s own admission, there is little scope for inflation to return to the target range before 2007.
