---
title: "Review of Bubble Man: Alan Greenspan & the Missing 7 Trillion Dollars"
date: "2005-08-10"
categories: ["Economics"]
---

My review of Peter Hartcher’s (2005) *Bubble Man:  Alan Greenspan & the Missing 7 Trillion Dollars*.  Black Inc: Melbourne.

Hartcher’s book follows his stint as a Washington correspondent, was written while a fellow at the Lowy Institute and is published by Morry Schwartz’s Black Inc.  Much of the book is a recycling of earlier books on the Greenspan Fed by Steve Beckner, Justin Martin and Bob Woodward, Robert Shiller’s Irrational Exuberance and other sources.  There are no footnotes or bibliography and the few references in the text give only a hint of the extensive borrowing from other sources.

As its title suggests, the book seeks to lay blame for the turn of the century boom and bust in US equities and subsequent recession at the feet of Federal Reserve Chairman Alan Greenspan.  Hartcher is not alone in making this argument and it is one that crosses party lines.  Economists at the otherwise respectable American Enterprise Institute have made similar claims.  Few have made it quite as forcefully as Hartcher, who mostly substitutes hyperbole for analysis, trying to carry the argument by sheer force of exaggeration: ‘Alan Greenspan was not prepared to contain or manage in any way one of the most deluded and dangerous market manias in four centuries of financial capitalism’ (p. 175).  Hartcher maintains that from 1996, Greenspan understood the risks associated with the stock market boom, but out of political timidity, did ‘absolutely nothing about it’ (p. xv). 

The main evidence offered for Hartcher’s claim that monetary policy from 1996 onwards was excessively accommodative of rising stock prices is that ‘Greenspan’s Fed made a net change to official interest rates of -1.25 percentage points during the bubble years’ (p. 132).  Both inflation and nominal interest rates have been in secular decline throughout the industrialised world since the early 1980s, so any sum of changes in nominal interest rates is likely to pick-up this downtrend.  The Fed was hardly alone in this.  The figure for the Reserve Bank of Australia over the same period referenced by Hartcher was -2.75 percentage points.  Hartcher’s reference to a ‘21%’ fall in the Fed funds rate (p. 147) tells us a lot about the global decline in inflation over this period, but very little about actual the stance of US monetary policy.  What really matters is the average level of the real rate over time relative to a (not necessarily constant) equilibrium real rate.

Hartcher acknowledges that the easings at the end of 1998 in response to the aftermath of the Asian crisis and the collapse of LTCM were necessary and even concedes that these episodes were ‘handled judiciously and well’ by the Fed (p. 147), so he can really only claim three easings, summing to -0.75 percentage points, for his ‘bubble’ accommodation thesis.  The Fed tightened aggressively from 1999 and Hartcher acknowledges the role of these tightenings in the undoing of the stock market boom and subsequent recession.  He also claims that the Fed tightening of the mid-1990s was appropriate.  So Hartcher’s claim boils down to the very implausible one that somewhere between the easing cycle that began in July 1995 and the concerted tightening that began in June 1999, US monetary policy was accommodative of what he calls ‘the biggest speculative mania the world has seen’ (p. 1).  This period was in fact punctuated by one Fed tightening, in March 1997, but Hartcher maintains this was not enough.  Hartcher never ventures to suggest by how much the Fed should have tightened over this period.  Instead, he quotes Fed research on the elasticity of stock prices to Fed funds rate shocks contained in a 2003 speech by then Federal Reserve Board Governor Ben Bernanke.  In this context, Hartcher says that the idea that ‘monetary policy has a strong influence over the market…is supported by *all* the evidence from within the Fed itself’ (p. 151 emphasis added).  Hartcher neglects to mention that the rest of Bernanke’s speech is in fact a compelling review of the theory and evidence against the proposition that monetary policy should respond to asset prices, citing no less than 20 academic papers and other sources on the subject.  In particular, Bernanke summarises his argument by noting that ‘monetary policy can lower stock values only to the extent that it weakens the broader economy, and in particular that it makes households considerably worse off.  Indeed, according to our analysis, policy would have to weaken the general economy quite significantly to obtain a large decline in stock prices.’  Hartcher is not being honest with his readers in making such highly selective use of his sources.

Hartcher maintains that the Fed Chairman acknowledged that there was, in Greenspan’s own words, ‘a stock market bubble problem’ in 1996, but failed to act against it, because of a combination of political timidity and personal fallibility.  However, it does not follow from Greenspan’s acknowledgment of a ‘stock market bubble problem’ that monetary policy should respond to it.  Greenspan’s famous ‘irrational exuberance’ speech to the American Enterprise Institute at the end of 1996 was deliberately couched in rhetorical terms because, as Hartcher concedes, most central bankers and economists think that targeting asset prices is an extremely risky proposition.  This is a view shared by RBA Governor Ian Macfarlane, who has argued against targeting asset prices in terms almost identical to Alan Greenspan.

The weaker the connection between asset prices and economic fundamentals, the stronger the argument against using asset prices as either targets or conditioning variables for monetary policy.  There is only one major recent example of a central bank targeting asset prices in a systematic way: the Reserve Bank of New Zealand’s use of the exchange rate as part of a composite operating target between 1996 and 1999.  This practice was abandoned, because the well known volatility of exchange rates and their very loose relationship with economic fundamentals made it a very poor basis for conducting monetary policy.  This is even more true of stock prices.  A direct and systematic response of monetary policy to asset prices would inject more volatility into financial markets and the economy and would be far more destabilising than the routine asset price inflation and deflation which for the most part has benign implications for the real economy and is necessary for the efficient allocation of capital. 

Hartcher is oblivious to a glaring contradiction at the heart of his argument: if central bankers are as personally and politically fallible as Hartcher suggests Greenspan was, then this a very strong argument against a discretionary monetary policy that seeks to second-guess the market on asset prices.  Hartcher is effectively arguing that we need a central banker who is prepared to back their own judgement on asset prices against the market, but we have no basis for believing that any other individual would be less error prone or fallible than Greenspan given the institutional environment in which the Fed Chair operates.  Hartcher acknowledges that Greenspan conducted monetary policy in a highly discretionary way, yet concludes from his supposed failings that central bankers should exercise even more discretion to target asset prices.  Like most journalists, Hartcher is preoccupied with personalities at the expense of processes, showing no interest in institutional reforms that might make the process of setting US monetary policy less subject to discretionary policy error, such as the adoption of a formal inflation targeting regime.

The idea that central banks should manage asset prices through monetary policy is antithetical to the very reason we have financial markets.  The debate over how monetary policy should respond to ‘bubbles’ is the asset market equivalent of the socialist calculation debate of the 1930s.  Unfortunately, the idea that monetary policy should respond to asset prices is gaining ground, in large part because of the growing tendency to view markets as being ‘bubble’ prone.  There is not a single asset class that has not been pronounced as being in a ‘bubble’ in recent years and the term is now so overused as to be bereft of analytical content.  If ‘bubbles’ are as common as the likes of Hartcher would have us believe, then this is strong grounds for believing that they are normal part of the functioning of markets.  If asset prices had simple and deterministic relationships with known fundamentals, there would in fact be no need for financial markets to set prices.  Asset price inflation and deflation is a necessary part of the market discovery process.  The notion that the authorities can know better than the market the appropriate level or growth rate for asset prices is a seductive, but dangerous one, not least in the hands of central bankers. 

\
**Hartcher’s Hyperbole: A Colourful Footnote**

There is a role for colourful prose in journalism, but Hartcher routinely lapses into hyperbole.  I can’t help but share the following, which had me laughing out loud in ways I’m sure the author never intended:

‘lewdley seductive slut of greed to run amok in the markets’ (p. xiii)

‘vortex of one of the greatest speculative frenzies the world has seen…the entire ranting, thundering, churning, wrenching \$17 trillion dollar frenzy that convulsed a superpower’ (p. 14)

‘Americans spent freely and threw the concept of savings \[sic\] into the same place they put prudence, moderation and common sense’ (p. 26)

‘the current account deficit…swiftly deteriorated to a new low of impoverishment’ (p. 27)

‘the Great American Bubble’ (p. 31)

‘Wall Street firms…synonymous with greed and exploitation and often reviled’ (p. 41)

‘Great American madness’ (p. 50 and p. 182)

‘what he \[Greenspan\] does is vital yet so stunningly simple: he operates the money supply, the giant on-off switch of American economic growth’ (p. 78)

‘virulent danger of an economic bacchanalia’ (p. 84)

Greenspan ‘the charismatic leader of a manic cult’ (p. 140)

‘the “rational markets” hypothesis is the economics equivalent of an apologia for \[German cannibal\] Armen Meiwes’ (p. 189)
