---
title: "Ross Gittins Off Treasurer’s Guest List"
date: "2005-03-07"
categories: ["Economics"]
---

[Ross Gittins](http://www.smh.com.au/news/Ross-Gittins/Economists-just-dont-get-whats-happening/2005/03/06/1110044256334.html "Ross Gittins") gives economists a serve for failing to go beyond the headline number in last week’s national accounts release:

Similarly, the literalists happily believe that during the period in which the economy slipped into near recession:

consumer spending grew by almost 4 per cent, business investment by 10 per cent and public sector spending by about 5 per cent.

Indeed, the only area of spending that was weak was housing construction, which contracted by 2 per cent, leaving domestic final demand growing by a rapid 4 per cent.

Sound like a sick economy to you? And while the economy was in the doldrums, credit (private sector debt) grew by 12.5 per cent and the stockmarket rose 23 per cent.

Why are so many otherwise sensible people so willing to take implausible figures literally? The media do it because they don’t want to spoil a good story. The financial markets don’t want to spoil a good betting opportunity.  What’s the business economists’ excuse?

The demand for economic commentary comes largely from the media and the ‘literalism’ Ross is railing against is largely media-driven.  Market economists are often made to look superficial, but this is more a function of how the media presents the story rather than a lack of sophistication on the part of those supplying the commentary.  As for the media, they see the economy as subordinate to politics and so interpret economic numbers largely in terms of political rivalry.  Their interest in substantive economic issues is typically fairly limited.

The fact that many journalists see the economy as being subordinate to politics goes directly to Ross’ other complaint about being discriminated against by the Treasurer:

*When I wrote a few weeks ago that Peter Costello’s ire was easily incurred, I little imagined I’d be the next recipient. All the nation’s senior economic journalists were invited to attend a recent dinner that Mr Costello addressed at a closed Treasury conference - except me.*

Ross accuses the Treasurer of more generalised bullying and intimidation, something for which Paul Keating was also famous when he was Treasurer.

The problem is not that Ross and others are critical of the government, but that they are often critical for the wrong reasons.  They also sometimes give the impression of being partisan because of the political overlay they give to their stories, even when their intentions are otherwise.  Many journalists also see themselves as players in the political process.  It is hard to feel much sympathy when they get treated accordingly.
