---
title: "Shameless Protectionism"
date: "2005-11-24"
categories: ["Economics"]
---

Protectionism is rarely as cynical and opportunistic as [this](http://www.theaustralian.news.com.au/common/story_page/0,5744,17348462%255E1702,00.html "this"):\

\
Prominent Liberal backbencher Bruce Baird said the Government should take 25-year-old Nguyen’s execution into consideration during negotiations with Singapore Airlines over a share of the lucrative Australia-US air route.

The Government is expected to make a decision shortly on granting the airline, owned by the Singapore government, access to the route from which Qantas makes much of its profit.

Mr Baird, who heads the parliamentary amnesty group, told ABC radio that while clemency for Nguyen should not be a condition of a Singapore Airlines deal, it should be a consideration.

“I’m not saying it should be made a condition I just think it is one of the issues that should be taken into consideration because we have made a number of requests to them to consider our position, we have no death penalty in this country so they are out of step in terms of other developed countries and imposing the death penalty,” he said.

The story neglects to mention Baird is also a member of the parliamentary Friends of Tourism group and that his electorate includes Sydney Airport.
