---
title: "Should the RMB Reval Keep Flordia Mortgage Holders Awake at Night?"
date: "2005-07-26"
categories: ["Economics"]
---

There has been much ink spilled on the subject of the RMB revaluation, but few have put it in perspective quite as well as UBS economist [Jon Anderson](http://online.wsj.com/article/0,,SB112224065129594292,00.html?mod=opinion%5Fmain%5Feurope%5Fasia "Jon Anderson"):

the current 2% revaluation (or, for that matter, even a move two or three times larger) is nothing to get excited about. By far the most common question in my inbox over the past three days has been the impact of the yuan adjustment on China’s trade and economic growth. The short answer is: no impact whatsoever. G-3 currencies fluctuate by 2% or more nearly every month without any noticeable influence on their economies, but somehow people who would never dream of asking about the effect of a yen move to 110 from 113 still can’t resist running for the phones when the yuan strengthens by the same amount. UBS hasn’t changed its forecasts for Chinese growth, inflation or employment, and I suspect most other economists haven’t either.

Nor do we foresee any sustained “yuan effect” on other Asian currencies, regional growth, the dollar or global bond markets. Despite the current press speculation, Florida mortgage holders can sleep soundly—at least as far China is concerned.

The notion that a few hundred billion in annual official reserve asset purchases by China could influence markets with the depth and liquidity of the US dollar and Treasuries has always been a stretch, but that has not stopped it from becoming an article of faith among many economists.
