---
title: "Skilled Migrants or Guest Workers?"
date: "2005-08-16"
categories: ["Economics"]
---

The Federal government has launched a [campaign](http://www.theaustralian.news.com.au/common/story_page/0,5744,16275220%255E601,00.html "campaign") to fill 20,000 new places in the skilled migration program.  This comes after Federal Treasurer Peter Costello ruled out the use of ‘guest workers’ as being ‘inconsistent with Australian values,’ despite being an obvious way of meeting both skilled and unskilled labour shortages and an effective form of development assistance for source countries.  Of course, we already have a de facto guest worker scheme in the form of European backpackers on working holiday visas, so a new guest worker visa category is not such a great leap.

What surprises me is that very few people see the guest worker concept as also being an obvious solution to the high cost of child care and the work-family balance issue.  Creating a special visa category for live-in [amahs](http://en.wikipedia.org/wiki/Amah "amahs") from South East Asia could dramatically lower the cost of child care and domestic help and promote higher labour force participation rates.
