---
title: "Some Hope for the Tories"
date: "2005-08-30"
categories: ["Politics"]
---

At least one of the Tory leadership contenders has a promising intellectual pedigree:

The [Observer](http://observer.guardian.co.uk/print/0,3858,5272444-102279,00.html "Observer") can reveal the influence on Tory frontrunner David Davis of the political philosophy of Randy E Barnett, a 53-year-old right-wing academic from Boston University, whose book [The Structure of Liberty](http://www.amazon.com/exec/obidos/tg/detail/-/0198297297/ref=ase_institutional-20/102-2153320-4096121?v=glance&s=books "The Structure of Liberty") has been hailed as a classic of conservative thought.

Barnett argues that political and legal decision-making should be devolved as locally as possible, with central government cut to the bone. He mounts a passionate argument for the right of self-defence for the property owner and the right of retribution for victims of crime.

More controversially, Barnett last year represented the Oakland Cannabis Buyers’ Co-operative in a Supreme Court action to defend their right to provide free cannabis to sufferers of conditions such as MS and glaucoma. The action failed, but Barnett was hailed by cannabis campaigners as an advocate of the rights of the citizen in the face of state power…

The men were introduced by John Blundell, head of a right-wing think-tank, the Institute of Economic Affairs…

Blundell said Davis’s intellectual hinterland is underestimated. He said that the young Davis was a keen reader of right-wing philosopher Karl Popper and free-market economist Milton Friedman, who provided the theoretical backbone to Thatcherism. ‘He is one of the brightest people I’ve ever met. It’s easy to typify him as a bruiser because of the broken nose and his SAS background, but he is a voracious reader and serious thinker.’

Davis is also the front-runner on the Intrade contract for next Tory leader.
