---
title: "Spec Free Property Boom"
date: "2005-07-21"
categories: ["Economics"]
---

Here is [one property boom](http://asia.news.yahoo.com/050720/3/249fk.html "one property boom") that is more or less guaranteed to be leverage and speculation free!

LONDON, July 20 (Reuters) - The rapid growth in investments compliant with Islamic Sharia law is gaining fresh impetus from high oil prices for energy-rich Muslim countries, and a large slab of this capital is going into real estate, researchers say.

Islamic banking and finance, fast becoming one of the biggest global niche financial services markets, is estimated to be worth up \$500 billion worldwide, and is expected to grow at between 12 percent to 15 percent over the next 10 years, Ali Parsa of London’s South Bank University said on Wednesday…

The attributes of real estate investment lend themselves to Sharia law which forbids the payment of interest, and speculation in the form of short selling—as practised by hedge funds—or the use of derivatives, Parsa said.

(via [Mahalanobis](http://mahalanobis.twoday.net/ "Mahalanobis"))
