---
title: "Steve Hanke’s Currency Board Fetish"
date: "2005-02-18"
categories: ["Economics/Financial Markets"]
---

[Steve Hanke](http://www.cato.org/pub_display.php?pub_id=3679 "Steve Hanke") is nothing if not consistent.  His fetish for currency boards seems to have spilled over into a love of almost any fixed exchange rate regime.  He even has the audacity to call the proponents of greater exchange rate flexibility in East Asia mercantilists. 

Hanke’s defence of HK’s currency board relies on financial instability that occurred more than 20 years ago.  The costs HK’s currency board has imposed on its economy in recent years are completely ignored (Singapore has done relatively better because of its more flexible approach to exchange rate management).

In relation to Japan, Hanke maintains:

*Japan has been under mercantilist pressure, primarily from the U.S., to ratchet up the yen’s value against the dollar. Tokyo has complied. Consequently, the economy has suffered from strong-yen-induced recessions and hasn’t yet recovered from the enormous deflation of the 1990s. And the mercantilists in the U.S. remain agitated because Japan continues to register large trade surpluses.*

Hanke has things exactly backwards.  Japan has not seen a yen-induced recession since 1985-6.  It has been Japan’s mercantilist attempts at *resisting* the secular appreciation of the yen, by laundering its massive current account surpluses through USD asset markets, that has landed its economy with a massive overhang of excess capacity.  China risks suffering the same fate, especially if its demographics ultimately turn as toxic as those of Japan.

Given the terrible havoc fixed exchange rate regimes have wrought in emerging market economies in recent years, and within the euro zone, it is incredible that anyone still defends them.  It is even more incredible that these hold-outs for Bretton Woods-era monetary regimes can still find a home within classical liberal think tanks.
