---
title: "Tagged by Soon"
date: "2005-06-19"
categories: ["Misc"]
---

It was only a matter of time before I would be [tagged](http://badanalysis.com/catallaxy/?p=957 " tagged") in relation to my reading habits.  I have listed the five books that have been the most influential on my own thinking and that are likely to be of most interest to readers of this blog.

**Total number of books I’ve owned**

Andrew Norton once characterised my book collection as ‘small, but tasteful’ which is how I would like to keep it.  Six hundred volumes at a rough guess. 

**The last book I bought**

Neal Stephenson’s [Quicksilver](http://www.amazon.com/exec/obidos/ASIN/0060593083/institutional-20/102-2156040-0420144?creative=327641&camp=14573&link_code=as1 "Quicksilver"), an indication of my interest in historical and speculative fiction.

**The last book I read**

See above.

**Five books that mean a lot to me**

1.  While Jason suggested that Hayek was a necessary inclusion, no single work really does him justice and some actually do him a disservice.  His essays ‘[The Use of Knowledge in Society](http://www.econlib.org/library/Essays/hykKnw1.html "The Use of Knowledge in Society")’ and ‘[The Intellectuals and Socialism](http://www.lfb.com/cart/affiliate.php?code=10488&stocknumber=FA7895 "The Intellectuals and Socialism")’ were foundational for the Mont Pelerin Society (the committee that really did save the world), so I will suggest those.

2.  Nozick’s [Anarchy, State and Utopia](http://www.lfb.com/cart/affiliate.php?code=10488&stocknumber=PL0196 "Anarchy, State and Utopia").  Nozick’s critique of end-state principles of justice is one of the most powerful statements of the classical liberal position on distributive justice.  One of the few books that will change the way you think about the world. 

3.  Buchanan and Tullock’s [The Calculus of Consent](http://www.lfb.com/cart/affiliate.php?code=10488&stocknumber=EC0013 "The Calculus of Consent").  One of the key statements in the liberation of social science by rational choice theory.  Converted me from political science (my undergraduate discipline) to economics.

4.  Rothbard’s [Man, Economy and State](http://www.amazon.com/exec/obidos/ASIN/0945466323/institutional-20/102-2156040-0420144?%5Fencoding=UTF8&camp=1789&link%5Fcode=xm2 "Man, Economy and State").  [Human Action](http://www.lfb.com/cart/affiliate.php?code=10488&stocknumber=LV7510%20 "Human Action") without the historical-philosophical baggage.  The populist version, [Power and Market](http://www.lfb.com/cart/affiliate.php?code=10488&stocknumber=MR0566 "Power and Market"), is probably more accessible for the average reader.  I will sneak in David Friedman’s [The Machinery of Freedom](http://www.amazon.com/exec/obidos/ASIN/0812690699/institutional-20/102-2156040-0420144?%5Fencoding=UTF8&camp=1789&link%5Fcode=xm2 "The Machinery of Freedom") for those looking for a consequentialist and more readable alternative that reaches the same anarchocapitalist conclusions.

5.  Vera Smith’s [The Rationale of Central Banking](http://www.amazon.com/exec/obidos/ASIN/0865970874/institutional-20/102-2156040-0420144?%5Fencoding=UTF8&camp=1789&link%5Fcode=xm2 "The Rationale of Central Banking").  Originally a PhD thesis supervised by Hayek at LSE in the 1930s and still the most powerful critique of central banking ever written. 

I will also nominate my top five books on Japan.  Japan is the single best case study of the consequences of abandoning market liberalism and the rule of law in favour of bureaucratic discretion.  No need to argue the theory, just look at the practice!

1.  Karel van Wolferen’s [The Enigma of Japanese Power](http://www.amazon.com/exec/obidos/ASIN/0679728023/institutional-20/102-2156040-0420144?%5Fencoding=UTF8&camp=1789&link%5Fcode=xm2 "The Enigma of Japanese Power").  A stunning critique of the dysfunctional nature of the modern Japanese state, all the more remarkable for having been written at the height of the ‘bubble economy’ in the late 1980s. 

2.  Alex Kerr’s [Dogs & Demons: The Fall of Modern Japan](http://www.amazon.com/exec/obidos/ASIN/0809039435/institutional-20/102-2156040-0420144?%5Fencoding=UTF8&camp=1789&link%5Fcode=xm2 "Dogs & Demons: The Fall of Modern Japan").  Very insightful on the role of statism in the destruction of Japanese culture, its natural and built environment.  And you thought it was just their economy that was stuffed!

3.  Peter Hartcher’s [The Ministry](http://www.amazon.com/exec/obidos/ASIN/0875847854/institutional-20/102-2156040-0420144?%5Fencoding=UTF8&camp=1789&link%5Fcode=xm2 "The Ministry").  A case study of the disastrous consequences of bureaucratic discretion on the part of the all-powerful Japanese Ministry of Finance that owes an obvious debt to van Wolferen.

4.  Akio Mikuni and R Taggart Murphy’s [Japan’s Policy Trap: Dollars, Deflation and the Crisis of Japanese Finance](http://www.amazon.com/exec/obidos/ASIN/081570223X/institutional-20/102-2156040-0420144?%5Fencoding=UTF8&camp=1789&link%5Fcode=xm2 "Japan’s Policy Trap: Dollars, Deflation and the Crisis of Japanese Finance").  A critique of the mercantilist foundations of the modern Japanese state.  Read this book and pray your country never runs a current account surplus!

5.  Ramseyer and Rosenbluth [Japan’s Political Market Place](http://www.amazon.com/exec/obidos/ASIN/0674472810/institutional-20/102-2156040-0420144?%5Fencoding=UTF8&camp=1789&link%5Fcode=xm2 "Japan’s Political Market Place").  This book sparked fierce intellectual resistance to the encroachment of rational choice theory into the cloistered and now thoroughly discredited world of Japan Studies.
