---
title: "Ted Evans on RBA Governance"
date: "2005-08-24"
categories: ["Economics"]
---

[ABE](http://www.abe.org.au/pindex.html "ABE") has not yet posted the text (if any exists) of former Treasury Secretary Ted Evans’ remarks on RBA governance last week.  Doing a quick search for it reminded me of working in financial markets in the 1990s, when speeches by the Treasury Secretary and Treasurer would go up on the Treasury web site days after the event and important documents like the Mid-Year Economic and Fiscal Update would have release dates and times that were not even announced until the last minute, to suit the convenience of the Treasurer.  Treasury was not alone in this.  The RBA did not have a meaningful web site until late 1997!  This made Australia’s homilies on the subject of transparency directed at regional governments during the Asian crisis more than a bit rich.

Ted’s credentials on governance and transparency issues are thus not great, but he did come out with one good suggestion: reducing the frequency of the currently monthly meetings of the RBA Board.  The RBNZ makes official cash rate decisions on a six week cycle and this seems to make an important difference.  The RBNZ almost invariably changes interest rates in consecutive policy moves, which greatly reduces uncertainty and makes NZ monetary policy a much easier call than in Australia. 

Ted also suggested that the RBA should make an official statement after every meeting, regardless of whether there is a change in interest rates, something to which the RBA remains opposed, although the RBNZ manages this just fine.  The RBA and some commentators have tried to argue that the RBA presents more detailed statements when it does change interest rates than other central banks.  This is partly a function of the paucity of RBA communication at other times.  The everything-but-the-kitchen-sink statements that accompany RBA policy actions are in fact symptomatic of a poorly focussed statutory mandate.  The RBA seems determined to summarise every influence on policy when announcing changes in interest rates, which can distract attention from the inflation target, which is the bottom line for policy.  The rather terse statements issued by the Bank of England’s Monetary Policy Committee are preferable in this regard.  This does not preclude making more detailed statements on economic conditions at other times.  The quality of central bank communication is more important than its quantity.  The RBA’s Statements on Monetary Policy are notable mainly for their avoidance of any discussion of the policy outlook.  By contrast, the RBNZ fully endogenises its macro forecasts to a projected path for interest rates.

An important change that has gone largely unremarked in recent years has been the RBA’s increased commitment to making policy announcements at the first post-Board meeting dealing intentions window, which is now recognised by a brief ‘no policy change’ announcement after each Board meeting.  It was only a few years ago that the RBA routinely made unscheduled policy announcements.  The justifications for these unscheduled announcements were weak and imposed entirely needless uncertainty and costs on market participants.
