---
title: "The New Institutional Economics"
date: "2005-02-08"
categories: ["Misc"]
---

The new site is up and running.  Please email if you experience any difficulties using the address shown on the Contact page, or in comments.

As mentioned previously, comments are only open to registered members (click on ‘Register’ at the top right), but once registered, you need never login in again and you can use your registration to obtain email notification of other comments (email notification of posts in general will unfortunately have to await the next iteration).  New members will need to be approved.  I will not generally approve unidentifiable persons, especially those with free email accounts.  You are welcome to use a screen name to conceal your identity when commenting and can suppress your email address.

Posts from the old site have been turned into pdf files and posted below and in the archives.  This was the quickest way to bring across the old content.  There is still some content to be brought across.

Those who want to read the site via an aggregator can now do so with the various feeds provided at the bottom of the left-hand sidebar.  Note that it may take a while for some sites and search engines to index the new site configuration.  Again, if you experience any problems, let me know.

As readers will be aware, there has been enormous growth in economics-related blogging in the last year or so.  The days when you could count all the economics blogs on one hand have gone and keeping up with all these sites would be a major undertaking.  Fortunately, Professor Bill Parke has taken on the task of aggregating economics blogs at his [Economics Roundtable](http://www.economicsroundtable.com/index.php/rt/opinions/76/ "Economics Roundtable").  Since Bill has done all the work, I have linked to his site, rather than attempting to maintain a comprehensive blog roll of related sites.

I have also put up my Technorati Link Cosmos, which is my rather cheap way of returning the favour if you have taken the trouble to link to me.  Readers should go visit these sites, since they are obviously run by people of taste and discernment!  I have linked to a few other sites of interest, but otherwise intend on maintaining a parsimonious set of links.  My failure to link to your site is not necessarily a comment on its worthiness, just a reflection of the burden blog roll maintenance.
