---
title: "The Dismissal: Get Over It"
date: "2005-11-11"
categories: ["Politics"]
---

Today is the 30th anniversary of the dismissal of the Whitlam Labor government by the Queen’s representative in Australia.  [Lindsay Tanner](http://www.theaustralian.news.com.au/common/story_page/0,5744,17208346%255E601,00.html "Lindsay Tanner") has the best advice on this subject: get over it.  Dramatic though it was, it is all too easy to exaggerate the significance of this event.  The counter-factual history is one in which the Whitlam government would have been repudiated at the next election anyway.  The removal of Whitlam in November 1975 did little to arrest the secular expansion in the size of government over the last 30 years.  The current government has built extensively on Whitlam’s legacy in its further centralisation of power in the hands of the Commonwealth.  The scope for fiscal and regulatory competition within Australia’s federal system of government has never been smaller.

November 1975 does leave an important legacy for Australian republicanism.  The 1999 republican referendum arguably failed because republicans did not adequately address the issue of the reserve powers of the head of state.  The republican movement in Australia has always been motivated by anti-establishment nationalism rather than a genuine republican constitutionalism, so it has never taken constitutional issues seriously.  Republicans will be hard pressed to offer an improvement on constitutional monarchy while it retains this narrow nationalist mindset.  As far as heads of state go, one who lives thousands of miles away and minds her own business is about as good as it gets.
