---
title: "The Price of Reserve Bank Secrecy"
date: "2005-12-17"
categories: ["Economics"]
---

The RBA is willing to pay a high price to keep its deliberations from public scrutiny:

THE Reserve Bank of Australia spent \$304,530 on lawyers to block a Freedom of Information request to release details of its board’s deliberations over interest rates.

The RBA hired a team of lawyers from Clayton Utz to keep secret from [The Weekend Australian](http://www.theaustralian.news.com.au/common/story_page/0,5744,17593078%255E2702,00.html "The Weekend Australian") the central bank’s board minutes for the 12 months to March last year.

Files from the Attorney-General’s Department show Clayton Utz’s bill was \$275,458 for solicitors’ fees and \$29,072 for legal counsel fees for four months to November last year.

The cost is revealed in the Attorney-General’s FOI annual report…

The proceedings before the AAT were effectively brought to an end when the RBA issued a conclusive certificate, which perhaps offers a hint as to the nature of the legal advice they received. 

Opposition Treasury spokesman Wayne Swan said the legal bill seemed “an extraordinarily large amount of money”.

“We need more transparency and openness when it comes to Reserve Bank appointments and their deliberations,” Mr Swan said yesterday.

The ALP backed away from reforms to the RBA Act ahead of last year’s federal election.  It remains to be seen whether they can put up a meaningful reform proposal before the next one.
