---
title: "The Political Economy of Tax Reform"
date: "2005-08-29"
categories: ["Economics"]
---

There is growing impetus for a new round of tax reform, thanks in no small part to Malcolm Turnbull, who has released an important paper on [Taxation Reform in Australia: Some Alternatives and Indicative Costings](http://www.malcolmturnbull.com.au/downloads/listanon.aspx "Taxation Reform in Australia: Some Alternatives and Indicative Costings").  It deserves to be widely discussed.  The Prime Minister has acknowledged the desirability of further reform.  Even opposition finance spokesman Lindsay Tanner has come out in favour of a reduction in the top marginal rate, an important policy shift for the Labor Party.

The only politician seemingly lacking enthusiasm for further reform is Treasurer Costello.  Any mention of the need for tax reform is an implicit criticism of his nearly ten years as Treasurer, so his lack of enthusiasm is understandable.  Costello has recently sought to enhance his leadership credentials by diversifying the range of issues in which he takes an interest.  Yet it is fairly clear that he has nothing new or interesting to say on any of these issues either.  Costello would be better served tackling the important issues within his own portfolio if he wants to establish his leadership credentials.  At the moment, he shows every sign of being devoid of new policy ideas.
