---
title: "The Gerard Affair and RBA Governance"
date: "2005-11-30"
---

Most columnists are, rather predictably, analysing the Gerard Affair purely in party political terms.  The AFR’s ‘special investigation’ published yesterday never thought to question the significance of the Gerard matter for RBA governance, instead couching it solely in terms of the Treasurer’s political judgement.  [Alan Wood](http://www.theaustralian.news.com.au/common/story_page/0,5744,17408335%255E31478,00.html "Alan Wood") is the stand-out exception in appreciating the affair’s real significance in exposing the antiquated model of monetary policy governance that has been allowed to persist in Australia, which has its roots in the class warfare of the 1920s and 30s:

under the Reserve Bank Act there are no grounds for dismissing Gerard. Whether he has breached the Reserve Bank’s code of conduct for board members, published last year, is another matter.

The code was established because, as its preamble explains, the Reserve Bank Act says little about the conduct of board members. The preamble also says that board members recognise their responsibility for maintaining “an unparalleled reputation for integrity and propriety in all respects” in agreeing to the code.

Under the heading General Principles, the code states that board members will avoid any action, or inaction, that compromises the bank’s standing in the community and its reputation for integrity, fairness, honesty and independence.

There is no question of Gerard behaving improperly in carrying out his duties as a board member or compromising the RBA’s independence. But if the tax office documents cited by Monday’s Australian Financial Review, alleging that tax investigators were misled, are confirmed as accurate, Gerard would appear to be in breach of the code.

The fact that his actions predated the code and his appointment to the board does not necessarily mitigate the harm that revelations of his conduct could cause later. It would be interesting to hear the uncensored opinions of his fellow board members on whether his behaviour has injured the board’s standing.

However, as with most codes of conduct, there is no penalty for a breach. It is up to Gerard to decide whether he should resign to avoid any risk of damage to the board’s reputation.

Whatever his decision, it has raised again the vexed question of whether the existing RBA board arrangements are adequate.\
\
Curiously, the Gerard Affair also seems to have prompted a change of view on the part of UQ’s Stephen Bell, the author of the most comprehensive study of the RBA to date (which I review [here](http://www.cis.org.au/policy/spring04/spring04-9.pdf "here")).  Bell is quoted in the [SMH](http://www.smh.com.au/news/national/costello-stands-by-tax-sham-man/2005/11/29/1133026469439.html?page=2 "SMH") as saying:

*It makes the case stronger to stick more professionals … who don’t have shady deals in the business sector and who can contribute more to meetings.*

This is surprising given the rather uncritical endorsement Bell gave to the current governance arrangements for the Bank in his book, although no less welcome for that.
