---
title: "The Future Fund as Revenue Laundering Operation"
date: "2005-07-21"
categories: ["Economics"]
---

The government’s Future Fund, a massive proprietary trading operation being established at the expense of taxpayers, is a thinly disguised revenue hoarding scheme on the part of a government that has more money than it knows what to do with.  The [Minister for Finance](http://www.smh.com.au/news/business/taxing-questions-still-to-be-answered-for-16b-future-fund/2005/07/20/1121539033016.html "Minister for Finance") has now all but confirmed that the Future Fund’s earnings will be subject to taxation, siphoning the Fund’s earnings directly into consolidated revenue.  Of course, paying taxes on the Fund’s earnings is no less absurd that than the government using the Fund to purchase its own liabilities in the form of government securities.  It just serves to highlight the fact that the Fund has been explicitly designed to launder the proceeds of privatisation and protect them from being returned to taxpayers.
