---
title: "The Rise and Fall of Monetary Targeting in Australia"
date: "2005-07-06"
categories: ["Economics"]
---

My review of Simon Guttmann’s (2005) *The Rise and Fall of Monetary Targeting in Australia*.

*The Rise and Fall of Monetary Targeting in Australia* is a detailed examination of an important episode of macroeconomic policymaking.  Based on the author’s PhD thesis, the book brings together an impressive range of primary and secondary source material.  Guttmann was given unfettered access to the archives of the Reserve Bank through to 1986, although Treasury refused a similar request.  Guttmann also interviewed many current and former policymakers.

Guttmann sets out to examine why monetary targeting ‘gained favour in Australia during the 1970s, how it was used to support a number of economic policies and why it lost appeal in the mid 1980s’ (p. vii).  Guttmann concludes that ‘while the government, the Treasury and the Reserve Bank did, on occasion, provide a considered discussion of monetary targeting, unfounded assertion, dissembling and obfuscation were the rule.  Misguided policies and unfavourable economic performance were arguably the result’ (p. 250).  Similar conclusions could be reached about many other historical episodes of macroeconomic policymaking.  The importance of the monetary targeting episode lies in what it tells us about Australia’s economic policymaking institutions. 

The picture painted by Guttman in this regard is not a pretty one, with key policymakers and policymaking institutions shown to have been driven overwhelmingly by expediency, political and bureaucratic self-interest at the expense of good policymaking.  Neither Treasury nor the RBA covered themselves with glory throughout this period, being concerned mainly with promoting their own bureaucratic prerogatives, while seeking to avoid being held accountable for macroeconomic outcomes.  The role of Treasury and RBA before the Campbell Committee puts paid to the notion that these institutions were at the forefront of the push for financial deregulation.  The Treasury’s submission showed that it barely understood what it meant to have a market-determined exchange rate, arguing against floating the dollar on the grounds that ‘the degree of intervention required in the foreign exchange market to achieve a desired exchange rate would be larger with a market-determined rate’ (p. 139). 

The problems with the RBA’s conflicted statutory mandate are readily apparent throughout the book.  In an amazingly frank admission before the Campbell Committee, the RBA argued in relation to its own statute:

*it has become all too clear that the hoped-for compatibility of objectives, and even their meaning, are the very stuff of politics.  The Reserve Bank must pick its way as best it can…its range of choice depends upon the powers and actions of others, as much as upon its own.  The objectives are achievable in their entirety only in the long run (if at all).* (cited on p. 133)

It is hard to imagine a more telling indictment of the statutory framework that stills governs Australian monetary policy.  The RBA opposed monetary targeting, not least because ‘the accountability that a projection imposed on the authorities was incompatible with the Reserve’s reluctance to provide information about monetary policy’ (p. 241).  These problems were not confined to the monetary targeting episode.  In the wake of the abandonment of monetary targeting, Guttmann notes that ‘it quickly became apparent that a strategy for structuring monetary policy, and also communicating with markets, was absent’ (p. 234).  The check-list approach to monetary policy adopted from May 1985 proved equally unsatisfactory and arguably still lives on in the everything-but-the-kitchen-sink inventories the RBA now offers by way of explanation for its policy actions.

While Guttmann’s book is very revealing about the failings of Australia’s macroeconomic policymaking institutions, unfortunately, this is not his major focus.  Instead, Guttmann is overly preoccupied with criticising monetary targeting as such.  Many of these criticisms would today meet with very little resistance from the economics profession.  He expects the pronouncements of policymakers to bear a logical and theoretical consistency that is probably rarely observed in any area of policymaking at any time, much less the deeply contested area of macroeconomic policy.  While some of these criticisms are fair and reasonable, they are significantly less interesting than what the monetary targeting episode reveals about the institutional framework for macroeconomic policy in Australia. 

Reading Guttmann’s book, one could be forgiven for thinking that monetary targeting and monetarism were an historical aberration, rather than a necessary stage in the evolution of contemporary monetary policy practice.  While monetary targeting was ultimately abandoned in favour of the eventual adoption of interest rate and inflation targeting, the core monetarist insights that drove the experiment with monetary targeting in Australia, the US and elsewhere were absorbed into mainstream monetary theory and practice.  Former Federal Reserve Board Governor Ben Bernanke recently noted that ‘\[Milton\] Friedman’s monetary framework has been so influential that, in its broad outlines at least, it has nearly become identical with modern monetary theory and practice.’  The rise of a monetary view of inflation was critical in discrediting the price and income control policies that were competing for policymakers’ attention in the developed economies during the 1970s, when non-monetary views of inflation held sway, leading to the Great Inflation of that decade.  Monetary targeting was primarily a response to the failure of existing policies.  The long term success of the monetary view of inflation is reflected in contemporary macroeconomic outcomes.

Guttmann concludes that ‘as with the monetary target, - ideology - in the form of the inflation target and prevailing fashion of central bank independence - is also crucial to understanding the financial markets’ support for the present approach to monetary policy’ (p. 249).  Guttmann’s evidence makes clear that expediency and pragmatism rather than ideology were the main drivers of the monetary targeting episode and this is also true of inflation targeting and central bank independence today.  The significant improvement in macroeconomic outcomes in recent years relative to the period examined by Guttmann owes an enormous debt to the post-war revival of monetarist thought, a debt that goes unacknowledged in this book.
