---
title: "The US Net IIP: Non-Hysterical Version"
date: "2005-02-20"
categories: ["Economics"]
---

Much of the hysteria surrounding the US current account deficit reflects a basic lack of faith in US institutions and growth prospects.  [David Levey and Stuart Brown](http://www.iht.com/articles/2005/02/18/opinion/edlevey.html "David Levey and Stuart Brown") have a refreshingly different perspective:

While the NIIP will continue to grow for many years to come, future dollar depreciation and market adjustments in interest rates and asset prices will mean that its increase will be far less dramatic than many fear. Moreover, focusing exclusively on the NIIP obscures the United States’ institutional, technological and demographic advantages. The classic doomsayer argument - that growing foreign indebtedness results from too little savings by Americans - neglects the fact that savings and investment are seriously undervalued in U.S. economic accounts. When you include capital gains, 401(k) retirement plans, and home values, U.S. domestic saving is around 20 percent of GDP, the same as in most other developed economies. And when you consider “intangible” investment (like new-product development and design experimentation) as part of total, the supposed increase in consumer\
spending as a share of GDP turns out to be a statistical artifact.

Indeed, much of the explanation for chronic current account deficits relates to the U.S. economy’s strong fundamentals, not fatal structural flaws.

The country with the world’s strongest external investment position is Japan, which achieved this dubious distinction by trashing its potential growth rate and the returns on domestic investment through state-sponsored forced saving and the overcapitalistion of its economy. 

(thanks to Jack S. for the pointer)
