---
title: "The UK Election, Liberalism and Strategic Voting"
date: "2005-04-01"
categories: ["Politics"]
---

[Samuel Brittan](http://www.samuelbrittan.co.uk/text208_p.html "Samuel Brittan") recently wrote about his intention to vote for the Lib-Dems in the forthcoming UK election, having voted for the Labour Party in 2001:

In going for the Lib-Dems I am under no illusion that they are the party of Gladstone and John Stuart Mill. But at least they are different from Labour and Conservative; and there is nothing wrong in voting for negative reasons. In the past I have shrunk from supporting them because they looked too much like the unreconstructed Old Labour of the 1980s. But since Gordon Brown’s large increases in public service spending, they have found less mileage in that direction; and the recent Orange Book from the still-too-small free market wing of the party suggests a move in the right direction, as does the appointment of the eminently sensible Vincent Cable as their shadow chancellor.

There is no avoiding tactical voting in our present electoral system; and if your main objective is to keep out either Labour or the Conservatives at all costs then there are only a few constituencies where voting Lib-Dem would make sense. But if you believe that two terms of Labour are long enough and you would not mind a hung House of Commons then feel free to go for the Lib-Dems.

It says a lot about the Tories that one of Britain’s most prominent classical liberal commentators cannot bring himself to vote for them.  But the fact that he has turned his back on the Labour Party is also telling.  The prediction markets are implying a Labour victory is a near certainty, but I suspect this is one election the prediction markets will get wrong.  With the Tory campaign now being run by the same campaigners who made John Howard Australia’s second longest serving Prime Minister and with Tony Blair on the nose with the anti-war left, the Labour Party will have their work cut out for them.
