---
title: "The Biggest Bubble in History?"
date: "2005-06-17"
categories: ["Economics"]
---

House prices feature on the cover of The Economist.  With its usual hyperbole, the Economist claims that house prices are now ‘the biggest bubble in history.’  Its benchmark for this claim is the percentage change in the capitalisation of the housing stock relative to GDP.  Apart from the dubious stock versus flow comparison, the [Economist](http://www.economist.com/opinion/displaystory.cfm?story_id=4079458 "Economist") would have us believe that this is all pure asset price inflation: 

*the biggest increase in wealth in history was largely an illusion.*

The many real factors that might be contributing to an increased capitalisation of the housing stock are all irrelevant apparently.  With all the authority of a hellfire preacher, The Economist claims to have seen it all coming and proclaims ‘the day of reckoning is closer at hand.’  It is all just so shriekingly obvious to [The Economist](http://www.economist.com/finance/displayStory.cfm?story_id=4079027 "The Economist").  It’s everyone else that must be stupid:

*The rapid house-price inflation of recent years is clearly unsustainable, yet most economists in most countries (even in Britain and Australia, where prices are already falling) still cling to the hope that house prices will flatten rather than collapse.*

I would suggest that what economists are clinging to is the intellectual modesty The Economist magazine surrendered a long time ago. 

The great Max Corden once said that worrying about something that is ‘unsustainable’ is like worrying about the growth rate of a teenager.  Australia’s experience both historically and with the current moderation in house prices certainly points to the ‘flatten’ rather than the ‘collapse’ scenario.  The fact that falling house prices have made the cover of The Economist, notorious as a contrarian indicator, is perhaps the most reassuring sign yet.
