---
title: "The Growing Chorus for Tax Reform"
date: "2005-03-31"
categories: ["Economics"]
---

[Ross Garnaut](http://www.theaustralian.news.com.au/common/story_page/0,5744,12704652%5E7583,00.html "Ross Garnaut") joins the growing chorus for tax reform:

The most urgent task is to reduce considerably the effective marginal tax rates for social security recipients, the high levels of which contribute to relatively low labour force participation and high levels of part-time employment.

High taxation rates are also significant elements in labour force participation and the attraction and retention of skilled personnel at higher levels—and probably at all but the highest levels of the incomes range.

A reform of taxation rates that established a flat 30 per cent marginal effective tax rate for all corporate and personal income, including capital gains, would be most advantageous for people at the bottom of the income range, and most disadvantageous for Australians on the highest incomes and with the greatest wealth. Contrary to popular perception, it would be progressive, as well as being highly advantageous to incentives for greater labour force participation. It would have the additional advantage of removing the gains from conversion of personal into corporate income. Raising the rate of taxation on capital gains (it would need to be on real rather than nominal gains) would have the incidental effect of greatly reducing the distortions in capital allocation that have spurred the housing and associated consumption boom.

Needless to say, I disagree with Garnaut on capital gains tax and its supposed effects, but a flat 30/30/30 system for personal, corporate and capital gains tax has some appeal and should be readily achievable.  Unfortunately, the government still shows no sign of taking tax and spending reform seriously.
