---
title: "The Flat Tax Costello Rejects"
date: "2005-10-14"
categories: ["Economics"]
---

The [30% flat tax plan](http://www.theaustralian.news.com.au/common/story_page/0,5744,16913865%255E601,00.html "30% flat tax plan") Treasurer Peter Costello rejected:

WHEN Treasurer Peter Costello left Canberra for his Christmas break last year, he had before him modelling for the most radical reform to income tax in 60 years.

The ambitious plan, prepared for the 2005 budget, would have replaced all the existing tax scales with a single flat rate of tax of 30 per cent…

The plan was clearly affordable without pushing the budget into deficit, with the cost rising from \$7.7 billion in 2005-06 to \$10.1 billion in 2008-09…

Only those privy to the Treasurer’s thinking know why the plan was dropped, but it may have been because of an analysis Treasury prepared on who would be the winners. Although nobody would be worse off as a result of the changes, only 20 per cent of taxpayers would be better off.

A more plausible explanation is that Costello is rationing tax cuts to fit with his leadership timetable.
