---
title: "The Political Economy of Tax Reform"
date: "2005-05-14"
categories: ["Economics"]
---

This [insider account](http://www.theaustralian.news.com.au/common/story_page/0,5744,15281772%255E2702,00.html "insider account") of the how the budget tax cuts were framed is quite revealing about the political economy of tax reform in Australia:

All the savings and outlays were known. What had not been finalised was the size and shape of the tax cuts **because the final revenue figures were not known**.

Both Howard and Costello are Liberal leaders committed to a doctrine of returning revenue to taxpayers **if** they can do so **after** achieving a budget surplus **and** paying for services (emphasis added).

What this outtake reveals is that the government views tax relief as just a residual, to be funded only out of the surplus.  The government has given no thought to tax reform over and above what is made possible by the surplus.  What is missing from this formulation is any consideration of reductions in government spending as a means of lowering the tax burden.  In the absence of such spending cuts, a meaningful reduction in the overall tax burden, as opposed to just a hand back of bracket creep, is impossible.

As it happens, the government has used the Future Fund as a cloak of respectability for retaining a large part of the surplus, which will now be used to partially nationalise financial markets for the benefit of future consolidated revenue.  The absurdity of this arrangement is that it makes no difference whether public service superannuation liabilities are paid for out of current revenue or future spending.

Terry McCrann suggests a better approach to budget strategy (no link):

The best way to generate the revenues to meet all obligations of tomorrow, is to maximise contemporary output in the context of building the highest sustainable growth path for the economy.

And one of the best ways to do that is to devote all surpluses to tax cuts/reform so that the budget remains essentially balanced year-in and year-out.

Meanwhile, don’t miss this [important letter](http://www.smh.com.au/news/Business/Important-message-to-investors-in-Aust-Ltd/2005/05/13/1115843369871.html "important letter") to shareholders from John Howard, MD of Aust Ltd:

Furthermore, the Board has decided to change the Articles of Association to require all future profits to be applied to the staff superannuation fund which, thanks to over-generous employment agreements in the past providing for sumptuous lifetime pensions for all staff, is in the red to the tune of \$91 billion.

It has been agreed by the Board that these future profits will not simply be added to the existing superannuation fund, but that a new fund - to be called the Future Fund - will be created with a new bureaucracy of its own and operated by people to whom the directors owe favours, to act as a job creation scheme for investment professionals…

The decision to apply all future profits to eliminating this liability means, unfortunately, that the moratorium on reinvestment in the assets of the business will continue for at least another six years.
