---
title: "The Reserve Bank and Industrial Relations ‘Reform’"
date: "2005-03-07"
categories: ["Economics"]
---

The old joke about the Australian economy was that the Reserve Bank set interest rates and the Industrial Relations Commission set the unemployment rate (through its determination of minimum wages).

Now the government wants the RBA to help set the unemployment rate too, with a [proposal before Cabinet](http://www.smh.com.au/news/National/Pay-rise-critics-could-rule-on-wage-claims/2005/03/06/1110044260128.html "proposal before Cabinet") to have representatives of the RBA and Treasury sit as members of the Commission.  The government seems to think that the RBA and Treasury will help secure more moderate wage increases:

*Senior government ministers are believed to be privately concerned about the impact on inflation - and flow-through pressure on interest rates - if the current labour market shortages lead to wage rises.*

The implication here is that the RBA should control inflation, not just through monetary policy, but through direct participation in centralised wage fixing.  It is becoming painfully apparent that the government’s idea of ‘reform’ across a wide range of areas is simply to further centralise power in the hands of the feds.

While on the subject of labour markets, Professor Charles Baird will be speaking to ABE on 23 March in Sydney on the ‘The American Labour Market: Lessons from Deregulation.’  See the [ABE web site](http://www.abe.org.au/eindex.html "ABE web site") for details, where a copy of the paper will most likely be posted after the event.
