---
title: "The House Economics Committee Gets a New Chair"
date: "2005-02-17"
categories: ["Economics", "Politics"]
---

Those of us who argue for greater central bank transparency can only cringe when the Reserve Bank Governor fronts the House Economics Committee.  You have to admire the patience and politeness Governor Macfarlane displays in the face of the Committee’s woeful displays of economic illiteracy and ham-fisted attempts at point scoring. 

Things are not going to get much better under the Committee’s new chair, Bruce Baird, who has rather helpfully put out a [press release](http://www.aph.gov.au/house/committee/efpa/rba2003_04/media/media001.pdf "press release") alerting us to what is on the Committee’s collective mind.  Baird says:

*I’m also interested in what incentives the Reserve believes are needed to encourage greater private investment and whether there should be a diversion away from investing in private housing.*

This is of course well outside the Governor’s mandate and, dare I suggest, also outside the realm of legitimate public policy concern.  The implication that investment in housing is excessive is particularly galling coming from people whose own homes are, at a wild guess, a cut above average.  It is fine for them to invest in housing, but a dangerous ‘bubble’ when everyone else gets in on the act.

Baird is also a coordinator of the informal government committee, the Friends of Tourism Group.  This sits rather uneasily with his [current efforts](http://www.smh.com.au/articles/2005/02/15/1108230002421.html "current efforts") to deny Singapore Airlines access to the Australia-US route in order to protect Qantas jobs in his electorate, which includes Sydney Airport.  The sort of ‘friend’ tourism could do without.
