---
title: "The Budget, the Leadership and the Spectre of Fraserism"
date: "2005-05-07"
categories: ["Economics"]
---

The pre-Budget leaks suggest a continuation of the politics of redistribution that has charaterised the current government’s approach to fiscal policy.  As [Paul Kelly](http://www.theaustralian.news.com.au/common/story_page/0,5744,15202229%255E12250,00.html "Paul Kelly") notes, the politics of redistribution will simply no longer cut it:

The Howard Government is a victim of its success and rhetoric. It has forgotten how to talk to the people about reform and challenge. It has not told the people the truth about the globalised age - that a market-based economy needs constant structural change to renew itself and maintain growth. It has been in office so long and made such a virtue of prosperity, naturally, that it can’t spin another story.

The Government is close to embracing a “no losers” political tactic. Once a government reaches this position its political nerve is shot. The Government seems hesitant to accept the responsibility that comes with Senate control when it has no excuses left. It is so used to fudge and compromise that it now feels trapped in the spotlight.

Another Budget of fudge and compromise also does not say much for Peter Costello’s leadership aspirations, as [Greg Sheridan](http://www.theaustralian.news.com.au/common/story_page/0,5744,15201411%255E25377,00.html "Greg Sheridan") notes:

the case for Costello seems to be simply that it’s his turn and if he doesn’t get it he’ll blow up the Government. But voters are profoundly unimpressed with the argument of any politician that it’s his turn.

The one area where Howard is weakest is in seeing the urgency of economic reform. Yet Costello has run no crusades here. The two most notable acts of economic reform of this Government are the GST and industrial relations deregulation, both intensely associated with Howard. It’s difficult to get Costello in private conversation even to admit that taking half of every additional dollar that people earn in tax is too much.

After ten Budgets, any mention of the need for fundamental tax reform is a direct challenge to Costello’s credibility.
