---
title: "The Anglo-American Model Delivers"
date: "2005-02-18"
categories: ["Economics"]
---

I recently came across a forsaken copy of Peter Brain’s (1999) *Beyond Meltdown* in a second-hand bookstore.  In the course of a diatribe against ‘neo-liberal’ economics and the ‘American’ economic model in Australia, Brain forecast that the Australian economy would enter a prolonged stagnation in the wake of the 2000 Olympics, during which the unemployment rate would return to the double-digit figures seen during the last recession in the early 1990s.

Instead, the Australian economy has gone from strength to strength, with the unemployment rate hitting multi-decade lows, precisely because it has generally avoided the policy prescriptions favoured by the likes of Brain.

The Anglo-American economies currently look a whole lot better than those countries that have followed less liberal policy prescriptions.  Japan has just gone back into recession for the third time since 1998.  Germany is just shy of its third recession in four years.

Meanwhile, the UK, Australia and NZ are all enjoying their lowest unemployment rates in decades.  This is particularly telling, since the ‘neo-liberal’ policies supposedly favoured by the Anglo-American economies are often stereotyped as anti-employment.  The evidence suggests otherwise.

Of course, there is no reason why the Anglo-American economies cannot also experience a downturn in the near future, but even in recession, they will fare much better than those economies outside the Anglo-American bloc, due to their greater commitment to liberal policy prescriptions.

**UPDATE:**  My Google ad strip is now rather amusingly showing “Discount GDP Forecasts: New and Used GDP Forecasts.”  It is of course an ad for Ebay, not Peter’s book.
