---
title: "The Doomsday Cult Takes a Bath, III"
date: "2005-10-10"
categories: ["Economics"]
---

The [WSJ](http://online.wsj.com/article/SB112889856683264011.html?mod=opinion_main_review_and_outlooks "WSJ") weighs in and declares a winner:

For a couple of years now, we’ve been watching a debate, generally speaking, between two economic factions. The first and largest group has routinely predicted slower growth, if not recession, almost as a rite of spring and sometimes autumn too. This crowd has included the most prominent economists on Wall Street, and most of those you see quoted in the media. In this view, inflation was nowhere to be seen, and for many of them the real danger was the budget and trade deficits. The Fed could stop raising rates at any time, the sooner the better.

A second, smaller band of economists has predicted robust growth all along, especially in the wake of the 2003 tax cuts. This group includes Brian Wesbury and David Malpass, to cite two economists who often appear on these pages. Their main concern has been that the Fed underestimated the economy’s strength and kept monetary policy too easy for too long. This has let inflationary expectations build up again, perhaps leading to trouble down the road as the Fed compensates for its mistake by raising rates higher than would otherwise have been necessary.

Well, the evidence is mostly in, and the second group looks to be the winner.
