---
title: "The Reserve Bank as Political Trade Practices Commission"
date: "2005-04-08"
categories: ["Economics"]
---

[This story](http://www.smh.com.au/news/National/Reserve-feared-it-was-used-as-election-pawn/2005/04/07/1112815670317.html "This story") makes the extraordinary claim that the RBA referred some of the Coalition’s advertising material to the Australian Electoral Commission during the last federal election campaign:

the central bank believed that some of the material in the Coalition’s campaign leaflets was exaggerated and that some was factually wrong, the officials said.

However, the bank concluded that it was the role of the electoral commission to police election campaigns.

Reserve Bank officials referred the Coalition’s leaflets to the commission during the six-week campaign and asked whether they breached any regulations.

The commission responded that it was unable to take action to halt a political party making policy claims or predictions even where they might be false and misleading, the officials said.

The bank decided that it would have to allow the Coalition’s claims to be contested by other political parties, and that it could not intervene without provoking headlines saying “Reserve says PM wrong,” a senior official said.

The bank was anxious to avoid this because it would make the bank itself the centrepiece of the campaign, the official said.

The Bank’s second decision (‘that it would have to allow the Coalition’s claims to be contested by other political parties’) was the correct one.  The fact that the AEC took no action shows that the RBA was grossly mistaken in thinking either it or the AEC had a role in arbitrating political truth.  Politicians make all sorts of ridiculous economic claims during election campaigns and the RBA could make a full-time job out of correcting them.  That the RBA would even contemplate setting itself up as some sort of political Trades Practices Commission is symptomatic of its paternalistic mistrust of markets, in this case, the political marketplace.
