---
title: "The Fed Succession: When Supply-Siders Attack"
date: "2005-08-13"
categories: ["Economics"]
---

The [WSJ](http://online.wsj.com/public/article/0,,SB112367212932209661,00.html?mod=free_interactives "WSJ") surveys US economists on their preferred replacement for Alan Greenspan, with CEA Chair Ben Bernanke commanding a plurality of support at 30%.  Bernanke is also still the favourite on Intrade, although the Bernanke contract has suffered recently in the wake of a Lawrence Lindsay rally (dare I suggest ‘bubble’?) on the strength of a favourable mention in another WSJ story.  Perhaps the biggest uncertainty about each of the candidates is whether they actually want the job.  Bernanke would make a fine Fed Chairman, although I think Martin Feldstein is the stronger prospect.

We previously noted Bryan Caplan’s defence of Bernanke against the attack of the fever swamp Austrians.  Leading free banking theorist [Larry White](http://divisionoflabour.com/archives/001565.php "Larry White") also offers a partial defence of Bernanke against a rather strange and ill-considered attack from the National Review’s knee-jerk supply-siders.  As someone who is also partial to free banking (albeit of the Yeager-Greenfield BFH variety), I have very few reservations about Bernanke.  Indeed, some of Bernanke’s recent work is consistent with the views of pre-rational expectations, old school monetarism, a departure from the neo-Wicksellian paradigm that dominates contemporary thinking about monetary policy. 

The WSJ story quotes at least one analyst saying:

financial markets have become overly complacent about the succession question. He says any successor, no matter how sound, will be selected at some cost to the markets.

“Nobody can replace Greenspan’s reputation,” Mr. Harris says. “His reputation helps keep low risk premiums in the markets. That will be lost on the day he retires. It can be re-earned by the next chairman, but there will be some loss.”

One of the costs associated with the highly discretionary approach to monetary policy personified by Alan Greenspan is the failure to institutionalise the Fed’s credibility.  Hopefully, the next Fed Chair will begin the task of formalising an inflation targeting framework for US monetary policy.
