---
title: "The Bull Market in Bubbles"
date: "2005-04-12"
categories: ["Economics"]
---

Barry Ritholtz on the [bubble in bubbles](http://bigpicture.typepad.com/comments/2005/04/the_bubble_in_b_1.html "bubble in bubbles"):

we currently find ourselves now in a Bull market for Bubbles. There is the housing Bubble, the oil Bubble, the interest rate Bubble. I have read about the import Bubble, the China bubble, the current account deficit Bubble, and the credit debt Bubble.

The Fed does econometric research to see if we can detect Asset Price Bubbles in advance. Several writers believe China is one great big Bubble - if not the nation, than China Net stocks. Some books advise us how to survive Bubbles, while others warn us of the impending Bubble in US foreign policy. From Australia, we learn there is even a Bubble in economic blogs.

In short, we have a Bubble in Bubbles.

Yet if we give careful consideration to the nature of bubbles, we see that most of these are not bubbles at all. They may be assets whose prices are extended - but being overpriced is not the same as being a Bubble. Rapid price appreciation increases the chance of a significant price retracement in the future. But all Bubbles? Hardly.

Unfortunately, this meta bubble is unlikely to burst any time soon.  As with many so-called bubbles, it actually has a fundamental basis: the inability of so many commentators to understand or think seriously about the market processes underlying asset price determination.
