---
title: "The Rise and Fall of Monetary Targeting: A Postscript"
date: "2005-08-19"
categories: ["Economics"]
---

A postscript to my [review](../2005/the_rise_and_fall_of_monetary_targeting_in_australia.qmd "review") of Simon Guttmann’s *The Rise and Fall of Monetary Targeting in Australia*.  Apparently, the publisher has withdrawn the book on legal grounds, which will make what was always going to be an inaccessible title even more so.  Given Australia’s draconian defamation laws, the withdrawal and pulping of books is not uncommon, although one would have thought that publishers would be sufficiently alert to these risks by now to avoid this sort of outcome.

As I indicated in my review, I don’t think Guttmann properly acknowledged the role played by the post-war revival of monetarist thought and the monetary targeting experiments of the 1970s and 80s in the evolution of contemporary monetary policy theory and practice.  For a work of both intellectual and economic history, this is a serious flaw.  Other readers evidently had their own, more personal, objections to Guttmann’s version of history. 

Who said monetary targeting had to be dull!
