---
title: "The Conundrum that Wasn’t"
date: "2005-12-10"
categories: ["Economics"]
---

[Alan Wood](http://www.theaustralian.news.com.au/common/story_page/0,5744,17516802%255E31478,00.html "Alan Wood") is coming around to the view that there is no bond yield ‘conundrum’:

there seems to be an emerging view that world bond markets may have been behaving rationally after all and that a 10-year US Treasury bond yield of around 4.5 per cent actually reflects the likely interest-rate path over the next decade.

An important test of this view is approaching. If, as markets expect, the Fed is close to the end of its rate rises and the Fed funds rate will peak at 4.5-4.75 per cent, and if this signals a peak in global interest rates, then a 10-year bond rate of 4.5 per cent won’t look too silly after all.\
\
It is strange that Greenspan ever floated the idea of a ‘conundrum,’ since an obvious explanation for the phenomenon is the increased credibility central banks have amassed relative to previous cycles, particularly the 1994 bear market in bonds.  Like his ‘irrational exuberance’ speech in 1996, the ‘conundrum’ was probably meant to be more of a rhetorical question than anything else, a case of Greenspan thinking aloud.

Current bond market pricing is also an obvious challenge to those who see the recent rise in the nominal gold price to near 25 year highs as heralding a new Great Inflation such as that seen in the 1970s.  If you believe that this is what is driving the gold price, then you must also think the bond market is massively wrong.  Is it really credible to argue that gold market participants know something bond market participants don’t?
