---
title: "The Euro:  Too Crappy, Even for the Italians"
date: "2005-06-05"
categories: ["Economics"]
---

One of the great attractions of the euro was that it offered instant monetary credibility to countries with less than stellar inflation records like Italy.  For these countries, the euro was a free lunch.  They could import monetary policy credibility, without having to make difficult monetary and fiscal policy decisions over and above satisfying the convergence criteria.

Italian politicians are [now seeking support](http://www.guardian.co.uk/italy/story/0,12576,1499165,00.html "now seeking support") for a referendum to pull Italy out of the euro:

Roberto Maroni, Mr Berlusconi’s social security minister and a joint acting leader of the Northern League, said his party would start collecting signatures for a referendum on the issue later this month. He also appealed for the process of ratifying the EU constitution to be halted.

Days after it was reported that senior German ministers had discussed the disintegration of the single currency, Mr Maroni pledged to start collecting signatures for a referendum later this month. He branded the euro a “disaster” which was product of a “European model whose failure we are witnessing with concern”...

Mr Maroni held up Britain as a model to be copied. “It is growing \[and\] developing while keeping its own currency,” he said.

(via [Alex Singleton](http://www.globalizationinstitute.org/blog/000376.php "Alex Singleton"))
