---
title: "The Bubble in Economics Blogs"
date: "2005-03-06"
categories: ["Economics"]
---

I think it has become obvious that economics blogs are in a dangerous bubble.  In March of 2003, there were only a handful of economics blogs.  I know this because a *Forbes* journalist who contacted me at the time about an article he was writing on economics blogs confessed his relief at finding mine.  Until then, he had been struggling to make up the five he needed for his [story](http://www.forbes.com/2003/03/19/cx_ah_0319econoblogs.html "story").

As of March 2005, Professor Bill Parke is tracking 72 economics blogs at his [Economics Roundtable](http://www.economicsroundtable.com/index.php/rt/opinions/76/ "Economics Roundtable").  So we seem to be adding around 34 new economics-related sites to the blogosphere every year.  This is clearly unsustainable and conclusive proof of the irrationality of bloggers!  Some economics bloggers are even purchasing Google ads in a desperate scramble for market share. 

Clearly government intervention is required to bring order to this sector of the blogosphere and prevent a blog boom-bust cycle from developing.  As a solution, I propose the nationalisation of blogs, starting with [John Quiggin](http://www.johnquiggin.com "John Quiggin"), who can then educate us all on the merits of public ownership of the means of blogging.

[Marginal Revolution](http://www.marginalrevolution.com "Marginal Revolution") will be broken up by the Justice Department into two separate blogs, one for Tyler and one for Alex, to end its market dominance.

The weaker economics bloggers will be subsidised or given jobs at *The Economist* magazine writing stories about the dangers of bubbles and how markets, the Fed, home buyers and American voters are all stupid compared to the magazine’s all-knowing leader writers.
