---
title: "The RBA as Central Planner"
date: "2005-03-12"
categories: ["Economics"]
---

[Alan Kohler](http://www.smh.com.au/news/Alan-Kohler/RBA-move-shows-it-has-little-trust-in-the-market/2005/03/11/1110417684665.html "Alan Kohler") accuses the RBA of central planning:

the basic problem is that the Reserve Bank does not trust the market. And why should it? It is a regulator whose sole purpose is to offset market forces.

Right now Australia needs market forces to work. There are, it is generally agreed, shortages of skilled labour and infrastructure capacity. There is also general agreement that the only answer to this is to slow “the economy” by lifting interest rates so the demand for these things falls to meet the supply.

This is a strategy straight out of central planning. Forcing the economy to slow so that demand meets an inadequate supply is a policy of despair by those who don’t trust the market.

At least we can be reasonably sure Alan hasn’t been nobbled by any insider relationship with the RBA!  I have a little more sympathy for the RBA’s position.  The current debate about monetary policy is actually a good example of how the RBA’s conflicted, catch-all statutory mandate gets it into trouble.  An independent, inflation targeting central bank is perfectly entitled to wash its hands of structural issues.  A central bank reliant on a letter from the Treasurer for its independence and responsible for ‘the welfare of the people of Australia’ cannot expect to get off the hook quite so easily.  This is why the RBA Governor gets asked about everything but the kitchen sink when he fronts the House Economics Committee.
