---
title: "The Joke is on Costello"
date: "2005-08-31"
categories: ["Economics", "Politics"]
---

Treasurer Costello has ridiculed fellow Liberal MHR Malcolm Turnbull’s discussion paper on tax reform, but the joke is actually on Costello.  Turnbull’s paper has effectively exposed the fact that Costello is a policy-free zone.  Costello is the most conservative senior politician in Australia, in the non-political sense of the term.  He is uninterested in reform, because he sees it as potentially disrupting his path to the leadership.  What Costello brings to the leadership is nothing more than a well developed sense of entitlement.  Even as a political strategy, this is deeply flawed, as [Paul Kelly](http://www.theaustralian.news.com.au/common/story_page/0,5744,16439339%5E12250,00.html "Paul Kelly") argues:

Peter Costello’s reform was far too cautious. By changing the thresholds and keeping the rates, he doomed his package to eclipse before a more reformist push. Costello was too cautious - and caution is not the quality needed to replace Howard in the Lodge…

On the ABC’s 7.30 Report on Monday, Costello was the opposite of a can-do leader. He was, instead, Mr If. The Treasurer believes in lower tax but only “if” it is possible in political terms; his distaste for cutting the top rate was obvious. The Coalition, of course, has just won the Senate.

This is a bizarre and risky situation. Shadow finance minister Lindsay Tanner sees a lower top rate as part of tax reform with equity. So does trade union leader Bill Shorten, en route to the ALP caucus. They share much of the terrain sketched out by Liberal MP Malcolm Turnbull…

Politics is driving Costello’s position and he admits this. He told the 7:30 Report that he wanted to focus on the 97 per cent of taxpayers not the 3 per cent. So Costello is the champion of the mainstream against a more ambitious tax reform agenda. He debunked Turnbull’s base broadening, pointing out that it meant increasing some taxes.

The problem for Costello, however, is that this debate will only intensify. It doesn’t matter that his May reforms aren’t completed until next year. Nor does his populist 97 per cent-3 per cent paradigm to debunk Turnbull have much traction.

Costello’s worst mistake would be to fall into defensive mode and champion the status quo, a blunder Howard will never make…

The irony is that Tanner is more aggressive about tax reform than Costello. Tanner sees cutting the top rate as slotting into a bigger reform, and he’s right. There is a beautiful political position opening up for Labor with the Coalition assuming that Labor lacks either the brains or the guts to seize it.
