---
title: "The Reserve Bank as ‘Benign Autocracy’"
date: "2005-04-02"
categories: ["Economics"]
---

[John Garnaut](http://www.smh.com.au/articles/2005/04/01/1112302237756.html "John Garnaut") uses next week’s Reserve Bank Board meeting as a hook to consider Australia’s 1920s model of monetary policy governance (Ross Gittins is obviously on leave!):

Professor Adrian Pagan, an economist at the Australian National University, sat on the Reserve’s board for five years to 2001.

Pagan says the bank is a “benign autocracy” where good policy outcomes have obscured the need to look more closely at rules and processes.

By the time of the 1990 recession, the rules that empowered and governed the bank had barely changed in 40 years. Fifteen years later and those rules and structures still have not changed.

“I think that once you become independent, it’s appropriate that you do change the governance structure,” he says. “Most others have changed, it’s unusual that we haven’t.”

Pagan’s reform agenda includes the publication of board meeting minutes, transparent risk-control processes for currency trading and, most importantly, restructuring the board.

The Reserve Bank board structure was established 80 years ago and remains almost unique among central banks.

Representing the institution are Macfarlane and his deputy, Glenn Stevens. Henry, secretary of the Treasury, represents the Government - although Macfarlane has said he still doesn’t know whether the Treasury secretary speaks for the Treasury or the Treasurer.

Five positions have been reserved for business people for most of the period since 1924. Not all have been praised for their contributions.

“They are very non-expert - to very high degree,” \[former Board member Professor Bob\] Gregory says. “I found that surprising.”

I make similar criticisms of Reserve Bank governance [here](http://www.cis.org.au/policy/spring04/spring04-9.pdf "here").
