---
title: "The Demise of the Euro"
date: "2005-07-07"
categories: ["Economics"]
---

Back in 1999, I gave the euro five years at most.  My prediction might have worked out if the goal posts, in particular, the Stability and Growth Pact, had not been shifted.  Milton Friedman gave himself more wriggle room by forecasting the euro’s demise within ten years.  The euro project is now being seriously questioned, and its possible demise actively canvassed, as [Joachim Fels](http://online.wsj.com/article/0,,SB112068356089678758,00.html?mod=opinion%5Fmain%5Feurope%5Fasia "Joachim Fels") notes:

A full-blown political union in Europe is not only unlikely, it is also undesirable. Europe’s cultural, political and institutional diversity should be seen as a strength rather than a weakness because it encourages institutional competition for ideas and for mobile capital…

The euro’s founding fathers assumed that monetary union would over time quasi-automatically lead to political union and thus didn’t spend much time worrying about the long-run viability of the euro. But their assumption is clearly no longer valid…

As long as all euro members agree that higher inflation and fiscal deficits are desirable or at least unavoidable, this does not yet put the euro at risk. Each euro would merely buy less domestic and foreign goods and services. However, some member states’ tolerance for inflation and fiscal deficits is likely to be lower than that of others, especially if the euro would turn into a mini-lira. In this case, the more stability minded members might decide to introduce a harder currency. Needless to say, a break-up of EMU would be economically very costly for all parties involved. But that doesn’t mean it cannot happen.

These costs need to be balanced against the reduction in macroeconomic policy risk that would occur with the demise of the euro, in particular, the risk of serious monetary policy mistake by the ECB being propagated across the euro zone.
