---
title: "The Real Ben Bernanke"
date: "2005-10-25"
categories: ["Economics"]
---

The market reaction to Ben Bernanke’s nomination as Fed Chair has been disappointing.  The implication that Bernanke is somehow more inflation friendly than Greenspan reveals profound ignorance about Bernanke’s thinking.  This view largely stems from two speeches given during the 2002-2003 deflation scare, in which Bernanke canvassed various quantitative approaches to monetary policy that might be used as an alternative to the Fed funds rate should the zero bound become a binding constraint.  Bernanke’s willingness to canvass unconventional approaches to monetary policy should if anything be welcomed.  I suspect very few of the people who derisively refer to ‘printing press Ben’ have bothered to even read these speeches, much less understood their significance or context.  It is interesting that Bernanke’s nomination has attracted endorsement from libertarian economists like [Tyler Cowen](http://www.marginalrevolution.com/marginalrevolution/2005/10/ben_bernanke_ec.html "Tyler Cowen"), [Bryan Caplan](http://econlog.econlib.org/archives/2005/10/bernankes_nomin.html "Bryan Caplan") and even qualified support from an arch free banker like [Larry White](http://divisionoflabour.com/archives/001857.php "Larry White").  Those on the libertarian right who have criticised Bernanke do so largely out of ignorance, but it seems these silly prejudices against Bernanke have wider currency given the market reaction to his nomination.

The negative market reaction to Bernanke’s nomination is also disappointing in the sense that it shows that the credibility of the Fed resides largely in the position of Chairman, not the institution itself.  This is the unfortunate legacy of Greenspan’s highly discretionary approach to Fed policy and hostility to inflation targeting.  I suspect that reform of Fed governance is high on Bernanke’s agenda.  Bernanke’s interest in inflation targeting is particularly promising in this regard.  The [WSJ’s](http://online.wsj.com/article/SB113020585591478414.html?mod=opinion_main_review_and_outlooks "WSJ's") reference to a ‘Bernanke Standard’ misses an important point: Bernanke may well end up presiding over the de-personalisation of US monetary policy, elevating process above personality.

Finally, it should be noted that Bernanke’s nomination is another event the prediction markets got ‘right,’ in the sense that the Bernanke contract was consistently the highest priced contract for next Fed Chair on [Intrade](http://www.intrade.com/apply.jsp?heardFromPromotionDetail=s0545138709r "Intrade").
