---
title: "The AEI Disgraces Itself Yet Again"
date: "2005-06-07"
categories: ["Economics"]
---

Why is it that the right-wing American Enterprise Institute is [channelling](http://www.aei.org/publications/filter.all,pubID.22612/pub_detail.asp "channelling") John Quiggin and Ross Gittins?

LETTERS TO THE EDITOR\
The Economist  \
Publication Date: June 2, 2005\
\
Sir—You waxed lyrical about Australia’s 15 years of continuous economic growth. However, you gloss over the fact that Australia’s external imbalances have never been larger, even at a time when international commodity prices are booming and China is expanding rapidly. You also failed to note that Australia’s housing bubble and consumer over-indebtedness make the United States look like a paragon of frugality. A more balanced view might have asked what happens to Australia when commodity prices ebb and when China’s investment bubble bursts?

Desmond Lachman is a resident fellow at AEI.

Since the Australian economy powered through the global collapse in commodity prices in 1998 after the Asian crisis with a real annual growth rate of 6%, I think we already know the answer to that question Des!

Maybe Quiggin and Brad DeLong [were right after all](http://johnquiggin.com/index.php/archives/2002/12/20/decline-of-the-american-enterprise/ "were right after all"):

*“Back in the late 1970s, the American Enterprise Institute ranked close to the Brookings Institution as a think tank you could trust not to deliberately lie to you. Now it has fallen very deeply into the pit indeed”.*
