---
title: "The Doomsday Cult Takes a Bath, II"
date: "2005-10-08"
categories: ["Economics"]
---

[Jay Hancock](http://www.baltimoresun.com/business/investing/bal-bz.hancock05oct05,1,1277729.column?ctrack=1&cset=true "Jay Hancock") on Warren Buffett as currency speculator:

Often as not recently, the world’s foremost dollar doubter has been waking up to find the greenback gaining in value, shaming its critics and costing him and his shareholders millions…

Not long after boss Buffett decided he was not just a stock-picker but an applied macroeconomist, competent to bet on global fund flows, Berkshire began lagging behind the stock market. Last month, Berkshire shares hit their lowest point in almost two years, although the drop is partly connected to anticipated costs from hurricane-insurance claims.

But from January through June of this year, Berkshire showed paper losses of nearly \$1 billion on currency bets. The dollar fell a bit over the first part of summer but regained ground in September, so Buffett may show another loss for the third quarter.\

Even the [NYT](http://www.trendfollowing.com/whitepaper/costly-choices.pdf "NYT") knows a dud trade when it sees one:

*Investors in funds holding bonds of intermediate and longer maturities did better; those who bought the conventional wisdom missed out.*

(hat tip: [Michael Covel](http://www.michaelcovel.com/archives/000546.html "Michael Covel"))
