---
title: "The Non-Free Market Case for VSU: Why Worse is Better"
date: "2005-09-01"
categories: ["Economics"]
---

As an undergraduate back in 1987, I was one of several contributors to a book published by John Hyde’s Australian Institute for Public Policy, *Compulsory Students Unions: Australia’s Forgotten Closed Shop*.  Other contributors were Michael Danby, now a federal Labor member of the House of Representatives and Mark Trowell, now better known for his role in the Shapelle Corby case.  The introduction was written by a young barrister by the name of Peter Costello.  My chapter argued for the use of federal financial powers by a future Liberal government to coerce universities into adopting voluntary student unionism, on the grounds that the right of individuals not to be coerced into membership of student associations trumped the rights of state governments and university autonomy.  The book and some of its authors were instrumental in having these policy prescriptions written into federal Liberal Party policy (and now, to a lesser extent, Labor Party policy), so I feel some responsibility for the policy the federal government is now following to make student unionism voluntary.

It was always recognised that if universities were to bundle student union fees with tuition fees within the context of a market system for provision of higher education, then the whole issue would simply go away.  This is why VSU was an issue in Australia and the UK, where tuition was free, but not in the US.  The institution of compulsory student unionism has always been a function of the funding model for higher education. 

1987 was also a pivotal year for this funding model.  As Andrew Norton points out in his paper [The Free Market Case Against Voluntary Student Unionism](http://www.cis.org.au/Media/releases/releases%202005/M310805.htm "The Free Market Case Against Voluntary Student Unionism"), 1987 was the first year in which full-fee paying overseas students were enrolled in Australian universities and the first year in which the federal government started levying charges for higher education.  Andrew argues that the debate over student unionism has not changed to reflect these realities and the government’s VSU legislation, when coupled with the price caps on the student contribution amounts for Commonwealth funded students, reduces the flexibility of universities to charge fees and to compete on the bundle of services they offer to students.  In Andrew’s view, VSU is just another form of price control in the market for higher education, moving us away from a more flexible funding model for higher education. 

I agree with Andrew’s analysis and would support his recommendation that greater flexibility on fees is the solution, not only to the problem of student unionism, but for the problems with Australian higher education more generally.  Andrew argues, rightly in my view, that the VSU legislation will make conditions at Australian universities even worse.  The likely outcome is that universities are forced to assume direct budgetary responsibility for some student services.  This will come at the expense of other university activities, although once this funding becomes internally contestable, it should also force universities to clean-up student unions, which is a desirable outcome. 

Where I finally part company with Andrew is over whether this situation is conducive to further reform.  I think it is, because it highlights the absurdities of price controls in general.  As we use to say about student unions, ‘worse is better’ if it helps build the case for reform.  Needless to say, this would be an unintended consequence of the government’s VSU policy, but I think ultimately a desirable one, because it will bring forward the acute financial crisis that will ultimately bring an end to price controls.  Andrew argues that this is ‘the slowest and most painful’ route to reform, but I would argue that it is in fact the fastest.
