---
title: "The May Budget and the Future Fund: Attack of the Stone"
date: "2005-05-02"
categories: ["Economics"]
---

Former Treasury Secretary [John Stone](http://www.theaustralian.news.com.au/common/story_page/0,5744,15145043%255E7583,00.html "John Stone") is unimpressed with the likely content of the May Budget and the Future Fund:

Can it really be that, apart from new spending on its welfare reforms, the Government is simply proposing to hang on to these huge surpluses quite deliberately? To lend some verisimilitude to this otherwise indefensible policy, it has devised a so-called future fund, into which it will pay these surpluses (plus most of the proceeds from Telstra and other future asset sales) to fund, over time, the present large public service superannuation accounts deficit.

It has always been hard to take the future-fund notion seriously. When it first surfaced as a broader inter-generational fund, the secretary to the Treasury, Ken Henry, was openly, and rightly, scathing about it. Now that ministers have decided to erect this nonsense on stilts at the apex of this and future budgets, he has understandably fallen silent.

Unfortunately, it is no longer the case that major tax and spending decisions are made in the context of the annual Budget.  These decisions are increasingly being tied to the political rather than the Budget cycle.  While the conventional wisdom is that the first Budget after an election is the best from the point of view of expenditure restraint, on this occasion, the government shows little interest in reducing spending.  This effectively rules out any meaningful reduction in the overall tax burden.
