---
title: "The Institutional Economics ‘Gloom & Doom Amid Boom’ Competition!"
date: "2005-02-28"
categories: ["Economics"]
---

Australia’s [January trade balance](http://www.abs.gov.au/ausstats/abs@.nsf/5087e58f30c6bb25ca2568b60010b303/6a1a57505bea0838ca2568b7001b4599!OpenDocument "January trade balance") has come in with the second largest deficit on record, ahead of tomorrow’s Q4 current account deficit.  I notice [Trade Minister Mark Vaile](http://www.theaustralian.news.com.au/common/story_page/0,5744,12395506%255E1702,00.html "Trade Minister Mark Vaile") has continued Tim Fischer’s old trick of pointing to exports being at record levels.  The relevant measure is of course the exports share of GDP, which would decline if exports did not keep posting new records in level terms.  It takes alot of cheek to claim credit for a secular trend. 

I am running a competition to find the most overwrought commentary or reporting on the January trade balance or Q4 current account.  The person(s) submitting the winning entry shall receive a free copy of Robert Prechter’s super-bearish *Conquer the Crash* to *really* keep them lying awake at night (no jokes about second place getting two copies!)  Email or post in comments (registration required, **click on ‘register’ at top right**).  Competition will be open until Thursday, by which time interest rate hike hysteria will have taken over from current account moral panic.
