---
title: "The Productivity Commission Strikes Back"
date: "2005-11-17"
categories: ["Economics"]
---

[Assistant Productivity Commissioner Dean Parham](http://www.theaustralian.news.com.au/common/story_page/0,5744,17269339%255E7583,00.html "Assistant Commissioner Dean Parham") strikes back at those who claim there have been no gains in productivity associated with microeconomic reform:

The ABS estimates reveal that, during the productivity cycle between 1993-94 and 1998-99, Australia’s annual rate of productivity growth was about half a percentage point above any other rate recorded and was nearly one percentage point above the long-term average. Clearly that was a dramatic rise.

A second issue is whether the higher productivity growth has disappeared. The ABS estimates put the average rate of growth between the productivity peaks in 1998-99 and 2003-04 at just below the average for the past four decades. This indeed indicates that growth is down from the ‘90s highs.

But some further digging into the data provides grounds to believe that the momentum in productivity growth did not disappear entirely. The key point is that there were some once-only factors at work - the Olympics, the GST, concerns about the Y2K bug - that dragged down the average for the cycle. While not a never-to-be-repeated factor, drought also reduced the average.

Australia’s underlying productivity growth in the 2000s has come off the exceptional highs of the ‘90s. However, if the effects of the once-off factors (if not drought) are discounted, average productivity growth during the latest cycle would still have been above the long-term average.\
\
It should also be recalled that the relevant counter-factual in which there were no reforms is not being considered.  Even if Australia’s productivity performance were deemed to be poor, this does not preclude the possibility that this performance could have been even worse had no reform had taken place.
