---
title: "‘They’re Commies?!’ An Australia-China Free Trade Agreement"
date: "2005-04-20"
categories: ["Economics"]
---

In an episode of *The Simpsons* in which Homer goes to China, he expresses his disbelief that the Chinese are communists: ‘then how come I’m seeing rudimentary free markets?’  In reality, there is nothing rudimentary about them.  China’s industrial prices are overwhelmingly market-determined.  The Australian government is being criticised for conceding market economy status (MES) to China at the outset of the negotiations for an Australia-China Free Trade Agreement.  We are in fact doing ourselves a favour by making this ‘concession,’ since it potentially reduces the scope for Australian producers to take anti-dumping actions against Chinese imports.  As [Peter Gallagher](http://www.inquit.com/article/424/free-trade-agreement-with-china "Peter Gallagher") notes, Australia does not have much more to offer in terms of Chinese access to Australian markets.  MES is a small ‘price’ to pay for bringing China to the table.
