---
title: "Throw the Book at China"
date: "2005-03-15"
categories: ["Economics"]
---

The IIE’s [Fred Bergsten](http://news.ft.com/cms/s/02ac19d4-94bc-11d9-8dd3-00000e2511c8.html "Fred Bergsten") says it is time the IMF and US Treasury started enforcing the rule book on China’s manipulation of its exchange rate:

key industrial countries and international institutions have done virtually nothing to counter these blatant market distortions. Despite their professed fealty to market principles, the US and European governments have limited themselves to ineffectual consultations with the perpetrators. Massive currency interventions by the Asian countries directly violate the charter of the International Monetary Fund, which calls on members to avoid manipulating exchange rates in order “to prevent effective balance of payments adjustment”. The chief culprit is China, whose continued dollar peg has helped weaken its currency by more than 10 per cent since 2002…

The US and the Europeans, the IMF’s leading shareholders, must insist the fund start implementing its rules. This calls for the managing director to send a consultation mission to each member country suspected of “manipulation” and, if resolution is not prompt, then to refer the problem to the fund’s executive board. The list of target countries should start with China. In addition, the Treasury Department must start fulfilling its legislative requirement to label these countries, most notably China, as “currency manipulators” in its next semi-annual report to Congress on the topic due later this month.

Fred Bergsten even goes so far as to call for IMF counter-intervention in foreign exchange markets and the erection of trade barriers under WTO auspices.  This is dangerous and unnecessary in my view.  But if the IMF will not enforce its own rule book, we have to ask, what is it good for?
