---
title: "Throw the FIRB on the Bonfire"
date: "2005-02-14"
categories: ["Economics"]
---

The FT calls for a Ludwig Erhard-style bonfire of Australian controls, with the FIRB on top of pyre:

the Financial Times called on the Australian Government to overhaul its foreign investment regime and scrap the body that implements it, the Foreign Investment Review Board.

It said the usual suspects, notably “businesses that would find it convenient to have the \[WMC\] takeover stopped” had lobbied against Xstrata being cleared to have a tilt at WMC, but the real problem was Australia’s foreign investment screening system, which was “a protectionist relic” that sat badly with the Australian Government’s free market principles.

Other nations, including the United States, also screened incoming investments “but few operate regimes that are more opaque, unaccountable or open to political and bureaucratic manipulation”, the FT said, adding that the Government’s power to block deals or conditionally approve deals on “national interest” grounds relied on “a criterion so vague as to justify almost anything”.

Noting that the OECD had recently urged the Australian Government to accelerate the pace of economic reform, the newspaper concluded that “when Canberra next makes a bonfire of costly, perverse and inefficient regulations, the FIRB regime should be at the top of the pile”.

It is unfortunate that it takes a foreign newspaper to give this process some critical scrutiny.  The local press generally view the politicisation of the ownership and control of equity capital as unproblematic.  The above extract is taken from [Malcolm Maiden](http://www.smh.com.au/news/Malcolm-Maiden/Foreign-investment-rules-need-overhaul/2005/02/13/1108229855223.html?oneclick=true "Malcolm Maiden"), who also feels compelled to offer at least some defence of the indefensible.
