---
title: "Voluntary vs Compulsory Student Unionism"
date: "2005-03-17"
categories: ["Politics"]
---

[Andrew Norton](http://badanalysis.com/catallaxy/index.php?p=729 "Andrew Norton") discusses the government’s voluntary student unionism (VSU) legislation over at Catallaxy, noting that as a market liberal, he opposes the legislation as just another form of centralised control over universities (leading to the ‘Minister for Sausage Rolls,’ as he puts it in [another post](http://badanalysis.com/catallaxy/index.php?p=728 "another post")).

Andrew raises what I think has always been a central problem for the advocates of VSU, which is that if universities were to bundle student services with tuition fees, then they become just another form of largely unobjectionable product bundling that we routinely see in the provision of private sector goods and services.  Andrew’s argument is that so long as market forces are allowed to operate in relation to the provision of higher education more generally, the problem of student unions will largely resolve itself.  Universities competing on price and quality will simply not permit the excesses and inefficiencies associated with today’s student unions. 

Andrew correctly argues that compulsory student union fees in Australia are a legacy of the funding model for higher education, which up until recently prevented universities charging tuition fees, giving rise to a separate ‘amenities’ fee for student services.  This is why student unionism has never been a major issue in the US, unlike Australia and the UK.  It is not coincidental that the Australian government is now addressing this issue in the context of wider changes to the funding model for higher education.

I have a somewhat less principled position than Andrew.  Andrew has done more than anyone to highlight how far removed Australian higher education is from a market model.  In the context of a highly centralised and regulated system, I think we are permitted to play favourites with the interventions we like and don’t like.  Even bad legislation that forces universities to confront the consequences of their dependence on public funding and centralised control can serve as a catalyst for change.  As Andrew notes, the government’s legislation will move us in the right direction by forcing universities to take direct responsibility for student services.  The only unfortunate thing about the legislation is that it is symptomatic of the government’s broader agenda of centralisation across a wide range of portfolio areas that is undermining the foundations of Australia’s federal system of government.
