---
title: "VSU in Our Time"
date: "2005-12-10"
categories: ["Politics"]
---

If the [Minister](http://www.dest.gov.au/Ministers/Media/Nelson/2005/12/n2064091205.asp "Minister") is to be believed, then Australian university students are about to save up to \$162 million dollars care of the abolition of compulsory student union fees.  This also implies that universities will have to front as much as \$162 million for student services, given that most universities have already exhausted the limited discretion they have to raise extra funds from Commonwealth funded students under the current funding regime.  This should have the desirable consequence of forcing universities to assume control of student services and rationalise their operations, eliminating the inefficiencies, politicisation and rorts for which they have long been notorious.  Universities will now have decide how much of this they are willing to tolerate, rather than just passing it on to students in the form of higher amenities and other fees unrelated to tuition.

As [Andrew Norton](http://badanalysis.com/catallaxy/?p=1388 "Andrew Norton") has pointed out, this will exacerbate the problems that beset the current funding model for higher education, whereby the net operating position of universities deteriorates for every Commonwealth funded student they are unfortunate enough to enroll.  This is an argument for deregulating the market for higher education along the lines Andrew has suggested in his book, [The Unchained University](http://www.cis.org.au/Publications/summaries/PM56summ.htm "The Unchained University").  It is actually a very good argument for universities simply refusing to enroll Commonwealth funded students, de facto privatising higher education.  While not an intended outcome of the legislation, to the extent that it hastens the demise of an unsustainable funding model, it is a welcome development.
