---
title: "What Do Money and Credit Aggregates Really Tell Us?"
date: "2005-11-14"
categories: ["Economics"]
---

[Barry Ritholtz](http://bigpicture.typepad.com/comments/2005/11/the_end_of_m3_r.html "Barry Ritholtz") is on the case in relation to the Fed’s decision to discontinue publication of the M3 aggregate.  As Barry notes, this is the sort of thing that excites the tin foil hat brigade and fever-swamp Austrians, but I would suggest that there is a rather innocent explanation.  Growth rates in broad money and credit aggregates tend to be dominated by trends in financial intermediation and thus have only a very tenuous relationship with monetary policy and even a somewhat loose relationship with economic activity.  There is in fact no necessary connection between a central bank’s targeting of an official interest rate and changes in the money supply, although there is often a link in practice under current central bank operating procedures.  Even under a system of free banking in which the money supply was market-determined, a central bank could still independently target an official interest rate (see Michael Woodford’s [Interest and Prices](http://www.amazon.com/exec/obidos/tg/detail/-/0691010498/ref=ase_institutional-20/002-2137068-5696835?v=glance&s=books "Interest and Prices") for a more formal argument in this regard).

I’m much more sympathetic than most economists to the idea that money matters.  Base money arguably has a neglected role in monetary policy transmission that is independent of the official interest rate and some of that role may also be reflected in broad money aggregates.  However, it is mistake to interpret broad money and credit aggregates as being predominantly a function of exogenous monetary policy decisions.  They have a much stronger relationship with individual portfolio choices and innovations in financial technology, in other words, capitalist acts between consenting adults.  When the fever-swamp Austrians point to growth in these aggregates as being symptomatic of the supposed monetary depredations of the Fed, they are inadvertently condemning what are largely market-determined outcomes in relation to financial intermediation.
