---
title: "When Costello Attacks"
date: "2005-10-11"
categories: ["Economics"]
---

[Treasury costings](http://www.theaustralian.news.com.au/common/story_page/0,5744,16879980%255E601,00.html "Treasury costings") of Liberal MHR Malcolm Turnbull’s tax reform proposals purport to show a greater cost than allowed for in Turnbull’s discussion paper.  This analysis somewhat misses the point that meaningful tax reform *should* come at a cost to revenue.  That these costs might be greater than assumed by Turnbull is not in itself an argument against the proposed reforms.  Analysis by the [Melbourne Institute](http://www.melbourneinstitute.com/news/news/media_releases/051003%20-%20mr_taxcuts.htm "Melbourne Institute") shows an expected increase in labour force participation from the tax reform proposals of both Turnbull and Labor MHR Craig Emerson.  Increased labour force participation is meant to be a key objective of government economic policy and yet the Treasurer shows no interest in tax reforms that might be helpful in realising this goal. Hiding behind Treasury costings does not conceal the fact that Treasurer Costello remains a policy-free zone when it comes to tax.

Perhaps the biggest mistake the tax reform debate has made to date has been to assume that tax cuts can only be funded out of the surplus, rather than through net reductions in government spending, particularly the welfare churn that sees many middle-income households paying no net tax.
