---
title: "Woodside Revisited"
date: "2005-02-11"
categories: ["Economics"]
---

Ian Harper on yet another [outbreak of capital xenophobia](http://www.theaustralian.news.com.au/common/story_page/0,5744,12210558%255E7583,00.html "outbreak of capital xenophobia"):

*As in the case of the Shell/Woodside deal, the Treasurer receives no guidance from the law as to what he should consider when weighing the national interest. The Foreign Investment Review Board will offer advice based on its interpretation of the act but the Treasurer is free to decide for himself what constitutes the national interest and whether XStrata’s ownership of WMC would compromise it.*

Harper explores the contradictory logic employed in both episodes.  But the real issue here is not the merits or demerits of foreign ownership in a given case.  It is that the ownership and control of equity capital in Australia is subject to sweeping ministerial discretion, not to mention the bureaucratic discretion exercised by the ACCC.  The rule of law is almost entirely absent, which encourages rent-seeking behaviour and the misallocation of equity capital.

**UPDATE:**  The Treasurer is being praised for making the ‘right’ decision by not blocking the XStrata bid.  [Steve Lewis](http://www.theaustralian.news.com.au/common/story_page/0,5744,12223466%255E2702,00.html "Steve Lewis") says it is ‘a decision that will enhance Australia’s reputation as a haven for foreign investment,’ and that ‘…the Howard Government has sent another powerful signal that Australia is open for business.’ 

In fact, the decision sends a signal that any attempt to upset the status quo in relation to the ownership and control of Australian equity capital will have to run the gauntlet of the political process, allowing special interests to seek outcomes they could not otherwise secure in the marketplace.  Rather than praising the outcome, we should be damning the process, which has Australia running the fifth most restrictive FDI regime in the OECD.
