---
title: "From “China Shock” to deglobalisation shock: China’s WTO accession and US economic engagement 20 years on"
date: "2022-01-24"
categories: ["Economics", "Free Trade & Protectionism"]
---

I have a new report out with USSC, [From “China Shock” to deglobalisation shock: China’s WTO accession and US economic engagement 20 years on](https://www.ussc.edu.au/analysis/from-china-shock-to-deglobalisation-shock-chinas-wto-accession-and-us-economic-engagement-20-years-on).\
\
Main points are as follows:

• China’s accession to the World Trade Organization (WTO) in 2001 was an important element of its growing integration into the world economy, as well as its domestic economic reform program dating back to 1978.

• In terms of access to US markets, accession only served to make permanent access China enjoyed since the 1980s.

• “China shock” literature highlights the number of US manufacturing jobs lost to import competition from China in previous decades.

• However, a broader assessment of the economic impact of the “China shock” suggests it has been a net positive for the US economy.

• US policymakers are increasingly critical of the role of the World Trade Organization and its failure to discipline China’s trade and industrial policies, but Australian policymakers see G7-led WTO reform as a key element to push back against China’s coercive economic diplomacy.

• President Trump’s trade war and sanctions against China led Chinese elites to equally question the extent of economic interdependence with the United States. President Xi Jinping revived the Maoist concept of “self-reliance,” explicitly citing the rise of foreign unilateralism and trade protectionism as a motivation.

• Far from calling out and disciplining China’s behaviour, President Trump’s trade policies, maintained by the Biden administration, have encouraged China to double-down on its state-led development model and strategic industry and trade policy, while potential multilateral solutions and processes have been neglected and under-utilised.

• The growth in discriminatory trade measures among G20 economies since the global financial crisis in 2008 demonstrates that the problems in the multilateral trading system are not specific to China.

• A key to restoring domestic political support for US leadership of the multilateral trading system is to reframe that leadership in terms of strategic competition with China around the rules and norms of the global economy.

• Effective US leadership of the multilateral trading system would not only promote US foreign policy objectives such as prosecuting its strategic competition with China but would also discipline US domestic economic policy in ways that better serve its economic interests. It also provides a rules-based framework to manage trade frictions arising from climate mitigation under the Paris Agreement and growth in the digital economy.
