---
title: "Sanctions are the least bad option against Putin’s aggression"
date: "2022-02-28"
---

I have an op-ed in the [AFR](https://www.afr.com/world/europe/sanctions-are-the-least-bad-option-against-putin-s-aggression-20220228-p5a0df) on the effectiveness of sanctions, noting that they are often the least bad option when the alternative is escalating conflict.

The United States and other leading economies, including Australia, have instituted sweeping financial sanctions on Russian financial institutions and its central bank, adding to a raft of existing measures, some of which have been in place since the Russian annexation of Crimea in 2014.

The latest sanctions include limiting the access of selected Russian banks to the international payments system and freezing the foreign exchange reserves of the Central Bank of Russia (CBR) held offshore. The offshore assets of the Russian elite are also targeted.

The sanctions will make it difficult for Russia’s government and firms to transact internationally, deepening its diplomatic and economic isolation. However, there are carve-outs for Russia’s energy exports designed to maintain the flow of energy to Europe and the rest of the world. The Biden Administration did not want to add even higher global energy prices to existing domestic inflation pressures, leaving a major hole in the sanctions framework.

The effectiveness of the sanctions can be gauged in part by their effect on the Russian rouble and rouble-denominated asset markets. With its \$US 630 billion in foreign exchange reserves largely immobilised, the CBR will have little option but to allow the currency to collapse, likely triggering defaults on foreign currency-denominated debt.

Russia’s international isolation in response to previous acts of aggression mean that its stocks and bonds have only a small weight in international bond and equity indices. Increased geopolitical risks will loom larger for global equity and debt markets than the direct effect of sanctions on Russian asset markets.

The Russian economy will also feel the impact of export controls on high tech goods, in particular, US use of its foreign direct product rule, which gives US law extra-territorial effect in relation to foreign-produced goods incorporating US content.

Previously road-tested against Chinese tech firms such as Huawei, these sanctions will severely constrain the ability of Russian industry to support the war effort. Taiwan, a major producer and exporter of semiconductors, has not surprisingly joined the embargo.

Financial sanctions against Russia will owe their effectiveness to the dominant role of the US dollar in the world economy and international payments system.

Most international trade and cross-border investment flows are either directly or indirectly US dollar-denominated.

The US controls and regulates the international clearing of US dollar transactions. This gives US financial sanctions enormous reach. Whether they are formally part of the sanctions regime or not, financial institutions cannot afford to risk losing access to the US-regulated dollar payments system by flouting sanctions.

Economic and financial sanctions have been a go-to policy instrument for US policymakers in recent years, having been employed against Iran, Venezuela, China and Russia. The use of economic coercion as an instrument of US foreign policy reflects both the size of the US economy but also the outsized role of the US financial system in the global economy.

There is little doubt that US-led economic sanctions against Russia will impose costs on the Russian state and economy. Regrettably, the biggest effect will be on the Russian population rather than the ruling elite.

It is unlikely that sanctions themselves will dissuade Putin from continuing his aggression against Ukraine. Additional economic sanctions were almost certainly a factor in Putin’s calculations of the costs and benefits war, even if he under-estimated their severity, just as he under-estimated Ukrainian resistance.

Other countries not part of the sanctions regime will continue to transact with Russia, mostly notably including China, although even China will be wary of the far-reaching implications of US dollar dominance.

Historically, economic sanctions have only a mixed track record of success in achieving foreign policy objectives, including inducing regime change.

The US economist Gary Hufbauer reviewed the use of economic sanctions dating back to 1914. He found that sanctions achieved their objectives only around one-third of the time and typically imposed only modest costs of around two percent of gross domestic product on target countries, although the costs imposed on Russia will likely exceed that historical average.

Sanctions can also be counter-productive, inducing even greater resilience and self-reliance on the part of the targeted country, as well as immiserating populations without harming elites.

Typically, economic sanctions are employed not because they are viewed as particularly effective in achieving immediate foreign policy objectives, but because they are less costly than alternative and less attractive policy options, most obviously, resort to armed conflict.

This is a particularly salient concern in relation to Russia’s invasion of Ukraine, where direct US and NATO involvement in the conflict would risk escalation with a nuclear-armed adversary. Putin has underscored that risk by putting Russian nuclear forces at a higher level of readiness.

Economic sanctions may be limited in their effectiveness, but are still among the best of a bad set of options in responding to Russian aggression.

Dr Stephen Kirchner is director of the International Economy Program at the United States Studies Centre, University of Sydney.
