---
title: "Xi’s rightly wary of Fed tightening"
date: "2022-01-19"
categories: ["Financial Markets", "Monetary Policy"]
---

I have an op-ed in the [AFR](https://www.afr.com/policy/economy/xi-s-rightly-wary-of-fed-tightening-20220117-p59oya) explaining why Chinese President Xi Jinping will be eyeing a prospective Fed tightening warily and why the RBA will lag the Fed. Full text below the fold.

Chinese President Xi Jinping’s remarks to the World Economic Forum cautioning against a tightening in monetary policy on the part of major developed economies highlights the fragility of the Chinese economy. Xi is right to be particularly concerned about the potential for negative international spillovers from a prospective tightening in United States monetary policy.

China’s economy expanded 1.6% in the fourth quarter last year and 4% over the year, the slowest growth pace in 18 months. This was a little better than expected, but only served to fuel long-standing suspicions that the official growth data have been smoothed.

Economists at the Federal Reserve Bank of San Francisco have developed a China Cyclical Activity Tracker (China CAT) as a cross-check on the official GDP figures using indices of economic activity such as electricity, rail shipments and industrial production that are less amenable to official window-dressing than China’s national accounts.

For the third quarter of last year, the China CAT points to annualised growth of minus 5%, well below the still barely positive official growth figure. This would be only the second time the Chinese economy has seen a contraction since 2008.

China’s economy was facing significant cyclical and structural headwinds even before it had to confront the implications of the new omicron variant of COVID-19. Chinese policymakers have been trying to engineer a controlled deleveraging of the economy, including deflating its deeply troubled property sector.

The economy is also show signs of strain as a result of the Chinese Communist Party’s prioritisation of political control over economic growth and reform.

While Xi Jinping talked-up his ‘common prosperity’ agenda to the World Economic Forum, the reality of that agenda is not an ‘open, competitive and orderly market system,’ as he suggested, but arbitrary and capricious attacks by the authorities on domestic industries, firms and entrepreneurs.

With the economic pie growing more slowly, the party-state is increasingly focused on redistribution.

China is attempting to maintain a zero-COVID approach against the highly transmissible omicron variant that has quickly over-run other formerly low-COVID jurisdictions around the world, disrupting domestic supply chains and economic activity.

Against this backdrop, it should not be surprising that the People’s Bank of China started cutting policy rates last month. This week, it lowered its one-year loan rate by 10 basis points to 2.85% and its rate on seven-day reverse repurchase agreements to 2.1%.

The problem for China is that its ability to ease monetary policy is constrained by its managed exchange rate regime. Like many other emerging market economies that manage their exchange rates with reference to the US dollar, China is vulnerable to a tightening in US monetary policy.

The US Federal Open Market Committee meets next week and will deliberate on the need for a near-term tightening in monetary policy in response to a strong labour market and some of the highest inflation rates in 40 years.

Having successfully stabilised the US economy with aggressive monetary policy actions during the pandemic, the Fed has growing freedom of action to respond to inflationary pressures.

The problem for China and other emerging market economies is that the Federal Reserve’s mandate is domestically focused. Xi Jinping’s concerns, while not misplaced, are unlikely to sway policymakers abroad. China will have to rely on its own policy settings to support its troubled economy.

The prospective tightening in Fed policy also underscores Australia’s outlier status in terms of global tightening efforts.

The Reserve Bank was slow to expand its balance sheet relative to the Fed and other central banks during 2020. The Australian dollar outperformed its G10 peers through much of 2020 as a result.

Ultimately, the RBA expanded its balance sheet by a similar amount as the Fed on a relative basis, but the expansion was delivered much later.

Just as Australia lagged the world in easing monetary policy, it now lags in prospects for a tightening, which helps explain recent weakness in the Australian dollar.

The December quarter trimmed mean inflation measure released on 25 January is likely to come in at 0.8%, taking the annual rate to just shy of the mid-point of the target range at 2.4%. This will provide the RBA with sufficient justification to wind-up its bond purchase program after its February meeting.

But with the RBA facing a review after the next election, Governor Lowe will be wary of raising the cash rate too quickly.

Having positioned Australia poorly before the onset of the pandemic and lagged the rest of the world in its pandemic response, the RBA cannot afford further hawkish policy errors that might add to the criticisms from an independent expert review.

Dr Stephen Kirchner is program director, International Economy, at the United States Studies Centre, University of Sydney.
