---
title: "Beware of romanticising the legacies of Bretton Woods"
date: "2019-07-26"
---

I have an op-ed in today’s [AFR](https://www.afr.com/policy/economy/beware-of-romanticising-the-legacies-of-bretton-woods-20190725-p52al3) marking the 75th anniversary of Bretton Woods. I argue that the nostalgia for Bretton Woods is misplaced and we should instead celebrate the 1969 Oyster Bay and Burgenstock conferences that laid the intellectual groundwork for floating exchange rates.

Text below the fold.

Beware Bretton Woods nostalgia

This week marks the 75th anniversary of the Bretton Woods conference that laid the foundations for the post-World War Two international monetary system. The anniversary has occasioned nostalgia for a system of international cooperation that is increasingly under challenge, but the nostalgia is misplaced.

The Bretton Woods system of fixed exchange rates and the multilateral trading system established shortly thereafter through the General Agreement on Tariffs and Trade (GATT) were both responses to the beggar-thy-neighbour protectionism and currency wars of the 1930s that contributed to the rise of political extremism and the Second World War.

The post-war international economy prospered under US leadership and the international rules-based order it helped to establish.

While the aspirations of the Bretton Woods conference were worthy, the institutions it established, most notably the system of fixed exchange rates linked to the US dollar and gold, were not robust. Moreover, they were in fundamental tension with the multilateral trading system.

Milton Friedman recognised as early as the 1950s that the trade and macroeconomic imbalances that would build up under a system of fixed exchange rates would ultimately threaten rather than facilitate free trade.

If exchange rates could not adjust to these imbalances, then domestic inflation and economic activity would have to do the adjustment. Fixed exchange rates would become the tail that wagged the dog of the domestic economy. Politicians would resist these adjustments through controls over cross-border trade and capital flows.

The Bretton Woods conference also established the International Monetary Funds to provide assistance to countries facing pressure on their exchange rate from their balance of payments with the rest of the world.

Foreign exchange reserves, together with assistance from the IMF when needed, could in-principle act as a shock absorber in maintaining a stable foreign exchange rate against pressure to revalue. But an increasingly globalised economy inevitably generated economic shocks that overwhelmed the defences offered by foreign exchange reserves and assistance from the IMF.

As Friedman pointed out subsequently, the Bretton Woods system functioned as intended for only eight years, from 1959 to 1967. The late 1960s and early 1970s saw the system break apart and gradually replaced by a system of floating exchange rates.

Two academic conferences in 1969, organised principally by the Austrian-American economist Fritz Machlup, laid the intellectual groundwork for the shift to an international system of floating exchange rates.

While the Bretton Woods conference is still celebrated, the two conferences that contributed to the dismantling of fixed exchange rates are little known today. Yet the system of floating exchange rates they promoted arguably did more to underpin the prosperity of the global economy since the 1970s than the dysfunctional Bretton Woods system.

Australia was late to float, having resisted the change until what former Reserve Bank Governor Bob Johnston called ‘the death knock’ in December 1983. The floating exchange rate became a foundation of Australia’s prosperity since the early 1980s.

Some Bretton Woods institutions, most notably, the IMF and World Bank still persist. While floating exchange rates rendered the IMF redundant, it has managed to reinvent itself and resist pressure for reform.

Private capital markets have done more to foster economic development and address global poverty than the IMF’s sister institution, the World Bank, but it too has survived.

Bretton Woods revivalists still walk among us. President Trump’s proposed nominee to the Board of Governors of the Federal Reserve System, Judy Shelton, has advocated a return to a system of fixed exchange rates backed by gold.

Responding to one of Shelton’s Wall Street Journal op-eds in 1994, Friedman wrote ‘it would be hard to pack more error into so few words.’\
It is difficult to square Shelton’s Bretton Woods revivalism with President Trump’s desire for easier monetary policy and a weaker exchange rate, although

Shelton has shown considerable flexibility on this score since becoming a prospective Fed nominee.

President Trump’s trade war with the rest of the world is ultimately constrained by the system of floating exchange rates. China is only at risk because it maintains a managed exchange rate, but even China could devalue, if not float, to neutralise Trump’s tariffs.

The danger is that Trump then seeks to drag the US dollar into his trade war by intervening in foreign exchange markets or politicising Federal Reserve monetary policy.

Financial markets are already gearing up for the prospect of foreign exchange market intervention. The Federal Reserve has often taken a subordinate role in foreign exchange intervention operations led by the US Treasury

Friedman was dramatically vindicated by the collapse of Bretton Woods. Always alert to dangerous economic ideas, Friedman also rang the bell on Judy Shelton’s intellectual errors.

Instead of romanticising Bretton Woods, we should instead be recalling the warnings of its greatest critic.

Dr Stephen Kirchner is Program Director, Trade and Investment, United States Studies Centre at the University of Sydney.
