---
title: "Currency wars lack real weapons"
date: "2019-08-14"
---

I have a piece in the USSC’s [45th](https://www.ussc.edu.au/analysis/currency-wars-lack-real-weapons) on why so-called ‘currency wars’ are lacking in effective weapons.

Full text below the fold.

Currency wars lack real weapons

Global financial markets have been unsettled by claims China has devalued is currency against the US dollar, with the US Treasury responding by declaring China a ‘currency manipulator.’ It is not surprising that exchange rate policy has been caught-up in the US-China trade dispute. However, for all the talk of a ‘currency war,’ exchange rates are difficult to weaponise.

China has long managed its exchange rate, with varying degrees of flexibility. It was fixed with respect to the US dollar from the mid-1990s until July 2005, but has been more flexible since then.

In August 2015, China sought to introduce a more market-based approach to setting the yuan’s value, accompanied by a 2% devaluation. But Chinese policymakers were unhappy with the resulting volatility and quickly reverted to a more managed approach in January 2016.

The best gauge of whether a currency is being manipulated is the magnitude of official intervention in the foreign exchange market and the resulting change in foreign exchange reserves.

A fixed exchange rate often requires heavy intervention to maintain it against market forces, which is why the US labelled China a ‘currency manipulator’ in the 1990s, but the label has become an increasingly poor fit for China.

It is difficult to argue that China’s currency has been systematically undervalued in a manner designed to boost its exports. In recent years, China has been intervening to support the value of the yuan to stem capital flight.

China’s recent management of its exchange rate is designed to accommodate market forces while maintaining capital controls and promoting domestic economic stability.

If China enjoyed a floating exchange rate like Australia’s, there is little doubt financial markets would have taken its exchange rate lower, perhaps dramatically so, in response to the growing trade war with the US. Far from intervening to devalue the yuan, the Chinese are simply doing less to stand in the way of a market-led adjustment.

The US government has traditionally advocated flexible exchange rates because they are more consistent with free and open international trade.

But under the Trump Administration, the US has sought commitments from China that it will not allow its exchange rate to depreciate as part of any trade deal. The US is asking China to manipulate its exchange rate in US interests.

The Omnibus Trade and Competitiveness Act of 1988 provides for the US Treasury to designate countries as ‘currency manipulators.’ The criteria for manipulation are (1) a significant bilateral trade surplus with the US; (2) a material current account surplus; and (3) persistent one-sided intervention in the foreign exchange market.

In fact, the first two criteria are not necessarily inconsistent with a floating exchange rate entirely determined by market forces. Only (3) is a reliable indicator of manipulation.

While China satisfies (1), it does not satisfy (2) or (3). Having ignored its own criteria, we have every reason to believe the US Treasury acted politically in declaring China a manipulator.

Designating another country a manipulator has no implications other than requiring Treasury to enter into consultations, either bilaterally or through the International Monetary Fund.

For its part, the US effectively has no exchange rate policy so long as the Federal Reserve conducts a monetary policy focused on targeting domestic inflation independently of the Treasury and President.

The US has notionally adhered to a ‘strong dollar policy’ since 1995, but the policy was entirely rhetorical. The Trump administration has shifted this rhetoric, but the US still has no effective exchange rate policy.

While the US Treasury could intervene in foreign exchange markets, with or without the Federal Reserve, such intervention would have little lasting effect and leave the US itself vulnerable to the charge of manipulation.

The US has deep and liquid foreign exchange and capital markets that are a key economic strength, not least because they are a bulwark against attempts by the US or foreign governments to manipulate exchange rates and interest rates.

Suggestions that China might sell its holdings of US Treasuries to punish the US ignore the fact that even its massive holdings are just a drop in the bucket of US capital markets. China selling US Treasuries would just be a buying opportunity for the rest of the world.

While the Trump Administration could intervene in foreign exchange markets and seek to politicise monetary policy, attempts to set exchange rates and interest rates at odds with economic fundamentals ultimately fail.

Fixed exchange rate regimes eventually succumb to market forces. Managed exchange rates like China’s only succeed to the extent that they accommodate those forces. Floating exchange rates like Australia’s accommodate market forces in real time.

A ‘currency war’ may give rise to increase volatility in financial markets, but lacks effective weapons and won’t change underlying economic fundamentals.

Dr Stephen Kirchner is Program Director, Trade and Investment, United States Studies Centre at the University of Sydney.
