---
title: "The ‘reserve currency’ myth: The US dollar’s current and future role in the world economy"
date: "2019-11-11"
categories: ["Economics", "Financial Markets"]
---

Very long time readers of this blog will know that the future of the US dollar was much debated in these pages in the mid-2000s. I have given these ideas a systematic treatment in a new report for the United States Studies Centre, [The ‘reserve currency’ myth: The US dollar’s current and future role in the world economy](https://www.ussc.edu.au/analysis/the-reserve-currency-myth-the-us-dollars-current-and-future-role-in-the-world-economy/).

This year, the euro celebrated its 20th anniversary. At the time of its launch at the beginning of 1999, it was widely expected the euro would assume a role equal to that of the US dollar in the international monetary system. Despite some early gains, in net terms, the euro has not increased its share since its inception two decades ago.

The campaign to internationalise the RMB from 2009 has also faltered. Measures of RMB globalisation have gone nowhere since 2016 as China’s communist party has prioritised state control. The inclusion of the RMB in the IMF’s Special Drawing Rights basket was little more than a vanity project.
