---
title: "I am leaving CIS and returning to financial markets"
date: "2014-08-28"
categories: ["Centre for Independent Studies", "Economics", "Financial Markets"]
---

This is my last week at CIS. I will be returning to financial markets from whence I came back in 2008. Thanks to Greg Lindsay for giving me a platform to participate in the public policy debate over the last few years. Thanks also to those who contributed to Policy while I was editor over the last 18 months. Policy will continue under a new editor.

My new employer won’t be paying me to blog or tweet during business hours, so you will be hearing even less from me on what is already a very low frequency blog. I will still post material here from time to time and link to what I am doing when appropriate. Needless to say, nothing on this web site should be attributed to current or previous employers.

This blog has followed me around in various roles since 2003, back when economics blogs were a rarity. The economics blogosphere is now a very over-crowded space. Since 2009, Scott Sumner has been saying much of what I wanted to say, only better. It is more efficient for me to send him a link and have him blog on it than to do it myself. So go read him if you don’t already.
