---
title: "Nina Munk on Jeff Sachs"
date: "2014-01-30"
categories: ["Economics"]
---

Nina Munk’s summation in her [Econtalk](http://www.econtalk.org/archives/2014/01/nina_munk_on_po.html#more) interview is not at all surprising, but no less devastating for that:

> *they were now really living in a kind of squalor that I hadn’t seen on my first visit. Their huts were jammed together; they were patched with those horrible polyurethane bags that one sees all over Africa, covered in sort of burlap bags and sort of plastic tarps from the UN refugee service. There were streams of slop that were going down between these tightly packed huts. And the latrines had overflowed or were clogged. And no one was able to agree on whose job it was to maintain them. And there were ditches piled high with garbage. And it was just—it made my heart just sink. And I thought to myself: You know what, Jeffrey Sachs? You came to this village once. That’s not true. I think he came a second time in a helicopter the second time. He’s been to that village twice. And on both times he was received like a welcoming monarchy. All the people come out to greet him, and the local officials come out in their best Sunday suit. And everyone’s out there giving grand speeches on a microphone, and they sing songs and they dance for him and they thank him and they praise him and they pray for him. But you know, when you leave and you go back home to your townhouse on the upper west side of Manhattan and you return back to your comforts, you know, these people are left really with nothing. With nothing. And arguably they are left with something that is more dismal and worse than it was before he tried to impose his ideas of progress on them.*
