---
title: "Scapegoating Foreigners for Domestic Policy Failures in Housing"
date: "2014-03-20"
categories: ["Economics", "Foreign Investment", "Free Trade & Protectionism"]
---

I have an op-ed in the [SMH](http://www.smh.com.au/comment/dont-blame-foreigners-for-rising-house-prices-20140319-352nn.html) on foreign direct investment in the Australian housing market noting that foreigners are being used as scapegoats for what are really domestic policy failures. The House Economics Committee will now inquire into the issue:

> According to committee chair Kelly O’Dwyer, the inquiry will consider whether the current restrictions on foreign investment in residential real estate serve to increase supply, as is their stated intention, or raise prices.
>
> This is rather like asking whether foreign tourists increase the production of goods and services or raise consumer prices. The answer depends on how flexibly Australian producers can accommodate changes in foreign as well as local demand through increased output.
>
> It is pointless blaming foreigners for inflexible elements on the supply-side of the Australian economy. For that, we should blame local politicians.

Ironically, the inquiry could result in a bringing forward of foreign demand in anticipation of increased controls on FDI in residential real estate. The inquiry should recommend the abolition of the existing controls on FDI in real estate. My guess is the Committee will instead recommend extra conditions be attached to FIRB approvals, along with some additional quantitative controls.

I am also quoted in this story in today’s [AFR](http://www.afr.com/p/national/tomato_company_awaits_anti_dumping_j7d80S5PsRO8385wKhro2K) on anti-dumping measures on imported tomatoes.
